### ISSUE TITLE
JENKINS: deploying war file through tomcat getting 

### ISSUE THREAD

**Issue by chittalalk** [QT-DevOps/DevOpsIssues#10]
Hii ,
  Iam trying to deploy the war file through jenkins job.But unfortunatly iam getting error like "Host key verification failed." in downstream.
I have enabled SSH authentication from jenkins m/c to tomcat server.

![Uploading build_script.PNG…]()
![down_stream error](https://user-images.githubusercontent.com/39190912/40575813-6f660ff8-6109-11e8-9206-51da7f5cbced.PNG)
![upstream_build](https://user-images.githubusercontent.com/39190912/40575817-88bee0e2-6109-11e8-92cd-9307b2564f8e.PNG)

Could you please help me for the same 
Thanks!!

**Comment by samjoel777** [comment]
Host key verification Failed
1)vi /etc/ssh/sshd_config
  PasswordAuthentication yes
2)ssh-keygen
ssh-copy-id jenkins@<tomcat ip/dns>
ssh jenkins@<tomcat ip/dns>
3)give jenkins user full permissions
4)first see manually if you're able to login

**Comment by chittalalk** [comment]
Thanks for your reply.
yes! i have logged into the remote system through SSH mannually.Even though its getting error

**Comment by samjoel777** [comment]
check host-key that you have generated and sent(i.e public and private),they should match

**Comment by sanjaysureshmv** [comment]
try to manually copy the public key generated by the jenkins user(master) in .ssh/id_rsa.pub to the tomcat servers authorized_keys file in .ssh directory of jenkins user. if file is not there then create the file

**Comment by samjoel777** [comment]
use private_ip it works better for tomcat not public _ip
