### ISSUE TITLE
NOPASSWD is not working for ansible user in both linux flavours

### ISSUE THREAD

**Issue by Somansh1993** [QT-DevOps/DevOpsIssues#100]
Redhat
## Read drop-in files from /etc/sudoers.d (the # here does not mean a comment)
#includedir /etc/sudoers.d
ec2-user        ALL=(ALL)       NOPASSWD: ALL
ansible         ALL=(ALL)       NOPASSWD: ALL

Ubuntu

# Members of the admin group may gain root privileges
%admin ALL=(ALL) ALL

# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL
ansible ALL=(ALL:ALL) NOPASSWD: ALL
# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d

I saved this configuration but still it is asking for passwd and i hv to enter in both linux flavours

**Comment by raviops100** [comment]
Hi Somansh,

Ansible installation on Ubuntu flavour machine in sudeors file 

Allow members of group sudo to execute any command

ansible ALL=(ALL:ALL) NOPASSWD: ALL

this is entry u have done i guess after NOPASSWD: space is not required between : and ALL

you just enter with outspace like below 

ansible ALL=(ALL:ALL) NOPASSWD:ALL

if u still face the issue please follow below steps in ubuntu 16.04

ANSBILE INSTALLATION 16.04
=================

1. https://docs.ansible.com/ansible/2.3/intro_installation.html

ansible --version
python --version

2. sudo vim /etc/ssh/sshd_config
   go to above file line no 51 
   passwordauthentication bydefult no u need to type yes 
   then execute below command
      
   sudo service sshd restart

3. adduser ansible

4. add ansible user to sudo group
   
  from == rootuser == visudo

in allow members group

ansible ALL=(ALL:ALL) NOPASSWD:ALL

GO TO ANSIBLE USER check sudo apt-get install it should work
5.ssh-keygen
6.ssh-copyid

**Comment by devopsawsazure** [comment]
Have you done the service sshd restart?,
Can you please keep a snapshot of the error so it can be helpful

**Comment by Somansh1993** [comment]
How does it related to sshd service?

I configuring in sudoers file only so it should work idlely. I ddint make
any changes in sshd configuration file.

Apart from that i try that too but still it is asking password for both
flaovurs redhat and ubuntu.

I am using Aws ec2 t2.micro.

**Comment by Somansh1993** [comment]
Hi Team,

Please help getting this error while copying ssh-copy -id command

[ansible@ip-172-31-44-93 .ssh]$ ssh-copy-id ansible@localhost
/bin/ssh-copy-id: INFO: Source of key(s) to be installed:
"/home/ansible/.ssh/id_rsa.pub"
/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter
out any that are already installed
/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are
prompted now it is to install the new keys
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

**Comment by raviops100** [comment]
ssh-copy-id uses the user's password to connect to the host.

Log in as root
Edit ssh config: 
sudo nano /etc/ssh/sshd_config
Change this line:
PasswordAuthentication no
to
PasswordAuthentication yes
Restart daemon: 
sudo systemctl restart sshd

Do ssh-copy-id:
ssh-copy-id someuser@<my-ip>

Revert changes to ssh_config if you are security conscious and restart daemon.

**Comment by mani5a3** [comment]
is dis resolved ?

**Comment by Somansh1993** [comment]
Hi,

Ya now it's resolved.
Thank you

**Comment by mani5a3** [comment]
closed
