### ISSUE TITLE
 Asking to enter password after running Knife bootstrap command in Chef

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [QT-DevOps/DevOpsIssues#101]
After running the command Knife bootstrap in (PS) chef, it is asking to enter password, says authentication failed, though knife node list is showing. Please let me know where am i wrong ?

**Comment by raviops100** [comment]
Plaese post what is the knife bootstrap command you have build ????

**Comment by venkatmamillapalli** [comment]
knife bootstrap 172.31.27.166 -i XXX.pem -N ec2-18-222-222-61.us-east-2.compute.amazonaws.com --sudo -x ubuntu
run this

**Comment by mani5a3** [comment]
is dis resolved?

**Comment by vallabhabairu** [comment]
Please mark the yes in PasswordAutheication file  /etc/ssh/sshd.conf file.Restart the sshd service.Change the User name password .Whenever iif any password ask give the password of the user 

Other wise we have an option called  P password for knife command use that .

**Comment by sandeepmchary** [comment]
Hi
where is the pem file ?
is it in the same location where you are executing the command ? 
if not place the pem file in the same folder where you are executing the command then try it once

**Comment by SajidAliKhanMohammed** [comment]
Hi Friends, repeated the same things from the scratch and this time got it successfully. Thanks all..

**Comment by mani5a3** [comment]
closed

**Comment by SajidAliKhanMohammed** [comment]
Thanks all friends for the help..
