### ISSUE TITLE
Did not get required files in chef

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [QT-DevOps/DevOpsIssues#102]
On creating a cookbook in chef for the first time, i didn't get the following : 
1) .delivery
2) .git
3) .gitignore
instead got one excess notepad file. Please let me know what went wrong ?

**Comment by lingaswamy123** [comment]
1)When you create a cookbook you won't get .git folder when you initiates your folder to be git repository then you will get .git folder.
2).delivery and .gitignore are automatic files when you create a cookbook .
3)create one more cookbook and check again

**Comment by SajidAliKhanMohammed** [comment]
ok, sure, thanks friend..

**Comment by SajidAliKhanMohammed** [comment]
Thanks for the information Lingaswamy.
