### ISSUE TITLE
Services not found

### ISSUE THREAD

**Issue by kuncham405** [QT-DevOps/DevOpsIssues#103]
Hi Sir,
Apache2 services is not starting getting below error, can you please help on this.

![image](https://user-images.githubusercontent.com/42239024/44002680-40786a04-9e64-11e8-9ee3-ed7744167283.png)

**Comment by kuncham405** [comment]
please find the logs for the above issue.

![image](https://user-images.githubusercontent.com/42239024/44002714-d63abff6-9e64-11e8-861d-c400b7189a9f.png)

**Comment by lingaswamy123** [comment]
remove the package and reinstall apche2 again
commands are: apt-get purge apache2 -y
                         apt-get install apache2 -y
                         service apache2 start

**Comment by mani5a3** [comment]
please add configuration to specific node. i think u didn't not added run list to node

**Comment by kuncham405** [comment]
Thanks for the information, if I not added the runlist to the node,  it
will show that runlist is empty. I have added the runlist to the node, let
me check on first comment reinstall apache2.
