### ISSUE TITLE
Error in Kubernetes

### ISSUE THREAD

**Issue by sainathareddy** [QT-DevOps/DevOpsIssues#104]
when i execute
kubectl get nodes  i  am getting the error saying
The connection to the server localhost:8080 was refused - did you specify the right host or port?
i enabled the port 8080

**Comment by raviops100** [comment]
Please run below commands:

mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

**Comment by raviops100** [comment]
Hi Sainath,

is it working now ???
