### ISSUE TITLE
Unable to login into AWS ec2  ubuntu instance from Git bash

### ISSUE THREAD

**Issue by revathi-muthana123** [QT-DevOps/DevOpsIssues#106]
Hi,

    I am trying to connect with ssh key in git bash below error occured.

 key : ssh -i "xxxx.pem" ubuntu@ec2-35-170-182-139.compute-1.amazonaws.com
 error : ssh: connect to host ec2-35-170-182-139.compute-1.amazonaws.com port 22: Connection timed out

**Comment by mani5a3** [comment]
please make sure that  chmod 400 pemfile and try to connect and some times due low network it will show like that and also please check security group too

**Comment by vallabhabairu** [comment]
open the git bash ,where the pem file exist

**Comment by revathi-muthana123** [comment]
thanks for your support, i have done all these things but still same issue.

**Comment by vallabhabairu** [comment]
Did you  opened port 22 for ec2 machine

**Comment by revathi-muthana123** [comment]
My default vpc issue, now it's resolved, thank you .
