### ISSUE TITLE
Error while executing chef-client command

### ISSUE THREAD

**Issue by venkatmamillapalli** [QT-DevOps/DevOpsIssues#107]
Hi i wrote a cook book in workstation.and i uploaded it
![image](https://user-images.githubusercontent.com/41816043/44032092-c5962432-9f23-11e8-94ea-05e9ea67e0b6.png)

After i executing chef-client command in node and iam getting error like this

/
![chef error](https://user-images.githubusercontent.com/41816043/44032168-fcb21a20-9f23-11e8-8ea6-1c8c24c23210.png)

**Comment by vallabhabairu** [comment]
Have you copied chef.pem file in user home directory

**Comment by Jagadeeshw** [comment]
execute as : sudo chef-client
 or login as root : (sudo-i)

**Comment by venkatmamillapalli** [comment]
yes my .pem file is in same location

**Comment by venkatmamillapalli** [comment]
![image](https://user-images.githubusercontent.com/41816043/44093707-e8d31544-9ff1-11e8-967b-16374414726b.png)

**Comment by vallabhabairu** [comment]
Pem file aslo suppose to be in Ec2 machine aslo /home/Ubuntu. Please place the file .

**Comment by shaikkhajaibrahim** [comment]
Please remove node & perform bootstrap
