### ISSUE TITLE
Using CLI in AWS how do we associate Network ACL a with particular subnet?

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#108]
Hi,

In creating the Azure N Tier reference architecture on AWS ussing CLI, we need to create 2 NACLs to restrict access into the Business and Data Tier machines. After creating 2 NACLs, how do we associate each NACL with each of the Business and Data subnets separately?
AWS docs suggests to replace network acl association with example:-
aws ec2 replace-network-acl-association --association-id aclassoc-e5b95c8c --network-acl-id acl-00f0c82ebc7a44122

I would like to know  what is this association-id and where can I get this id from.

Please help out.

**Comment by raviops100** [comment]
Hi Ramesh,

By default when you create a VPC it also creates a NACL associated with that VPC. 
When you create a subnet as by default it associates itself to the default NACL that was created during the VPC setup and gives itself an aclassoc-id.

Coming to your AWS CLI Command:

aws ec2 replace-network-acl-association --association-id aclassoc-e5b95c8c --network-acl-id acl-00f0c82ebc7a44122

Where aclassoc-e5b95c8c = Default Subnet ACL Assocation ID that was created during subnet creation and acl-00f0c82ebc7a44122 = your own NACL ID that you created.

This will then replace the acl association ID of aclassoc-e5b95c8c with a new one relating to your own NACL.

Hope this will work

**Comment by rameshm78** [comment]
Thanks Ravi, I just copy - pasted this example from amazon docs.

Please tell me, from where I can find the Default Subnet ACL Assocation ID that was created during subnet creation. I'm unable to find it anywhere; maybe I have not looked at the correct place.
