### ISSUE TITLE
ssh permission denied

### ISSUE THREAD

**Issue by saikishore44** [QT-DevOps/DevOpsIssues#109]
1. aws ec2 create-key-pair --key-name MyKeyPair --query 'KeyMaterial' --output text > MyKeyPair.pem
2. aws ec2 run-instances --image-id ami-5e8bb23b --count 1 --instance-type t2.micro --key-name 
   mykeypair 
3. ssh -i "MyKeyPair.pem" ubuntu@ec2-52-15-138-132.us-east-2.compute.amazonaws.com
 error:     
     Load key "MyKeyPair.pem": invalid format
     ubuntu@ec2-52-15-138-132.us-east-2.compute.amazonaws.com: Permission denied (publickey).

**Comment by revathi-muthana123** [comment]
Hi,
Same Error:
ssh: connect to host ec2-54-214-61-191.us-west-2.compute.amazonaws.com port 22: Connection timed out

**Comment by raviops100** [comment]
Hi SaiKishore,

for Windows PowerShell, the > file redirection defaults to UTF-8 encoding, which cannot be used with some SSH clients. 
So, you must explicitly specify ASCII encoding in the out-file command.

your creating key-pair command should be like this below

before executing below command just change key pair name to other name. becoz i guess in your machine having MyKeyPair.pem file already

aws ec2 create-key-pair --key-name MyKeyPair --query 'KeyMaterial' --output text | out-file -encoding ascii -filepath MyKeyPair.pem

after this you can execute run-instance command  

it should work

**Comment by sravyamaridi** [comment]
THANKS
