### ISSUE TITLE
Jenkins Installation on ec2

### ISSUE THREAD

**Issue by surajp491** [QT-DevOps/DevOpsIssues#11]
Hai ,

I have low configuration on my system so, i am planning to install jenkins on ec2 for that please let me know how to see proper billing cost for instance types on ec2  and which instance type should i choose  to complete the assignments on jenkins.

**Comment by vijaybhaskarreddyy** [comment]
Use Ec2 calc & 8GB RAM i.e t2.large is sufficient.

**Comment by samjoel777** [comment]
https://aws.amazon.com/ec2/pricing/on-demand/
i suggest t2.medium 
for me worked well
high speed internet connectivity is necessary
