### ISSUE TITLE
Public DNS name

### ISSUE THREAD

**Issue by Sravan-jk** [QT-DevOps/DevOpsIssues#110]
Hello all,

When i created an instance in public subnet, its not having the public DNS/IP for it

Can anyone help out with a reason for it

**Comment by raviops100** [comment]
Hi Sravan,

Please follow below steps

1. In AWS CONSOLE GO TO SERVICES

2. CLICK ON VPC

3. CLICK ON YOUR VPCS  SELECT YOUR VPC

4. select your VPC connected to your EC2 instance

5. IN VPC GO TO ACTIONS TAB ND SELECT 

6.  EDIT DNS HOSTNAMES ---> CHANGE DNS HOSTNAMES: TO YES

**Comment by Sravan-jk** [comment]
Hi Ravi,

Thanks for it 
I created 2 subnets and in public subnet i created an instance.
Please check the screenshots and let me know your thoughts on it
and I changed DNS Hostname to Yes
i am guessing if there anyway to assign public ip/dns to the instance while giving the subnet (Just like in UI)

Thanks
![screenshot 33](https://user-images.githubusercontent.com/42171871/44216593-e5f2ec80-a192-11e8-9dd3-295b463eacec.png)
![screenshot 34](https://user-images.githubusercontent.com/42171871/44216594-e5f2ec80-a192-11e8-82d9-eb5dae45a164.png)
![screenshot 35](https://user-images.githubusercontent.com/42171871/44216595-e5f2ec80-a192-11e8-9351-71c689b4c0c4.png)
![screenshot 36](https://user-images.githubusercontent.com/42171871/44216596-e68b8300-a192-11e8-9797-816347607036.png)

**Comment by revathi-muthana123** [comment]
Hi Sravan,
 Are you worrying about public-ip address  or public-DNS host Name?

for Public-IP:
-------------
while creating ec2 instance 
go to configure instance page, then
Enable :- Auto-assign Public IP 

for DNS Host:
--------------
Yes :- Edit DNS Host name --> from your VPC

**Comment by Sravan-jk** [comment]
Hi Revathi,

can you let me if there is anyway that we can do it in CLI

Is so please suggest

**Comment by shaikkhajaibrahim** [comment]
Please google
