### ISSUE TITLE
Chef ec2 driver instance

### ISSUE THREAD

**Issue by pganapathirao** [QT-DevOps/DevOpsIssues#111]
While running of "kitchen create" command following errors are writing.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Both F:/Devops/CHEF/chef-repo/cookbooks/tomcat-trails/kitchen.yml and F:/Devops/CHEF/chef-repo/cookbooks
/tomcat-trails/.kitchen.yml found. Please use the un-dotted variant: F:/Devops/CHEF/chef-repo/cookbooks/tomcat-trails/ki
tchen.yml.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
[kitchen.log](https://github.com/QT-DevOps/DevOpsIssues/files/2299440/kitchen.log)

**Comment by raviops100** [comment]
Hi ganapathirao,

Can you please post kitchen.yml you have written

**Comment by pganapathirao** [comment]
---
driver:
  name: ec2
  aws_ssh_key_id: chef
  security_group_ids: ["sg-067d51782ac228fbc"]
  region: us-east-2
  require_chef_omnibus: true
  instance_type: t2.micro
  associate_public_ip: true
  shared_credentials_profile: Ganesh

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-7d132e18
    transport:
      ssh_key: chef.pem  
      username: ubuntu
  #- name: centos-7

suites:
  - name: default
    run_list:
      - recipe[tomcat-trails::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

**Comment by shaikkhajaibrahim** [comment]
We have ran into same problem in the class. Please dont execute any kitchen init commands.

Directly modify the .kitchen.yml with suitable fields. and execute kitchen converge

**Comment by pganapathirao** [comment]
Here the problem is,  My OS version is Windows7. I tried in Windows 2012 R2. Kitchen run successfully without any issues.
