### ISSUE TITLE
syncronize the clock on your host

### ISSUE THREAD

**Issue by satyakuppala** [QT-DevOps/DevOpsIssues#112]
when i am trying to bootstrap i am getting the below error
![capture11](https://user-images.githubusercontent.com/31399927/44301530-33f42580-a336-11e8-90b9-b3db6f9fda69.JPG)

**Comment by raviops100** [comment]
Hi Satya,
Can you please restart the both local machine where chef-server(Hosted-chef) installed and also EC2 virtual machine CHEF-NODE you have configured
and execute the same  knife boot strap command again

**Comment by raviops100** [comment]
is this resolved ???

**Comment by raviops100** [comment]
is this resloved

**Comment by shakirmir** [comment]
hi satya ,
 change your local machine time zone and  try again boot strap ,i am sending u the screenshot check below

![image](https://user-images.githubusercontent.com/39324287/44943260-03ee5d00-ade1-11e8-9a01-2fe484a22c69.png)
