### ISSUE TITLE
when i exicute my playbook i faced a problem ssh password

### ISSUE THREAD

**Issue by ajs777** [QT-DevOps/DevOpsIssues#113]
i dont know ssh password please give me a suggestion 
![screenshot 30](https://user-images.githubusercontent.com/37798362/44389606-e8fe2c00-a548-11e8-9107-84bd575331ea.png)

**Comment by lingaswamy123** [comment]
1)first enable PasswordAuthentication to yes in /etc/ssh/sshd_config file and restart ssh
2)second create pub and pvt keys in ansible control server with the command: ssh-keygen
3)copy your pub key to nodes with the command: ssh-copy-id ansible@pvtdnsname

**Comment by ajs777** [comment]
hi
lingaswamy garu
firstly thank u for u r rply

they all are i did it.. but i dnt  know why it's come

**Comment by raviops100** [comment]
Hi,
can you please recheck Ansible installation steps
and specially
entry in sudoer's file should be  like this below(with out any spell mistake and space) 
in allow members group
ansible ALL=(ALL:ALL) NOPASSWD:ALL
why becoz For the user, use ssh keys to avoid the user password prompt

**Comment by ajs777** [comment]
thank u ravi garu
