### ISSUE TITLE
undefined method `platform' for #<Chef

### ISSUE THREAD

**Issue by prakkug** [QT-DevOps/DevOpsIssues#114]
Hi, 
while executing sudo chef-client for Apache-comm cookbook, I am getting the below error, I tired platform-version as well,but it couldn't resolve the issue...
Details :+1: 
System Info:
------------
chef_version=14.3.37
platform=ubuntu
platform_version=16.04
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef/bin/chef-client

Running handlers:
[2018-08-21T19:55:20+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-08-21T19:55:20+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 01 seconds
[2018-08-21T19:55:20+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-08-21T19:55:20+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-08-21T19:55:20+00:00] FATAL: NoMethodError: undefined method `platform' for #<Chef::Node::Attribute:0x00000000050901f0>

**Comment by raviops100** [comment]
HI ,

it seems it is a syntax error. It might be missing the default.rb file

**Comment by shaikkhajaibrahim** [comment]
Share your cookbook

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by prakkug** [comment]
Please see the bellow code. Thank You. 
Attributes(default.rb)
default['apache-install']['package_git'] = 'git'
default['apache-install']['file_path'] = '/var/www/html/welcome.html'

if node[platform] == 'ubuntu'
  default['apache-install']['package_apache'] = 'apache2'
elsif node[platform] == 'redhat'
  default['apache-install']['package_apache'] = 'httpd'
end
--------------------------------------------------------------------
recipes(apache_cmn,rb)
#
# Cookbook:: apache-install
# Recipe:: apache_cmn
#
# Copyright:: 2018, The Authors, All Rights Reserved.
package node['apache-install']['package_git'] do
  action :install
end

file node['apache-install']['file_path'] do
  content 'Welcome to Chef --- this is done by ruby !'
  action :create
end

package node['apache-install']['package_apache'] do
  action [:enable, :start]
end

service node['apache-install']['package_apache'] do
  action :restart
end
--------------------------------------------------
recipes(default,rb)
#
# Cookbook:: apache-install
# Recipe:: default
#
# Copyright:: 2018, The Authors, All Rights Reserved.
# genaric package to install git for both ubuntu and redhat

package node['apache-install']['package_git'] do
  action :install
end

Regards, 
Prakash

**Comment by shaikkhajaibrahim** [comment]
Please upload the cookbook as zip & raise new issue with error
