### ISSUE TITLE
Unable to login to EC2 instance with key created using cli

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#115]
Hi,

I am unable to connect to an EC2 instance whose key has been created using CLI. I have tried creating the key and the EC2 instance twice but it always fails saying Load key invalid format.

![image](https://user-images.githubusercontent.com/40449948/44455137-ecfa7e80-a61a-11e8-9f93-f069be065a46.png)

![image](https://user-images.githubusercontent.com/40449948/44455179-08658980-a61b-11e8-9196-1dcc459b5171.png)

However it works fine when I use a console created key.
Is there anything wrong with my create key command?
PS E:\Keys> aws ec2 create-key-pair --key-name CliKey --output text --query KeyMaterial > CliKey.pem

Kindly let me know where the issue is.

Regards
Ramesh

**Comment by Imalli5253** [comment]
Note that for Windows PowerShell, the > file redirection defaults to UTF-8 encoding, which cannot be used with some SSH clients. 
So, you must explicitly specify ASCII encoding in the out-file command.

---> **$aws ec2 create-key-pair --key-name MyKeyPair --query 'KeyMaterial' --output text | out-file -encoding ascii -filepath MyKeyPair.pem**

Ex:   aws ec2 create-key-pair --key-name CliKey --output text --query KeyMaterial | out-file -encoding ascii -filepath CliKey.pem

(or)

If you want to login using the key which is created in the format of **utf-8**( using the above command that you've used) you need to convert it into **ascii**.

Ex :  
step 1   **$aws ec2 create-key-pair --key-name CliKey --output text --query KeyMaterial > CliKey.pem**

step 2  **$ cat .\CliKey2.pem | out-file -encoding ascii -filepath E:\Aws@keys\CliKey2.pem**

note: Don't convert the file within the same directory. Specify different path for output( **-filepath** )

**Comment by rameshm78** [comment]
Thanks a lot Malli. 
Exactly what I suspected. 
I will close this issue as soon as I get a chance to verify this.
Currently struggling with issue #123
