### ISSUE TITLE
Unable to login to Jenkins

### ISSUE THREAD

**Issue by vinaysandela** [QT-DevOps/DevOpsIssues#117]
I have created ubuntu 14.04 machine from AWS. Followed instructions from the /JENKINS-INSTALLATION-STEPS-ON-UBUNTU.pdf document. 

Installed  Oracle java 8 
Installed Maven
Installed GIT
Installed Jenkins.
When trying IP:8080 from browser, **Jenkins page is not opening**

Tried these- 
Opened the port 8080 - _sudo ufw allow 8080_
Enbled ufw  - _sudo ufw enable_
Status of ufw - 
ubuntu@ip-172-31-47-169:~$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
8080                       ALLOW       Anywhere
8080 (v6)                  ALLOW       Anywhere (v6)

Attached are the screenshots - 
![aws_securitygroup](https://user-images.githubusercontent.com/22040836/44491689-11148a80-a630-11e8-9ede-05f6d5ec0c2e.jpg)
![jenkinserror](https://user-images.githubusercontent.com/22040836/44491690-11148a80-a630-11e8-84c5-203968d62dc0.jpg)

**Comment by vinaysandela** [comment]
I have added All Traffic in the Security Group and the Jenkins page is opened. But, when I closed the server and trying to login again - getting Timeout error. Can you please check - 

Public DNS: ec2-34-203-219-240.compute-1.amazonaws.com

**Comment by Imalli5253** [comment]
Have you tried with **public IP**. Because it seems you are trying to access it by **Private Ip**(http://172.31.47.189:8080)
Try to access with **Public Ip**

Ex: http://ec2-34-203-219-240.compute-1.amazonaws.com:8080  (I tried this It is working fine)
     http://[public Ip]:8080

![image](https://user-images.githubusercontent.com/20962752/44500477-3f34b180-a6a6-11e8-80ac-0d5f52a8e827.png)

**Comment by vinaysandela** [comment]
Yes, After changing the security group to allow "All Traffic", I am able to get the Jenkins Page. But I am unable to login to the server - 
Gitbash - _ssh -i "Jenkins.pem" ubuntu@ec2-34-203-219-240.compute-1.amazonaws.com_
Getting Timeout Error.

**Comment by Imalli5253** [comment]
share the security group inbound rules..

**Comment by vinaysandela** [comment]
Sure, Please see the attached - I was trying different options

![securitygroup](https://user-images.githubusercontent.com/22040836/44537326-16231980-a6c4-11e8-9607-300c102de596.JPG)

**Comment by raviops100** [comment]
Hi Vinay,
Can you please try in security groups SSH port 22 default it is available and to access jenkins try to open
ALL TRAFFIC  source should 0.0.0.0/0 i mean any where please remove all other rules.
and try to access jenkins

**Comment by vinaysandela** [comment]
I did that and able to see the Jenkins Page. But I am unable to login to the AWS instance.

Attached are the steps I followed. Please let me know where I am doing wrong.
[Jenkins Installation on Ubuntu 14.04.txt](https://github.com/QT-DevOps/DevOpsIssues/files/2316144/Jenkins.Installation.on.Ubuntu.14.04.txt)

**Comment by raviops100** [comment]
Hi Vinay,
your installtion steps seems correct except sudo ufh allow 8080 i guess
it is not required

any how please try below steps 

1.Add Jenkins user to root group: sudo usermod -a -G root jenkins

2. Make Jenkins listen to all external IPs by editing file /etc/sysconfig/jenkins and changing the  JENKINS_LISTEN_ADDRESS="0.0.0.0"

3. restart jenkins

**Comment by shaikkhajaibrahim** [comment]
Did you play with nacl in this same vpc?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vinaysandela** [comment]
Thanks for helping. 

I have reinstalled everything. This time, I tired with Ubuntu 16.0 and same steps and it worked. 
Security Group that I have is - 

All traffic | All | All | 0.0.0.0/0 |  
All traffic | All | All | ::/0 |  
SSH | TCP | 22 | 0.0.0.0/0
