### ISSUE TITLE
Regaring RDS creation

### ISSUE THREAD

**Issue by vdileepdevops** [QT-DevOps/DevOpsIssues#118]
how can i create RDS instance in my private subnet using cli

**Comment by raviops100** [comment]
Hi Dileep,

Please folloe   below link it may help to achive your requirement

https://linuxacademy.com/blog/cloud/converting-your-aws-ec2-rds-instances-to-amazon-vpc/

**Comment by vdileepdevops** [comment]
thank you for reply ,but i want to do this using cli

**Comment by shaikkhajaibrahim** [comment]
Create db subnet group using https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-subnet-group.html and give private subnets. Pass this  db subnet group in create-db-instance
