### ISSUE TITLE
vagrant box not found

### ISSUE THREAD

**Issue by sainathareddy** [QT-DevOps/DevOpsIssues#119]
when i try with 
vagatant init centos/7
vagrant up
i am getting an error saying
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'centos/7' could not be found. Attempting to find and install..                                                                                        .
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'centos/7' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/centos/7"]
Error: The requested URL returned error: 404 Not Found

**Comment by saikiran243** [comment]
try this
vagrant init centos/7
vagrant up

**Comment by shaikkhajaibrahim** [comment]
I think you need to change the vagrant url  
https://github.com/hashicorp/vagrant/issues/9442

A workarround to add in your Vagrantfile:

Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
