### ISSUE TITLE
Installing jenkins in Vagrant

### ISSUE THREAD

**Issue by Vijay0973** [QT-DevOps/DevOpsIssues#12]
**status is running fine** 
![ip with status of jenkins](https://user-images.githubusercontent.com/39436774/40579654-83de9306-60e1-11e8-8373-8f7ffba4c336.PNG)
 **and i'm facing this error**
![site unreachable of jenkins](https://user-images.githubusercontent.com/39436774/40579667-c07ece84-60e1-11e8-872d-263e7db03616.PNG)

**please suggest me what i'm doing wrong**

**Comment by OTHMAN52** [comment]
Hi,
Reload your machine using
vagrant reload
or
Try localhost:8081
8081 is the  "forwarded_port" in vagrant file

**Comment by vijaybhaskarreddyy** [comment]
Check your system ram, by default vagrant is running 512mb Increase RAM and reload your vagrant machine after login into vagrant machine check jenkins status and check in browser.
