### ISSUE TITLE
Map a host directory to a Docker volume

### ISSUE THREAD

**Issue by siva0139** [QT-DevOps/DevOpsIssues#121]
![docker issue](https://user-images.githubusercontent.com/29588320/44518993-62cd1b80-a6e9-11e8-909e-f3963285fcb2.png)

**Comment by shaikkhajaibrahim** [comment]
You have overwritten the contents of tomcat with your empty folder. For these kind of folders better to 

docker run -v /var/tomcat/webapps ....... <remaining command>

docker inspect <containerid>

Navigate to the directory & see the contents

**Comment by siva0139** [comment]
thanks
