### ISSUE TITLE
kitchen converge throws description error

### ISSUE THREAD

**Issue by ramana152** [QT-DevOps/DevOpsIssues#122]
am trying to deploy nodejs ..but it is gettig error below
am trying with ec2 as kitchen drive

PS F:\Chef_Aug18\chef-repo\cookbooks\nodejs_deployee> kitchen converge
-----> Starting Kitchen (v1.22.0)
-----> Converging <default-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.0.4...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       ubuntu 14.04 x86_64
       Getting information for chef stable  for ubuntu...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=ubuntu&pv=14.04&m=x86_64
         to file /tmp/install.sh.1438/metadata.txt
       trying wget...
       sha1     64645bebefc45191064073a689a90c10a60fa9ae
       sha256   9ae754e889fbcaaef5632c783a09f134c548c7fdc126de3846f2752acc0e3d3c
       url      https://packages.chef.io/files/stable/chef/14.3.37/ubuntu/14.04/chef_14.3.37-1_amd64.deb
       version  14.3.37
       downloaded metadata file looks valid...
       downloading https://packages.chef.io/files/stable/chef/14.3.37/ubuntu/14.04/chef_14.3.37-1_amd64.deb
         to file /tmp/install.sh.1438/chef_14.3.37-1_amd64.deb
       trying wget...
       Comparing checksum with sha256sum...

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

       You are installing an omnibus package without a version pin.  If you are installing
       on production servers via an automated process this is DANGEROUS and you will
       be upgraded without warning on new releases, even to new major releases.
       Letting the version float is only appropriate in desktop, test, development or
       CI/CD environments.

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

       Installing chef
       installing with dpkg...
       Selecting previously unselected package chef.
(Reading database ... 51310 files and directories currently installed.)
       Preparing to unpack .../chef_14.3.37-1_amd64.deb ...
       Unpacking chef (14.3.37-1) ...
       Setting up chef (14.3.37-1) ...
       Thank you for installing Chef!
       Transferring files to <default-ubuntu-1404>
       Starting Chef Client, version 14.3.37
       Creating a new client identity for default-ubuntu-1404 using the validator key.
       resolving cookbooks for run list: ["nodejs_deployee::default"]

       ================================================================================
       Error Resolving Cookbooks for Run List:
       ================================================================================

       Missing Cookbooks:
       ------------------
       No such cookbook: build-essential

       Expanded Run List:
       ------------------
       * nodejs_deployee::default

       System Info:
       ------------
       chef_version=14.3.37
       platform=ubuntu
       platform_version=14.04
       ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
       program_name=/opt/chef/bin/chef-client
       executable=/opt/chef/bin/chef-client

       Running handlers:
       [2018-08-23T10:04:54+00:00] ERROR: Running exception handlers
       [2018-08-23T10:04:54+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-08-23T10:04:54+00:00] ERROR: Exception handlers complete
       [2018-08-23T10:04:54+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 01 seconds
       [2018-08-23T10:04:54+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-08-23T10:04:54+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-08-23T10:04:54+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-08-23T10:04:54+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-08-23T10:04:54+00:00] FATAL: Net::HTTPServerException: 412 "Precondition Failed"
       [2018-08-23T10:04:54+00:00] FATAL: Net::HTTPServerException: 412 "Precondition Failed"
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-1404>.  Please see .kitchen/logs/default-ubuntu-1404.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

please slove the my problem Thanks in Advance

**Comment by chagamreddy** [comment]
PS E:\quality\chef-starter\chef-repo\cookbooks\tom> kitchen create
-----> Starting Kitchen (v1.22.0)
-----> Creating <default-ubuntu-1404>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [AWS was not able to validate the provided access credentials] on default-ubuntu-1404
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

while creating my kitchen plz help for these error

**Comment by shaikkhajaibrahim** [comment]
Did you executed berks install before kitchen converge?

& one more thing attach cookbook

**Comment by ramana152** [comment]
yes sir.... i done berks install before only.... afterthat also am getting same error...

**Comment by ramana152** [comment]
Done.
