### ISSUE TITLE
Problem with passing atributes while using Chef in kitchen

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#123]
Hi,

I have tried this program without using attributes and tomcat7 gets installed, however, when I try using attributes, I fail.
Attributes: default,rb:-
# Package name for tomcat installation on ubuntu
default['tomcat-trials']['package_name'] = 'tomcat7'

# additional tomcat packages on ubuntu
default['tomcat-trials']['additional-packages'] = ['tomcat7-docs', 'tomcat7-admin', 'tomcat7-examples']

# variables for the tomcat7 template
default['tomcat-trials']['xmx'] = 512
default['tomcat-trials']['MaxPermSize'] = 256

Recipe: default.rb:-
include_recipe 'tomcat-trials::tomcat7'

Recipe: tomcat7.rb:-
apt_update 'update ubuntu packages' do
  action :update
  only_if node['platform'] == 'ubuntu'
end

packagename = node['tomcat-trials']['package_name']

package 'packagename' do
  action :install
  notifies :restart, "service[#{packagename}]"
end

# To do nano /etc/default/tomcat7
template '/etc/default/tomcat7' do
  source 'tomcat7.erb'
  action :create
end

package 'additional packages' do
  package_name node['tomcat-trials']['additional-packages']
  action :install
end

# To do sudo nano /etc/tomcat7/tomcat-users.xml
service 'packagename' do
  action :nothing
end

The error faced upon kitchen converge is:-
![image](https://user-images.githubusercontent.com/40449948/44538748-eace1800-a71f-11e8-895e-f616ec28e856.png)

Please tell me where I have made a mistake.

Regards
Ramesh

**Comment by shaikkhajaibrahim** [comment]
Please attach your cookbook
________________________________

**Comment by rameshm78** [comment]
[tomcat-trials.zip](https://github.com/QT-DevOps/DevOpsIssues/files/2317905/tomcat-trials.zip)
Here it is

**Comment by lingaswamy123** [comment]
package 'additional packages' do >>>>here remove single quotes when you define variable
package_name node['tomcat-trials']['additional-packages']
action :install
end

**Comment by lingaswamy123** [comment]
package 'packagename' do>>>>>>remove single quotes for variable here
action :install
notifies :restart, "service[#{packagename}]"
end

**Comment by rameshm78** [comment]
I had put the single quotes, because it was already failing. After removing them, it is failing as usual.
Also there is something wrong with the syntax of the commented line in attributes file
apt_update 'update ubuntu packages' do
  action :update
  #only_if node['platform'] == 'ubuntu'
end
It says it was expecting a true value. After commenting it out, one error stops coming. However, the script itself continues to fail at many places like 
1. Error executing action `restart` on resource 'service[tomcat7]'
And
 Mixlib::ShellOut::ShellCommandFailed
           Expected process to exit with [0], but received '1'
           ---- Begin output of /etc/init.d/tomcat7 start ----
           STDOUT: * Starting Tomcat servlet engine tomcat7
       ...fail!
           STDERR:
           ---- End output of /etc/init.d/tomcat7 start ----
           Ran /etc/init.d/tomcat7 start returned 1

FATAL: Mixlib::ShellOut::ShellCommandFailed: service[tomcat7] (tomcat-trials::tomcat7 line 31) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of /etc/init.d/tomcat7 start ----
       STDOUT: * Starting Tomcat servlet engine tomcat7
          ...fail!
       STDERR:
       ---- End output of /etc/init.d/tomcat7 start ----
       Ran /etc/init.d/tomcat7 start returned 1
       [2018-08-28T06:14:09+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: service[tomcat7] (tomcat-trials::tomcat7 line 31) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of /etc/init.d/tomcat7 start ----
       STDOUT: * Starting Tomcat servlet engine tomcat7
          ...fail!
       STDERR:
       ---- End output of /etc/init.d/tomcat7 start ----
       Ran /etc/init.d/tomcat7 start returned 1

I logged into the machine and did tomcat --version, but it says
tomcat: command not found.

Please suggest an alternative method.

Regards
Ramesh

**Comment by rameshm78** [comment]
No solution
