### ISSUE TITLE
Getting parsing error for kitchen.yml file

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#124]
Hi,
When I try to run kitchen create on this cookbook, I'm getting an error:-
Message: Error parsing E:/QT/Chef/chef-repo/cookbooks/tomcat-super/.kitchen.yml as YAML.
Is there any online tool to validate yaml file syntax/ structure.
[tomcat-super.zip](https://github.com/QT-DevOps/DevOpsIssues/files/2317972/tomcat-super.zip)
I've attached my cookbook herewith.
Please help.

Regards
Ramesh

**Comment by arunkumar127** [comment]
@rameshm78 
You can verify your yaml syntax online. There are plenty of websites which can validate your yaml files.

I have checked your .kitchen.yml file in http://www.yamllint.com/
It is showing error at 26th line
![yamlint](https://user-images.githubusercontent.com/40756184/44588825-6b4e5080-a7d4-11e8-8867-6237072b10fe.PNG)

Even in notepad++ it is showing same error
![npp error](https://user-images.githubusercontent.com/40756184/44588890-9a64c200-a7d4-11e8-8855-036bab7d80e3.PNG)

I modified your yaml file and checked again
![yamlval](https://user-images.githubusercontent.com/40756184/44589176-75248380-a7d5-11e8-81cf-79f4435016b9.PNG)

Here is modified kitchen.yml file
[kitchenyml.zip](https://github.com/QT-DevOps/DevOpsIssues/files/2318683/kitchenyml.zip)

**Comment by rameshm78** [comment]
Hi Arun,
Thanks a lot.
Could you please tell me what exact modification you did?
Yamllint is showing error, but I cannot see what is wrong.
Also can you please tell me what setting in Notepad++ helps you see the error? In mine, no error is shown.

**Comment by arunkumar127** [comment]
@rameshm78
 I did not modify much. I have only maintained spaces (alignments)
Compare these two images.

Error syntax
https://user-images.githubusercontent.com/40756184/44593797-04379880-a7e2-11e8-860d-28105b7447bf.png

Valid syntax
https://user-images.githubusercontent.com/40756184/44593831-229d9400-a7e2-11e8-97a9-607a003039b4.png

I did not use any specific setting in Notepad++, I am using version 7.5.8. Please check your version.

**Comment by rameshm78** [comment]
Thanks a lot for the help Arun.
I found that by setting Language to YAML in Notepad++, the error gets shown in red.
