### ISSUE TITLE
Error in Jenkins Build with SonarQube Project

### ISSUE THREAD

**Issue by vinaysandela** [QT-DevOps/DevOpsIssues#125]
Installed Jenkins on Ubuntu 16.06 and SonarQube on Ubuntu 16.06. Both from AWS instances. 
Installed Plugins for Sonarqube and added Sonrqube Server as attached
Created Pipeline project - in Jenkins and configured the script as shown in the screenshot
When Build, getting following error -  Can you help me where should i fix this?
```
[INFO] 2 source files to be analyzed
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000fac8b000, 52232192, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 52232192 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /var/lib/jenkins/workspace/Testing Sonarqube/hs_err_pid9804.log
[Pipeline] }
WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succedeed?
[Pipeline] // withSonarQubeEnv
```

**Comment by raviops100** [comment]
Hi Vinay,
Below article will resolve memory for the Java Runtime Environment
https://www.build-business-websites.co.uk/java-memory-allocation-failures-due-to-insufficient-swap-space/

**Comment by mani5a3** [comment]
JAVA_OPTS="-Xmx1024m" add this to environment variable and then check

**Comment by siva0139** [comment]
sorcecode file is not identified
give the source code file path properly
/var/lib/jenkins/workspace/Testing Sonarqube/hs_err_pid9804.log   -- error

**Comment by raviops100** [comment]
Hi Vinay,
is this closed ????
