### ISSUE TITLE
Supermarket cookbook mysql failing

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#126]
Hi,
I tried running the mysql cookbok, but it fails with error:
Error executing action `install` on resource 'apt_package[mysql-server-5.5]'

My cookbook is attached herewith
[cook_dbserver.zip](https://github.com/QT-DevOps/DevOpsIssues/files/2320393/cook_dbserver.zip)

Please let me know what I'm doing wrong.

**Comment by arunkumar127** [comment]
@rameshm78 
I tested your cookbook. It is asking to update packages (Check below image)
![error](https://user-images.githubusercontent.com/40756184/44616671-9fc41a00-a871-11e8-9814-0c9a4985fc37.PNG)

After adding apt_update resource, your cookbook is working. So add apt_update.
In server it is showing Mysql version ($ mysql --version), but it is not running. We need to modify cookbook to run Mysql.

**Comment by rameshm78** [comment]
Thanks Arun.  So we cannot rely on Supermarket cookbooks.
