### ISSUE TITLE
how to add a inbound rule to a security group

### ISSUE THREAD

**Issue by bhanukandula** [QT-DevOps/DevOpsIssues#127]
command1:
aws ec2 authorize-security-group-ingress --group-id sg-0cbc6a602bd8e9c9b --protocol http --port 80l --source-group 0.0.0.0/0
command2:
aws ec2 authorize-security-group-ingress --group-id sg-0cbc6a602bd8e9c9b --protocol all --port all --source-group 0.0.0.0/0

An error occurred (InvalidGroup.NotFound) when calling the  AuthorizeSecurityGroupIngress operation: The security group '0.0.0.0/0' does not exist in
default VPC 'vpc-c9dd8fae'

**Comment by vdileepdevops** [comment]
aws ec2 authorize-security-group-ingress --group-id sg-0cbc6a602bd8e9c9b --protocol tcp --port 80 --cidr 0.0.0.0/0

aws ec2 authorize-security-group-ingress --group-id sg-0cbc6a602bd8e9c9b --protocol all --cidr 0.0.0.0/0

**Comment by raviops100** [comment]
is this resolved ???
