### ISSUE TITLE
Recipe Compile Error in /var/chef/cache/cookbooks/my-second-cookbook/recipes/default.rb

### ISSUE THREAD

**Issue by chinnadas** [QT-DevOps/DevOpsIssues#129]
ubuntu@ip-172-31-21-85:~$ sudo chef-client
Starting Chef Client, version 14.3.37
resolving cookbooks for run list: ["my-second-cookbook"]
Synchronizing Cookbooks:
  - my-second-cookbook (0.1.8)
Installing Cookbook Gems:
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/my-second-cookbook/recipes/default.rb
================================================================================

NoMethodError
-------------
undefined method `package' for Chef::Resource::AptPackage

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/my-second-cookbook/recipes/default.rb:23:in `block in from_file'
  /var/chef/cache/cookbooks/my-second-cookbook/recipes/default.rb:22:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/my-second-cookbook/recipes/default.rb:

 16:
 17:
 18:   apt_update 'update_package' do
 19:     action :update
 20:   end
 21:
 22:   apt_package 'git' do
 23>>    package name 'git'
 24:     action :install
 25:   end
 26:
 27:   apt_package 'tree' do
 28:     action :install
 29:   end
 30:
 31:   apt_package 'nano' do
 32:     action :install

System Info:
------------
chef_version=14.3.37
platform=ubuntu
platform_version=16.04
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef/bin/chef-client

Running handlers:
[2018-08-27T09:56:02+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-08-27T09:56:02+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 02 seconds
[2018-08-27T09:56:02+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-08-27T09:56:02+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-08-27T09:56:02+00:00] FATAL: NoMethodError: undefined method `package' for Chef::Resource::AptPackage

**Comment by shaikkhajaibrahim** [comment]
In Line 23 there is error
22: apt_package 'git' do
23>> package name 'git'
24: action :install
25: end

correct this to either
package 'git' do
   action :install
end

or

apt_package 'git' do
   action :install
end
