### ISSUE TITLE
Build failure issue on jenkins

### ISSUE THREAD

**Issue by surajp491** [QT-DevOps/DevOpsIssues#13]
Hai,

As per the documentation i have been installed jenkins but while building the game of life my build was failure and it was shown env variables are not defined correctly.

But i have done it exactly whatever in the documentation any help would be highly appreciated.

Find the screen shot of my error  in the below attachment.

![capture-1](https://user-images.githubusercontent.com/35172963/40582293-38d01fc0-618f-11e8-8218-be7263f52d40.PNG)

**Comment by samjoel777** [comment]
check java -version and in vi /etc/profile have you added the java path.
for maven java is a must dependency
first install java and set the path correctly

**Comment by surajp491** [comment]
I have done exactly whatever in the documentation provide by the quality thought and checked all versioning commands it is working but atlast it was shown the env variables are not defined correctly.

**Comment by vijaybhaskarreddyy** [comment]
check JAVA_HOME env varible and goto manage jenkinks  and global tool configuration click jdk installation un select  Install automatically and give any name abd paste JAVA_HOME what ever you given in server.
![jenkins](https://user-images.githubusercontent.com/22870876/40596869-5ab29d26-625b-11e8-9e42-779d9dc4dff7.PNG)

**Comment by samjoel777** [comment]
send screenshot of jenkins user checking java -version in jenkins server terminal

**Comment by surajp491** [comment]
In the documentation a slight error is there while setting the java path on the  Jenkins server  remove the leading slash for this is the reason my build will fail ,Now correcting this everything would be fine.
