### ISSUE TITLE
Json Format

### ISSUE THREAD

**Issue by Sravan-jk** [QT-DevOps/DevOpsIssues#130]
let me know if its correct

{
    "Summary": "djaojdadd",
    "Skills":[
        "linux",
        "devops",
        "aws",
        "json",
        "jenkins"
    ],
    "Experience": {
        "company name": "xxxxx",
        "role": "engineer",
        "Responsibilities": [
            "xxxxxxxxxxxxx",
            "yyyyyyyyyyyyy",
            "zzzzzzzzzzzzz"
        ],
    },
    "Education": {
        "SSC": "BSE",
        "10+2": "xxx",
        "Graduation": "collegename"
        }
}

**Comment by raviops100** [comment]
Hi Sravan,

in line no 17 just remove , after [] try to validate JSON it works fine

when ever you want to validate your JSON

there are multiple json validators in online one of below

https://jsonlint.com/ go to this site paste your JSON code 

and validate your code

**Comment by Sravan-jk** [comment]
Thanks, it worked after removing a comma(,) in 17th line
