### ISSUE TITLE
Git related Query

### ISSUE THREAD

**Issue by duddumounika** [QT-DevOps/DevOpsIssues#132]
Hi Sir,
How to write a Webhook in bitbucket so that it should not allow you to push certain type of files?
Can we  create a branch with one of the folder in master branch

Thanks
Mounika

**Comment by raviops100** [comment]
Hi Mounika,

For your first question below link may help you to resolve

https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html

after visiting this link end of the page click on ==>create webhooks ==> push repositary events

For second question 

When you select a branch - the branch is the active branch and the local folder corresponds to the current branch. 
If you switch over the branch in source tree, 
the local folder will automatically reflect to selected branch.
