### ISSUE TITLE
Chef - Issue with parsing attributes while deploying nodejs in kitchen

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#133]
Hi,

When I try to deploy nodejs using cookbook from supermarket, following error is being thrown with regards to entry in the attribute file for ip address:

![image](https://user-images.githubusercontent.com/40449948/44794997-4d636000-abc7-11e8-952c-379382550bc5.png)

Please let me know where I'm going wrong. My cook book is attached herewith.
[cook_nodejs.zip](https://github.com/QT-DevOps/DevOpsIssues/files/2332561/cook_nodejs.zip)

Regards
Ramesh

**Comment by arunkumar127** [comment]
@rameshm78 
You have missed quotes for attributes
default['cook_nodejs']['appserver-ip'] = node['ipaddress']
default['cook_nodejs']['webserver-dns'] = node['fqdn']

**Comment by arunkumar127** [comment]
@shaikkhajaibrahim @vijaybhaskarreddyy 
Sir how to access/copy appserver's IP address into nginx (reverse proxy)?
How to write attribute to access them?
Please let me know this sir.
I'm stuck at this point in both Chef & Ansible.

Thank in advance.

**Comment by arunkumar127** [comment]
@rameshm78 
Please let me know if you have solution for my above query.

Thank in advance.

**Comment by rameshm78** [comment]
Hi Arun,
Thanks a lot again, for helping me out.
With regards to your query, what I understand is that the appserver's ip address needs to be put in manually. This is because, this particular case is for setting up a system physically. It was stated in some earlier class that when this setup is on the web, this situation is handled by the Load Balancer. In case of physical systems, one will already be aware of the ip address of the machine.

This is my understanding and needs to be confirmed by Khaja sir. You could either ask this at the beginning of class tomorrow to get immediate response. Else post a question here.

Also we have not yet seen how Load Balancer in configured, but it is perhaps in some future class.

I'll close this thread once, I find things are working. Thanks again Arun.

**Comment by arunkumar127** [comment]
@ramesh78
Thank you for your reply.
Upto now I've copied Appserver IP in Nginx manually. I have been searching if there is any method to copy IP address dynamically.

I'll ask Khaja sir tomorrow and let you know if there is any approach.

Thank you.

**Comment by rameshm78** [comment]
Thanks Arun.
If he explains during tomorrow's session, I will close this thread, or else please update the answer here.
By the way, the attributes file worked after adding the quotes.

**Comment by arunkumar127** [comment]
@rameshm78 
Is NodeJS installed in your machine?
If so can you please let me know version installed in your machine.
$ node --version

Thank you.

**Comment by rameshm78** [comment]
@arunkumar127 
Just did a kitchen converge to create the setup.
The version of nodejs is v6.14.4
