### ISSUE TITLE
aws volume snapshot image not working

### ISSUE THREAD

**Issue by khksairaj** [QT-DevOps/DevOpsIssues#134]
Created a snapshot in aws volumes then created a image and then created a instance from that image, but that image is not working. Not able to ping even that have public ip and all ports opened. Not able to login using ssh command also.

**Comment by raviops100** [comment]
Hi SaiRaj,

Please follow below steps to create volume and snapshot::
-------------------------------------------------------
1. create an Amazon AMI t2 micro machine

2. root volume create by default

3. create extra volume for 4GB after that you can mount it

4. stop the machine take snapshot 

5.  from this snap shot create Volume

for ping to the EC2  machine::
----------------------------
Add a new EC2 security group inbound rule:

    Type: Custom ICMP rule
    Protocol: Echo Request
    Port: N/A
    Source: your choice (select Anywhere to be able to ping from any machine)
	
For SSH coonectivity to EC2 machine::
-----------------------------------
Please Check Once in your region 
If you do not have an Internet gateway, 
create one and attach it to Default VPC.

Thanks
Ravi

**Comment by revathi-muthana123** [comment]
Hi,
Is it cleared?

Thanks 
Revathi
