### ISSUE TITLE
but service[httpd] cannot be found in the resource collection. 

### ISSUE THREAD

**Issue by naveenaws66** [QT-DevOps/DevOpsIssues#135]
## I am getting "but service[httpd] cannot be found in the resource collection. " error while running below recipe.
##point out what mistake i am doing and correct me THANKS IN ADVANCE

packages = ['httpd','mariadb-server','mariadb','php','php-mysql']
packages.each do |pkg|
    package pkg do
        action :install
    end
end
file '/var/www/html/info.php' do
    content '<?php phpinfo(); ?>'
    notifies :restart, 'service[httpd]', :immediately
    notifies :enable, 'service[httpd]', :immediately
    notifies :restart, 'service[mariadb]', :immediately
    notifies :enable, 'service[mariadb]', :immediately   
end
service 'notify' do
    action :nothing
end

**Comment by shaikkhajaibrahim** [comment]
What is service 'notify'?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by naveenaws66** [comment]
i should give some name to the resource right , so that i can later call 'notifies'. so that just a name i have given to that resource.

**Comment by shaikkhajaibrahim** [comment]
Then why are you calling notifies service by name httpd which doesn't exist

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by naveenaws66** [comment]
ok i got it now , i will try again.

**Comment by naveenaws66** [comment]
thank you sir it worked perfectly. now i understood how 'notifies' work .
