### ISSUE TITLE
 Cookbook depends on itself in cookbook

### ISSUE THREAD

**Issue by Sravan-jk** [QT-DevOps/DevOpsIssues#136]
Hello all,

can you please check this issue and let me know how can i resolve it

tried to install java using supermarket cookbook and this error occured

also attached the log file 

Thanks
[default-ubuntu-1404.log](https://github.com/QT-DevOps/DevOpsIssues/files/2340287/default-ubuntu-1404.log)
[java.zip](https://github.com/QT-DevOps/DevOpsIssues/files/2340294/java.zip)

**Comment by arunkumar127** [comment]
@Sravan-jk 
Change your cookbook name.
Generated cookbook name & any cookbook which you're depending on (from supermarket) should not be same.

**Comment by Sravan-jk** [comment]
Hi Arun,

Thank you, it worked
