### ISSUE TITLE
CF error for VPC

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#137]
Hi,
This is my json for vpc, and ma getting an eror while creating stack:-
Template validation error: Template format error: Unresolved resource dependencies [cfcidr] in the Resources block of the template

{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Create VPC",
    "Parameters": {

        "netcidr": {
            "Description": "CIDR for the VPC",
            "Type": "String",
            "Default": "10.10.0.0/16"        
        }
    },

    "Resources": {

        
        "cfvpc": {
          "Type": "AWS::EC2::VPC",
          "Properties": {
            "CidrBlock": {"Ref": "cfcidr"},
            "EnableDnsHostnames": true
          }
        }
        
    }
}

**Comment by shaikkhajaibrahim** [comment]
Use netcidr in ref

Get Outlook for Android<https://aka.ms/ghei36>



From: Ramesh Menon
Sent: Saturday, 1 September, 07:46
Subject: [QT-DevOps/DevOpsIssues] CF error for VPC (#137)
To: QT-DevOps/DevOpsIssues
Cc: Subscribed


Hi,
This is my json for vpc, and ma getting an eror while creating stack:-
Template validation error: Template format error: Unresolved resource dependencies [cfcidr] in the Resources block of the template
{
"AWSTemplateFormatVersion": "2010-09-09",
"Description": "Create VPC",
"Parameters": {
"netcidr": { "Description": "CIDR for the VPC", "Type": "String", "Default": "10.10.0.0/16" } }, "Resources": { "cfvpc": { "Type": "AWS::EC2::VPC", "Properties": { "CidrBlock": {"Ref": "cfcidr"}, "EnableDnsHostnames": true } } }
}

**Comment by rameshm78** [comment]
Thanks a lot.
Sorry for the very silly mistake.
