### ISSUE TITLE
cloud formation

### ISSUE THREAD

**Issue by kskreddy87** [QT-DevOps/DevOpsIssues#139]
[testvpcc.txt](https://github.com/QT-DevOps/DevOpsIssues/files/2342096/testvpcc.txt)
good afternoon, sir
  this issue is related to AWS cloud formation
today's exercise in class room
 I write the json file to create the vpc, subnet, internet gateway, routetable, security group and ec2 machine (RHEL) every thing is working fine. My code created the ec2 machine but the problem is  I can't log on to that ec2 machine.   So I attach my code to this please check the code and specify what are the corrections to do to log on to my ec2 machine 
 thank you sir

**Comment by shakirmir** [comment]
hi ,
As u said your ec2 machine created ,please check and open ssh port 22  to login from security group

**Comment by kskreddy87** [comment]
let me close this issue my self 
i found that ec2 machine cannot assign to a public ip
so in subnet section to enable public ip to ec2 machine there is a property called   "MapPublicIpOnLaunch" : default set to false so enable it to true
  "MapPublicIpOnLaunch" : true,
