### ISSUE TITLE
Jenkins Reverse proxy

### ISSUE THREAD

**Issue by Somansh1993** [QT-DevOps/DevOpsIssues#14]
Hi Team,

I installed Jenkins and Nginx on Centos 7 machine but i checked few proxy pass settings they mentioned that you have to change the servername with your local domain name, now i am confused with server IP and servername configuration. Please suggest how to get jenkins domain name.

________________________________________My proxy pass setting in nginx___________________________________
**upstream jenkins{
    server 10.0.2.15:8081;
}

server{
    listen      80;
    server_name ci.yourdomain.com;

    access_log  /var/log/nginx/jenkins.access.log;
    error_log   /var/log/nginx/jenkins.error.log;

    proxy_buffers 16 64k;
    proxy_buffer_size 128k;

    location / {
        proxy_pass  http://jenkins;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;

        proxy_set_header    Host            $host;
        proxy_set_header    X-Real-IP       $remote_addr;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto https;
    }

}**

**Comment by shaikkhajaibrahim** [comment]
Use your servers ip address

my reverse proxy would be something like 

server {
    listen 80;

    server_name <fqdn- public dns in amazon>;

    location / {
        proxy_pass http://Jenkins_PRIVATE_IP_ADDRESS:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

I would access jenkins using http://<publicdns>
