### ISSUE TITLE
ansible issue

### ISSUE THREAD

**Issue by siva0139** [QT-DevOps/DevOpsIssues#140]
sudo /etc/init.d/tomcat8 start   - it works in commandline

- name: start the tomcat server
  command:  /etc/init.d/tomcat8 start

not working when i write it in ansibe module

**Comment by ramana152** [comment]
upload error log or playbook , Then only we can try to get solution.

**Comment by siva0139** [comment]
![screenshot 23](https://user-images.githubusercontent.com/29588320/44945649-ac191b80-ae0b-11e8-9c1b-ac882b533f4e.png)
![screenshot 24](https://user-images.githubusercontent.com/29588320/44945651-b1766600-ae0b-11e8-85b4-805c2577a775.png)
its executing suceess fully but tomcat server is not running

**Comment by malli86271** [comment]
Have you installed java. Because tomcat requires java to be installed

**Comment by ramana152** [comment]
@siva0139  upload complete playbook (zip format)..

**Comment by lingaswamy143** [comment]
1)it looks like you don't need to start the service from /etc/init.d/ when you configure a script file inside the /etc/init.d locatin. just give sudo systemctl daemon-reload and sudo systemctl start tomcat
as ansible modules.
2)next give ansible user permissions over entire tomcat directory recursively

**Comment by shaikkhajaibrahim** [comment]
Any progress on this
