### ISSUE TITLE
jenkins and git 

### ISSUE THREAD

**Issue by saireddy224** [QT-DevOps/DevOpsIssues#141]
i am unable to get code from git .i am getting following error
[log (1).txt](https://github.com/QT-DevOps/DevOpsIssues/files/2342725/log.1.txt)

**Comment by bhanukandula** [comment]
can u please verify POM.xml file in your code. It is mandatory to be present.

**Comment by lingaswamy143** [comment]
Have you installed java?

**Comment by devopsawsazure** [comment]
Hope this resolves your issue!

https://stackoverflow.com/questions/46232906/git-clone-error-rpc-failed-curl-56-openssl-ssl-read-ssl-error-syscall-errno

**Comment by shaikkhajaibrahim** [comment]
Is this done ?

**Comment by saireddy224** [comment]
yes sir,i seached in web and resolved my problem.it is due to slow internet connection.thank you
