### ISSUE TITLE
jenkins not cloning git

### ISSUE THREAD

**Issue by saireddy224** [QT-DevOps/DevOpsIssues#142]
jenkins is taking lot of time to clone git.and it not cloning 
![jen](https://user-images.githubusercontent.com/7966678/44949585-41d79980-ae52-11e8-997e-f1c097792d8b.PNG)

**Comment by shakirmir** [comment]
for which project you are creating build like (freestyle and pipeline) 
send the build status console 
if you only trying for cloning then goto source code management>git>https://github.com/wakaleo/game-of-life.git

**Comment by lingaswamy143** [comment]
Execute git clone as jenkins user and check whether it is doing fine

**Comment by devopsawsazure** [comment]
Low Bandwidth ? try this.

https://stackoverflow.com/questions/46232906/git-clone-error-rpc-failed-curl-56-openssl-ssl-read-ssl-error-syscall-errno

**Comment by shaikkhajaibrahim** [comment]
Duplicate #141
