### ISSUE TITLE
QT-Blog Materials 

### ISSUE THREAD

**Issue by revathi-muthana123** [QT-DevOps/DevOpsIssues#143]
http://devopsmaterial.blogspot.com/ - For git
http://qualitythoughtawsmaterial.blogspot.com/ - for AWS & Azure
http://qualitythoughtchefpuppetdocker.blogspot.com/ - for Devops

**Comment by ramana152** [comment]
this blog is not open. its showing 404 error in attached pic  for every link.
![error](https://user-images.githubusercontent.com/39365142/44973549-8e1df900-af7a-11e8-84d7-8abf23460468.png)

**Comment by Suneel023** [comment]
Links are not working 
Showing 404 Error

**Comment by sohailfaizan** [comment]
Unable to access. Its showing 404 Error.
