### ISSUE TITLE
Creating multiple Rules in Security group using CF

### ISSUE THREAD

**Issue by vdileepdevops** [QT-DevOps/DevOpsIssues#145]
Hi sir,
how can i create multiple ingress rules in one security group using cloud formation.
Ex: i want to allow only 22,23,3368 ports.

Thank you
Dileep.

**Comment by shaikkhajaibrahim** [comment]
{
  "Type" : "AWS::EC2::SecurityGroup",
  "Properties" : {
     "GroupName" : String,
     "GroupDescription" : String,
     "SecurityGroupEgress" : [ Security Group Rule, ... ],
     "SecurityGroupIngress" : [ Security Group Rule, ... ],
     "Tags" :  [ Resource Tag, ... ],
     "VpcId" : String
  }
}

Security Group Egress or ingress is array pass multiple reference sections
