### ISSUE TITLE
Git Remote Server Issue  

### ISSUE THREAD

**Issue by vsaisatya21** [QT-DevOps/DevOpsIssues#146]
sir !
 I got struck here. Can you please help me out sir. Actually I tried to **push my code to remote repository** but I couldn't sir. I'm getting this **fatal:403** error please solve this s
![git](https://user-images.githubusercontent.com/38434922/45076084-c7836f80-b106-11e8-8d94-e0040b419ca6.PNG)
ir.

**Comment by shaikkhajaibrahim** [comment]
Create your own repository. On asquarezone, I'm the only user who has write permissions

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by arunkumar127** [comment]
@vsaisatya21 
Create your own repository in your GitHub account, copy your repository url.
Follow this document to add remote repository
https://help.github.com/articles/adding-a-remote/

Then perform push/pull operations.

**Comment by vsaisatya21** [comment]
thank you sir

**Comment by vsaisatya21** [comment]
sir how can I get the **game of life** what you are using now   with  same structure.

**Comment by arunkumar127** [comment]
@vsaisatya21 
You can get game-of-life from this link.
https://github.com/wakaleo/game-of-life
