### ISSUE TITLE
jfrog installation and configuration

### ISSUE THREAD

**Issue by siva0139** [QT-DevOps/DevOpsIssues#147]
i installed jfrog as a service on linux 16.04
but i am unable to create maven repository inside the jfrog.
can any one have proper document for installation and 
configuration of jfrog plz share with me

**Comment by devopsawsazure** [comment]
Hope this helps

https://redstack.wordpress.com/2013/12/04/setting-up-a-maven-repository-manager-with-artifactory/

**Comment by siva0139** [comment]
Thanks for your response
But I want to configure jfrog with jenkins

**Comment by shaikkhajaibrahim** [comment]
Perform as shown in class & refer docs from blog
