### ISSUE TITLE
tomca7 instalation on ubuntu 14.04

### ISSUE THREAD

**Issue by ghost** [QT-DevOps/DevOpsIssues#148]
Starting Kitchen (v1.22.0)
-----> Converging <default-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.0.4...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-ubuntu-1404>
       Starting Chef Client, version 14.4.56
       resolving cookbooks for run list: ["tomcat-user::default"]
       Synchronizing Cookbooks:
         - tomcat-user (0.2.34)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 11 resources
       Recipe: tomcat-user::install
         * apt_update[update] action update
           - force update new lists of packages
           * directory[/var/lib/apt/periodic] action create (up to date)
           * directory[/etc/apt/apt.conf.d] action create (up to date)
           * file[/etc/apt/apt.conf.d/15update-stamp] action create_if_missing (up to date)
           * execute[apt-get -q update] action run
             - execute ["apt-get", "-q", "update"]

         * apt_package[tomcat7] action install (up to date)
         * service[tomcat7] action restart

           ================================================================================
           Error executing action `restart` on resource 'service[tomcat7]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '127'
           ---- Begin output of /etc/init.d/tomcat7 stop ----
           STDOUT:
: not foundSTDERR: /etc/init.d/tomcat7: 4: /etc/default/tomcat7:
           ---- End output of /etc/init.d/tomcat7 stop ----
           Ran /etc/init.d/tomcat7 stop returned 127

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/tomcat-user/recipes/install.rb

            12: service 'tomcat7' do
            13:   action :restart
            14: end
            15:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/tomcat-user/recipes/install.rb:12:in `from_file'

           service("tomcat7") do
             action [:restart]
             default_guard_interpreter :default
             service_name "tomcat7"
             enabled nil
             running nil
             masked nil
             pattern "tomcat7"
             declared_type :service
             cookbook_name "tomcat-user"
             recipe_name "install"
           end

           System Info:
           ------------
           chef_version=14.4.56
           platform=ubuntu
           platform_version=14.04
           ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client

       Running handlers:
       [2018-09-05T09:43:23+00:00] ERROR: Running exception handlers
       [2018-09-05T09:43:23+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-09-05T09:43:23+00:00] ERROR: Exception handlers complete
       [2018-09-05T09:43:23+00:00] ERROR: Exception handlers complete
       Chef Client failed. 2 resources updated in 22 seconds
       [2018-09-05T09:43:23+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-09-05T09:43:23+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-09-05T09:43:23+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-09-05T09:43:23+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-09-05T09:43:23+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: service[tomcat7] (tomcat-user::install line 12) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '127'
       ---- Begin output of /etc/init.d/tomcat7 stop ----
       STDOUT:
: not foundRR: /etc/init.d/tomcat7: 4: /etc/default/tomcat7:
       ---- End output of /etc/init.d/tomcat7 stop ----
       Ran /etc/init.d/tomcat7 stop returned 127
       [2018-09-05T09:43:23+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: service[tomcat7] (tomcat-user::install line 12) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '127'
       ---- Begin output of /etc/init.d/tomcat7 stop ----
       STDOUT:
: not foundRR: /etc/init.d/tomcat7: 4: /etc/default/tomcat7:
       ---- End output of /etc/init.d/tomcat7 stop ----
       Ran /etc/init.d/tomcat7 stop returned 127
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-1404>.  Please see .kitchen/logs/default-ubuntu-1404.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by arunkumar127** [comment]
@nareshabbanapuri 
Attach your complete cookbook as .zip here.

**Comment by shaikkhajaibrahim** [comment]
Add this to #152

**Comment by shaikkhajaibrahim** [comment]
Add this to #154
