### ISSUE TITLE
Ansible - How to overwrite default variable value.

### ISSUE THREAD

**Issue by arunkumar127** [QT-DevOps/DevOpsIssues#149]
Hi 
I'm trying to deploy NodeJS app with Nginx as reverse proxy.

For Nginx I wrote template which dynamically takes Server IP Value
![1](https://user-images.githubusercontent.com/40756184/45085615-b5adc680-b11e-11e8-8d54-982bd81cde7a.jpg)

I am trying to overwrite this value with my NodeJS Server IP using --extra-vars/ -e. But value is not changing, Value of Nginx IP is being copied.

Here are commands I'm trying to execute
$ ansible-playbook -i inventory/ -e "ansible_default_ipv4.address = 172.31.40.36" webserver.yml
$ ansible-playbook -i inventory/ --extra-vars "ansible_default_ipv4.address = 172.31.40.36" webserver.yml

For both commands value is not changing. Please check whether my command is right or wrong.
Please tell me where I am going wrong.

Thanks & Regards
Arun Kumar

**Comment by siva0139** [comment]
sorry we can't override default variable value

**Comment by siva0139** [comment]
define custom variable and pass your value from anywhere i.e playbook or commandline

**Comment by arunkumar127** [comment]
@siva0139
Thank you for reply.
I did the same.
