### ISSUE TITLE
SonarQube Failure with Freestyle Project

### ISSUE THREAD

**Issue by ChaitanyaPasupula** [QT-DevOps/DevOpsIssues#15]
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 16.501s
INFO: Final Memory: 11M/121M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: Please provide compiled classes of your project with sonar.java.binaries property
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succedeed?
ERROR: SonarQube scanner exited with non-zero code: 1
Finished: FAILURE

**Comment by vijaybhaskarreddyy** [comment]
Attach you're your job configuration and sonar qube configuration details.

**Comment by shaikkhajaibrahim** [comment]
Is this resolved??
