### ISSUE TITLE
web page creation error

### ISSUE THREAD

**Issue by ajs777** [QT-DevOps/DevOpsIssues#150]
when i try to create wegpage i got this error can u plz
![screenshot 45](https://user-images.githubusercontent.com/37798362/45162798-71005900-b20c-11e8-9881-7342b597b74d.png)
![screenshot 44](https://user-images.githubusercontent.com/37798362/45162806-765da380-b20c-11e8-8883-0f9f6943afa8.png)

 try to help me

**Comment by arunkumar127** [comment]
@ajs777 
In **copy** module src should be specified as a file format.

If you're trying to copy hi ajay content to html file, then you should mention in quotes.

- name: Copy content to webserver
  copy:
    content: 'Hi Ajay'
    dest: /var/www/html/index.html

**Comment by ajs777** [comment]
thank u arunkumar garu 

I have done what u  said,But still the same error is coming,

**Comment by arunkumar127** [comment]
@ajs777 

I did the same & it worked for me.

![1](https://user-images.githubusercontent.com/40756184/45167065-00f6d080-b216-11e8-9d41-af99b68ef79c.jpg)

![2](https://user-images.githubusercontent.com/40756184/45167084-0f44ec80-b216-11e8-93a9-75183e064566.jpg)

![3](https://user-images.githubusercontent.com/40756184/45167110-1966eb00-b216-11e8-82b1-d56e2b226c9d.jpg)

Here is my playbook  for reference
[test.zip](https://github.com/QT-DevOps/DevOpsIssues/files/2357626/test.zip)
