### ISSUE TITLE
Adhoc command error

### ISSUE THREAD

**Issue by ajs777** [QT-DevOps/DevOpsIssues#151]
when i try to write webpage by Adhoc command iam getting this error can you plz help me

![screenshot 48](https://user-images.githubusercontent.com/37798362/45252988-e4c17380-b37c-11e8-8f9d-437dafe1cfb7.png)

**Comment by shaikkhajaibrahim** [comment]
Use src and destination properties
If you want file in remote machine with content  use file module instead

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by siva0139** [comment]
remove double quotes for copy
ansible --become -m copy -a "content=hai dest=/var/www/html/index.html"  -i inventory/myinventory appserver

**Comment by ajs777** [comment]
hai khaja sir 
How to use src can you please tell me

**Comment by shaikkhajaibrahim** [comment]
ansible coreservers -m copy -a "src=/etc/hosts dest=/tmp/hosts"

ansible coreservers -m file -a "dest=/var/www/index.html mode=755 owner=scarlz group=www" -b -K

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
