### ISSUE TITLE
error while untar jdk

### ISSUE THREAD

**Issue by siva0139** [QT-DevOps/DevOpsIssues#152]
$ wget http://download.oracle.com/otn-pub/java/jdk/8u18b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk- 
     8u181-linux-x64.tar.gz
jdk-8u181-linux-x64.tar.gz                100%[=====================================================================================>]   5.18K  --.-KB/s    in 0s

2018-09-08 10:28:27 (486 MB/s) - ‘jdk-8u181-linux-x64.tar.gz’ saved [5307/5307]

ubuntu@ip-172-31-88-8:~$ ls
jdk-8u181-linux-x64.tar.gz
ubuntu@ip-172-31-88-8:~$ tar -xvzf jdk-8u181-linux-x64.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by arunkumar127** [comment]
@siva0139 
1) In official website. gz file which you're trying to download is around 178 MB.
Check size of file which you have downloaded.
$ ls -sh jdk-8u181-linux-x64.tar.gz
(ls -sh file-name)
If file size is not around 178 MB, then file which you have downloaded is corrupt.

2) While downloading files from Oracle website using wget, we have to accept license.
Append -c --header "Cookie: oraclelicense=accept-securebackup-cookie" to wget command.
$ wget http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz -c --header "Cookie: oraclelicense=accept-securebackup-cookie"

Check file size after downloading & perform untar operation
$ tar -xvzf jdk-8u181-linux-x64.tar.gz
