### ISSUE TITLE
tomcat7 - : not found/tomcat7: 4: /etc/default/tomcat7:

### ISSUE THREAD

**Issue by ghost** [QT-DevOps/DevOpsIssues#154]
[2018-09-09T09:16:38+00:00] DEBUG: Running Ohai with the following configuration: {:logger=>Chef::Log}
Starting Chef Client, version 14.4.56
[2018-09-09T09:16:38+00:00] INFO: *** Chef 14.4.56 ***
[2018-09-09T09:16:38+00:00] INFO: Platform: x86_64-linux
[2018-09-09T09:16:38+00:00] INFO: Chef-client pid: 12911
[2018-09-09T09:16:38+00:00] DEBUG: Chef-client request_id: c3d71036-ab00-4b5d-8759-8230e3a637cd
[2018-09-09T09:16:38+00:00] DEBUG: Running Ohai with the following configuration: {:logger=>Chef::Log}
[2018-09-09T09:16:38+00:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
[2018-09-09T09:16:39+00:00] DEBUG: Plugin Zpools: Could not shell_out "zpool list -H -o name,size,alloc,free,cap,dedup,health,version". Skipping plugin.
[2018-09-09T09:16:39+00:00] DEBUG: Extracting run list from JSON attributes provided on command line
[2018-09-09T09:16:39+00:00] DEBUG: Applying attributes from json file
[2018-09-09T09:16:39+00:00] DEBUG: Platform is ubuntu version 14.04
[2018-09-09T09:16:39+00:00] INFO: Run List is [recipe[tomcat::default]]
[2018-09-09T09:16:39+00:00] INFO: Run List expands to [tomcat::default]
[2018-09-09T09:16:39+00:00] INFO: Starting Chef Run for ec2-18-234-187-117.compute-1.amazonaws.com
[2018-09-09T09:16:39+00:00] INFO: Running start handlers
[2018-09-09T09:16:39+00:00] INFO: Start handlers complete.
[2018-09-09T09:16:39+00:00] INFO: Error while reporting run start to Data Collector. URL: https://api.chef.io/organizations/abnnaresh/data-collector Exception: 404 -- 404 "Not Found"  (This is normal if you do not have Chef Automate)
resolving cookbooks for run list: ["tomcat::default"]
[2018-09-09T09:16:39+00:00] INFO: Loading cookbooks [tomcat@0.1.4]
Synchronizing Cookbooks:
  - tomcat (0.1.4)
Installing Cookbook Gems:
Compiling Cookbooks...
[2018-09-09T09:16:39+00:00] DEBUG: Cookbooks to compile: [:tomcat]
[2018-09-09T09:16:39+00:00] DEBUG: Node ec2-18-234-187-117.compute-1.amazonaws.com loading cookbook tomcat's attribute file /var/chef/cache/cookbooks/tomcat/attributes/default.rb
Converging 9 resources
[2018-09-09T09:16:39+00:00] DEBUG: Converging node ec2-18-234-187-117.compute-1.amazonaws.com
Recipe: tomcat::install
  * apt_update[update] action update[2018-09-09T09:16:39+00:00] INFO: Processing apt_update[update] action update (tomcat::install line 6)

    - force update new lists of packages
    * directory[/var/lib/apt/periodic] action create[2018-09-09T09:16:39+00:00] INFO: Processing directory[/var/lib/apt/periodic] action create (/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/provider/apt_update.rb line 60)
 (up to date)
    * directory[/etc/apt/apt.conf.d] action create[2018-09-09T09:16:39+00:00] INFO: Processing directory[/etc/apt/apt.conf.d] action create (/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/provider/apt_update.rb line 60)
 (up to date)
    * file[/etc/apt/apt.conf.d/15update-stamp] action create_if_missing[2018-09-09T09:16:39+00:00] INFO: Processing file[/etc/apt/apt.conf.d/15update-stamp] action create_if_missing (/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/provider/apt_update.rb line 65)
 (up to date)
    * execute[apt-get -q update] action run[2018-09-09T09:16:40+00:00] INFO: Processing execute[apt-get -q update] action run (/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/provider/apt_update.rb line 70)

      [execute] Ign http://us-east-1.ec2.archive.ubuntu.com trusty InRelease
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates InRelease
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports InRelease
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty Release.gpg
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty Release
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/main Sources
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/restricted Sources
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/universe Sources
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/multiverse Sources
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/main amd64 Packages
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/restricted amd64 Packages
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/universe amd64 Packages
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/multiverse amd64 Packages
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/main Translation-en
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/multiverse Translation-en
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/restricted Translation-en
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-updates/universe Translation-en
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/main Sources
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/restricted Sources
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/universe Sources
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/multiverse Sources
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/main amd64 Packages
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/restricted amd64 Packages
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/universe amd64 Packages
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/multiverse amd64 Packages
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/main Translation-en
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/multiverse Translation-en
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/restricted Translation-en
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty-backports/universe Translation-en
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty/main Sources
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty/restricted Sources
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty/universe Sources
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty/multiverse Sources
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty/main amd64 Packages
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty/restricted amd64 Packages
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty/universe amd64 Packages
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty/multiverse amd64 Packages
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty/main Translation-en
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty/multiverse Translation-en
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty/restricted Translation-en
                Hit http://us-east-1.ec2.archive.ubuntu.com trusty/universe Translation-en
                Hit http://security.ubuntu.com trusty-security InRelease
                Hit http://security.ubuntu.com trusty-security/main Sources
                Hit http://security.ubuntu.com trusty-security/universe Sources
                Hit http://security.ubuntu.com trusty-security/main amd64 Packages
                Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
                Hit http://security.ubuntu.com trusty-security/main Translation-en
                Hit http://security.ubuntu.com trusty-security/universe Translation-en
                Reading package lists...
[2018-09-09T09:16:43+00:00] INFO: execute[apt-get -q update] ran successfully
      - execute ["apt-get", "-q", "update"]

  * apt_package[tomcat7] action install[2018-09-09T09:16:43+00:00] INFO: Processing apt_package[tomcat7] action install (tomcat::install line 9)
tomcat7:
  Installed: 7.0.52-1ubuntu0.15
  Candidate: 7.0.52-1ubuntu0.15
  Version table:
 *** 7.0.52-1ubuntu0.15 0
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     7.0.52-1 0
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
 (up to date)
  * service[tomcat7] action start[2018-09-09T09:16:43+00:00] INFO: Processing service[tomcat7] action start (tomcat::install line 12)
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 07:08 ?        00:00:01 /sbin/init
root         2     0  0 07:08 ?        00:00:00 [kthreadd]
root         3     2  0 07:08 ?        00:00:00 [ksoftirqd/0]
root         5     2  0 07:08 ?        00:00:00 [kworker/0:0H]
root         6     2  0 07:08 ?        00:00:00 [kworker/u30:0]
root         7     2  0 07:08 ?        00:00:00 [rcu_sched]
root         8     2  0 07:08 ?        00:00:00 [rcuos/0]
root         9     2  0 07:08 ?        00:00:00 [rcuos/1]
root        10     2  0 07:08 ?        00:00:00 [rcuos/2]
root        11     2  0 07:08 ?        00:00:00 [rcuos/3]
root        12     2  0 07:08 ?        00:00:00 [rcuos/4]
root        13     2  0 07:08 ?        00:00:00 [rcuos/5]
root        14     2  0 07:08 ?        00:00:00 [rcuos/6]
root        15     2  0 07:08 ?        00:00:00 [rcuos/7]
root        16     2  0 07:08 ?        00:00:00 [rcuos/8]
root        17     2  0 07:08 ?        00:00:00 [rcuos/9]
root        18     2  0 07:08 ?        00:00:00 [rcuos/10]
root        19     2  0 07:08 ?        00:00:00 [rcuos/11]
root        20     2  0 07:08 ?        00:00:00 [rcuos/12]
root        21     2  0 07:08 ?        00:00:00 [rcuos/13]
root        22     2  0 07:08 ?        00:00:00 [rcuos/14]
root        23     2  0 07:08 ?        00:00:00 [rcu_bh]
root        24     2  0 07:08 ?        00:00:00 [rcuob/0]
root        25     2  0 07:08 ?        00:00:00 [rcuob/1]
root        26     2  0 07:08 ?        00:00:00 [rcuob/2]
root        27     2  0 07:08 ?        00:00:00 [rcuob/3]
root        28     2  0 07:08 ?        00:00:00 [rcuob/4]
root        29     2  0 07:08 ?        00:00:00 [rcuob/5]
root        30     2  0 07:08 ?        00:00:00 [rcuob/6]
root        31     2  0 07:08 ?        00:00:00 [rcuob/7]
root        32     2  0 07:08 ?        00:00:00 [rcuob/8]
root        33     2  0 07:08 ?        00:00:00 [rcuob/9]
root        34     2  0 07:08 ?        00:00:00 [rcuob/10]
root        35     2  0 07:08 ?        00:00:00 [rcuob/11]
root        36     2  0 07:08 ?        00:00:00 [rcuob/12]
root        37     2  0 07:08 ?        00:00:00 [rcuob/13]
root        38     2  0 07:08 ?        00:00:00 [rcuob/14]
root        39     2  0 07:08 ?        00:00:00 [migration/0]
root        40     2  0 07:08 ?        00:00:00 [watchdog/0]
root        41     2  0 07:08 ?        00:00:00 [khelper]
root        42     2  0 07:08 ?        00:00:00 [kdevtmpfs]
root        43     2  0 07:08 ?        00:00:00 [netns]
root        44     2  0 07:08 ?        00:00:00 [xenwatch]
root        45     2  0 07:08 ?        00:00:00 [xenbus]
root        46     2  0 07:08 ?        00:00:01 [kworker/0:1]
root        47     2  0 07:08 ?        00:00:00 [writeback]
root        48     2  0 07:08 ?        00:00:00 [kintegrityd]
root        49     2  0 07:08 ?        00:00:00 [bioset]
root        50     2  0 07:08 ?        00:00:00 [kworker/u31:0]
root        51     2  0 07:08 ?        00:00:00 [kblockd]
root        52     2  0 07:08 ?        00:00:00 [ata_sff]
root        53     2  0 07:08 ?        00:00:00 [khubd]
root        54     2  0 07:08 ?        00:00:00 [md]
root        55     2  0 07:08 ?        00:00:00 [devfreq_wq]
root        57     2  0 07:08 ?        00:00:00 [khungtaskd]
root        58     2  0 07:08 ?        00:00:00 [kswapd0]
root        59     2  0 07:08 ?        00:00:00 [vmstat]
root        60     2  0 07:08 ?        00:00:00 [ksmd]
root        61     2  0 07:08 ?        00:00:00 [khugepaged]
root        62     2  0 07:08 ?        00:00:00 [fsnotify_mark]
root        63     2  0 07:08 ?        00:00:00 [ecryptfs-kthrea]
root        64     2  0 07:08 ?        00:00:00 [crypto]
root        76     2  0 07:08 ?        00:00:00 [kthrotld]
root        77     2  0 07:08 ?        00:00:00 [kworker/u30:1]
root        78     2  0 07:08 ?        00:00:00 [scsi_eh_0]
root        79     2  0 07:08 ?        00:00:00 [scsi_eh_1]
root        99     2  0 07:08 ?        00:00:00 [deferwq]
root       100     2  0 07:08 ?        00:00:00 [charger_manager]
root       142     2  0 07:08 ?        00:00:00 [kpsmoused]
root       160     2  0 07:08 ?        00:00:00 [kworker/0:2]
root       205     2  0 07:08 ?        00:00:00 [jbd2/xvda1-8]
root       206     2  0 07:08 ?        00:00:00 [ext4-rsv-conver]
root       408     1  0 07:08 ?        00:00:00 upstart-udev-bridge --daemon
root       413     1  0 07:08 ?        00:00:00 /lib/systemd/systemd-udevd --daemon
root       539     1  0 07:08 ?        00:00:00 upstart-socket-bridge --daemon
root       612     1  0 07:08 ?        00:00:00 dhclient -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
root       812     2  0 07:08 ?        00:00:00 [kauditd]
message+   874     1  0 07:08 ?        00:00:00 dbus-daemon --system --fork
root       907     1  0 07:08 ?        00:00:00 /lib/systemd/systemd-logind
syslog     915     1  0 07:08 ?        00:00:00 rsyslogd
root       931     1  0 07:08 ?        00:00:00 upstart-file-bridge --daemon
root      1055     1  0 07:08 tty4     00:00:00 /sbin/getty -8 38400 tty4
root      1058     1  0 07:08 tty5     00:00:00 /sbin/getty -8 38400 tty5
root      1062     1  0 07:08 tty2     00:00:00 /sbin/getty -8 38400 tty2
root      1063     1  0 07:08 tty3     00:00:00 /sbin/getty -8 38400 tty3
root      1065     1  0 07:08 tty6     00:00:00 /sbin/getty -8 38400 tty6
root      1118     1  0 07:08 ?        00:00:00 /usr/sbin/sshd -D
root      1120     1  0 07:08 ?        00:00:00 acpid -c /etc/acpi/events -s /var/run/acpid.socket
root      1124     1  0 07:08 ?        00:00:00 cron
daemon    1125     1  0 07:08 ?        00:00:00 atd
root      1243     1  0 07:08 tty1     00:00:00 /sbin/getty -8 38400 tty1
root      1244     1  0 07:08 ttyS0    00:00:00 /sbin/getty -8 38400 ttyS0
root     11544  1118  0 08:58 ?        00:00:00 sshd: ubuntu [priv]
ubuntu   11617 11544  0 08:58 ?        00:00:00 sshd: ubuntu@pts/0
ubuntu   11618 11617  0 08:58 pts/0    00:00:00 -bash
root     11634 11618  0 08:58 pts/0    00:00:00 sudo -i
root     11635 11634  0 08:58 pts/0    00:00:00 -bash
root     12774     1  0 09:14 ?        00:00:00 /lib/systemd/systemd-hostnamed
tomcat7  12861     1  3 09:14 ?        00:00:03 /usr/lib/jvm/default-java/bin/java -Djava.util.logging.config.file=/var/lib/tomcat7/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.awt.headless=true -Xmx128M -Djava.endorsed.dirs=/usr/share/tomcat7/endorsed -classpath /usr/share/tomcat7/bin/bootstrap.jar:/usr/share/tomcat7/bin/tomcat-juli.jar -Dcatalina.base=/var/lib/tomcat7 -Dcatalina.home=/usr/share/tomcat7 -Djava.io.tmpdir=/tmp/tomcat7-tomcat7-tmp org.apache.catalina.startup.Bootstrap start
root     12911 11635 23 09:16 pts/0    00:00:01 /opt/chef/embedded/bin/ruby --disable-gems /usr/bin/chef-client -l debug
root     13214 12911  0 09:16 ?        00:00:00 ps -ef
 (up to date)
  * apt_package[default-jdk] action install[2018-09-09T09:16:44+00:00] INFO: Processing apt_package[default-jdk] action install (tomcat::install line 15)
default-jdk:
  Installed: 2:1.7-51
  Candidate: 2:1.7-51
  Version table:
 *** 2:1.7-51 0
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
 (up to date)
Recipe: tomcat::tomcat7-configure
  * cookbook_file[/etc/default/tomcat7] action create[2018-09-09T09:16:44+00:00] INFO: Processing cookbook_file[/etc/default/tomcat7] action create (tomcat::tomcat7-configure line 6)
 (up to date)
  * template[/etc/tomcat7/tomcat-users.xml] action create[2018-09-09T09:16:44+00:00] INFO: Processing template[/etc/tomcat7/tomcat-users.xml] action create (tomcat::tomcat7-configure line 11)
 (up to date)
Recipe: tomcat::addpackages
  * apt_package[tomcat7-docs] action install[2018-09-09T09:16:44+00:00] INFO: Processing apt_package[tomcat7-docs] action install (tomcat::addpackages line 9)
tomcat7-docs:
  Installed: 7.0.52-1ubuntu0.15
  Candidate: 7.0.52-1ubuntu0.15
  Version table:
 *** 7.0.52-1ubuntu0.15 0
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     7.0.52-1 0
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
 (up to date)
  * apt_package[tomcat7-admin] action install[2018-09-09T09:16:44+00:00] INFO: Processing apt_package[tomcat7-admin] action install (tomcat::addpackages line 9)
tomcat7-admin:
  Installed: 7.0.52-1ubuntu0.15
  Candidate: 7.0.52-1ubuntu0.15
  Version table:
 *** 7.0.52-1ubuntu0.15 0
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     7.0.52-1 0
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
 (up to date)
  * apt_package[tomcat7-examples] action install[2018-09-09T09:16:44+00:00] INFO: Processing apt_package[tomcat7-examples] action install (tomcat::addpackages line 9)
tomcat7-examples:
  Installed: 7.0.52-1ubuntu0.15
  Candidate: 7.0.52-1ubuntu0.15
  Version table:
 *** 7.0.52-1ubuntu0.15 0
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     7.0.52-1 0
        500 http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
 (up to date)
[2018-09-09T09:16:44+00:00] DEBUG: Saving the current state of node ec2-18-234-187-117.compute-1.amazonaws.com
[2018-09-09T09:16:44+00:00] INFO: Chef Run complete in 4.430974699 seconds

Running handlers:
[2018-09-09T09:16:44+00:00] INFO: Running report handlers
Running handlers complete
[2018-09-09T09:16:44+00:00] INFO: Report handlers complete
Chef Client finished, 2/13 resources updated in 05 seconds
[2018-09-09T09:16:44+00:00] INFO: Sending resource update report (run-id: c3d71036-ab00-4b5d-8759-8230e3a637cd)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/34856585/45263238-37656300-b443-11e8-97c2-8d04df8d3b67.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/34856585/45263243-5c59d600-b443-11e8-8592-eec45570d6b2.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/34856585/45263245-6a0f5b80-b443-11e8-91aa-40903e8c84c0.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/34856585/45263247-75fb1d80-b443-11e8-8c0e-191ff70f46a4.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/34856585/45263251-87dcc080-b443-11e8-97d6-2b8285c8ad4a.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/34856585/45263255-97f4a000-b443-11e8-9117-36a3ec9335f3.png)

**Comment by ghost** [comment]
STDOUT:
: not foundc/init.d/tomcat7: 4: /etc/default/tomcat7:
---- End output of /etc/init.d/tomcat7 stop ----
Ran /etc/init.d/tomcat7 stop returned 127

**Comment by shaikkhajaibrahim** [comment]
Upload your cookbook here rather than screen shots
