### ISSUE TITLE
file download from internet for tomcat7

### ISSUE THREAD

**Issue by ajs777** [QT-DevOps/DevOpsIssues#155]
when i try to execute my playbook iam getting this error can u plz any one try to help me

![screenshot 50](https://user-images.githubusercontent.com/37798362/45264325-6afeb800-b458-11e8-9bd3-8d96a3046e85.png)
![screenshot 49](https://user-images.githubusercontent.com/37798362/45264326-6afeb800-b458-11e8-9660-21da85d52458.png)

**Comment by arunkumar127** [comment]
@ajs777 
Maintain correct spaces for notify.
notify should be exactly below module name.

**Comment by ajs777** [comment]
thank u arun garu
error is solved
