### ISSUE TITLE
when module issue 

### ISSUE THREAD

**Issue by ajs777** [QT-DevOps/DevOpsIssues#156]
when i try use when module for my playbook, debian family os is passing, centos family os is skipping can u plz tell me

![screenshot 52](https://user-images.githubusercontent.com/37798362/45265321-a2746100-b466-11e8-8df8-dc56d74ed251.png)
![screenshot 51](https://user-images.githubusercontent.com/37798362/45265323-a56f5180-b466-11e8-936b-ffcab043ba5a.png)

**Comment by arunkumar127** [comment]
@ajs777 
HTTPD has not been installed on CentOS.
Check Task HTTPD Install task, It has been skipped.
Once check your Hosts file and modify hosts section. Upload screenshot of Hosts file here once.

**Comment by arunkumar127** [comment]
@ajs777 
HTTPD has not been installed on CentOS.
Check Task HTTPD Install, It has been skipped.

For RedHat, when condition is
when: ansible_os_family == "**RedHat**"
(H Capital)

**Comment by shaikkhajaibrahim** [comment]
arunkumar127 solution will work & one more thing 
Service name should be **httpd** not **Httpd**
