### ISSUE TITLE
GIT CLONE ISSUE

### ISSUE THREAD

**Issue by saireddy224** [QT-DevOps/DevOpsIssues#158]
while executing game of life in jenkins .git is not cloning the repo .it is throwing timeout error
![capture](https://user-images.githubusercontent.com/7966678/45285085-d9e31c00-b4ff-11e8-83bf-2fb17b473b12.PNG)

**Comment by shaikkhajaibrahim** [comment]
Can you switch as jenkins user & execute git clone manually & share results

**Comment by shaikkhajaibrahim** [comment]
Duplicate #141
