### ISSUE TITLE
Git Hub

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#159]
I have created a anew folder and .git is also created. first time made changes in the visual code are getting captured when checked on Git status.
Once add and commit were made, 2nd time changes are not getting captured.
After making changes  git status message is giving below msg.

$ git status
On branch QA
nothing to commit, working tree clean

Even I cant see color change in visual code after making 1st change.

Please help me in understanding this

**Comment by manikanta35** [comment]
Hi Aamukta,
 Basically git doesn't identify empty folders it identifies only files so first you create some files and then try.
