### ISSUE TITLE
slave is not getting connected from windows machine and giving error with 38885

### ISSUE THREAD

**Issue by Rameshdutt80** [QT-DevOps/DevOpsIssues#16]
created windows machine as slave
![capture1](https://user-images.githubusercontent.com/37854691/40636029-b06e1d02-631a-11e8-9bd2-45a13dcf93b3.JPG)

![capture2](https://user-images.githubusercontent.com/37854691/40636060-d8537df8-631a-11e8-8ad6-a7963de028c6.JPG)
When iam trying to launch slave from windows iam facing this error
![capture3](https://user-images.githubusercontent.com/37854691/40636063-ddbf5e1a-631a-11e8-8c53-446b4f8bb90b.JPG)
![capture4](https://user-images.githubusercontent.com/37854691/40636070-e36cbb00-631a-11e8-9b7b-810dde0368f6.JPG)

**Comment by shaikkhajaibrahim** [comment]
Is the port 38885 open in Security Group/Firewall

**Comment by Rameshdutt80** [comment]
The above error is resolved and again same kind of error is coming for the port 45663

I have tried to add the same port in windows firewall with advanced security in my slave system.
and again same error is repeating
![capture6](https://user-images.githubusercontent.com/37854691/40699449-f34b2c14-63f1-11e8-83d0-e0a26eda95fb.JPG)

**Comment by shaikkhajaibrahim** [comment]
Where is Jenkins Server is the Port opened in Server

**Comment by Rameshdutt80** [comment]
jenkins server is hosted in AWS. And given all trafic in security group.

**Comment by Rameshdutt80** [comment]
Given Alltraffic in AWS with source ::/0 then i got an same kind of error which i given in the above.

After that i have changed the source as given in the below

![capture001](https://user-images.githubusercontent.com/37854691/40756418-28ecf1a4-64a1-11e8-8382-948c198e6a95.JPG)

after launching the slave it got connected.
![image](https://user-images.githubusercontent.com/37854691/40756441-4bd2edf4-64a1-11e8-8ead-2d3ff30ea012.png)

Thank you
