### ISSUE TITLE
Azure ARM templates

### ISSUE THREAD

**Issue by ksateesh22** [QT-DevOps/DevOpsIssues#160]
I am going to start a new job next week and need to understand ARM templates, how to modify and deploy them at the bare minimum. Can some one help with links and videos

**Comment by shaikkhajaibrahim** [comment]
1. https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-deploy
2. https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authoring-templates
3. https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-deploy-cli
4. https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-deploy-portal
5. https://docs.microsoft.com/en-us/azure/azure-resource-manager/
