### ISSUE TITLE
bash script for vagrant

### ISSUE THREAD

**Issue by sunilkumarkorupolu** [QT-DevOps/DevOpsIssues#162]
help me in doing this.
1. Write a bash script that creates and boots Vagrant box
 (https://vagrant.io)
 with Ubuntu
 2. Write an Ansible script that connects to this Vagrant box
 and does the following on it:
 - Creates a user "testuser"
 - Sets the system's timezone to
 "Asia/Kolkata"
 - Uploads a random local file from the host into the
 /home/testuser/ directory
 - Installs python, supervisord, and the latest version of
 consul

**Comment by shaikkhajaibrahim** [comment]
Please this forum is not to do tasks. If you are struck in implementing something/face issues.

By the way for this task use ansible provisioning in vagrant
Refer https://www.vagrantup.com/docs/provisioning/ansible.html
