### ISSUE TITLE
Cloudformation from jenkins 

### ISSUE THREAD

**Issue by Naveendevopss** [QT-DevOps/DevOpsIssues#163]
Sir how to upgrade python 2.7.6 to latest in ubuntu 14.04 .

Errror:-
 Started by user Naveen
Building on master in workspace /var/lib/jenkins/workspace/CF-FROM-JN
[CF-FROM-JN] $ /bin/sh -xe /tmp/jenkins6269894707456584419.sh
+ aws cloudformation create-stack --stack-name Myteststack --template-body file:\C:CFFROMJENKINSfirst.json
/usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:369: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning

An error occurred (ValidationError) when calling the CreateStack operation: Template format error: unsupported structure.
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by lingaswamy143** [comment]
Hi Naveen you can upgrade a particular package also follow below
apt-get upgrade
apt-get install --only-upgrade python       ##python must be installed before upgrading

**Comment by shaikkhajaibrahim** [comment]
Is this done?
