### ISSUE TITLE
Error while install Jenkins in ubuntu

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#164]
![image](https://user-images.githubusercontent.com/42566531/45582407-e636f280-b8cc-11e8-813f-a0ba73c8792f.png)
[](url)

ubuntu@ip-172-31-88-32:/opt$ sudo wget http://www-eu.apache.org/dist/maven/maven                                                                                                             -3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz
--2018-09-15 04:19:23--  http://www-eu.apache.org/dist/maven/maven-3/3.5.3/binar                                                                                                             ies/apache-maven-3.5.3-bin.tar.gz
Resolving www-eu.apache.org (www-eu.apache.org)... 95.216.24.32, 2a01:4f9:2a:185                                                                                                             f::2
Connecting to www-eu.apache.org (www-eu.apache.org)|95.216.24.32|:80... connecte                                                                                                             d.
HTTP request sent, awaiting response... 404 Not Found
2018-09-15 04:19:23 ERROR 404: Not Found.

____________________

Please help me in fixing this issue

**Comment by raviops100** [comment]
Hi Aamukta,

Can you please try to use same command but version is 3.5.4 

sudo wget http://www-eu.apache.org/dist/maven/maven -3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz

sudo tar xzf apache-maven-3.5.4-bin.tar.gz

sudo ln -s /opt/apache-maven-3.5.4/bin/mvn /usr/bin/mvn

while setting maven environment varaibles also fallow version 3.5.4

Thanks
Ravi

**Comment by arunkumar127** [comment]
@Aamukta
If you're using Jenkins Installation Document, then use this link to download Maven gz file. (For v3.5.3)
https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.5.3/apache-maven-3.5.3-bin.tar.gz

**Comment by arunkumar127** [comment]
Or use v3.5.4
http://apache.mirrors.hoobly.com/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz

**Comment by Aamukta** [comment]
> Hi Aamukta,
> 
> Can you please try to use same command but version is 3.5.4
> 
> sudo wget http://www-eu.apache.org/dist/maven/maven -3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
> 
> sudo tar xzf apache-maven-3.5.4-bin.tar.gz
> 
> sudo ln -s /opt/apache-maven-3.5.4/bin/mvn /usr/bin/mvn
> 
> while setting maven environment varaibles also fallow version 3.5.4
> 
> Thanks
> Ravi

Hi Ravi,
It worked now.. Thanks.

**Comment by Aamukta** [comment]
> Or use v3.5.4
> http://apache.mirrors.hoobly.com/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz

Hi Arun, It worked. Thanks
