### ISSUE TITLE
Unable to access Jenkins page

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [QT-DevOps/DevOpsIssues#165]
Hi Friends
Is it mandatory to select aws u16 - t2.large instance for jenkins to get started ???
An aws u16 - t2.micro (free tier) wont work ??? bcoz i launched u16 - t2.micro (free tier) for jenkins, but unable to launch jenkins, page says "This site can't be reached"

**Comment by arunkumar127** [comment]
@Sajid
t2.micro will be enough to run Jenkins.
Check whether Jenkins service is up & running or not.
$ sudo service jenkins status

If it is not running, try to start it.
$ sudo service jenkins (start | restart)

**Comment by raviops100** [comment]
Hi Sajid,

It is not mandatory to install jenkins in aws t2.large machine

we can install jenkins t2.micro also 

i feel in your case AWS INSTANCE you did not open port for jenkins 8080

Just add security groups ALL TCP rule. even if it not working

please follow below steps

JENKINS_HTTPS_LISTEN_ADDRESS="Public IP"  >> /etc/sysconfig/jenkins

Then

/etc/init.d/jenkins restart

**Comment by SajidAliKhanMohammed** [comment]
Ok, sure Ravi, i will try this.. 
Thanks

**Comment by SajidAliKhanMohammed** [comment]
Sure Arun..

Thanks
Sajid

**Comment by shaikkhajaibrahim** [comment]
Is it working?

**Comment by SajidAliKhanMohammed** [comment]
Yes, working now..
