### ISSUE TITLE
Build fails while using Maven project with Artifactory

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#167]
Hi,
I configured Jenkins my Win 10 desktop and managed to build successfully using freestyle project. Next I ran the .bat file for Artifactory, managed to login and create a repository. 

After adding Artifactory plugin in Jenkins I created a Maven project. But this time build fail after a long time, with one of the errors being:-  No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK? 
I tried installing jdk again but choco said it is already installed and I may force a reinstall. 
I've attached the console logs herewith.

[Console Logs.txt](https://github.com/QT-DevOps/DevOpsIssues/files/2387327/Console.Logs.txt)

I tried restarting my system, still, the Maven Project fails but the Freestyle Project with or without artifactory, both build successfully. With Artifactory option, the freestyle project's build history doesn't show any artifactory link, nor is it stored in the repository.
Please help.
-Ramesh

**Comment by raviops100** [comment]
Hi Ramesh,

It Seems jenkins not able to find out JDK in your machine.

In windows 10 Machine JAVA MUST BE INSTALLED AND ENVIRONMENT VARAIBLES you need to set like this below

JAVA_HOME : C:\Program Files\Java\jdk1.8.0_112

PATH      : C:\Program Files\Java\jdk1.8.0_112\bin

IN JENKINS UI Do below setting

Go To Jenkins -> Manage Jenkins -> Configure System -> JDK. 
Configure path to the JDK under JAVA_HOME field.

Thanks
Ravi

**Comment by vjskothu** [comment]
Hi Ramesh,

Can you post full log here.  did you configure security and security-settings.xml  in .M2 folder

Regards
Kothandaraman

**Comment by vjskothu** [comment]
mvn -emp password 
mvn -ep password

place settings and setting-securit.xml files in .M2 folder.
Please cross check Java_home and M2 home also. 



Regards
`Kothandaraman

**Comment by rameshm78** [comment]
Hi Kothandaraman,

I have already attached the console logs in the file Console Logs.txt in my first post. Please let me know if some other logs need to be extracted. If yes, how?


What are these commands for?:-
mvn -emp password
mvn -ep password
Where can I get the "settings and setting-securit.xml files" from? Let me know, so that I can place it in the .M2 folder. 
How do I cross check between Java_home and M2 home?
My M2 folder looks as follows:-
![image](https://user-images.githubusercontent.com/40449948/45794166-f6771500-bcb2-11e8-9c19-a53df034ddbf.png)

The Environmental variables are set as follows:-
![image](https://user-images.githubusercontent.com/40449948/45794198-1c041e80-bcb3-11e8-81ee-681fd8de460e.png)

Please help me proceed.

Regards
Ramesh

**Comment by vjskothu** [comment]
![screen shot 2018-09-20 at 7 05 18 am](https://user-images.githubusercontent.com/40923564/45795335-edcb1280-bca3-11e8-8297-eca9f385be96.png)
![screen shot 2018-09-20 at 7 08 53 am](https://user-images.githubusercontent.com/40923564/45795384-2ec32700-bca4-11e8-8f73-3956a82959ff.png)


PLEASE CHECK --> CONFIGURE SYSTEM --JDK

These two files for connecting Jenkins --> to artifactory repository
["setting.txt"](https://github.com/QT-DevOps/DevOpsIssues/files/2399622/setting.txt)

I am not able to attach those xml files --> I have added as text file. please convert it as xml files.  

Once this setup is done.. after building it will saved in Artifactory
![screen shot 2018-09-20 at 7 22 15 am](https://user-images.githubusercontent.com/40923564/45795779-0d633a80-bca6-11e8-89e5-83f20df42b7d.png)
Regards
Kothandaraman
I

**Comment by rameshm78** [comment]
Thank you very much Kothandaraman.

After adding the JAVA_HOME path in Global configuration, my build was successful and it saved in artifactory.
![image](https://user-images.githubusercontent.com/40449948/45805050-5f728300-bcdb-11e8-8f52-edfa6e04fc87.png)

Q1. Where should I add the two xml files you have given? 
Q2. It contains some encrypted passwords also, where will I get those from, in my system?

**Comment by vjskothu** [comment]
Dear Ramesh,

Thanks. Your results saved in artifactory your steps are correct if you want to send encrypted password from maven to artifactory only you have to follow these steps. I am also not sure, I am new to devops and learning, 
KAJA SIR has to answer.

regards
Kothandaraman.

**Comment by rameshm78** [comment]
Dear Kothandaraman,

Thanks a lot for all the help.

Regards
Ramesh
