### ISSUE TITLE
Artifactory PDF link Online

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#168]
Hi I am unable to view Artifactory PDF link on quality thought website.
Getting 404 error. Could you please provide me..

**Comment by raviops100** [comment]
Hi Aamukta,
[Configuring-Artifactory.pdf](https://github.com/QT-DevOps/DevOpsIssues/files/2387672/Configuring-Artifactory.pdf)

Thanks
Ravi
