### ISSUE TITLE
in window 10 pipeline project failure

### ISSUE THREAD

**Issue by BALU6** [QT-DevOps/DevOpsIssues#17]
![in windows 10](https://user-images.githubusercontent.com/34449707/40640085-135ca868-6332-11e8-8bf7-b2ae8b4cf684.PNG)

**Comment by shaikkhajaibrahim** [comment]
Set the Environment Variable in Global Tools Sections

**Comment by BALU6** [comment]
Sir there also I had set the environment variable correct format

**Comment by shaikkhajaibrahim** [comment]
Execute echo %JAVA_HOME% in Invoke Windows Batch in build the value should point out JAVA JDK 
for eg "C:\Program Files\Java\jdk1.8.0_152" in windows

**Comment by BALU6** [comment]
Yes it's showing same directory

**Comment by shaikkhajaibrahim** [comment]
Can you share the screen shot of JEnkins Console Output

**Comment by BALU6** [comment]
sir now build was success after executing echo %JAVA_HOME% in cmd
