### ISSUE TITLE
Multiple replication controller for diff apps

### ISSUE THREAD

**Issue by gmajay** [QT-DevOps/DevOpsIssues#170]
Hi Sir,

What if multiple replication controllers enabled with matching labels ? ain't these give trouble while deploying. ? Sometimes matching labels in RC of other application keeps the pod running in the cluster even after the deployment of new version. Isn't it headache. ?

**Comment by shaikkhajaibrahim** [comment]
Yes labels should be used carefully. Add version label  with different RC's atleast

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
