### ISSUE TITLE
vagrant box issue

### ISSUE THREAD

**Issue by bansalniranjan** [QT-DevOps/DevOpsIssues#171]
I am starting my downloaded box but getting following error:

λ  vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'hashicorp/precise64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'hashicorp/precise64' is up to date...
==> default: Setting the name of the VM: hello_default_1537323313708_73688
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "4dfe50ae-5416-4716-a33b-5654ddd47488", "--type", "headless"]

Stderr: VBoxManage.exe: error: The virtual machine 'hello_default_1537323313708_73688' has terminated unexpectedly during startup with exit code -1073741819 (0xc0000005).  More details may be available in 'C:\Users\Niranjan.Bansal\VirtualBox VMs\hello_default_1537323313708_73688\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

E:\projects\hello

**Comment by arunkumar127** [comment]
@Niranjan
Please share your complete log file generated in your logs folder.

**Comment by bansalniranjan** [comment]
[VBoxHardening.log](https://github.com/QT-DevOps/DevOpsIssues/files/2396388/VBoxHardening.log)

**Comment by bansalniranjan** [comment]
Bios it is enabled. Hyperv is enabled . Tried with many different versions. Spent 2-3 hrs but no luck

**Comment by shaikkhajaibrahim** [comment]
Can you try creating VM manually

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bansalniranjan** [comment]
Same error manually also

**Comment by shaikkhajaibrahim** [comment]
Can you share your os details?

**Comment by bansalniranjan** [comment]
Windows 10 Enterprise

**Comment by shaikkhajaibrahim** [comment]
Problem with virtual box. Can you  sharebyour OS details

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by shaikkhajaibrahim** [comment]
Can you check if hyperv is enabled. You cannot run two hypervisor s.
Disable hyperv & continue

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bansalniranjan** [comment]
tried that too. No luck

**Comment by raviops100** [comment]
Hi bansalniranjan,

Can you please try below specific versions

FOR WINDOWS 10 :::


ORACLE VM ::: 5.1.26 64-bit

vagrant ::::  1.9.7  64-bit

git  :::      2.16  64-bit (or) any latest version of git also fine  

Thanks
Ravi

**Comment by bansalniranjan** [comment]
Sure Let me try and get back

**Comment by rajd1** [comment]
> 
> 
> Sure Let me try and get back

Can you try this
http://teckbase.blogspot.com/2015/05/oracle-virtualbox-error-0xc0000005.html

**Comment by vjskothu** [comment]
I tried in windows 10 enterprise. It is working bansalniranjan.
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'hashicorp/precise64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'hashicorp/precise64' is up to date...
==> default: Setting the name of the VM: PROJECTS_default_1537380586241_35555
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.2.0
    default: VirtualBox Version: 5.2
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/user/Desktop/PROJECTS

Thanks
Kothandaraman

**Comment by bansalniranjan** [comment]
Hi Kothandaraman , I am in the process of uninstalling everything and installing:
ORACLE VM ::: 5.1.26 64-bit

vagrant :::: 1.9.7 64-bit

git ::: 2.16 64-bit (or) any latest version of git also fine


I will try vagrant up then and will touch base in 2-3 hrs.

**Comment by bansalniranjan** [comment]
So i faced the same error again. Now following the link that you shared. Tell me the virtualbox version with which you got success ? I am not able to find VirtualBox v.3.28 version

**Comment by bansalniranjan** [comment]
Is it VirtualBox Version: 5.2?  shall i go ahead and install the same ?

**Comment by vjskothu** [comment]
VirtualBox Graphical User Interface
Version 5.2.4 r119785 (Qt5.6.2)
Copyright © 2017 Oracle Corporation and/or its affiliates. All rights reserved.

**Comment by shaikkhajaibrahim** [comment]
I would recommend using hyperv if virtual box is not working out. Don't waste too much time on this.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bansalniranjan** [comment]
ok will give 1 more hr else will use the hyperv . Thanks

**Comment by bansalniranjan** [comment]
Fixed it and it is working for me now thanks.

**Comment by rajd1** [comment]
> Fixed it and it is working for me now thanks.

how did you fix it ? please share the solution so it may help others in future.
