### ISSUE TITLE
Bamboo: MSBuild failing using bamboo, In jenkins i am able to build the code

### ISSUE THREAD

**Issue by vjskothu** [QT-DevOps/DevOpsIssues#172]
I have tried to Install bamboo in Azure and tried to build ms build project,  Everytime I receive the error message not able to *.rsp file and build failed.

### 16-Sep-2018 08:00:23	Failing task since return code of [C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe @C:\Windows\system32\config\systemprofile\AppData\Local\Temp\AC-AP-JOB1-28-MsBuildTaskType-4669440742136683751.rsp] was 1 while expected 0

Regards
Kothandaraman

**Comment by shaikkhajaibrahim** [comment]
we don't support issues on bamboo... as it is not part of our curiculum
