### ISSUE TITLE
vagrant

### ISSUE THREAD

**Issue by ramakrishna228** [QT-DevOps/DevOpsIssues#173]
i am using windows 10 os.for enable virtualization in add or remove programs hyper-v is not displayed

**Comment by bansalniranjan** [comment]
Check "Turn Windows features on or off " and disable / enable in that area

Note: I am a student and not official from inst.

**Comment by arunkumar127** [comment]
Hi @ramakrishna228 
Goto **Programs  and Features** (Run appwiz.cpl), Click on **Turn Windows features on or off**
In next window Check Hyper-V to enable it.
![1](https://user-images.githubusercontent.com/40756184/45822463-25b87100-bd09-11e8-9b86-ab225dbc9f0f.jpg)

Or run **_optionalfeatures_** from Run prompt, it will open **Turn Windows features on or off**

**Comment by SuneelkumaarNarayana** [comment]
I think, You will not able to see Hyper-V bcz you have ''windows 10 Home''. it is available in other than 'windows 10 Home' youshouldto OS Windows 10 professional or Education
