### ISSUE TITLE
yaml run through jenkins downstrean 

### ISSUE THREAD

**Issue by ghost** [QT-DevOps/DevOpsIssues#174]
![image](https://user-images.githubusercontent.com/34856585/45827196-8ba9f600-bd13-11e8-8287-48ef250d324f.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/34856585/45827276-b5fbb380-bd13-11e8-83a7-e535b7e37b20.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/34856585/45827319-c9a71a00-bd13-11e8-8f0e-92ff544cc030.png)

**Comment by shaikkhajaibrahim** [comment]
Can you show the o/p of the command if you run this playbook manually as jenkins user in jenkins machine

**Comment by lingaswamy143** [comment]
Naresh generate ssh-key for jenkins user and using ssh-copy-id command copy the public key to host machine.
