### ISSUE TITLE
While i try to run mvn package command on jenkins it throughs an error 

### ISSUE THREAD

**Issue by kampatinagesh** [QT-DevOps/DevOpsIssues#176]
Hi Guys,

[ERROR] Error executing Maven.
[ERROR] The specified user settings file does not exist: /opt/apache-maven-3.5.4/bin

![image](https://user-images.githubusercontent.com/43181712/45916529-63da9f80-be85-11e8-826a-12ea0ef7dd7b.png)

Please help me.

**Comment by raviops100** [comment]
Hi Nagesh,
i guess this issue related to maven Environment variables setting

if your running Jenkins on WINDOWS for maven below are settings

M2_HOME=D:\Maven ====> your local machine path where maven installed )
path=D:\Maven\bin

RUNNING IN JENKINS IN LINUX Environment

M2_HOME=/opt/apache-maven-3.5.4
PATH=$PATH:$M2_HOME/bin
export M2_HOME
export PATH

Can Please cross check same maven env settings you have done in your machine

Thanks
Ravi

**Comment by kampatinagesh** [comment]
This my /etc/profile config file:
=======================

ubuntu@ip-172-31-16-157:~$ sudo cat /etc/profile
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

if [ "$PS1" ]; then
  if [ "$BASH" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "`id -u`" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
export JAVA_HOME=/usr/lib/jvm/java-8-oracle/
export PATH=$PATH:$HOME/bin:$JAVA_HOME/bin
export M2_HOME=/opt/apache-maven-3.5.4/
export M2="M2_HOME"bin
export PATH=$PATH:$M2

**Comment by ghost** [comment]
Hi Nagesh,

AS PER OUR INSTALLATION DOC JENKINS ON UBUNTU 

3 line just remove export before M2_HOME
4 line add PATH=$PATH:$M2_HOME/bin
5 line export M2_HOME
6 line export PATH

entire file look like this below copy below lines and paste /etc/profile file and try to build once

export JAVA_HOME=/usr/lib/jvm/java-8-oracle/
export PATH=$PATH:$HOME/bin:$JAVA_HOME/bin
M2_HOME=/opt/apache-maven-3.5.4
PATH=$PATH:$M2_HOME/bin
export M2_HOME
export PATH

Thanks
Ravi

**Comment by kampatinagesh** [comment]
Even i try to use  your /etc/profiles file but no luck

**Comment by kampatinagesh** [comment]
![image](https://user-images.githubusercontent.com/43181712/45927523-f779a200-bf51-11e8-8060-08e4488d53a1.png)

**Comment by kampatinagesh** [comment]
root@ip-172-31-16-157:/opt# sudo cat /etc/profile
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

if [ "$PS1" ]; then
  if [ "$BASH" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "`id -u`" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
export JAVA_HOME=/usr/lib/jvm/java-8-oracle/
export PATH=$PATH:$HOME/bin:$JAVA_HOME/bin
M2_HOME=/opt/apache-maven-3.5.4
PATH=$PATH:$M2_HOME/bin
export M2_HOME
export PATH
root@ip-172-31-16-157:/opt#

**Comment by kampatinagesh** [comment]
root@ip-172-31-16-157:/opt# mvn -version
'Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z)
Maven home: /opt/apache-maven-3.5.4
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-1067-aws", arch: "amd64", family: "unix"
root@ip-172-31-16-157:/opt#

**Comment by kampatinagesh** [comment]
root@ip-172-31-16-157:/opt# java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
root@ip-172-31-16-157:/opt#

**Comment by raviops100** [comment]
Hi Nages,

Can you please try this once it may work i am not sure

After installing maven we get setting.xml you need to copy this setting.xml into .m2 folder

in linux below are commands

cd ~/.m2 

Probably you need to copy settings.xml in your .m2 folder:

cp /usr/local/bin/apache-maven-3.5.4/conf/settings.xml .m2/

If no .m2 folder exists:

mkdir -p ~/.m2

Thanks
Ravi

**Comment by revathi-muthana123** [comment]
Hi,
Please verify your maven version & the path where your maven installed.
Then specify that particular path in "/etc/profile"
sudo vi /etc/profile
export M2_HOME=/opt/usr/share/maven (mention your maven path)
export PATH=$PATH:$M2_HOME/bin

Thanks & Regards
Revathi

**Comment by raviops100** [comment]
Hi Nages,

Any Progress on this issue

while running JENKINS JOB in the build step select 
invoke top level maven target there in goals tab : give package not mvn package
it seems like simple reason but it fails can you please cross check once in build job

Thanks
Ravi

**Comment by veerendradevops** [comment]
hai nagesh,
 have you gone with freestyle or pipeline project for this job?? if it is pipeline project, can you post that code once

**Comment by kampatinagesh** [comment]
issue resolved thanks guys for support.

**Comment by ramu424** [comment]
Started by user adminuser
Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/hello-world
No credentials specified
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/ramu424/hello-world.git # timeout=10
Fetching upstream changes from https://github.com/ramu424/hello-world.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/ramu424/hello-world.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision f88329b44c6b54de79495d81c86015a7034f6efe (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f f88329b44c6b54de79495d81c86015a7034f6efe # timeout=10
Commit message: "initial commit"
First time build. Skipping changelog.
ERROR: Maven Home null doesnt exist
Finished: FAILURE

**Comment by Capt-Ejaz** [comment]
> issue resolved thanks guys for support.

hello 

I need your favor , I am facing the same issue even I tried every best possible scenario to resolved the maven issue could you please help me how do you resolved this issue

Thanks
