### ISSUE TITLE
Vagrant share

### ISSUE THREAD

**Issue by shaikkhajaibrahim** [QT-DevOps/DevOpsIssues#178]
[myubuntu.zip](https://github.com/QT-DevOps/DevOpsIssues/files/2407836/myubuntu.zip)

Download this file

unzip 
enter into folder 
vagrant up

**Comment by amit2793** [comment]
Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\chocolateyInstall.ps1.
this i am getting when i am trying to install virtual box and i have upgraded PS to5.1 from 2.0..

**Comment by HunterXHunters** [comment]
**I have an issue with vagrant share command.**  
After reading the Vagrant documentation, got to know about plugins and interesting topic for sharing my Vagrant environment with anyone in the world. 

Steps I have followed:
$ vagrant plugin install vagrant-share
$ vagrant share

**ERROR**
The `classic` driver has been deprecated.

**Comment by shaikkhajaibrahim** [comment]
Vagrant share is not a secure way used in enterprise. So it is intentionally skipped. I will not encourage using this as this has no enterprise relevance
________________________________

**Comment by amit2793** [comment]
hello sir ,you download linux flavours before and then you executed vagrant up command..so how to find correct os for vagrant box to installl without downloading from vagrant cloud..

**Comment by shaikkhajaibrahim** [comment]
google ;)
