### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by amit2793** [QT-DevOps/DevOpsIssues#179]
when i am installing virtualbox from cmd or powershell its showing error "Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\chocolateyInstall.ps1'."...why..??

**Comment by arunkumar127** [comment]
@amit2793 
Can you please share screenshot of the error which you got.
Have you run CMD/ Powershell as an Administrator? (Elevated privilege)

**Comment by amit2793** [comment]
how to add screenshot

**Comment by amit2793** [comment]
![error](https://user-images.githubusercontent.com/26686554/45919932-006b6480-bebb-11e8-93a4-2f78586531e9.jpeg)
 this ...
powershell is not opening in admin mode

cannot install vagrant also..

same error as above

**Comment by ramana152** [comment]
@amit2793  Please check the your power shell version .. If it 2.x please upgrade to 4.x or 5.0 , Then you can open power shell as a Run as administrator. Then you can install all the sodfwares..

**Comment by amit2793** [comment]
yes it is 2.0...and what about cmd why i am getting problem in that...can you provide me link to upgrade powershell
![vagrant error](https://user-images.githubusercontent.com/26686554/45925183-30a01b00-bf2e-11e8-8a23-60a338ce36fb.jpeg)
![virtulabox error](https://user-images.githubusercontent.com/26686554/45925184-3138b180-bf2e-11e8-878c-a9242341f501.jpeg)

**Comment by ramana152** [comment]
choco upgrade powershell --version 4.0.20141001   please try this command in Powershell...

**Comment by arunkumar127** [comment]
@Amit
Are you using Windows 7 or Windows 10?
If Win7, then check version of Powershell.

Run get-host in Powershell to check version.
If it is 2.x, then upgrade to 4.x using command provided by Ramana above.

**Comment by amit2793** [comment]
why problem is occuring in cmd then...???
![powershell error](https://user-images.githubusercontent.com/26686554/45925781-becdce80-bf39-11e8-8f2a-3a587fd918d8.png)
 error: Windows update  could not be installed because of error 2147943458 "The service cannot be started, either because it is disabled or because it has no enabled devices associated with it." (Command line: ""C:\Windows\System32\wusa.exe" "C:\Users\Administrator\AppData\Local\Temp\chocolatey\PowerShell\5.1.14409.20180811\PowerShellInstall.MSU" /quiet /norestart /log:"C:\Users\Administrator\AppData\Local\Temp\chocolatey\PowerShell-Install-201809230216.evtx" ")

**Comment by amit2793** [comment]
I have upgrade powershell to 5.1 still virtual box is not installing

**Comment by shaikkhajaibrahim** [comment]
Can you install virtual box manually & share the results.
If it fails manually choco also fails

**Comment by shaikkhajaibrahim** [comment]
@arunkumar127  can you login into the machine & try

**Comment by arunkumar127** [comment]
@shaikkhajaibrahim Yes sir I'll try.

@amit2793 If you have teamviewer installed in your machine, once mail me arunkumardevops127@gmail.com.
If you are in classroom meet me once.

Regards
Arun Kumar

**Comment by amit2793** [comment]
ok..thanks

**Comment by hamsa-2001** [comment]
Hi @amit2793,

I'm also facing the same error. Could you please help me

![Image](https://github.com/user-attachments/assets/5e6e8bb9-14d4-4826-b52a-f333b4ebf9c1)
