### ISSUE TITLE
jenkins-Jfrog Nothing populating artifacts in Jfrog After build success

### ISSUE THREAD

**Issue by veerendradevops** [QT-DevOps/DevOpsIssues#18]
Hi..
  After building job in jenkins along with Jfrog the build result got success.But while redirectig to Jfrog link
iam unable to find artifacts which i have build.Even i have created test_repo in Jfrog and also tried with default repository which is given jfrog.
![screenshot 1](https://user-images.githubusercontent.com/37468369/40641334-e3bb5ab4-6336-11e8-920f-1f2ebb691393.png)
![screenshot 2](https://user-images.githubusercontent.com/37468369/40641335-e3ebc7a8-6336-11e8-8aec-c110966c7b88.png)
![screenshot 3](https://user-images.githubusercontent.com/37468369/40641336-e41ebd8e-6336-11e8-91ba-30546e24e0f6.png)

Could you help me out for the same.

**Comment by shaikkhajaibrahim** [comment]
Should configure as shown 
![artifactoryconfig1](https://user-images.githubusercontent.com/2438317/40653411-aff267c8-6358-11e8-8837-8c9885ee5ff4.PNG)

![artifactoryconfig2](https://user-images.githubusercontent.com/2438317/40653417-b550bd28-6358-11e8-8b7f-81f08ea35954.PNG)

![artifactoryconfig3](https://user-images.githubusercontent.com/2438317/40653428-baea1810-6358-11e8-817d-e32a25b789d1.PNG)

![artifactoryconfig4](https://user-images.githubusercontent.com/2438317/40653434-c09daa42-6358-11e8-92fa-605f1c2b0ebb.PNG)
