### ISSUE TITLE
Here is Azure CLI script to create 3tier architecture 

### ISSUE THREAD

**Issue by ksateesh22** [QT-DevOps/DevOpsIssues#180]
Here is Azure CLI script to create 3tier architecture. 
1. Create Resource group
2. Create Virtual Network and subnets
3. Create Network Security groups and Rules

$resgroupName="fromcli"
$location="centralus"
$vNetName="3tier"
$subnet1="business"
$subnet2="websubnet"
$subnet3="data"
$subnet4="mgt"
$subnet5="AD"
$nsgBusiness="nsgBusiness"
$nsgData="nsgData"

az group create --name $resgroupName --location $location
az network vnet create --name $vNetName --resource-group $resgroupName --address-prefixes "10.2.0.0/16" --location $location --subnet-name $subnet1 --subnet-prefix "10.2.1.0/24"
az network vnet subnet create --name $subnet2 --resource-group $resgroupName --vnet-name $vNetName --address-prefix "10.2.2.0/24"
az network vnet subnet create --name $subnet3 --resource-group $resgroupName --vnet-name $vNetName --address-prefix "10.2.3.0/24"
az network vnet subnet create --name $subnet4 --resource-group $resgroupName --vnet-name $vNetName --address-prefix "10.2.4.0/24"
az network vnet subnet create --name $subnet5 --resource-group $resgroupName --vnet-name $vNetName --address-prefix "10.2.5.0/24"

az network nsg create --name $nsgBusiness --resource-group $resgroupName
az network nsg rule create --name "businessAllowWeb" --nsg-name $nsgBusiness --priority 1000 --resource-group $resgroupName --access Allow --direction Inbound --protocol * --source-address-prefixes "10.2.2.0/24" --source-port-ranges '*' --destination-port-ranges '*'
az network nsg rule create --name "businessDenyAll" --nsg-name $nsgBusiness --priority 2000 --resource-group $resgroupName --access Deny --direction Inbound --protocol * --source-address-prefixes '*' --source-port-ranges '*' --destination-port-ranges '*'

az network nsg create --name $nsgData --resource-group $resgroupName
az network nsg rule create --name "dataAllowBusiness" --nsg-name $nsgData --priority 1000 --resource-group $resgroupName --access Allow --direction Inbound --protocol * --source-address-prefixes "10.2.1.0/24" --source-port-ranges '*' --destination-port-ranges '*'
az network nsg rule create --name "dataDenyAll" --nsg-name $nsgData --priority 2000 --resource-group $resgroupName --access Deny --direction Inbound --protocol * --source-address-prefixes '*' --source-port-ranges '*' --destination-port-ranges '*'

**Comment by ksateesh22** [comment]
[3tier.txt](https://github.com/QT-DevOps/DevOpsIssues/files/2409002/3tier.txt)

**Comment by ksateesh22** [comment]
i have attached the script "3tier.txt" this is for your reference..

**Comment by shaikkhajaibrahim** [comment]
Great.
