### ISSUE TITLE
provisioning issue

### ISSUE THREAD

**Issue by kmraok** [QT-DevOps/DevOpsIssues#181]
I got an error while "vagrant up" after un commented provisioning. how to solve this?
![error 1](https://user-images.githubusercontent.com/43443111/45946353-4f75de80-c00e-11e8-933d-e9cd86153f08.png)
![error 2](https://user-images.githubusercontent.com/43443111/45946354-500e7500-c00e-11e8-8fdc-199bc2e98b9a.png)

"D:/Vagrant/virtualbox/apache/Vagrantfile:70: syntax error, unexpected keyword_end, expecting end-of-input
 end
    ^
PS D:\Vagrant\virtualbox\apache> vagrant up
Vagrant failed to initialize at a very early stage:

There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

D:/Vagrant/virtualbox/apache/Vagrantfile:70: syntax error, unexpected keyword_end, expecting end-of-input
 end
    ^
PS D:\Vagrant\virtualbox\apache>"

**Comment by arunkumar127** [comment]
@kmraok 
Seems to be it is problem with spaces. Upload your Vagrantfile here.
I'll check & let you know error.

**Comment by kmraok** [comment]
I just un commented only.

*Mallikharjuna **Rao. Koppolu*
*9908636373*

*kmraok@gmail.com <kmraok@gmail.com>*
*mallikharjun.koppolu@srijaytech.com <mallikharjun.koppolu@srijaytech.com>*
*www.srijaytech.com <http://www.srijaytech.com>*

**Comment by shaikkhajaibrahim** [comment]
share your vagrant file

**Comment by kmraok** [comment]
*Mallikharjuna **Rao. Koppolu*
*9908636373*

*kmraok@gmail.com <kmraok@gmail.com>*
*mallikharjun.koppolu@srijaytech.com <mallikharjun.koppolu@srijaytech.com>*
*www.srijaytech.com <http://www.srijaytech.com>*
