### ISSUE TITLE
jenkins- master-slave configuration-windows node not conneting

### ISSUE THREAD

**Issue by sandhyadev** [QT-DevOps/DevOpsIssues#182]
hai,
 I am trying to connect windows node from jenkins, but unable to connect. It is showing below error.
Can you please help?
![image](https://user-images.githubusercontent.com/42669522/45950164-43911900-c01c-11e8-8a71-4fe13e78e956.png)

Thank you.
Sandhya

**Comment by raviops100** [comment]
Hi Sandhya,

your adding winows machine as a slave  to jenkins for this for some time you need to disable firewall of your machine 

In your machine go to below location 

Control Panel\System and Security\Windows Defender Firewall\Customize Settings\Private networkseetings\

Turn-off Defender firewall off in both public and private 

then try to execute command like 

java -jar the you have pasted in the screenshot

and also aws machine publicip and port  where jenkins is installed that public ip corretly u need to configure in the command

Thanks
Ravi

**Comment by arunkumar127** [comment]
@sandhyadev 
As we discussed earlier, make sure that you have opened required ports for communication.
Check port number which has failed to connect.
In your case 49187 port should be opened.

Regards
Arun Kumar

**Comment by revathi-muthana123** [comment]
open port  "3389" which is "RDP " in your remote machine security security group.

**Comment by raviops100** [comment]
is this issue resolved ???

**Comment by sandhyadev** [comment]
HAI,
Yes, it's resolved.
I have opened port  49187 ,now its connecting.
Thank you for all.

**Comment by Lokeswararao** [comment]
hi,
while am trying to connect windows node from jenkins, not able to connect. It is showing Connection timeout error.
Please help me on tis..



![image](https://user-images.githubusercontent.com/26164550/50805527-d712ff00-1318-11e9-83a3-159bad262b43.png)

**Comment by Lokeswararao** [comment]
And i have done the below settings also
Control Panel\System and Security\Windows Defender Firewall\Customize Settings\Private networkseetings\

Turn-off Defender firewall off in both public and private

then i have tried..even thogh im getting same issue
