### ISSUE TITLE
task about vagrant box

### ISSUE THREAD

**Issue by vsaisatya21** [QT-DevOps/DevOpsIssues#183]
can you please help me out sir :

**1. Write a bash script that creates and boots Vagrant box
 (https://vagrant.io)  with Ubuntu.
 2. Write an Ansible script that connects to this Vagrant box
 and does the following on it:
 - Creates a user "testuser"
 - Sets the system's timezone to
 "Asia/Kolkata"
 - Uploads a random local file from the host into the
 /home/testuser/ directory
 - Installs python, supervisord, and the latest version of
 consul **(https://consul.io)**

**Comment by shaikkhajaibrahim** [comment]
Refer #162
