### ISSUE TITLE
How to create amazon ami from existing instance using packer

### ISSUE THREAD

**Issue by rajd1** [QT-DevOps/DevOpsIssues#185]
hi sir, can we use packer to create ami from an existing ec2 instance ?
example scenario:
i am having ec2 instance for which ami need to be created maybe with some customization/provisioners like to install some software or some configuration.
can we do that using packer...

i am aware we can create ami from ec2 instance thru aws, but can we do it from packer?

**Comment by raviops100** [comment]
Hi Raj,
Yes we can create AMI from an  an existing ec2 instance from Packer
Below are some points related to your query from packer documentation

AMI Builder (instance-store)
Type: amazon-instance

The amazon-instance Packer builder is able to create Amazon AMIs backed by instance storage as the root device. For more information on the difference between instance storage and EBS-backed instances, see the "storage for the root device" section in the EC2 documentation.

This builder builds an AMI by launching an EC2 instance from an existing instance-storage backed AMI, provisioning that running machine, and then bundling and creating a new AMI from that machine. This is all done in your own AWS account. The builder will create temporary key pairs, security group rules, etc. that provide it temporary access to the instance while the image is being created. This simplifies configuration quite a bit.

The builder does not manage AMIs. Once it creates an AMI and stores it in your account, it is up to you to use, delete, etc. the AMI.

Thanks
Ravi

**Comment by rajd1** [comment]
Hi Ravi,
Thanks for reply. what you have said is about building ami by launching instance from existing ami.
"**This builder builds an AMI** by launching an EC2 instance **from an existing** instance-storage backed **AMI**"
I think same above process happening when you are trying to create image from packer even for ebs backed ami.. that is first packer launch instance from a ami, shut down that instance and take image etc..

What I am saying that assume you already have one running instance (ebs backed) in aws, and want to create image of that using packer... is that be possible ?

**Comment by revathi-muthana123** [comment]
Hi,
Packer is used  create re-usable image with provisioner. Already u have instance with provisioning, so no need to create image from packer in this case. 
Creating an image from a running instance is a single AWS command in  cli :
=> aws ec2 create-image --instance-id <instance id>  --name <name> --description <text>
=> UI: right click  on instance -> create image 
  
still if you woud like to create an AMI  from a running EC2 instance using Packers..
Steps:
1) Use packer to generate the base AMI and start the EC2 instance 
2) Have user data configuration on the EC2 instance.. (Human Intervention needed here) 
3) Generate an app specific AMI from step#2 using Packer 

we don't want to use the "provisioner" provided by packers. we need a human intervention at step#2
Thank you

**Comment by pramod414** [comment]
@rajd1 
If you want to create ami for the existing ec2 machine, you can directly create from the actions,

**Comment by shaikkhajaibrahim** [comment]
No you cannot as there is already simple option. Packer doesnt support this
