### ISSUE TITLE
aws

### ISSUE THREAD

**Issue by ramakrishna228** [QT-DevOps/DevOpsIssues#186]
i am creating aws accout but i am not go through ec2 machine,by clicking ec2 the page displays like  below.i am go through below 3 steps,but unable to get ec2

![screenshot 2](https://user-images.githubusercontent.com/42872074/45996874-67f00280-c0bb-11e8-94ff-b060c8c74d01.png)

**Comment by rajd1** [comment]
contact support and explain same thing to them, they will guide you. mostly they may ask you for id proof

**Comment by rameshm78** [comment]
Is it over 24 hours since you registered? If yes, then click on Contact Support button and try to raise a ticket.

**Comment by revathi-muthana123** [comment]
=>Some times "credit card" verification might be failed.
=> check your mail which was given to that account.
=>Or else try to create new account with new mobile number &  new mail id.

**Comment by ramana152** [comment]
@ramakrishna228    Dont create any new account . please check the your payment method , if it success , wait for activation mail, it may take time to get activation mail. If it is activated then wait for 24 hours to access services.
If payment  gets failed , remove that card & add new card . AWS accept VISA and Master cards only.

**Comment by revathi-muthana123** [comment]
Is it Activated your Account?

**Comment by shaikkhajaibrahim** [comment]
Please raise support ticket on AWS @ https://aws.amazon.com/contact-us/
![image](https://user-images.githubusercontent.com/2438317/46192370-71c27180-c318-11e8-9edb-5f32fc0b3600.png)
