### ISSUE TITLE
Unable to save Vi editor in Ubuntu 16

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#187]
Hi Team,

I am unable to  do chnages and save the Vi editor in ubuntu.
I logged in with sudo. used esc+:q!
But that is taking as text rather than command. I had to exit from terminal to come out.
Please help.

**Comment by ramana152** [comment]
@Aamukta   Please use Esc+:wq!  Then it will save and came out...

**Comment by arunkumar127** [comment]
@Aamukta
If you're facing problem with Vi, the use nano editor.
$ sudo nano (filename)

Enter text & press Ctrl+X to exit.
When prompted, press Y to save.

**Comment by Aamukta** [comment]
> @Aamukta Please use Esc+:wq! Then it will save and came out...

However this is not working. Tried the same thing before. :(

**Comment by Aamukta** [comment]
> @Aamukta
> If you're facing problem with Vi, the use nano editor.
> $ sudo nano (filename)
> 
> Enter text & press Ctrl+X to exit.
> When prompted, press Y to save.

@Arun.. Yes This helped in coming out of vi when selected N.
If I select Y, it is still inside vi.

**Comment by revathi-muthana123** [comment]
> > @Aamukta
> > If you're facing problem with Vi, the use nano editor.
> > $ sudo nano (filename)
> > Enter text & press Ctrl+X to exit.
> > When prompted, press Y to save.
> 
> @Arun.. Yes This helped in coming out of vi when selected N.
> If I select Y, it is still inside vi.


Click  enter after selecting "Y"

**Comment by pramod414** [comment]
> Hi Team,
> 
> I am unable to do chnages and save the Vi editor in ubuntu.
> I logged in with sudo. used esc+:q!
> But that is taking as text rather than command. I had to exit from terminal to come out.
> Please help.

**Comment by pramod414** [comment]
@Aamukta 
As you are using Esc+q! this is for the only quit,
 Use Esc+wq!  to save and quit.
