### ISSUE TITLE
version

### ISSUE THREAD

**Issue by amit2793** [QT-DevOps/DevOpsIssues#188]
how to know if vagrant box is server or desktop version in ubuntu case

**Comment by raviops100** [comment]
Hi amit,

Command for to check version of Vagrant on ubuntu

vagrant --version

**Comment by amit2793** [comment]
> Hi amit,
> 
> Command for to check version of Vagrant on ubuntu
> 
> vagrant --version

ubuntu has desktop and server version as you know , how to find whether server or desktop vagrant box is there on vagrant site

**Comment by shaikkhajaibrahim** [comment]
It depends on box which you are using . You can find that info in vagrant public boxes site
![image](https://user-images.githubusercontent.com/2438317/46192280-25773180-c318-11e8-8c48-3caddc71875f.png)
