### ISSUE TITLE
Trying to create an Ubuntu AMI from packer- getting error 

### ISSUE THREAD

**Issue by vjskothu** [QT-DevOps/DevOpsIssues#189]
==> Builds finished but no artifacts were created.
PS C:\Users\user\Desktop\PROJECTS\packer> packer build -debug .\secondami.json
Debug mode enabled. Builds will not be parallelized.
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name: apache web server kothu sowmya
==> amazon-ebs: Pausing after run of step 'StepPreValidate'. Press enter to continue.
    amazon-ebs: Found Image ID: ami-0ac019f4fcb7cb7e6
==> amazon-ebs: Pausing after run of step 'StepSourceAMIInfo'. Press enter to continue.
==> amazon-ebs: Creating temporary keypair: packer_5bab4274-5410-006a-aa7a-a11281f8a59f
    amazon-ebs: Saving key for debug purposes: ec2_amazon-ebs.pem
==> amazon-ebs: Pausing after run of step 'StepKeyPair'. Press enter to continue.
==> amazon-ebs: Creating temporary security group for this instance: packer_5bab427e-f4df-a73b-845b-c293f60c8233
==> amazon-ebs: Authorizing access to port 22 from 0.0.0.0/0 in the temporary security group...
==> amazon-ebs: Pausing after run of step 'StepSecurityGroup'. Press enter to continue.
==> amazon-ebs: Pausing after run of step 'StepCleanupVolumes'. Press enter to continue.
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
    amazon-ebs: Instance ID: i-0c47bc593a5d711c3
==> amazon-ebs: Waiting for instance (i-0c47bc593a5d711c3) to become ready...
    amazon-ebs: Public DNS: ec2-54-166-189-3.compute-1.amazonaws.com
    amazon-ebs: Public IP: 54.166.189.3
    amazon-ebs: Private IP: 172.31.88.162
==> amazon-ebs: Pausing after run of step 'StepRunSourceInstance'. Press enter to continue.
==> amazon-ebs: Pausing after run of step 'StepGetPassword'. Press enter to continue.
**==> amazon-ebs: Using ssh communicator to connect: 54.166.189.3
==> amazon-ebs: Waiting for SSH to become available...

**==> amazon-ebs: Error waiting for SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain****
==> amazon-ebs: Pausing before cleanup of step 'StepGetPassword'. Press enter to continue. ==> amazon-ebs: Pausing before cleanup of step 'StepRunSourceInstance'. Press enter to continue.
==> amazon-ebs: Terminating the source AWS instance...

**Comment by vjskothu** [comment]
JSON file
===========

{
    "builders": [
     {
         "type": "amazon-ebs",
        "access_key": "**********",
        "secret_key": "**********", 
        "region": "us-east-1",
         "source_ami": "ami-0ac019f4fcb7cb7e6",
         "instance_type": "t2.micro",
         "ssh_username": "ec2-user",
         "ami_name": "apache web server kothu sowmya"
       }
 ],
 "provisioners":[
    {
        "type": "shell",
        "inline": [
            "sudo apt-get update",
            "echo apt-get update done.",
           " sudo sudo apt-add-repository 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu bionic main'",
           "sudo apt-get -y install ansible",
           "sudo wget 'https://s3-us-west-2.amazonaws.com/vjskothu1/playbook.yml'"]
      },
     {
        "type": "ansible-local",
        "playbook_file": "playbook.yml"
       }
    
 ]
}

**Comment by arunkumar127** [comment]
@vjskothu 
**ssh: unable to authenticate**
Have you created user in IAM & provided correct Access key & Secret key?

Create a new user and try to run **packer build** command with correct Access key & Secret key.

Regards
Arun Kumar

**Comment by vjskothu** [comment]
Dear Arun Kumar,

It was my bad, ssh_user parameter I have given wrong username it is not ec2-user, It has to be ubuntu for Ubuntu AMI.
Fixed and now it is working. Thanks for your time.
Regards
Kothandaraman

**Comment by vjskothu** [comment]
thanks closing the issue.
