### ISSUE TITLE
Getting error when starting the vagrant (up).

### ISSUE THREAD

**Issue by reddyvenu** [QT-DevOps/DevOpsIssues#19]
![vagrant error](https://user-images.githubusercontent.com/38197992/40653497-fe490ecc-6358-11e8-85b6-f064bdbb25d6.PNG)

**Comment by shaikkhajaibrahim** [comment]
Please use Virtual Box instead of Hyper-V .

**Comment by reddyvenu** [comment]
I think In windows 7 we do't have Hyper-V .(I am using win7).

**Comment by shaikkhajaibrahim** [comment]
Can you show me the vagrantfile in the folder

**Comment by reddyvenu** [comment]
[Vagrantfile.zip](https://github.com/QT-DevOps/DevOpsIssues/files/2047916/Vagrantfile.zip)

**Comment by shaikkhajaibrahim** [comment]
Attach Vagrantfile directly zip seems to be corrupted

**Comment by reddyvenu** [comment]
[Vagrantfile.txt](https://github.com/QT-DevOps/DevOpsIssues/files/2047946/Vagrantfile.txt)

**Comment by shaikkhajaibrahim** [comment]
Can you try "**vagrant up --provider virtualbox**"
Share the result

**Comment by reddyvenu** [comment]
![vagrant error](https://user-images.githubusercontent.com/38197992/40655539-463a5fd2-635f-11e8-95c8-59dfbfd2e74b.PNG)

**Comment by shaikkhajaibrahim** [comment]
As the error clearly states Virtual Box might not be in usable state. Please check that

**Comment by reddyvenu** [comment]
ok

**Comment by reddyvenu** [comment]
It's working after re install the virtual box .

 thank you.
