### ISSUE TITLE
401 Error - building ec2 image from packer

### ISSUE THREAD

**Issue by sivasankardevops** [QT-DevOps/DevOpsIssues#190]
Hi,

I tried to build image with packer in AWS ec2. I am getting 401 Error. Can you pls suggest ? 
Script:
{
    "builders":[
        {
            "type": "amazon-ebs",
            "access_key": "",
            "secret_key": "",
            "region": "us-west-2",
            "source_ami": "ami-0bbe6b35405ecebdb",
            "instance_type": "t2.micro",
            "ssh_username": "ubuntu",
            "ami_name": "packer-quick-start"
        }
    ],
    "provisioners":[
        {
            "type": "shell",
            "inline":[
              "sudo apt-get update",
              "sudo apt-get install git -y"
            ]
        }
    ]
}

Error:

![image](https://user-images.githubusercontent.com/42856513/46084086-afc46780-c157-11e8-8662-22a5a22f96d7.png)

Thank You
Siva

**Comment by ramana152** [comment]
@Siva  specify access key and secret key in packer build command...then try to run packer build command ...hope it will run successfully...

**Comment by sivasankardevops** [comment]
After giving Access key and secret key the result was same

**Comment by ramana152** [comment]
@siva.  Then delete user in IAM..Create new user .. Then generate new access key and secret key ...After that you run that packer build command with new access key and secret key...Bocz this is happend same for me...

**Comment by sivasankardevops** [comment]
@ramana.    after building with new user same error was occurred

**Comment by ramana152** [comment]
Then do one thing ...Direct u can add access key and secret key  in builders section ..Run only packer build with json file..

**Comment by arunkumar127** [comment]
@sivasankarvenkata 
Have you created user in IAM with **Programmatic access** > **Attach existing policies directly** > **AdministratorAccess**
Please check whether you have created user with AdministratorAccess or not.

Have you hard-coded Access key & Secret key or passing them through command line (-var)?

**Comment by sivasankardevops** [comment]
*@arunkumar       Programmatic access* > *Attach existing policies directly*
 > *AdministratorAccess ..                             *
 I was created the user as mentioned in above  and Access key and secret
key are hardcoded not passing from _var file

**Comment by ramana152** [comment]
@siva Have you installed awscli software?

**Comment by sivasankardevops** [comment]
Yes . Installed

**Comment by vjskothu** [comment]
**Dear Siva

I tried with your code, it is working fine. the issue could be only with access key and security key. 

see the output of execution

====================**
PS C:\Users\user\Desktop\PROJECTS\packer> packer validate  .\test.json
Template validated successfully.
PS C:\Users\user\Desktop\PROJECTS\packer> packer build -debug .\test.json
Debug mode enabled. Builds will not be parallelized.
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name: packer-quick-start
==> amazon-ebs: Pausing after run of step 'StepPreValidate'. Press enter to continue.
    amazon-ebs: Found Image ID: ami-0bbe6b35405ecebdb
==> amazon-ebs: Pausing after run of step 'StepSourceAMIInfo'. Press enter to continue.
==> amazon-ebs: Creating temporary keypair: packer_5bac388f-196b-7518-23df-249dfd352c0a
    amazon-ebs: Saving key for debug purposes: ec2_amazon-ebs.pem
==> amazon-ebs: Pausing after run of step 'StepKeyPair'. Press enter to continue.
==> amazon-ebs: Creating temporary security group for this instance: packer_5bac389a-e818-32e3-5eae-6ac6d31c15e6
==> amazon-ebs: Authorizing access to port 22 from 0.0.0.0/0 in the temporary security group...
==> amazon-ebs: Pausing after run of step 'StepSecurityGroup'. Press enter to continue.
==> amazon-ebs: Pausing after run of step 'StepCleanupVolumes'. Press enter to continue.
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
    amazon-ebs: Instance ID: i-03fb48195c63e6d2c
==> amazon-ebs: Waiting for instance (i-03fb48195c63e6d2c) to become ready...
    amazon-ebs: Public DNS: ec2-54-245-186-203.us-west-2.compute.amazonaws.com
    amazon-ebs: Public IP: 54.245.186.203
    amazon-ebs: Private IP: 172.31.24.242
==> amazon-ebs: Pausing after run of step 'StepRunSourceInstance'. Press enter to continue.
==> amazon-ebs: Pausing after run of step 'StepGetPassword'. Press enter to continue.
==> amazon-ebs: Using ssh communicator to connect: 54.245.186.203
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Pausing after run of step 'StepConnect'. Press enter to continue.
==> amazon-ebs: Pausing before the next provisioner . Press enter to continue.
==> amazon-ebs: Provisioning with shell script: C:\Users\user\AppData\Local\Temp\packer-shell741734695
    amazon-ebs: Hit:1 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic InRelease
    amazon-ebs: Get:2 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
    amazon-ebs: Get:3 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
    amazon-ebs: Get:4 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic/main Sources [829 kB]
    amazon-ebs: Get:5 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic/restricted Sources [5324 B]
    amazon-ebs: Get:6 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic/universe Sources [9051 kB]
    amazon-ebs: Get:7 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic/multiverse Sources [181 kB]
    amazon-ebs: Get:8 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [8570 kB]
    amazon-ebs: Get:9 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic/universe Translation-en [4941 kB]
    amazon-ebs: Get:10 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
    amazon-ebs: Get:11 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [151 kB]
    amazon-ebs: Get:12 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic/multiverse Translation-en [108 kB]
    amazon-ebs: Get:13 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/universe Sources [66.3 kB]
    amazon-ebs: Get:14 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/multiverse Sources [3216 B]
    amazon-ebs: Get:15 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/main Sources [174 kB]
    amazon-ebs: Get:16 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [354 kB]
    amazon-ebs: Get:17 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [136 kB]
    amazon-ebs: Get:18 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [214 kB]
    amazon-ebs: Get:19 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [101 kB]
    amazon-ebs: Get:20 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [4180 B]
    amazon-ebs: Get:21 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-updates/multiverse Translation-en [2740 B]
    amazon-ebs: Get:22 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-backports/universe Sources [1188 B]
    amazon-ebs: Get:23 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [2852 B]
    amazon-ebs: Get:24 http://us-west-2.ec2.archive.ubuntu.com/ubuntu bionic-backports/universe Translation-en [1200 B]
    amazon-ebs: Get:25 http://security.ubuntu.com/ubuntu bionic-security/main Sources [49.2 kB]
    amazon-ebs: Get:26 http://security.ubuntu.com/ubuntu bionic-security/multiverse Sources [1336 B]
    amazon-ebs: Get:27 http://security.ubuntu.com/ubuntu bionic-security/universe Sources [18.3 kB]
    amazon-ebs: Get:28 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [171 kB]
    amazon-ebs: Get:29 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [67.3 kB]
    amazon-ebs: Get:30 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [74.7 kB]
    amazon-ebs: Get:31 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [42.3 kB]
    amazon-ebs: Get:32 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [1444 B]
    amazon-ebs: Get:33 http://security.ubuntu.com/ubuntu bionic-security/multiverse Translation-en [996 B]
    amazon-ebs: Fetched 25.6 MB in 5s (5339 kB/s)
    amazon-ebs: Reading package lists...
    amazon-ebs: Reading package lists...
    amazon-ebs: Building dependency tree...
    amazon-ebs: Reading state information...
    amazon-ebs: git is already the newest version (1:2.17.1-1ubuntu0.1).
    amazon-ebs: 0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
==> amazon-ebs: Pausing after run of step 'StepProvision'. Press enter to continue.

**Comment by revathi-muthana123** [comment]
Hi All,
I have verified his access key & secret key, and i have given administrator policy also. Same error ccured.
Then I tried with new  user credentials , AWS CLI also installed. even though same issue.
Packer version: 1.3.1
What could be the reason ?

Thanks & Regards
Revathi

**Comment by sivasankardevops** [comment]
hi
is there any problem with packer version 1.3.1........    ?

**Comment by ramana152** [comment]
@sivasankarvenkata  
If you have Remote desktop softwares like NoMachine/TeamViewer then reach me at ramana152@gmail.com

**Comment by sivasankardevops** [comment]
at what time?

**Comment by ramana152** [comment]
@Siva  Today 9PM...

**Comment by sivasankardevops** [comment]
@ramana15
ok

**Comment by arunkumar127** [comment]
@sivasankarvenkata @ramana152 @revathi-muthana123 
As per the discussion we had, it's problem with AWSCLI installation.
After reinstalling AWSCLI, everything went fine.

**Comment by sivasankardevops** [comment]
the problem is in awscli  after reinstalling awscli it was build successfully
