### ISSUE TITLE
i have powershell 5.1 still i cannot install virtual box..i have installed chocolatey

### ISSUE THREAD

**Issue by amit2793** [QT-DevOps/DevOpsIssues#191]

**Comment by revathi-muthana123** [comment]
Hi Amit,
Can  you please share error  which you got whie installing. Is it same issue no :179 ?

Thanks 
Revathi

**Comment by amit2793** [comment]
![virtulabox error](https://user-images.githubusercontent.com/26686554/46162781-dd6bf680-c2a6-11e8-9d0b-3713b272d191.jpeg)

**Comment by shaikkhajaibrahim** [comment]
i doubt the network connectivity of yours.

**Comment by shaikkhajaibrahim** [comment]
duplicate #179
