### ISSUE TITLE
Can anybody give me steps for creating Packer image which i should call from Jenkins. any extra software should install for this Jenkins master. Thanks in advance

### ISSUE THREAD

**Issue by SuneelkumaarNarayana** [QT-DevOps/DevOpsIssues#192]

**Comment by revathi-muthana123** [comment]
Hi,
Please follow steps:
-------------------
1. Install "Packer" plugin in jenkins
   Manage jenkins -> Manage Plugins -> Available -> packer -> install packer
   Restart Jenkins
2. Configure packer in "Glbal Tool Configuration"
   Manage jenkins -> Global Tool Configuration -> packer -> Packer installations 
![image](https://user-images.githubusercontent.com/39338792/46127105-3eff7700-c24d-11e8-8f07-58316e19898d.png)
Save
3. Create a new job. Then configure "Packer"  in Post Build Actions

![image](https://user-images.githubusercontent.com/39338792/46127169-79691400-c24d-11e8-9cee-0a9bae55c492.png)

4. Build Now

This link might be help you:
------------------------------
https://wiki.jenkins.io/display/JENKINS/Packer+Plugin

Thanks & Regards
Revathi

**Comment by SuneelkumaarNarayana** [comment]
Surely This acan help me. thanks!
