### ISSUE TITLE
Scope of Security Group

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#193]
What is the scope of Security Group.
Like NACL is operated at Subnet level(If I am not wrong)

**Comment by revathi-muthana123** [comment]
Hi,

Difference between Security Group and NACLs :
----------------------------------------------------------
=> Security Group act as a firewall for  associated Amazon EC2 instances, controlling both inbound and 
      outbound traffic at the instance level.
=> NACLs act as a firewall for associated subnets, controlling both inbound and outbound traffic at 
     the subnet level
=> NACLs are stateless where as Security groups are statefull. 
      Ex: In security groups if we add an inbound rule say for port 80, it is automatically allowed out, 
            meaning outbound rule for that particular port need not be explicitly added. 
            But in NACLs we need to provide explicit inbound and outbound rules
=> In security groups we cannot deny traffic from a particular instance, by default everything is denied. 
     we can set rules only to allow. Where as in NACLs we  can set rules both to deny and allow. There by 
     denying and allowing only the instances of our choice. We can able to take more granular decisions.

Thanks & Regards
Revathi

**Comment by Aamukta** [comment]
> Hi,
> 
> ## Difference between Security Group and NACLs :
> => Security Group act as a firewall for associated Amazon EC2 instances, controlling both inbound and
> outbound traffic at the instance level.
> => NACLs act as a firewall for associated subnets, controlling both inbound and outbound traffic at
> the subnet level
> => NACLs are stateless where as Security groups are statefull.
> Ex: In security groups if we add an inbound rule say for port 80, it is automatically allowed out,
> meaning outbound rule for that particular port need not be explicitly added.
> But in NACLs we need to provide explicit inbound and outbound rules
> => In security groups we cannot deny traffic from a particular instance, by default everything is denied.
> we can set rules only to allow. Where as in NACLs we can set rules both to deny and allow. There by
> denying and allowing only the instances of our choice. We can able to take more granular decisions.
> 
> Thanks & Regards
> Revathi

Thanks Revathi
