### ISSUE TITLE
Unable to create a packer image

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [QT-DevOps/DevOpsIssues#194]
Hi Friends

I am not able to create packer image though I followed the same script in hello.json file, and executed it thru Win PS as an Administrator. The script is as follows : 
{
    "builders": [
        {
            "type" : "amazon-ebs",
            "region" : "us-west-2",
            "source_ami" : "ami-09bfeda7337019518",
            "access_key" : "                                     ",
            "secret_key" : "                                      ",
            "ssh_username" : "ubuntu",
            "instance_type" : "t2.micro",
            "ami_name" : "image-from-packer"
        }
    ],
    "provisioners": [
        {
                "type": "shell",
                "inline": ["sudo apt-get update", "sudo apt-get install git tree -y"]
        }
    ]
}

Rather, instances namely "Packer Builder" is getting created the number of times i execute the script, that too in Terminated State.  
And when i checked in AMI section, it says "You do not own any Images matching your filter criteria." I did refreshed the page several number of times..

**Comment by arunkumar127** [comment]
@SajidAliKhanMohammed 
Packer build command will always first create an instance with default tag **Packer Builder**. After creating instance, provisioners will be run.
If every thing is successful then an AMI will be created with name **ami_name** which we have provided in **Builders** section. After creating AMI, **Packer Builder** instance will be terminated. 

After running packer build command check your PowerShell window for message **Creating AMI**. If this message appears in log then AMI will be created. Now check in AMI section.
If there is any error in json file, action will be terminated.

Post screenshot of output you got after running packer build command.

Regards
Arun Kumar

**Comment by ramana152** [comment]
@SajidAliKhanMohammed     Hi I tried with your code and it is working good and created AMI also... 
![packer1](https://user-images.githubusercontent.com/39365142/46156531-55322500-c297-11e8-8e3f-12e91fe7950b.jpg)
![packer2](https://user-images.githubusercontent.com/39365142/46156533-56635200-c297-11e8-84ce-f6ce0f9cd8d8.png)
![packer3](https://user-images.githubusercontent.com/39365142/46156536-582d1580-c297-11e8-9ca9-1fc5f30900f6.png)

**Comment by SajidAliKhanMohammed** [comment]
Hi Arun and Ramana
Thanks for your instant help. I again executed the same script without changing anything and this time it worked..

Thanks
SajidKhan

![untitled3](https://user-images.githubusercontent.com/16450606/46161661-c24bb780-c2a3-11e8-909c-0c98fb760010.png)
