### ISSUE TITLE
vagrant

### ISSUE THREAD

**Issue by amit2793** [QT-DevOps/DevOpsIssues#195]
so how to find correct os version for vagrant box to installl without downloading from vagrant cloud..

**Comment by Santosh-Peddada** [comment]
Downloading it from choco will get you the latest version <choco install vagrant>

**Comment by arunkumar127** [comment]
@amit2793 
What do you mean by correct OS version?

**Comment by shaikkhajaibrahim** [comment]
In vagrant generally you go with latest versions rather than correct version. But if you want specific version of box vagrant box add <boxname> --box-version <versionofbox>
