### ISSUE TITLE
AWS CLI not required for packer to create ami

### ISSUE THREAD

**Issue by rajd1** [QT-DevOps/DevOpsIssues#196]
Hi Sir,
As you have mentioned once that aws cli is must for running packer, I have tried creating image without installing aws cli and successfully able to create ami.
If we are installing cli, then there is also danger of exposing credentials because it will be stored in plain text in the .aws/credentials file. I think packer will also be checking this path for credentials in some cases.
https://github.com/hashicorp/packer/issues/1612

So basically we don't need aws cli to create ami via packer because anyway we are passing the credentials at runtime by using -var option and packer no need to interact with aws cli components.

Even better way will be to use like iam role with packer on ec2 instance so that no fixed credentials are passed anywhere.. i will explore this option and update.

I was checked with very basic example taken from packer site:
https://www.packer.io/intro/getting-started/build-image.html

**Comment by shaikkhajaibrahim** [comment]
Thanks for the info
