### ISSUE TITLE
os installation 

### ISSUE THREAD

**Issue by amit2793** [QT-DevOps/DevOpsIssues#198]
i want to install redhat 6.3 using vagrant.can you help me with that

**Comment by amit2793** [comment]
![rhel error](https://user-images.githubusercontent.com/26686554/46254797-994d4180-c4b2-11e8-86e8-1121a0f8c74c.png)

**Comment by raviops100** [comment]
Hi  Amit

**Comment by raviops100** [comment]
Hi Amit, 
You can't install redhat6.3 from vagrant 
Because redhat has licenced versions
But you want some from redhat family you can go for CentOs from vagrant 
Vagrant init centos/07
Thanks 
Ravi
