### ISSUE TITLE
vagrant

### ISSUE THREAD

**Issue by amit2793** [QT-DevOps/DevOpsIssues#199]
i am trying to create a webpage by logging in private network but when i am entering my ip in browserthen nothing is displaying

**Comment by ramana152** [comment]
@amit2793    share vagrant file....

**Comment by amit2793** [comment]
this is file

**Comment by amit2793** [comment]
extract it you will find

**Comment by amit2793** [comment]
> @amit2793 share vagrant file....

cannot find a way to upload

**Comment by ramana152** [comment]
> > @amit2793 share vagrant file....
> 
> cannot find a way to upload
@amit2793   just drag and drop from file location to here........

**Comment by amit2793** [comment]
@ramana152 can you take my pc on teamviewer

**Comment by ramana152** [comment]
yes.... ramana152@gmail.com

**Comment by amit2793** [comment]
wait

**Comment by amit2793** [comment]
@ramana152 are you on line

**Comment by ramana152** [comment]
> @ramana152 are you on line

yes

**Comment by amit2793** [comment]
@ramana152 check your mail

**Comment by ramana152** [comment]
As per discussion, I tried with your vagrant file and it is working good... got webpage also..
![vagrant](https://user-images.githubusercontent.com/39365142/46268094-3d3bf900-c556-11e8-956c-ab2862f26119.png)
