### ISSUE TITLE
winrm timeout issue while Building windows AMI using packer

### ISSUE THREAD

**Issue by dsrit30** [QT-DevOps/DevOpsIssues#200]
I am trying to build the windows AMI using packer. But it is not working and throws the winrm timeout error.

The below is my packer content.

{
"variables" : {
    "access_key": "",
    "secret_key": ""
},

"Builders":[{
"type": "amazon-ebs",
 "access_key": "{{user `access_key`}}",
 "secret_key": "{{user  `secret_key`}}",
 "region": "us-east-1",
 "source_ami": "ami-04b06bdb58cae787d",
 "instance_type": "t2.micro",
 "communicator": "winrm",
 "winrm_username": "admin",
 "winrm_password": "Hyderabad123",
 "ami_name": "Myfirstwindowsami{{timestamp}}",
 "winrm_port": 5985

}],

"provisioners":[
{
    "type": "file",
    "source": "./winrm.ps1",
    "destination": "C://winrm.ps1"
},  
{    
    "type": "powershell",
    "inline": [
      "C:\\winrm.ps1",
      "$ErrorActionPreference = 'Stop'",
       ]
}

]
}

**************************************************************************************************************winrm.ps1 content as follows.
-------------------------------------------------------
***********************************************************
<powershell>
Write-output "Setting up WinRM"
write-host "(host) setting up WinRM"
Set-ExecutionPolicy Unrestricted -Scope LocalMachine -Force -ErrorAction Ignore
$ErrorActionPreference = "stop"
cmd.exe /c winrm quickconfig -q
cmd.exe /c winrm set "winrm/config" '@{MaxTimeoutms="1800000"}'
cmd.exe /c winrm set "winrm/config/winrs" '@{MaxMemoryPerShellMB="1024"}'
cmd.exe /c winrm set "winrm/config/service" '@{AllowUnencrypted="true"}'
cmd.exe /c winrm set "winrm/config/client" '@{AllowUnencrypted="true"}'
cmd.exe /c winrm set "winrm/config/service/auth" '@{Basic="true"}'
cmd.exe /c winrm set "winrm/config/client/auth" '@{Basic="true"}'
cmd.exe /c winrm set "winrm/config/service/auth" '@{CredSSP="true"}'
cmd.exe /c winrm set "winrm/config/listener?Address=*+Transport=HTTPS" "@{Port=`"5986`";Hostname=`"packer`";CertificateThumbprint=`"$($Cert.Thumbprint)`"}"
cmd.exe /c netsh advfirewall firewall set rule group="remote administration" new enable=yes
cmd.exe /c netsh firewall add portopening TCP 5986 "Port 5986"
cmd.exe /c net stop winrm
cmd.exe /c sc config winrm start= auto
cmd.exe /c net start winrm

</powershell>

**Comment by ramana152** [comment]
@dsrit30   Can you share Source file (winrm.ps1).

**Comment by dsrit30** [comment]
Thanks for your response.



<powershell>

write-output "Running User Data Script"
write-host "(host) Running User Data Script"

Set-ExecutionPolicy Unrestricted -Scope LocalMachine -Force -ErrorAction
Ignore

# Don't set this before Set-ExecutionPolicy as it throws an error
$ErrorActionPreference = "stop"

# Remove HTTP listener
Remove-Item -Path WSMan:\Localhost\listener\listener* -Recurse

$Cert = New-SelfSignedCertificate -CertstoreLocation Cert:\LocalMachine\My
-DnsName "packer"
New-Item -Path WSMan:\LocalHost\Listener -Transport HTTPS -Address *
-CertificateThumbPrint $Cert.Thumbprint -Force

# WinRM
write-output "Setting up WinRM"
write-host "(host) setting up WinRM"

cmd.exe /c winrm quickconfig -q
cmd.exe /c winrm set "winrm/config" '@{MaxTimeoutms="1800000"}'
cmd.exe /c winrm set "winrm/config/winrs" '@{MaxMemoryPerShellMB="1024"}'
cmd.exe /c winrm set "winrm/config/service" '@{AllowUnencrypted="true"}'
cmd.exe /c winrm set "winrm/config/client" '@{AllowUnencrypted="true"}'
cmd.exe /c winrm set "winrm/config/service/auth" '@{Basic="true"}'
cmd.exe /c winrm set "winrm/config/client/auth" '@{Basic="true"}'
cmd.exe /c winrm set "winrm/config/service/auth" '@{CredSSP="true"}'
cmd.exe /c winrm set "winrm/config/listener?Address=*+Transport=HTTPS"
"@{Port=`"5986`";Hostname=`"packer`";CertificateThumbprint=`"$($Cert
.Thumbprint)`"}"
cmd.exe /c netsh advfirewall firewall set rule group="remote administration"
new enable=yes
cmd.exe /c netsh firewall add portopening TCP 5986 "Port 5986"
cmd.exe /c net stop winrm
cmd.exe /c sc config winrm start= auto
cmd.exe /c reg add
"HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\WinRM\Service" /v
AllowUnencryptedTraffic /t REG_DWORD /d 1 /f
cmd.exe /c net start winrm

</powershell>
