### ISSUE TITLE
AWS - Invalid CIDR for subnet masking

### ISSUE THREAD

**Issue by revathi-muthana123** [QT-DevOps/DevOpsIssues#201]
Hi ,
I created one VPC network 
vpc => CIDR - 192.168.0.0/16
subnet-1 => CIDR - 192.168.0.0/22
Subnet-2 => CIDR - 192.168.1.0/22
  subnet-1 created, but subnet-2 error occured
Error :  Invalid CIDR 

There must be some logic, can u please suggest on this.

Thanks & Regards
Revathi

**Comment by veerendradevops** [comment]
try with below subnets. it will work.
192.168.0.0/22 => subnet_1
192.168.4.0/22=> subnet_2

reason: 
192.168.0.0/22 means it will reserve 1020 ips for subnet_1. so next subnet_2 will be start from 192.168.4.0/22

**Comment by revathi-muthana123** [comment]
@shaikkhajaibrahim , Thank you sir, i got it now, 1019 ips can be reserved for below ranges
192.168.0.0/22
192.168.1.0/22
192.168.2.0/22
192.168.3.0/22
so, next we have to start from 192.168.4.0/22
@vijaybhaskarreddyy  : yes,  Thank you for your responce
