### ISSUE TITLE
terraform - backend - issue

### ISSUE THREAD

**Issue by muralifeb** [QT-DevOps/DevOpsIssues#204]
Hi,

Anywhere here please help to sort out below forwarded issue.
Please find below error description while trying to execute terraform backend script

Error inspecting states in the "s3" backend:
    AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'
        status code: 400, request id: 1EF8E8A4B22220EA, host id: MBH/Xhxslms/l07FNtGIsw8m4yp5FQQfGwgaYzN0Dmt9FMhrkEBplVNvcpX57cInhnlLhD7ih9o=

Prior to changing backends, Terraform inspects the source and destination
states to determine what kind of migration steps need to be taken, if any.
Terraform failed to load the states. The data in both the source and the

Note:  Please find attached screenshot for your reference...

=====================================
![image](https://user-images.githubusercontent.com/43574724/46352392-4a9cd480-c677-11e8-9dcc-021260136890.png)

![image](https://user-images.githubusercontent.com/43574724/46352415-57b9c380-c677-11e8-94e1-d0925561677d.png)

**Comment by revathi-muthana123** [comment]
Hi,
I tried with same script, it is working for me & environment also created.

Can you please suggest??

Thanks & Regards
Revathi

**Comment by muralifeb** [comment]
Thank you Revathi for the response.
I have tried all the possible ways, still trying to dig in.

@Anyone
Request you to refer screeshots attached and If you have any inputs, do reply. Thank you.

**Comment by muralifeb** [comment]
Now I am able to proceed.

This time, I have created dynamo table in us-west-2 and continued by taking all entries new one.

Can any one tell, what key stands for and what is its significance, in below mentioned script?

  backend "s3" {
    bucket = "tf-dynamo"
    key    = "my-module-demo.state"
    region = "us-west-2"
    dynamodb_table = "tfdynamoWest"
  }
}

![backenddynamo](https://user-images.githubusercontent.com/43574724/46391593-6053dd80-c6fb-11e8-9ab6-8a2160fce421.jpg)

**Comment by revathi-muthana123** [comment]
Hi @muralifeb 
key means 'terraform.tfstate' file  which is by executing terraform apply. In our scenario state file can be shared by some one.

Thanks & Regards
Revathi
