### ISSUE TITLE
mvn -v    (not installing) ubuntu 

### ISSUE THREAD

**Issue by chinnadas** [QT-DevOps/DevOpsIssues#205]
Error: Could not find or load main class org.codehaus.plexus.classworlds.launcher.Launcher

**Comment by raviops100** [comment]
Hi chinnadas, 
Can you please try below entry in /etc/profile
export M2_HOME=/usr/share/maven
Thanks
Ravi

**Comment by raviops100** [comment]
Any update on this issue is it working now ???

**Comment by raviops100** [comment]
any update regarding this issue

**Comment by chinnadas** [comment]
Haii


Ok No issue,  if any issue i will Raise in QT Devops.



Thanks & Regards
*K.Chinna Das*
