### ISSUE TITLE
Error while doing docker installation in windows OS

### ISSUE THREAD

**Issue by Jaganarekatla** [QT-DevOps/DevOpsIssues#206]
Hi Team,

Could some one help on below Error, getting this error while doing Docker installation on Windows box, OS and version info given below
Error:

Download of Docker for Windows Installer.exe (520.33 MB) completed.
Hashes match.
Installing docker-for-windows-edge...
[17:40:21.498] [InstallWorkflow] Manifest extraction failed
Exception type: System.TypeLoadException, Exception message: Could not find Windows Runtime type 'Windows.Data.Json.Json
Object'., StackTrace:
   at LightweightInstaller.Manifest.FromJson(String json)
   at LightweightInstaller.ExtractManifestStep.<DoAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
[17:40:21.498] [InstallWorkflow] Installation failed
**Exception type: System.TypeLoadException, Exception message: Could not find Windows Runtime type 'Windows.Data.Json.Json**
Object'., StackTrace:
   at LightweightInstaller.Manifest.FromJson(String json)
   at LightweightInstaller.ExtractManifestStep.<DoAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
docker-for-windows-edge has been installed.
Only an exit code of non-zero will fail the package by default. Set
 `--failonstderr` if you want error messages to also fail a script. See
 `choco -h` for details.
_**The install of docker-for-windows was successful.
  Software installed as 'EXE', install location is likely default.**_

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Systeam OS info :+1: 
OS --> windows 7 ultimate Server Pack 1 64-bit,
Power shell version :+1: 
PS C:\Windows\system32> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Choco version :  PS C:\Windows\system32> choco --version
0.10.11
PS C:\Windows\system32>

**Comment by revathi-muthana123** [comment]
Hi @Jaganarekatla 
How did you installed? i mean Which commands you have given for installation.
Can you please share those?

Try With these Commands, these are working:
--------------------------------------------------
choco install docker-for-windows -y
choco upgrade docker-for-windows

Thanks & Regards
Revathi

**Comment by Jaganarekatla** [comment]
Hi Tried installation with below CMD'S

choco install docker-for-windows --pre

**Comment by Jaganarekatla** [comment]
Hi Revathi,

Retried below steps but still same error, info is,

1) Uninstall the docker
2) Install the docker and upgrade it with the steps which u share above,.

choco install docker-for-windows -y
choco upgrade docker-for-windows

PS C:\Windows\system32> choco install docker-for-windows -y
Chocolatey v0.10.11
Installing the following packages:
docker-for-windows
By installing you accept licenses for the packages.
Progress: Downloading docker-for-windows 18.06.1.19507... 100%

docker-for-windows v18.06.1.19507 [Approved]
docker-for-windows package files install completed. Performing other installation steps.
Downloading docker-for-windows
  from 'https://download.docker.com/win/stable/19507/Docker%20for%20Windows%20Installer.exe'
Progress: 100% - Completed download of C:\Users\Rupa\AppData\Local\Temp\chocolatey\docker-for-windows\18.06.1.19507\Dock
er for Windows Installer.exe (521.01 MB).
Download of Docker for Windows Installer.exe (521.01 MB) completed.
Hashes match.
Installing docker-for-windows...
[18:54:51.215] [InstallWorkflow] Manifest extraction failed
Exception type: System.TypeLoadException, Exception message: Could not find Windows Runtime type 'Windows.Data.Json.Json
Object'., StackTrace:
   at LightweightInstaller.Manifest.FromJson(String json)
   at LightweightInstaller.ExtractManifestStep.<DoAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
[18:54:51.215] [InstallWorkflow] Installation failed
Exception type: System.TypeLoadException, Exception message: Could not find Windows Runtime type 'Windows.Data.Json.Json
Object'., StackTrace:
   at LightweightInstaller.Manifest.FromJson(String json)
   at LightweightInstaller.ExtractManifestStep.<DoAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
docker-for-windows has been installed.
Only an exit code of non-zero will fail the package by default. Set
 `--failonstderr` if you want error messages to also fail a script. See
 `choco -h` for details.
 The install of docker-for-windows was successful.
  Software installed as 'EXE', install location is likely default.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
PS C:\Windows\system32> choco upgrade docker-for-windows
Chocolatey v0.10.11
Upgrading the following packages:
docker-for-windows
By upgrading you accept licenses for the packages.
docker-for-windows v18.06.1.19507 is the latest version available based on your source(s).

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Error which run docker is:


PS C:\Windows\system32> Docker
Docker : The term 'Docker' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Docker
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (Docker:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Thank you
Jagan

**Comment by Jaganarekatla** [comment]
Hi Ravathi, Thank you for your reply.

Retried below steps but still same error, info is,

   1. Uninstall the docker
   2. Install the docker and upgrade it with the steps which u share above,.

choco install docker-for-windows -y
choco upgrade docker-for-windows

PS C:\Windows\system32> choco install docker-for-windows -y
Chocolatey v0.10.11
Installing the following packages:
docker-for-windows
By installing you accept licenses for the packages.
Progress: Downloading docker-for-windows 18.06.1.19507... 100%

docker-for-windows v18.06.1.19507 [Approved]
docker-for-windows package files install completed. Performing other
installation steps.
Downloading docker-for-windows
from '
https://download.docker.com/win/stable/19507/Docker%20for%20Windows%20Installer.exe
'
Progress: 100% - Completed download of
C:\Users\Rupa\AppData\Local\Temp\chocolatey\docker-for-windows\18.06.1.19507\Dock
er for Windows Installer.exe (521.01 MB).
Download of Docker for Windows Installer.exe (521.01 MB) completed.
Hashes match.
Installing docker-for-windows...
[18:54:51.215] [InstallWorkflow] Manifest extraction failed
Exception type: System.TypeLoadException, Exception message: Could not find
Windows Runtime type 'Windows.Data.Json.Json
Object'., StackTrace:
at LightweightInstaller.Manifest.FromJson(String json)
at LightweightInstaller.ExtractManifestStep.d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at LightweightInstaller.InstallWorkflow.d__26.MoveNext()
[18:54:51.215] [InstallWorkflow] Installation failed
Exception type: System.TypeLoadException, Exception message: Could not find
Windows Runtime type 'Windows.Data.Json.Json
Object'., StackTrace:
at LightweightInstaller.Manifest.FromJson(String json)
at LightweightInstaller.ExtractManifestStep.d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at LightweightInstaller.InstallWorkflow.d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
at LightweightInstaller.InstallWorkflow.d__23.MoveNext()
docker-for-windows has been installed.
Only an exit code of non-zero will fail the package by default. Set
--failonstderr if you want error messages to also fail a script. See
choco -h for details.
The install of docker-for-windows was successful.
Software installed as 'EXE', install location is likely default.

Chocolatey installed 1/1 packages.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
PS C:\Windows\system32> choco upgrade docker-for-windows
Chocolatey v0.10.11
Upgrading the following packages:
docker-for-windows
By upgrading you accept licenses for the packages.
docker-for-windows v18.06.1.19507 is the latest version available based on
your source(s).

Chocolatey upgraded 0/1 packages.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Error which run docker is:

PS C:\Windows\system32> Docker
Docker : The term 'Docker' is not recognized as the name of a cmdlet,
function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At line:1 char:1

   - Docker
   -

     + CategoryInfo          : ObjectNotFound: (Docker:String) [],
CommandNotFoundException
     + FullyQualifiedErrorId : CommandNotFoundException



Thank you,
Jagan.

**Comment by revathi-muthana123** [comment]
Yes, You are right Jagan.
I think it can not be work for windows 7
I am also trying but not installing.
Can anyone suggest on this?

**Comment by raviops100** [comment]
Hi Jagan,
Installation failure
Reason No:1
To run Docker, your machine must have a 64-bit operating system running Windows 7 or higher.
Additionally, you must make sure that virtualization is enabled on your machine. 
 Reason No:2
Please install docker tool box 
Docker Toolbox automatically creates a Linux VM on VirtualBox that hosts Docker on your Windows system
go to below link
https://docs.docker.com/toolbox/toolbox_install_windows/
click on download next == go for default steps
once installed execute sample command

docker run hello-world

Thanks
Ravi

**Comment by Jaganarekatla** [comment]
Hi Ravi, Thank you for reply,

I have been tried the given wiki by you and i am able to install the docker , oracle VM box with Kitematic (Alpha) software sucessfully, but when i try to run the docker hello-world program getting the below error could you help on this,

![image](https://user-images.githubusercontent.com/40374014/46582225-35ea8300-ca61-11e8-8408-3251e1b7b7e5.png)

And same i tried to start the  docker daemon service with help of below but getting the same above error, could you help on this.


![image](https://user-images.githubusercontent.com/40374014/46582295-eeb0c200-ca61-11e8-9fcb-ee586cf111fc.png)

Another error which got from Oracle VM 

![image](https://user-images.githubusercontent.com/40374014/46582317-51a25900-ca62-11e8-95f6-2c6953fc73f8.png)

**Comment by Jaganarekatla** [comment]
Hi Ravi, Thank you for reply,

I have been tried the given wiki by you and i am able to install the docker
, oracle VM box with Kitematic (Alpha) software sucessfully, but when i try
to run the docker hello-world program getting the below error could you
help on this,

[image: image]
<https://user-images.githubusercontent.com/40374014/46582225-35ea8300-ca61-11e8-8408-3251e1b7b7e5.png>

And same i tried to start the docker daemon service with help of below but
getting the same above error, could you help on this.

[image: image]
<https://user-images.githubusercontent.com/40374014/46582295-eeb0c200-ca61-11e8-9fcb-ee586cf111fc.png>

Another error which got from Oracle VM

[image: image]
<https://user-images.githubusercontent.com/40374014/46582317-51a25900-ca62-11e8-95f6-2c6953fc73f8.png>
