### ISSUE TITLE
Experiencing strange behavior of Terraform

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [QT-DevOps/DevOpsIssues#207]
Hi Friends
Yesterday terraform was working fine, able to provision aws VM through terraform script.
But today, when I started its continuation, and when i am trying to execute terraform commands in Windows Powershell "Run as Administrator", firstly i typed : 
1. D:\terraform init -------> displays error message
2. I typed D:\ choco install terraform -y ---------> says already installed 
Displaying the same error for any command that i type. Though spellings are correct, path is also correct, unable to find out what went wrong..
Please see screenshot as well..
![terraformissue](https://user-images.githubusercontent.com/16450606/46581221-7a225700-ca52-11e8-988d-b8cd1f240c9f.png)

**Comment by revathi-muthana123** [comment]
if you install packer manually then set environment variable
location is:   right click on computers>>>>properties>>>advanced system settings>>>>path>>>edit

**Comment by SajidAliKhanMohammed** [comment]
This is the issue i am getting : 
![untitled1](https://user-images.githubusercontent.com/16450606/46596177-30407c00-caf9-11e8-8dbc-a7f5b52b8db0.png)

**Comment by revathi-muthana123** [comment]
please follow the link to set environmental variable, then try to execute commands.
https://www.nextofwindows.com/how-to-addedit-environment-variables-in-windows-7

**Comment by shaikkhajaibrahim** [comment]
choco uninstall terraform 
& then
choco install terraform

close powershell

open new powershell terminal & execute terraform --version
