### ISSUE TITLE
vagrant: getting error with vagrant up

### ISSUE THREAD

**Issue by veerendradevops** [QT-DevOps/DevOpsIssues#21]
hai guys,
i am trying to install ubuntu 14.04 with vagrant,  i am getting below error.

vagrant up
The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.

  Installed version: N/A
  Minimum required version: 3

![screenshot 1](https://user-images.githubusercontent.com/37468369/40670118-372bc1bc-6386-11e8-9a97-f6aa8302ec88.png)

**Comment by ghost** [comment]
Hi @veerendradevops

Check your PowerShell version, by default it will be 2.0
get-host (enter this command in PowerShell to check version)

We need 4.0 version to run vagrant.
Upgrade PowerShell to 4.0 using Choco.

choco upgrade powershell4 --version 4.0

It requires DotNet 4.5 version
