### ISSUE TITLE
Anybody working in Chef real-time?

### ISSUE THREAD

**Issue by ksateesh22** [QT-DevOps/DevOpsIssues#210]
Is anybody working in Chef real-time? 
what is the actual process/steps  followed ?

Is this the way that most developers do, I mean is it industry standard?

1.we would install Kitchen on laptops
2. create cookbooks
3.test them (on the different specific OS etc) using vagrant etc.
4. and then push to the cookbooks to the server.  

All who are working on chef ,, can you please share your thoughts

**Comment by shaikkhajaibrahim** [comment]
Yes. There might be slight changes in the process as per project/architectural needs
