### ISSUE TITLE
Error while Chef Kitchen create

### ISSUE THREAD

**Issue by ksateesh22** [QT-DevOps/DevOpsIssues#211]
I am getting the following error while doing a kitchen create . I deleted all the vms in the virtual box, deleted the folders in the Virtualbox VMs folder but the problem still persists. can somebody help.

C:\Customers\QT\Chef\git_cookbook>kitchen create
-----> Starting Kitchen (v1.23.2)
-----> Creating <default-ubuntu-1604>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Checking if box 'bento/ubuntu-16.04' is up to date...
       Your VM has become "inaccessible." Unfortunately, this is a critical error
       with VirtualBox that Vagrant can not cleanly recover from. Please open VirtualBox
       and clear out your inaccessible virtual machines or find a way to fix
       them.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'bento/ubuntu-16.04' is up to date...
STDERR: Your VM has become "inaccessible." Unfortunately, this is a critical error
with VirtualBox that Vagrant can not cleanly recover from. Please open VirtualBox
and clear out your inaccessible virtual machines or find a way to fix
them.
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1] on default-ubuntu-1604
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

C:\Customers\QT\Chef\git_cookbook>kitchen diagnose --all
---
timestamp: 2018-10-08 13:37:51 UTC
kitchen_version: 1.23.2
plugins:
  driver:
    Vagrant:
      class: Kitchen::Driver::Vagrant
      version: 1.3.3
      api_version: 2
  provisioner:
    ChefZero:
      class: Kitchen::Provisioner::ChefZero
      version: 1.23.2
      api_version: 2
  transport:
    Ssh:
      class: Kitchen::Transport::Ssh
      version: 1.23.2
      api_version: 1
  verifier:
    Inspec:
      class: Kitchen::Verifier::Inspec
      version: 0.23.1
      api_version: 1
loader:
  process_erb: true
  process_local: true
  process_global: true
  global_config:
  project_config:
    filename: C:/Customers/QT/Chef/git_cookbook/.kitchen.yml
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: chef_zero
        always_update_cookbooks: true
      verifier:
        name: inspec
      platforms:
      - name: ubuntu-16.04
      suites:
      - name: default
        run_list:
        - recipe[git_cookbook::default]
        verifier:
          inspec_tests:
          - test/integration/default
        attributes:
  local_config:
  combined_config:
    filename:
    raw_data:
      driver:
        name: vagrant
      provisioner:
        name: chef_zero
        always_update_cookbooks: true
      verifier:
        name: inspec
      platforms:
      - name: ubuntu-16.04
      suites:
      - name: default
        run_list:
        - recipe[git_cookbook::default]
        verifier:
          inspec_tests:
          - test/integration/default
        attributes:
instances:
  default-ubuntu-1604:
    platform:
      os_type: unix
      shell_type: bourne
    state_file:
      last_error: Kitchen::ShellOut::ShellCommandFailed
    driver:
      boot_timeout:
      box: bento/ubuntu-16.04
      box_check_update:
      box_download_ca_cert:
      box_download_insecure:
      box_url:
      box_version:
      cache_directory: "/tmp/omnibus/cache"
      cachier:
      customize: {}
      gui:
      kitchen_cache_directory: C:/Users/ksateesh/.kitchen/cache
      kitchen_root: C:/Customers/QT/Chef/git_cookbook
      linked_clone:
      log_level: :info
      name: vagrant
      network: []
      pre_create_command:
      provider: virtualbox
      provision: false
      ssh: {}
      synced_folders:
      - - C:/Users/ksateesh/.kitchen/cache
        - "/tmp/omnibus/cache"
        - 'create: true'
      test_base_path: C:/Customers/QT/Chef/git_cookbook/test/integration
      vagrant_binary: vagrant
      vagrantfile_erb: C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/kitchen-vagrant-1.3.3/templates/Vagrantfile.erb
      vagrantfiles: []
      vm_hostname: default-ubuntu-1604.vagrantup.com
    provisioner:
      always_update_cookbooks: true
      architecture:
      attributes: {}
      channel: :stable
      checksum:
      chef_client_path: "/bin/chef-client"
      chef_omnibus_install_options:
      chef_omnibus_url: https://omnitruck.chef.io/install.sh
      chef_zero_host:
      chef_zero_port: 8889
      client_rb: {}
      clients_path:
      command_prefix:
      config_path:
      cookbook_files_glob: README.*,metadata.{json,rb},attributes/**/*,definitions/**/*,files/**/*,libraries/**/*,providers/**/*,recipes/**/*,resources/**/*,templates/**/*
      data_bags_path:
      data_path:
      debug:
      deprecations_as_errors: false
      download_url:
      downloads: {}
      encrypted_data_bag_secret_key_path:
      enforce_idempotency: false
      environments_path:
      ftp_proxy:
      http_proxy:
      https_proxy:
      install_strategy: once
      json_attributes: true
      kitchen_root: C:/Customers/QT/Chef/git_cookbook
      log_file:
      log_level: auto
      max_retries: 1
      multiple_converge: 1
      name: chef_zero
      named_run_list: {}
      nodes_path:
      platform:
      platform_version:
      policyfile:
      policyfile_path:
      product_name:
      product_version: :latest
      profile_ruby: false
      require_chef_omnibus: true
      retry_on_exit_code:
      - 35
      - 213
      roles_path:
      root_path: "/tmp/kitchen"
      ruby_bindir: "/embedded/bin"
      run_list:
      - recipe[git_cookbook::default]
      sudo: true
      sudo_command: sudo -E
      test_base_path: C:/Customers/QT/Chef/git_cookbook/test/integration
      wait_for_retry: 30
    transport:
      compression: false
      compression_level: 0
      connection_retries: 5
      connection_retry_sleep: 1
      connection_timeout: 15
      keepalive: true
      keepalive_interval: 60
      kitchen_root: C:/Customers/QT/Chef/git_cookbook
      log_level: :info
      max_ssh_sessions: 9
      max_wait_until_ready: 600
      name: ssh
      port: 22
      ssh_gateway:
      ssh_gateway_port: 22
      ssh_gateway_username:
      ssh_http_proxy:
      ssh_http_proxy_password:
      ssh_http_proxy_port:
      ssh_http_proxy_user:
      ssh_key:
      test_base_path: C:/Customers/QT/Chef/git_cookbook/test/integration
      username: root
    verifier:
      chef_omnibus_root: "/opt/chef"
      command_prefix:
      debug:
      ftp_proxy:
      http_proxy:
      https_proxy:
      inspec_tests:
      - test/integration/default
      kitchen_root: C:/Customers/QT/Chef/git_cookbook
      log_level: :info
      name: inspec
      root_path: "/tmp/verifier"
      sudo: true
      sudo_command: sudo -E
      suite_name: default
      test_base_path: C:/Customers/QT/Chef/git_cookbook/test/integration

C:\Customers\QT\Chef\git_cookbook>

**Comment by arunkumar127** [comment]
@ksateesh22 

Open VirtualBox & delete any **Inaccessible** VMs in VirtualBox (Shown as in below screenshot). Now try Kitchen Create.
![vm](https://user-images.githubusercontent.com/40756184/46618439-23457c00-cb3d-11e8-9544-5fd7f9c00763.png)
I hope it will work after deleting Inaccessible VMs from VirtualBox.

Regards
Arun Kumar

**Comment by ksateesh22** [comment]
Thanks for the help Arun.. I did what you suggested but it didn't solve the
issue

**Comment by shaikkhajaibrahim** [comment]
Is the manual virtual box creation working ?
