### ISSUE TITLE
packer build struck at passing access and secret key run time

### ISSUE THREAD

**Issue by saikiranjayanthi** [QT-DevOps/DevOpsIssues#212]
HI
 I am facing a issue.when i want to pass secret and access key as a run time variable.
This is the basic script i am using{
    "variables": {
      "aws_access_key": "",
      "aws_secret_key": ""
    },

    "builders":[
         {
        "type" :"amazon-ebs",
        "region" :"us-west-2",
        "source_ami" : "ami-09bfeda7337019518",
        "access_key" : "{{user `aws_access_key`}}",
        "secret_key" : "{{user `aws_secret_key`}}",
        "ssh_username" : "ubuntu",
       "instance_type" : "t2.micro" ,
        "ami_name" : "packer-ami-HELP"
         }
    ],
    "provisioners" : [
        {
            "type": "shell",
            "inline":["sudo apt-get update" , "sudo apt-get install git -y"]
        }
    ]
}

{
    "variables": {
      "aws_access_key": "",
      "aws_secret_key": ""
    },

    "builders":[
         {
        "type" :"amazon-ebs",
        "region" :"us-west-2",
        "source_ami" : "ami-09bfeda7337019518",
        "access_key" : "{{user `aws_access_key`}}",
        "secret_key" : "{{user `aws_secret_key`}}",
        "ssh_username" : "ubuntu",
       "instance_type" : "t2.micro" ,
        "ami_name" : "packer-ami-HELP"
         }
    ],
    "provisioners" : [
        {
            "type": "shell",
            "inline":["sudo apt-get update" ,"sudo apt-get install git -y"]
        }
    ]
}
![packer](https://user-images.githubusercontent.com/43769701/46637369-894ff480-cb79-11e8-80d0-8d05da843b5c.PNG)

it is struck their from 3 to 4 hrs.
i have tried by passing hard code  values . it is running successfully.
i have tried packer validate and inspect also. template is creating.

**Comment by saikiranjayanthi** [comment]
one more question is everytime i need to create a access and secret key?
after using i am deleted a key pair and again generating.Is this is recommanded ?

**Comment by ramana152** [comment]
@saikiranjayanthi    Hi i tried with your json file it is working good..it is created AMI also..

amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name: packer-ami-HELP
    amazon-ebs: Found Image ID: ami-0eb1f21bbd66347fe
==> amazon-ebs: Creating temporary keypair: packer_5bbbf018-0479-823b-287f-88cdb807cec2
==> amazon-ebs: Creating temporary security group for this instance: packer_5bbbf01b-70bc-3cb1-2965-fb1bc63db8f1
==> amazon-ebs: Authorizing access to port 22 from 0.0.0.0/0 in the temporary security group...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
    amazon-ebs: Instance ID: i-03f6494a7ab1a3d2f
==> amazon-ebs: Waiting for instance (i-03f6494a7ab1a3d2f) to become ready...
==> amazon-ebs: Using ssh communicator to connect: 3.0.50.228
==> amazon-ebs: Waiting for SSH to become available...
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Provisioning with shell script: C:\Users\India\AppData\Local\Temp\packer-shell463370147
    amazon-ebs: Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
    amazon-ebs: Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
    amazon-ebs: Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
    amazon-ebs: Get:4 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [563 kB]
    amazon-ebs: Get:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
    amazon-ebs: Get:6 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [7532 kB]
    amazon-ebs: Get:7 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [237 kB]
    amazon-ebs: Get:8 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [387 kB]
    amazon-ebs: Get:9 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [147 kB]
    amazon-ebs: Get:10 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3460 B]
    amazon-ebs: Get:11 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [1744 B]
    amazon-ebs: Get:12 http://archive.ubuntu.com/ubuntu xenial/universe Translation-en [4354 kB]
    amazon-ebs: Get:13 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [144 kB]
    amazon-ebs: Get:14 http://archive.ubuntu.com/ubuntu xenial/multiverse Translation-en [106 kB]
    amazon-ebs: Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [856 kB]
    amazon-ebs: Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [349 kB]
    amazon-ebs: Get:17 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [690 kB]
    amazon-ebs: Get:18 http://archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [279 kB]
    amazon-ebs: Get:19 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.4 kB]
    amazon-ebs: Get:20 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [8344 B]
    amazon-ebs: Get:21 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [7304 B]
    amazon-ebs: Get:22 http://archive.ubuntu.com/ubuntu xenial-backports/main Translation-en [4456 B]
    amazon-ebs: Get:23 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [7804 B]
    amazon-ebs: Get:24 http://archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [4184 B]
    amazon-ebs: Fetched 16.0 MB in 8s (1821 kB/s)
    amazon-ebs: Reading package lists...
    amazon-ebs: Reading package lists...
    amazon-ebs: Building dependency tree...
    amazon-ebs: Reading state information...
    amazon-ebs: git is already the newest version (1:2.7.4-0ubuntu1.4).
    amazon-ebs: 0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.
==> amazon-ebs: Stopping the source instance...
    amazon-ebs: Stopping instance, attempt 1
==> amazon-ebs: Waiting for the instance to stop...
==> amazon-ebs: Creating unencrypted AMI packer-ami-HELP from instance i-03f6494a7ab1a3d2f
    amazon-ebs: AMI: ami-05bbc3690ff2a4e73
==> amazon-ebs: Waiting for AMI to become ready...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' finished.

==> Builds finished. The artifacts of successful builds are:
--> amazon-ebs: AMIs were created:
ap-southeast-1: ami-05bbc3690ff2a4e73

**Comment by arunkumar127** [comment]
@saikiranjayanthi 
You have taken variables aws_access_key & aws_secret_key, but in packer build command you have given -var 'access=' -var 'secret='.
I did not get why you gave not mentioned variables in command line.

Your packer build command should be
**packer build -var 'aws_access_key=' -var 'aws_secret_key=' aws-hello.json**

Regards
Arun Kumar

**Comment by revathi-muthana123** [comment]
> one more question is everytime i need to create a access and secret key?
> after using i am deleted a key pair and again generating.Is this is recommanded ?

yes, it is recommanded for security purpose
or else "inactive" credentials after completion of your work, then again "active" when you start working.

Thank you.

**Comment by revathi-muthana123** [comment]
Is it  working now? Have you corrected variable names?

**Comment by saikiranjayanthi** [comment]
Thanks revathi/Arun/ramana

Yes it is working fine now
