### ISSUE TITLE
Deploy Nodejs through Reverse Proxy 

### ISSUE THREAD

**Issue by naveenaws66** [QT-DevOps/DevOpsIssues#213]
problem with configuring /etc/nginx/nginx.conf.
configured my nodejs server private ip in /etc/nginx/nginx.conf file  
even then nginx application was unable to load nodejs application .
launched 2 servers first one for nodejs app and second for nginx
opened all my ports for all protocols in aws security group and both the servers were using same vpc and SG.
followed this tutorials 
https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-centos-7

attaching all required images.
![0001_pm2nodejs_app_running](https://user-images.githubusercontent.com/37922029/46656059-c98b9300-cbca-11e8-91e3-54a668f9d076.PNG)
![0002_from_browser_nodejsapp_upandrunning](https://user-images.githubusercontent.com/37922029/46656062-c98b9300-cbca-11e8-8805-774f6e21c406.PNG)
![0003_nginx_status_in_secondserver](https://user-images.githubusercontent.com/37922029/46656064-ca242980-cbca-11e8-9849-573791b3d2da.PNG)
![0004_nginx_statusfrom_browser](https://user-images.githubusercontent.com/37922029/46656065-ca242980-cbca-11e8-9aad-468d4689262c.PNG)
![0005configureing_nginx_conf_file_with_nodejs_privateip](https://user-images.githubusercontent.com/37922029/46656066-ca242980-cbca-11e8-86d2-3f61981ec80a.PNG)

After configuring private ip of nodejs i am getting  following error.

![0006after_configureing_nginx_conf_file](https://user-images.githubusercontent.com/37922029/46656067-cabcc000-cbca-11e8-9a74-b20c600d7ca6.PNG)

Please help

**Comment by arunkumar127** [comment]
@Naveen
Please recheck IP Address format you have provided in nginx.conf file.
It should be http://172.31.92.40:8080
(There is an extra : in IP Address).

- Modify conf file with correct IP
- Restart Nginx service
- Access Reverse proxy server

Regards
Arun Kumar.

**Comment by naveenaws66** [comment]
@arunkumar127    That is not the issue ,i corrected it and tried but didn't worked

**Comment by arunkumar127** [comment]
@Naveen
Create a user with password access, provide ssh access to your server.
Let me work on it.

**Comment by naveenaws66** [comment]
@arunkumar127 

have you tried doing use case from 
https://github.com/asquarezone/ChefZone/blob/master/Workbook/nodejs/Workbooks.md 

very first one was installing nginx on ubuntu but i tried on centos7.
using  following link.
https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-centos-7

if you have tried it on centos  and successful let me know
if not tried, please do it using above link i have given for centos7 on aws and if successful let me know.

**Comment by arunkumar127** [comment]
@naveenaws66 
It is working good for me with two Centos 7 Instances. Check below screenshots

NodeJS application running 
![0](https://user-images.githubusercontent.com/40756184/46711870-e1672380-cc6b-11e8-9ddb-0ee668e5361a.jpg)
![1](https://user-images.githubusercontent.com/40756184/46711882-ec21b880-cc6b-11e8-8ca0-a100f7095a4d.jpg)

Nginx Server up & running
![2](https://user-images.githubusercontent.com/40756184/46711893-00fe4c00-cc6c-11e8-9a84-4e7f18dc8130.jpg)
![3](https://user-images.githubusercontent.com/40756184/46711901-0cea0e00-cc6c-11e8-822a-ac776776ade2.jpg)

Server block in /etc/nginx/nginx.conf
![4](https://user-images.githubusercontent.com/40756184/46711920-2b500980-cc6c-11e8-9566-534bcf5f9165.jpg)

Nginx as a reverse proxy accessing NodeJS app.
![5](https://user-images.githubusercontent.com/40756184/46711968-5aff1180-cc6c-11e8-9ba7-87e32b66a44e.jpg)

**Comment by arunkumar127** [comment]
Check Nginx error log file /var/log/nginx/error.log
If you have error **_(13: Permission denied) while connecting to upstream_**, run below command
$ **sudo setsebool -P httpd_can_network_connect 1**
(Checked from **https://stackoverflow.com/questions/23948527/13-permission-denied-while-connecting-to-upstreamnginx/24830777#24830777**)

Regards
Arun Kumar

**Comment by arunkumar127** [comment]
It's working fine for me with two Centos 7 instances. (one with NodeJS & other with Nginx)

NodeJS up & running.
![1](https://user-images.githubusercontent.com/40756184/46713765-e4ffa800-cc75-11e8-9ded-1bf824b75b01.jpg)
![2](https://user-images.githubusercontent.com/40756184/46713779-f21c9700-cc75-11e8-879f-f341fa9049b0.jpg)

Nginx up & running.
![5](https://user-images.githubusercontent.com/40756184/46713803-0bbdde80-cc76-11e8-8ef3-1017c7b15a45.jpg)
![3](https://user-images.githubusercontent.com/40756184/46713811-14aeb000-cc76-11e8-83a2-ae56a43ebf28.jpg)

Server block in /etc/nginx/nginx.conf
![4](https://user-images.githubusercontent.com/40756184/46713824-242df900-cc76-11e8-9be5-7797d8338957.jpg)

Nginx as reverse proxy accessing NodeJS app.
![6](https://user-images.githubusercontent.com/40756184/46713857-46c01200-cc76-11e8-88b1-827e67988aa2.jpg)

Regards
Arun Kumar

**Comment by naveenaws66** [comment]
hi @arunkumar127 
destroyed my old servers created new servers.
this time its not showing any error page.its showing home page of nginx without any errors but its not redirecting to nodejs.

**Comment by naveenaws66** [comment]
since problem is redirecting to  nodejs server it must be configuration mistake so here are my nginx.conf and hello.js files

[hello.js.txt](https://github.com/QT-DevOps/DevOpsIssues/files/2463294/hello.js.txt)
[nginx.conf.txt](https://github.com/QT-DevOps/DevOpsIssues/files/2463300/nginx.conf.txt)


Thanks buddy @arunkumar127  problem solved . actually its (13: Permission denied) while connecting to upstream error . i ran below command as u said , i should have checked those logs when you said  .  thanks for help.  

sudo setsebool -P httpd_can_network_connect 1

**Comment by shaikkhajaibrahim** [comment]
Is this resolved

**Comment by naveenaws66** [comment]
yes, its resolved.
