### ISSUE TITLE
in docker 

### ISSUE THREAD

**Issue by lingambaikari** [QT-DevOps/DevOpsIssues#214]
how to i re-use ,removable container ,is there any command sir?

**Comment by revathi-muthana123** [comment]
Hi,

To my knowledge, it's not possible to get back removable container.
If you want  again re-pull same image or run same image, then u will get a container.

If your container is in "stop" state it's possible to start that container.
find it in "docker ps -a"
then start container with "docker start" command.

Thanks & Regards
Revathi

**Comment by lingambaikari** [comment]
Tq mam

**Comment by shaikkhajaibrahim** [comment]
Once container is removed it cannot be restored

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
