### ISSUE TITLE
Information on Devops Class

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#215]
Hi Sir,

Could you please tell when are we starting Puppet/Chef/Ansible in our Devops class as per the syllabus?

**Comment by arunkumar127** [comment]
@Aamukta 
From which topic you have started course? 
Puppet is not part of our course.
As of now Docker is being covered, so upcoming topics will be Monitoring tools, Powershell DSC (Win DevOps), Ansible, Chef. (Order may vary, it depends on Khaja sir which topic he may choose).

Regards
Arun Kumar

**Comment by Aamukta** [comment]
Ok thanks Arun.. I have started from GIT.. so approximately how long it
might take to reach Ansible if that is the sequnece which you have
mentioned..

**Comment by revathi-muthana123** [comment]
Hi @Aamukta 
According to Shcedule, It is expected to start Ansible on Nov-19th, Chef will be on Dec-3rd.
But these are not exact dates. It may have slight changes.

Thanks & Regards
Revathi

**Comment by Aamukta** [comment]
Ok thanks Revathi for info.. you may close the issue..

**Comment by revathi-muthana123** [comment]
You only have that option to close this issue. Can you pls  close?

**Comment by Aamukta** [comment]
Ok Revathi.. will do
