### ISSUE TITLE
How to find the ip address of packer image in AWS

### ISSUE THREAD

**Issue by saikiranjayanthi** [QT-DevOps/DevOpsIssues#216]
Hi Sir,

can i know where we can see the ip address of packer image which  was created in AWS.
can you please guide me path in AWS.

**Comment by revathi-muthana123** [comment]
Hi,
Packer is used to create only images, not instances. Image doesn't has ip address.
After launching instance from that image, we can get IP address = Public IP + Private IP

Thanks & Regards
Revathi
