### ISSUE TITLE
service apache not active it goes inctive mode 

### ISSUE THREAD

**Issue by lingambaikari** [QT-DevOps/DevOpsIssues#218]
service apache not active it goes inctive mode ..cant start again why?
![screenshot 17](https://user-images.githubusercontent.com/42967022/46854921-fc7a9480-ce1f-11e8-904d-b830f73ed082.png)

**Comment by arunkumar127** [comment]
@lingambaikari 
Authentication failure.
Run command with admin privilege (sudo).
$ **sudo service apache2 start**
$ **sudo service apache2 status**

Regards
Arun Kumar

**Comment by ramana152** [comment]
@lingambaikari   u can start the service manually  by using **service apache2 start**

**Comment by revathi-muthana123** [comment]
@lingambaikari 
How did you install ? What are  the steps ?

**Comment by revathi-muthana123** [comment]
@lingambaikari 

Try with these commands with sudo :
---------------------------------------
1. Sudo service apache2 start
2. Sudo service apache2 status
 
Eventhugh If you get again error, try with below commands:
------------------------------------------------------------------
  1. command to  Start Service : sudo systemctl start apache2
   2. For status : sudo systemctl status apache2

For Reference:
---------------
http://www.learn4master.com/programming-language/shell/start-restart-and-stop-apache-on-linux

Thanks & Regards
Revathi

**Comment by revathi-muthana123** [comment]
Is it done?

**Comment by lingambaikari** [comment]
Done sir tq...

**Comment by revathi-muthana123** [comment]
pls mention how did you resolve? Then close this issue.
