### ISSUE TITLE
not able to connect the internet using linux

### ISSUE THREAD

**Issue by vinay4001** [QT-DevOps/DevOpsIssues#219]
sir i am not able to connect to internet on git after launching instances. its showing that ec2-user@xx.xxx.xxx.xxx:permision denied <public key>
and it is showing no file or  directory

**Comment by arunkumar127** [comment]
@vinay4001 
Can you please be specific about what you are trying to do & your output.
Post screenshot of command & output you are getting.

**Comment by vinay4001** [comment]
How can I post image over here I'm new to this

**Comment by arunkumar127** [comment]
@vinay4001 
Just Drag & Drop image in the text section in this page to upload.
Or use **_selecting them_** option below text section to upload.

**Comment by vinay4001** [comment]
![screenshot_20181012-145138](https://user-images.githubusercontent.com/44084389/46861339-2045d680-ce30-11e8-9857-a504b83cdeef.png)

**Comment by arunkumar127** [comment]
@vinay4001 
Seems to be .pem file has read permission problem.
Run chmod command with 0644 permission on .pem file once.
$ **chmod 0644 adminaws.pem**

After running this command try to login. If problem still persists, create new instance with new identity file.
Let me know whether it is working or not.

**Comment by vinay4001** [comment]
Prem file can be created for private or public

**Comment by ramana152** [comment]
@vinay4001    r u in the lab?

**Comment by vinay4001** [comment]
Sir I have entered chmod 0644 adminaws.pem but still ita showing no file or directory

**Comment by cvreddy1236** [comment]
you have to provide the absolute path of .pem file.
      or
go to  the pem file location then open terminal there.

**Comment by arunkumar127** [comment]
@vinay4001 
Are you running ssh command from .pem file location. What is the location of pem file in your system?
Seems to be you are running ssh command from User directory.
Please verify pem file path & run again.

**Comment by ramana152** [comment]
@vinay4001    If you are getting same problem , Please connect Remote desktop , then only we will get to know what is the error and try to fix that error...

**Comment by revathi-muthana123** [comment]
@vinay4001 
If you facing same issue, We are in Lab to help you, can you pls reach me.
If you are online try to connect  with "Team Viewer"

**Comment by shaikkhajaibrahim** [comment]
Done ?

**Comment by vinay4001** [comment]
Yes sir
