### ISSUE TITLE
unable to install jenkins

### ISSUE THREAD

**Issue by babasmd** [QT-DevOps/DevOpsIssues#22]
sir,
when i tried to install jenkins its showing me following error please help me with that 
![image](https://user-images.githubusercontent.com/39340070/40710566-9ad7d63e-6416-11e8-8340-35ee7c9ce91e.png)
![image](https://user-images.githubusercontent.com/39340070/40710581-a4a0a48e-6416-11e8-8e9a-32860a163fb2.png)

**Comment by shaikkhajaibrahim** [comment]
If plugin install fails the only option is to reinstall. If the reinstall is failing removing JENKINS_HOME directory & retry

**Comment by babasmd** [comment]
sir how to remove JENKINS_HOME directory
its saying no such file or directory
![image](https://user-images.githubusercontent.com/39340070/40713955-ed315a7e-641e-11e8-9601-4e26f225875b.png)

**Comment by shaikkhajaibrahim** [comment]
JENKINS_HOME is environment variable for the Jenkins HOME DIRECTORY generally present @ /var/lib/jenkins.

PLease understand what you are trying to do before implementing any stuff

**Comment by chittalalk** [comment]
first type command echo $JENKINS_HOME you will find Jenkins home directory.

**Comment by babasmd** [comment]
sorry sir can u please tell me how to remove jenkins _home directory

**Comment by shaikkhajaibrahim** [comment]
rm -rf /var/lib/jenkins

**Comment by babasmd** [comment]
sir when i use these commands rm -rf /var/lib/jenkins

 its says permission denied ihave tried new ubuntu server still same issue sir unable to connect jenkins

**Comment by vijaybhaskarreddyy** [comment]
use sudo   rm -rf /var/lib/jenkins

**Comment by vijaybhaskarreddyy** [comment]
restart your jenkins service  and try again.

**Comment by shaikkhajaibrahim** [comment]
Is this resolved??

**Comment by babasmd** [comment]
yes sir due to internet issue its hapenning sir so i have created new instance and done installation its working
