### ISSUE TITLE
What are the steps to migrate ecomm site from AWS to another cloud?

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#220]
Hi Sir,
@shaikkhajaibrahim 

A relative of mine wants to migrate his self created e-commerce website from AWS to VULTR in Australia as it' far cheaper in comparison and also situated in Sydney. he plans to put up the task on freelancer.com
www.uniformaustralia.com.au and www.sauersclothing.com.au

In such a scenario, what are the basic steps to be looked into, in order to carry out this task?
I have asked him for a read only user access using IAM, to
1. View what machines are used - OS and size
2. What RDS is used
3. Structure of network & subnets and the Route Table rules
4. Check for auto scaling - which he said he has not implemented
5. I can ask him whether he used apache server or tomcat server

I don't have any web experience other than Quality Thought education on Cloud and DevOps.
Is there some other points to be checked or asked?
Please give some pointers, so that in the best case he gives me the job, or in the worst case, at least I can compare my analysis with what is implemented by the professional that does this work and learn something.

Regards
Ramesh

**Comment by shaikkhajaibrahim** [comment]
Find out the  technologies used. 
Migration changes from technology to technology

**Comment by rameshm78** [comment]
Hi Sir,
@shaikkhajaibrahim 

The technologies used are basically Micrososft.
AMI ID 
=Windows_Server-2012-RTM-English-64Bit-SQL_2012_SP3_Web-2018.04.11 (ami-157ab377)
Size = m3.xlarge
Website developed in .Net using C#.

Single machine hosting both web-server and database - was recently disabled by ransomeware.
The SG inbound rules are as follows:

![image](https://user-images.githubusercontent.com/40449948/47760803-2666fe80-dcdc-11e8-8af5-5df6efc234e8.png)

The NACL rules are as follows:

![image](https://user-images.githubusercontent.com/40449948/47762060-0980fa00-dce1-11e8-953b-6bd8edb13a3e.png)

Is there anything else wrt technology that I need to find out?
Does .Net code need to be changed if we change from Windows Server 2012 to any recent version, say Win Server 2016?

Regards
Ramesh

**Comment by rameshm78** [comment]
Hi Sir,
@shaikkhajaibrahim 

The major challenge at the moment seems to be how to download the database dump from AWS, so that it can be transferred to Vultr cloud. Is there any way to do this?

Regards
Ramesh

**Comment by shaikkhajaibrahim** [comment]
Couple of ways.

One is using SSIS (ETL)

other area is using sql server management studio export the database into your system & then  import it on to the other cloud
________________________________

**Comment by rameshm78** [comment]
Thank you Sir. @shaikkhajaibrahim 
I'll google the methods suggested.

This is currently on AWS. Is there any method, to take an image of the setup, download it to local system and then upload it for deployment on the target cloud?

Regards
Ramesh
