### ISSUE TITLE
permission denied, while I am installing anything on aws ubantu

### ISSUE THREAD

**Issue by haridasuvenky** [QT-DevOps/DevOpsIssues#221]
ubuntu@ip-172-31-42-142:/$ docker pull hello-world
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.27/info: dial unix /var/run/docker.sock: connect: permission denied). Using system default: https://index.docker.io/v1/
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.27/images/create?fromImage=hello-world&tag=latest: dial unix /var/run/docker.sock: connect: permission denied

**Comment by ramana152** [comment]
@haridasuvenky  What you are trying to install and what you are getting error? can u drop   screen shot here...

**Comment by revathi-muthana123** [comment]
@haridasuvenky 
It looks like you're not part of the Docker group in Ubuntu.
=> If you're not part of the group, add user by running  "sudo usermod -a -G docker <your_username>"
=> ubuntu user : 
$ sudo usermod -aG docker ubuntu
     After adding to group exit from ubuntu machine then re-login
=>check "docker info"
=>Verify that you can run docker commands without sudo.

$ docker run hello-world

Thanks & Regards
Revathi

**Comment by revathi-muthana123** [comment]
Hi, Is it resolved ????
