### ISSUE TITLE
Docker Installation Issues

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [QT-DevOps/DevOpsIssues#222]
Hi Friends
I am blocked with practicing Docker. My laptop configuration was Windows 7 32-bit, so docker was giving problems in running commands. No I upgraded my system to **Win 7 64-bit**, still facing errors while running docker commands. Please see screenshots of docker installation and errors while running docker ps commands.
If it is an environment variable path setup issue, please let me know how to set up env variables..
![untitled](https://user-images.githubusercontent.com/16450606/46935923-4bbc0180-d07a-11e8-8f29-4e2e3e2c5f67.png)
![untitled2](https://user-images.githubusercontent.com/16450606/46935924-4bbc0180-d07a-11e8-8f64-418ca84c6659.png)
Thanks
SajidKhan

**Comment by raviops100** [comment]
Hi

**Comment by raviops100** [comment]
Hi SAjid, 
Please go through issue number 206
There I have given docker installation steps on windows 
Suggestion: if you have time please work on 
Docker installation on  Linux and then practice docker commands 
Thanks 
Ravi
