### ISSUE TITLE
default browser in powershell

### ISSUE THREAD

**Issue by veerendradevops** [QT-DevOps/DevOpsIssues#224]
/> Get-Help Get-Process -Online,
 when we execute above command in powershell, it'll give the result in default browser INTERNET EXPLORER. how can we change it to GOOGLE CHROME or any other browser.  thanks in advance

**Comment by raviops100** [comment]
Hi Veerendra,

To change default browser IE to Chrome please try to execute below commands in powersheel

$chromePath = "${Env:ProgramFiles(x86)}\Google\Chrome\Application\" 
$chromeApp = "chrome.exe"
$chromeCommandArgs = "--make-default-browser"
& "$chromePath$chromeApp" $chromeCommandArgs

Thanks
Ravi

**Comment by veerendradevops** [comment]
Hi Ravi,
Thank u for ur responce....plz let me know, was it worked for u??, because i have already done that, but that code didn't worked for me. i got the below error,

At line:1 char:46
+ $chromeCommandArgs = "--make-default-browser"& "$chromePath$chromeApp ...
+                                              ~
Unexpected token '&' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
,
