### ISSUE TITLE
Docker container isn't running

### ISSUE THREAD

**Issue by Santosh-Peddada** [QT-DevOps/DevOpsIssues#225]
Hi
Please find the the docker file.

FROM ubuntu:xenial
RUN apt-get update && apt-get install iputils-ping -y
RUN apt-get install apache2 -y && apt-get install tomcat7 -y
RUN service apache2 start
EXPOSE 8080 80
ENTRYPOINT ["ping"]
CMD ["google.com"]

After building and running docker... i am not able to container running.
I there anything i missed?

**Comment by arunkumar127** [comment]
@Santosh-Peddada 
What is the Docker run command you have run? I have tested your Dockerfile and container is running.

Dockerfile content
![1](https://user-images.githubusercontent.com/40756184/46999856-78d4e680-d144-11e8-8da1-f32e7a5bba77.jpg)

$ **docker build -t pingtest .** _(Image created)_
![2](https://user-images.githubusercontent.com/40756184/46999933-ade13900-d144-11e8-8b3c-f47fd5804c68.jpg)

$ **docker run -d -p 8080:8080 -p 80:80 --name apache-tomcat-ping pingtest** _(Created a container with name apache-tomcat-ping & it is running)_
![3](https://user-images.githubusercontent.com/40756184/47000110-2f38cb80-d145-11e8-8f7a-a9a48a120abc.jpg)

$ **docker logs apache-tomcat-ping** _(Ping successful)_
![5](https://user-images.githubusercontent.com/40756184/47000246-7cb53880-d145-11e8-9488-df185144dd9d.jpg)

Apache & Tomcat running
![6](https://user-images.githubusercontent.com/40756184/47000616-475d1a80-d146-11e8-918e-bf17e1bbae52.jpg)
