### ISSUE TITLE
How to connect Private subnet vm from Public subnet vm

### ISSUE THREAD

**Issue by rahul1984p** [QT-DevOps/DevOpsIssues#226]
Hi Team 
My name is Rahul Pawar.
I have few doubts regarding accessing Private subnet vm from Public subnet vm. 

query
1) are we accessing  DB subnet vm using private IP (10.10.2.X) 
2) do we have to modify the both routes ? 
3) or we are using public ip of DB subnet vm  to access it ?

**Comment by revathi-muthana123** [comment]
Hi Rahul,
It's not possible to access directly into DB subnet which is private.
 just  edit default route table attach internet gate way

To Verify
---------
1. Launch 2 instances for two subnets
   => one instance from public subnet
   =>  second instance from Private subnet
2. Copy  Private key (.Pem file) into public server
3. Login to Public server
4. From that server you need  login to private server (DB) with "ssh -i "pem file" user@private ip" 
    command to access

Thanks & Regards
Revathi

**Comment by revathi-muthana123** [comment]
If u want to get internet for DB Server, Pls follow these steps in VPC
1. Create one private route table  and associate with private subnet
2. Create NAT gateway with elastic IP
3. Attach NAT gateway to Private route table
4.  Now you will get internet to DB server

**Comment by rahul1984p** [comment]
Thanks Revathi . The issue is resolved now . 
while Setting up the NAT gateway i had associated it with Private subnet instead of Public subnet and which is why i was not able to access the internet on DB vm. And Thanks for the steps to copy .pem file and access db from Private IP
