### ISSUE TITLE
80:8080

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#228]
When  we do Port Forwarding, why do we use 80:8080. Rather it can be 80:80.
Is there a reason for that?
When I checked Tomcat's image, its Expose 8080. why is that 8080?

**Comment by arunkumar127** [comment]
@Aamukta 

### Docker Port Forwarding
**< portno >:< portno >**
- 1st port represents Docker host (Machine in which Docker Container is running, like EC2 Instance/VM/Physical machine)
- 2nd Port represents TCP port of Docker Container (Application port of Container which is running)

### Let's consider 80:8080
For example our machine has a container with Tomcat, which requires 8080 port to run. If we did mapping like 80:8080, to access application we have to run "**< IPAddr >:80**".
In the same machine if we run another container which requires 8080 port like Jenkins, then our mapping should be like 81:8080. To access this "**< IPAddr >:81**" (We can't do 80:8080 as 80 is already in use.)
But as a convention we generally map ports very closer to actual value, like 8080/8081 or as per what our team uses.
(8080:8080 / 8081:8080)

### Let's consider EXPOSE
EXPOSE < port no > gives information of what ports we should use to map while running the container.
For Tomcat/Jenkins 8080 port should me mapped. For Apache/Httpd 80 port should be mapped.
Consider a scenario like I have written a Dockerfile and asked you to run it, but you are unaware of what the Dockerfile is about (Like what does it Install/Configures/Port which it uses). If it has EXPOSE, then you  can run container with required port mapped.

### Let's consider 80:80
This purely depends on which port number our container uses. Check port number and map accordingly.

Regards
Arun Kumar

**Comment by arunkumar127** [comment]
### Why we do port forwarding?
Consider most used scenario in our class room.
We have to deploy Web Applications like Gameoflife/ Petclinic/ OpenMRS projects in Tomcat. We have written a Dockerfile which does each & every step mentioned above & we have built an Image. We have run a Container from Image created using network (default/custom created n/w). This container will have an IP address, we cannot provide this IP to our customer. We have to provide MachineIP:Portno/Projectname or Website/Projectname.

To do above scenario we have to do port mapping
$ **docker run -p < tcpport >: < containerport> < imagename >**
This will provide access to Container using Machine's IP
MachineIP:Portno/Projectname.

Apache/Httpd/Nginx uses port 80. MySQL uses port 3306. Perform port mapping as per your project requirement.

### Refer
https://docs.docker.com/engine/reference/builder/#expose

Regards
Arun Kumar

**Comment by Aamukta** [comment]
> ### Why we do port forwarding?
> Consider most used scenario in our class room.
> We have to deploy Web Applications like Gameoflife/ Petclinic/ OpenMRS projects in Tomcat. We have written a Dockerfile which does each & every step mentioned above & we have built an Image. We have run a Container from Image created using network (default/custom created n/w). This container will have an IP address, we cannot provide this IP to our customer. We have to provide MachineIP:Portno/Projectname or Website/Projectname.
> 
> To do above scenario we have to do port mapping
> $ **docker run -p < tcpport >: < containerport> < imagename >**
> This will provide access to Container using Machine's IP
> MachineIP:Portno/Projectname.
> 
> Apache/Httpd/Nginx uses port 80. MySQL uses port 3306. Perform port mapping as per your project requirement.
> 
> ### Refer
> https://docs.docker.com/engine/reference/builder/#expose
> 
> Regards
> Arun Kumar

Thanks Arun. Got it :)
