### ISSUE TITLE
Unable to access recorded vedios in webinar.

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#229]
Hi Team, I am unable to access any of the videos. Tried oct 12th 13th 16th Devops videos.
Please check and confirm on the same.

Below is the error msg:

Please Try Again
We apologize, but an error has occurred while processing your request. Please try again. For support, please contact Global Customer Support.

**Comment by arunkumar127** [comment]
@Aamukta
Please contact Quality Thought Admin for this issue.
Mail your issue to qtdevops@gmail.com or  contact them. (Check www.qualitythought.in for contact details)
Please close this issue.

Regards 
Arun Kumar

**Comment by revathi-muthana123** [comment]
@Aamukta 

Pls contact admin@sathish : 9963799240 & 9963486280
Note: Please don't share these issues in this portal. This is only for technical issues.

**Comment by Aamukta** [comment]
It is accessible now. Thanku.
