### ISSUE TITLE
Jenkins(Master-slave error) for windows machine

### ISSUE THREAD

**Issue by sunnydevops** [QT-DevOps/DevOpsIssues#23]
When i am trying to configure windows machine as a slave getting error, and my firewall and antivirus is Disable  
![error](https://user-images.githubusercontent.com/31772526/40727496-9de39492-6445-11e8-908e-0e5b52b532a2.png)

**Comment by vijaybhaskarreddyy** [comment]
Have you enable  jnl ports on global tool security in manage jenkins? and open all ports in jenkins  server secrity group.

**Comment by shaikkhajaibrahim** [comment]
Please refer https://github.com/QT-DevOps/DevOpsIssues/issues/16

**Comment by shaikkhajaibrahim** [comment]
Is the issue resolved?

**Comment by sunnydevops** [comment]
Yes

Thank you
