### ISSUE TITLE
Docker not starting

### ISSUE THREAD

**Issue by kmraok** [QT-DevOps/DevOpsIssues#230]
OS : Win10 Professional,installed docker with Choco, its not runnning.I installed docker tools for windows also.,attaching screenshot. 
![image](https://user-images.githubusercontent.com/43443111/47257356-20864780-d4aa-11e8-9252-05d4b312876c.png)

**Comment by arunkumar127** [comment]
@kmraok
Go through this link for solution.
https://success.docker.com/article/docker-for-windows-fails-with-a-daemon-not-running-message
Let me know whether it is working or not.

Regards
Arun Kumar

**Comment by kmraok** [comment]
Dear Arun..Thanks for your support. I tried that,but its not showing in
services.msc.plz chk the screens below.
[image: image.png]
[image: image.png]
*Mallikharjuna **Rao. Koppolu*
*9908636373*

*kmraok@gmail.com <kmraok@gmail.com>*
*mallikharjun.koppolu@srijaytech.com <mallikharjun.koppolu@srijaytech.com>*
*www.srijaytech.com <http://www.srijaytech.com>*

**Comment by arunkumar127** [comment]
@kmraok 
Screenshot is not uploaded. Upload again.
Have you checked 2nd option?
Run following commands in PowerShell as Administrator
**Net stop com.docker.service
Net start com.docker.service**

Regards
Arun Kumar

**Comment by kmraok** [comment]
[image: image.png]
[image: image.png]
*Mallikharjuna **Rao. Koppolu*
*9908636373*

*kmraok@gmail.com <kmraok@gmail.com>*
*mallikharjun.koppolu@srijaytech.com <mallikharjun.koppolu@srijaytech.com>*
*www.srijaytech.com <http://www.srijaytech.com>*

**Comment by kmraok** [comment]
![image](https://user-images.githubusercontent.com/43443111/47263877-1f93fb00-d528-11e8-9cb8-859e9596e68d.png)

![image](https://user-images.githubusercontent.com/43443111/47263879-2c185380-d528-11e8-8865-64c7c2a4a31a.png)

**Comment by arunkumar127** [comment]
@kmraok 
I'm not sure why it's not working for you.
Please verify these checks
- Virtualization enabled in BIOS
- OS should be 64 Bit Architecture

**Comment by kmraok** [comment]
Yes,I have enabled Virtulation ,AND os IS wIN10 64 bBit.
![image](https://user-images.githubusercontent.com/43443111/47269898-914c6300-d581-11e8-9918-497c37f3808f.png)

**Comment by raviops100** [comment]
Hi 
While installing docker in windows environment:
1. you need to install docker toolbox for windows
2. once if you install successfully you need to get one background service call docker for "windows service"  the screenshot you have shared i am not able see the service above
3. i suspect while installation something missed
Thanks
Ravi

**Comment by shaikkhajaibrahim** [comment]
IS it resolved. try running powershell as admin

**Comment by kmraok** [comment]
hi..its working.thanks for your support
