### ISSUE TITLE
daily getting bill on ec2 even im stopping it

### ISSUE THREAD

**Issue by vinay4001** [QT-DevOps/DevOpsIssues#231]
![capture](https://user-images.githubusercontent.com/44084389/47263306-bce93200-d51c-11e8-9345-a5bcfa283169.PNG)

**Comment by raviops100** [comment]
Hi Vijay 
Ec2 instancees charges only while they are running but EBS volumes attached continue to accure charges even instance stopped 
Delete EBS volumes and EBS snapshots you don't need 
2. Delete elastic IP's you have created 
Thanks
Ravi

**Comment by revathi-muthana123** [comment]
@vinay4001 
if you want to know billing details: 
=> My billing dashboard --> bills 
=>click on " Elastic Cloud computing" you can find region wise for which service you have been charged.
![image](https://user-images.githubusercontent.com/39338792/47266232-4286d500-d551-11e8-8e5d-638cb2a328f4.png)



Thank you
Revathi

**Comment by vinay4001** [comment]
how to stop getting bill
![capture1](https://user-images.githubusercontent.com/44084389/47267075-64398980-d55c-11e8-9a29-109aec362c04.PNG)

**Comment by revathi-muthana123** [comment]
Pls click on " Elastic Compute Cloud",  share that screen shot,  check  for which service u are getting Bill, stop/delete those services. Then only u can able to stop billing.

**Comment by vinay4001** [comment]
![screenshot_20181021-200816](https://user-images.githubusercontent.com/44084389/47268341-2f81fe00-d56d-11e8-8bfb-7ac6050bbbca.png)

**Comment by revathi-muthana123** [comment]
Do u have idea about "VPC"?
In " Mumbai" region,  u have created "NAT" gateway with "Elastic ip" that's y u r getting Bill. 
Pls delete those.Bill will be stop.

**Comment by vinay4001** [comment]
I have deleted every thing

**Comment by vinay4001** [comment]
I mean i have deleted every thing including vpc

**Comment by revathi-muthana123** [comment]
1. Go to "Services" --> select "VPC" 
2. Go to "NAT" gateway --> actions --> delete NAT gateway.
After deleting
3. Go to "Elastic IP" --> actions --> "release address"

**Comment by vinay4001** [comment]
I have deleted VPC with that every thing deleted

**Comment by revathi-muthana123** [comment]
NAT gateway should not be delete while deleting vpc

**Comment by vinay4001** [comment]
Then what to do now

**Comment by revathi-muthana123** [comment]
Do u have "Team viewer"?  Can u Pls connect?

**Comment by vinay4001** [comment]
No

**Comment by revathi-muthana123** [comment]
U r Class room / online?
If u r classroom I will verify tomorrow. 
If it is online,  Pls download " Team viewer".

**Comment by revathi-muthana123** [comment]
Verify EBS volumes & snapshots. These can be effect in billing.

**Comment by vinay4001** [comment]
how to use ec2 without getting bills.. i mean what to close after using

**Comment by revathi-muthana123** [comment]
Contact Customer Support:
-----------------------------
![image](https://user-images.githubusercontent.com/39338792/47289481-8f81ae80-d618-11e8-8835-d66cc69aac8f.png)

=> Raise a ticket to Amazon, regarding your issue including screenshots.
=> you will get reply to your mail.

For reference:
--------------
https://docs.aws.amazon.com/awssupport/latest/user/getting-started.html
