### ISSUE TITLE
How to come out of container without killing it. 

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#232]
How to come out of container without killing it.  If we do cntrl+c, it kills. what is that command?

**Comment by arunkumar127** [comment]
@Aamukta 
To come out of container without killing, use **Ctrl+p+q**
### Refer
**https://stackoverflow.com/questions/19688314/how-do-you-attach-and-detach-from-dockers-process**

Regards
Arun Kumar

**Comment by raviops100** [comment]
Hi  
Try to run docker in exec mode
Docker exec -it  name of image /bin/bash
After this if don't want to kill the container 
Control+pq 
Thanks 
Ravi

**Comment by Aamukta** [comment]
Thankyou Ravi & Arun.
