### ISSUE TITLE
im not able to connect to internet though cli

### ISSUE THREAD

**Issue by vinay4001** [QT-DevOps/DevOpsIssues#233]
![oi](https://user-images.githubusercontent.com/44084389/47291936-23f10e80-d623-11e8-9bde-7c1c5394c400.PNG)

**Comment by arunkumar127** [comment]
@Vinay
Recheck your EC2 Instance IP address. 192.168.1.101 doesn't seem to be valid EC2 Instance IP.
Post screenshot of your EC2 IP.

Regards
Arun Kumar

**Comment by revathi-muthana123** [comment]
@vinay4001 
1. Open 22 port in security group.
2. If you launched from default VPC, make sure " Internet Gateway" connected to default route table. (Custome VPC connect internet gateway with public route table which associated with public subnet)
3. Verify NACL rules, which allow all traffic
4. Login from where your ".pem" file (private key existed).

Thanks
Revathi

**Comment by raviops100** [comment]
Hi is this issue resolved ???

**Comment by shaikkhajaibrahim** [comment]
Search vpc flow logs & find the reason for REJECT Logs
