### ISSUE TITLE
Issue with kubernetes node joining

### ISSUE THREAD

**Issue by crsreddy1447** [QT-DevOps/DevOpsIssues#237]

**Comment by crsreddy1447** [comment]
I am unable to join the nodes with master.
![kubernetes](https://user-images.githubusercontent.com/34264332/47381696-4156d300-d71e-11e8-9887-173f0d2276b4.JPG)

**Comment by raviops100** [comment]
Hi CRSREDDY,
Can you please follow below steps 

1.  you have to execute below commands only on MASTER
=================================================
root user:
=========
apt-get update

kubeadm init

you need to see message like master has initialized succesfully


below commands
=============== 
run on ubuntu user(or) created user not a root user

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

  Once you execute above command you will get kubeadm join command save this command
  
  go to node machine execute the kubeadm join command
  
  u need to get node join complete
  
  after this u need to login to master  
==============================================
kubectl get all nodes

**Comment by crsreddy1447** [comment]
My master is running but nodes are unable to join

**Comment by revathi-muthana123** [comment]
Which Environment, is it cloud or virtual machine?

**Comment by crsreddy1447** [comment]
google cloud.

**Comment by raviops100** [comment]
Hi is this issue resolved ???

**Comment by shaikkhajaibrahim** [comment]
See whether required ports are open for communication or not
