### ISSUE TITLE
Not starting pod network add-on

### ISSUE THREAD

**Issue by vinaymamidala** [QT-DevOps/DevOpsIssues#238]
Hi,
I have created kubernete cluster and installing pod network is weave net
when i execute kubectl get pods --all-namespaces. it shows  CrashLoopBackOff
{code}
vinay@vinay-kubemaster:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                       READY   STATUS              RESTARTS   AGE
kube-system   coredns-576cbf47c7-2zcjc                   0/1     ContainerCreating   0          57m
kube-system   coredns-576cbf47c7-cbhj9                   0/1     ContainerCreating   0          57m
kube-system   etcd-vinay-kubemaster                      1/1     Running             0          52m
kube-system   kube-apiserver-vinay-kubemaster            1/1     Running             0          52m
kube-system   kube-controller-manager-vinay-kubemaster   1/1     Running             0          52m
kube-system   kube-proxy-lplbw                           1/1     Running             0          51m
kube-system   kube-proxy-mfxwm                           1/1     Running             0          52m
kube-system   kube-proxy-ttwwl                           1/1     Running             0          57m
kube-system   kube-scheduler-vinay-kubemaster            1/1     Running             0          52m
**kube-system   weave-net-cvdkn                            1/2     CrashLoopBackOff    14         47m
kube-system   weave-net-f54g4                            1/2     CrashLoopBackOff    14         47m
kube-system   weave-net-kw77m                            1/2     CrashLoopBackOff    14         47m**
{code}

**Comment by raviops100** [comment]
Hi Vinay,

while Installing a pod network add-on:

basically weavenet is networking component for KUBERNATES

please excute below command 

kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

after this try to excute  kubectl get pods --all-namespaces

Thanks
Ravi
