### ISSUE TITLE
not able to mount to folder

### ISSUE THREAD

**Issue by vinay4001** [QT-DevOps/DevOpsIssues#239]
![1](https://user-images.githubusercontent.com/44084389/47480306-9f360880-d84d-11e8-8c9c-de8cb5584920.PNG)

**Comment by revathi-muthana123** [comment]
Hi,
Pls go to current directory --> cd /home/images/myvolume
Then execute : sudo mount /dev/xvdf .

Thanks & regards
Revathi

**Comment by vinay4001** [comment]
we should create that device..?

**Comment by revathi-muthana123** [comment]
Can u provide more info what u have done?

**Comment by vinay4001** [comment]
I have created volume and attaches it to instance
Next I did sudo lsblk command and found device name
After that formated the system by mods extra /dev/**/
While mount it is showing file not exists

**Comment by vinay4001** [comment]
Mkfs ext4 /dev/**/

**Comment by revathi-muthana123** [comment]
Have you created mount point  (directory) which is "myvolume"
=> If not created , first create it.
sudo mkdir /newvolume
=> Go to current directory
=> Execute the command
sudo mount /dev/xvdf /newvolume/

reference:
-----------
https://devopscube.com/mount-ebs-volume-ec2-instance/

**Comment by raviops100** [comment]
Hi is this issue resolved ???

**Comment by vinay4001** [comment]
Noo madam...

**Comment by raviops100** [comment]
Hi Vinay,

Please Try below commads:

Mounting: is a procedure for attaching directory to filesystem

1. df -h ( prints out details about  mounted file systems)

2.  fdisk -l(to check the partitions on a disk)

/dev/xvdf ---- is a filesytem

4.  mkfs -t ext4 /dev/xvdf === to format with file system

5. mkdir /my-new-dir

6. mount /dev/xvdf /my-new-dir
Thanks
Ravi

**Comment by raviops100** [comment]
Is this solved??

**Comment by vinay4001** [comment]
Yeah it is solved
