### ISSUE TITLE
Artifactory service error

### ISSUE THREAD

**Issue by SarfrazPNQ** [QT-DevOps/DevOpsIssues#24]
After installation of jFrog am unable to start service. Below is the logs.

root@ip-172-31-1-174:~# systemctl status artifactory.service
● artifactory.service - Setup Systemd script for Artifactory in Tomcat Servlet Engine
   Loaded: loaded (/lib/systemd/system/artifactory.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-05-30 15:47:41 UTC; 4s ago
  Process: 7459 ExecStart=/opt/jfrog/artifactory/bin/artifactoryManage.sh start (code=exited, status=1/FAILURE)

May 30 15:47:41 ip-172-31-1-174 systemd[1]: Failed to start Setup Systemd script for Artifactory in Tomcat Servlet Engine.
May 30 15:47:41 ip-172-31-1-174 systemd[1]: artifactory.service: Unit entered failed state.
May 30 15:47:41 ip-172-31-1-174 systemd[1]: artifactory.service: Failed with result 'exit-code'.
root@ip-172-31-1-174:~#

Any configuration am missing ? Please help!

**Comment by vijaybhaskarreddyy** [comment]
For artifactory server to rnn it required at  latest 4GB ram machine.

**Comment by SarfrazPNQ** [comment]
I've used same config as commented.

**Comment by vijaybhaskarreddyy** [comment]
run # ### expor  JAVA_OPTS="-Xms512m -Xmx1024m" ## the command in your artifactory server then try to start again.

**Comment by shaikkhajaibrahim** [comment]
Can you share the logs from artifactory as mentioned in https://www.jfrog.com/confluence/display/RTF/Artifactory+Log+Files

**Comment by SarfrazPNQ** [comment]
It worked for me. I followed below steps:

 $ sudo apt-get update
 $ sudo apt-get -y upgrade

Installing Oracle JDK 8
$ sudo add-apt-repository ppa:webupd8team/java
$ sudo apt-get update
$ sudo apt-get -y install oracle-java8-installer

$ java -version
    java version "1.8.0_91"
    Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

Set JAVA HOME with below commands
$ vi /etc/environment
JAVA_HOME=/usr/lib/jvm/java-8-oracle
export JAVA_HOME

Install JFrog Artifactory

$ wget -c -O- "https://bintray.com/user/downloadSubjectPublicKey?username=jfrog" | sudo apt-key add -
$ echo "deb https://bintray.com/artifact/download/jfrog/artifactory-debs trusty main" | sudo tee -a /etc/apt/sources.list.d/artifactory-oss.list

sudo apt-get update
sudo apt-get -y install jfrog-artifactory-oss

systemctl start artifactory.service
systemctl status artifactory.service
