### ISSUE TITLE
unable to see application in hostmachine

### ISSUE THREAD

**Issue by saikiranjayanthi** [QT-DevOps/DevOpsIssues#240]
Hi 
I have created a Docker file of openmrs with COPY command.
I have succesfully created a build and done a docker run command
The issue i am facing here i am not able to see my application on outside.
I have open a all port of tcp
![tcp port](https://user-images.githubusercontent.com/43769701/47556361-c105bd00-d92b-11e8-9d80-9c75ecae3ac6.PNG)

I hope i have given below command wrong in tab.
https:13.233.146.80(machine ip address)

*******DOCKER file************
FROM tomcat:8.0
RUN apt-get update
COPY openmrs-standalone.war /usr/local/tomcat/webapps/openmrs.war
EXPOSE 8080
CMD ["catalina.sh", "run"]

**Comment by qtsathish** [comment]
Hi,
Please access with port number :
http://<public ip> :8080
To my knowledge  from "https" might not be access

It's better to share output after building image & after creating container.
Run container with port number 8080                       

Note: pls make sure it is working manually or not. Then try to build with dockerfile.

Thanks 
Revathi

**Comment by revathi-muthana123** [comment]
Hi,
Please access with port number :
http://publicip :8080
To my knowledge from "https" might not be access

It's better to share output after building image & after creating container.
Run container with port number 8080

Note: pls make sure it is working manually or not. Then try to build with dockerfile.

Thanks
Revathi

**Comment by revathi-muthana123** [comment]
From where you are copying openmrs.war file.
###
FROM tomcat:8.0
RUN apt-get update
RUN cd /usr/local/tomcat/webapps && wget -O openmrs.war 
         http://sourceforge.net/projects/openmrs/files/releases/OpenMRS_1.9.3/openmrs.war/download
EXPOSE 8080
CMD ["catalina.sh", "run"]
###
it is working

**Comment by saikiranjayanthi** [comment]
Hi Revathi
 i have dowloaded the war file in my windows desktop and i have copy the war file to aws through scp command
**location**
https://downloads.sourceforge.net/project/openmrs/releases/OpenMRS_Platform_2.0.4.1/openmrs.war 

scp -i Docker123.pem referenceapplication-standalone-2.8.0/tomcat/webapps/openmrs-standalone.war ubuntu@ec2-13-233-146-80.ap-south-1.compute.amazonaws.com:/home/ubuntu

**Comment by saikiranjayanthi** [comment]
Hi Revathi
whether this docker file working for you
FROM tomcat:8.0
RUN apt-get update
RUN cd /usr/local/tomcat/webapps && wget -O openmrs.war
http://sourceforge.net/projects/openmrs/files/releases/OpenMRS_1.9.3/openmrs.war/download
EXPOSE 8080
CMD ["catalina.sh", "run"]

Im getting a error at build time
Error response from daemon: Dockerfile parse error line 4: unknown instruction: HTTPS://SOURCEFORGE.NET/PROJECTS/OPENMRS/FILES/RELEASES/OPENMRS_1.9.3/OPENMRS.WAR/DOWNLOAD

**Comment by revathi-muthana123** [comment]
combine these two lines: it is a single command:
----------------------------------------------------
wget -O openmrs.war
http://sourceforge.net/projects/openmrs/files/releases/OpenMRS_1.9.3/openmrs.war/download
