### ISSUE TITLE
command to move the file from  parent image to container

### ISSUE THREAD

**Issue by saikiranjayanthi** [QT-DevOps/DevOpsIssues#242]
Hi 
Is it possible to move the file from the parent image to the docker container through scp or other method
if any idea please suggest me

**Comment by raviops100** [comment]
As per my undersatnding 
file from the parent image to the docker container is not possible

other concept is like you copy localfile(or) direcoty from your hostmachine to DockerImage

by using DockerInstuction Called COPY COMMAND

**Comment by shaikkhajaibrahim** [comment]
If the file is in parent image, it should be already part of your image
________________________________
