### ISSUE TITLE
How to access Jenkins installed in an Ubuntu VM in local system?

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#244]
Hi,

I have installed Docker and Jenkins in an Ubuntu 16 VM which was set up using VMWare Player on my system. I tried googling a lot but not able to find a method to access Jenkins in this set up. I had tried this setup on a t2.micro but that is not sufficient to run both. So trying it in my own system which as 12 Gb RAM. 
http://localhost:8080/ does not yield anything.

Kindly help
Regards
Ramesh

**Comment by arunkumar127** [comment]
@Ramesh
You can access using VM IP address.
$ **ifconfig**
http://**VMIP**:8080/

Regards
Arun Kumar

**Comment by rameshm78** [comment]
Thanks a lot Arun.
I took the inet addr from ens33 section, which was given by the ifconfig command and it worked.

I got 3 sections - docker0, ens33 and lo when I executed "ifconfig". Can you please tell me what the three sections are for? Or maybe given links of some documentation where it is explained?
![image](https://user-images.githubusercontent.com/40449948/47629797-4cb55e80-db63-11e8-8cd7-6ca857f72e6d.png)

**Comment by arunkumar127** [comment]
@rameshm78 
docker0 is default network we get when we install Docker. Inspect default bridge network.
lo represents localhost (127.0.0.1)
Other one depends on which type of network we choose while we are bringing up our VM (NAT/Bridge/Host-Only)
### Refer
https://kb.novaordis.com/index.php/VirtualBox_Networking_Concepts

Regards
Arun Kumar

**Comment by arunkumar127** [comment]
This video has simple explanation regarding VM Networking concept. 
https://www.youtube.com/watch?v=cDF4X7RmV4Q

**Comment by rameshm78** [comment]
Thanks Arun.
