### ISSUE TITLE
regarding chef kitchen converge

### ISSUE THREAD

**Issue by satyamuralidhar** [QT-DevOps/DevOpsIssues#246]
-----> Starting Kitchen (v1.23.2)
-----> Creating <default-ubuntu-1404>...
       Bringing machine 'default' up with 'virtualbox' provider...
       Failed to locate the powershell executable on the available PATH. Please
       ensure powershell is installed and available on the local PATH, then
       run the command again.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
STDERR: Failed to locate the powershell executable on the available PATH. Please
ensure powershell is installed and available on the local PATH, then
run the command again.
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1] on default-ubuntu-1404
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by arunkumar127** [comment]
@immurai5
Run below commands in PowerShell (Run as admin) and share result screenshot.
**powershell**
**get-host**

**Comment by arunkumar127** [comment]
@immurali5 
Run below commands in Powershell (Run as admin) & share result screenshot.
**powershell
get-host**

Verify whether PowerShell Path is defined or not in Environmental Variables.
**`%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\`**

![1](https://user-images.githubusercontent.com/40756184/47672702-a310b480-dbd8-11e8-9f4f-8017e081fa34.jpg)

Regards
Arun Kumar
