### ISSUE TITLE
regarding ansible

### ISSUE THREAD

**Issue by satyamuralidhar** [QT-DevOps/DevOpsIssues#248]
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via
squash_actions is deprecated. Instead of using a loop to supply multiple items and
specifying `name: {{ item }}`, please use `name: [u'php', u'libapache2-mod-php', u
'php-mcrypt', u'php-mysql']` and remove the loop. This feature will be removed in
version 2.11. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cf

**Comment by shaikkhajaibrahim** [comment]
Share your playbook
________________________________

**Comment by satyamuralidhar** [comment]
---
- hosts: all
  become: yes
  tasks:
  - name: installing apache2
    apt:
      name: apache2
      update_cache: yes
      state: present
    notify:
    - restart apache
    when: ansible_os_family == "Debian"
  - name: install httpd
    yum:
      name: httpd
      state: present
    notify:
    - restart httpd    
    when: ansible_os_family == "Redhat"    
  
  - name: installing php
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - php
    - libapache2-mod-php
    - php-mcrypt 
    - php-mysql  
    notify:
    - restart apache 
    when: ansible_os_family == "Debian"
  - name: install php
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - php
    - php-mysql
    notify:
    - restart httpd
    when: ansible_os_family == "Redhat"     
  handlers:
  - name: restart apache 
    service:
      name: apache2
      state: restarted  
    when: ansible_os_family == "Debian"
  - name: restart httpd
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == "Redhat"

**Comment by shaikkhajaibrahim** [comment]
alignment is confusing . Please upload file directly
________________________________

**Comment by satyamuralidhar** [comment]
[lamp.txt](https://github.com/QT-DevOps/DevOpsIssues/files/2529651/lamp.txt)

**Comment by shaikkhajaibrahim** [comment]
I discovered that as per the porting guide you can make a list of the packages as a separate variable and then pass that variable to the apt module, like so:

vars:
  packages:
    - ubuntu-mate-core    
    - ubuntu-mate-desktop     
    - xrdp

tasks:
  - name: "Install dependencies"
    apt:
      pkg: "{{ packages }}"
      state: present

Since its a warning as of now you can ignore. It is going to impact in the future

**Comment by satyamuralidhar** [comment]
thanks sir as per ur teaching lot of things learned in devops  .
