### ISSUE TITLE
Unable to create files using ansible user in centos

### ISSUE THREAD

**Issue by kmahesh121785** [QT-DevOps/DevOpsIssues#249]
Unable to create files using ansible user in centos.

error: Permission denied.

ssh -i "Ansible.pem" centos@ec2-18-222-135-183.us-east-2.compute.amazonam
Last login: Tue Oct 30 07:08:47 2018 from 124.123.86.90
[centos@ip-172-31-17-8 ~]$ su ansible
Password:
[ansible@ip-172-31-17-8 centos]$ touch 1
touch: cannot touch ‘1’: Permission denied
[ansible@ip-172-31-17-8 centos]$

**Comment by raviops100** [comment]
Please give sudo permission to ansible user
Visudo file

**Comment by kmahesh121785** [comment]
Under which section exactly i need to add
The COMMANDS section may have other options added to it.
##
## Allow root to run any commands anywhere
root    ALL=(ALL)       ALL

## Allows members of the 'sys' group to run networking, software,
## service management apps and more.
# %sys ALL = NETWORKING, SOFTWARE, SERVICES, STORAGE, DELEGATING,
PROCESSES, LOCATE, DRIVERS

## Allows people in group wheel to run all commands
%wheel  ALL=(ALL)       ALL

## Same thing without a password
 ansible        ALL=(ALL)       NOPASSWD: ALL

## Allows members of the users group to mount and unmount the
## cdrom as root
# %users  ALL=/sbin/mount /mnt/cdrom, /sbin/umount /mnt/cdrom

## Allows members of the users group to shutdown this system
# %users  localhost=/sbin/shutdown -h now

## Read drop-in files from /etc/sudoers.d (the # here does not mean a
comment)
#includedir /etc/sudoers.d

**Comment by kmahesh121785** [comment]
Under which section exactly i need to add
The COMMANDS section may have other options added to it.
##
## Allow root to run any commands anywhere
root    ALL=(ALL)       ALL

## Allows members of the 'sys' group to run networking, software,
## service management apps and more.
# %sys ALL = NETWORKING, SOFTWARE, SERVICES, STORAGE, DELEGATING, PROCESSES, LOCATE, DRIVERS

## Allows people in group wheel to run all commands
%wheel  ALL=(ALL)       ALL

## Same thing without a password
 ansible        ALL=(ALL)       NOPASSWD: ALL

## Allows members of the users group to mount and unmount the
## cdrom as root
# %users  ALL=/sbin/mount /mnt/cdrom, /sbin/umount /mnt/cdrom

## Allows members of the users group to shutdown this system
# %users  localhost=/sbin/shutdown -h now

## Read drop-in files from /etc/sudoers.d (the # here does not mean a comment)
#includedir /etc/sudoers.d


On Tue, Oct 30, 2018 at 1:37 PM raviops100 <notifications@github.com> wrote:
Please give sudo permission to ansible user
Visudo file

**Comment by kmahesh121785** [comment]
I dont see sudo option to give

**Comment by arunkumar127** [comment]
Run below command as root user.
$ **usermod -aG wheel ansible**
Now try to run touch command. Let me know whether it worked or not.

Regards
Arun Kumar

**Comment by kmahesh121785** [comment]
Still i cant


$ ssh -i "Ansible.pem" centos@ec2-18-222-135-183.us-east-2.compute.amazonam
Last login: Tue Oct 30 08:15:12 2018 from 124.123.86.90
[centos@ip-172-31-17-8 ~]$ sudo -i
[root@ip-172-31-17-8 ~]# usermod -aG wheel ansible
[root@ip-172-31-17-8 ~]# su ansible
[ansible@ip-172-31-17-8 root]$ touch 1
touch: cannot touch ‘1’: Permission denied
[ansible@ip-172-31-17-8 root]$ usermod -aG wheel ansible
bash: /sbin/usermod: Permission denied
[ansible@ip-172-31-17-8 root]$

**Comment by shaikkhajaibrahim** [comment]
Are you not supposed to add sudo to your commands if you are running as ansible?
________________________________

**Comment by kmahesh121785** [comment]
Got it ....

**Comment by kmahesh121785** [comment]
Thank you
