### ISSUE TITLE
Error while configuring artifactory server

### ISSUE THREAD

**Issue by venkatesh263** [QT-DevOps/DevOpsIssues#25]
Hi Sir,

i am getting below error while starting the service in artifactory server. Please hep me to fix this issue.

root@ip-172-31-16-195:/home/ubuntu# systemctl status artifactory.service
● artifactory.service - Setup Systemd script for Artifactory in Tomcat Servlet Engine
   Loaded: loaded (/lib/systemd/system/artifactory.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: resources) since Thu 2018-05-31 03:15:42 UTC; 2s ago
  Process: 4901 ExecStart=/opt/jfrog/artifactory/bin/artifactoryManage.sh start (code=exited, status=0/SUCCESS)

May 31 03:15:42 ip-172-31-16-195 systemd[1]: artifactory.service: PID file /var/opt/jfrog/run/artifactory.pid not readable (yet?) after start: No such file or directory
May 31 03:15:42 ip-172-31-16-195 systemd[1]: Failed to start Setup Systemd script for Artifactory in Tomcat Servlet Engine.
May 31 03:15:42 ip-172-31-16-195 systemd[1]: artifactory.service: Unit entered failed state.
May 31 03:15:42 ip-172-31-16-195 systemd[1]: artifactory.service: Failed with result 'resources'.
root@ip-172-31-16-195:/home/ubuntu#

**Comment by shaikkhajaibrahim** [comment]
Can you share the logs from artifactory as mentioned in https://www.jfrog.com/confluence/display/RTF/Artifactory+Log+Files

**Comment by venkatesh263** [comment]
i got the solution and fixed .. thanks for the support.
