### ISSUE TITLE
AWS ECR repository

### ISSUE THREAD

**Issue by raja139** [QT-DevOps/DevOpsIssues#250]
Hi Team,,

After I pushed  the images to the repository its showing any extra entry in the docker image list , does this mean  i did anything wrong or  is it normal behavior ?
Before push:
===========
ubuntu@ip-172-31-39-40:~/images$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
python              latest              2cc378c061f7        5 days ago          923MB
ubuntu              latest              ea4c82dcd15a        11 days ago         85.8MB
python              2.7                 3c43a5d4034a        2 weeks ago         908MB

ubuntu@ip-172-31-39-40:~/images$ docker build -t git .
Sending build context to Docker daemon  3.584kB

ubuntu@ip-172-31-39-40:~/images$ docker tag git 979528035674.dkr.ecr.us-east-2.amazonaws.com/gan_repo:ganeshgit
ubuntu@ip-172-31-39-40:~/images$ docker push 979528035674.dkr.ecr.us-east-2.amazonaws.com/gan_repo
The push refers to repository [979528035674.dkr.ecr.us-east-2.amazonaws.com/gan_repo]
60b06db431cd: Pushed
76c033092e10: Layer already exists
2146d867acf3: Layer already exists
ae1f631f14b7: Layer already exists
102645f1cf72: Layer already exists
ganeshgit: digest: sha256:836a20fe96a8735e06591c86ebc153c3b364f7dbc6a5cc6de26b2157ba7b29ad size: 1362

After Push:
===========
ubuntu@ip-172-31-39-40:~/images$ docker images
REPOSITORY                                              TAG                 IMAGE ID            CREATED             SIZE
979528035674.dkr.ecr.us-east-2.amazonaws.com/gan_repo   ganeshgit           b9beeeec9a50        5 minutes ago       203MB
git                                                     latest              b9beeeec9a50        5 minutes ago       203MB
python                                                  latest              2cc378c061f7        5 days ago          923MB
ubuntu                                                  latest              ea4c82dcd15a        11 days ago         85.8MB
python                                                  2.7                 3c43a5d4034a        2 weeks ago         908MB

can you please correct me if im wrong.

Regards,
Raja

**Comment by shaikkhajaibrahim** [comment]
Both
979528035674.dkr.ecr.us-east-2.amazonaws.com/gan_repo ganeshgit b9beeeec9a50 5 minutes ago 203MB
git latest b9beeeec9a50 5 minutes ago 203MB
are same images with different names
________________________________

**Comment by raja139** [comment]
Sir after i pushed the image to the repository then it has visible like that before that it was not there. 

My PUSH Command:
ubuntu@ip-172-31-39-40:~/images$ docker tag git 979528035674.dkr.ecr.us-east-2.amazonaws.com/gan_repo:ganeshgit
ubuntu@ip-172-31-39-40:~/images$ docker push 979528035674.dkr.ecr.us-east-2.amazonaws.com/gan_repo

**Comment by shaikkhajaibrahim** [comment]
Your image has been tagged to new name
________________________________

**Comment by raja139** [comment]
sir its bit confusing for me.Tag name we can give any thing right .Do we need to give same name as image name ?
That name will be visible at ECR console but in docker image its displayed.
Even if i delete my image at physically , Can i get my image from repository.

**Comment by BRAHMAREDDYV** [comment]
Hi Raja,


This is ur tag command

     docker tag git 979528035674.dkr.ecr.us-east-2.amazonaws.com/gan_repo:ganeshgit

This is ir push command

    docker push 979528035674.dkr.ecr.us-east-2.amazonaws.com/gan_repo

Here u must specify ur full tag, u missed ganeshgit in ur tag 

Check this command 

    docker push 979528035674.dkr.ecr.us-east-2.amazonaws.com/gan_repo:ganeshgit



thq 
Brahmareddy

**Comment by shaikkhajaibrahim** [comment]
yes you can get if it is displayed in ECR
