### ISSUE TITLE
NodeJS inatallationerror

### ISSUE THREAD

**Issue by kmahesh121785** [QT-DevOps/DevOpsIssues#251]
TASK [excute shell script downloaded] **************************************************************************************************************************************
 [WARNING]: Consider using 'become', 'become_method', and 'become_user' rather than running sudo

fatal: [ip-172-31-21-1.us-east-2.compute.internal]: FAILED! => {"changed": true, "cmd": ["sudo", "bash", "/home/ansible/nodesetup/nodesource_setup.sh"], "delta": "0:00:00.008359", "end": "2018-10-30 15:41:48.460441", "msg": "non-zero return code", "rc": 127, "start": "2018-10-30 15:41:48.452082", "stderr": "bash: /home/ansible/nodesetup/nodesource_setup.sh: No such file or directory", "stderr_lines": ["bash: /home/ansible/nodesetup/nodesource_setup.sh: No such file or directory"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/home/ansible/Nodejs/node.retry

PLAY RECAP *****************************************************************************************************************************************************************
ip-172-31-17-125.us-east-2.compute.internal : ok=2    changed=1    unreachable=0    failed=0
ip-172-31-21-1.us-east-2.compute.internal : ok=5    changed=2    unreachable=0    failed=1
===============================================================

But file available with below screenshot

ansible@ip-172-31-43-101:~$ curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
ansible@ip-172-31-43-101:~$ ls
Nodejs  apache.yml  hosts  nginx.retry  nginx.yaml  nginx.yml  nodesource_setup.sh  playbooks
ansible@ip-172-31-43-101:~$ cd Nodejs/
ansible@ip-172-31-43-101:~/Nodejs$ ls
README.md  inventory  node.retry  node.yml
ansible@ip-172-31-43-101:~/Nodejs$ ansible-playbook -i inventory node.yml

**Comment by arunkumar127** [comment]
@kmahesh121785
Upload your complete playbook. (zip)

**Comment by kmahesh121785** [comment]
Node.yml

---
- hosts: all
  become: yes
  tasks:
   - name: update packing
     apt:
       update_cache: yes


 # node JS specific setting (url :https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04)     
- hosts: app
  become: yes
  vars:
    folderpath: /home/ansible/nodesetup
  tasks:
    - name: creating a directory
      file:
        path: "{{ folderpath }}"
        state: directory
        mode: 0755
    - name: Download node js on ubuntu
      command: "curl -sL https://deb.nodesource.com/setup_8.x -o {{ folderpath}} nodesource_setup.sh"
    - name: excute shell script downloaded
      command: "sudo bash {{folderpath}}/nodesource_setup.sh"
    - name: Installing Nodejs
      apt:
        name: nodejs
        state: present
  ========================================================
Inventory

[web]
ip-172-31-17-125.us-east-2.compute.internal

[app]
ip-172-31-21-1.us-east-2.compute.internal

**Comment by arunkumar127** [comment]
It worked fine for me. NodeJS v8.12.0 installed

YML file
![1](https://user-images.githubusercontent.com/40756184/47767303-042fa980-dcf9-11e8-82a2-6a6693ae8a2c.jpg)

ansible-playbook
![2](https://user-images.githubusercontent.com/40756184/47767429-98017580-dcf9-11e8-85b6-8ccb1659dc46.jpg)

NodeJS installed in app
![3](https://user-images.githubusercontent.com/40756184/47767453-ae0f3600-dcf9-11e8-85a6-870b5df83d71.jpg)

**Comment by kmahesh121785** [comment]
Am not able to see the nodesetup folder only in my account

**Comment by shaikkhajaibrahim** [comment]
Run in verbose mode & see whats happening
