### ISSUE TITLE
Docker Deployment

### ISSUE THREAD

**Issue by Sravan-jk** [QT-DevOps/DevOpsIssues#252]
Hello all,

please let me know the steps to do a docker deployment on jenkins slave after CI

**Comment by shaikkhajaibrahim** [comment]
Build Images Part
Install docker on jenkins slave.
Add jenkins user to docker group
    usermod -aG docker jenkins
execute docker build statements from jenkins invoke shell in build steps
push the image built into some repo.

Deployment Part
Login as user in deployment machine & execute docker run for docker deployments

If kubernetes deployment execute kubectl apply commands



________________________________

**Comment by revathi-muthana123** [comment]
@Sravan-jk 
Have you done?
