### ISSUE TITLE
copy war file to container

### ISSUE THREAD

**Issue by vdileepdevops** [QT-DevOps/DevOpsIssues#253]
hi
how can i copy my war file host machine to docker container

Thanks's
Dileep

**Comment by raviops100** [comment]
It is possible by using Docker instructions call ADD or COPY 
Example :
ADD game
oflife.war  /user/local/tomcat/webapps/gameoflife.war
thanks 
ravi

**Comment by arunkumar127** [comment]
@vdileepdevops
Do you mean to copy file into running container?

**Comment by revathi-muthana123** [comment]
Hi Dileep,
Yes, we can do
***
FROM tomcat:7.0
ADD https://downloads.sourceforge.net/project/openmrs/releases/OpenMRS_Platform_2.0.4.1/openmrs.war /usr/local/tomcat/webappas/openmrs.war
EXPOSE 8080
CMD ["catalina.sh", "run"]
***
Thanks & Regards
Revathi

**Comment by revathi-muthana123** [comment]
@vdileepdevops 
Is it cleared ?

**Comment by vdileepdevops** [comment]
thank you
