### ISSUE TITLE
K8s - Error - Yaml file validation Error

### ISSUE THREAD

**Issue by revathi-muthana123** [QT-DevOps/DevOpsIssues#254]
Hi all,
   I am trying to Deploy jenkins application by using k8s. I have written one yaml file which includes Service & Deployment. It is showing error. But while running individually it is working. 
Yaml File: Attachment
[Deployment.yml.txt](https://github.com/QT-DevOps/DevOpsIssues/files/2538620/Deployment.yml.txt)

Error:
***
 kubectl create -f jenkins.yml
error: error validating "jenkins.yml": error validating data: ValidationError(De                                                      ployment.spec.selector): unknown field "matchlabels" in io.k8s.apimachinery.pkg.                                                      apis.meta.v1.LabelSelector; if you choose to ignore these errors, turn validatio                                                      n off with --validate=false
***
What could be the reason? One of our student also facing same issue. Can anyone suggest.

Thanks & Regards
Revathi

**Comment by raviops100** [comment]
Hi 
In the yaml file you have written matchlabels you should write matchLabels
in matchlabels command L should be capital letter 
Thanks
Ravi

**Comment by revathi-muthana123** [comment]
Thanks for your early response ravi,  I 'll check with that.

**Comment by revathi-muthana123** [comment]
@ravi
Thank you, I am able to deploy now. But how can we access that. 
Correct me if i wrong, i tried to access with "External IP " of "Load Balancer". But it''s not accessing.

Thanks & Regards
Revathi
