### ISSUE TITLE
IAM policy issue

### ISSUE THREAD

**Issue by raja139** [QT-DevOps/DevOpsIssues#255]
Hi Team,

I have create a policy condition like below but when i try to launch instance itself its display like below:

###############################################
=> JSON file:
------------------------------------------------------------------
    "Statement": [
        {
            "Action": "ec2:*",
            "Effect": "Allow",
            "Resource": "*",
			"Condition" :{"StringEquals" : {"ec2:InstanceType": "t2.micro",
"ec2:ImageType":"ami-0782e9ee97725263d"}}
        },
#################################################

You are not authorized to describe Running Instances
You are not authorized to describe Dedicated Hosts
You are not authorized to describe Volumes
You are not authorized to describe Key Pairs
You are not authorized to describe Placement Groups |  
-- | --

Can you correct me.

Regards,
Raja

**Comment by revathi-muthana123** [comment]
Hi Raja,

What is your condition here? For which service are trying to give access?

Thanks & Regards
Revathi

**Comment by raja139** [comment]
Hi Revathi,

As per my policy, it should restrict other than "t2.micro"  ec2 instance  but in current situation when i click "EC2 dashboard" itself its display notification like below:

You are not authorized to describe Running Instances
You are not authorized to describe Dedicated Hosts
You are not authorized to describe Volumes
You are not authorized to describe Key Pairs

================================= 
  "Statement": [
        {
            "Action": "ec2:*",
            "Effect": "Allow",
            "Resource": "*",
			"Condition" :{"StringEquals" : {"ec2:InstanceType": "t2.micro"}}
        },
================================
Regrads,
raja

**Comment by ramesh44557** [comment]
EC2-full acces and restric only t2.micro:


{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "ec2:*",
            "Effect": "Allow",
            "Resource": "*",
            "Condition": {
                "StringNotEquals": {
                    "ec2:InstanceType": "t2.micro"
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": "elasticloadbalancing:*",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "cloudwatch:*",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "autoscaling:*",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "iam:CreateServiceLinkedRole",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "iam:AWSServiceName": [
                        "autoscaling.amazonaws.com",
                        "ec2scheduled.amazonaws.com",
                        "elasticloadbalancing.amazonaws.com",
                        "spot.amazonaws.com",
                        "spotfleet.amazonaws.com"
                    ]
                }
            }
        }
    ]
}

**Comment by raja139** [comment]
Thank you ramesh I will check and let you know.

Raja

**Comment by revathi-muthana123** [comment]
> Hi Team,
> 
> I have create a policy condition like below but when i try to launch instance itself its display like below:
> 
> ## ###############################################
> => JSON file:
> ```
> "Statement": [
>     {
>         "Action": "ec2:*",
>         "Effect": "Allow",
>         "Resource": "*",
> 		"Condition" :{"StringEquals" : {"ec2:InstanceType": "t2.micro",
> ```
> "ec2:ImageType":"ami-0782e9ee97725263d"}}
> },
> #################################################
> 
> You are not authorized to describe Running Instances
> You are not authorized to describe Dedicated Hosts
> You are not authorized to describe Volumes
> You are not authorized to describe Key Pairs
> You are not authorized to describe Placement Groups |  
> -- | --
> 
> Can you correct me.
> 
> Regards,
> Raja

In this code, In Action you mentioned "ec2:*" means you are allowing all ec2 actions, but you have given a condition to allow only "t2.micro" type. So it is conflicting.  
The solution is you have to specify actions :--
ex: {
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ec2:StartInstances",
        "ec2:StopInstances",      
        "ec2:RebootInstances",
        "ec2:TerminateInstances"
      ],
      "Condition": {
        {
           "StringEquals" : {"ec2:InstanceType": "t2.micro"
        }
      },
      "Effect": "Allow"
    }
  ]
}


> EC2-full acces and restric only t2.micro:
> 
> {
> "Version": "2012-10-17",
> "Statement": [
> {
> "Action": "ec2:_", "Effect": "Allow", "Resource": "_",
> "Condition": {
> "StringNotEquals": {
> "ec2:InstanceType": "t2.micro"
> }
> }
> },
> {
> "Effect": "Allow",
> "Action": "elasticloadbalancing:_", "Resource": "_"
> },
> {
> "Effect": "Allow",
> "Action": "cloudwatch:_", "Resource": "_"
> },
> {
> "Effect": "Allow",
> "Action": "autoscaling:_", "Resource": "_"
> },
> {
> "Effect": "Allow",
> "Action": "iam:CreateServiceLinkedRole",
> "Resource": "*",
> "Condition": {
> "StringEquals": {
> "iam:AWSServiceName": [
> "autoscaling.amazonaws.com",
> "ec2scheduled.amazonaws.com",
> "elasticloadbalancing.amazonaws.com",
> "spot.amazonaws.com",
> "spotfleet.amazonaws.com"
> ]
> }
> }
> }
> ]
> }

@shaikkhajaibrahim 
Sir, Is it correct? This logic is something wrong, can you pls explain?

**Comment by revathi-muthana123** [comment]
@raja139 
In Actions you have mentioned "ec2:*" means you are trying to allow all actions but restricting Instance Type. That's why you are facing issue.
***
ex: 
{
  "Statement": [
    {
      "Action": [
        "ec2:Describe*"
      ],
      "Effect": "Allow",
      "Resource": "*",
      "Condition": {
        "StringEquals": {
          "ec2:Region": "eu-west-1"
        }
      }
    }
  ]
}
***
You need to be mention specific action, relevant to your requirement.

Thanks & Regards
Revathi

**Comment by raja139** [comment]
Thank you Revathi.Can you please correct me for s3 service creation on "us-east-2"

I have used the following format but not able to create the bucket and getting error like "Error: S3 does not require region selection."

Json:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
            "s3:CreateBucket",
            "s3:ListBucket"
        ],
            "Resource": "*",
			"Condition" :{"StringEquals" : {"s3:LocationConstraint": "us-east-2"}}
        }
    ]
}

===============================================
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:CreateBucket"
            "Resource":[
            "arn:aws:s3:::*"],
			"Condition" :{"StringEquals" : {"s3:LocationConstraint": "us-east-2"}}
        }
    ]
}

=================================================
Error: S3 does not require region selection.

Regards,
Raja

**Comment by raja139** [comment]
> 
> 
> @raja139
> In Actions you have mentioned "ec2:*" means you are trying to allow all actions but restricting Instance Type. That's why you are facing issue.
> 
> ex:
> {
> "Statement": [
> {
> "Action": [
> "ec2:Describe*"
> ],
> "Effect": "Allow",
> "Resource": "*",
> "Condition": {
> "StringEquals": {
> "ec2:Region": "eu-west-1"
> }
> }
> }
> ]
> }
> 
> You need to be mention specific action, relevant to your requirement.
> 
> Thanks & Regards
> Revathi

Hi Revathi,

I'm able create ec2 instance with "ec2:Region": "eu-west-1" condition but my issue is with "{"ec2:InstanceType": "t2.micro"}".

Even i follow your instruction ,still i struck with the issue:

{
            "Action": [""ec2:StartInstances","ec2:StopInstances","ec2:RebootInstances","ec2:TerminateInstances"],
            "Effect": "Allow",
            "Resource": "*",
			"Condition" :{"StringEquals" : {"ec2:InstanceType": "t2.micro"}}
        },

**Comment by shaikkhajaibrahim** [comment]
Can you show whats happening visually when you login as this user  by sharing screenshots

**Comment by raja139** [comment]
Hi Sir,

I'm getting error "permission issue" like below before i select instance
type.

[image: image.png]

Regards,
Raja

**Comment by shaikkhajaibrahim** [comment]
Your image is not uploaded??

**Comment by raja139** [comment]
Hi,

Please find the attachment now.

Regards,
Raja

**Comment by revathi-muthana123** [comment]
@raja139 
pls upload by drag & drop method, first verify in preview then try to update comment.

Thanks & Regards
Revathi

**Comment by raja139** [comment]
Thanks revathi.

Please clarify me whether its about attachment or creating policy ?

Regards,
Raja
