### ISSUE TITLE
Relation b/w security group and subnet

### ISSUE THREAD

**Issue by sainathareddy** [QT-DevOps/DevOpsIssues#256]
when i run command 
aws ec2 run-instances --image-id ami-0e32ec5bc225539f5 --count 1 --instance-type t2.micro  --key
-name myansible --security-group-ids sg-01048a5f724140078
i got an error saying
An error occurred (InvalidParameter) when calling the RunInstances operation: Security group sg-01048a5f724140078 and subnet subnet-a78bf4fc belong to different networks.

according to the definition security group contains  some inbound/outbound rules then what the relation b/w security group and subnet

**Comment by shaikkhajaibrahim** [comment]
Security group is linked to vpc

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by revathi-muthana123** [comment]
Hi SainathReddy,
Your subnet belongs to one vpc, security group belongs to another vpc, Pls verify that.
=>if you mentioned default security group, take default vpc subnet
=> Another way if you taken your custom vpc subnet, create security group which belongs to that vpc.

Thanks & Regards
Revathi

**Comment by revathi-muthana123** [comment]
Is it done?
