### ISSUE TITLE
terraform issue

### ISSUE THREAD

**Issue by trinathtiru** [QT-DevOps/DevOpsIssues#257]
Hi,

Using terraform, created the AWS machine. But while adding a connection in the main.tf it is throwing the error.

  connection {
    user        = "ubuntu"
    private_key = "${file(var.privatekeypath)}"
  }

Error: Unknown root level key: connection

Please let me know where i am missing

**Comment by arunkumar127** [comment]
@trinathtiru 
Can you please upload your complete .tf file.

**Comment by trinathtiru** [comment]
provider "aws" {
    region = "${var.region}"
    access_key = "${var.access}"
    secret_key = "${var.secret}"
  
}

resource "aws_security_group" "allow_all" {
  name        = "allow_all"
  description = "Allow all inbound traffic"
  vpc_id      = "${var.vpcid}"

  ingress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
resource "aws_instance" "web" {
    ami = "ami-0f65671a86f061fcd"
    instance_type = "t2.micro"
    key_name = "job2mon"
    security_groups = ["${aws_security_group.allow_all.name}"]
 
}

Please find the main.tf

**Comment by raviops100** [comment]
Hi,

Can you please share your variables.tf file

why becoz 

resource "aws_instance" "web" {

you are not referning varaibles you have directly hard coded

and the attached main.tf doesnot have connection below entry 

connection {
user = "ubuntu"
private_key = "${file(var.privatekeypath)}"
}

Thanks
Ravi

**Comment by trinathtiru** [comment]
Hi Ravi,

Please find the variable.tf file
-----------------------------------------------------------------------------------
variable "region" {
    default = "us-east-2"
  
}

variable "access" {
    default = "string"  
}

variable "secret" {
    default = "string"
  
}

variable "vpcid" {
  default = "vpc-dba092b3"
}

variable "privatekeypath" {}
-------------------------------------------------------------------------------------------
main.tf
------------------------------------------------------------------------------------------
provider "aws" {
    region = "${var.region}"
    access_key = "${var.access}"
    secret_key = "${var.secret}"
  
}

resource "aws_security_group" "allow_all" {
  name        = "allow_all"
  description = "Allow all inbound traffic"
  vpc_id      = "${var.vpcid}"

  ingress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
resource "aws_instance" "web" {
    ami = "ami-0f65671a86f061fcd"
    instance_type = "t2.micro"
    key_name = "job2mon"
    security_groups = ["${aws_security_group.allow_all.name}"]
 
}
-------------------------------------------------------------------------------------
Till here there is no issue. But, if I am adding the below details then it throws an error.

connection {
user = "ubuntu"
private_key = "${file(var.privatekeypath)}"
}

Error: Unknown root level key: connection

**Comment by shaikkhajaibrahim** [comment]
Are you adding connection in resource?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by shaikkhajaibrahim** [comment]
Any updates

**Comment by trinathtiru** [comment]
Hi @shaikkhajaibrahim, 

Yes, I am adding connection after resource in main.tf file. Please correct me if I'm wrong.

resource "aws_instance" "web" {
ami = "ami-0f65671a86f061fcd"
instance_type = "t2.micro"
key_name = "job2mon"
security_groups = ["${aws_security_group.allow_all.name}"]
}
connection {
user = "ubuntu"
private_key = "${file(var.privatekeypath)}"
}

**Comment by arunkumar127** [comment]
@trinathtiru 
Connection block should be inside Resource block. It should be like...

resource "aws_instance" "web" {
  ami = "ami-0f65671a86f061fcd"
  instance_type = "t2.micro"
  key_name = "job2mon"
  security_groups = ["${aws_security_group.allow_all.name}"]
  connection {
    user = "ubuntu"
    private_key = "${file(var.privatekeypath)}"
  }
}

Try with this and let us know whether it is working or not.

Regards
Arun Kumar

**Comment by revathi-muthana123** [comment]
@trinathtiru 
Your script is working very well.
Can you pls share your "privatekeypath" variable, which is mentioned in "variable.tf" file.

Thanks & B.Regards
Revathi

**Comment by trinathtiru** [comment]
@arunkumar127  @shaikkhajaibrahim  @revathi-muthana123  Thanks.. it works now..... 👍 
Furthermore, combined provisioning to install ansible.  Please find the below steps to install ansible

 provisioner "remote-exec" {
    inline = [
      "sudo apt-get update",
      "sudo apt-get install software-properties-common -y",
      "sudo apt-repository ppa:ansible/ansible -y",
      "sudo apt-get update",
      "sudo apt-get install ansible -y"
         ]
  }

but I don't see ansible installed in the machine. Please correct me if I am wrong?

![image](https://user-images.githubusercontent.com/33506201/48418834-5acac800-e77c-11e8-9022-5fa6af2faf02.png)

**Comment by shaikkhajaibrahim** [comment]
Please close the ticket

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
