### ISSUE TITLE
Installed visual studio code using dsc but couldn't uninstalled it.

### ISSUE THREAD

**Issue by KishoreKrishna** [QT-DevOps/DevOpsIssues#259]
Hi Sir

I have installed visual studio code using dsc resource cchoco (Enable = "Present") and was successful, but I'm not able to uninstall it by replacing (Enable = "Absent"). Eventhough, it says package uninstalled, still I can use visual studio code.

**Configuration Ran First:**

Configuration basicinstallconfig {
Import-DSCresource -Modulename "cchoco"
Node "Localhost" {
cChocoInstaller "installchoco" {
InstallDir = "C:\Choco_Package_Manager"
}

cChocoPackageInstaller "installGit" {
Name = "Git"
DependsOn = "[cChocoInstaller]installChoco"
Ensure = "present"
}

cChocoPackageInstaller "installvsc" {
Name = "vscode"
DependsOn = "[cChocoInstaller]installChoco"
Ensure = "present"
}

cChocoPackageInstaller "installchrome" {
Name = "google-chrome-x64"
DependsOn = "[cChocoInstaller]installChoco"
Ensure = "present"
}

cChocoPackageInstaller "installnotepadplusplus" {
Name = "notepadplusplus"
DependsOn = "[cChocoInstaller]installChoco"
Ensure = "present"
}
}
}
basicinstallconfig

**Configuration Ran Next:**

Configuration basicinstallconfig {
Import-DSCresource -Modulename "cchoco"
Node "Localhost" {
cChocoInstaller "installchoco" {
InstallDir = "C:\Choco_Package_Manager"
}

cChocoPackageInstaller "installGit" {
Name = "Git"
DependsOn = "[cChocoInstaller]installChoco"
Ensure = "present"
}

cChocoPackageInstaller "installvsc" {
Name = "visualstudiocode"
DependsOn = "[cChocoInstaller]installChoco"
Ensure = "absent"
}

cChocoPackageInstaller "installchrome" {
Name = "google-chrome-x64"
DependsOn = "[cChocoInstaller]installChoco"
Ensure = "present"
}

cChocoPackageInstaller "installnotepadplusplus" {
Name = "notepadplusplus"
DependsOn = "[cChocoInstaller]installChoco"
Ensure = "present"
}
}
}
basicinstallconfig

Error in the Console: Chocolatey v0.10.11 Uninstalling the following packages: visualstudiocode  visualstudiocode v1.23.1.20180730  Skipping
auto uninstaller - No registry snapshot.  visualstudiocode has been successfully uninstalled. visualstudiocode not
uninstalled. An error occurred during uninstall:  Unable to find package 'visualstudiocode'.  Chocolatey uninstalled
0/1 packages. 1 packages failed.  See the log for details (C:\Choco_Package_Manager\logs\chocolatey.log).  Failures  -
visualstudiocode (exited 1) - visualstudiocode not uninstalled. An error occurred during uninstall:  Unable to find
package 'visualstudiocode'.  If a package uninstall is failing and/or you've already uninstalled the  software outside
of Chocolatey, you can attempt to run the command  with `-n` to skip running a chocolateyUninstall script, additionally
  adding `--skip-autouninstaller` to skip an attempt to automatically  remove system-installed software. This will only
 remove the packaging  files and not things like software installed to Programs and Features.  If a package is failing
because it is a dependency of another package  or packages, then you may first need to consider if it needs removed  as
 it is typically installed as a dependency for a reason. If you  decide that you still want to remove it, head into
`$env:ChocolateyInstall\lib` and find the package folder you want  removed. Then delete the folder for the package.

**Comment by raviops100** [comment]
Hi kishore,
The package name should be "vscode"
The second script you have attached package name you have given "visualstdiocode" please correct it try to run once
thanks 
Ravi

**Comment by shaikkhajaibrahim** [comment]
Fixed??

**Comment by revathi-muthana123** [comment]
@KishoreKrishna 
Pls respond is it done or not ?

**Comment by KishoreKrishna** [comment]
Hi Sir & Ravi

sorry for the delayed reply

**Yes it is, thank you.**

Things I noticed:
On running commands, 
choco install visualstudiocode -y OR choco install vscode -y
package manager is installing the package VSCODE (visualstudiocode v1.28)

And when I try to uninstall using the command:
**choco uninstall visualstudiocode -y**
It throws an error package not found
But with the following command:
**choco uninstall vscode -y**
it works fine

MayBe Reason: deprecated visualstudiocode at v1.23

With command: **choco install visualstudiocode -y** we get v1.28 VSC, but when running the uninstallation command:
**choco uninstall visualstudiocode -y** it may be looking for v1.23 which is not installed, so the error package not installed.

![vsc_deprecated](https://user-images.githubusercontent.com/44924861/48389869-51fad780-e725-11e8-912a-5d9911995923.PNG)
![vsc_today](https://user-images.githubusercontent.com/44924861/48389873-56bf8b80-e725-11e8-9c5a-4f7a1e92f012.PNG)

Once again, thank you for the quick responses and your time
