### ISSUE TITLE
Jenkins - Unable to connect Jenkins with AWS

### ISSUE THREAD

**Issue by MuraliTL25** [QT-DevOps/DevOpsIssues#26]
![jenkins cann t be reached](https://user-images.githubusercontent.com/39365053/40811743-14831220-6550-11e8-9770-879f83c15c20.PNG)
![jenkins connect with gitbah](https://user-images.githubusercontent.com/39365053/40811750-1c68bb20-6550-11e8-998f-5a7cc953cd6a.PNG)
![aws details](https://user-images.githubusercontent.com/39365053/40811810-605bf900-6550-11e8-8029-9227d37c33f4.PNG)

1.I have created free trail machine in AWS.
2.Ater create AWS machine followed jenkins installation steps.
3.Once jenkins installation done trying to connect, but cann't able to connect.
4.Please find attached screen shots and help me on the same. Thanks!.

**Comment by vijaybhaskarreddyy** [comment]
open port 8080 in secrity group.
