### ISSUE TITLE
Unable to connect machine via terraform

### ISSUE THREAD

**Issue by kmahesh121785** [QT-DevOps/DevOpsIssues#262]
Error

aws_instance.mymachine (remote-exec):   Checking Host Key: false
aws_instance.mymachine: Still creating... (1m0s elapsed)
aws_instance.mymachine: Still creating... (1m10s elapsed)
aws_instance.mymachine (remote-exec): Connecting to remote host via SSH...
aws_instance.mymachine (remote-exec):   Host: 18.188.13.49
aws_instance.mymachine (remote-exec):   User: ec2_user
aws_instance.mymachine (remote-exec):   Password: false
aws_instance.mymachine (remote-exec):   Private key: true
aws_instance.mymachine (remote-exec):   SSH Agent: false
aws_instance.mymachine (remote-exec):   Checking Host Key: false
aws_instance.mymachine: Still creating... (1m20s elapsed)

File

==============

variable "access" {}
variable "secret" {}
variable "region" {}
variable "instanctype"{
    default ="t2.micro"
}
variable "image"{}

variable "key"{
    default = "new"
}
variable "secgroups"{
    type="list"
    default=["launch-wizard-13"]
}
variable "private_key_path"{
    default= "new.pem"
}

provider "aws" {
  access_key = "${var.access}"
  secret_key = "${var.secret}"
  region =     "${var.region}"
}

resource "aws_instance" "mymachine" {
  instance_type = "${var.instanctype}"
  ami ="${var.image}"
  key_name="${var.key}"
  security_groups="${var.secgroups}"
  tags{
      Name = "Helloworld"
  }
  connection{
      user="ec2_user"
      private_key = "${file(var.private_key_path)}"
  }
  provisioner "remote-exec"{
      inline=["sudo apt-get update", "sudo apt-get install tree -y"]
  }
}

**Comment by raviops100** [comment]
Hi Mahesh,
in the above script 4 Th line variable "instanctype"{ default ="t2.micro"}
"instancetype" spelling you just missed to type letter e

Thanks
Ravi

**Comment by kmahesh121785** [comment]
Error is repeating even after above changes

**Comment by kmahesh121785** [comment]
Any update admin

**Comment by revathi-muthana123** [comment]
@kmahesh121785 
Where did you pass region & ami values? Can you pls share your execution commands ??

Thanks & Regards
Revathi

**Comment by kmahesh121785** [comment]
terraform apply -var access=XXXXX -var secret=XXXXXXX -var region=us-east-2 -var image=ami-0b59bfac6be064b78 .

i provided access and secret key correctly

**Comment by revathi-muthana123** [comment]
In variable "private_key_path" you have to specify "Relative path" or exact path of pem file.
But you specified only key name. Pls change then let me know.

**Comment by revathi-muthana123** [comment]
pls share your security group rules ; it's better you to create new security group from our script itself.
i think you need to mention "ID of security group".
I am not sure whether it ll work or not as like you mentioned.

@shaikkhajaibrahim 
Sir, pls confirm on this.

**Comment by revathi-muthana123** [comment]
I tried with your script, but im also facing same issue.

**Comment by srinivas25682** [comment]
I think , you missed " ". Please try command as below
terraform apply -var "keyName=****" -var "accesskey=*****" -var "secretkey=****** "
