### ISSUE TITLE
unable to install docker ce on windows 10 pro

### ISSUE THREAD

**Issue by harimakenti** [QT-DevOps/DevOpsIssues#263]
installed docker-ce by using choco , it is downloaded

PS C:\Windows\system32> choco install docker-for-windows -y
Chocolatey v0.10.11
Installing the following packages:
docker-for-windows
By installing you accept licenses for the packages.
Progress: Downloading docker-for-windows 18.06.1.19507... 100%

docker-for-windows v18.06.1.19507 [Approved]
docker-for-windows package files install completed. Performing other installation steps.
Downloading docker-for-windows
  from 'https://download.docker.com/win/stable/19507/Docker%20for%20Windows%20Installer.exe'
Progress: 100% - Completed download of C:\Users\shiva\AppData\Local\Temp\chocolatey\docker-for-windows\18.06.1.19507\Docker for Windows Installer.exe (521.01 MB).
Download of Docker for Windows Installer.exe (521.01 MB) completed.
Hashes match.
Installing docker-for-windows...
[23:13:22.443] [InstallWorkflow] Pre-requisite failed: Docker for Windows requires Windows 10 Pro or Enterprise version 14393, or Windows server 2016 RTM to run
docker-for-windows has been installed.
Only an exit code of non-zero will fail the package by default. Set
 `--failonstderr` if you want error messages to also fail a script. See
 `choco -h` for details.
 The install of docker-for-windows was successful.
  Software installed as 'EXE', install location is likely default.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

but when i try to  run installer  it is giving following error
i frustrated , this is my third attempt , i tried all versions of docker ce editions
iam using windows 10 pro version

Docker for Windows requires Windows 10 Pro or Enterprise version 14393, or Windows server 2016 RTM to run

**Comment by raviops100** [comment]
Hi Hari,

Reason No:1
To run Docker, your machine must have a 64-bit operating system running Windows 7 or higher.
Additionally, you must make sure that virtualization is enabled on your machine.
Reason No:2
Please install docker tool box
Docker Toolbox automatically creates a Linux VM on VirtualBox that hosts Docker on your Windows system
go to below link
https://docs.docker.com/toolbox/toolbox_install_windows/
click on download next == go for default steps

Thanks
Ravi

**Comment by shaikkhajaibrahim** [comment]
Resolution is uninstall VmWare/Virtual box before you use Docker
