### ISSUE TITLE
issue regarding docker ce on windows

### ISSUE THREAD

**Issue by harimakenti** [QT-DevOps/DevOpsIssues#264]
Hai

i installed docker ce on windows 10 pro  by using choco.  choco  only downloaded docker installer and when i try to run the installer file. is saying that  you have to execute it from windows 10 pro . i tried it for many times  no use.

Regards
Hari

**Comment by shaikkhajaibrahim** [comment]
Follow the documentation over here https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install.

If you have any mismatch in prerequisites get them corrected

**Comment by harimakenti** [comment]
I fulfilled are the requirements

**Comment by harimakenti** [comment]
I fulfilled all the requirements

**Comment by shaikkhajaibrahim** [comment]
Do one thing
Please share screenshot of your bios setting to prove virtualize tion is enabled.
Then I will come to other pre reqs

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by harimakenti** [comment]
I am running Nealy 2 VMs daily

**Comment by shaikkhajaibrahim** [comment]
VMS using hyperv??

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by harimakenti** [comment]
No using vmware, virtual box

**Comment by shaikkhajaibrahim** [comment]
In this case docker will not work as only one hypervisor is allowed . You have to uninstall others to enable hyperv . SO docker cannot be used in your system as long as you have vmware/virtual box.

Uninstall others to use Docker
________________________________

**Comment by shaikkhajaibrahim** [comment]
Resolution is uninstall other hypervisors(vmware/virtual box)

**Comment by harimakenti** [comment]
This is win 10 pro  on this I don't hv any other VMs, I hv VMs on Win7,why
I am saying this it proves virtualization is enabled on my lap

**Comment by shaikkhajaibrahim** [comment]
Do you have virtual box or vmware installed on this machine?
________________________________

**Comment by harimakenti** [comment]
I dnt hv any hypervisors on it this is win 10 pro newly installed ,
previously I was using VMs that was on win 7 . But now on this machine
hyperv v is enabled

**Comment by shaikkhajaibrahim** [comment]
Then there is no reason for failure. Raise community issue on docker

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
