### ISSUE TITLE
unable to execute powershell DSC 

### ISSUE THREAD

**Issue by harimakenti** [QT-DevOps/DevOpsIssues#266]
i have been facing this issue for the last one week , but there is no resolavation, iam using powershell 5.0
still i have a issue with docker ce installation on windows 10 pro. that is also not resoloved sofar.

i set all the necessary permissions , i executed enable-psremoting -force i executed policies and i have executed as admistrator. pl resolve the issues as early as possible

issue no.1 i posted yesterday

1) on windows 10 pro i was not able install docker ce
issue no 2
2)i unable to execute powershell dsc for the the last week, and iam posting all my execution environment

PS C:\Windows\system32> Get-Host

Name             : ConsoleHost
Version          : 5.0.10240.16384
InstanceId       : ffd486b8-2b12-47b0-b5e8-c0ac91e9d51a
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

PS C:\Windows\system32> cd\
PS C:\> cd .\powershelldsc\
PS C:\powershelldsc> ls

    Directory: C:\powershelldsc

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        11/9/2018   9:42 PM                issues
d-----        11/6/2018  10:33 PM                test
d-----        11/7/2018   2:21 AM                WebSiteTest
-a----        11/6/2018   9:56 PM            774 WebSite.ps1
-a----        11/7/2018   4:43 AM            795 WebSiteTest.ps1

PS C:\powershelldsc> . .\WebSiteTest.ps1
. : File C:\powershelldsc\WebSiteTest.ps1 cannot be loaded because running scripts is disabled on this system. For
more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . .\WebSiteTest.ps1
+   ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\powershelldsc> Enable-PSRemoting -force
WinRM has been updated to receive requests.
WinRM service type changed successfully.
WinRM service started.

WinRM has been updated for remote management.
Created a WinRM listener on HTTP://* to accept WS-Man requests to any IP on this machine.
WinRM firewall exception enabled.
Configured LocalAccountTokenFilterPolicy to grant administrative rights remotely to local users.

PS C:\powershelldsc> . .\WebSiteTest.ps1
. : File C:\powershelldsc\WebSiteTest.ps1 cannot be loaded because running scripts is disabled on this system. For
more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . .\WebSiteTest.ps1
+   ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\powershelldsc> dir

    Directory: C:\powershelldsc

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        11/9/2018   9:42 PM                issues
d-----        11/6/2018  10:33 PM                test
d-----        11/7/2018   2:21 AM                WebSiteTest
-a----        11/6/2018   9:56 PM            774 WebSite.ps1
-a----        11/7/2018   4:43 AM            795 WebSiteTest.ps1

PS C:\powershelldsc> . .\WebSiteTest.ps1
. : File C:\powershelldsc\WebSiteTest.ps1 cannot be loaded because running scripts is disabled on this system. For
more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . .\WebSiteTest.ps1
+   ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\powershelldsc> . .\WebSiteTest.ps1
. : File C:\powershelldsc\WebSiteTest.ps1 cannot be loaded because running scripts is disabled on this system. For
more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . .\WebSiteTest.ps1
+   ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\powershelldsc> Enable-PSRemoting -force
WinRM is already set up to receive requests on this computer.
WinRM is already set up for remote management on this computer.
PS C:\powershelldsc> Start-DscConfiguration .\WebSiteTest

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
4      Job4            Configuratio... Running       True            localhost,WINCTRL... Start-DscConfiguration...

PS C:\powershelldsc> . .\WebSiteTest.ps1
. : File C:\powershelldsc\WebSiteTest.ps1 cannot be loaded because running scripts is disabled on this system. For
more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . .\WebSiteTest.ps1
+   ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\powershelldsc> Set-Item WSMan:localhost\client\trustedhosts -value *

WinRM Security Configuration.
This command modifies the TrustedHosts list for the WinRM client. The computers in the TrustedHosts list might not be
authenticated. The client might send credential information to these computers. Are you sure that you want to modify
this list?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): Y
PS C:\powershelldsc> . .\WebSiteTest.ps1
. : File C:\powershelldsc\WebSiteTest.ps1 cannot be loaded because running scripts is disabled on this system. For
more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . .\WebSiteTest.ps1
+   ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
PS C:\powershelldsc> set-executionpolicy unrestricted

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
http://go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
PS C:\powershelldsc> . .\WebSiteTest.ps1

    Directory: C:\powershelldsc\WebSiteTest

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/14/2018  11:04 AM           2106 localhost.mof

PS C:\powershelldsc> Start-DscConfiguration .\WebSiteTest

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
7      Job7            Configuratio... Running       True            localhost,WINCTRL... Start-DscConfiguration...

PS C:\powershelldsc>

**Comment by raviops100** [comment]
Hi Hari,
are you available in LAB today ??

**Comment by shaikkhajaibrahim** [comment]
Only way to solve this is refer these https://stackoverflow.com/questions/4037939/powershell-says-execution-of-scripts-is-disabled-on-this-system
