### ISSUE TITLE
Ansible installation by vagrant 

### ISSUE THREAD

**Issue by ajs777** [QT-DevOps/DevOpsIssues#267]
Can you please tell me how to send ssh key to another vagrant machine

**Comment by santoshkalingwar** [comment]
please give the ip to both vagrant machine in vagrant file  then do ssh with ssh command

eg: Vagrant.configure(2) do |config|
    config.vm.define "master" do |master|    
        master.vm.box = "ubuntu/trusty64"
        # You may wish to use a more obscure private ip, like 10.2.2.4
        master.vm.network "private_network", ip: "10.0.0.200"
    end

then ssh
eg: ssh 10.0.0.200

**Comment by raviops100** [comment]
is it fixed ???
