### ISSUE TITLE
not able to create ec2 machine through cloudformation

### ISSUE THREAD

**Issue by vinay4001** [QT-DevOps/DevOpsIssues#269]
![243](https://user-images.githubusercontent.com/44084389/48704823-94d51780-ec1d-11e8-8c4e-5b85a3b60a53.PNG)
![capture2435](https://user-images.githubusercontent.com/44084389/48704841-9c94bc00-ec1d-11e8-98ff-2a27e3e1084e.PNG)

**Comment by raviops100** [comment]
Hi Vinay,
Every AWS regions is having diffrent Image-id's

If you select  image id in 1 regions and you trying 
to execute cloudformationscript in other region it will through Image id doesn't exist

Can you please check once
Thanks
Ravi

**Comment by revathi-muthana123** [comment]
Yes, Khaja sir & Ravi's answer is  absolutely correct, the default AMI is intended for use in the default
region (us-east-1). We  keep a list of
what AMIs are intended for use in the other regions and switch based upon
region selection. 

Thank you.

**Comment by revathi-muthana123** [comment]
@vinay4001 
Pls confirm, is it fixed?

**Comment by vinay4001** [comment]
yes sir.

**Comment by revathi-muthana123** [comment]
pls close this issue.
