### ISSUE TITLE
issue:packer creation of ami of linux

### ISSUE THREAD

**Issue by cvreddy1236** [QT-DevOps/DevOpsIssues#27]
![ami of ubuntu](https://user-images.githubusercontent.com/39652472/40823596-851bbee0-658e-11e8-9123-31a78d24dd4e.PNG)

**Comment by cvreddy1236** [comment]
the issue is with creation of ami in ubutu with nginx.

**Comment by cvreddy1236** [comment]
"sudo rm  /var/lib/apt/lists/lock",            
            "sudo rm  /var/cache/apt/archives/lock",
            "sudo rm  /var/lib/dpkg/lock",
        
added these lines in provisioners issue is resolved

**Comment by shaikkhajaibrahim** [comment]
Can you share your provisioning script

**Comment by cvreddy1236** [comment]
{
    "variables": {
        "aws_access": "",
        "aws_secret": ""
    },
    "builders": [
        {
                "type": "amazon-ebs",
                "access_key": "{{user `aws_access`}}",
                "secret_key": "{{user `aws_secret`}}",
                "region": "us-east-2",
                "source_ami": "ami-aad1e0cf",
                "instance_type": "t2.micro",
                "ssh_username": "ubuntu",
                "ami_name": "packernginx"
        }
    ],
    "provisioners": [
        {
            "type": "shell",
            "inline": [
            "sudo rm -rf /var/lib/apt/lists/lock",            
            "sudo rm -rf /var/cache/apt/archives/lock",
            "sudo rm -rf /var/lib/dpkg/lock",
            "sudo apt-get update",
            "sudo apt-get install nginx -y"              
            ]
        }
    ]
}

**Comment by shaikkhajaibrahim** [comment]
Those are not required. Probably you might need shebang (in some ubuntu machines)

![image](https://user-images.githubusercontent.com/2438317/41097319-26e68102-6a75-11e8-851a-36885c0b084e.png)
