### ISSUE TITLE
parameterize SVN url in jenkins pipeline script

### ISSUE THREAD

**Issue by vamsi1670** [QT-DevOps/DevOpsIssues#271]
can you please let me know how to parameterize SVN repository url using jenkins pipeline script so that branches/tags/trunk , are selected using parameters.

**Comment by ghost** [comment]
please follow below link
https://st-g.de/2016/12/parametrized-jenkins-pipelines

**Comment by vamsi1670** [comment]
If this is the script i used,
checkout([$class: 'SubversionSCM', 
          additionalCredentials: [], 
          excludedCommitMessages: '', 
          excludedRegions: '', 
          excludedRevprop: '', 
          excludedUsers: '', 
          filterChangelog: false, 
          ignoreDirPropChanges: false, 
          includedRegions: '', 
          locations: [[credentialsId: '34761a89-1402-47d7-96e2-aec22ffdc50b', ----Credentials ID has  to be parmeterized like SVN URL.
                       depthOption: 'infinity', 
                       ignoreExternalsOption: true, 
                       local: 'cable_branch', 
                       remote: {"https://trac.nci.org.au/svn/cable/branches/$SVN_BRANCH"} ]],  ----- **this url has  to be parameterized so that if new branch is created automatically it has to be seen in jenkins  dashboard.**
          workspaceUpdater: [$class: 'UpdateUpdater']])

**Comment by vamsi1670** [comment]
"https://trac.nci.org.au/svn/cable/branches/$SVN_BRANCH" this is the way we have to give to parameterize the svn repository url. 
this issue is closed.
