### ISSUE TITLE
unable execute ansible -m ping all

### ISSUE THREAD

**Issue by harimakenti** [QT-DevOps/DevOpsIssues#272]
ansible@ip-172-31-40-117:~$ ssh-copy-id localhost
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed

/usr/bin/ssh-copy-id: WARNING: All keys were skipped because they already exist on the remote system.

ansible@ip-172-31-40-117:~$ ansible -m ping all
 [WARNING]:  * Failed to parse /etc/ansible/hosts with yaml plugin: Syntax Error while loading YAML.   could not find
expected ':'  The error appears to have been in '/etc/ansible/hosts': line 45, column 1, but may be elsewhere in the file
depending on the exact syntax problem.  (specified line no longer in file, maybe it changed?)

 [WARNING]:  * Failed to parse /etc/ansible/hosts with ini plugin: /etc/ansible/hosts:18: Expected key=value host
variable assignment, got: 2:

 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'

**Comment by revathi-muthana123** [comment]
share your "hosts" file also

**Comment by revathi-muthana123** [comment]
I am asking you to upload in this issue. Don't raise another issue(delete that one).
That file format also not clear.

**Comment by harimakenti** [comment]
Now I uploaded complete Document including hosts file

**Comment by revathi-muthana123** [comment]
Execute "ansible -m  -vv ping localhost", then show me output.

**Comment by revathi-muthana123** [comment]
or else create another hosts file, mention "localhost" in that file.
Then execute "ansible  -i hosts -m ping localhost.

**Comment by revathi-muthana123** [comment]
if it is fixed, close the issue hari.

**Comment by harimakenti** [comment]
It is not solved the default hosts file is not recognisint

**Comment by santoshkalingwar** [comment]
hi hari,

yesterday i show you how to create another host file and execute, please try that one, otherwise you take hosts file backup and create another one hosts file in same place it will resolve your issue ,

please close the issue

**Comment by nempati** [comment]
ssh-copy-id ansible@localhost i think this must be the command to ping self machine

**Comment by harimakenti** [comment]
The machine is pinging itself
