### ISSUE TITLE
my hosts file

### ISSUE THREAD

**Issue by harimakenti** [QT-DevOps/DevOpsIssues#273]
## 192.168.100.10

Ex 2: A collection of hosts belonging to the 'webservers' group

## 192.168.1.110

# If you have multiple hosts following a pattern you can specify
# them like this:

## www[001:006].example.com

# Ex 3: A collection of database servers in the 'dbservers' group

##
## 10.25.1.57

# Here's another example of host ranges, this time there are no
# leading 0s:

## db-[99:101]-node.example.com
localhost

**Comment by shaikkhajaibrahim** [comment]
Don't raise issue for every reply. Please use #272
