### ISSUE TITLE
my complete hosts unable to ping

### ISSUE THREAD

**Issue by harimakenti** [QT-DevOps/DevOpsIssues#274]
i enabled password less connectivity
ssh-keygen
ssh-copy-id localhost
ssh-copy-id ansible@172.31.43.23

## 192.168.100.10

Ex 2: A collection of hosts belonging to the 'webservers' group

## 192.168.1.110

# If you have multiple hosts following a pattern you can specify
# them like this:

## www[001:006].example.com

# Ex 3: A collection of database servers in the 'dbservers' group

##
## 10.25.1.57

# Here's another example of host ranges, this time there are no
# leading 0s:

## db-[99:101]-node.example.com
localhost
172.31.43.23

ansible@ip-172-31-40-117:/etc/ansible$ ansible -m ping all
 [WARNING]:  * Failed to parse /etc/ansible/hosts with yaml plugin: Syntax Error while loading YAML.   could not find
expected ':'  The error appears to have been in '/etc/ansible/hosts': line 45, column 1, but may be elsewhere in the file
depending on the exact syntax problem.  The offending line appears to be:  localhost 172.31.43.23 ^ here

 [WARNING]:  * Failed to parse /etc/ansible/hosts with ini plugin: /etc/ansible/hosts:18: Expected key=value host
variable assignment, got: 2:

 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'

**Comment by shaikkhajaibrahim** [comment]
Use #272 to reply

**Comment by shaikkhajaibrahim** [comment]
Use #272 to reply
