### ISSUE TITLE
Build number to be selected manually.

### ISSUE THREAD

**Issue by vamsi1670** [QT-DevOps/DevOpsIssues#275]
I have created a pipeline job for jenkins. this job is to parameterize the build number. Requirement is , one have to select the build number in the job manually.which should be similar to Drop-down list which shows all the list of builds. can any one help in this regards.

**Comment by santoshkalingwar** [comment]
please use this url may be help you
-------------------------------------------------------------------------------------
https://stackoverflow.com/questions/19135280/parameter-list-in-jenkins-to-display-list-of-build-numbers-from-another-build

**Comment by vamsi1670** [comment]
thanks you Santosh working on that will update you once this is completed.

**Comment by vamsi1670** [comment]
Hi Team
https://stackoverflow.com/questions/19135280/parameter-list-in-jenkins-to-display-list-of-build-numbers-from-another-build 
the above url is good to go but "Dynamic  parameter plugin " is not available to proceed with the above approach. 
So tried the below approach,but i am able to deploy the specific build but unable to manually select the build number if anybody can assist me with this it would be helpful.
https://stackoverflow.com/questions/15126059/how-to-promote-a-specific-build-number-from-another-job-in-jenkins

**Comment by vamsi1670** [comment]
do anyone have any approach using script ,and using active choice reactive reference parameter plugin.
