### ISSUE TITLE
i unable to execute ansible roles , i already inststalled role and when try to run playbook i am facing the following error

### ISSUE THREAD

**Issue by harimakenti** [QT-DevOps/DevOpsIssues#276]
i unable to execute ansible roles , i already inststalled role and when try to run playbook i am facing the following error on ubuntu 16 aws cloud 

playbook contents
---
- name: Converge
  hosts: all
  become: true
  gather_facts: false

  roles:
    - robertdebock.java
    - robertdebock.tomcat

ansible@ip-172-31-32-12:~/playbooks$ ansible-playbook testrole.yml
ERROR! the role 'robertdebock.java' was not found in /home/ansible/playbooks/roles:/home/ansible/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ansible/playbooks

The error appears to have been in '/home/ansible/playbooks/testrole.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - robertdebock.java
      ^ here

 ansible-playbook testrole.yml      ERROR! the role 'robertdebock.java' was not found in /home/ansible/playbooks/roles:/home/ansible/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/ansible/playbooks

The error appears to have been in '/home/ansible/playbooks/testrole.yml': line 8, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:---

- name: Converge
  hosts: all
  become: true
  gather_facts: false
  roles:
    - robertdebock.tomcat

  roles:
    - robertdebock.java
      ^ here

i tried with the following playbook contents  also still iam getting the following error

PLAY [Converge] **********************************************************************************************************

TASK [robertdebock.tomcat : loop over tomcat_instances] ******************************************************************
included: /home/ansible/.ansible/roles/robertdebock.tomcat/tasks/instance.yml for localhost, 172.31.36.103

TASK [robertdebock.tomcat : ensure instance group exists] ****************************************************************
ok: [localhost]
ok: [172.31.36.103]

TASK [robertdebock.tomcat : ensure instance user exists] *****************************************************************
ok: [localhost]
ok: [172.31.36.103]

TASK [robertdebock.tomcat : ensure instance directory exists] ************************************************************
ok: [172.31.36.103]
ok: [localhost]

TASK [robertdebock.tomcat : install tomcat instance] *********************************************************************
skipping: [localhost]
skipping: [172.31.36.103]

TASK [robertdebock.tomcat : configure tomcat instance] *******************************************************************
ok: [172.31.36.103]
ok: [localhost]

TASK [robertdebock.tomcat : register tomcat instance to sysvinit] ********************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'ansible_service_mgr == \"sysvinit\" or ansible_service_mgr== \"upstart\"' failed. The error was: error while evaluating conditional (ansible_service_mgr == \"sysvinit\" or ansible_service_mgr == \"upstart\"): 'ansible_service_mgr' is undefined\n\nThe error appears to have been in '/home/ansible/.ansible/roles/robertdebock.tomcat/tasks/instance.yml': line 46, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: register tomcat instance to sysvinit\n  ^ here\n"}
fatal: [172.31.36.103]: FAILED! => {"msg": "The conditional check 'ansible_service_mgr == \"sysvinit\" or ansible_service_mgr == \"upstart\"' failed. The error was: error while evaluating conditional (ansible_service_mgr == \"sysvinit\" or ansible_service_mgr == \"upstart\"): 'ansible_service_mgr' is undefined\n\nThe error appears to have been in '/home/ansible/.ansible/roles/robertdebock.tomcat/tasks/instance.yml': line 46, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: register tomcat instance to sysvinit\n  ^ here\n"}
        to retry, use: --limit @/home/ansible/playbooks/testrole.retry

PLAY RECAP ***************************************************************************************************************
172.31.36.103              : ok=5    changed=0    unreachable=0    failed=1
localhost                  : ok=5    changed=0    unreachable=0    failed=1

Even add robertdebock.bootstrap role  in playbook and execute it  iam getting same error

**Comment by arunkumar127** [comment]
@harimakenti 
robertdebock.bootstrap role is also required to use Java & Tomcat roles. There is link between some variables defined in these roles.
After using these 3 roles, Java 8 & Tomcat 8.5.34 were installed.

Regards
Arun Kumar

**Comment by santoshkalingwar** [comment]
please download the 'robertdebock.java' role , then execute it ,

please read how to execute role in roles document

**Comment by harimakenti** [comment]
I downloaded role

**Comment by raviops100** [comment]
Hi Hari,
It is failing due to robertdebock.tomcat 
After downlaod this robertdebock.tomcat role 
/home/ansible/.ansible/roles/robertdebock.tomcat/tasks/instance.yml

line no 46:
template:
   dest: "/etc/init.d/{{ instance.name | default(tomcat_name) }}"
    mode: 0750
  when:
    - ansible_service_mgr == "sysvinit"
      or ansible_service_mgr == "upstart"
	  
	  **Prior to ansible 2.4.0.0 ansible_service_mgr contained the value sysvinit, 
	  after the update to 2.4.0.0 ansible falls back to service. 
	   would call it "alternative fact" right now, at least some roles fail due to this behaviour.**
	  
I guess it is product related bug( I am not sure)

Thy Guy who developed this role might be run and works in other Ansible Releases
	  
ansible_service_mgr fact for sysvinit incorrect in ansible 2.4.0 

Please follow below link more deatils

https://github.com/ansible/ansible/issues/30753

Thanks
Ravi
