### ISSUE TITLE
i unable to connect to ansible tower giving invaliduser name and password for centos user 

### ISSUE THREAD

**Issue by harimakenti** [QT-DevOps/DevOpsIssues#277]
i given user name and password in ansible tower login page but it is giving invalid user name and password i tried several times

$ ssh -i "ansibletower.pem" centos@ec2-54-152-35-98.compute-1.amazonaws.com
Last login: Sun Nov 25 17:34:54 2018 from 157.48.18.169

  Welcome to Ansible Tower!

  Log into the web interface here:

    https://10.42.0.42/

    Username: admin
    Password: gPmhfLHYQ2Tb

Invalid username and/or password. Please try again.
USERNAME
admin
PASSWORD
••••••••••••

i tried it for 3 times .

**today also i tried same iam facing same error**

$ ssh -i "ansibletowerkey.pem" centos@ec2-34-215-184-150.us-west-2.compute.amazonaws.com

Last login: Mon Nov 26 09:15:54 2018 from 157.48.49.204

  Welcome to Ansible Tower!

  Log into the web interface here:

    https://10.42.0.42/

    Username: admin
    Password: 6J7eMnDLYRnD

  The documentation for Ansible Tower is available here:

    http://www.ansible.com/tower/

  For help, visit  http://support.ansible.com/

Invalid username and/or password. Please try again.
USERNAME
PASSWORD

**Comment by santoshkalingwar** [comment]
please try to create ansible tower again
