### ISSUE TITLE
Worker node in "NotReady" state after joining with Master

### ISSUE THREAD

**Issue by kampatinagesh** [QT-DevOps/DevOpsIssues#278]
I try to join the worker nodes to kubemaster. it was joined successfully ,after i need to check the status of the status:
$ kubectl get nodes
in this nodes are not ready state. Please find the attached screen shot for your reference.

kmaster@kmaster:~$ kubectl get nodes
NAME          STATUS     ROLES    AGE    VERSION
kmaster       Ready      master   108m   v1.12.2
workernode1   NotReady   <none>   77m    v1.12.2
workernode2   NotReady   <none>   77m    v1.12.2
kmaster@kmaster:~$

Please help me.

**Comment by raviops100** [comment]
HI Nagesh,
Can you try to execute below command on kubernetes master
 kubectl apply --filename https://git.io/weave-kube-1.6
after this execute
kubectl get nodes

**Comment by kampatinagesh** [comment]
Not working again i am getting same error.

**Comment by nempati** [comment]
kubectl describe nodes   once can you plz try this

and find what is the state of nodes

**Comment by kampatinagesh** [comment]
I have tried that one. but no luck 
Still it is showing not ready state.

**Comment by shaikkhajaibrahim** [comment]
Please open required ports as per kubernetes documentation

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
