### ISSUE TITLE
ansible vault error when running a playbook

### ISSUE THREAD

**Issue by muraligedela** [QT-DevOps/DevOpsIssues#279]
Team,

I am having issues while running a playbook with vault. Below are the steps I have followed to create it.

vault encrypted file

password.yml
---
password: admin@123

task.yml

- hosts: dbserver
  become: yes
  gather_facts: false
  tasks:
  - name: adding users on the remote machine
    user:
      name: testuser
      password: "{{password}}"

-------
The error while I am running the playbook is
ansible-playbook -i hosts --vault-id password.yml task.yml

Error:
 **[WARNING]: Error in vault password file loading (None): A vault password must be specified to decrypt data

ERROR! A vault password must be specified to decrypt data**

please help me out.
Thanks in advance.

**Comment by ramana152** [comment]
@muraligedela     in password line inside password give space like "{{ password }}" and try it.

**Comment by muraligedela** [comment]
Hello Sir,
I tried using space in the tasks.yml file and the error still reproduces.

**tasks.yml**
- hosts: dbserver
  become: yes
  gather_facts: false
  tasks:
  - name: adding users on the remote machine
    user:
      name: testuser
      password: "{{password}}"
      state: present
**Error :**
_jenkins@ip-172-31-90-149:~/playbooks$ ansible-playbook -i hosts --vault-id passwd.yml task.yml_
 [WARNING]: Error in vault password file loading (None): A vault password must be specified to decrypt data

ERROR! A vault password must be specified to decrypt data

**Comment by raviops100** [comment]
Hi Murali,

for Example  you have password.yml file inside that you have TESTSERVER
username and password if you want to protect this
	
then command is ansible-vault encrypt password.yml
it will ask password: you should give any password
From command line 
	      
ansible-playbook password.yml --ask-vault-pass 

In your playbook you have written  **adding user to the remote machine**
Ansible-valut is not for the your required purpose

Thanks
Ravi

**Comment by muraligedela** [comment]
Thanks Ravi. I got you
