### ISSUE TITLE
kubernetes 

### ISSUE THREAD

**Issue by sunnydevops** [QT-DevOps/DevOpsIssues#28]
Why i am getting this error.
![capture1](https://user-images.githubusercontent.com/31772526/40850874-6575d602-65e3-11e8-8534-6f8863ebd756.PNG)

**Comment by vijaybhaskarreddyy** [comment]
open all the ports in you're security group.

**Comment by shaikkhajaibrahim** [comment]
Working??

**Comment by sunnydevops** [comment]
yes, i forget to copy this command on node machine.

mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
 sudo chown $(id -u):$(id -g) $HOME/.kube/config
