### ISSUE TITLE
Ansible role installation issue

### ISSUE THREAD

**Issue by VenkateswararaoPaturi** [QT-DevOps/DevOpsIssues#282]
Can some one please help on below issue.

When i try to install any role getting the bellow error and role installation is failing. What can be done to resolve this issue?

ansible@ip-172-31-32-179:~$ ansible-galaxy install robertdebock.tomcat
 [WARNING]: - robertdebock.tomcat was NOT installed successfully: Failed to get data from the API server (https://galaxy.ansible.com/api/): Failed to validate the SSL
certificate for galaxy.ansible.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >=
2.7.9 on your managed machine  (the python executable used (/usr/bin/python) is version: 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]) or you can install the
`urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to
confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs,
/usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: hostname u'galaxy.ansible.com' doesn't match either of '*.c1e4.galaxy.openshiftapps.com',
'c1e4.galaxy.openshiftapps.com'.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by raviops100** [comment]
HI  can you please post which version of Ansible you are using ???

**Comment by raviops100** [comment]
Hi

1. To fix the issue you need to upgarade your python version to 3.0

otherwise :

i guess your   machine python version is 2.7.9

 you should install additional dependencies for urllib3 library:

pip install urllib3[secure]

Please try this

**Comment by VenkateswararaoPaturi** [comment]
@raviops100 
i am using below versions of Ansible and Python 

python --version
Python 2.7.6
ansible --version
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]

i have updated the package but still getting same error 

 sudo pip install urllib3[secure] update
Requirement already satisfied (use --upgrade to upgrade): urllib3[secure] in /usr/local/lib/python2.7/dist-packages
  Installing extra requirements: 'secure'
Downloading/unpacking update
  Downloading update-0.0.1-py2.py3-none-any.whl
Downloading/unpacking style==1.1.0 (from update)
  Downloading style-1.1.0-py2.py3-none-any.whl
Installing collected packages: update, style
Successfully installed update style
Cleaning up...

ansible-galaxy install robertdebock.tomcat
 [WARNING]: - robertdebock.tomcat was NOT installed successfully: Failed to get data from the API server (https://galaxy.ansible.com/api/): Failed to validate the SSL
certificate for galaxy.ansible.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >=
2.7.9 on your managed machine  (the python executable used (/usr/bin/python) is version: 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]) or you can install the
`urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to
confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs,
/usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: hostname u'galaxy.ansible.com' doesn't match either of '*.c1e4.galaxy.openshiftapps.com',
'c1e4.galaxy.openshiftapps.com'.

**Comment by VenkateswararaoPaturi** [comment]
i have updated python version to 3.X but still getting same error .

python --version
Python 3.4.3
 ansible-galaxy install robertdebock.java
 [WARNING]: - robertdebock.java was NOT installed successfully: Failed to get data from the API server (https://galaxy.ansible.com/api/): Failed to validate the SSL
certificate for galaxy.ansible.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >=
2.7.9 on your managed machine  (the python executable used (/usr/bin/python) is version: 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]) or you can install the
`urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to
confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs,
/usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: hostname u'galaxy.ansible.com' doesn't match either of '*.c1e4.galaxy.openshiftapps.com',
'c1e4.galaxy.openshiftapps.com'.

**Comment by raviops100** [comment]
Hi Venkateswararao,
i am able to download robertdebock.tomcat 

for a last try please uninstall python 3.4.3 and install Python 2.7.12 why becoz it is working for me

check below:

ansible@ip-172-31-42-28:~/.ansible$ cd roles/
ansible@ip-172-31-42-28:~/.ansible/roles$ ls
entercloudsuite.mysql  geerlingguy.mysql  robertdebock.tomcat
geerlingguy.java       robertdebock.java
ansible@ip-172-31-42-28:~/.ansible/roles$ ansible --version
ansible 2.7.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
ansible@ip-172-31-42-28:~/.ansible/roles$ python --version
### **Python 2.7.12**
ansible@ip-172-31-42-28:~/.ansible/roles$

**Comment by sivasankardevops** [comment]
hi venkateswararao, 
 the problem is with your ansible version  me also downloaded that role


ansible@ip-172-31-30-181:~$ ansible-galaxy install robertdebock.tomcat
- downloading role 'tomcat', owned by robertdebock

- downloading role from https://github.com/robertdebock/ansible-role-tomcat/archive/2.3.0.tar.gz
- extracting robertdebock.tomcat to /home/ansible/.ansible/roles/robertdebock.tomcat
- robertdebock.tomcat (2.3.0) was installed successfully

ansible@ip-172-31-30-181:~/.ansible/roles$ ansible --version
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
ansible@ip-172-31-30-181:~/.ansible/roles$ python --version
Python 2.7.12

**Comment by santoshkalingwar** [comment]
its is working with ansible 2.7.2 and Python 2.7.12

just now i install that its working fine i install roles first then i write playbook as below please try this

---
- hosts: all
  become: yes
  roles:
    - robertdebock.java

**Comment by VenkateswararaoPaturi** [comment]
issue is with Ansible and Python versions and Ubuntu 14.

it's working fine with Ubuntu 16 and Python 2.7.12 and Ansible 2.7.1
