### ISSUE TITLE
Private git server

### ISSUE THREAD

**Issue by vdileepdevops** [QT-DevOps/DevOpsIssues#283]
hi sir
i want create private git server in my organization,where all developers stores and retrieve their code ,in windows is it possible ?

**Comment by shaikkhajaibrahim** [comment]
https://medium.com/@piteryo7/how-to-set-up-git-server-on-local-network-windows-tutorial-7ec5cd2df3b1

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vdileepdevops** [comment]
thank you sir,
i had configured private git server but i'm not able to see my project files after push the files to server
if i clone the files i'm getting file.
and can do all these operations like clone git from mac if git server is private windows server

**Comment by shaikkhajaibrahim** [comment]
It could have some restrictions. Please read docs or seek community support of git

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vdileepdevops** [comment]
thank you sir
