### ISSUE TITLE
unable to perform bootstrap from workstation

### ISSUE THREAD

**Issue by harimakenti** [QT-DevOps/DevOpsIssues#284]
unable to perform bootstrap from workstation in chef , i tried it many times
1 ) i configured one ec2 machine(chef node)
2)created chef server
3)downloaded startup kit from chef server
4) i installed chefdk also

PS G:\chefpractice\chef-starter\chef-repo> chef --version
Chef Development Kit Version: 3.4.38
chef-client version: 14.6.47
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 3.0.12

PS G:\chefpractice\chef-starter\chef-repo> knife --version
Chef: 14.6.47
PS G:\chefpractice\chef-starter\chef-repo>

4)extracted and copied chef-repo folder into my chef practice directory

PS G:\chefpractice\chef-starter\chef-repo> knife bootstrap FQDN ec2-52-54-144-79.compute-1.amazonaws.com --sudo -x ubuntu -i C:\Users\shivakumar\Desktop\Downloads\chefsetup.pem  -N ip-172-31-21-209.ec2.internal
Node ip-172-31-21-209.ec2.internal exists, overwrite it? (Y/N) y
Client ip-172-31-21-209.ec2.internal exists, overwrite it? (Y/N) y
Creating new client for ip-172-31-21-209.ec2.internal
Creating new node for ip-172-31-21-209.ec2.internal
Connecting to FQDN
#<Thread:0x000000000b157010@C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        10: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
         9: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session_actions.rb:36:in `block (2 levels) in sessions'
         8: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:138:in `session'
         7: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:488:in `next_session'
         6: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:186:in `new_session'
         5: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `start'
         4: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `new'
         3: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:70:in `initialize'
         2: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:631:in `tcp'
         1: from C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:227:in `foreach'
C:/opscode/chefdk/embedded/lib/ruby/2.5.0/socket.rb:227:in `getaddrinfo': getaddrinfo: No such host is known.  (SocketError)
ERROR: Network Error: getaddrinfo: No such host is known.
Check your knife configuration and network settings

**Comment by santoshkalingwar** [comment]
knife  bootstrap  ec2-52-54-144-79.compute-1.amazonaws.com   --sudo  -x ubuntu   -i C:\Users\shivakumar\Desktop\Downloads\chefsetup.pem   -N   ip-172-31-21-209.ec2.internal

pleas do not use word fqdn while bootstraping

**Comment by santoshkalingwar** [comment]
hi hari ,

your using fqdn word in boostraping  that is why that giving error
please use this one may be helps you


knife bootstrap ec2-52-54-144-79.compute-1.amazonaws.com --sudo -x ubuntu -i C:\Users\shivakumar\Desktop\Downloads\chefsetup.pem -N ip-172-31-21-209.ec2.internal
