### ISSUE TITLE
unable to solve issue related bootstrap

### ISSUE THREAD

**Issue by akshith678** [QT-DevOps/DevOpsIssues#286]
knife bootstrap ec2-13-127-149-52.ap-south-1.compute.amazonaws.com --sudo -x u
buntu -i C:\Users\POTHULA AKSHITH\Downloads\cheflab.pem -N ip-172-31-23-87.ap-south-1.compute.internal
Creating new client for ip-172-31-23-87.ap-south-1.compute.internal
Creating new node for ip-172-31-23-87.ap-south-1.compute.internal
Connecting to ec2-13-127-149-52.ap-south-1.compute.amazonaws.com
#<Thread:0x000000000ab19b30@C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        5: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
        4: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session_actions.rb:36:in `block (2 levels) in sessions'
        3: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:138:in `session'
        2: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:488:in `next_session'
        1: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:182:in `new_session'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:194:in `rescue in new_session': Authentication failed for user ubuntu@ec2-13-127-149-52.ap-south-1.compute.amazonaws.com@ec2-13-127-149-52.ap-south-1.compute.amazonaws.com (Net::SSH::AuthenticationFailed)
Failed to authenticate ubuntu - trying password auth
Enter your password:

**Comment by arunkumar127** [comment]
@akshith678 
Mention .pem file path in quotes.

Try this & let me know whether it is working or not.
knife bootstrap ec2-13-127-149-52.ap-south-1.compute.amazonaws.com --sudo -x u
buntu -i 'C:\Users\POTHULA AKSHITH\Downloads\cheflab.pem' -N ip-172-31-23-87.ap-south-1.compute.internal

**Comment by akshith678** [comment]
yes, it worked.
why that has to be in quotes.
thankyou.

**Comment by arunkumar127** [comment]
@akshith678 
Space in the path will be considered as separate arguments.
So make sure your path wont have any spaces. If there is any space in path, mention it in quotes.

Regards
Arun Kumar
