### ISSUE TITLE
How to modify the recipies once upload to chef.manage.io

### ISSUE THREAD

**Issue by saikiranjayanthi** [QT-DevOps/DevOpsIssues#287]
Hi,

I have a couple of questions in manage.chef.io
1.Can i know how to modify the file like default.rb or someother file once if it update to manage.chef.io. let me know if there is any command.
2.If we want to upload a cookbook with the same name in manage.chef.io . How we can delete the cookbook manually or there is any commands to delete

**Comment by santoshkalingwar** [comment]
hello saikiran,

1  you modify default.rb and  change the version in metadata.rb file then you upload to   manage.chef.io
2 if you want to delete the cookbook from managed chef server then run below command
# knife cookbook delete  cookbook_name , here cookbook_name is your generated cookbook name eg: nginx

**Comment by saikiranjayanthi** [comment]
Thanks santhosh
