### ISSUE TITLE
how to install ansible-galaxy  in docker 

### ISSUE THREAD

**Issue by ARSHADBALU** [QT-DevOps/DevOpsIssues#288]
![ansible-galaxy](https://user-images.githubusercontent.com/43450435/49327225-a1922d80-f584-11e8-82bb-0e6089f1af2f.png)
 not working

**Comment by santoshkalingwar** [comment]
that is python or your os issue

it is working in ubuntu 16.04
i just try this

ansible-galaxy install geerlingguy.docker
