### ISSUE TITLE
unable to intall nginx  server in chef

### ISSUE THREAD

**Issue by harimakenti** [QT-DevOps/DevOpsIssues#289]
unable to install nginx in chef, 

my recipe file contents

package 'nginx' do
    action :install
  end

  service 'nginx' do
    action [ :enable, :start ]
  end
  cookbook_file "/usr/share/nginx/www/index.html" do
    source "index.html"
    mode "0644"
  end

PS G:\chefpractice\chef-starter\chef-repo\cookbooks\nginxserver> berks upload
Uploaded nginxserver (0.4.0) to: 'https://api.chef.io/organizations/harimakenti'

ubuntu@ip-172-31-21-209:~$ sudo chef-client
Starting Chef Client, version 14.7.17
resolving cookbooks for run list: ["nginxserver"]
Synchronizing Cookbooks:
  - nginxserver (0.4.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 3 resources
Recipe: nginxserver::default
  * apt_package[nginx] action install (up to date)
  * service[nginx] action enable (up to date)
  * service[nginx] action start

    ================================================================================
    Error executing action `start` on resource 'service[nginx]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /bin/systemctl --system start nginx ----
    STDOUT:
    STDERR: Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
    ---- End output of /bin/systemctl --system start nginx ----
    Ran /bin/systemctl --system start nginx returned 1

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/nginxserver/recipes/default.rb

     11:   service 'nginx' do
     12:     action [ :enable, :start ]
     13:   end
     14:   cookbook_file "/usr/share/nginx/www/index.html" do

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/nginxserver/recipes/default.rb:11:in `from_file'

    service("nginx") do
      action [:enable, :start]
      default_guard_interpreter :default
      service_name "nginx"
      enabled true
      running false
      masked false
      pattern "nginx"
      declared_type :service
      cookbook_name "nginxserver"
      recipe_name "default"
    end

    System Info:
    ------------
    chef_version=14.7.17
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
    program_name=/usr/bin/chef-client
    executable=/opt/chef/bin/chef-client

Running handlers:
[2018-12-02T17:32:16+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-12-02T17:32:16+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 03 seconds
[2018-12-02T17:32:16+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-12-02T17:32:16+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-12-02T17:32:16+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: service[nginx] (nginxserver::default line 11) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /bin/systemctl --system start nginx ----
STDOUT:
STDERR: Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
---- End output of /bin/systemctl --system start nginx ----
Ran /bin/systemctl --system start nginx returned 1

**Comment by santoshkalingwar** [comment]
please check it manually once , is it running or not

**Comment by harimakenti** [comment]
Yes I did its working

**Comment by santoshkalingwar** [comment]
please upload your recipe files , we are unable to understand how you write, is there any syntax or spaces error

**Comment by harimakenti** [comment]
I uploaded recipe already

**Comment by harimakenti** [comment]
See that at the beginning of the issue only ,I hv submitted my recipe that
is default. rb

**Comment by santoshkalingwar** [comment]
https://www.digitalocean.com/community/tutorials/how-to-create-simple-chef-cookbooks-to-manage-infrastructure-on-ubuntu

please above link  will help you to install nginx

it works for me

execute "apt-get update" do
  command "apt-get update"
end
package 'nginx' do
  action :install
end
service 'nginx' do
  action [ :enable, :start ]
end
cookbook_file "/usr/share/nginx/www/index.html" do
  source "index.html"
end

you create file in your cookbooks files folder as index.html
and check location of file where you want to copy that folder is exist of not
