### ISSUE TITLE
am unable to do SSH from git after vagrant up

### ISSUE THREAD

**Issue by kumars2019** [QT-DevOps/DevOpsIssues#290]
am unable to do SSH from git after vagrant up

![image](https://user-images.githubusercontent.com/45548776/49351035-81bf4e80-f6d7-11e8-8b2b-16f742c45d48.png)

**Comment by kumars2019** [comment]
can you please help me , how to fix this issue

**Comment by santoshkalingwar** [comment]
For login in into vagrant command is

vagrant ssh

if this is not fix your issue then please error screenshot

**Comment by kumars2019** [comment]
Thanks for your response santosh....

Below error am getting while doing vagrant up... Please suggest me ..
![image](https://user-images.githubusercontent.com/45548776/49351201-4e30f400-f6d8-11e8-9ca9-4939e8db7b17.png)

**Comment by kumars2019** [comment]
i think might be this is network issue, can you please help me.

![image](https://user-images.githubusercontent.com/45548776/49351338-078fc980-f6d9-11e8-84c5-50cc97755a67.png)

**Comment by santoshkalingwar** [comment]
its showing network issue , did you change anything in vagrant file

please follow the link
https://www.vagrantup.com/docs/networking/public_network.html

**Comment by kumars2019** [comment]
i havent changed any thing in vagrant file.....

and i have same configuration but its not working

[vagrant.log](https://github.com/QT-DevOps/DevOpsIssues/files/2638036/vagrant.log)

[Vagrantfile.txt](https://github.com/QT-DevOps/DevOpsIssues/files/2638040/Vagrantfile.txt)

**Comment by kumars2019** [comment]
i have found one more thing in my machine, my OS is 64bit but ubuntu is installed automatically 32 bit...
maybe this is any reason

**Comment by santoshkalingwar** [comment]
please enable virtualazation in your system  in bios

if you have 64 bit os then you can install 64 bit only

**Comment by kumars2019** [comment]
Yes i have installed, ubuntu/trusty64, but its showing 32bit ubuntu..

**Comment by Santosh-Peddada** [comment]
On seeing timeout error.. this may happens if you have hyper-v and virtual box are running parallel . Ensure hyper -v feature off in appwiz.cpl and try vagrant up
