### ISSUE TITLE
i got error while trying to get kubeadm init

### ISSUE THREAD

**Issue by ramesh44557** [QT-DevOps/DevOpsIssues#292]

**Comment by ramesh44557** [comment]
![capture](https://user-images.githubusercontent.com/44061340/49461215-2ac19280-f819-11e8-9392-65161d19da39.PNG)

**Comment by santoshkalingwar** [comment]
hi,

please check requirement of run this , you are getting this error because of less cpu cores ,you have 1 core cpu , it minimum requires 2 core

**Comment by ramesh44557** [comment]
thank you i will check with that

**Comment by ramesh44557** [comment]
thank you santhosh i have gone with 2 cores 8gb mem its going smooth
