### ISSUE TITLE
bootstraping windows issue

### ISSUE THREAD

**Issue by sumankumarpagadala** [QT-DevOps/DevOpsIssues#293]
Facin an issue while bootstrapping windows machine below is the error

ERROR: Network Error: No connection could be made because the target machine actively refused it. - No connection could be made because the target machine actively refused it. - connect(2) for "192.168.136.27" port 5985 (192.168.136.27:5985)

**Comment by revathi-muthana123** [comment]
pls share your bootstrap command & windows machine details???

**Comment by sumankumarpagadala** [comment]
please close this case, as i would like to wait for end of chef class.

**Comment by BRAHMAREDDYV** [comment]
Hi suman,

Did u got the solution.

**Comment by sumankumarpagadala** [comment]
no but let me wait for end of chef classes.
