### ISSUE TITLE
Can't see .aws file on ~directory after installing awscli in Chef

### ISSUE THREAD

**Issue by KalpanaAddagada** [QT-DevOps/DevOpsIssues#294]
Hi,

I cannot see .aws file in ~directory after intsalling awscli also. I want to create kitchen.yml file.
Can anyone help me please

**Comment by raviops100** [comment]
Hi Kalpana,

If you install AWS CLI in WINDOWS 64-bit OS

basically .aws folder will be available C:\Users\usernameofmachine

but some laptops/machines .aws folder available in the folder name of manufacturer

EXAMPLE: mine is dell laptop it is creating foldername call DELL inside .aws folder is available

 c:\users\DELL\.aws\credentials

Please check once same thing is happening in your machine also

Thanks
Ravi

**Comment by KalpanaAddagada** [comment]
Hi Ravi,

I installed awscli thorugh through command, choco install awscli.
![no aws](https://user-images.githubusercontent.com/42040121/49682052-f2e57400-fad2-11e8-9ec7-e6d3e395c92c.png)
![in c folder also](https://user-images.githubusercontent.com/42040121/49682061-20322200-fad3-11e8-91fb-c787dd3d8ea7.png)

 

I don't find it in c:\users also.
can you let me know if there is any other source.

Thanks
Kalpana

**Comment by raviops100** [comment]
Hi,
try this below link go to windows few oprtions tri it

1. https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
still you are not able filnd .aws folder try below not from choclatey 
2. go to below link

https://docs.aws.amazon.com/cli/latest/userguide/install-windows.html#install-msi-on-windows

select AWS MSI INSTALLER 64-bit install this in your machine

once it is done take poweshell run as adminstrator

execute powershell aws -v command

it should not through any error 

now check .aws folder in C:\Users\usernameofmach
