### ISSUE TITLE
unable execute kitchen converge -l debug command

### ISSUE THREAD

**Issue by harimakenti** [QT-DevOps/DevOpsIssues#295]
unable to execute kitchen converge -l debug command , throwing following errors

1)kitchen.yml

---
driver:
  name: vagrant
  provider: hyperv
  network:
  - ["public_network", bridge: "vagrant"]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
 # - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[lampstack::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

2)i  set environment variables in control panel

VAGRANT_DEFAULT_PROVIDER=hyperv

3)KITCHEN_HYPERV_SWITCH=vagrant

4)made virtual switch
5)executed kitchen converge -l debug

**Comment by raviops100** [comment]
Hi Hari,

Can you please try below kitechel.yml file 
Plase try to launch  single Env on  Ubuntu coomented out CentOS below kitechel.yml file

---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
   - name: ubuntu-16.04
   #- name: centos-7
suites:
  - name: default
    run_list:
      - recipe[helloworld::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
	
once it is done 

go to cookbookfolfer 

execue

berks install

kithen converge

kithen login

once it is done in your cook book folder

you should find out .kirtche folder inside vagrantfile will be available

Thanks
Ravi

**Comment by harimakenti** [comment]
I commented centos
