### ISSUE TITLE
Bootstrap Issue On Readhat EC2 Instance 

### ISSUE THREAD

**Issue by abdulrahimdba** [QT-DevOps/DevOpsIssues#296]
Hi while doing the bootstrap on Redhat Ec2 instance getting below error.

Attached bootstrap script too.

Connecting to ec2-18-188-36-213.us-east-2.compute.amazonaws.com
#<Thread:0x000000000a061b98@C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        5: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
        4: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session_actions.rb:36:in `block (2 levels) in sessions'
        3: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:138:in `session'
        2: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:488:in `next_session'
        1: from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:182:in `new_session'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:194:in `rescue in new_session': Authentication failed for user ec2-user@ec2-18-188-36-213.us-east-2.compute.amazonaws.com@ec2-18-188-36-213.us-east-2.compute.amazonaws.com (Net::SSH::AuthenticationFailed)
Failed to authenticate ec2-user - trying password auth
Enter your password:

knife bootstrap ec2-18-188-36-213.us-east-2.compute.amazonaws.com -x ec2-user -i C:\Users\sar\Desktop\My keys\MyKey.pem --sudo -N Node01

**Comment by arunkumar127** [comment]
@abdulrahimdba 
Refer issue no #286 
Your key path should be in quotes.

Regards
Arun Kumar

**Comment by abdulrahimdba** [comment]
Perfect.. Thanks for you quick turnaround.
please close the issue
