### ISSUE TITLE
Unable to run Ansible playbook

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#298]
Hi Team, 
I had tried this earlier and it worked at that time . Now I am unable to execute the playbook in ansible.
validate the yml file in yml validator. But still getting syntax error.
YML Content : 
---
-hosts: all
 become: yes
 tasks
 -name:installing git
  apt:
   name: git
   state: present
   update_cache: yes

Below is the error:

ansible@ip-172-31-91-15:~/playbook$ ansible-playbook helloworld.yml
ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to have been in '/home/ansible/playbook/helloworld.yml': line 3, column 8, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

-hosts: all
 become: yes
       ^ here

**Comment by arunkumar127** [comment]
@Aamukta
Can you please share screenshot of your playbook. (.yml file)

**Comment by BRAHMAREDDYV** [comment]
Hi aamukta,

-hosts: all
become: yes
^ here

tasks    -  here put a  :  for tasks


Thq

**Comment by Aamukta** [comment]
> Hi aamukta,
> 
> -hosts: all
> become: yes
> ^ here
> 
> tasks - here put a : for tasks
> 
> Thq

Thankyou it worked.. :)
