### ISSUE TITLE
Create Cookbook Erroor Windpws work station

### ISSUE THREAD

**Issue by abdulrahimdba** [QT-DevOps/DevOpsIssues#299]
Hi Team,
When we creating cookbook in getting below error,i have verified in chaef manage its showing let me know  check the below error and suggest the same.
Thanks
Abdul Rahim Syed

-----------------Error-------------
PS D:\Devops\chef-repo> chef generate cookbook project1
Generating cookbook project1
- Ensuring correct cookbook file content
- Committing cookbook files to git

================================================================================
Error executing action `run` on resource 'execute[git-commit-new-files]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '128'
---- Begin output of git commit -m "Add generated cookbook content" ----
STDOUT:
STDERR: *** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'sar@DESKTOP-0N2DDK2.(none)')
---- End output of git commit -m "Add generated cookbook content" ----
Ran git commit -m "Add generated cookbook content" returned 128

Resource Declaration:
---------------------
# In C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-dk-3.5.13/lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb

151:     execute('git-commit-new-files') do
152:       command('git commit -m "Add generated cookbook content"')
153:       cwd cookbook_dir
154:     end
155:   end

Compiled Resource:
------------------
# Declared in C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-dk-3.5.13/lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb:151:in `from_file'

execute("git-commit-new-files") do
  action [:run]
  default_guard_interpreter :execute
  command "git commit -m \"Add generated cookbook content\""
  backup 5
  declared_type :execute
  cookbook_name :code_generator
  recipe_name "cookbook"
  cwd "D:/Devops/chef-repo/project1"
  domain nil
  user nil
end

System Info:
------------
chef_version=14.7.17
ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
program_name=C:/opscode/chefdk/bin/chef
executable=C:/opscode/chefdk/bin/chef

ERROR: Chef failed to converge: execute[git-commit-new-files] (code_generator::cookbook line 151) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '128'
---- Begin output of git commit -m "Add generated cookbook content" ----
STDOUT:
STDERR: *** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'sar@DESKTOP-0N2DDK2.(none)')
---- End output of git commit -m "Add generated cookbook content" ----
Ran git commit -m "Add generated cookbook content" returned 128 from file C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.0-universal-mingw32/lib/mixlib/shellout.rb:297:in `invalid!'
Caused by: (Mixlib::ShellOut::ShellCommandFailed) execute[git-commit-new-files] (code_generator::cookbook line 151) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '128'
---- Begin output of git commit -m "Add generated cookbook content" ----
STDOUT:
STDERR: *** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'sar@DESKTOP-0N2DDK2.(none)')
---- End output of git commit -m "Add generated cookbook content" ----
Ran git commit -m "Add generated cookbook content" returned 128

**Comment by BRAHMAREDDYV** [comment]
Is this solved r not?

Please let other knows abt it

Thq

**Comment by abdulrahimdba** [comment]
Not Solved.

Could you pls give the reference.

Thanks
Abdul Rahim Syed

**Comment by BRAHMAREDDYV** [comment]
Hi rahim,

PS D:\Devops\chef-repo> chef generate cookbook project1

use \chef-repo\cookbooks> , create here and check it again 

Thq

**Comment by abdulrahimdba** [comment]
issue resolved
