### ISSUE TITLE
Auto Scaling Queries

### ISSUE THREAD

**Issue by Kishore-Ram** [QT-DevOps/DevOpsIssues#3]
I have couple of queries in AWS Auto Scaling.
1) While we create launch configuration, minimum instances I have selected is 2 (lets suppose). Now after all creation, 2 instances are created. I have applied auto scaling rules as well (CPU > 60% increase, CPU <10% decrease by 1. I have 3 questions on this.

(a) Suppose I deleted or terminated one instance, the minimum instances defined in Launch Configuration is 2, hence automatically a new instance should be created since the minimum instances is 2. But when I tried, it does not create a new instance.
(b) Due to auto scaling conditions (CPU > 60%) a new instance was created this week and suppose next week the instance gets terminated due to scale down condition (CPU < 10) met. So, now while termination of instance automatically, what happens to data??
(c) I have created a Launch Configuration, and applied Auto scaling with min 2 instances. I haven't installed any app or service. So the CPU remains less than 5% always. But the instances does not gets decremented or terminated even though it meets Scale Down condition (CPU < 10%). So, my question in any case, the minimum instances (2 in this case) will not be disturbed or destroyed. Is that true?

**Comment by sanjaysureshmv** [comment]
(a)Please select your autoscaling group and check the activity history. check for any error occurrence during the creation of the instance.

**Comment by shaikkhajaibrahim** [comment]
As sanjay suggested it should show the history. As it would create the machine when the instance is out of service & health checks have failed. It depends on the health check timings
