### ISSUE TITLE
am not able to validate the json file using packer

### ISSUE THREAD

**Issue by shakirmir** [QT-DevOps/DevOpsIssues#30]
This is my json file and i have started my powershell with admin permissions  and just am trying to validate the json but am getting following error:
command :packer validate .\nginx.json
Error : Failed to initialize build 'amazon-ebs': error initializing builder 'amazon-ebs': Unrecognized remote plugin message: Error starting plugin server: Couldn't bind plugin TCP listener

{
  "builders": [
        {
            "type": "amazon-ebs",
            "access_key": "access-id",
            "secret_key": "pwd",
            "region": "us-east-1",
            "source_ami": "ami-a4dc46db",
            "instance_type": "t2.micro",
            "ssh_username": "ubuntu",
            "ami_name": "packer-nginx"
        }
    ]

        }
    ]
}

**Comment by samjoel777** [comment]
The script isn't right, u can use Visual Studio code for writing json script.
Else use online json validator to see ur script is error free.

**Comment by shakirmir** [comment]
Yes,i m using visual studio code only and the same code is working in my friends system  .

**Comment by SarfrazPNQ** [comment]
Did you install aws cli in your machine ?

**Comment by shaikkhajaibrahim** [comment]
Json is invalid, Please share complete script which you are using. If in your friends system this script which you shared  is working I'm quite sure, he/his system has magical powers 🥇 
![image](https://user-images.githubusercontent.com/2438317/41097185-bbcc6364-6a74-11e8-9603-d046a9393337.png)

**Comment by shakirmir** [comment]
once again ,i started the same procedure from beginning and got the same issue showing the below steps 

![image](https://user-images.githubusercontent.com/39324287/41112924-efae0950-6a45-11e8-86e4-fc35d3c24f6d.png)



issue: unable to validate the json file 
step 1:
nginx.json template

{
    "builders":[
        {
            
                "type": "amazon-ebs",
                "access_key": "access-id",
                "secret_key": "secret-id",
                "region": "us-east-1",
                "source_ami": "ami-a4dc46db",
                "instance_type": "t2.micro",
                "ssh_username": "ubuntu",
                "ami_name": "packer-nginx"
              }
        
    ]
}

step 2:

![image](https://user-images.githubusercontent.com/39324287/41112955-00c0d1aa-6a46-11e8-892c-b3018db07077.png)

PS C:\Windows\system32> packer --version
1.2.4
PS C:\Windows\system32> cd E:\packerzone\may2018\nginx
PS E:\packerzone\may2018\nginx> packer --help
Usage: packer [--version] [--help] <command> [<args>]

Available commands are:
    build       build image(s) from template
    fix         fixes templates from old versions of packer
    inspect     see components of a template
    push        push a template and supporting files to a Packer build service
    validate    check that a template is valid
    version     Prints the Packer version

PS E:\packerzone\may2018\nginx> packer validate .\nginx.json
Failed to initialize build 'amazon-ebs': error initializing builder 'amazon-ebs': Unrecognized remote plugin message: Error starting plugin server: Couldn't bind plugin TCP listener
PS E:\packerzone\may2018\nginx>
