### ISSUE TITLE
Ansible Roles

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#302]
Hi Team,

In Ansible , when we write roles, we install it from galaxy.
At enterprise level, when we want to deploy a role, it shows Geerlingguy.docker etc.
If we dont want to show that the role is copied from galaxy, how can we rename the role?
Example: We dont want to show that it is a geerlingguy role.. How is that possible?

**Comment by santoshkalingwar** [comment]
hi ,

you can install role from ansible galaxy then mv that role into another folder , go to meta file and change the name section

**Comment by raviops100** [comment]
https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names

**Comment by Aamukta** [comment]
OK Thankyou
