### ISSUE TITLE
s3 bucket permission for iam user

### ISSUE THREAD

**Issue by vdileepdevops** [QT-DevOps/DevOpsIssues#306]
Hi Sir,
can i give the s3 bucket or  objects and folders  permissions to aperticular user 

Thank you
Dileep

**Comment by revathi-muthana123** [comment]
yes, we can do

**Comment by vdileepdevops** [comment]
can you give me  details how we can give permissions

**Comment by revathi-muthana123** [comment]
We can do it by using custome Policies (or)
We can write custome policies to give specific permissions to bucket/ objects & then assign those policies to a specific user.
please refer below url:
https://docs.aws.amazon.com/AmazonS3/latest/dev/example-policies-s3.html

**Comment by vdileepdevops** [comment]
thank you so much revathi.

**Comment by vdileepdevops** [comment]
thank you,Revathi
