### ISSUE TITLE
Unable to install Tomcat manually on the ubuntu server.

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#307]
Hi Team,

Unable to install Tomcat manually on the ubuntu server.
I am doing it using Digital Ocean link .
https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-8-on-ubuntu-16-04
Below is the error.

 
ubuntu@ip-172-31-92-115:/tmp$ sudo tar xzvf apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by arunkumar127** [comment]
@Aamukta 
Tomcat tr.gz file mirror links were changed, so link given in above documentation is not working.
You can get gz file links from below link
https://archive.apache.org/dist/tomcat/tomcat-8/

If you want to get Tomcat v8.5.5, use below command
$ **curl -O https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.5/bin/apache-tomcat-8.5.5.tar.gz**
Remaining steps remains same.

If you want other versions, get tar.gz files from above link provided.

Regards
Arun Kumar.

**Comment by santoshkalingwar** [comment]
Please download the tomcat from tomcats official site

**Comment by Aamukta** [comment]
OK.. Thankyou
