### ISSUE TITLE
knife command not woking after installing chefdk

### ISSUE THREAD

**Issue by praveenkbingi** [QT-DevOps/DevOpsIssues#308]
I have installed chefdk in my windows 10 and 2 linux machines, In linux knife command is working and i can get the output but in win10 i am getting following error can you please help me what may be the issue. as i cannot run chef or knife commands.
Error:
"knife : The term 'knife' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1
+ knife -v"

![knife error](https://user-images.githubusercontent.com/42661020/49989695-1e6bd100-ffa1-11e8-91f5-714278f00210.JPG)

**Comment by raviops100** [comment]
Hi Praveen,
 there is no need to add anything for powershell to recognize knife except chef-client. 
After installing the chef-client reopen the powershell window and then try knife commands. That should work for you. There is no need to go to "chef-repo" folder for "knife --version" command. From any folder location that should work.
Thanks
Ravi

**Comment by praveenkbingi** [comment]
Hi Ravi,
 I cannot run chef command, I have rebooted the system after installing chefdk and getting the same error.
I have done some searching and found dependency of dotnet framework I have reinstalled but the issue is same.


Sent from Yahoo Mail for iPhone


On Friday, December 14, 2018, 9:57 PM, raviops100 <notifications@github.com> wrote:


Hi Praveen,
there is no need to add anything for powershell to recognize knife except chef-client.
After installing the chef-client reopen the powershell window and then try knife commands. That should work for you. There is no need to go to "chef-repo" folder for "knife --version" command. From any folder location that should work.
Thanks
Ravi

**Comment by sunil3456** [comment]
hi Praveen 
probably you might be doing something wrong!!
I think you have to do this, get back to chef-repo instead of trying from .chef
and make sure you check your knife.rb current directory.
hope it works
thanks

**Comment by praveenkbingi** [comment]
Hi Sunil,

Tried in all the directories issue is same.

Thank You.

**Comment by shaikkhajaibrahim** [comment]
What's the powershell version & os version

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sunil3456** [comment]
Can you drop your knife.rb path 
Thanks

**Comment by praveenkbingi** [comment]
Hi 
I have installed windows 10 pro , My powershell version.

PS C:\WINDOWS\system32> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.17134.407
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.407
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Thanks & Regards 

Praveen.
--------------------------------------------
On Mon, 17/12/18, shaikkhajaibrahim <notifications@github.com> wrote:

 Subject: Re: [QT-DevOps/DevOpsIssues] knife command not woking after installing chefdk (#308)
 To: "QT-DevOps/DevOpsIssues" <DevOpsIssues@noreply.github.com>
 Cc: "praveenkbingi" <pkbingi@yahoo.co.in>, "Author" <author@noreply.github.com>
 Date: Monday, 17 December, 2018, 8:49 AM
 
 What's the powershell version
 & os version
 
 
 
 Get Outlook for Android<https://aka.ms/ghei36>
 
 
 
 ________________________________

**Comment by praveenkbingi** [comment]
Hi Sunil,

I have extracted chef-starter in c:

PS C:\chef-starter\chef-repo\.chef> dir


    Directory: C:\chef-starter\chef-repo\.chef


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12/13/2018  12:20 PM            416 knife.rb
-a----       12/13/2018  12:20 PM           1674 pkbingi.pem

Thanks& Regards

Praveen
--------------------------------------------
On Mon, 17/12/18, Sunil <notifications@github.com> wrote:

 Subject: Re: [QT-DevOps/DevOpsIssues] knife command not woking after installing chefdk (#308)
 To: "QT-DevOps/DevOpsIssues" <DevOpsIssues@noreply.github.com>
 Cc: "praveenkbingi" <pkbingi@yahoo.co.in>, "Author" <author@noreply.github.com>
 Date: Monday, 17 December, 2018, 8:58 AM
 
 Can you drop your knife.rb path
 
 Thanks
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by sunil3456** [comment]
can you open knife.rb in source code and drop it !! only reason I think is command cant read the knife.rb from your folder, try chef -v. please go through knife.rb if all good then try this commands
In windows command prompt try make sure your inside  .chef, it will show the knife status in Linux and all
Dir C:\*knife* /s
powershell
knife status
knife search '*:*' -I
!!I'm sorry if I mislead you!!
thanks

**Comment by praveenkbingi** [comment]
Hi Sunil,

I have compared the knife.rb and didnt find any issue, I have pasted the the content.

I am doing the configuration and setup with linux nodes as i am comfortable with linux, I also need to know why i am getting the issue in windows.
Can you please help.


##knife.rb file 
# See http://docs.chef.io/config_rb_knife.html for more information on knife configuration options

current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                "pkbingi"
client_key               "#{current_dir}/pkbingi.pem"
chef_server_url          "https://api.chef.io/organizations/chclass1"
cookbook_path            ["#{current_dir}/../cookbooks"]
 
--------------------------------------------
On Mon, 17/12/18, Sunil <notifications@github.com> wrote:

 Subject: Re: [QT-DevOps/DevOpsIssues] knife command not woking after installing chefdk (#308)
 To: "QT-DevOps/DevOpsIssues" <DevOpsIssues@noreply.github.com>
 Cc: "praveenkbingi" <pkbingi@yahoo.co.in>, "Author" <author@noreply.github.com>
 Date: Monday, 17 December, 2018, 12:31 PM
 
 can you open knife.rb in source
 code and drop it !! only reason I think is command cant read
 the knife.rb from your folder. please go through knife.rb if
 all good then try this commands
 
 In windows command prompt try make sure your inside  .chef,
 it will show the knife working status in Linux and all
 
 Dir C:*knife* /s
 
 powershell
 
 knife status
 
 knife search ':' -I
 
 !!I'm sorry if I mislead you!!
 
 thanks
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by sunil3456** [comment]
ok lets get back to basics, I thing you have installed chefdk using choco
try doing upgrade, and then try chef -v

**Comment by santoshkalingwar** [comment]
hi ,
when you run the command as knife or chef it may have path issue please set the path of it below link will help it may be fix your issue
https://blog.chef.io/2014/11/04/the-chefdk-on-windows-survival-guide/

**Comment by shaikkhajaibrahim** [comment]
Is it done

**Comment by praveenkbingi** [comment]
Hi,
Sorry for the late update, there may issue with my windows installation. I have setup  new system working fine 


Sent from Yahoo Mail for iPhone


On Friday, December 21, 2018, 7:25 PM, shaikkhajaibrahim <notifications@github.com> wrote:


Is it done
