### ISSUE TITLE
docker issue 

### ISSUE THREAD

**Issue by ajs777** [QT-DevOps/DevOpsIssues#309]
![screenshot 76](https://user-images.githubusercontent.com/37798362/50001920-723be180-ffc4-11e8-866c-5ddb4209e8ad.png)

**Comment by ajs777** [comment]
when i try to start wordpress iam getting this issue

**Comment by santoshkalingwar** [comment]
Linked container is not up and running that is why this container shows ,container not linking

**Comment by ajs777** [comment]
Thank you santhoshkalinwar garu
