### ISSUE TITLE
IAM Json Policy Issues for EC2 List

### ISSUE THREAD

**Issue by Kishore-Ram** [QT-DevOps/DevOpsIssues#31]
Hi All,

My aim is to create a user (test1), write a policy where in, the test1 user can only view selected instances(based on Tag (key-value) in a particular region (ap-south-1, MUMBAI). I tried with below policies which did not work.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "ec2:Describe*",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/": "prod"  **<== This will filter based on Value=prod instance.**
                }
            }
        }
    ]
}

**Comment by vijaybhaskarreddyy** [comment]
please refer below  link https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_ec2_volumes-instance.html

**Comment by shaikkhajaibrahim** [comment]
Closing the issue
