### ISSUE TITLE
chef server organization identification issue

### ISSUE THREAD

**Issue by raja139** [QT-DevOps/DevOpsIssues#310]
Hi Team,

When i tried to install lamp server with new organization its still pointing old organization. Where i have to update new organization details. 
 
Berks upload:

PS C:\Users\Ganesh\Desktop\ganesg_dev\chef-starter\chef-repo\cookbooks\lamp_new> berks upload
Uploaded lamp_new (0.1.3) to: 'https://api.chef.io/organizations/gani139'
PS C:\Users\Ganesh\Desktop\ganesg_dev\chef-starter\chef-repo\cookbooks\lamp_new>

<img width="865" alt="organization" src="https://user-images.githubusercontent.com/44603973/50044219-1f3a5b00-00a6-11e9-983e-17247fde22fd.PNG">

**Comment by sunil3456** [comment]
you gotta change your organization from top right hand drop down.
thanks

sunil

**Comment by santoshkalingwar** [comment]
you downloaded the startkit of your current organization , that is why cookbooks are uploading in same organization , if you want to change the organization , then create organization and download starterkit of that organization , otherwise change the knife.rb file info

**Comment by revathi-muthana123** [comment]
@raja139 
pls confirm is it fixed?

**Comment by raja139** [comment]
Hi

Issue got fixed.Thank you .

**Comment by revathi-muthana123** [comment]
can you pls close issue?

**Comment by santoshkalingwar** [comment]
please close the issue if you fix it
