### ISSUE TITLE
Kitchen converge issue since 12 hours

### ISSUE THREAD

**Issue by sumankumarpagadala** [QT-DevOps/DevOpsIssues#311]
PS D:\chef-starter\chef-repo\cookbooks\apache9> kitchen converge
-----> Starting Kitchen (v1.23.2)
-----> Creating <default-ubuntu-1604>...
       Bringing machine 'default' up with 'hyperv' provider...
       ==> default: Verifying Hyper-V is enabled...
       ==> default: Verifying Hyper-V is accessible...
       ==> default: Importing a Hyper-V instance
           default: Creating and registering the VM...
           default: Successfully imported VM
           default: Configuring the VM...
       ==> default: Starting the machine...
       ==> default: Waiting for the machine to report its IP address...
           default: Timeout: 120 seconds
           default: IP: 192.168.1.7
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 192.168.1.7:22
           default: SSH username: vagrant
           default: SSH auth method: private key
           default:
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default:
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Setting hostname...
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [SSH] Established
       Vagrant instance <default-ubuntu-1604> created.
       Finished creating <default-ubuntu-1604> (1m31.78s).
-----> Converging <default-ubuntu-1604>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.0.6...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       ubuntu 16.04 x86_64
       Getting information for chef stable  for ubuntu...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=&p=ubuntu&pv=16.04&m=x86_64
         to file /tmp/install.sh.2040/metadata.txt
       trying wget...
       sha1     27aa243ab6a05b70115357ea1e552a381a65dd85
       sha256   cb1f032bc9d0031e12464d7b394901fe340d8e8ef6fe4413e125b9e803b3aaf5
       url      https://packages.chef.io/files/stable/chef/14.8.12/ubuntu/16.04/chef_14.8.12-1_amd64.deb
       version  14.8.12
       downloaded metadata file looks valid...
       downloading https://packages.chef.io/files/stable/chef/14.8.12/ubuntu/16.04/chef_14.8.12-1_amd64.deb
         to file /tmp/install.sh.2040/chef_14.8.12-1_amd64.deb
       trying wget...

**Comment by sunil3456** [comment]
Hi Suman
Can you try doing    kitchen converge -l debug
and copy the stuff, if possible logs file.
thanks

Regards
Sunil

**Comment by sumankumarpagadala** [comment]
Hi sunil,

Issue got resolved.

Thank you
