### ISSUE TITLE
How vm single NIC is handling both private & Public IPs ? is all NICs are support dual stack IPs ?

### ISSUE THREAD

**Issue by azyp** [QT-DevOps/DevOpsIssues#312]

**Comment by shaikkhajaibrahim** [comment]
Read this https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections?toc=%2fazure%2fvirtual-network%2ftoc.json

And close the ticket

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
