### ISSUE TITLE
what is the use of private IP in virtaul N/W?

### ISSUE THREAD

**Issue by azyp** [QT-DevOps/DevOpsIssues#314]
i could noticed that Public IP is being used to access the VM from both On premise N/W and Public N/W,
But not a Private IP, How should Private IP works in vnet ?

**Comment by shaikkhajaibrahim** [comment]
Private ip is required for communication within vnet. In vnet we do private networking & expose it to outside networks using public. In any cloud public network is optional & private network is mandatory

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by azyp** [comment]
Does it use NAT concept [private IP to Public IP] ? and what about
applications inside the VM ?
As some applications are need to have special N/W settings to communicate
with some extra components.

[sorry for delay in posting a query]

**Comment by shaikkhajaibrahim** [comment]
Maintained by azure internally

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
