### ISSUE TITLE
Can you provide us a windows based configuration like LAMP in linux to use Ansible or chef.

### ISSUE THREAD

**Issue by sumankumarpagadala** [QT-DevOps/DevOpsIssues#315]
Can you provide us a windows based configuration like LAMP in linux to use Ansible or chef.

**Comment by sunil3456** [comment]
> WAMP

**Comment by sumankumarpagadala** [comment]
Hi Sunil,

Thanks for your help, but am asking it to write cookbook or playbook for hands on of chef and ansible, not an equivalent of LAMP in windows.

**Comment by sunil3456** [comment]
try WISA
https://learn.chef.io/modules/create-a-web-app-cookbook/windows/virtualbox/configure-iis#/
If not this then I'm not sure what your after.
thanks

**Comment by santoshkalingwar** [comment]
You can try iis server and .net project in Windows

**Comment by sumankumarpagadala** [comment]
Can I get any sample .net code and manual steps to automate.

Regards,
Suman

**Comment by shaikkhajaibrahim** [comment]
Search in GitHub. I would recommend googling

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
