### ISSUE TITLE
Cent os machines are automatically adding to nagios server with out installing nagios plugin, why its adding automatically???

### ISSUE THREAD

**Issue by sumankumarpagadala** [QT-DevOps/DevOpsIssues#316]

**Comment by santoshkalingwar** [comment]
please give detailed information what you did
and what it display

**Comment by sumankumarpagadala** [comment]
i have added my host details in nagios server and its started coming up in nagios console automatically without installing nagios plugin node. attaching screenshot. Do we need install nagios plugin linux nodes to monitor or not.
![capture](https://user-images.githubusercontent.com/45389644/50423663-5d8e0200-087e-11e9-8f54-5442ca812d3e.JPG)

**Comment by sumankumarpagadala** [comment]
Do we need to install nagios plugin in linux nodes or not to monitor.

**Comment by KishoreKrishna** [comment]
Hi Suman,

Not sure if I understood your question, but I'm writing down the info I have below:

--> From the screenshot above, I can see that the host defined is inheriting values from the template 
      linux-server, this template has the default **check_command** value as **check-host-alive**. chech- 
      host-alive is the alias to the command check_ping.

    define host {
    name                              linux-server            
    use                                  generic-host            
    check_period                    24x7                    
    check_interval                        5                       
    retry_interval                          1                       
    max_check_attempts              10                      
    check_command                   check-host-alive            
   --------------------------------------------------  }

    For this reason, you can see the hosts appear in the console.

-->Public services like http and ftp ..... don't require agent installation on the nodes/clients
-->But private attributes like memory, cpu and disk usage require agent installation on nodes.
               Agents: NCPA on windows and NRPE on linux clients/nodes
              And also check_ncpa.py and check_nrpe plugins need to be installed on the nagios core server.

Please see the page for more info:  https://support.nagios.com/kb/article/nrpe-how-to-install-nrpe-v3-from-source-515.html
