### ISSUE TITLE
jenkins

### ISSUE THREAD

**Issue by ramakrishna228** [QT-DevOps/DevOpsIssues#317]
i am installing apache tomcat sever.while startup apache server .   ls -l  command not working
![jenkins](https://user-images.githubusercontent.com/42872074/50403160-5dc8c780-07c2-11e9-9ce4-75640d680ea1.png)

**Comment by raviops100** [comment]
Hi Ramakrishna,

Can you please try to execute  below command to start apachetomcat server from powershell from same location(tomcat/bin)

Start-Process -FilePath ".\startup.bat"

Thanks
Ravi

**Comment by BRAHMAREDDYV** [comment]
Hi Rk,

You are using ls command in powershell, but powershell not act as linux terminal. If u want to use ls command then open git bash terminal and use any command.


Thq

**Comment by santoshkalingwar** [comment]
please run the startup.bat file

**Comment by ramakrishna228** [comment]
Thank you
