### ISSUE TITLE
jenkins

### ISSUE THREAD

**Issue by ramakrishna228** [QT-DevOps/DevOpsIssues#319]
while start up jenkins,i am going to jenkins repository open terrminal at that location and apply command java -jar jenkins.war.but this command not working to start jenkins
![jenkins](https://user-images.githubusercontent.com/42872074/50421019-f3b32f80-0860-11e9-9726-797b7db445b1.png)

**Comment by santoshkalingwar** [comment]
your log is displaying address already used means your system is running any other application on port 8080 please check it

**Comment by raviops100** [comment]
Hi Ramakrishna,

Please execute below command 

where --httpPort should not be 8080 port

java -jar jenkins.war --httpPort=XXXX

Thanks
Ravi
