### ISSUE TITLE
unable to validate json file using packer

### ISSUE THREAD

**Issue by babasmd** [QT-DevOps/DevOpsIssues#32]
![image](https://user-images.githubusercontent.com/39340070/40891366-d1c4470c-67a1-11e8-8d41-88f6f54673cc.png)
when i have given this its showing me the error unexpected end of json input ,so if i missed out something  help me 
![image](https://user-images.githubusercontent.com/39340070/40891381-199cb67c-67a2-11e8-9866-577e976d8994.png)

**Comment by vijaybhaskarreddyy** [comment]
Save That file first and run again.

**Comment by babasmd** [comment]
yes its working
