### ISSUE TITLE
when I am trying to compile mvn it is showing built fail

### ISSUE THREAD

**Issue by kashif-nayeem9** [QT-DevOps/DevOpsIssues#321]
[INFO] ------------------------------------------------------------------------                                                                                                                  [INFO] BUILD FAILURE                                                                                                                                                                             [INFO] ------------------------------------------------------------------------                                                                                                                  [INFO] Total time: 4.219 s                                                                                                                                                                       [INFO] Finished at: 2018-12-26T09:59:36+00:00                                                                                                                                                    [INFO] Final Memory: 26M/62M                                                                                                                                                                     [INFO] ------------------------------------------------------------------------                                                                                                                  [ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.5:revision (default) on project spring-petclinic: Could not complete Mojo execution... java.io.IOException: Unable to  create parent directories of /projects/spring-petclinic/target/classes/git.properties -> [Help 1]                                                                                               [ERROR]                                                                                                                                                                                          [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.                                                                                                              [ERROR] Re-run Maven using the -X switch to enable full debug logging.                                                                                                                           [ERROR]                                                                                                                                                                                          [ERROR] For more information about the errors and possible solutions, please read the following articles:                                                                                        [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
--
![maven issue](https://user-images.githubusercontent.com/44407258/50442257-10fd0200-0924-11e9-9452-021a8741105c.jpg)

**Comment by raviops100** [comment]
Hi can you please share pom.xml file and and what is maven goal you are trying to execute

**Comment by santoshkalingwar** [comment]
please run mvn goals , where is your pom.xml file

**Comment by kashif-nayeem9** [comment]
i am using ec2 ubuntu 1.6 
where to find pom.xml file

now when i am trying mvn --version or any mvn command i am getting this 
ubuntu@ip-172-31-6-90:~/projects$ mvn --version                                  
Error: JAVA_HOME is not defined correctly.               
We cannot execute  /usr/lib/jvm/java-8-openjdk-amd64/bin/java

**Comment by sumankumarpagadala** [comment]
Can u try with "sudo mvn compile"

**Comment by santoshkalingwar** [comment]
Set path for Java and maven in /etc/environment file 
And run command , source /etc/environment 
Then you can do mvn compile

**Comment by kashif-nayeem9** [comment]
> Can u try with "sudo mvn compile"


ubuntu@ip-172-31-6-90:~/projects$ sudo mvn compile                               
Error: JAVA_HOME is not defined correctly.                                         
We cannot execute  /usr/lib/jvm/java-8-openjdk-amd64/bin/java
--

**Comment by kashif-nayeem9** [comment]
> Set path for Java and maven in /etc/environment file
> And run command , source /etc/environment
> Then you can do mvn compile

Yes I have done that but still I am facing this issue

**Comment by santoshkalingwar** [comment]
JAVA_HOME=/usr/lib/jvm/java-openjdk-amd64

Set like this
You set path that is wrong

**Comment by kashif-nayeem9** [comment]
Thank you Santosh, Yeah i was giving the wrong path
Thank you all for helping...
