### ISSUE TITLE
Ansible - Unable to install ansible-galaxy geerlingguy.java

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [QT-DevOps/DevOpsIssues#322]
Hi Friends 
I am not able to install ansible-galaxy install geerlingguy.java to install java on linux machine. 
Details:
# i created a linux vm
# added user : ansible
# did visudo as well 
# changed p/w authentication 
# becoming an ansible user, i am not able to install java using geerlingguy
# 
![untitled364](https://user-images.githubusercontent.com/16450606/50451965-4eca4c80-095d-11e9-9918-3a2ca2c48891.png)

# if error says java already exists, then how can i check it ? i am not able to see it installed anywhere..

Thanks
SajidKhan

**Comment by raviops100** [comment]
Hi Sajid,
Do you have below specific versions of software installed in your machine 
 Ubuntu 16.04
 Python 2.7.12  
 Ansible 2.7.1(or)2.7.2
Thanks
Ravi

**Comment by SajidAliKhanMohammed** [comment]
I will check and let you know Ravi.

Thanks
SajidKhan

**Comment by SajidAliKhanMohammed** [comment]
Hi Ravi..

Unfortunately I terminated the vm as I am unable to install
geerlingguy.java...
Please let me know the steps so that I can try it again..

Thanks
SajidKhan.

**Comment by raviops100** [comment]
Hi Sajid,
Can you try same command with --ignore-errors

**Comment by SajidAliKhanMohammed** [comment]
Hi Ravi
I already used the command like this : ansible-galaxy --ignore-errors
install geerlingguy.java,
so got that error. Is this the right way to use the command ?

Thanks
SajidKhan.

**Comment by BRAHMAREDDYV** [comment]
Hi Sajid,

Use --force, if exist it will forcefully install(override) 

Thq 
VBReddy

**Comment by SajidAliKhanMohammed** [comment]
Hi Brahma Reddy & Ravi
As a root user i am able to install geerlingguy.java and idealista.tomcat-role successfully, but unable to install the same as an ansible user

Thanks 
SajidKhan

**Comment by BRAHMAREDDYV** [comment]
Hi Sajid,

are you add ansible user as root under visudo 

Thq
VBReddy

**Comment by SajidAliKhanMohammed** [comment]
Yes Brahma Reddy I added ansible user in visudo file as ansible ALL=(ALL:ALL) NOPASSWD: ALL

Thanks
SajidKhan

**Comment by bhaskardegala** [comment]
Try using jdk --version it will give you the information about java version

**Comment by sohailfaizan** [comment]
try this,
ansible-galaxy install --force geerlingguy.java

**Comment by SajidAliKhanMohammed** [comment]
Ok sure
Thanks..
