### ISSUE TITLE
metric beat template communicate to elasticsearch

### ISSUE THREAD

**Issue by pravin-07** [QT-DevOps/DevOpsIssues#323]
![metric beat issues](https://user-images.githubusercontent.com/39874060/50458564-fb222800-0989-11e9-8319-6e441ed158ed.png)

when i was communicating with elasticsearch this type problem is occuured..all ports are open and also i have given the private ip address of elasticsearch

**Comment by raviops100** [comment]
Hi Pravin,
Please go throguh below link 
https://www.elastic.co/guide/en/beats/metricbeat/5.1/metricbeat-starting.html
Thanks 
Ravikumar
