### ISSUE TITLE
Export powershell output to excel file

### ISSUE THREAD

**Issue by NikhilBhoga** [QT-DevOps/DevOpsIssues#325]
Get-AzureRMResource | format-table

How to export the above output in excel sheet where the data should be in a proper table format unlike getting data in one cell.

**Comment by raviops100** [comment]
Hi Nikhil,
Please follow below link it helps to resolve your query 
https://dailydotnettips.com/export-the-list-of-azure-resources-to-excel/
Thanks 
Ravi

**Comment by NikhilBhoga** [comment]
Thank you it's working
