### ISSUE TITLE
Docker OOM issue

### ISSUE THREAD

**Issue by Nreddy2020** [QT-DevOps/DevOpsIssues#326]
Recently i was facing the problem with Docker outofmemory issue when starting the docker.
i have changed the memory from 2048 to 1024 also but still i was facing the memory issue.
My lapy ram is 3GB. let me know the best resolution for this issue.
![docker memory issue](https://user-images.githubusercontent.com/44947790/50502335-85e74d80-0a84-11e9-9670-12a1bd0a966f.PNG)

**Comment by santoshkalingwar** [comment]
please send the detailed information

**Comment by santoshkalingwar** [comment]
Docker OOM issue mean heap memory issue in java below like will help you please go through this
https://stackoverflow.com/questions/17369522/set-default-heap-size-in-windows

**Comment by Nreddy2020** [comment]
this is the error i was facing when i am starting the Docker in windows
![image](https://user-images.githubusercontent.com/44947790/50517192-12216100-0ad5-11e9-934b-c386de6eae0f.png)

**Comment by raviops100** [comment]
Hi 
The screen shot you have shared 
Reduce the CPU silde
And increase memory 30000
Swap keep it same then try to launch container 
thanks 
Ravi
