### ISSUE TITLE
its a doubt which is running in my mind about chef

### ISSUE THREAD

**Issue by sumankumarpagadala** [QT-DevOps/DevOpsIssues#327]
i have 100 nodes having chef client with scheduled job to run chef client periodically, so i would like to run chef client before the scheduled time or date, how can i do that instead of running chef-client manually in every node.

**Comment by BRAHMAREDDYV** [comment]
Hi Suman,

default the chef-client runs every 30 mins automatically. If u want to change the time, u can.

Thq
VBReddy

**Comment by sumankumarpagadala** [comment]
I know that if I set to run once In a month and I want to change that to 15
days what would I do.

**Comment by sumankumarpagadala** [comment]
Do I need wait for 1 month for node to execute chef-client.

**Comment by shaikkhajaibrahim** [comment]
Why don't you use chef client super market cookbook   to change chef client parameters as discussed in class

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by shaikkhajaibrahim** [comment]
Integrate this with roles and environments

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sumankumarpagadala** [comment]
Okay, if I integrate this with rules and environments, do i need to wait
for node to converge or is there any other way.

**Comment by santoshkalingwar** [comment]
you need to wait for converge

**Comment by shaikkhajaibrahim** [comment]
You can define convergence period as attribute & change it in roles/ environment

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sumankumarpagadala** [comment]
HI Sir,

what will happens when the chef-client converges 2nd time, after a successful cookbook execution at 1st convergence.

1. will "chef-client" execute cookbook again or ignore the execution of cookbook??

~Suman

**Comment by santoshkalingwar** [comment]
if your cookbook is same then it will skip the steps

**Comment by sumankumarpagadala** [comment]
If my cookbook has some commands??

~suman

**Comment by sunil3456** [comment]
knife ssh "role:app" "sudo chef-client" -x myuser -p 22
Please go through this links
https://docs.chef.io/knife_ssh.html
https://docs.chef.io/knife_search.html

### Do you know how to bootstrap 100 nodes in one go!! Any idea###
Thanks

**Comment by shaikkhajaibrahim** [comment]
Unattended bootstrap

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sunil3456** [comment]
Thanks Khaja
