### ISSUE TITLE
Doubt on Chef Default

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#328]
Why do we use Default in Attributes of Chef?
I think it was covered in class but I missed it. 
Where do we use Default and Node?

**Comment by raviops100** [comment]
Hi,
Please go to below link 
https://docs.chef.io/attributes.html
in this link a topic call AttributeTypes

**Comment by santoshkalingwar** [comment]
please go through below link

https://docs.chef.io/attributes.html

**Comment by Aamukta** [comment]
Thankyou.. got it
