### ISSUE TITLE
MAVEN issue

### ISSUE THREAD

**Issue by charan417** [QT-DevOps/DevOpsIssues#329]
after doing mvn compile,test and package when iam trying to run the open mrs jar file using java -jar,the following issue arose.Could u check and tell me what the issue is?

root@ip-172-31-16-204:~/projects/openmrs-core# ls
CONTRIBUTING.md  NOTICE.md  api                          checkstyle.xml        license-header.txt  ruleset.xml  test   web
LICENSE          README.md  checkstyle-suppressions.xml  findbugs-include.xml  pom.xml             target       tools  webapp
root@ip-172-31-16-204:~/projects/openmrs-core# cd target/
root@ip-172-31-16-204:~/projects/openmrs-core/target# ls
maven-archiver  openmrs-2.2.0-SNAPSHOT-tests.jar
root@ip-172-31-16-204:~/projects/openmrs-core/target# java -jar openmrs-2.2.0-SNAPSHOT-tests.jar
no main manifest attribute, in openmrs-2.2.0-SNAPSHOT-tests.jar
root@ip-172-31-16-204:~/projects/openmrs-core/target#

**Comment by raviops100** [comment]
Hi,
Please follow below link
https://www.baeldung.com/java-jar-executable-manifest-main-class
