### ISSUE TITLE
Error:unknown root level key:configure Terraform 

### ISSUE THREAD

**Issue by chittalalk** [QT-DevOps/DevOpsIssues#33]
Hello Everyone.
Iam trying to execute command terranform init before validate command but it given the error like "unknown root level key:configure"
Could you please help me out for the same
![error terraform](https://user-images.githubusercontent.com/39190912/40957232-c50a1b16-68b1-11e8-8863-f59d38bffa06.PNG)

**Comment by vijaybhaskarreddyy** [comment]
Check your code or attach code screen shot

**Comment by SarfrazPNQ** [comment]
You have to pass directory as input. Can you try giving => terraform init .

**Comment by chittalalk** [comment]
Configure the AWS Provider
provider "aws" {
  access_key = "###############"
  secret_key = "######################"
  region     = "ap-south-1"
}
resource "aws_instance" "web"{
ami ="ami-####"
instance_type="t2.micro"

tags{
    Name="Hello world"
}

}
Same problem happing with linux m/c also

**Comment by cnuchowdary** [comment]
Please update your terraform version with following command  (choco upgrade terraform)after update re-open PowerShell and must save your file with .tf extension and now start with terraform init maybe it will helpful for you

**Comment by shashank370** [comment]
you have to check your path(directory) and execute command  --         terraform init .

**Comment by sanjaysureshmv** [comment]
can you list all the files in your terraform directory and its contents. basically executing ls -al and cat *
Also , execute grep -irl "configure"  . from your terraform directory and paste the output

**Comment by shaikkhajaibrahim** [comment]
Alsor refer this https://github.com/hashicorp/terraform/issues/14224
