### ISSUE TITLE
knife boot strap issue by using local chef server

### ISSUE THREAD

**Issue by sumankumarpagadala** [QT-DevOps/DevOpsIssues#330]
**Sucessfully bootstraping by usin hosted chef server:**

PS D:\Devops\Configuration manager-CHEF AND ANSIBLE\chef-starter\chef-repo\.chef> knife bootstrap 192.168.1.8 -x root -P p@55w0rd -N jenkins
Creating new client for jenkins

Creating new node for jenkins

Connecting to 192.168.1.8

192.168.1.8 -----> Existing Chef installation detected
192.168.1.8 Starting the first Chef Client run...

192.168.1.8 Starting Chef Client, version 14.8.12

192.168.1.8 resolving cookbooks for run list: []

192.168.1.8 Synchronizing Cookbooks:
192.168.1.8 Installing Cookbook Gems:
192.168.1.8 Compiling Cookbooks...
192.168.1.8 [2018-12-29T01:50:31+05:30] WARN: Node jenkins has an empty run list.

192.168.1.8 Converging 0 resources

192.168.1.8
192.168.1.8 Running handlers:
192.168.1.8 Running handlers complete
192.168.1.8 Chef Client finished, 0/0 resources updated in 07 seconds

PS D:\Devops\Configuration manager-CHEF AND ANSIBLE\chef-starter\chef-repo\.chef> cd ''
PS D:\Devops\Configuration manager-CHEF AND ANSIBLE\chef-starter\chef-repo\.chef> cd 'C:\Users\spagadala\Downloads\chef-starter\chef-repo\.chef\trusted_certs'

**Error while try to bootstrap using local chef server:**

PS C:\Users\spagadala\Downloads\chef-starter\chef-repo\.chef\trusted_certs> knife bootstrap 192.168.1.8 -x root -P p@55w0rd -N jenkins
Node jenkins exists, overwrite it? (Y/N)
y
Client jenkins exists, overwrite it? (Y/N)
y
Creating new client for jenkins

Creating new node for jenkins
Connecting to 192.168.1.8

192.168.1.8 -----> Existing Chef installation detected
192.168.1.8 Starting the first Chef Client run...

192.168.1.8 Starting Chef Client, version 14.8.12

192.168.1.8 [2018-12-29T01:52:06+05:30] ERROR: SSL Validation failure connecting to host: chef.lab.com - SSL_connect returned=1 errno=0 state=error: certificate verify failed (error number 1)
192.168.1.8
192.168.1.8 ================================================================================
192.168.1.8 Chef encountered an error attempting to load the node data for "jenkins"
192.168.1.8 ================================================================================
192.168.1.8
192.168.1.8 Unexpected Error:
192.168.1.8 -----------------
192.168.1.8 OpenSSL::SSL::SSLError: SSL Error connecting to https://chef.lab.com/organizations/cheflab/nodes/jenkins - SSL_connect returned=1 errno=0 state=error: certificate verify failed (error number 1)
192.168.1.8
192.168.1.8 System Info:
192.168.1.8 ------------
192.168.1.8 chef_version=14.8.12
192.168.1.8 ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
192.168.1.8 p
rogram_name=/usr/bin/chef-client
192.168.1.8 executable=/opt/chef/bin/chef-client
192.168.1.8
192.168.1.8
192.168.1.8 Running handlers:
192.168.1.8 [2018-12-29T01:52:06+05:30] ERROR: Running exception handlers
192.168.1.8 Running handlers complete
192.168.1.8 [2018-12-29T01:52:06+05:30] ERROR: Exception handlers complete
192.168.1.8 Chef Client failed. 0 resources updated in 01 seconds
192.168.1.8 [2018-12-29T01:52:06+05:30] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
192.168.1.8 [2018-12-29T01:52:06+05:30] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
192.168.1.8 [2018-12-29T01:52:06+05:30] FATAL: OpenSSL::SSL::SSLError: SSL Error connecting to https://chef.lab.com/organizations/cheflab/nodes/jenkins - SSL_connect returned=1 errno=0 state=error: certificate verify failed (error number 1)

**Comment by sumankumarpagadala** [comment]
successfully Imported the certificate by using command "knife ssl fetch"
successfully ran this command also"knife client list"
 but still getting the above error

**Comment by santoshkalingwar** [comment]
hi, 
this may be help you to get ssl certificate 

https://www.thegeekstuff.com/2016/06/knife-ssl-check-fetch/

**Comment by sumankumarpagadala** [comment]
Hi Santosh,

Thanks for your help, but i have added host file entries in node as well as
chef server and able to fetch certificate able to open chef using FQDN but
still am getting error. Below are the screenshots.


[image: image.png]

[image: image.png]

[image: image.png]

[image: image.png]

~Suman

**Comment by santoshkalingwar** [comment]
please bootstrap your node without  certificate validation

**Comment by sumankumarpagadala** [comment]
again an error

[image: image.png]

**Comment by sumankumarpagadala** [comment]
Help me to resolve this issue.


PS C:\Users\spagadala\Downloads\chef-starter\chef-repo\.chef> knife bootstrap 192.168.1.16 -x root -P p@55w0rd -N chef-node --node-ssl-verify-mode none
Creating new client for chef-node

Creating new node for chef-node
Connecting to 192.168.1.16

192.168.1.16 -----> Existing Chef installation detected
192.168.1.16 Starting the first Chef Client run...

192.168.1.16 Starting Chef Client, version 14.8.12

192.168.1.16
192.168.1.16 ================================================================================
192.168.1.16 Chef encountered an error attempting to load the node data for "chef-node"
192.168.1.16 ================================================================================
192.168.1.16
192.168.1.16 Unexpected Error:
192.168.1.16 -----------------
192.168.1.16 NoMethodError: undefined method `key?' for #<String:0x000000000568e1d8>
192.168.1.16
192.168.1.16 System Info:
192.168.1.16 ------------
192.168.1.16 chef_version=14.8.12
192.168.1.16 ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
192.168.1.16 program_name=/usr/bin/chef-client
192.168.1.16 executable=/opt/chef/bin/chef-client
192.168.1.16
192.168.1.16
192.168.1.16 Running handlers:
192.168.1.16 [2019-01-02T20:35:22+05:30] ERROR: Running exception handlers
192.168.1.16 Running handlers complete
192.168.1.
16 [2019-01-02T20:35:22+05:30] ERROR: Exception handlers complete
192.168.1.16 Chef Client failed. 0 resources updated in 06 seconds
192.168.1.16 [2019-01-02T20:35:22+05:30] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
192.168.1.16 [2019-01-02T20:35:22+05:30] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
192.168.1.16 [2019-01-02T20:35:22+05:30] FATAL: NoMethodError: undefined method `key?' for #<String:0x000000000568e1d8>

**Comment by sumankumarpagadala** [comment]
issue got resolved, thank you
