### ISSUE TITLE
unable to use sudo command

### ISSUE THREAD

**Issue by pravin-07** [QT-DevOps/DevOpsIssues#331]
sudo cat /etc/sudoers
>>> /etc/sudoers: syntax error near line 27 <<<
sudo: parse error in /etc/sudoers near line 27
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy pluginsudo 
>>> /etc/sudoers: syntax error near line 27 <<<
sudo: parse error in /etc/sudoers near line 27
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin

**Comment by santoshkalingwar** [comment]
please check your syntax in visudo file

you made some mistake in sudoer file please fix it

**Comment by raviops100** [comment]
Hi pravin,
execute below commands from root user
Pkexec chmod 440 /etc/sudeors
Pkexec chmod 775 /etc/sudoers.d
Perfect child 440  /etc/soders.d/README
Thanks 
Ravi

**Comment by pravin-07** [comment]
sudo -i
>>> /etc/sudoers: syntax error near line 27 <<<
sudo: parse error in /etc/sudoers near line 27
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin

> 
> 
> Hi pravin,
> execute below commands fr

**Comment by pravin-07** [comment]
> 
> 
> Hi pravin,
> execute below commands from root user
> Pkexec chmod 440 /etc/sudeors
> Pkexec chmod 775 /etc/sudoers.d
> Perfect child 440 /etc/soders.d/README
> Thanks
> Ravi
thats the problem i m unable to login with root user let see below

sudo -i
>>> /etc/sudoers: syntax error near line 27 <<<
sudo: parse error in /etc/sudoers near line 27
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin

**Comment by pravin-07** [comment]
> 
> 
> > Hi pravin,
> > execute below commands from root user
> > Pkexec chmod 440 /etc/sudeors
> > Pkexec chmod 775 /etc/sudoers.d
> > Perfect child 440 /etc/soders.d/README
> > Thanks
> > Ravi
> > thats the problem i m unable to login with root user let see below
> 
> sudo -i
> 
> > > > /etc/sudoers: syntax error near line 27 <<<
> > > > sudo: parse error in /etc/sudoers near line 27
> > > > sudo: no valid sudoers sources found, quitting
> > > > sudo: unable to initialize policy plugin

![sudo error](https://user-images.githubusercontent.com/39874060/50559518-3e7bee00-0d1e-11e9-985d-5bc9b0ec6fd0.png)
