### ISSUE TITLE
Error: JAVA_HOME is not defined correctly.

### ISSUE THREAD

**Issue by charan417** [QT-DevOps/DevOpsIssues#332]
When i build the project from jenkins iam getting the error.i didnot get what the issue is.

my ENVIRONMENT VARIABLES
root@ip-172-31-30-62:~# cat /etc/environment
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java/bin/java"
M2_HOME="/usr/share/maven"

CONSOLE OUTPUT IN JENKINS
Started by user admin123
Building in workspace /var/lib/jenkins/workspace/daybuild
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/charan417/spring-petclinic.git # timeout=10
Fetching upstream changes from https://github.com/charan417/spring-petclinic.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/charan417/spring-petclinic.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/Dev^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/Dev^{commit} # timeout=10
Checking out Revision ab567242851166983e5f0140ab7593fd04c7d365 (refs/remotes/origin/Dev)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ab567242851166983e5f0140ab7593fd04c7d365
Commit message: "Remove redundant component scan filter"
 > git rev-list --no-walk ab567242851166983e5f0140ab7593fd04c7d365 # timeout=10
****[daybuild] $ mvn package
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java/bin/java
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE****

**Comment by BRAHMAREDDYV** [comment]
Hi Charan,

Did u check what is inside this path /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java/bin/java

JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java/bin/java"

Here u r setting java Path not JAVA_HOME 

Java Path is different JAVA_HOME is different 

JAVA_HOME is, Where is ur java installed folder. That is JAVA_HOME

Java Path, Where is ur jdk binary(bin) files that is ur java Path 

So, check ur JAVA_HOME 

Is ur JAVA_HOME  r java path




Thq 
VBReddy

**Comment by charan417** [comment]
root@ip-172-31-30-62:/usr/lib/jvm/java-8-openjdk-amd64# cat /etc/environment
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
M2_HOME="/usr/share/maven"
root@ip-172-31-30-62:/usr/lib/jvm/java-8-openjdk-amd64#
same error

**Comment by charan417** [comment]
Started by user admin123
Building in workspace /var/lib/jenkins/workspace/daybuild
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/charan417/spring-petclinic.git # timeout=10
Fetching upstream changes from https://github.com/charan417/spring-petclinic.git
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/charan417/spring-petclinic.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/Dev^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/Dev^{commit} # timeout=10
Checking out Revision ab567242851166983e5f0140ab7593fd04c7d365 (refs/remotes/origin/Dev)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ab567242851166983e5f0140ab7593fd04c7d365
Commit message: "Remove redundant component scan filter"
First time build. Skipping changelog.
[daybuild] $ mvn package
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java/bin/java/bin/java
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE

**Comment by BRAHMAREDDYV** [comment]
Hi Charan,

After u set the JAVA_HOME  in /etc/environment, What is ur next command 

Tell me

Thq 
VBReddy

**Comment by charan417** [comment]
source /etc/environment

**Comment by BRAHMAREDDYV** [comment]
After u run source /etc/environment, logout and login again from the machine. Bcz of some times not set after this (source /etc/environment).

After login update ur packages( apt update)

**Comment by charan417** [comment]
Iam getting the same error even after doing this

**Comment by BRAHMAREDDYV** [comment]
can u check 

echo $JAVA_HOME 

if u get output then u done 

else 

ur process was wrong from installation
Please make sure if u get error again 

Install jdk again

Thq
VBReddy

**Comment by santoshkalingwar** [comment]
please set env as 

JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
MAVEN_HOME="/usr/share/maven"

run command 
 # source /etc/environment
then you check your variable is set properly or not

if your setting jenkins job then no need to give maven goal as mvn package just you give the package in maven goal section

**Comment by charan417** [comment]
will try installing one more time .I have already done twice.Let me do this one more time

**Comment by charan417** [comment]
Thanx for u r responses

**Comment by sunil3456** [comment]
Hi Charan
Can you check you security group. You need to open port 8080 and 22
Thanks

**Comment by charan417** [comment]
at last done 
Thanx guys

**Comment by baisachinna** [comment]
Hi, 

I am getting a similar error, Can someone help.

root@ip-172-31-39-125:~# echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64/bin/
root@ip-172-31-39-125:~# mvn -version
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
root@ip-172-31-39-125:~# source /etc/environment
root@ip-172-31-39-125:~# mvn -version
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
