### ISSUE TITLE
DOCKER ISSUE

### ISSUE THREAD

**Issue by charan417** [QT-DevOps/DevOpsIssues#333]
FROM ubuntu
RUN apt-get update
RUN apt-get install apache2 -y
RUN apt-get install iputils-ping -y
EXPOSE 80
RUN echo hello from docker >> /var/www/html/index.html
CMD ["ping", "google.com"]
THIS IS MY DOCKER FILE.WHEN I TRY TO START THE SERVICE APACHE2 IT SHOWS THE BELOW ERROT

root@0ffab9c903fb:/# service apache2 start
 * Starting Apache httpd web server apache2                                                                                   /usr/sbin/apache2ctl: 99: ulimit: error setting limit (Operation not permitted)
Setting ulimit failed. See README.Debian for more information.
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message

**Comment by santoshkalingwar** [comment]
hi,
please run the below command

#sudo service apache2 start
 
https://stackoverflow.com/questions/15916197/apache2-wont-start-ulimit-error

**Comment by BRAHMAREDDYV** [comment]
Hi Charan,

Did u get the solution. Please we know abt it.

Thq
BReddy

**Comment by charan417** [comment]
hi  bro,
Yes its working.Thanks for resolving my issue.
