### ISSUE TITLE
Jenkins Server Sync

### ISSUE THREAD

**Issue by vsaisatya21** [QT-DevOps/DevOpsIssues#334]
![jenkins master](https://user-images.githubusercontent.com/38434922/50629241-c69e0580-0f61-11e9-8f6b-5ac99012c50d.PNG)
![jenkins](https://user-images.githubusercontent.com/38434922/50629243-c7369c00-0f61-11e9-9378-3f336d9a0644.PNG)

 sir, I getting problem with my jenkins server. While I'm creating the projects in Jenkins those are not synching to my Jenkins Machine . Can you please guide me to resolve this issue.

**Comment by santoshkalingwar** [comment]
please check your console log it will display where is target file and your war package

otherwise please send me the jobs console log

**Comment by santoshkalingwar** [comment]
please send us detailed log

**Comment by vsaisatya21** [comment]
where to find console logs bhayya

**Comment by vsaisatya21** [comment]
[Daybuild-gol #2 Console output.pdf](https://github.com/QT-DevOps/DevOpsIssues/files/2723691/Daybuild-gol.2.Console.output.pdf)

**Comment by santoshkalingwar** [comment]
/var/lib/jenkins/workspace/Daybuild-gol/gameoflifeweb/target/gameoflife.war

above location you have your war file

**Comment by vsaisatya21** [comment]
yha! I know  that but my projects(Workspace) are not shown in my  ubuntu machine

**Comment by vsaisatya21** [comment]
thank you i got it bhayya
