### ISSUE TITLE
git bash is logging off often

### ISSUE THREAD

**Issue by kashif-nayeem9** [QT-DevOps/DevOpsIssues#336]
Hello sir,
when I am using git bash for aws ec2 ubuntu 16 machine and I have installed jenkins in it with open jdk-8 
I am automatically logging off 4 - 5 times in an hour, is it because I am using t2 micro or am i doing any other mistake ??

Thank you

**Comment by BRAHMAREDDYV** [comment]
Hi kashif,

If u leave the git bash terminal session for few mins then it'll automatically log-off without our involvement.

The
VBReddy
