### ISSUE TITLE
DevOps interviews

### ISSUE THREAD

**Issue by saireddy224** [QT-DevOps/DevOpsIssues#337]
Any one attending DevOps interviews

**Comment by charan417** [comment]
no

**Comment by sunil3456** [comment]
If your then be prepare yourself, here are some of collections in word doc, it might help you all.
https://github.com/sunil3456/Devops-interview-questions

All the best bud

**Comment by charan417** [comment]
tq

**Comment by manikanta35** [comment]
Thank you Sunil for sharing this document to us..

**Comment by sunil3456** [comment]
Noworries guys
All the best
