### ISSUE TITLE
jenkins- master-slave configuration-windows node not conneting

### ISSUE THREAD

**Issue by Lokeswararao** [QT-DevOps/DevOpsIssues#338]
hi,
while am trying to connect windows node from jenkins, not able to connect. It is showing Connection timeout error.
Please help me on tis..

And i have done the below settings also
Control Panel\System and Security\Windows Defender Firewall\Customize Settings\Private networkseetings\

Turn-off Defender firewall off in both public and private

then i have tried..even thogh im getting same issue

![image](https://user-images.githubusercontent.com/26164550/50805973-b51a7c00-131a-11e9-964c-5ec5467c5ead.png)

![image](https://user-images.githubusercontent.com/26164550/50805527-d712ff00-1318-11e9-83a3-159bad262b43.png)

_Originally posted by @Lokeswararao in https://github.com/QT-DevOps/DevOpsIssues/issue_comments#issuecomment-452150490_

**Comment by sunil3456** [comment]
Hi Lokeswararao
Looks like your slave is windows
Have you changed TCP port to random which is in global security
and while launching node/slave change Launch method to "launch agent via java web start"
Thanks

**Comment by Lokeswararao** [comment]
Yes, i have updated already those two also..even though im getting same issue...

![image](https://user-images.githubusercontent.com/26164550/50807714-602e3400-1321-11e9-9f72-1474f8f6553d.png)

![image](https://user-images.githubusercontent.com/26164550/50807862-05490c80-1322-11e9-970b-ad75f57d3216.png)

**Comment by sunil3456** [comment]
Change your ip address to public while your copying agent.jar file link and make sure your agent.jar is in the "Devops recorded videos" folder and do not close powershell untill you finish your job. All good now
Thanks

**Comment by praveen1461996** [comment]
did you solved the issue?

**Comment by Lokeswararao** [comment]
need to check on the above scenarios. Will update you tomorrow..

**Comment by Lokeswararao** [comment]
Hi Praveen,
plz let me know how to change into public and where to change with screen shots.

Regards,
Lokesh

**Comment by praveen1461996** [comment]
while configuring agent.jar your  ip 34.220.227.157 may be private ,change it with your jenkins public ip
