### ISSUE TITLE
ansibel

### ISSUE THREAD

**Issue by sunnydevops** [QT-DevOps/DevOpsIssues#34]
I am trying to create playbook to deploy python web application, but when after installing postgresql  i am trying to switch as a postgresql  to create database  it is giving some error.
![postgresql](https://user-images.githubusercontent.com/31772526/40972146-6c9e6096-68dd-11e8-8eff-7c2d13e3e737.PNG)

And my tasks to install postgresql ans switch as a postgresql.
![playbook](https://user-images.githubusercontent.com/31772526/40972299-e2edfa36-68dd-11e8-8db2-cb3b0ab5a3c2.PNG)

**Comment by vijaybhaskarreddyy** [comment]
Cross check that (become_user) postgres is existing or not.

**Comment by shaikkhajaibrahim** [comment]
Resolved??

**Comment by sunnydevops** [comment]
No still giving the same error.

**Comment by shaikkhajaibrahim** [comment]
Can you list all the users in the system & share the screenshot. Also attach your playbook completely

**Comment by sunnydevops** [comment]
unfortunately, my  AWS account has been blocked , so i will recreate the account and then i will give you the list of users and screenshot along with my playbook

**Comment by shaikkhajaibrahim** [comment]
ok

**Comment by shaikkhajaibrahim** [comment]
Are you able to close or shall i close this
