### ISSUE TITLE
How to create a local kubernetes cluster in one or two vm's

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [QT-DevOps/DevOpsIssues#340]
Hi Friends..
Can anyone help me out in creating a local kubernetes cluster in one or two vm's ?

Thanks
SajidKhan

**Comment by praveen1461996** [comment]
hi ,

please follow below documentation , it will helps you

https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

**Comment by SajidAliKhanMohammed** [comment]
Thanks Praveen, got it.
