### ISSUE TITLE
getting error  "msg": "Destination /etc not writable" while trying to create nfs server client setup with ansible.

### ISSUE THREAD

**Issue by sagarbaratam** [QT-DevOps/DevOpsIssues#342]
This is my play book

--- 
- 
  become_user: root
  hosts: all
  tasks: 
    - 
      name: "Install NFS packages"
      tags: "nfs_client,nfs_server"
      yum: "name=nfs-utils state=installed"
    - 
      name: "copy /etc/exports"
      tags: "nfs_server, copy_export"
      template: "src=templates/exports.j2 dest=/etc/exports owner=root group=root mode=755"
    - 
      name: "start the nfs service"
      service: "name=nfs state=restarted enabled=yes"
      tags: nfs_server
    - 
      file: "path={{nfs_mnt}} state=directory mode=755 owner=root"
      name: "create a mount point for nfs"
      tags: nfs_client
    - 
      mount: "name={{nfs_mnt}} src={{nfsserver}}:/{{nfsexport}} fstype=nfs opts=defaults,rw,bg dump=0 passno=2 state=mounted"
      name: "update fstab & mount share"
      tags: nfs_client
  vars: 
    nfs_mnt: /mountshare
    nfsexport: /exportshare
    nfsserver: "172.31.30.92"

This is my exports.j2 file

/exportshare  172.31.16.88 (rw,sync,no_root_squash)

below is the verbose output of playbook

[ec2-user@ip-172-31-30-92 ~]$ ansible-playbook -vv nfs1.yml -t nfs_server -l nfs_server
ansible-playbook 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.15 (default, Nov 28 2018, 22:38:08) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
/etc/ansible/hosts did not meet host_list requirements, check plugin documentation if this is unexpected
/etc/ansible/hosts did not meet script requirements, check plugin documentation if this is unexpected

PLAYBOOK: nfs1.yml *****************************************************************************************************************************************************************************
1 plays in nfs1.yml

PLAY [all] *************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************
task path: /home/ec2-user/nfs1.yml:3
ok: [172.31.30.92]
META: ran handlers

TASK [Install NFS packages] ********************************************************************************************************************************************************************
task path: /home/ec2-user/nfs1.yml:7
ok: [172.31.30.92] => {"changed": false, "msg": "", "rc": 0, "results": ["1:nfs-utils-1.3.0-0.21.amzn1.x86_64 providing nfs-utils is already installed"]}

TASK [copy /etc/exports] ***********************************************************************************************************************************************************************
task path: /home/ec2-user/nfs1.yml:11
fatal: [172.31.30.92]: FAILED! => {"changed": false, "checksum": "6d518bae1e5b54b7c442fbd53a1fffc88fd71364", "msg": "Destination /etc not writable"}
        to retry, use: --limit @/home/ec2-user/nfs1.retry

PLAY RECAP *************************************************************************************************************************************************************************************
172.31.30.92               : ok=2    changed=0    unreachable=0    failed=1

[ec2-user@ip-172-31-30-92 ~]$

**Comment by santoshkalingwar** [comment]
please give write permission to /etc/ folder

**Comment by bhaskardegala** [comment]
Try using mode=0755
And try to give full path for "nfs_mnt"
