### ISSUE TITLE
Unable to copy paste kubeadm cluster commands in virtual box vm

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [QT-DevOps/DevOpsIssues#343]
Hi Friends

i created a vm in virtual box, its running successfully, but unable to run kubernetes kubeadm cluster commands in that vm, as i am not able to see the Copy - Paste options enabled in the vm terminal, tried several attempts but in vain. Also changed options like Host to Guest, Bidirectional in Settings in Advanced. 

Any other alternative way to run kube cluster commands ? 

Atleast wanted to create a vm using Vagrant, but getting failed, though followed exact steps, downloaded vagrant boxes as well..

Thanks
SajidKhan

**Comment by Santosh-Peddada** [comment]
Hi Sajid 
For flexible usage of VM thats created from vagrant
use Powershee(from foler where you have vagrant file)--> vagrant ssh (or) do ssh <VM IP> from git bash.
Please share vagrant file if you are seeing issues in creating VM
