### ISSUE TITLE
Unable to open Jenkins UI for Jenkins server installed in RHEL 7.6

### ISSUE THREAD

**Issue by manikantap1243** [QT-DevOps/DevOpsIssues#344]
Hello Sir,

I have installed java open jdk in RHEL 7.6 (AWS) and jenkins as well, restarted jenkins service. But unable to open the jenkins home page in my laptop browser. Ports all opened. set the environmental variable also.

**Comment by santoshkalingwar** [comment]
please check jenkins service is running or not, then open 8080 port no in security group
