### ISSUE TITLE
unable to connect jenkins via virtualbox

### ISSUE THREAD

**Issue by kashif-nayeem9** [QT-DevOps/DevOpsIssues#345]
Hello sir,

I have install centOS via vagrant (Oracle VM VirtualBox)
install jdk, jenkins (done with environment variable JAVA_HOME)
but when I am connecting ip address (ip a) with 8080 I am not getting connected

Started Jenkins server and set it to run at boot time
(sudo systemctl start jenkins.service)
Allow access to Jenkins via 8080 port  
(sudo firewall-cmd --zone=public --permanent --add-port=8080/tcp)

![virtualbox_myfirstvm_default_1546961549920_78538_17_01_2019_02_16_19](https://user-images.githubusercontent.com/44407258/51277795-a90b7a00-19fe-11e9-9c34-b5d3be34a5be.png)

**Comment by santoshkalingwar** [comment]
please do the port forwarding in  .vagrantfile , or do public networking then

**Comment by revathi-muthana123** [comment]
Have u verified status of the service? Is it active & running ?

**Comment by kashif-nayeem9** [comment]
Hello guys
sorry for the late reply
@santoshkalingwar how to do port forwarding 
I search on google 
https://www.vagrantup.com/docs/networking/basic_usage.html
unable to understand 

@revathi-muthana123 
status is active (exited)

**Comment by ghost** [comment]
in vagrantfile enable public ip and give ip address
