### ISSUE TITLE
ISSUE WITH MAVEN

### ISSUE THREAD

**Issue by charan417** [QT-DevOps/DevOpsIssues#346]
hello,
Iam to build a pipeline where from git,the project is build and it should  be deployed on to tomcat8.
I came across this error which i could not solve.could some one let me know what the issue is?

![screenshot 489](https://user-images.githubusercontent.com/39755715/51398118-be9cb300-1b68-11e9-8f9a-f88cdb5d2e83.png)
![screenshot 490](https://user-images.githubusercontent.com/39755715/51398134-ca887500-1b68-11e9-993a-2b7f1771a11a.png)

**Comment by santoshkalingwar** [comment]
this  is may be with your maven  goal , please first check your project is manually build or not

**Comment by charan417** [comment]
i gave clean package as my maven goals

**Comment by santoshkalingwar** [comment]
run your project manually first if it is build successfully then you go for jenkins

**Comment by ghost** [comment]
if run manually successfully  ur settings are wrong
