### ISSUE TITLE
issue with pm2

### ISSUE THREAD

**Issue by ghost** [QT-DevOps/DevOpsIssues#347]
I was installed node js 10.15.0 using supermarket and after install pm2 manually I get an error like this

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/pm2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by santoshkalingwar** [comment]
please provide us detailed information or detailed log because  i am not able to understand where is the exact issue

**Comment by ghost** [comment]
are you doing this

**Comment by ghost** [comment]
node version 10.15.0

**Comment by ghost** [comment]
ubuntu 16.04

**Comment by ghost** [comment]
if you have done successfully
I will try
