### ISSUE TITLE
unable to login Azure Sql DB using Azure Data studio & SSMS.

### ISSUE THREAD

**Issue by azyp** [QT-DevOps/DevOpsIssues#348]
I had created Azure Sql DB via portal and create server level firewall rule to access the DB from on premises.
i am getting an error while accessing DB using  Azure DB studio and SSMS.Attached are the error screenshots.

**Comment by shaikkhajaibrahim** [comment]
Can you share your firewall rules

**Comment by azyp** [comment]
Attached are the FW rules & error screenshots.

**Comment by azyp** [comment]
![image](https://user-images.githubusercontent.com/45029679/51913603-d8b07e00-2411-11e9-9b46-de06c30b862f.png)

**Comment by azyp** [comment]
azure data studio access error

**Comment by shaikkhajaibrahim** [comment]
Firewall rules??

**Comment by azyp** [comment]
![fw-rues](https://user-images.githubusercontent.com/45029679/51913843-6f7d3a80-2412-11e9-8ecb-5f0325eee221.JPG)
FW rules

**Comment by azyp** [comment]
I had fix the issue, now i can access Azure DB using SSMS & Azure Data studio.
