### ISSUE TITLE
Version increment in Jenkins build

### ISSUE THREAD

**Issue by raghuvadde** [QT-DevOps/DevOpsIssues#349]
Suppose for first build we have java1.0 any changes in code the next build we have to increase the code like java1.1

**Comment by shaikkhajaibrahim** [comment]
Refer https://wiki.jenkins.io/plugins/servlet/mobile?contentId=38928617#content/view/38928617


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by raghuvadde** [comment]
Hi Sir,
please check below commands i attached,here after completion of npm install it will skipped

[‎23-‎01-‎2019 11:41] Reddy, Lakshma: 
cd "<C:\Program Files (x86)\Jenkins\workspace\Stratus_windows_build>"
npm install 
cd "<C:\Program Files (x86)\Jenkins\workspace\Stratus_windows_build\app>"
npm version patch
cd "<C:\Program Files (x86)\Jenkins\workspace\Stratus_windows_build>"
npm run package
