### ISSUE TITLE
Building the packer on azure failed.

### ISSUE THREAD

**Issue by gvharikrishna** [QT-DevOps/DevOpsIssues#35]
==> azure-arm: Running builder ...
    azure-arm: Creating Azure Resource Manager (ARM) client ...
    azure-arm: temp admin user: 'packer'
    azure-arm: temp admin password: 'KwvlZseFM0L10dcgsXlY05jjSKC36rSh'
==> azure-arm: Creating resource group ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-9dkkdz441m'
==> azure-arm:  -> Location          : 'East US'
==> azure-arm:  -> Tags              :
==> azure-arm:  ->> dept : Engineering
==> azure-arm:  ->> task : Image deployment
==> azure-arm: Pausing after run of step 'StepCreateResourceGroup'. Press enter to continue.
==> azure-arm: Validating deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-9dkkdz441m'
==> azure-arm:  -> DeploymentName    : 'pkrdp9dkkdz441m'
==> azure-arm: Pausing after run of step 'StepValidateTemplate'. Press enter to continue.
==> azure-arm: Deploying deployment template ...
==> azure-arm:  -> ResourceGroupName : 'packer-Resource-Group-9dkkdz441m'
==> azure-arm:  -> DeploymentName    : 'pkrdp9dkkdz441m'
==> azure-arm: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Lo
ng running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment
operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
==> azure-arm: Pausing before cleanup of step 'StepValidateTemplate'. Press enter to continue.
==> azure-arm: Pausing before cleanup of step 'StepCreateResourceGroup'. Press enter to continue.
==> azure-arm:
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' errored: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Origin
al Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource  deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usa
ge details."

==> Some builds didn't complete successfully and had errors:
--> azure-arm: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment
operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."

==> Builds finished but no artifacts were created.

**Comment by shaikkhajaibrahim** [comment]
I want to see your configuration.

**Comment by shaikkhajaibrahim** [comment]
I will be moving the issue to closed as there is no response
