### ISSUE TITLE
How to Dockerize the nginx application installed through chef?

### ISSUE THREAD

**Issue by SaiSrikanth10** [QT-DevOps/DevOpsIssues#352]
I have installed nginx in my aws ubuntu through chef and it is running good. Now I want to create a docker image for the above application and run that in docker container. I have tried to create dockerfile with SCRATCH as base image but 0 KB image has created. Please suggest.

**Contents of my dockerfile:**
--------------------------------------
FROM scratch
CMD service nginx start
EXPOSE 80

**Comment by shaikkhajaibrahim** [comment]
Please go through docker image creation as discussed in class once again. Your image has nothing present to be started

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SaiSrikanth10** [comment]
Sir,
I have created nginx image by writing dockerfile. 
But, In docker IS THERE ANY WAY to run an already installed nginx.
I mean to say I have installed nginx in aws and I want to run THAT (installed) in my docker container.

**Comment by praveen1461996** [comment]
docker image is mandatory to create a docker container

**Comment by revathi-muthana123** [comment]
Hi srikanth,

If u installed nginx already then why do you want docker image?

**Comment by SaiSrikanth10** [comment]
Actually, I have installed nginx through chef in Ubuntu (AWS-ec2 instance). I have got the requirement to dockerize the whole solution and need to upload in dockerhub. So I am just asking is there any way to dockerize the above solution so that other person can pull and use this image?

**Comment by revathi-muthana123** [comment]
To my knowledge, Docker container is an isolated executable area, means there won't be any relation b/n one application & other application. So if u want to dockerize ur application first u need to be install then start the service.

**Comment by shaikkhajaibrahim** [comment]
If you install on Linux how it will be part of container. Write a docker file for nginx
