### ISSUE TITLE
Terraform Backend Issue

### ISSUE THREAD

**Issue by charan417** [QT-DevOps/DevOpsIssues#357]
![screenshot 505](https://user-images.githubusercontent.com/39755715/52058596-cce9c680-258d-11e9-9492-21e80584dd4b.png)

**Comment by charan417** [comment]
could some one tell me what the issue is?

**Comment by praveen1461996** [comment]
make sure that your access key and secret key is valid or not

**Comment by santoshkalingwar** [comment]
you need to write  terraform section also


terraform {
    backend "s3"{
        bucket = "${var.statestoragelocations3}"
        key = "${var.statestoragekey}"
    }
}



please go through the directdevops.blog

https://directdevops.blog/2019/01/27/terraform-backends/

**Comment by charan417** [comment]
Done with this error thanks for replying back
