### ISSUE TITLE
Git not found error in jenkins

### ISSUE THREAD

**Issue by chandanabandla** [QT-DevOps/DevOpsIssues#358]
Hi sir
![git not found error](https://user-images.githubusercontent.com/43385196/52190151-761d0f00-2863-11e9-859d-86975b76ad10.PNG)
,
I am getting git : not found error even after configuring git path in global tool configuration.
Please help. I am able to do the same cloning and packaging using command line but not able to execute on jenkins.

**Comment by munesh-reddy** [comment]
Log in to jenkins account, and check whether git is available, by using which git.
If not, install git.

**Comment by santoshkalingwar** [comment]
please install the git in your server and manually check it is working or not if it is working then you can do it with jenkins

**Comment by chandanabandla** [comment]
As i mentioned, it is working fine if i do it manually in command line.

**Comment by munesh-reddy** [comment]
You might have messed up in giving correct path.

Unix System, example: /usr/bin/git.

Windows System example C:/Program Files (x86)/Git/bin/git.exe. 
Do not forget to include ‘.exe’ extension

Note: Make sure not to include any white space at the end of your path.

**Comment by chandanabandla** [comment]
![git](https://user-images.githubusercontent.com/43385196/52338304-0a3bd180-2a30-11e9-913a-6be406e499d3.PNG)
![jenkins](https://user-images.githubusercontent.com/43385196/52338314-0f008580-2a30-11e9-8e6e-7bd09f981728.PNG)
I have done the same thing. Still getting the error

**Comment by munesh-reddy** [comment]
Please add   #!/bin/sh line into your "Execute shell" Build step.

By default Jenkins take /bin/sh -xe and this means -x will print each and every command. And the other option -e, which causes shell to stop running a script immediately when any command exits with non-zero (when any command fails) exit code.

So by adding the #!/bin/sh will allow you to execute with no option.

**Comment by chandanabandla** [comment]
Tried adding #!/bin/sh. No luck. Still getting the same error.

**Comment by munesh-reddy** [comment]
Please post your script here.

In rare circumstances, you may not have the proper SSH access to a repository.

You should ensure that the SSH key you are using is attached to your GitHub user account. You can check this by typing the following into the command line:

ssh -T git@github.com
Hi username! You've successfully authenticated, but GitHub does not
provide shell access.

**Comment by santoshkalingwar** [comment]
please share your jenkins log for that job and attach jenkins job configuration how you configure
