### ISSUE TITLE
unable to assign public ip to ec2 through cloudformation

### ISSUE THREAD

**Issue by rameshkocherla** [QT-DevOps/DevOpsIssues#359]
ERROR:: Network interfaces and an instance-level security groups may not be specified on the same request
--
"webServer": {
            "Type": "AWS::EC2::Instance",
            "Properties": {
                "KeyName": "ChefKey",
                "ImageId": "ami-0d773a3b7bb2bb1c1",
                "InstanceType": "t2.micro",
                "SecurityGroupIds": [
                    "sg-0820d174031bef59e"
                ],
                "NetworkInterfaces": [
                    {
                        "SubnetId": {
                            "Ref": "subnet1"
                        },
                        "AssociatePublicIpAddress": "true",
                        "DeviceIndex": "0"
                    }
                ],
                "Tags": [
                    {
                        "Key": "Name",
                        "Value": "WebServer"
                    }
                ]
            }
        }

**Comment by praveen1461996** [comment]
security group id could be represented in networkinterfaces as "GroupSet": ["sg-id"]

**Comment by rameshkocherla** [comment]
finally got it.thank you.
