### ISSUE TITLE
Maven - 404 Error 

### ISSUE THREAD

**Issue by raj32935** [QT-DevOps/DevOpsIssues#36]
ubuntu@ip-172-31-35-30:~$ wget http://ftp.wayne.edu/apache/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.zip
--2018-06-06 06:32:34--  http://ftp.wayne.edu/apache/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.zip
Resolving ftp.wayne.edu (ftp.wayne.edu)... 141.217.0.199
Connecting to ftp.wayne.edu (ftp.wayne.edu)|141.217.0.199|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-06-06 06:32:34 ERROR 404: Not Found.

I have been trying to wget maven and seems like file not found on the server and unable to find the correct link to download maven. Could you please help me in getting the correct link.
Thanks,
Raj

**Comment by veerendradevops** [comment]
try with one of the below links, it's working

http://www-us.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz
or
http://www-us.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.zip

**Comment by raj32935** [comment]
Hi Veerandra ,

Thanks for your reply. still it doesn't work

ubuntu@ip-172-31-35-30:/opt$ sudo wget http://www-us.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz
--2018-06-06 08:08:23--  http://www-us.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz
Resolving www-us.apache.org (www-us.apache.org)... 40.79.78.1
Connecting to www-us.apache.org (www-us.apache.org)|40.79.78.1|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8799579 (8.4M) [application/x-gzip]
Saving to: ‘apache-maven-3.5.3-bin.tar.gz’

apache-maven-3.5.3-bin.tar.gz                   100%[=======================================================================================================>]   8.39M  19.6MB/s    in 0.4s

2018-06-06 08:08:23 (19.6 MB/s) - ‘apache-maven-3.5.3-bin.tar.gz’ saved [8799579/8799579]

ubuntu@ip-172-31-35-30:/opt$ ls
apache-maven-3.5.3-bin.tar.gz
ubuntu@ip-172-31-35-30:/opt$ sudo tar -xvzf apache-maven-3.5.3-bin.tar.gz
apache-maven-3.5.3/README.txt
apache-maven-3.5.3/LICENSE
apache-maven-3.5.3/NOTICE
apache-maven-3.5.3/lib/
apache-maven-3.5.3/lib/cdi-api.license
apache-maven-3.5.3/lib/commons-cli.license
apache-maven-3.5.3/lib/commons-io.license
apache-maven-3.5.3/lib/commons-lang3.license
apache-maven-3.5.3/lib/jcl-over-slf4j.license
apache-maven-3.5.3/lib/jsr250-api.license
apache-maven-3.5.3/lib/maven-artifact.license
apache-maven-3.5.3/lib/maven-builder-support.license
apache-maven-3.5.3/lib/maven-compat.license
apache-maven-3.5.3/lib/maven-core.license
apache-maven-3.5.3/lib/maven-embedder.license
apache-maven-3.5.3/lib/maven-model-builder.license
apache-maven-3.5.3/lib/maven-model.license
apache-maven-3.5.3/lib/maven-plugin-api.license
apache-maven-3.5.3/lib/maven-repository-metadata.license
apache-maven-3.5.3/lib/maven-resolver-api.license
apache-maven-3.5.3/lib/maven-resolver-connector-basic.license
apache-maven-3.5.3/lib/maven-resolver-impl.license
apache-maven-3.5.3/lib/maven-resolver-provider.license
apache-maven-3.5.3/lib/maven-resolver-spi.license
apache-maven-3.5.3/lib/maven-resolver-transport-wagon.license
apache-maven-3.5.3/lib/maven-resolver-util.license
apache-maven-3.5.3/lib/maven-settings-builder.license
apache-maven-3.5.3/lib/maven-settings.license
apache-maven-3.5.3/lib/maven-shared-utils.license
apache-maven-3.5.3/lib/maven-slf4j-provider.license
apache-maven-3.5.3/lib/org.eclipse.sisu.inject.license
apache-maven-3.5.3/lib/org.eclipse.sisu.plexus.license
apache-maven-3.5.3/lib/plexus-cipher.license
apache-maven-3.5.3/lib/plexus-component-annotations.license
apache-maven-3.5.3/lib/plexus-interpolation.license
apache-maven-3.5.3/lib/plexus-sec-dispatcher.license
apache-maven-3.5.3/lib/plexus-utils.license
apache-maven-3.5.3/lib/slf4j-api.license
apache-maven-3.5.3/lib/wagon-file.license
apache-maven-3.5.3/lib/wagon-http.license
apache-maven-3.5.3/lib/wagon-provider-api.license
apache-maven-3.5.3/lib/jansi-native/
apache-maven-3.5.3/lib/jansi-native/freebsd32/
apache-maven-3.5.3/lib/jansi-native/freebsd64/
apache-maven-3.5.3/lib/jansi-native/linux32/
apache-maven-3.5.3/lib/jansi-native/linux64/
apache-maven-3.5.3/lib/jansi-native/osx/
apache-maven-3.5.3/lib/jansi-native/windows32/
apache-maven-3.5.3/lib/jansi-native/windows64/
apache-maven-3.5.3/lib/jansi-native/freebsd32/libjansi.so
apache-maven-3.5.3/lib/jansi-native/freebsd64/libjansi.so
apache-maven-3.5.3/lib/jansi-native/linux32/libjansi.so
apache-maven-3.5.3/lib/jansi-native/linux64/libjansi.so
apache-maven-3.5.3/lib/jansi-native/osx/libjansi.jnilib
apache-maven-3.5.3/lib/jansi-native/windows32/jansi.dll
apache-maven-3.5.3/lib/jansi-native/windows64/jansi.dll
apache-maven-3.5.3/bin/m2.conf
apache-maven-3.5.3/bin/mvn.cmd
apache-maven-3.5.3/bin/mvnDebug.cmd
apache-maven-3.5.3/bin/mvn
apache-maven-3.5.3/bin/mvnDebug
apache-maven-3.5.3/bin/mvnyjp
apache-maven-3.5.3/conf/
apache-maven-3.5.3/conf/logging/
apache-maven-3.5.3/conf/logging/simplelogger.properties
apache-maven-3.5.3/conf/settings.xml
apache-maven-3.5.3/conf/toolchains.xml
apache-maven-3.5.3/lib/ext/
apache-maven-3.5.3/lib/jansi-native/
apache-maven-3.5.3/lib/ext/README.txt
apache-maven-3.5.3/lib/jansi-native/README.txt
apache-maven-3.5.3/boot/plexus-classworlds-2.5.2.jar
apache-maven-3.5.3/lib/maven-embedder-3.5.3.jar
apache-maven-3.5.3/lib/maven-settings-3.5.3.jar
apache-maven-3.5.3/lib/plexus-utils-3.1.0.jar
apache-maven-3.5.3/lib/maven-settings-builder-3.5.3.jar
apache-maven-3.5.3/lib/maven-builder-support-3.5.3.jar
apache-maven-3.5.3/lib/commons-lang3-3.5.jar
apache-maven-3.5.3/lib/plexus-interpolation-1.24.jar
apache-maven-3.5.3/lib/plexus-component-annotations-1.7.1.jar
apache-maven-3.5.3/lib/plexus-sec-dispatcher-1.4.jar
apache-maven-3.5.3/lib/plexus-cipher-1.7.jar
apache-maven-3.5.3/lib/maven-core-3.5.3.jar
apache-maven-3.5.3/lib/maven-model-3.5.3.jar
apache-maven-3.5.3/lib/maven-repository-metadata-3.5.3.jar
apache-maven-3.5.3/lib/maven-artifact-3.5.3.jar
apache-maven-3.5.3/lib/maven-plugin-api-3.5.3.jar
apache-maven-3.5.3/lib/org.eclipse.sisu.plexus-0.3.3.jar
apache-maven-3.5.3/lib/cdi-api-1.0.jar
apache-maven-3.5.3/lib/jsr250-api-1.0.jar
apache-maven-3.5.3/lib/javax.inject-1.jar
apache-maven-3.5.3/lib/org.eclipse.sisu.inject-0.3.3.jar
apache-maven-3.5.3/lib/maven-model-builder-3.5.3.jar
apache-maven-3.5.3/lib/guava-20.0.jar
apache-maven-3.5.3/lib/maven-resolver-provider-3.5.3.jar
apache-maven-3.5.3/lib/maven-resolver-api-1.1.1.jar
apache-maven-3.5.3/lib/maven-resolver-spi-1.1.1.jar
apache-maven-3.5.3/lib/maven-resolver-util-1.1.1.jar
apache-maven-3.5.3/lib/maven-resolver-impl-1.1.1.jar
apache-maven-3.5.3/lib/maven-shared-utils-3.2.1.jar
apache-maven-3.5.3/lib/commons-io-2.5.jar
apache-maven-3.5.3/lib/guice-4.0-no_aop.jar
apache-maven-3.5.3/lib/aopalliance-1.0.jar
apache-maven-3.5.3/lib/slf4j-api-1.7.25.jar
apache-maven-3.5.3/lib/commons-cli-1.4.jar
apache-maven-3.5.3/lib/maven-compat-3.5.3.jar
apache-maven-3.5.3/lib/wagon-provider-api-3.0.0.jar
apache-maven-3.5.3/lib/wagon-http-3.0.0-shaded.jar
apache-maven-3.5.3/lib/jcl-over-slf4j-1.7.25.jar
apache-maven-3.5.3/lib/wagon-file-3.0.0.jar
apache-maven-3.5.3/lib/maven-resolver-connector-basic-1.1.1.jar
apache-maven-3.5.3/lib/maven-resolver-transport-wagon-1.1.1.jar
apache-maven-3.5.3/lib/maven-slf4j-provider-3.5.3.jar
apache-maven-3.5.3/lib/jansi-1.17.jar
ubuntu@ip-172-31-35-30:/opt$ ls
apache-maven-3.5.3  apache-maven-3.5.3-bin.tar.gz
ubuntu@ip-172-31-35-30:/opt$ cd ..
ubuntu@ip-172-31-35-30:/$ mvn -version
The program 'mvn' is currently not installed. You can install it by typing:
sudo apt install maven

**Comment by vijaybhaskarreddyy** [comment]
Set those maven path variables follow the document.

**Comment by shaikkhajaibrahim** [comment]
I had googled d  the maven download 
![image](https://user-images.githubusercontent.com/2438317/41034712-18e1ef1a-69a8-11e8-9601-3c4c45d01e60.png)

From the above image i copied the link. The command is working now with this
 wget http://mirror.reverse.net/pub/apache/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz

please google the installation atleast for hyper links

**Comment by raj32935** [comment]
Thank you now it works , I have googled it so many times from yesterday but no luck and sorry for thr trouble.
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T19:49:05Z)
Maven home: /opt/apache-maven-3.5.3
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-1060-aws", arch: "amd64", family: "unix"
