### ISSUE TITLE
Nginx-Dockerfile

### ISSUE THREAD

**Issue by vamsi1670** [QT-DevOps/DevOpsIssues#360]
Hi Sir,
I have attempted to complete this issue but facing error, please suggest me any solution.
Use Case:
Write a docker file to launch a webpage in nginx. 
i have manually installed nginx and changed the index.html file as required & launched a webpage in Ubuntu 16.04. this is successful.
The same task i am doing by writing a docker file.How do i change the custom" index.html file" (as per our requirement) in a docker file.

Please suggest me any solution.

**Comment by munesh-reddy** [comment]
Nginx container is set up by default to look for an index page at /usr/share/nginx/html, so in our new Docker container, we need to give it access to our files at that location.
In your docker container copy the directory which has index.html  to /usr/share/nginx/html.

**Comment by santoshkalingwar** [comment]
you can create index.html in docker server then copy it in container in nginx document root

**Comment by vamsi1670** [comment]
Hi Santosh 
I have created an index.html file and copied the same to docker container ,but not successful.
can you please let me know if it can be done specific folder.

**Comment by munesh-reddy** [comment]
COPY <directory of your index.html>  /usr/share/nginx/html 

(/usr/share/nginx/html ) is nginx default  index.html location

I tried with below simple Dockerfile

FROM nginx                                                                     
COPY myhtml /usr/share/nginx/html
WORKDIR /usr/share/nginx/html

**Comment by santoshkalingwar** [comment]
yes that is correct path but 

you use 

COPY sourece deestination

**Comment by vamsi1670** [comment]
sure i will try and let you know.

**Comment by vamsi1670** [comment]
Now the docker file is corrected & done thank you.
