### ISSUE TITLE
SonarQube

### ISSUE THREAD

**Issue by charan417** [QT-DevOps/DevOpsIssues#361]
When Iam trying to start soanrqube its starting and running for a while and exiting immediately
Could some one tell me what the issue is? the logs are attached below
![screenshot 506](https://user-images.githubusercontent.com/39755715/52420150-7f360680-2b17-11e9-9eb6-66aea0106eb2.png)

**Comment by munesh-reddy** [comment]
Some other process might be running on same port number.

Check the list of running processes. On Linux you can use netstat -ntlp | grep :<portnumber> to find what's running on port
Once you have identified what else is using port 9000 there are several solution paths:

Kill that process
Change the configuration of the other process or SonarQube to use a different port

**Comment by charan417** [comment]
there are no proccess running on port 9000.there is only one process
running on port 22...

**Comment by santoshkalingwar** [comment]
please provide detailed log we are not able to understand exact issue
