### ISSUE TITLE
Game of life on Azure vm 

### ISSUE THREAD

**Issue by hari856** [QT-DevOps/DevOpsIssues#362]
How upload the game of life war file on Azure and get the url to move the war file onto tomcat/webapps in linux .

Thanks in advance
Hari

**Comment by CHARANJAI** [comment]
Hi Mr.Hari,
Please go through Below link.
[https://docs.microsoft.com/en-in/azure/app-service/app-service-web-get-started-java](url) .
Thanks 
Charan Jai

**Comment by santoshkalingwar** [comment]
where do you have the war file , if it has url then use wget command in linux , 

if you have war file in local machine then copy it with using scp command

**Comment by revathi-muthana123** [comment]
Be specific about requirement.
If you want to deploy war file through CI/CD server follow the below steps.
1. Create a vm in azure with public ip.
2. Install git, maven & jenkins on vm then build 
   Gameoflife projec by configuring git url in jenkins.
3. Artifacts can be generated 
4. Push those artifacts to artifactory/s3 bucket
5. Install tomcat, by default u will get webapps folder
6. Download that war file into webapps by using wget command
7. Access that with ip address

**Comment by hari856** [comment]
> Hi Mr.Hari,
> Please go through Below link.
> [https://docs.microsoft.com/en-in/azure/app-service/app-service-web-get-started-java](url) .
> Thanks
> Charan Jai

Thank you Charan

**Comment by hari856** [comment]
> Be specific about requirement.
> If you want to deploy war file through CI/CD server follow the below steps.
> 
> 1. Create a vm in azure with public ip.
> 2. Install git, maven & jenkins on vm then build
>    Gameoflife projec by configuring git url in jenkins.
> 3. Artifacts can be generated
> 4. Push those artifacts to artifactory/s3 bucket
> 5. Install tomcat, by default u will get webapps folder
> 6. Download that war file into webapps by using wget command
> 7. Access that with ip address

Actually i have war file saved in my local drive .. want to deploy on to vm (azure).. and then run it on tomcat

**Comment by revathi-muthana123** [comment]
Then install tomcat on azure vm, then copy that war file to webapps folder with scp command. Access it through browser.

**Comment by hari856** [comment]
> Then install tomcat on azure vm, then copy that war file to webapps folder with scp command. Access it through browser.

Many Thanks

**Comment by revathi-muthana123** [comment]
Pls close this, if u done.
