### ISSUE TITLE
Integration between application server and database

### ISSUE THREAD

**Issue by Sravan-jk** [QT-DevOps/DevOpsIssues#366]
Hello all,

Using terraform i can create a application server (Tomcat8) with GameofLife app init and a database.

I would like to attach this database to the application server using terraform scripts itself

please let me know if its possible to do that, if so let me know the steps to do it

Thanks
Sravan

**Comment by sunil3456** [comment]
It depends where is your DB server if its on same subnet or same VPC or different Cloud provider.
You need to install certain drivers to establish connection, it depends on your DB.
If your app server is pingable to DB server than all good to go by editing .cfg file.

This Link might clear your clouds 👍 

https://www.digitalocean.com/community/tutorials/how-to-set-up-a-remote-database-to-optimize-site-performance-with-mysql

**Comment by Sravan-jk** [comment]
Thanks Sunil, DB is in the same network and in private subnet. using cm tools can we automate this task in terraform. I want to try it

**Comment by shaikkhajaibrahim** [comment]
You can using terraform resource attributes & provisioning
