### ISSUE TITLE
azure ubuntu16 site

### ISSUE THREAD

**Issue by kotakondasuresh** [QT-DevOps/DevOpsIssues#368]
![image](https://user-images.githubusercontent.com/45281968/52995171-d73a0a80-343f-11e9-8bf8-e018b7935390.png)

**Comment by praveen1461996** [comment]
hi

make a look on this 
https://docs.microsoft.com/en-us/azure/site-recovery/vmware-physical-azure-support-matrix#ubuntu-kernel-versions

basically,the version you are selected is not supported for site recovery

**Comment by revathi-muthana123** [comment]
What's the problem? Pls describe it.
