### ISSUE TITLE
Problem with GIT PUSH 

### ISSUE THREAD

**Issue by Suneel023** [QT-DevOps/DevOpsIssues#369]
I have an issue on git push command:
below are my commands:

Su Kumar@SUKumar MINGW64 /g/My PC/DO Practice/Git/GitHub-Test (master)
$ git push
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master

Su Kumar@SUKumar MINGW64 /g/My PC/DO Practice/Git/GitHub-Test (master)
$ git push  --set-upstream origin master
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Please help me in resolving this issue.

**Comment by santoshkalingwar** [comment]
Hi,

Do you have the remote repository ,

if you have remote repository then you add remote  repository to your repo
eg:
git remote add origin git@git.assembla.com:portfolio/space.space_name.git
   
it will ask username and password ,please pass those detailes

**Comment by santoshkalingwar** [comment]
then you push into remote repo

**Comment by sivasankardevops** [comment]
try this command 
git push origin your branch name
