### ISSUE TITLE
Jenikins image building failed @packer

### ISSUE THREAD

**Issue by Imalli5253** [QT-DevOps/DevOpsIssues#37]
I have tried to create Jenkins image by using packer. But at the end its failed
If I do it manually with the same script file it will create Jenkins Image.
Here are the screen shots...
![opt](https://user-images.githubusercontent.com/20962752/41021561-7d293f7e-6984-11e8-8021-ec72c4d6f4d8.JPG)
![sh](https://user-images.githubusercontent.com/20962752/41021562-7d5cf350-6984-11e8-8438-4df56bd68d53.JPG)
![jen](https://user-images.githubusercontent.com/20962752/41021563-7d90c09a-6984-11e8-90a2-51c39aff0185.JPG)

**Comment by chittalalk** [comment]
Replace the "script":"<location of script>"
ex: "script":"E:/test/script.sh"

**Comment by sanjaysureshmv** [comment]
I had also issue in fetching the script path. so I gave the script path directly in the main json file
eg: "script_path":"/home/sanjaym/packer/tomcat_provision.sh"

**Comment by Imalli5253** [comment]
"script":"E:/test/script.sh" 
I tried like this. But it was not worked.

**Comment by sanjaysureshmv** [comment]
can you try building with -debug option, check if its showing more information about the error

**Comment by SarfrazPNQ** [comment]
I don't see Shebang in your shell script. Not sure if that is missing.

**Comment by Imalli5253** [comment]
I think shebang is not a problem. However I tried it. But still its not working.

**Comment by SarfrazPNQ** [comment]
Please give the absolute path where you have defined "aws_script" 
Below code works fine for me
![capture](https://user-images.githubusercontent.com/36878154/41033924-b2670132-69a5-11e8-87a2-e6e0b1dd49c6.PNG)

**Comment by SarfrazPNQ** [comment]
![capture-1](https://user-images.githubusercontent.com/36878154/41033992-e910a850-69a5-11e8-902c-283f92af5c0c.PNG)

**Comment by SarfrazPNQ** [comment]
![capture2](https://user-images.githubusercontent.com/36878154/41034062-1b4ef25e-69a6-11e8-8e4e-f2ab5d415e30.PNG)

**Comment by shaikkhajaibrahim** [comment]
The trouble shooting section of shell has already resolution for this 
My shell script doesn't work correctly on Ubuntu

    On Ubuntu, the /bin/sh shell is dash. If your script has bash-specific commands in it, then put #!/bin/bash -e at the top of your script. Differences between dash and bash can be found on the DashAsBinSh Ubuntu wiki page.

![image](https://user-images.githubusercontent.com/2438317/41034593-acba587c-69a7-11e8-9dd8-77aa17679817.png)

**Comment by shaikkhajaibrahim** [comment]
Can you run the commands without user intervention

![image](https://user-images.githubusercontent.com/2438317/41035029-11ff6636-69a9-11e8-919b-0270144de526.png)


Try them on linux machine. If it  asks for user input . It wouldn't  work in packer

**Comment by shaikkhajaibrahim** [comment]
@malli86271  Did you tried the stuff asked

**Comment by Imalli5253** [comment]
Yes sir I tried it. It asked user input when I had tried to install ORACLE-JAVA8-INSTALLER.

**Comment by shaikkhajaibrahim** [comment]
If it asks for user input packer will fail. You have execute commands which don't expect user intervention. 
One approach is use CM tools like chef/ansible to acheive this.
Other is write shell script in a way which will not expect user intervention.

**Comment by Imalli5253** [comment]
Thank you sir.
