### ISSUE TITLE
how to pull multiple repositories from project

### ISSUE THREAD

**Issue by boorla99** [QT-DevOps/DevOpsIssues#370]
Hello,
Assume, i have Repo A, Repo B , Repo C ...... Repo Z in the  _**XYZ**_ project folder on github/bitbucket repository
how do i clone multiple repositories to my local machine in one go ?  **(i dont want to clone each single repo everytime, it takes lot of time to pull & also manual interruption required for that.)**
if it is possible how can i achieve this?.

Thanks inadvance

**Comment by santoshkalingwar** [comment]
hi,

if you don't want any manual intervention then go for pipeline script which will help you to pull multiple branches 
below link may help you

https://code.i-harness.com/en/q/e27f30

**Comment by boorla99** [comment]
thanks santosh for you reply,
sorry if my question made  you confusion.it's not related to jenkins
basically, i want to clone 2 or more remote git repos to my laptop in single click.
.

**Comment by shaikkhajaibrahim** [comment]
Write script
