### ISSUE TITLE
Best Approach for CI/CD implementation

### ISSUE THREAD

**Issue by boorla99** [QT-DevOps/DevOpsIssues#371]
Hello **Everyone**,
I would like to build Jenkins pipeline which performs code checkout to till system monitoring, i need your thought process for this scenario.
any pre-requisite stuff required?
How should i start ?
How many servers do i require to achieve this ?
i also welcome any smart/quick way of establishing this pipeline through docker.
please input your answer.
when ever i make changes to **petlclinic** code it should go through all the above mention stages.
Thanks in advance,
_**Example flow should be like this**_ : SCM + BUILD+SCAN+ARTIFACTORY +DOCKER+TERRAFORM (IF POSSIBLE)+ANSIBLE+KUBERNETES+NAGIOS.
Dont' forget to share if you have any reference tutorial/video.

**Comment by sunil3456** [comment]
This flow works for the first time (by the way that is Iac)
When it comes to regular docker world, you gotta make sure pipe line works this way:
SCM+Jenkins>dockerhub>Jenkins>K8s> Nagios

# if you need this sort of architecture in Iac
You need to work on bits first and link them with Jenkins.
# Firstly, how do you want to do,
Do you want to spin up all the servers by provisioning with code or just deployment.
# If you want everything to be done, than its big deal. I’m working on it all the infra in one single click.
If you need reference better go with github repos: split your work and make it. 
All the best

**Comment by boorla99** [comment]
@sunil3456  Thanks for your input.
i agree, terraform script required for the first to sPin the servers then most of work will be on BUILD & DEPLOY. whenever there is scm change. 
I need some extra clarity here why do we need jenkins again after docker hub. 
_SCM+Jenkins>dockerhub>Jenkins>K8s> Nagios_
 i assume once the build images are pushed to dockerhub(or any private registry) i will specify that app. image in  k8s yaml file. K8's will pull the image & deploy it on one of its node. if i miss anything please
correct me .
thanks,
pradeep

**Comment by sunil3456** [comment]
Ok you can specify in manifest but someone has to call kubectl command!!

**Comment by boorla99** [comment]
@sunil3456  thanks 
i need small help & have few questions on devops  
how can i reach you? what's your email.
thanks in advance.
