### ISSUE TITLE
while terraform init ..getting this error

### ISSUE THREAD

**Issue by inileshpatel** [QT-DevOps/DevOpsIssues#372]
PS C:\Terraform\terraform1> terraform init
Initializing modules...
- module.Azure_storage
  Getting source ".//module//Azure_storage"

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

Error installing provider "azurerm": Get https://releases.hashicorp.com/terraform-provider-azurerm/: dial tcp 151.101.153.183:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions..

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/windows_amd64

**Comment by sunil3456** [comment]
This could be few reasons:
Must have Azure cli installed in your machine
For the first time better go with simple.tf file or empty file for initialising
Modules are for resuablility

**Comment by revathi-muthana123** [comment]
@nilesh, can u pls share your terraform file, what u have written? Better to elaborate what u have done ?
