### ISSUE TITLE
RESUME REVIEW

### ISSUE THREAD

**Issue by sumankumarpagadala** [QT-DevOps/DevOpsIssues#373]
Hello sir,

can u review my resume as i have sent 9 days ago.

**Comment by sumankumarpagadala** [comment]
As you said in class of 9th march, there is no such review email from you regarding my **resume review**.

**Comment by sumankumarpagadala** [comment]
Hello khaja sir,

Since feb 16th am waiting for your review, but no replay.. thank you for your help

**Comment by shaikkhajaibrahim** [comment]
I will do it I might have missed sorry for that. Can you resend mail

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sumankumarpagadala** [comment]
Sent today.

**Comment by sumankumarpagadala** [comment]
i have saved my resume in drive shared you the link 2 days ago...

**Comment by shaikkhajaibrahim** [comment]
I will do it over weekend.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sumankumarpagadala** [comment]
i havent got any response.

**Comment by shaikkhajaibrahim** [comment]
This is not the place to raise such concerns so closed. By the way reviewing your resume is happening.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
