### ISSUE TITLE
 EKS / AKS cluster creation by writing code

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [QT-DevOps/DevOpsIssues#375]
Hi Khaja Sir

Could you please let me know, as so far we have seen manual creation of EKS / AKS cluster in AWS / AZURE. Can i write code for creating these cluster in VSCode and execute ? if yes, please just hint me how to do, as this could be a big achievement for me.

Thanks
SajidKhan

**Comment by santoshkalingwar** [comment]
yes  you can write ARM template for aks

**Comment by SajidAliKhanMohammed** [comment]
ok, thanks, 
can you hint me how ?

**Comment by sunil3456** [comment]
https://www.terraform.io/docs/providers/aws/r/eks_cluster.html
