### ISSUE TITLE
Unable to create VM through json

### ISSUE THREAD

**Issue by thisiskrish1984** [QT-DevOps/DevOpsIssues#376]
HI Guys.Iam  trying to create ec2 machine through json script.
1.Started creating with vpc and subnets and created successfully.
2.Tried to create ec2 along with the existing script by adding the required parameters and end up showing error as 

  | Security group sg-025d7f6dd42a5ea4e and subnet subnet-0e8f071ba51d6cfc0 belong to different networks. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameter; Request ID: e53db50f-6f1e-469c-92ae-d250a6880be0).

Any guidance would be very much appreciated.

Thanks.
Krishna.

{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "Trying to create ec2 and rds",
    "Parameters":{
    "vpccidr": {
        "Description": "This is vpc cidr",
        "Type": "String"
    },
    
    "subnet1cidr": {
        "Description": "This is subnet1 cidr",
        "Type": "String"
    },
    
    "subnet1az": {
        "Description": "This is subnet1 az",
        "Type": "AWS::EC2::AvailabilityZone::Name"
    },
    
    "subnet2cidr": {
        "Description": "This is subnet2 cidr",
        "Type": "String"
    },
    
    "subnet2az": {
        "Description": "This is subnet2 az",
        "Type": "AWS::EC2::AvailabilityZone::Name"
        
    },
    
    "mykeys": {
        "Description": "This is my key name",
        "Type":"AWS::EC2::KeyPair::KeyName"
    },
    
    "myami": {
        "Description": "This is my image id",
        "Type": "AWS::EC2::Image::Id",
        "Default": "ami-04bfee437f38a691e"
    },
    
    "instancetypelist": {
        "Description": "This is my instance list",
        "Type": "String",
        "Default": "t2.micro",
        "AllowedValues":["t2.micro","t2.small","t2.large"]
    },
    
    "sggroup": {
        "Description": "This is my security group",
        "Type": "List<AWS::EC2::SecurityGroup::Id>"
        
    }
    },

    "Resources":{
        
        "vpc1": {
          "Type": "AWS::EC2::VPC",
          "Properties": {
            "CidrBlock":{ "Ref": "vpccidr" }
            
          }
        },
        
        "subnet1": {
          "Type": "AWS::EC2::Subnet",
          "Properties": {
            "AvailabilityZone":{ "Ref": "subnet1az" },
            "VpcId":{ "Ref": "vpc1" },
            "CidrBlock":{ "Ref": "subnet1cidr" }
            
            
          }
        },
        
        "subnet2": {
          "Type": "AWS::EC2::Subnet",
          "Properties": {
            "AvailabilityZone":{ "Ref": "subnet2az" },
            "VpcId":{ "Ref": "vpc1" },
            "CidrBlock":{ "Ref": "subnet2cidr" }
            
          }
        },
        
        "instance1": {
            "Type": "AWS::EC2::Instance",
            "Properties": {
                "KeyName":{ "Ref": "mykeys" },
                "ImageId":{ "Ref": "myami" },
                "InstanceType":{ "Ref": "instancetypelist" },
                "SubnetId":{ "Ref": "subnet1" },
                "SecurityGroupIds" :{ "Ref": "sggroup" }
                    
            }
        }       
    }

**Comment by santoshkalingwar** [comment]
please create secutity group in same vpc

**Comment by thisiskrish1984** [comment]
Thanks much for you help.
As said I  created a security group for this vpc and tried to create a template but getting an issue as
Value of property SecurityGroupIds must be of type List of String.
On surfing the net what I get to know is,should mention security group Id on instance.
But how to get the security group id for the new template?

 "instance1": {
            "Type": "AWS::EC2::Instance",
            "Properties": {
                "KeyName":{ "Ref": "mykeys" },
                "ImageId":{ "Ref": "myami" },
                "InstanceType":{ "Ref": "instancetypelist" },
                "SubnetId":{ "Ref": "subnet1" },
                "SecurityGroupIds" :{ "Ref": "securitygroup" }
                    
            }
        },
        
        "securitygroup" : {
          "Type" : "AWS::EC2::SecurityGroup",
          "Properties" : {
            "GroupDescription" : "This is vpc1 sggroup",
            "SecurityGroupIngress" : [{
                "IpProtocol" : "tcp",
                "FromPort" :22,
                "ToPort" : 22,
                "CidrIp" : "0.0.0.0/0"
             }],
          "SecurityGroupEgress" : [{
             "IpProtocol" : "tcp",
             "FromPort" : 22,
             "ToPort" : 22,
             "CidrIp" : "0.0.0.0/0"
          }], 
            "VpcId" : 
            { "Ref": "vpc1" }

**Comment by santoshkalingwar** [comment]
please follow below link

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html

**Comment by revathi-muthana123** [comment]
Please check it:

"sggroup": {
    "Description": "This is my security group",
    "Type": "List<AWS::EC2::SecurityGroup::Id>"
    
}

**Comment by revathi-muthana123** [comment]
Is it resolved? Security group I'd must be a list
