### ISSUE TITLE
i was trying to do ssh-key-based authication using playbook on aws.

### ISSUE THREAD

**Issue by pravin-07** [QT-DevOps/DevOpsIssues#377]
i was trying to do ssh-key-based authication using playbook on aws.just these thing we have to 125 server plz hepl me out
![ssh-iisues](https://user-images.githubusercontent.com/39874060/53875207-077dcd80-402a-11e9-8d44-5a1adc987b0e.png)

**Comment by santoshkalingwar** [comment]
hello,

follow the link it may help you

https://www.agix.com.au/build-an-ec2-using-ansible-step-by-step/

**Comment by pravin-07** [comment]
> 
> 
> hello,
> 
> follow the link it may help you
> 
> https://www.agix.com.au/build-an-ec2-using-ansible-step-by-step/

thanks

**Comment by pravin-07** [comment]
service metricbeat status                                                                           ● metricbeat.service - Metricbeat is a lightweight shipper for metrics.                                                                   Loaded: loaded (/usr/lib/systemd/system/metricbeat.service; enabled; vendor preset: disabled)                                          Active: failed (Result: start-limit) since Tue 2019-03-12 06:17:47 UTC; 12s ago                                                          Docs: https://www.elastic.co/products/beats/metricbeat                                                                              Process: 4662 ExecStart=/usr/share/metricbeat/bin/metricbeat -c /etc/metricbeat/metricbeat.yml -path.home /usr/share/metricbeat -pat h.config /etc/metricbeat -path.data /var/lib/metricbeat -path.logs /var/log/metricbeat (code=exited, status=1/FAILURE)                  Main PID: 4662 (code=exited, status=1/FAILURE)                                                                                                                                                                                                                               Mar 12 06:17:47 ip-172-31-40-87.ec2.internal systemd[1]: metricbeat.service failed.                                                    Mar 12 06:17:47 ip-172-31-40-87.ec2.internal systemd[1]: metricbeat.service holdoff time over, scheduling restart.                     Mar 12 06:17:47 ip-172-31-40-87.ec2.internal systemd[1]: Stopped Metricbeat is a lightweight shipper for metrics..                     Mar 12 06:17:47 ip-172-31-40-87.ec2.internal systemd[1]: start request repeated too quickly for metricbeat.service                     Mar 12 06:17:47 ip-172-31-40-87.ec2.internal systemd[1]: Failed to start Metricbeat is a lightweight shipper for metrics..             Mar 12 06:17:47 ip-172-31-40-87.ec2.internal systemd[1]: Unit metricbeat.service entered failed state.                                 Mar 12 06:17:47 ip-172-31-40-87.ec2.internal systemd[1]: metricbeat.service failed.                                                    Mar 12 06:17:51 ip-172-31-40-87.ec2.internal systemd[1]: start request repeated too quickly for metricbeat.service                     Mar 12 06:17:51 ip-172-31-40-87.ec2.internal systemd[1]: Failed to start Metricbeat is a lightweight shipper for metrics..             Mar 12 06:17:51 ip-172-31-40-87.ec2.internal systemd[1]: metricbeat.service failed.                                                    [root@ip-172-31-40-87 metricbeat]#                                                                                                     [root@ip-172-31-40-87 metricbeat]# systemctl restart metricbeat
--


![metricbeat](https://user-images.githubusercontent.com/39874060/54178920-480f9800-44bd-11e9-87a2-9c77a485114a.png)
