### ISSUE TITLE
running docker cmd issue

### ISSUE THREAD

**Issue by singaravellu** [QT-DevOps/DevOpsIssues#379]
i have pulled jenkins image from docker hub and i am trying to run it but it's was not running can you please help in this 

![Capture](https://user-images.githubusercontent.com/32475854/54253697-5c639b80-4576-11e9-9ecd-da15c1404ed7.PNG)

**Comment by sunil3456** [comment]
don't use bin/bash or else go with detached mode -d or
run the container with 
"docker run -it jenkins:alpine" same with other
while exiting the container use Ctrl+p+q (to keep container runing)
because container status shows exited.

**Comment by tgvrk** [comment]
Do not use /bin/bash , run 

docker run -d -p 8080:8080 jenkins
