### ISSUE TITLE
error in upstream and downstream

### ISSUE THREAD

**Issue by manikantadevopss** [QT-DevOps/DevOpsIssues#38]
iam facing this below issue

Started by upstream project "gameoflife" build number 4
originally caused by:
 Started by user durga manikanta punnam
Building in workspace /var/lib/jenkins/workspace/cdex
[cdex] $ /bin/sh -xe /tmp/jenkins8983592963623440870.sh
+ “echo Location is /var/lib/jenkins/workspace/gameoflife/gameoflife-web/target/gameoflife.war
/tmp/jenkins8983592963623440870.sh: 2: /tmp/jenkins8983592963623440870.sh: “echo: not found
Build step 'Execute shell' marked build as failure
Finished: FAILURE

                                     "can u help me"

**Comment by shaikkhajaibrahim** [comment]
Please share your job configuration  screenshot of your build steps in Jenkins

**Comment by manikantadevopss** [comment]
thank you for response sir,

![1](https://user-images.githubusercontent.com/33957232/41105236-dc0b0c28-6a8a-11e8-9257-2f43e41028b3.png)
![2](https://user-images.githubusercontent.com/33957232/41105238-dc4e2f8a-6a8a-11e8-8f4b-5be87edb6c0b.png)
![3](https://user-images.githubusercontent.com/33957232/41105239-dc7aa86c-6a8a-11e8-92f9-96bb47bc4a76.png)
![4](https://user-images.githubusercontent.com/33957232/41105240-dca85122-6a8a-11e8-979a-819306189341.png)
![5](https://user-images.githubusercontent.com/33957232/41105241-dcd49c50-6a8a-11e8-804f-f397c87e2ae1.png)
![6](https://user-images.githubusercontent.com/33957232/41105242-dd0aa2dc-6a8a-11e8-9587-09d99c30faac.png)
![7](https://user-images.githubusercontent.com/33957232/41105243-dd38fae2-6a8a-11e8-8520-dbc937494fa3.png)

**Comment by vijaybhaskarreddyy** [comment]
Where did you specified tomcat_ip, have you passed any parameter?

**Comment by manikantadevopss** [comment]
![4](https://user-images.githubusercontent.com/33957232/41143841-71ba8d56-6b18-11e8-855f-bb69037cea01.png)



i gave tomcat macnins's private ip of aws machin

**Comment by shaikkhajaibrahim** [comment]
The highlighted section is showing error why?
do you have jenkins job with the name cdex?

![image](https://user-images.githubusercontent.com/2438317/41146149-0d501630-6b20-11e8-8469-88e0a6c329ca.png)

**Comment by manikantadevopss** [comment]
i resolved that one, yes i have job with that name.but getting below error


“echo Location is /var/lib/jenkins/workspace/gameoflife/gameoflife-web/target/gameoflife.war
/tmp/jenkins8983592963623440870.sh: 2: /tmp/jenkins8983592963623440870.sh: “echo: not found
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by shaikkhajaibrahim** [comment]
I suspect quotes
![image](https://user-images.githubusercontent.com/2438317/41215426-dea31134-6d6d-11e8-9919-6e538888d883.png)

what is need for quotes "". Remove them

**Comment by manikantadevopss** [comment]
thank you,but after modify that, iam getting below error, can u help me

Building on master in workspace /var/lib/jenkins/workspace/cdex
[cdex] $ /bin/sh -xe /tmp/jenkins3853121719139919905.sh
+ echo Location is /var/lib/jenkins/workspace/gameoflife-daybuild/gameoflife-web/target/gameoflife.war
Location is /var/lib/jenkins/workspace/gameoflife-daybuild/gameoflife-web/target/gameoflife.war
+ echo IP is 172.31.21.167
IP is 172.31.21.167
+ whoami
jenkins
+ scp /var/lib/jenkins/workspace/gameoflife-daybuild/gameoflife-web/target/gameoflife.war 172.31.21.167:/var/lib/tomcat8/webapps/
scp: /var/lib/tomcat8/webapps//gameoflife.war: Permission denied
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by shaikkhajaibrahim** [comment]
SCP Expects user input right??
how are you passing password then
Can you execute the command manually & Check whether it is asking for user input. If the command is expecting user input, Jenkins will fail.

And  one more thing why are using scp. Why not ansible/chef to copy the file

**Comment by manikantagaddam** [comment]
please check webapps folder permissions  and if u dont have permissions give  permissions using chmod 777 webapps/ and try it

**Comment by manikantagaddam** [comment]
is this resolved?
