### ISSUE TITLE
Code from different source code mgmnt

### ISSUE THREAD

**Issue by saireddy224** [QT-DevOps/DevOpsIssues#383]
I have some code in svn and some code in git and I want to create a build combining two codes in Jenkins. How can we achieve this

**Comment by sunil3456** [comment]
https://git-scm.com/docs/git-svn

**Comment by santoshkalingwar** [comment]
https://git-scm.com/book/en/v1/Git-and-Other-Systems-Git-and-Subversion

**Comment by shaikkhajaibrahim** [comment]
How are you doing this manually. Let us know. Then we can think of Jenkins
