### ISSUE TITLE
jenkins credintials

### ISSUE THREAD

**Issue by saireddy224** [QT-DevOps/DevOpsIssues#384]
i configered git credentials in global credintials in jenkins ,i want to run a job with new git credintials .can we override the credentials

**Comment by sunil3456** [comment]
Hi Sai
yes you can either delete .git folder or follow these two links you will find solution.
https://stackoverflow.com/questions/30196936/how-to-overwrite-global-git-credentials-for-one-repo

https://stackoverflow.com/questions/43118543/how-can-i-config-two-different-git-repo-with-different-credentials-in-one-system

**Comment by santoshkalingwar** [comment]
please follow below link , it may help you

https://www.thegeekstuff.com/2016/10/jenkins-git-setup/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%253A+TheGeekStuff+%2528The+Geek+Stuff%2529

**Comment by shaikkhajaibrahim** [comment]
Is this resolved

**Comment by ghost** [comment]
plz  close the issue
