### ISSUE TITLE
Sonar build failed on startup

### ISSUE THREAD

**Issue by BRAHMAREDDYV** [QT-DevOps/DevOpsIssues#385]
Hi Team,

I got this when i build the job
![Sonar_Build_failed](https://user-images.githubusercontent.com/43407156/54472658-131f8000-47f2-11e9-8279-f6201ccbd387.JPG)

Thq

**Comment by sunil3456** [comment]
Mate can you drop logs, screen shot of pipeline wont help to solve.

**Comment by santoshkalingwar** [comment]
Please send the log file and also send the how you configured in Jenkins

**Comment by shaikkhajaibrahim** [comment]
If you want the issues to be resolved attach logs

**Comment by BRAHMAREDDYV** [comment]
Thanks
