### ISSUE TITLE
choosing controlserver name other than ansible

### ISSUE THREAD

**Issue by hariprata** [QT-DevOps/DevOpsIssues#386]
when i am choosing other names  for controlserver name then at the time of generating key
path shown was 

/home/controlserver/.ssh/id_rsa

but when i'm trying to go to the path then

/home/controlserver/.ssh/id_rsa: Not a directory

**Comment by sunil3456** [comment]
id_rsa is not a directory, its file go with vim/vi/nano editor

**Comment by santoshkalingwar** [comment]
Id_rsa is file, you can't go inside the file ,if you want to see the contents of file then open it with vi or nano or cat commnad

**Comment by BRAHMAREDDYV** [comment]
What is the issue here, Could u please specify the issue with logs

**Comment by bhaskardegala** [comment]
Hariprata the error itself states it was not a directory , inorder to view the file use "cat <path/filename>" and I think there is no necessity to open that as it was a public key created by you using "ssh-keygen" if your question is how to copy it to other servers then use "ssh-copy-id <user>@<private ip>" or simply "ssh-copy-id <private ip>

**Comment by BRAHMAREDDYV** [comment]
Hi hariprata,

/home/controlserver/.ssh/id_rsa: Not a directory

This is not an error, please ensure that if u have error please specify or else close the issue

**Comment by bhaskardegala** [comment]
Hi hariprata 
Please send proper logs if the issue  was not solved or else close the issue

**Comment by ghost** [comment]
if issue resolved , plz close issue
