### ISSUE TITLE
Need documents for terraform with chef and Ansible

### ISSUE THREAD

**Issue by kampatinagesh** [QT-DevOps/DevOpsIssues#387]
Hi Sir,

Few days back we had a discussion in class regarding that Documents.

Please share those documents. It will be very helpful for interviews. 

Need documents for terraform with chef and Ansible

Thanks,
Nagesh.

**Comment by shaikkhajaibrahim** [comment]
This forum is only for technical concerns. Please send mail to Satish for documents
