### ISSUE TITLE
Port 8080 not reachable in Azure VM ( Redhat ) - NSG is allowed 

### ISSUE THREAD

**Issue by Karthick-Gopalakrishnan** [QT-DevOps/DevOpsIssues#388]
I got 3 vms running in azure vm.. With Redhat, Ubuntu, Centos. 

I have deployed httpd in Redhat VM using ansible running in local VM (Lappy). 
* HTTPD is installed 
![image](https://user-images.githubusercontent.com/48745218/54684160-eb4f5580-4b2c-11e9-92d4-afb79440e45d.png)
* Service is up and running 
* allowed port 8080 in Redhat VM 
![image](https://user-images.githubusercontent.com/48745218/54684187-002be900-4b2d-11e9-8d28-45d2abe36644.png)
* Tried accessing the web portal failed 
![image](https://user-images.githubusercontent.com/48745218/54684308-61ec5300-4b2d-11e9-9ba9-b6b17b7301f4.png)
* Tried scanning open port using nmap 
![image](https://user-images.githubusercontent.com/48745218/54684361-8a744d00-4b2d-11e9-8657-68187f605f07.png)
I couldn't access the HTTP server portal though my port 8080 is open 
I have missed something somewhere kindly point me towards it. Any assistance is appreciated !!

**Comment by sunil3456** [comment]
Check your local firewall, try flush or stop
iptables -L -n
Check your port by using
tcpdump -i eth0 port 8080 or
netstat -ntlp or
telnet

**Comment by santoshkalingwar** [comment]
Please check firewall of server

**Comment by Karthick-Gopalakrishnan** [comment]
Hello Sunil & Santosh,
Stopping firewall and adding inbound rule for port 80 worked, Am able to access the HTTP portal.
Thanks for your assistance..Really appreciate it !! 
when i use nmap -open hostip i could see 
22 ssh and 80 http port open 

Below points is still open: 
1. But still when i point the ip to XX.XX.XX.XX:8080 it not reachable though inbound rule is allowed   
2. 8080 is till not showing under nmap scan 
3. how to make it work with firewall enabled

When i get answers for above will update this forum

**Comment by sunil3456** [comment]
If thats the case add rule in linux server
To enable port permanently (recommend go with command line)
vi /etc/sysconfig/iptables or
sudo iptables -A INPUT -p tcp --dport 80 -j ACCEPT (To open webserver)
sudo iptables -A INPUT -p tcp --dport 22 -j ACCEPT (to open ssh)
iptables-save | grep 80
service iptables restart
I think you can close the case

Thanks

**Comment by Karthick-Gopalakrishnan** [comment]
Sunil,
as u said ..PFB
![image](https://user-images.githubusercontent.com/48745218/54834942-9d785000-4cda-11e9-9005-1566769ff29d.png)
started Iptables & firewall 
![image](https://user-images.githubusercontent.com/48745218/54835087-dd3f3780-4cda-11e9-9b1b-eb497d809247.png)

Unable to access the HTTP server.

**Comment by sunil3456** [comment]
https://www.google.com.au/amp/s/www.cyberciti.biz/faq/linux-web-server-firewall-tutorial/amp/

**Comment by sunil3456** [comment]
I think the problem is this rule:

-A INPUT -j REJECT --reject-with icmp-host-prohibited
That tells IPTables to reject everything coming in on the INPUT chain, i.e. all incoming packets. And since IPTables reads (and applies) its rules in order from top to bottom, for NEW packets coming in on ports 80 and 3306, that's the first rule that matches. So they all get rejected. The only packets that wouldn't be rejected by that rule are the ones coming into port 22, since the rule right above it says to accept them.

To fix it, just move that rule to the end of the file. That way, IPTables will encounter the rules saying to ACCEPT packets on ports 80 and 3306 first.

Reference:
https://serverfault.com/questions/154531/help-with-iptables-cannot-connect-to-web-server

**Comment by Karthick-Gopalakrishnan** [comment]
Thanks Sunil, I will swap the rule and will update the status

**Comment by Karthick-Gopalakrishnan** [comment]
Hello Sunil,

firewall-cmd --zone=public --add-port=80/tcp this did the trick, It allowed port 80 and webpage was up. 

P.S : Changing the IP table didn't work in my case

Appreciate all your assistance!!
