### ISSUE TITLE
git bash timed out

### ISSUE THREAD

**Issue by soujanyachigulla** [QT-DevOps/DevOpsIssues#389]
every time git bash is getting timed out after few minutes
i tried ClientAliveInterval command also
still it doesn't work
plzz help me in resolving this issue

**Comment by sunil3456** [comment]
have you tried adding count, if you dont specify count it takes default value to  3
ClientAliveCountMax

**Comment by santoshkalingwar** [comment]
please follow the below link

https://www.digitalocean.com/community/questions/how-to-increase-ssh-connection-timeout

**Comment by soujanyachigulla** [comment]
I tried those commands but still its getting timed out

**Comment by sunil3456** [comment]
have you restarted sshd

**Comment by soujanyachigulla** [comment]
yes

**Comment by krohithram** [comment]
Try this  https://confluence.atlassian.com/bitbucketserverkb/git-push-over-ssh-user-session-has-timed-out-idling-after-600000-ms-856822707.html

**Comment by sunil3456** [comment]
Can you screen shot what you have done.
https://jasonhzy.github.io/2016/02/03/ssh-alive/

**Comment by soujanyachigulla** [comment]
![IMG_20190322_191136663](https://user-images.githubusercontent.com/48559097/54826995-04940580-4cd7-11e9-8dd0-d0d6b9e4ca66.jpg)

**Comment by soujanyachigulla** [comment]
its working now
Thank you everyone for ur help

**Comment by revathi-muthana123** [comment]
Hi soujanya, pls close this issue. If it's resolved.
