### ISSUE TITLE
Error(packer): AWS was not able to validate the provided access credentials

### ISSUE THREAD

**Issue by Vijay0973** [QT-DevOps/DevOpsIssues#39]
![packer](https://user-images.githubusercontent.com/39436774/41190715-d915be14-6b98-11e8-9e5a-8a21d5a98e4c.PNG)

**Comment by SarfrazPNQ** [comment]
Please check if you have provided active access key & secret key with correct region.

**Comment by Vijay0973** [comment]
Yaa I given the correct secret key....but it's not working......can u guide me please....

-----Original Message-----

**Comment by SarfrazPNQ** [comment]
Can you please share your json file hiding your credentials.

**Comment by Vijay0973** [comment]
![packer-1](https://user-images.githubusercontent.com/39436774/41194009-fb0e6f80-6bc9-11e8-9111-403fb57307d6.PNG)

**Comment by Vijay0973** [comment]
I delete the user and credentials and again i created ..but still i'm facing the same problem

**Comment by Vijay0973** [comment]
![packer-2](https://user-images.githubusercontent.com/39436774/41194301-3d42c92e-6bce-11e8-8d86-2c877d721567.PNG)
and this the access key which is active ...

**Comment by Vijay0973** [comment]
![packer-3](https://user-images.githubusercontent.com/39436774/41194372-02b87154-6bcf-11e8-9589-92ece357044e.PNG)
and i terminated the machine also  which was created before  ...and u can check the origin name here

**Comment by shaikkhajaibrahim** [comment]
can you use aws cli "aws ec2 run-instances" as mentioned here https://docs.aws.amazon.com/cli/latest/reference/ec2/run-instances.html
and share the result

**Comment by Vijay0973** [comment]
Sir , i got the answer, which i was asked from the packer documents.
 this was  reason............
![packer-ans](https://user-images.githubusercontent.com/39436774/41237813-18f1fe24-6db2-11e8-98e1-0d24008b3153.PNG)

**Comment by shaikkhajaibrahim** [comment]
Thanks
