### ISSUE TITLE
How restart jenkins slave!

### ISSUE THREAD

**Issue by praghu8055** [QT-DevOps/DevOpsIssues#393]
When Jenkins job build failure for redeployment how to restart slave server?

**Comment by santoshkalingwar** [comment]
Reboot slave machine , manually or you can ssh inside slave and run reboot command with jenkins

**Comment by sunil3456** [comment]
#"make sure you configure your slave with private Ip " or else you have to change host everytime you restart your machine.
#Remember If you want to take action on one server its beter going by manually or else if you want periodicway or multiple servers or multiple times go with jobs or playbook or command line.
#If you dont want your slave to sit and wait online than go to configure and change the availability of your slave.
