### ISSUE TITLE
bootstrap getting failed

### ISSUE THREAD

**Issue by chinavenkannababu** [QT-DevOps/DevOpsIssues#394]
I am unable to bootstrap due to below issue. Please help m on this and i cannot proceed further without bootstrap success

PS C:\Devops\chef-starter\chef-repo> knife bootstrap 18.222.42.214 -N ip-172-31-31-200.us-east-2.compute.internal --sudo -x ubuntu -i .\chefws.pem
ERROR: Failed to authenticate to https://api.chef.io/organizations/organisation_chef as chinnachef with key C:/Devops/chef-starter/chef-repo/.chef/chinnachef.pem
Response:  Failed to authenticate as chinnachef. Synchronize the clock on your host.

PS C:\Devops\chef-starter\chef-repo> knife bootstrap 18.222.42.214 -N ip-172-31-31-200.us-east-2.compute.internal --sudo -x ubuntu -i .\chefws.pem --node-ssl-verify-mode none
ERROR: Failed to authenticate to https://api.chef.io/organizations/organisation_chef as chinnachef with key C:/Devops/chef-starter/chef-repo/.chef/chinnachef.pem
Response:  Failed to authenticate as chinnachef. Synchronize the clock on your host.

**Comment by dharmatejadevops** [comment]
you can place the pem file with in the chef-repo directory and try it may be its help full.
or you can give the complete path of pem pfile where you place it.

**Comment by chinavenkannababu** [comment]
Pem file exists in chef-repo directory and i tried with complete path of pem file...Hope it is related to some port issue. I cannot connect from Workstation to Nodes.

Response: Failed to authenticate as chinnachef. Synchronize the clock on your host.

**Comment by santoshkalingwar** [comment]
Hi,

I this issue because of time and date syncronization of you system please check date and time ,

**Comment by chinavenkannababu** [comment]
Time & date looks fine in my sysem

![image](https://user-images.githubusercontent.com/49113288/55305020-44f43180-5403-11e9-9965-b885baf28a56.png)

**Comment by shaikkhajaibrahim** [comment]
Synchronize the clock on your host¶<https://docs.chef.io/errors.html#synchronize-the-clock-on-your-host>

If the system clock drifts more than 15 minutes from the actual time, the following type of error will be shown:

INFO: Client key /etc/chef/client.pem is not present - registering INFO: HTTP Request Returned 401 Unauthorized: Failed to authenticate as ORGANIZATION-validator. Synchronize the clock on your host. FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out FATAL: Net::HTTPServerException: 401 "Unauthorized"

To resolve this error, synchronize the clock with an NTP server.



Do this on your node

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sunil3456** [comment]
its common issue you can reboot your node. sometimes uptime of your machine doesnt sync with server reboot solves the issues.

**Comment by chinavenkannababu** [comment]
I tried reboot of the node but it doesn't work and still it throws the same error.

![image](https://user-images.githubusercontent.com/49113288/55333738-847b5600-54b5-11e9-9324-70dbf11115be.png)

**Comment by santoshkalingwar** [comment]
You are executing bootstrap command in chef-repo folder and you pem key is present in same repo or in any other repo ,if it is present in different repo please give full path

Otherwise please send the screenshot of you pem key location and from where you are execute command

**Comment by chinavenkannababu** [comment]
![image](https://user-images.githubusercontent.com/49113288/55335676-31a39d80-54b9-11e9-8a84-7fcc2c1c470f.png)

**Comment by sunil3456** [comment]
we need to stop the ntpd service before synchronising and then restarting it after the ntpdate.
/etc/init.d/ntpd stop
/etc/init.d/ntpdate <server-name from where the date/clock has to be synchronised>
/etc/init.d/ntpd start
/etc/init.d/ntpd status

**Comment by nareshabbanapuri** [comment]
please close issue if it solved

**Comment by ghost** [comment]
plz close issue

**Comment by bhaskardegala** [comment]
Did your problem resolved if yes please close the issue or else let us know

**Comment by chinavenkannababu** [comment]
Yes, my issue got resolved and thanks to Naresh for resolving the issue.

**Comment by chinavenkannababu** [comment]
As my issue got resolved, i am closing this
