### ISSUE TITLE
Unable to run docker file 

### ISSUE THREAD

**Issue by manohar128** [QT-DevOps/DevOpsIssues#395]
Hi All ,

    I am trying to run gameoflife.war file through docker file but i am getting below error.
"unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/ubuntu/images/gameoflife/Dockerfile: no such file or directory"
                                                 
                                           Could you please help me to get resolve of this issue.

**Comment by shaikkhajaibrahim** [comment]
share your Dockerfile
________________________________

**Comment by manohar128** [comment]
Thanks for your quick response.Please find the below Dockerfile

FROM tomcat
MAINTAINER qulitythought
ADD gameoflife.war /usr/local/tomcat/webapps/gameoflife.war
EXPOSE 8080
CMD ["catalina.sh" "run"]

**Comment by shaikkhajaibrahim** [comment]
Can you execute ls from the terminal where you are running your docker image build command. Share the results
________________________________

**Comment by manohar128** [comment]
Please find the below screen for reference.
![Docker issue](https://user-images.githubusercontent.com/40994509/55323266-3dcd3200-549c-11e9-9812-835622cdf875.JPG)

**Comment by shaikkhajaibrahim** [comment]
Where is Dockerfile??? in this directory
________________________________

**Comment by sunil3456** [comment]
can you drop Dockerfile path

**Comment by manohar128** [comment]
oops it's My bad , it's working fine now. Thanks for your help. I was not saving Docker file due to that reason i was getting error.
          "Once again thanks for your quick input."

**Comment by sunil3456** [comment]
close the case

**Comment by manohar128** [comment]
working as expected
