### ISSUE TITLE
when play ansible playbook getting error like 

### ISSUE THREAD

**Issue by dharmatejadevops** [QT-DevOps/DevOpsIssues#396]
![Capture](https://user-images.githubusercontent.com/43385451/55339758-f1e0b400-54c0-11e9-80e1-90635fb2a3fb.PNG)

**Comment by dharmatejadevops** [comment]
the playbook of above ansible play is file.
[appserver.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3030259/appserver.txt)

**Comment by santoshkalingwar** [comment]
Please send your playbook

**Comment by AFZALBIW** [comment]
please give full permission on /opt/tomcat/conf/ folder

**Comment by dharmatejadevops** [comment]
> please give full permission on /opt/tomcat/conf/ folder

i will give mode 1777 on template dest: /opt/tomcat/conf

**Comment by dharmatejadevops** [comment]
> Please send your playbook




[playbook.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3033809/playbook.zip)

**Comment by bhaskardegala** [comment]
as the above message states that it could not find tomcat-users.xml and please try to copy your tomcat-users.xml file to following path " /home/ansible/playbooks/ntier/templates/" as it seems to be absent in that location

**Comment by dharmatejadevops** [comment]
> as the above message states that it could not find tomcat-users.xml and please try to copy your tomcat-users.xml file to following path " /home/ansible/playbooks/ntier/templates/" as it seems to be absent in that location

as the same path i placed that  tomcat-users.xml.j2 file

**Comment by bhaskardegala** [comment]
> > as the above message states that it could not find tomcat-users.xml and please try to copy your tomcat-users.xml file to following path " /home/ansible/playbooks/ntier/templates/" as it seems to be absent in that location
> 
> as the same path i placed that tomcat-users.xml.j2 file

remove .j2 extension

**Comment by dharmatejadevops** [comment]
> > > as the above message states that it could not find tomcat-users.xml and please try to copy your tomcat-users.xml file to following path " /home/ansible/playbooks/ntier/templates/" as it seems to be absent in that location
> > 
> > 
> > as the same path i placed that tomcat-users.xml.j2 file
> 
> remove .j2 extension

for the  templates extension is .j2 na

**Comment by dharmatejadevops** [comment]
> please give full permission on /opt/tomcat/conf/ folder

for giving full permissions mode: 01777 na

**Comment by bhaskardegala** [comment]
try to have a glance at my playbook as i haven't used templets for configuring tomcat-users.xml  https://github.com/bhaskardegala/ansible-sample

**Comment by dharmatejadevops** [comment]
> try to have a glance at my playbook as i haven't used templets for configuring tomcat-users.xml https://github.com/bhaskardegala/ansible-sample

good one bhaskar its help full but in file module which parameter we are used for append the file content

**Comment by bhaskardegala** [comment]
> > try to have a glance at my playbook as i haven't used templets for configuring tomcat-users.xml https://github.com/bhaskardegala/ansible-sample
> 
> good one bhaskar its help full but in file module which parameter we are used for append the file content

actually i deleted the existing file and replaced with new one that i have created before you can find those files in [https://github.com/bhaskardegala/ansible-sample/tree/master/roles/gameoflife/files/copy](url) folder as i thought it can simplify my work

**Comment by dharmatejadevops** [comment]
> > > try to have a glance at my playbook as i haven't used templets for configuring tomcat-users.xml https://github.com/bhaskardegala/ansible-sample
> > 
> > 
> > good one bhaskar its help full but in file module which parameter we are used for append the file content
> 
> actually i deleted the existing file and replaced with new one that i have created before you can find those files in [https://github.com/bhaskardegala/ansible-sample/tree/master/roles/gameoflife/files/copy](url) folder as i thought it can simplify my work

in that  copy tomcat-user.xml task r u using copy module
src: copy/<file-name>
i trie dthis it gives cannot find or access some error

![errorcopy](https://user-images.githubusercontent.com/43385451/55413044-2f5b4500-5586-11e9-90b5-b9818faa2c04.png)

**Comment by dharmatejadevops** [comment]
closed
