### ISSUE TITLE
I have cookbook in place. I have uploaded it to server.Added it to runlist. Manually did the convergence.My cookbook recipe entitiled to create a file in home directory of linux system .

### ISSUE THREAD

**Issue by MupparajuPraveen** [QT-DevOps/DevOpsIssues#397]
Recipe file content in cookbook:

#
# Cookbook:: Praveen_CookBook4
# Recipe:: default
#
# Copyright:: 2019, The Authors, All Rights Reserved.
#syntax
#file 'name' do
#attribute 'value' example path value should be file path
#action 'value' example create,delete

file 'Praveen4.txt' do
    path  '\home\ubuntu'
    content 'Hi All, I have starting writing receipe'
    action :create
end    

Screenshot of node and runlist:
![image](https://user-images.githubusercontent.com/49182018/55380242-445fb600-553d-11e9-9ec4-75facfa9e62e.png)

Doubts?

1.from the bash " knife node list " command throwing below error.

I did Git bash from D:\Chef\Starter_Kit\chef-starter\chef-repo( Here i have .pem file for ubantu system)

WARNING: No knife configuration file found. See https://docs.chef.io/config_rb_knife.html for details.
WARN: Failed to read the private key /etc/chef/client.pem: #<Errno::EACCES: Permission denied @ rb_sysopen - /etc/chef/client.pem>
ERROR: Your private key could not be loaded from /etc/chef/client.pem
Check your configuration file and ensure that your private key is readable
ubuntu@ip-172-31-14-232:~$ knife node list

2. Bash "sudo chef-client" after uploading the cookbook to server (Did it from power shell after     changing the path to my cookbook path)
I could see below message 

![image](https://user-images.githubusercontent.com/49182018/55380792-e9c75980-553e-11e9-95fa-6abca75acf0b.png)

But when i ran ls command from that path i dont see any files exist in the path.

Could you please help me on this

Please let me know if you want me to share the my screen 
Thanks for you help.

Praveen

**Comment by santoshkalingwar** [comment]
Files are created in you machine in /home/Ubuntu folder please check inside that folder

**Comment by MupparajuPraveen** [comment]
Appreciated your quick response.

 I have changed directory to ubuntu ( cd ubuntu) and ran ls command but i
don't see any files .

Thanks,
Praveen

**Comment by MupparajuPraveen** [comment]
You could see the screenshot attached to the ticket.

Thanks,
Praveen

**Comment by sunil3456** [comment]
try 
ls -la

**Comment by santoshkalingwar** [comment]
Your cookbook file path has given wrong , path should be /home/Ubuntu/

This is Linux way

**Comment by MupparajuPraveen** [comment]
I did try .After giving the path as you said cook book is failing to upload
with syntax error in ruby file.


Regards,
Praveen

**Comment by santoshkalingwar** [comment]
Change the version in metadata.rb file and upload

**Comment by MupparajuPraveen** [comment]
I did not update the existing cookbook .I have created the new cook book
with same recipe and cange the path as you suggested

Regards,
Praveen

**Comment by Karthick-Gopalakrishnan** [comment]
hello, 
As santhosh said,  Forward slash " / " is how we define path in LINUX

Below recipe will work ... It is cooked and tasted :P

file 'create file' do
    path '/home/chef/1.txt'
    content 'hello1'
    action :create
end

**Comment by Karthick-Gopalakrishnan** [comment]
> hello,
> As santhosh said, Forward slash " / " is how we define path in LINUX
> 
> Below recipe will work ... It is cooked and tasted :P
> 
> file 'create file' do
> path '/home/chef/1.txt'
> content 'hello1'
> action :create
> end

in your case path will be '/home/ubuntu/1.txt'

**Comment by AFZALBIW** [comment]
https://docs.chef.io/resource_file.html

**Comment by MupparajuPraveen** [comment]
Can some one share your phone number so that I can call and share my screen
in WebEx that would be a great help.

Regards,
Praveen

**Comment by Karthick-Gopalakrishnan** [comment]
Praveen,

before moving to the part of sharing the screen...Give a try with below ruby script. 

create a new cookbook with below recipe and post us the result .  If you get an error then clear screenshot of error. 

file 'create file' do
path '/home/chef/1.txt'
content 'hello1'
action :create
end  

![image](https://user-images.githubusercontent.com/48745218/55453405-c22eca80-55ec-11e9-823c-15e00c0a989c.png)

**Comment by MupparajuPraveen** [comment]
Thank you all. Appreciate your support.

Thanks,
Praveen
