### ISSUE TITLE
Ruby syntax error in path/to/file in resource

### ISSUE THREAD

**Issue by gayithrikota** [QT-DevOps/DevOpsIssues#399]
I got Ruby syntax error in path/to/file in resource

**Comment by santoshkalingwar** [comment]
Please send the log

**Comment by AFZALBIW** [comment]
please send the cookbook file

**Comment by AFZALBIW** [comment]
please check file path in your cookbook 

in linux you have to give  

/home/ubuntu/1.txt

in windows  
\home\user\1.txt

**Comment by ghost** [comment]
plz upload cookbook
