### ISSUE TITLE
Jenkins: Reverse proxy setup is broken

### ISSUE THREAD

**Issue by xavyaly** [QT-DevOps/DevOpsIssues#4]
Please let me know why it's coming in yours as well as mine jenkins console.

I tried to figure it out with the help of this link but still facing the same issue in my local jenkins.

https://wiki.jenkins.io/display/JENKINS/Running+Jenkins+behind+Apache

**Comment by shaikkhajaibrahim** [comment]
<Proxy http://localhost:8080/jenkins*>
  Order deny,allow
  Allow from all
</Proxy>

Change from 8081 to 8080 that should be it
