### ISSUE TITLE
terraform module error

### ISSUE THREAD

**Issue by ganeshkarthika** [QT-DevOps/DevOpsIssues#40]
I am not using any variable file to define the variables , I am trying to define in the same program/code

provider "aws" {
  access_key = "xxxx"
  secret_key = "xxxx"
  region     = "us-west-2c"
}

module "ec2-inst" {
  source = "terraform-aws-modules/ec2-instance/aws"

  name           = "ec2-inst"
  instance_count = 1

  ami                    = "ami-db710fa3"
  instance_type          = "t2.micro"
  key_name               = "tf_keypair"
  vpc_security_group_ids = ["sg-06cdc7b5f9ccaee35"]
  subnet_id              = "subnet-34385f6e"

  tags = {
    Terraform   = "true"
    Environment = "dev"
  }
}

error which I have received.
==================

Error: resource 'aws_instance.terraform_inst' config: unknown variable reference                                                      d: 'imageid'; define it with a 'variable' block

Error: resource 'aws_instance.terraform_inst' config: unknown variable reference                                                      d: 'instancetype'; define it with a 'variable' block

Error: resource 'aws_instance.terraform_inst' config: unknown variable reference                                                      d: 'keypair'; define it with a 'variable' block

Error: provider config 'aws': unknown variable referenced: 'region'; define it w                                                      ith a 'variable' block

Error: provider config 'aws': unknown variable referenced: 'accesskey'; define i                                                      t with a 'variable' block

**Comment by manikantagaddam** [comment]
please hardcode the value or go with the variable file if we use both then we will get  unknown variable referenced Error
and one thing u should give region name but u gave availabilty Zone and wen u are giving pem file as key name make sure that  pem is available in your desktop

**Comment by ganeshkarthika** [comment]
Hi Manikanta,

Thanks a lot you for your quick and timely support.
Definitely, will make a note of the corrections that are suggested by you.

**Comment by shaikkhajaibrahim** [comment]
Is the issue resolved?

**Comment by ganeshkarthika** [comment]
Yes Sir ,It got resolved on the same day.
Thanks a lot for the quick and timely support.
