### ISSUE TITLE
Build unstable 

### ISSUE THREAD

**Issue by Bkumar87** [QT-DevOps/DevOpsIssues#400]
![image](https://user-images.githubusercontent.com/49071695/55418125-fbf5c780-553f-11e9-8917-9fe587d7430e.png)

Hello Team, 
Please help me troubleshoot this issue with Jenkins.  I am trying to copy .war file to remote server, but build is unstable.  It is asking me to give target prefix in all the paths.  I have already configured that in all the paths.  

Below is the syntax i used to copy 

sshPublisher(publishers: [sshPublisherDesc(configName: 'dev_docker', transfers: [sshTransfer(excludes: '', execCommand: '', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '/home/mary/Docker', remoteDirectorySDF: false, removePrefix: 'target/', sourceFiles: '**/*.war')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: true)])

Thanks, 
Mary

**Comment by sunil3456** [comment]
change your source to target/*.war and remote dir to /home/mary 
lets me know how did u go!

**Comment by Bkumar87** [comment]
this error has been fixed Sunil.  Now stuck with deploying war to docker container.  Do you have a jenkins pipeline script to deploy war to container ? Tried to google it but none are working for me

**Comment by sunil3456** [comment]
build the image and push it to dockerhub 
https://github.com/sunil3456/Groovy
to do deployment go for another job which has to pull and run the container.
If you know ansible you can workout with yaml, using shell module

**Comment by Bkumar87** [comment]
This job needs to be done in one jenkins pipeline script ... end to end .  From building war file to deploying to container.  I will try the link you provided and update you the result. Thanks Sunil.

**Comment by Bkumar87** [comment]
Sunil, 
Do you have the code for declarative pipeline? Getting error saying needs steps and after adding steps also getting error 
![image](https://user-images.githubusercontent.com/49071695/55454569-588fcb80-55ae-11e9-8a5c-d75bb06c2670.png)

**Comment by shaikkhajaibrahim** [comment]
Try with Ansible i would suggest usage of unnecessary plugin's
