### ISSUE TITLE
Getting error while using kitchen command

### ISSUE THREAD

**Issue by venugopalkatukam** [QT-DevOps/DevOpsIssues#401]
------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Error parsing E:/chef/chef-repo/cookbooks/apache_cookbook/.kitchen.yml as YAML.
Please run `kitchen diagnose --no-instances --loader' to help debug your issue.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by sunil3456** [comment]
your issue is not clear!

**Comment by ghost** [comment]
please share logs

**Comment by ghost** [comment]
if its resolved please close the issue
