### ISSUE TITLE
Kubernets: Creating Highly Available Clusters with kubeadm

### ISSUE THREAD

**Issue by mad551985** [QT-DevOps/DevOpsIssues#402]
Creating Highly Available Clusters with kubeadm

My K8's setup is in AWS cloud with ubuntu 18.04 server

In my K8's cluster 1master & 2 nodes are present,
but my requirement is master should have Highly Available ( another server add to cluster as a master)

how to slove the issue ( 2 master & 2 nodes )
 i can add nodes with kubeadm join,  but how to add a node as a master in the cluster

my refer links are 
https://v1-10.docs.kubernetes.io/docs/tasks/tools/install-kubeadm/
https://v1-10.docs.kubernetes.io/docs/setup/independent/create-cluster-kubeadm/

Thank you
Madhava

**Comment by sunil3456** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/highly-available-master/

**Comment by mad551985** [comment]
tq sunil,

but am getting some errors by following the doccuments  , if u don't mine do have steps to setup another master? it would be helpful

Thanks

**Comment by sunil3456** [comment]
drop your errors here or screen shot. 
https://stackoverflow.com/questions/50498643/what-is-the-best-way-to-add-a-second-master-in-kubernetes-cluster

**Comment by nareshabbanapuri** [comment]
it's not possible with kubadm if u want please follow this link https://kubernetes.io/docs/setup/independent/high-availability/
