### ISSUE TITLE
Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space 

### ISSUE THREAD

**Issue by Karthick-Gopalakrishnan** [QT-DevOps/DevOpsIssues#403]
Team,
os: centos 7
tomcat version : 7.0
Java version: 1.8.0
Local vm running with 1 VCPU and 1 GB RAM

I got a file.war which i have deployed to tomcat/webapp post which am getting an error when i navigate to url 

![image](https://user-images.githubusercontent.com/48745218/55525086-ba306280-56a0-11e9-9618-2e410b3e7c59.png)

Google says to modify the Catalina sh . I couldn't figure where it is

When i do whereis tomcat 

![image](https://user-images.githubusercontent.com/48745218/55525243-64a88580-56a1-11e9-87eb-f47b05dc697f.png)

**Comment by sunil3456** [comment]
It’s memory issue
Open catalina.sh from tomcat/bin.
Change JAVA_OPTS 
Or run 
Java -Xmx256m -Xmx512m

**Comment by Karthick-Gopalakrishnan** [comment]
Hello Sunil,
i dont see catalina.sh in below path 

![image](https://user-images.githubusercontent.com/48745218/55532569-6bde8c00-56bf-11e9-88b3-f89183b40ed0.png)

**Comment by sunil3456** [comment]
try this path
/etc/init.d/tomcat7
ls -la
sudo find / -name "*catalina*.sh"

**Comment by Karthick-Gopalakrishnan** [comment]
Nopes!!

![image](https://user-images.githubusercontent.com/48745218/55537514-6c7e1f00-56cd-11e9-9252-564a8bbb52ac.png)

**Comment by sunil3456** [comment]
copy war file to /usr/share/tomcat/webapps

**Comment by Karthick-Gopalakrishnan** [comment]
that's where my war file is lying around... When i try to reach that ip in browser, i get that java heap space issue

**Comment by Karthick-Gopalakrishnan** [comment]
Sunil, 
I have increased my VM ram size and java memory space issue fixed. I will close the issue app started working. 

Still i couldnt figure out the place where we need to increase the memory space.

Thanks a lot for your assistance!!
