### ISSUE TITLE
error:unable to locate package php-mycrypt

### ISSUE THREAD

**Issue by gayithrikota** [QT-DevOps/DevOpsIssues#404]
when i use sudo apt-get install php libapache2-mod-php php-mcrypt php-mysql
reading package list .. done
building dependency  tree
Reading state information done
Package php-mcrypt is not available,but is referred to by another package
This means package is missing or obsoleted
Package php-mcrypt has no installation candidate

how to rectify?

**Comment by sunil3456** [comment]
PLease go through this links
https://askubuntu.com/questions/1031921/php-mcrypt-package-missing-in-ubuntu-server-18-04-lts

**Comment by ghost** [comment]
please find a document based on ur Linux os and version

**Comment by ghost** [comment]
please close ur issue if its resolved
