### ISSUE TITLE
Getting error While executing kitchen converge command.

### ISSUE THREAD

**Issue by venkatmamillapalli** [QT-DevOps/DevOpsIssues#405]
![image](https://user-images.githubusercontent.com/41816043/55535207-1b255e00-56d4-11e9-816a-191c47d5600f.png)

while executing kitchen converge command its asking root password.

my .kitchen.yml file is 

---
driver:
name: ec2
aws_ssh_key_id: march.pem 
region: us-east-1 
availability_zone: us-east-1b 
subnet_id: subnet-803ab6dc 
instance_type: t2.micro 
image_id:  ami-0a313d6098716f372 
security_group_ids: ["sg-0750d6489c88af419"]

provisioner:
name: chef_zero
# You may wish to disable always updating cookbooks in CI or other testing environments.
# For example:
#   always_update_cookbooks: <%= !ENV['CI'] %>
always_update_cookbooks: true

verifier:
name: inspec

transport:
ssh_key: ./march.pem # relative path to pem file
connection_timeout: 10
connection_retries: 5
username: ubuntu

platforms:
- name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[nginx_cookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

**Comment by shaikkhajaibrahim** [comment]
Change
aws_ssh_key_id: march.pem
To
aws_ssh_key_id: march

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by venkatmamillapalli** [comment]
Sir, I changed it .still i'm getting same error

**Comment by sunil3456** [comment]
its not best practise but try updating visudo
%sudo  ALL=(ALL) NOPASSWD:ALL

**Comment by shaikkhajaibrahim** [comment]
Execute kitchen converge - l debug
Share all the logs

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ghost** [comment]
if your issue is resolved please close your issue

**Comment by ghost** [comment]
plz upload cookbook

**Comment by santoshkalingwar** [comment]
Please upload cookbook,if you resolved please close issue

**Comment by bhaskardegala** [comment]
did you give user accessible permissions to your .pem file if not give the permission if you know how to if not try out following steps
---
first know your user by typing "whoami" in powershell then you will come to know your user and copy it
then open properties of your pem file by right clicking on your pem file
then open security and click on advanced and remove all users existing under permission entries to do that first click on disable inheritance then a prompt window will be opened an click on convert inheritance permissions ... and remove all the users  
later click on change beside owner then a small window will be opened then paste the copied username from powershell under 'enter the object name to select , and click on check name and ok 
then add the user under permission entries by clicking on add then click on 'select principle'  then a small window will be opened then paste the copied username from powershell under 'enter the object name to select , and click on check name and ok and then click on full control under basic permissions then click ok >> click apply >> click ok 
now try using kitchen converge and it works without asking password as it worked for me

even turn off your windows firewall and antivirus software(if you hvae)

**Comment by bhaskardegala** [comment]
If your issue was resolved please close the issue
