### ISSUE TITLE
ansible

### ISSUE THREAD

**Issue by mad551985** [QT-DevOps/DevOpsIssues#406]
Hi all,

I have installed python & ansible in ubuntu:18.04 (name: k8-Ansible)

sudo ansible user with ansible

root@k8-Ansible:~# vi /etc/ssh/sshd_config
PasswordAuthentication yes

visudo
# Allow members of group sudo to execute any command
%sudo   ALL=(ALL:ALL) ALL
ansible ALL=(ALL:ALL) NOPASSWD: ALL

ssh-keygen
ssh-copy-id ansible@localhost
ssh localhost

ansible@k8-Ansible:~$ cd /etc/ansible/
ansible@k8-Ansible:/etc/ansible$ ls
ansible.cfg  hosts  hosts2  roles
ansible@k8-Ansible:/etc/ansible$ sudo vi hosts
localhost
192.168.0.13  (private ip)

below error am getting 

ansible@k8-Ansible:~$ ansible -m ping all
192.168.0.191 | FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to 192.168.0.191 closed.\r\n",
    "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n",
    "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
    "rc": 127
}
localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}

**Comment by krohithram** [comment]
Hi, Have you copied SSH keys to 192.168.0.191 machine. please check once are you able to login to that machine without password or not. 

Once Password less authentication enabled and python installed on node then the issue will resolve.

**Comment by ghost** [comment]
1 give sudo permission -->  visudo
2 please enable password-based authentication --> vi /etc/ssh/sshd_config
3 restart ssh service --> systemctl restart ssh.service

**Comment by mad551985** [comment]
Hi all,

i got clear the below error 

here my Ansible Control Server is: ansible@k8-Ansible
              Ansible Node Server is : ansible@k8-Master

**Note: Ansible Control server python version & Ansible Node server python version should be same **


ansible@k8-ansible:~$ python --version
Python 2.7.15rc1

ansible@k8-Master:~$ python --version
Python 2.7.15rc1


**If version is different will get below error**

module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n",

Now am able to ping all ndes in hosts



========================
below error am getting 

ansible@k8-Ansible:~$ ansible -m ping all
192.168.0.191 | FAILED! => {
"changed": false,
"module_stderr": "Shared connection to 192.168.0.191 closed.\r\n",
"module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n",
"msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
"rc": 127
}
localhost | SUCCESS => {
"changed": false,
"ping": "pong"
}

**Comment by sunil3456** [comment]
install on ubuntu server and let me know
sudo apt install python-minimal python-simplejson

**Comment by dharmatejadevops** [comment]
> Hi all,
> 
> I have installed python & ansible in ubuntu:18.04 (name: k8-Ansible)
> 
> sudo ansible user with ansible
> 
> root@k8-Ansible:~# vi /etc/ssh/sshd_config
> PasswordAuthentication yes
> 
> visudo
> 
> # Allow members of group sudo to execute any command
> %sudo ALL=(ALL:ALL) ALL
> ansible ALL=(ALL:ALL) NOPASSWD: ALL
> 
> ssh-keygen
> ssh-copy-id ansible@localhost
> ssh localhost
> 
> ansible@k8-Ansible:~$ cd /etc/ansible/
> ansible@k8-Ansible:/etc/ansible$ ls
> ansible.cfg hosts hosts2 roles
> ansible@k8-Ansible:/etc/ansible$ sudo vi hosts
> localhost
> 192.168.0.13 (private ip)
> 
> below error am getting
> 
> ansible@k8-Ansible:~$ ansible -m ping all
> 192.168.0.191 | FAILED! => {
> "changed": false,
> "module_stderr": "Shared connection to 192.168.0.191 closed.\r\n",
> "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n",
> "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
> "rc": 127
> }
> localhost | SUCCESS => {
> "changed": false,
> "ping": "pong"
> }

you should copy the ssh-key (what you generate on ansible server) on node also  
ssh-copy-id user@node Public ip

**Comment by santoshkalingwar** [comment]
Create one user who has sudo permission
Then install python , put password authentication yes in ssh configuration file , restart the ssh service

**Comment by bhaskardegala** [comment]
Make sure your that your  node has python installed (as I see an error stating that it could not find python so connection is lost) and I found one error that you have not restarted sshd service i.e " service sshd restart" after you give the password authentication and this is not related to this node connectio
Please close the issue if it is resolved

**Comment by mad551985** [comment]
Hi all,

i got clear the below error

here my Ansible Control Server is: ansible@k8-Ansible
Ansible Node Server is : ansible@k8-Master

**Note: Ansible Control server python version & Ansible Node server python version should be same **

ansible@k8-ansible:~$ python --version
Python 2.7.15rc1

ansible@k8-Master:~$ python --version
Python 2.7.15rc1
