### ISSUE TITLE
Cookbook apache to be solved

### ISSUE THREAD

**Issue by shaikkhajaibrahim** [QT-DevOps/DevOpsIssues#408]
[my_lamp.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3056974/my_lamp.zip)

**Comment by Karthick-Gopalakrishnan** [comment]
Team,

If you are facing issue with executing the cookbook change 

```ruby
only_if  node['platform'] == 'ubuntu' to only_if { node['platform'] == 'ubuntu' }
```

**Comment by bhaskardegala** [comment]
> Team,
> 
> If you are facing issue with executing the cookbook change
> 
> ```ruby
> only_if  node['platform'] == 'ubuntu' to only_if { node['platform'] == 'ubuntu' }
> ```

it works fine for me
