### ISSUE TITLE
Jenkins: Not able to fetch github project in Jenkins

### ISSUE THREAD

**Issue by SaiSrikanth10** [QT-DevOps/DevOpsIssues#41]
I've installed Jenkins 2.127 version in my Windows 7 64 bit Operating system. When I try to create a free style project , I'm copying a github url and pasting in source code management section. But the following error is coming.

Please check below.
![image](https://user-images.githubusercontent.com/39853597/41462515-be544984-70b0-11e8-9538-4653bb229d59.png)

The following is the console output. 
![image](https://user-images.githubusercontent.com/39853597/41462640-1dd01028-70b1-11e8-97a0-091e63933918.png)

I've Git and Maven installed in my system. 

Thank you.

**Comment by shaikkhajaibrahim** [comment]
Is your machine connected to internet  while you are executing this

**Comment by SaiSrikanth10** [comment]
Yes it is.

**Comment by manikantagaddam** [comment]
git should be install in your local machine and configure the git path in manage jenkins ->configure system and try it.

**Comment by shaikkhajaibrahim** [comment]
Resolved??

**Comment by SaiSrikanth10** [comment]
Sir,
I've uninstalled Jenkins on windows and installed it on vagrant Ubuntu
14.04 and it's working fine. I need to take my friend's windows laptop to
test the above fix. I'll test that and see whether the above fix can
resolve the issue or not.

**Comment by manikantagaddam** [comment]
Closed?
