### ISSUE TITLE
Class: Kitchen::ClientError, unable to upload kicthen

### ISSUE THREAD

**Issue by ShauryaKashyap** [QT-DevOps/DevOpsIssues#410]
Hi Team,

Command "Kitchen list" giving the below error,

Please share the NPA to upload kitchen on AWS

Error:

 >>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'ec2' provisioner from the load path. Did you mean: chef_apply, chef_base, chef_solo, chef_zero, dokken, dummy, policyfile_zero, shell ? Please ensure that your provisioner is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

Please find the coombook file in attachment

 
[apache_cookbook.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3065332/apache_cookbook.zip)

**Comment by Naga-vineela** [comment]
try changing provisioner from ec2 to chef_zero 
provisioner:
  name: chef_zero

**Comment by ghost** [comment]
yes change to chef_zero  try this

**Comment by ghost** [comment]
please close the issue if solve

**Comment by ShauryaKashyap** [comment]
Hi,

I changed the provisioner name but  "Kitchen Create" command below error occurs.

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Microsoft SQL Server is not supported for the instance type 't2.micro'.] on default-ubuntu-1604
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

[apache_cookbook.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3069367/apache_cookbook.zip)

**Comment by ghost** [comment]
please check image-id

**Comment by ghost** [comment]
choose right image-id

**Comment by Naga-vineela** [comment]
Microsoft SQL Server is not supported for the instance type 't2.micro'- mean image which u selected doenot support instance t2.micro . either give higher resources like t2.large (doesnot cover under free tier) 
or select other AMI id .. like base ubuntu16.

i would suggest selecting diff AMI "Ubuntu Server 16.04 LTS (HVM), SSD Volume Type"

**Comment by ShauryaKashyap** [comment]
Hi All,

Thanks for the support now it is working.
I did two mistake first in "provisioner  name".  2nd in Image ID, I have not taken Ubuntu 16 image id.
after correcting these , It worked.

![image](https://user-images.githubusercontent.com/49370417/55977464-7e068e80-5cac-11e9-886a-7edefcfce1ca.png)
