### ISSUE TITLE
Net::HTTPServerException: 401 "Unauthorized" - berks upload

### ISSUE THREAD

**Issue by Karthick-Gopalakrishnan** [QT-DevOps/DevOpsIssues#412]
While executing berks upload it says Net::HTTPServerException: 401 "Unauthorized"

![image](https://user-images.githubusercontent.com/48745218/56348591-d7544d80-61d7-11e9-99f6-5183d7729228.png)

**Comment by ghost** [comment]
please upload cookbook

**Comment by Karthick-Gopalakrishnan** [comment]
issue is fixed, It was issue with time sync.
Installed ntp (centos) and started the service.

Thanks for your assistance!!
