### ISSUE TITLE
Berks install - chef supermarket

### ISSUE THREAD

**Issue by Naga-vineela** [QT-DevOps/DevOpsIssues#414]
Hello all , 
i am trying to use supermarket  . however berks install throws type error
matadata.rb file contains : 
depends 'ark', '~> 4.0.0'
i see there is already open issue for the same but raised on jan11 . Anyone has any idea on this ?

over view of error - also attached detailed log 

"Installing seven_zip (3.1.0)
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-libarchive-0.4.6/lib/ffi-libarchive.rb:3: warning: already initi
alized constant Archive::LIBPATH
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-libarchive-0.4.6/lib/ffi-libarchive.rb:3: warning: previous defi
nition of LIBPATH was here
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-libarchive-0.4.6/lib/ffi-libarchive.rb:4: warning: already initi
alized constant Archive::PATH
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-libarchive-0.4.6/lib/ffi-libarchive.rb:4: warning: previous defi
nition of PATH was here
Installing windows (5.3.0)
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-libarchive-0.4.6/lib/ffi-libarchive.rb:3: warning: already initi
alized constant Archive::LIBPATH
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-libarchive-0.4.6/lib/ffi-libarchive.rb:3: warning: previous defi
nition of LIBPATH was here
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-libarchive-0.4.6/lib/ffi-libarchive.rb:4: warning: already initi
alized constant Archive::PATH
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-libarchive-0.4.6/lib/ffi-libarchive.rb:4: warning: previous defi
nition of PATH was here
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-libarchive-0.4.6/lib/ffi-libarchive.rb:3: warning: already initi
alized constant Archive::LIBPATH
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-libarchive-0.4.6/lib/ffi-libarchive.rb:3: warning: previous defi
nition of LIBPATH was here
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-libarchive-0.4.6/lib/ffi-libarchive.rb:4: warning: already initi
alized constant Archive::PATH
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/ffi-libarchive-0.4.6/lib/ffi-libarchive.rb:4: warning: previous defi
nition of PATH was here
TypeError unable to resolve type 'mode_t'"
[berks_error.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3108023/berks_error.txt)

**Comment by bhaskardegala** [comment]
i was working on your issue and will let you know once it is done
that cookbook ark installed in berkshelf without any error for my environment(windows)
can you please let know on what environment you are working on linux or windows
i think you can find a solution from this link who got some error which is similar to yours in puppet 
[click here](https://github.com/ffi/ffi/issues/386)
just even try this add '#include <sys/stat.h>' line in ffi flie situated in "C:\opscode\chefdk\embedded\lib\libffi-3.2.1\include" and this includes "mode_t" , it should work and i think even it may not be the correct solution but i came with this after referring some articles

**Comment by Naga-vineela** [comment]
Thanks for looking into it . I tried to add mentioned line in the file and ran the berks install , however it failed with belo error .
OS: win7 
PS D:\Devops\Chef\chef-starter\chef-repo\cookbooks\supermarket_mysql> berks install
An error occurred while reading the Berksfile:

  The version constraint syntax you are using is not valid. If you recently
upgraded to Chef 0.10.0, be aware that you no may longer use "<<" and ">>" for
'less than' and 'greater than'; use '<' and '>' instead.
Consult https://docs.chef.io/config_rb_metadata.html for more information.

Called by: depends 'java', '~= 3.2.1'
Called from:
  C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/cookbook/metadata.rb:667:i
n `validate_version_constraint'
  C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/cookbook/metadata.rb:291:i
n `depends'
  D:/Devops/Chef/chef-starter/chef-repo/cookbooks/supermarket_mysql/metadata.rb:13:in `from_file'
  C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/mixin/from_file.rb:34:in `
instance_eval'
  C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/mixin/from_file.rb:34:in `
from_file'

**Comment by bhaskardegala** [comment]
i think there is some syntactical error in your metadata file
first try using "foodcritic" in powershell where your cookbook is present so it will evaluate your cookbook and let you know if there are any syntactical errors in your cookbook so that we can proceed our investigation further or some how your your metadata file in C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/cookbook/ is messed up and i suggest one more solution which is not a good practice at all try to reinstall your chefdk and once again download chef-repo from client server do this when you couldn't find any solution

**Comment by Naga-vineela** [comment]
created new linux workstation and new starter kit . It worked there . 
on my current lappy top its stil issue , not sure if it  has got to do any thing with any version of tools.

Closing this thread , Thanks Bhaskar,for looking into it
