### ISSUE TITLE
test build failed in jenkins in windows

### ISSUE THREAD

**Issue by bhargavsindu** [QT-DevOps/DevOpsIssues#415]
installed jdk8 through choco
downloaded Jenkins.war
Jenkins setup is done..while creating new item with freestyle project created shell file as shown in example, while building it is saying build failed..
![image](https://user-images.githubusercontent.com/49969967/56708833-da9d8b00-673b-11e9-880e-83bee55edef9.png)

**Comment by sunil3456** [comment]
You are executing shell script in windows
https://superuser.com/questions/120045/how-to-execute-sh-file-on-windows

**Comment by bhaskardegala** [comment]
if you are using windows select "execute windows batch command" instead of "execute shell" in build and you can find commands that works on windows from this link [click here](https://devblogs.microsoft.com/scripting/table-of-basic-powershell-commands/)

**Comment by ghost** [comment]
yes
try execute batch commands

**Comment by santoshkalingwar** [comment]
Select execute batch file give the script to there it will execute

**Comment by bhargavsindu** [comment]
Resolved
