### ISSUE TITLE
Create the directory mkdir jenkins cd jenkins ,vagrant box add bento/ubuntu16.04, vagrant init bento/ubuntu16.04

### ISSUE THREAD

**Issue by jdp11** [QT-DevOps/DevOpsIssues#416]
when run the command vagrant vagrant up .
getting the below message.
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Verifying Hyper-V is accessible...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: check_hyperv_access.ps1
Error:

where : Exception calling "Translate" with "1" argument(s): "Some or all identity references could not be translated."
At C:\HashiCorp\Vagrant\embedded\gems\2.2.4\gems\vagrant-2.2.4\plugins\providers\hyperv\scripts\utils\VagrantVM\VagrantVM.psm1:721 char:32

$systemACL = $acl.Access | where {
                           ~~~~~~~
CategoryInfo : NotSpecified: (:) [Where-Object], MethodInvocationException
FullyQualifiedErrorId : IdentityNotMappedException,Microsoft.PowerShell.Commands.WhereObjectCommand
is the above error ignorable or any corrections need to be done, i am working on windows 10 non home edition

**Comment by santoshkalingwar** [comment]
Please check you vt is enabled


Please tell us how you creating then only we can resolve

**Comment by bhaskardegala** [comment]
i think image that we need to use was bento/ubuntu-16.04

**Comment by dharmatejadevops** [comment]
> when run the command vagrant vagrant up .
> getting the below message.
> Bringing machine 'default' up with 'hyperv' provider...
> ==> default: Verifying Hyper-V is enabled...
> ==> default: Verifying Hyper-V is accessible...
> An error occurred while executing a PowerShell script. This error
> is shown below. Please read the error message and see if this is
> a configuration error with your system. If it is not, then please
> report a bug.
> 
> Script: check_hyperv_access.ps1
> Error:
> 
> where : Exception calling "Translate" with "1" argument(s): "Some or all identity references could not be translated."
> At C:\HashiCorp\Vagrant\embedded\gems\2.2.4\gems\vagrant-2.2.4\plugins\providers\hyperv\scripts\utils\VagrantVM\VagrantVM.psm1:721 char:32
> 
> $systemACL = $acl.Access | where {
> ~~~~~~~
> CategoryInfo : NotSpecified: (:) [Where-Object], MethodInvocationException
> FullyQualifiedErrorId : IdentityNotMappedException,Microsoft.PowerShell.Commands.WhereObjectCommand
> is the above error ignorable or any corrections need to be done, i am working on windows 10 non home edition
once try  hyper-v box other than bento/ubuntu-16.04( like geniric ubuntu etc..)
because i faced some issue with hyper-v with box bento/ubuntu-16.04  then i tried another one its working.
