### ISSUE TITLE
Jenkins status 

### ISSUE THREAD

**Issue by ghost** [QT-DevOps/DevOpsIssues#417]
![jenkins images](https://user-images.githubusercontent.com/49831402/56809042-8b954a00-6850-11e9-9ea3-3c68c5088584.PNG)

***
ubuntu@ip-172-31-19-119:~$ systemctl status jenkins
● jenkins.service - LSB: Start Jenkins at boot time
   Loaded: loaded (/etc/init.d/jenkins; generated)
   Active: active (exited) since Fri 2019-04-26 12:48:13 UTC; 36s ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 0 (limit: 1152)
   CGroup: /system.slice/jenkins.service

Apr 26 12:48:12 ip-172-31-19-119 systemd[1]: Starting LSB: Start Jenkins at boot time...
Apr 26 12:48:12 ip-172-31-19-119 jenkins[8692]: Correct java version found
Apr 26 12:48:12 ip-172-31-19-119 jenkins[8692]:  * Starting Jenkins Automation Server jenkins
Apr 26 12:48:12 ip-172-31-19-119 su[8738]: Successful su for jenkins by root
Apr 26 12:48:12 ip-172-31-19-119 su[8738]: + ??? root:jenkins
Apr 26 12:48:12 ip-172-31-19-119 su[8738]: pam_unix(su:session): session opened for user jenkins by (uid=0)
Apr 26 12:48:12 ip-172-31-19-119 su[8738]: pam_unix(su:session): session closed for user jenkins
Apr 26 12:48:13 ip-172-31-19-119 jenkins[8692]:    ...done.
Apr 26 12:48:13 ip-172-31-19-119 systemd[1]: Started LSB: Start Jenkins at boot time.
ubuntu@ip-172-31-19-119:~$ sudo ufw allow 8080
Rules updated
Rules updated (v6)
ubuntu@ip-172-31-19-119:~$ sudo ufw status
Status: inactive
***

![jenkins app](https://user-images.githubusercontent.com/49831402/56810454-f5632300-6853-11e9-8f56-4202a6c221b6.PNG)

not connecting jenkins server

**Comment by dharmatejadevops** [comment]
You need ufw status active then enable it and check the list of ports is allowed 

https://hostpresto.com/community/tutorials/install-and-configure-ufw-firewall-on-ubuntu-16-04/nd


If the machine is from aws cloud add 8080rule on security group

**Comment by Karthick-Gopalakrishnan** [comment]
Am running jenkins in local VM, In my case i didn't enable the firewall it is not required 

ufw (Uncomplicated Firewall) if it is disabled by default it will allow all sorts of ports to be used. If is it VM running in AWS/AZURE allow 8080 as **TEJA**  said .

**Comment by santoshkalingwar** [comment]
Did you access that using private ip or public , if you are accessing using public ip did you checked is it pinging form your machine

**Comment by ghost** [comment]
Thanks for your information, 
Yes i have created in AWS and enabled 8080 port

i used **https** so that's why jenkins server not opened,

**Comment by bhaskardegala** [comment]
> Thanks for your information,
> Yes i have created in AWS and enabled 8080 port
> 
> i used **https** so that's why jenkins server not opened
hey jura thanks for sharing resolution for your issue { we need to give http not https} and i hope your issue was resolved if yes please close the issue

**Comment by ghost** [comment]
enable port 8080 in inbound rules
and http://publicip:8080
follow this

**Comment by rightpay22** [comment]
Thank you it helped me a lot
