### ISSUE TITLE
vagrant up error

### ISSUE THREAD

**Issue by sirishkumarp1287** [QT-DevOps/DevOpsIssues#418]
PS C:\temp\jenkins> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/xenial64' version '20190426.0.0' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "47ebfb82-7d4c-49f2-a4fa-aadb1f8e709a", "--type", "headless"]

Stderr: VBoxManage.exe: error: Not in a hypervisor partition (HVP=0) (VERR_NEM_NOT_AVAILABLE).
VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

**Comment by santoshkalingwar** [comment]
Please enable virtualation in your systems BIOS

**Comment by sirishkumarp1287** [comment]
thankyou santhosh

**Comment by santoshkalingwar** [comment]
If it fix please close issue
