### ISSUE TITLE
Duplicate project

### ISSUE THREAD

**Issue by sandeep5683** [QT-DevOps/DevOpsIssues#419]
hi while i m creating new freestyle project in jenkins portal, the project will creating 4 times in the same way. please let me know how to sort it out.

**Comment by santoshkalingwar** [comment]
Why you want to create same project 4 times at same time

**Comment by bhaskardegala** [comment]
Hi Sandeep
I didn't get your question exactly I was expecting that your are trying to create multiple projects with same name but I think it is not possible to create a multiple projects with same name

**Comment by santoshkalingwar** [comment]
With same name ,you cannot create multiple project

**Comment by sandeep5683** [comment]
i created it only  once but 3 more duplicate project also creating with same nature without my intention, how can i fix it

**Comment by bhaskardegala** [comment]
hi sandeep 
if possible share screen some shots of those duplicate projects (or) just remove your jenkins home directory and install it once again
