### ISSUE TITLE
ubuntu machine error

### ISSUE THREAD

**Issue by ghost** [QT-DevOps/DevOpsIssues#42]
hi,
 i don't know why what happend but my ubuntu machine is automatically signing off showing error like this
i have posted screenshot related to that

![screenshot 2](https://user-images.githubusercontent.com/39849480/41504970-b390b3b8-721b-11e8-85ec-4313273f3911.png)

**Comment by SarfrazPNQ** [comment]
Have you opened port 80 for Nginx ?

**Comment by ghost** [comment]
no i din't

**Comment by shaikkhajaibrahim** [comment]
Please correct the spelling of nginx

**Comment by ghost** [comment]
yha i have  obseverd that and had corrected but getting the same problem sir

**Comment by shaikkhajaibrahim** [comment]
Refer https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/TroubleshootingInstancesConnecting.html


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ghost** [comment]
thanks for the suggestion sir , i will go over that and look back to u if still problem araises__
