### ISSUE TITLE
Jenkins Project - Workspace projects folder empty

### ISSUE THREAD

**Issue by Sanad09** [QT-DevOps/DevOpsIssues#420]
Hello,

I created 3 project in Jenkins, I can see the job and execution contents but I do not see anything in my workspace project folders (I can see the project but noting inside their folders):

root@ip-172-31-37-237:/var/lib/jenkins/workspace# ll
total 20
drwxr-xr-x 5 jenkins jenkins 4096 Apr 27 07:11 ./
drwxr-xr-x 15 jenkins jenkins 4096 Apr 27 07:15 ../
drwxr-xr-x 2 jenkins jenkins 4096 Apr 26 01:39 helloworld/
drwxr-xr-x 2 jenkins jenkins 4096 Apr 27 07:02 project2/
drwxr-xr-x 2 jenkins jenkins 4096 Apr 27 07:11 project3/
root@ip-172-31-37-237:/var/lib/jenkins/workspace# cd helloworld/
root@ip-172-31-37-237:/var/lib/jenkins/workspace/helloworld# ls
root@ip-172-31-37-237:/var/lib/jenkins/workspace/helloworld# ls -la
total 8
drwxr-xr-x 2 jenkins jenkins 4096 Apr 26 01:39 .
drwxr-xr-x 5 jenkins jenkins 4096 Apr 27 07:11 ..
root@ip-172-31-37-237:/var/lib/jenkins/workspace/helloworld# cd ../project2
root@ip-172-31-37-237:/var/lib/jenkins/workspace/project2# ls -la
total 8
drwxr-xr-x 2 jenkins jenkins 4096 Apr 27 07:02 .
drwxr-xr-x 5 jenkins jenkins 4096 Apr 27 07:11 ..
root@ip-172-31-37-237:/var/lib/jenkins/workspace/project2#

Regards,

**Comment by bhaskardegala** [comment]
Let me know one thing did you build them atleast once
If the answer was no first build it
If yes is your build succes for our reference please share your console output details if possible atleast screen shot

**Comment by santoshkalingwar** [comment]
Please send you log and how you create project in Jenkins , attache screenshot then we able to understand what is the issue

**Comment by Sanad09** [comment]
Hello Santosh/Bhaskar,

Thank you both for looking into this (I have been posting my questions int he wrong place until recently when bhaskar emailed me :( ).

Yes Bhaskar, I have build project and exited them (some were success and some failed). 
I am attaching screenshot go hello world project which was a success yet I do not see any files/folders inside the workspace for that project. Let me know how I can obtain more  log if needed?

/Users/Maradwi/Desktop/hellowworld project.png

**Comment by bhaskardegala** [comment]
> Hello Santosh/Bhaskar,
> 
> Thank you both for looking into this (I have been posting my questions int he wrong place until recently when bhaskar emailed me :( ).
> 
> Yes Bhaskar, I have build project and exited them (some were success and some failed).
> I am attaching screenshot go hello world project which was a success yet I do not see any files/folders inside the workspace for that project. Let me know how I can obtain more log if needed?
> 
> /Users/Maradwi/Desktop/hellowworld project.png

Hey Sanad 
You just try cloning some thing from git-hub this should definitely show some changes in our work space if not try to reinstall Jenkins at once as the basic commands like pwd who am I does not change anything thing in your work space

**Comment by Sanad09** [comment]
Yes, I tried the Game of life and I do see files there now. Also got the "target " folder after successfully running maven test and package in the Build

**Comment by bhaskardegala** [comment]
> Yes, I tried the Game of life and I do see files there now. Also got the "target " folder after successfully running maven test and package in the Build

I think your issue was resolved, if yes  then please close the issue
