### ISSUE TITLE
Removing Projects from CLI

### ISSUE THREAD

**Issue by Sanad09** [QT-DevOps/DevOpsIssues#421]
Hello,

I was experimenting on removing a project from CLI, I went to the jobs folder and ran #rm -rf ProjectName. 

I refreshed Jenkins master webpage but I still saw the project, I restarted Jenkins #service jenkins restart --> and only then I could see in UI that the Project is no longer there. Is there a better way to remove a project from CLI ?

Regards,

**Comment by bhaskardegala** [comment]
Hey Sanad 
I found something from google just refer it will definitely help you out [click here](https://stackoverflow.com/questions/13052390/jenkins-remove-old-builds-with-command-line)

**Comment by sunil3456** [comment]
https://stackoverflow.com/questions/3410141/how-do-i-clear-my-jenkins-hudson-build-history

**Comment by ghost** [comment]
it may help to you
https://mirzazeyrek.wordpress.com/2017/02/10/how-to-delete-jobs-in-jenkins/

**Comment by bhaskardegala** [comment]
Is your issue still unresolved

**Comment by shaikkhajaibrahim** [comment]
Is it fixed. If fixed close the issue with resolution
