### ISSUE TITLE
master-node connection issue

### ISSUE THREAD

**Issue by ghost** [QT-DevOps/DevOpsIssues#422]
Master node
-jdk,jenkins,git,maven installed
-java env set
-added user
-keygenerate 

Node
-jdk,maven installed
-jave env set
-add user

can you help me on his how to fix this issue

![2](https://user-images.githubusercontent.com/49831402/56880686-591b6500-6a7b-11e9-9edd-39ef28d3dfcc.JPG)
![3](https://user-images.githubusercontent.com/49831402/56880687-591b6500-6a7b-11e9-80ca-2ab9cfa73ef6.JPG)
![12](https://user-images.githubusercontent.com/49831402/56880689-59b3fb80-6a7b-11e9-90d1-dd11c554a064.JPG)

**Comment by ghost** [comment]
jenkins@ip-172-31-30-243:~$ ssh-copy-id jenkins@172.31.26.47
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/jenkins/.ssh/id_rsa.pub"
The authenticity of host '172.31.26.47 (172.31.26.47)' can't be established.
ECDSA key fingerprint is SHA256:uUzrkuPD/ZcHaOoKMk38cE3nUvuAB/Xe/ahqgP43GKc.
Are you sure you want to continue connecting (yes/no)? yes
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
jenkins@172.31.26.47: Permission denied (publickey).
jenkins@ip-172-31-30-243:~$

**Comment by bhaskardegala** [comment]
Did you copy public key to the node if no try to copy public key to the node first

**Comment by bhaskardegala** [comment]
> jenkins@ip-172-31-30-243:$ ssh-copy-id jenkins@172.31.26.47
> /usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/jenkins/.ssh/id_rsa.pub"
> The authenticity of host '172.31.26.47 (172.31.26.47)' can't be established.
> ECDSA key fingerprint is SHA256:uUzrkuPD/ZcHaOoKMk38cE3nUvuAB/Xe/ahqgP43GKc.
> Are you sure you want to continue connecting (yes/no)? yes
> /usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
> /usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
> jenkins@172.31.26.47: Permission denied (publickey).
> jenkins@ip-172-31-30-243:$

I think you did not generate key in home directory but attempting to copy it , so make sure that key was generated in home directory and you copy the key From home directory

**Comment by santoshkalingwar** [comment]
You have to generate key in Jenkins user and copy it in nodes Jenkins user 

Following document will help you

https://www.google.com/amp/s/www.howtoforge.com/tutorial/ubuntu-jenkins-master-slave/amp/

**Comment by ghost** [comment]
i have generated key - this master
jenkins@ip-172-31-25-104:~$ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/home/jenkins/.ssh/id_rsa):
Created directory '/home/jenkins/.ssh'.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /home/jenkins/.ssh/id_rsa.
Your public key has been saved in /home/jenkins/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:ZMg5tv37dFF7UGlhvBQFK4Uk/Q/FXBfkePd9mOSfBs4 jenkins@ip-172-31-25-104
The key's randomart image is:
+---[RSA 2048]----+
|          .o..=X%|
|     . o   .o.+B=|
|      * o   .o*++|
|     . *     ++*=|
|      . S    .=+=|
|         .  o .o=|
|          . .E.o.|
|           o ..  |
|          ...    |
+----[SHA256]-----+

**Comment by sunil3456** [comment]
You need to copy the ssh key where Jenkins is looking for!! Check this out
Cat /home/Jenkins/.ssh/known_hosts

**Comment by anon-42** [comment]
use ssh-copy-d jenkins@<ip of node>
try to connect from master using "ssh jenkins@<ip of node> " to test ssh is working

**Comment by nagireddy-9** [comment]
please try this steps 
on master:
as a jenkins user@=> ssh-keygen
=> ssh-copy-id  node-user-name@node-ip
and try whether both are pinging or not 
ssh <node-user-name@ip-of-node> or ssh  if-of-node

**Comment by ghost** [comment]
@sunil3456 
root@ip-172-31-19-217:~# cat /home/jenkins/.ssh/known_hosts
|1|YcPHF5jmF61EmwkdnT24IG7UdLo=|/eJrBdpOB6R2otZS01bv4dbAi20= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJocAcgfT16iQsHFeP9Ru3E3wd4wWtM6aJKvHzpRSLY3bYmQ6/fINjrAC2Ai1nogg2Y7YY/MTTYn2wgp5sXzY94=

**Comment by ghost** [comment]
@nagireddy-9 

jenkins@ip-172-31-19-217:~$ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/home/jenkins/.ssh/id_rsa):
Created directory '/home/jenkins/.ssh'.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /home/jenkins/.ssh/id_rsa.
Your public key has been saved in /home/jenkins/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:bw/8ok4lXwQoA+3hsw+lKtzydxu+Ae14J9T4gIfa/Ek jenkins@ip-172-31-19-217
The key's randomart image is:
+---[RSA 2048]----+
|    .o   ..      |
|      = .  .     |
|     o +    .    |
|      ++.o .     |
|      +=S o .    |
|     ++* O .     |
| . ...+oE O      |
|  + o .*oB.+     |
|   +.. oO+ .o    |
+----[SHA256]-----+
jenkins@ip-172-31-19-217:~$ ssh-copy-id jenkins@172.31.19.153
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/jenkins/.ss                      h/id_rsa.pub"
The authenticity of host '172.31.19.153 (172.31.19.153)' can't be established.
ECDSA key fingerprint is SHA256:Sd81mryKPZwo6PwYsHFj8r5PUSvNVrFEkTlibduCAkk.
Are you sure you want to continue connecting (yes/no)? yes
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter                       out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompt                      ed now it is to install the new keys
jenkins@172.31.19.153: Permission denied (publickey).

**Comment by ghost** [comment]
@anon-42 
root@ip-172-31-19-217:~# ssh 172.31.19.153
The authenticity of host '172.31.19.153 (172.31.19.153)' can't be established.
ECDSA key fingerprint is SHA256:Sd81mryKPZwo6PwYsHFj8r5PUSvNVrFEkTlibduCAkk.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '172.31.19.153' (ECDSA) to the list of known hosts.
root@172.31.19.153: Permission denied (publickey).

**Comment by dharmatejadevops** [comment]
give the passwordauthenticatin yes on /etc/ssh/sshd_confg of  node(user- jenkins) then restrt the sshd and try it

**Comment by ghost** [comment]
@devopslearningteja - Yes i given 
now working - thanks to all for your suggestion

**Comment by dharmatejadevops** [comment]
> @devopslearningteja - Yes i given
> now working - thanks to all for your suggestion

ok , if issue solved close the issue...
