### ISSUE TITLE
Cant edit environment variable in ubuntu, saying readonly

### ISSUE THREAD

**Issue by bhargavsindu** [QT-DevOps/DevOpsIssues#423]
Created  a ubuntu machine in AWS and installed java. while setting env variable it is showing readonly file , I can not insert the JAVA_HOME path and cant save.

**Comment by sandhyadev** [comment]
use this command:
sudo nano /etc/environment
 It will work.

**Comment by sunil3456** [comment]
If you want to edit file go with sudo it will give you permission to edit.

**Comment by bhargavsindu** [comment]
Thank you its working
