### ISSUE TITLE
Jenkins intsllation issue

### ISSUE THREAD

**Issue by bhargavsindu** [QT-DevOps/DevOpsIssues#424]
![image](https://user-images.githubusercontent.com/49969967/56941575-ec63a180-6b32-11e9-8906-ece20d990f7c.png)

**Comment by sunil3456** [comment]
please follow the link while installing jenkins
https://www.digitalocean.com/community/tutorials/how-to-install-jenkins-on-ubuntu-18-04

**Comment by anon-42** [comment]
You haven't added the repository for installing jenkins

**Comment by nagireddy-9** [comment]
please go through always official website of jenkins is better
https://wiki.jenkins.io/display/JENKINS/Installing+Jenkins+on+Ubuntu

**Comment by sohailfaizan** [comment]
Please follow the link.
https://github.com/asquarezone/DevOpsClassRoom/blob/master/JenkinsClassRoom/setup.md

**Comment by dharmatejadevops** [comment]
please add repository

**Comment by bhaskardegala** [comment]
i think your issue was resolved so please close the issue if your issue was not resolved let us know we will try to help you further
