### ISSUE TITLE
tomcat error after deploy war file

### ISSUE THREAD

**Issue by pravin-07** [QT-DevOps/DevOpsIssues#426]
i have got the error after deploy war file.

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu May 02 11:11:11 IST 2019
There was an unexpected error (type=Internal Server Error, status=500).
I/O error on POST request for "https://qah1-appstore.e-pragati.in/AppStore/store/v1/users": Connection reset; nested exception is java.net.SocketException: Connection reset

![image](https://user-images.githubusercontent.com/39874060/57058105-747caf00-6ccb-11e9-8f23-c4c0e38d50b4.png)
![Capture](https://user-images.githubusercontent.com/39874060/57058124-8d856000-6ccb-11e9-97b2-20f3b43234bd.JPG)

**Comment by anon-42** [comment]
It looks like a java error, please refer this https://stackoverflow.com/questions/31134333/this-application-has-no-explicit-mapping-for-error OR try with some other war file, If you are still getting the same error with another war file , please update

**Comment by ghost** [comment]
it may help you
https://www.logicbig.com/tutorials/spring-framework/spring-boot/disable-default-error-page.html

**Comment by pravin-07** [comment]
> 
> 
> it may help you
> https://www.logicbig.com/tutorials/spring-framework/spring-boot/disable-default-error-page.html

thanks for the reply ...their is some domain issues..now resolved.
