### ISSUE TITLE
Git push

### ISSUE THREAD

**Issue by Naveenchalla900** [QT-DevOps/DevOpsIssues#428]
Hi team,

git push                                                                     
fatal: The current branch customerA has no upstream branch.  
 To push the current branch and set the remote as upstream, use                                                                                                        git push --set-upstream origin customerA
--

git push origin master                                                        
 git@github.com: Permission denied (publickey).                                  
 fatal: Could not read from remote repository.                                                                                                                     Please make sure you have the correct access rights                             
 and the repository exists.
--
Tried the resolutions from Related issue But not resolved 
Please Help me on this

Thanks
naveen

**Comment by bhaskardegala** [comment]
Hey Naveen 
Let me know one thing are you trying to push to your remote git hub repository or some one else

**Comment by bhaskardegala** [comment]
If you don't have any repository in your git hub try to create one first

**Comment by ghost** [comment]
create a remote repository and add to the local repository and then push

**Comment by Naveenchalla900** [comment]
Hi team,

i created Remote repository and added to Local Repository,But tried to push
Getting the same issue

git remote add origin git@github.com:Naveenchalla900/my-first.git


Thanks & Regards
naveen

**Comment by shaikkhajaibrahim** [comment]
This seems to be url for SSH authentication do you have your SSH keys placed or try https

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bhaskardegala** [comment]
Yes try using https instead of git it might help you
