### ISSUE TITLE
unable to push

### ISSUE THREAD

**Issue by sandeep5683** [QT-DevOps/DevOpsIssues#429]
while i am trying push to remote i am getting this error "SANDEEP@github.com: Permission denied (publickey).
fatal: Could not read from remote repository", please let me know how to fix this.

**Comment by ghost** [comment]
git remote add origin https://github.com/username/reponame.git
git push -u origin master
please follow this

**Comment by sandeep5683** [comment]
![image](https://user-images.githubusercontent.com/48408567/57173609-27761580-6e50-11e9-8e86-9a0517737251.png)

**Comment by sandeep5683** [comment]
Still i got this issue

**Comment by bhaskardegala** [comment]
Better once remove your .git folder and start it once again and may I know the steps that you have used from the very first step git init and even I  noticed that in your previous step you did not give any repository name it was empty first create a repository in your git hub and then u can find URL for your repository after that use git remote add (your url) it should work out

**Comment by bhaskardegala** [comment]
> Still i got this issue

The url you have used was not correct 
It should somehow look like https://github.com/(git hub name)/(your repository name ) 
For this you need to first create a repository in git hub first

**Comment by ghost** [comment]
git remote add origin https://github.com/username/reponame.git
git push -u origin master
please follow this

**Comment by ghost** [comment]
…or create a new repository on the command line
echo "# tomcat" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/username/tomcat.git
git push -u origin master
…or push an existing repository from the command line
git remote add origin https://github.com/username/tomcat.git
git push -u origin master
