### ISSUE TITLE
Terraform Machine provision on azure

### ISSUE THREAD

**Issue by gvharikrishna** [QT-DevOps/DevOpsIssues#43]
While provisioning the VM in Azure, I have keep getting the following error with windows.

![image](https://user-images.githubusercontent.com/28618322/41514493-031a9dfa-72c5-11e8-878c-80d4cd2b85d3.png)

here it my main.tf configuration
provider "azurerm" {
  subscription_id = "${var.AZURE_SUBSCRIPTION_ID}"
  client_id       = "${var.AZURE_CLIENT_ID}"
  client_secret   = "${var.AZURE_CLIENT_SECRET}"
  tenant_id       = "${var.AZURE_TENANT_ID}"
}

resource "azurerm_resource_group" "res_group" {
  name     = "terraformresourcegroup"
  location = "eastus"
}

resource "azurerm_storage_account" "storage_acc" {
  name                     = "mystorageaccount20180"
  resource_group_name      = "${azurerm_resource_group.res_group.name}"
  location                 = "${azurerm_resource_group.res_group.location}"
  account_tier             = "Standard"
  account_replication_type = "LRS"

  tags {
    environment = "Storage-Acount-Test"
  }
}

# Create a virtual network within the resource group
resource "azurerm_virtual_network" "my_virt_net" {
  name                = "production-network"
  address_space       = ["10.0.0.0/16"]
  resource_group_name = "${azurerm_resource_group.res_group.name}"
  location            = "${azurerm_resource_group.res_group.location}"
}

#create subnets
resource "azurerm_subnet" "test1" {
  name                 = "subnet1"
  resource_group_name  = "${azurerm_resource_group.res_group.name}"
  virtual_network_name = "prod1"

  #  virtual_network_name = "${azurerm_virtual_network.my_virt_net.name}"
  address_prefix = "10.0.5.0/24"
}

#Create Public IP

resource "azurerm_public_ip" "datasourceip" {
  name                         = "testPublicIp"
  location                     = "${azurerm_resource_group.res_group.location}"
  resource_group_name          = "${azurerm_resource_group.res_group.name}"
  public_ip_address_allocation = "Dynamic"
}

resource "azurerm_subnet" "test2" {
  name                = "subnet2"
  resource_group_name = "${azurerm_resource_group.res_group.name}"

  #  virtual_network_name = "${azurerm_virtual_network.my_virt_net.name}"
  virtual_network_name = "prod2"
  address_prefix       = "10.0.6.0/24"
}

resource "azurerm_subnet" "test3" {
  name                 = "subnet3"
  resource_group_name  = "${azurerm_resource_group.res_group.name}"
  virtual_network_name = "prod3"

  #virtual_network_name = "${azurerm_virtual_network.my_virt_net.name}"
  address_prefix = "10.0.7.0/24"
}

#Create network interface

resource "azurerm_network_interface" "my_int" {
  name                = "myWindowsServer_NIC"
  location            = "${azurerm_resource_group.res_group.location}"
  resource_group_name = "${azurerm_resource_group.res_group.name}"

  #network_security_group_id = "${var.vm_security_group_id}"
  ip_configuration {
    name                          = "Server2016"
    subnet_id                     = "${azurerm_subnet.test1.id}"
    private_ip_address_allocation = "dynamic"
    public_ip_address_id          = "${azurerm_public_ip.datasourceip.id}"
  }
}

resource "azurerm_managed_disk" "test" {
  name                 = "datadisk_existing"
  location             = "${azurerm_resource_group.res_group.location}"
  resource_group_name  = "${azurerm_resource_group.res_group.name}"
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "1023"
}

resource "azurerm_virtual_machine" "test" {
  name                             = "myvm"
  location                         = "${azurerm_resource_group.res_group.location}"
  resource_group_name              = "${azurerm_resource_group.res_group.name}"
  network_interface_ids            = ["${azurerm_network_interface.my_int.id}"]
  vm_size                          = "Standard_DS1_v2"
  delete_os_disk_on_termination    = "true"
  delete_data_disks_on_termination = "true"

  storage_image_reference {
    publisher = "${var.vm_image_publisher}"
    offer     = "${var.vm_image_offer}"
    sku       = "${var.vm_image_sku}"
    version   = "${var.vm_image_version}"
  }

  storage_os_disk {
    name              = "datadisk_new_2018_01"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  # Adding additional disk 1

  storage_data_disk {
    name              = "datadisk_new"
    managed_disk_type = "Standard_LRS"
    create_option     = "Empty"
    lun               = 0
    disk_size_gb      = "1023"
  }

  #Additional disk 2

  storage_data_disk {
    name            = "${azurerm_managed_disk.test.name}"
    managed_disk_id = "${azurerm_managed_disk.test.id}"
    create_option   = "Attach"
    lun             = 1
    disk_size_gb    = "${azurerm_managed_disk.test.disk_size_gb}"
  }
  #define credentials
  os_profile {
    computer_name  = "SERVER2016"
    admin_username = "${var.VM_ADMIN}"
    admin_password = "${var.VM_PASSWORD}"
  }
  os_profile_windows_config {
    provision_vm_agent        = "true"
    enable_automatic_upgrades = "true"

    winrm {
      protocol        = "http"
      certificate_url = ""
    }
  }
}

#get public IP
data "azurerm_public_ip" "test" {
  name                = "${azurerm_public_ip.datasourceip.name}"
  resource_group_name = "${azurerm_resource_group.res_group.name}"
  depends_on          = ["azurerm_virtual_machine.test"]
}

output "ip_address" {
  value = "${data.azurerm_public_ip.test.ip_address}"
}

Thanks,
Hari

**Comment by shaikkhajaibrahim** [comment]
Why are you having two virtual_network_name sections in subnet

![image](https://user-images.githubusercontent.com/2438317/41579396-795d21be-73b4-11e8-898e-64221876a027.png)

**Comment by gvharikrishna** [comment]
while troubleshooting, i have tried to given name directly and varable, forgot to comment in the shared version, but even if i disabled, am getting the same error.

**Comment by gvharikrishna** [comment]
Sorry, if i am asking one more question,  when i ran terraform init in the folder.  following error throwing.  tried online, but couldnt get proper solution.

Error: Unknown root level key: provisioner

**Comment by shaikkhajaibrahim** [comment]
Zip your script & share

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gvharikrishna** [comment]
can you share your email id, so that i will share keys as well

**Comment by gvharikrishna** [comment]
[share.zip](https://github.com/QT-DevOps/DevOpsIssues/files/2114150/share.zip)
