### ISSUE TITLE
error in ansible user 

### ISSUE THREAD

**Issue by singaravellu** [QT-DevOps/DevOpsIssues#432]
i have create an ansible user in redhat while trying to login withansible giving bellow error 
![Capture 6](https://user-images.githubusercontent.com/32475854/57178530-3cbe6480-6e8f-11e9-9137-555863201091.PNG)

**Comment by bhaskardegala** [comment]
If you don't have passwd for your user use these commands
"sudo -i "(this will make you root user)
Then " su ansible" this will log into your user
Basically when you add user in redhat u should give password seperately by using "passwd ansible" (use this command when you are in root user)

**Comment by sandhyadev** [comment]
first you become a root user "sudo -i" after that excute this "su - ansible"

**Comment by anon-42** [comment]
Instead of "su ansible" type "sudo su ansible" (If this is aws machine  in rhel , ec2-user will have sudo permission)

**Comment by bhaskardegala** [comment]
> first you become a root user "sudo -i" after that excute this "su - ansible"

For best practice don't use " - " between su and ansible

**Comment by bhaskardegala** [comment]
> > first you become a root user "sudo -i" after that excute this "su - ansible"
> 
> For best practice don't use " - " between su and ansible

Sorry it's my bad I made a wrong statement actually - give more flexibility over normal su user and i came to know that today

**Comment by shaikkhajaibrahim** [comment]
Is it fixed. If fixed close the issue with resolution

**Comment by ghost** [comment]
singaravellu please respond,

**Comment by singaravellu** [comment]
done
