### ISSUE TITLE
question: Sonarqube

### ISSUE THREAD

**Issue by chintalamadhu** [QT-DevOps/DevOpsIssues#433]
Hi,
is there any difference between sonarscanner & sonarqube? if yes, please explain about it.

thanks,
Madhu

**Comment by bhaskardegala** [comment]
Sonarqube is the central server holding the results of analysis
Sonarqube-scanner or sonar scanner performs the analysis and send the results to sonarqube

**Comment by bhaskardegala** [comment]
Even this [link](https://stackoverflow.com/questions/43029897/sonarqube-vs-sonarscanner) can help you out

**Comment by ghost** [comment]
please post only issues
and close this issue

**Comment by chintalamadhu** [comment]
@nareshabbanapuri , is it not for the doubt clarification? it wold be clarify for others also who will have the same doubt.
@bhaskardegala , thanks for your explaination
