### ISSUE TITLE
Devops - Jenkins Node set up

### ISSUE THREAD

**Issue by manibushan24** [QT-DevOps/DevOpsIssues#434]
Hi While setting up a node in Jenkins It throws below error.
-> I'm able to ssh slave jenkins user from master.
-> When i Create a node in Jenkins Ui i tried Authentication in two different ways 
 1- Username and password 
 2- SSH private key.

![image](https://user-images.githubusercontent.com/26714961/57208974-5644d680-6f8b-11e9-9c2b-8a62e58873c3.png)

**Comment by ghost** [comment]
please follow this steps
https://www.howtoforge.com/tutorial/ubuntu-jenkins-master-slave/

**Comment by nagireddy-9** [comment]
you must copy key file to jenkins user on node
ssh-copy-id jenkins@ip-of-node

**Comment by bhaskardegala** [comment]
Try to create and copy the SSH key to the node from Jenkins home directory and I am quite sure that your problem will be resolved

**Comment by anon-42** [comment]
> I'm able to ssh slave jenkins user from master.

can you try using _public ip address_ of the node instead of _private ip_ , while configuring connection in jenkins, 
Or use _Host Key Verification Strategy_=non verifying verification startergy while configuring the connection to node

**Comment by bhaskardegala** [comment]
> > I'm able to ssh slave jenkins user from master.
> 
> can you try using _public ip address_ of the node instead of _private ip_ , while configuring connection in jenkins,
> Or use _Host Key Verification Strategy_=non verifying verification startergy while configuring the connection to node

For best practice it is better to use private ip or elastic ip instead of public ip as it keeps on changing when you restart your machine

**Comment by ghost** [comment]
no problem if both machines are in amazon n/w you can use any but prefer to use private ip

**Comment by manibushan24** [comment]
Solved it! Thanks for helping!
