### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by sandeep5683** [QT-DevOps/DevOpsIssues#437]
anybody let me know how to do this steps
Steps for the installation on ubuntu are add the following line to the file @ /etc/apt/sources.list: deb [trusted=yes] http://downloads.sourceforge.net/project/sonar-pkg/deb  binary/

**Comment by bhaskardegala** [comment]
In this you need to add "deb [trusted=yes] http://downloads.sourceforge.net/project/sonar-pkg/deb binary/" line to the file /etc/apt/sources.list and better use t2.medium machine

**Comment by sandeep5683** [comment]
where to add it buddy that is my confusion

**Comment by sandeep5683** [comment]
just show me how

**Comment by bhaskardegala** [comment]
> where to add it buddy that is my confusion

sudo vi /etc/apt/sources.list 
And above coated line any where in this file ex:- u can add it in the last line

**Comment by sandeep5683** [comment]
i am getting this error
"Unable to locate package sonar"

**Comment by sandeep5683** [comment]
its working thanks pal
