### ISSUE TITLE
unable to login into SonarQube

### ISSUE THREAD

**Issue by sandeep5683** [QT-DevOps/DevOpsIssues#438]
![image](https://user-images.githubusercontent.com/48408567/57309084-1570cd00-7105-11e9-8c0b-2d7a71b56048.png)

**Comment by sandeep5683** [comment]
![image](https://user-images.githubusercontent.com/48408567/57309165-389b7c80-7105-11e9-8ebe-d7d164d3c759.png)

**Comment by sandeep5683** [comment]
i just follow the documentation but unable to login SonarQube, let me know how to fix it

**Comment by bhaskardegala** [comment]
Which instance did you use
If it was t2.medium you are good to go and make sure all ports are open as it need to access to 9000 port

**Comment by ghost** [comment]
follow document clearly
requirements:-
t2.medium
open port: 9000

**Comment by sandhyadev** [comment]
requirements:
===========
Instance Type: t2.medium
open port: 9000
ubuntu(16.04,18.04)
Follow the steps:
=============
open file
vi /etc/apt/sources.list
copy this  line in the file
deb [trusted=yes] http://downloads.sourceforge.net/project/sonar-pkg/deb  binary/
save and quit
sudo apt-get update
sudo apt-get install openjdk-8-jdk
sudo apt-get install sonar=6.7.4
sudo service sonar start
http://<ipaddressofsonarqube>:9000

**Comment by CHARANJAI** [comment]
Hi Mr.Sandeep,
Please choose  instance type t2.medium it is good to work and  blindly follow the Documentation.
Please go through below link. In security group you must open all traffic.
By Default **Sonarqube** port no: 9000.
if your issuse is resolve please close the issuse.  
[https://directdevops.blog/2019/01/05/sonarqube/](url)

**Comment by anon-42** [comment]
You haven't opened port 9000, try adding the firewall rule

**Comment by Meganathreddy** [comment]
Hello, 
Even I'm facing the same issue. Unable to access the SonarQube login page. Need help ASAP. 
But then the only difference is that, i have selected t2.micro free tier. Thanks.

**Comment by dharmatejadevops** [comment]
> Hello,
> Even I'm facing the same issue. Unable to access the SonarQube login page. Need help ASAP.
> But then the only difference is that, i have selected t2.micro free tier. Thanks.

if you chose instance-type t2.micro it will installed but not opening the page because of it consume more memory. change the insistence-type to t2.medium  then its work.

**Comment by Meganathreddy** [comment]
> > Hello,
> > Even I'm facing the same issue. Unable to access the SonarQube login page. Need help ASAP.
> > But then the only difference is that, i have selected t2.micro free tier. Thanks.
> 
> if you chose instance-type t2.micro it will installed but not opening the page because of it consume more memory. change the insistence-type to t2.medium then its work.

Thanks Dharmateja. but now i did the same in t2.medium with 2 cores and 4 GB of RAM.  And now i am facing a different issue:(

Log:
[ERROR] No TypeScript compiler found in your project, analysis of typescript files is aborted
[INFO] Sensor TypeScript Sensor [typescript] (done) | time=31ms
[INFO] Sensor TypeScript LCOV Coverage Sensor [typescript]
[INFO] Sensor TypeScript LCOV Coverage Sensor [typescript] (done) | time=3ms
[INFO] Sensor JavaScript Squid Sensor [javascript]
[INFO] 341 source files to be analyzed
[INFO] 34/341 files analyzed, current file: /home/jenkins/workspace/Test/src/main/webapp/bower_components/angular-scenario/angular-scenario.js
[WARNING] [JOURNAL_FLUSHER] WARNING Journal flush operation took 6,388ms last 8 cycles average is 798ms
[INFO] 34/341 files analyzed, current file: /home/jenkins/workspace/Test/src/main/webapp/bower_components/angular-scenario/angular-scenario.js
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 55.487 s
[INFO] Finished at: 2019-05-14T08:18:52Z
[INFO] Final Memory: 64M/239M
[INFO] ------------------------------------------------------------------------
[ERROR] Java heap space -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError
[Pipeline] }
WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succedeed?
[Pipeline] // withSonarQubeEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by Meganathreddy** [comment]
> > > Hello,
> > > Even I'm facing the same issue. Unable to access the SonarQube login page. Need help ASAP.
> > > But then the only difference is that, i have selected t2.micro free tier. Thanks.
> > 
> > 
> > if you chose instance-type t2.micro it will installed but not opening the page because of it consume more memory. change the insistence-type to t2.medium then its work.
> 
> Thanks Dharmateja. but now i did the same in t2.medium with 2 cores and 4 GB of RAM. And now i am facing a different issue:(
> 
> Log:
> [ERROR] No TypeScript compiler found in your project, analysis of typescript files is aborted
> [INFO] Sensor TypeScript Sensor [typescript] (done) | time=31ms
> [INFO] Sensor TypeScript LCOV Coverage Sensor [typescript]
> [INFO] Sensor TypeScript LCOV Coverage Sensor [typescript] (done) | time=3ms
> [INFO] Sensor JavaScript Squid Sensor [javascript]
> [INFO] 341 source files to be analyzed
> [INFO] 34/341 files analyzed, current file: /home/jenkins/workspace/Test/src/main/webapp/bower_components/angular-scenario/angular-scenario.js
> [WARNING] [JOURNAL_FLUSHER] WARNING Journal flush operation took 6,388ms last 8 cycles average is 798ms
> [INFO] 34/341 files analyzed, current file: /home/jenkins/workspace/Test/src/main/webapp/bower_components/angular-scenario/angular-scenario.js
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 55.487 s
> [INFO] Finished at: 2019-05-14T08:18:52Z
> [INFO] Final Memory: 64M/239M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Java heap space -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OutOfMemoryError
> [Pipeline] }
> WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succedeed?
> [Pipeline] // withSonarQubeEnv
> [Pipeline] }
> [Pipeline] // stage
> [Pipeline] }
> [Pipeline] // node
> [Pipeline] End of Pipeline
> ERROR: script returned exit code 1
> Finished: FAILURE

Issue resolved. Seems there is some issue related to the gameoflife code of particular repository.
I have just fetched the same project "Game of life" but from different git hub repository and the issue resolved.
Also just to make sure i have build Spring per clinic project prepared the quality reports. It worked. Thanks..

snippet:
![image](https://user-images.githubusercontent.com/39144078/57695638-6a17c900-766c-11e9-8886-7a9ca0062aa8.png)
