### ISSUE TITLE
error in json file while validating

### ISSUE THREAD

**Issue by Nara-Sagar** [QT-DevOps/DevOpsIssues#439]
![image](https://user-images.githubusercontent.com/48256252/57447901-cac29280-7275-11e9-8cf1-233339e137f9.png)
this was my error but i have seen same issue posted here so  i  have fixed it tnx

**Comment by devopslearningteja** [comment]
Send me your json file, then we clarify it

**Comment by ghost** [comment]
upload json file

**Comment by Nara-Sagar** [comment]
I fixed the error tnx.
Any new issue I'll get back to you

**Comment by sandhyadev** [comment]
close the issue.
