### ISSUE TITLE
Some builds didn't complete successfully and had errors: --> amazon-ebs: Error processing 

### ISSUE THREAD

**Issue by Nara-Sagar** [QT-DevOps/DevOpsIssues#441]
![image](https://user-images.githubusercontent.com/48256252/57517198-e9875e80-7333-11e9-8f40-dd11727c5f05.png)

please find the attached .json file and i am facing an error, please check.
[variables.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3165810/variables.txt)

**Comment by bhaskardegala** [comment]
Nsk 
If possible build it again using git bash or cmd , I think env variables for PS scripts may not be specified correctly by default I will try to look after it mean while you us git bash or cmd and let us know the result

**Comment by nareshabbanapuri** [comment]
type not powershell 
use shell

**Comment by sandhyadev** [comment]
Follow this step to rectify your issue:

1)remove this line in the provisioner section of your json file " "sudo apt-get install -y","
2)Pass your variable values only one time, either through variable section in json or through commandline but not both

 you are passing the values to variables twice through json and also from commandline so thatswhy you are getting the error

**Comment by ghost** [comment]
use shell type

**Comment by ghost** [comment]
{
    "variables":{
        "aws_access_key" :"xxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "aws_private_key" :"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
               
        },
    
    "builders":[
        {
            "type" : "amazon-ebs",
            "source_ami" : "ami-0653e888ec96eab9b",
            "ami_name" : "Packer with variable",
            "access_key" : "{{user `aws_access_key`}}",
            "secret_key" : "{{user `aws_private_key`}}",
            "region" : "us-east-2",
            "ssh_username" : "ubuntu",
            "instance_type" : "t2.micro"

        }
    ],
    "provisioners":[
        {
            "type" : "shell",
            "inline" :[ "sudo apt-get update ",
                        "sudo apt-get install wget -y",
                        "sudo apt-get install git -y",
                        "sudo apt-get install tree -y" ]
                          
            
        }
    ]
}

**Comment by ghost** [comment]
use this and 
run
packer build location of packerfile.json

**Comment by bhaskardegala** [comment]
Yes you need to use shell but not powershell as the environment that you dealing was Linux and there is no scope for powershell

If you get an error stating "error executing PS scripts" even after changing refer this [link](https://github.com/hashicorp/packer/issues/6240)

**Comment by Nara-Sagar** [comment]
![image](https://user-images.githubusercontent.com/48256252/57520620-bb0d8180-733b-11e9-9d10-5af57020ecb6.png)
thanks, guys now it is working i typed PowerShell instead of shell.
