### ISSUE TITLE
Packer Issue

### ISSUE THREAD

**Issue by khatrigopal** [QT-DevOps/DevOpsIssues#442]
Hi
When i am create packer file, instance launched successfully but images not created. Please resolve this issue
![Packer Error](https://user-images.githubusercontent.com/35285671/57527073-b56c6780-734c-11e9-8aaa-d3944087beb6.PNG)
![packer-file](https://user-images.githubusercontent.com/35285671/57527074-b604fe00-734c-11e9-9c20-74bd407c3284.PNG)

**Comment by ghost** [comment]
please send packer file

**Comment by bhaskardegala** [comment]
Gopal
While creating access and secret keys did you give administrator level permissions

**Comment by bhaskardegala** [comment]
As sir discussed in class it is something which is related to firewall and antivirus software of your system so try to disable your firewall and antivirus or you can use a Linux environment

**Comment by khatrigopal** [comment]
Hi

I am using aws linux with admin rights

**Comment by ghost** [comment]
upload packer file

**Comment by khatrigopal** [comment]
Hi

I hv uploaded on github, Devops issue.

Regards
Gopal Khatri

**Comment by bhaskardegala** [comment]
Gopal
Actually we are not able to find your JSON so kindly upload your file here in this issue once again

**Comment by jignesh29** [comment]
Hi..
When i am create packer file on VSC below snap.
and open step power shell , after all last i run ### [ packer validate .\intro.json ]
error show me like 
### Failed to initialize build 'amzon-ebs': builder type not found: amzon-ebs.

pls solved this issued ... 


!
![packer](https://user-images.githubusercontent.com/48603617/57587168-5a8a6a00-751e-11e9-9393-2f5ad9f26574.PNG)
![vsc scripting packer](https://user-images.githubusercontent.com/48603617/57587169-5b230080-751e-11e9-815c-00c4b5632875.PNG)

**Comment by khatrigopal** [comment]
Hi

Please find attached file and resolve my issue.

Regards
Gopal Khatri

**Comment by shaikkhajaibrahim** [comment]
I dont see any attachments

**Comment by khatrigopal** [comment]
PFA

**Comment by shaikkhajaibrahim** [comment]
Zip file & drag n drop on editor. I still don't see attachment

**Comment by shaikkhajaibrahim** [comment]
Use GitHub not email

**Comment by khatrigopal** [comment]
![Uploading packer-file.PNG…]()

**Comment by khatrigopal** [comment]
Find Packer file

**Comment by khatrigopal** [comment]
![Packer Error](https://user-images.githubusercontent.com/35285671/57754584-6b003780-770c-11e9-8049-e05ff3a3c87c.PNG)
![packer-file](https://user-images.githubusercontent.com/35285671/57754586-6b98ce00-770c-11e9-8c97-fc51c789b8f0.PNG)
Find packer file

**Comment by khatrigopal** [comment]
Hi

I have sent on github. Please check and resolve issue.

Regadrs
Gopal Khatri
