### ISSUE TITLE
`access_key` and `secret_key` must both be either set or not set.

### ISSUE THREAD

**Issue by Nara-Sagar** [QT-DevOps/DevOpsIssues#443]
any buddy has a solution for this error.

1 error(s) occurred:

* `access_key` and `secret_key` must both be either set or not set.

**Comment by bhaskardegala** [comment]
Nsk 
As per my knowledge they are set

**Comment by ghost** [comment]
access_key and secret_key must both be either set or not set?
what is your question 
can you elaborate
