### ISSUE TITLE
Seperate envirnoments for different envirnoment

### ISSUE THREAD

**Issue by Mohanbabu97** [QT-DevOps/DevOpsIssues#444]
Hi Team,

I have a single tfstate file for development and testing environment. But i need different tfstate files for them. Is it possible, if possible can you please explain

**Comment by sandhyadev** [comment]
You can do it in two ways:
1)You can initiate terraform in two different folders one for dev and another for test
2)Configure two back-ends i.e s3 buckets one for test and another for dev

**Comment by bhaskardegala** [comment]
Yes Mohan you can use terraform workspace
