### ISSUE TITLE
Packer - Hyper-V-Boot command

### ISSUE THREAD

**Issue by Karthick-Gopalakrishnan** [QT-DevOps/DevOpsIssues#445]
Hello, 

Did anyone tried to create Linux image in hyper-v/virtualbox using packer ?

**Comment by bhaskardegala** [comment]
hello karthick 
actually i haven't tried that but i found some think from web which can help you out
refer this [link](http://www.hurryupandwait.io/blog/creating-hyper-v-images-with-packer)

**Comment by Karthick-Gopalakrishnan** [comment]
Bhaskar,

Thanks for the share, My doubt was related to boot_command configuration in the build, where i couldn't move further. so thought, if some had figured out they can share the experience.

[Hyervpacker.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3171862/Hyervpacker.zip)

**Comment by devopslearningteja** [comment]
> Bhaskar,
> 
> Thanks for the share, My doubt was related to boot_command configuration in the build, where i couldn't move further. so thought, if some had figured out they can share the experience.
> 
> [Hyervpacker.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3171862/Hyervpacker.zip)

**Comment by dharmatejadevops** [comment]
> Bhaskar,
> 
> Thanks for the share, My doubt was related to boot_command configuration in the build, where i couldn't move further. so thought, if some had figured out they can share the experience.
> 
> [Hyervpacker.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3171862/Hyervpacker.zip)

![errorgroup](https://user-images.githubusercontent.com/43385451/57639686-19ea2980-75ce-11e9-890a-5cc50403a3b4.PNG)

Did you get any error like above image, once try this command in power-shell a administration
([adsi]”WinNT://./Hyper-V Administrators,group”).Add(“WinNT://$env:UserDomain/$env:Username,user”)
for above error refer this link
https://blogs.msdn.microsoft.com/virtual_pc_guy/2016/05/30/adding-yourself-to-the-hyper-v-administrators-group-with-powershell/
i tried this bellow packer document, it will create vm and running on hyper-v it ask some manual steps.
after some time getting error like bellow image
![packerhyper-v error](https://user-images.githubusercontent.com/43385451/57640528-5e76c480-75d0-11e9-9f77-aade452ce985.png)
 
https://www.packer.io/docs/builders/hyperv-iso.html

**Comment by Karthick-Gopalakrishnan** [comment]
> > Bhaskar,
> > Thanks for the share, My doubt was related to boot_command configuration in the build, where i couldn't move further. so thought, if some had figured out they can share the experience.
> > [Hyervpacker.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3171862/Hyervpacker.zip)
> 
> ![errorgroup](https://user-images.githubusercontent.com/43385451/57639686-19ea2980-75ce-11e9-890a-5cc50403a3b4.PNG)
> 
> Did you get any error like above image, once try this command in power-shell a administration
> ([adsi]”WinNT://./Hyper-V Administrators,group”).Add(“WinNT://$env:UserDomain/$env:Username,user”)
> for above error refer this link
> https://blogs.msdn.microsoft.com/virtual_pc_guy/2016/05/30/adding-yourself-to-the-hyper-v-administrators-group-with-powershell/
> i tried this bellow packer document, it will create vm and running on hyper-v it ask some manual steps.
> after some time getting error like bellow image
> ![packerhyper-v error](https://user-images.githubusercontent.com/43385451/57640528-5e76c480-75d0-11e9-9f77-aade452ce985.png)
> 
> https://www.packer.io/docs/builders/hyperv-iso.html

Run power shell in admin mode

**Comment by Karthick-Gopalakrishnan** [comment]
there is a way to automate that manual steps, In Linux world they call it kickstart file which automates that manual keying process.
There is a folder Http inside which u can find the cfg file.. Now we need to link the build with that config file and thats where am struck

**Comment by ghost** [comment]
please try with virtual box

**Comment by ghost** [comment]
[boot.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3191612/boot.txt)
boot command

**Comment by Karthick-Gopalakrishnan** [comment]
Hello Naresh,

Thanks for your reply, the boot txt you have shared is for Ubuntu. I was trying with centos anyhow i figured out to pass kickstart file using goggle. 

Am struck at the place where it says waiting for SSH connection

![image](https://user-images.githubusercontent.com/48745218/57936663-6a66cd00-78d5-11e9-86b2-a5423e3c4f7f.png)

sharing build file and packerlogs for your reference
[packer.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3192403/packer.zip)
