### ISSUE TITLE
build 'amazon-ebs' errored:script exited with non zero exit status :100 

### ISSUE THREAD

**Issue by Nara-Sagar** [QT-DevOps/DevOpsIssues#446]
please check attaching the JSON file.
[mytry.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3172271/mytry.txt)

**Comment by bhaskardegala** [comment]
hello nsk 
please remove sudo  apt-git install tree -y from your json file it will working ,
i actually don't know the reason why it was not installing tree from your json file i will defiantly look after that , except that your json file working fine remove tree and try installing something like openjdk   
nsk once again requesting you please remove your azure credentials from your file some one will definitely miss use it and one more correction to your file your image_name is static try using time strap as same name can not be acceptable for image creation

**Comment by bhaskardegala** [comment]
i think even you got this error
![1](https://user-images.githubusercontent.com/48744320/57619329-4a689e00-75a3-11e9-89ed-af68d634c680.PNG)

**Comment by bhaskardegala** [comment]
hello nsk
i figured it out you are using this format
![2](https://user-images.githubusercontent.com/48744320/57620497-8bae7d00-75a6-11e9-877c-fca8598a5b97.PNG)
but try using this format
![3](https://user-images.githubusercontent.com/48744320/57620511-98cb6c00-75a6-11e9-9652-846ca9fb6082.PNG)
it will work

**Comment by Nara-Sagar** [comment]
yes, it is working now thanks.
