### ISSUE TITLE
terrarotm unable to create instace

### ISSUE THREAD

**Issue by praveenkumar9154** [QT-DevOps/DevOpsIssues#447]
terraform unable to create instace 
i got below error plaese look into this 

![Capture](https://user-images.githubusercontent.com/49840014/57673632-463b8f80-763a-11e9-8252-81db75ff1741.JPG)

**Comment by bhaskardegala** [comment]
Your Ami I'd doesn't exist
Please provide valid Ami I'd

**Comment by praveenkumar9154** [comment]
i provide valid ami id but am unable to create instance

**Comment by praveenkumar9154** [comment]
provider "aws" {
    region = "us-east-1"
    access_key = " "
    secret_key = " "
    }
    
    resource  "aws_instance" "hello" {
    ami = "ami-5b673c34" 
    key_name =  "86:fb:ab:72:0c:60:c5:eb:78:a3:2f:35:d0:4c:04:ed:ba:e5:81:d1"
    instance_type = "t2.micro"
    }


this is syntax please look into this and any mistake let us know

**Comment by sunil3456** [comment]
https://github.com/sunil3456/Terraform?files=1

**Comment by shaikkhajaibrahim** [comment]
Please don't post access keys & secret keys

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by shaikkhajaibrahim** [comment]
Correct your key name you have used key fingerprint

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by praveenkumar9154** [comment]
Tq u sir

**Comment by shaikkhajaibrahim** [comment]
Is it fixed. If fixed close the issue with resolution

**Comment by praveenkumar9154** [comment]
yes sir 
  issue is fixed 
tq u for your support
