### ISSUE TITLE
packer with chef getting error 

### ISSUE THREAD

**Issue by dharmatejadevops** [QT-DevOps/DevOpsIssues#449]
i am trying to packer provision with chef getting error like Chef Infra Client cannot execute without accepting the license
![packerchef](https://user-images.githubusercontent.com/43385451/57715088-87ac5900-7693-11e9-8ce3-a31899b3b3d6.png)

in this zip file contains cookbook and packerfile
[packerchef.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3178867/packerchef.zip)

**Comment by dharmatejadevops** [comment]
issue resolved 
in provisioning i have add the version of chefdk and path of cookbook also changed correctly then its working.

**Comment by shaikkhajaibrahim** [comment]
Close the issue

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dharmatejadevops** [comment]
sorry sir
