### ISSUE TITLE
how to get game-of-life.war file

### ISSUE THREAD

**Issue by ivsrikanthDevops** [QT-DevOps/DevOpsIssues#45]
how to get the game-of-life.war file.
for practicing while installing tomcat7 on ubuntu server
i am starting for docker class

**Comment by ghost** [comment]
Hi @ivsrikanthDevops 
Please find gameoflife zip file attached below.

[gameoflife.zip](https://github.com/QT-DevOps/DevOpsIssues/files/2130588/gameoflife.zip)

**Comment by ivsrikanthDevops** [comment]
thanks@arunkumar
