### ISSUE TITLE
error while creating terraform instance

### ISSUE THREAD

**Issue by Nara-Sagar** [QT-DevOps/DevOpsIssues#450]
![image](https://user-images.githubusercontent.com/48256252/57743342-4becb000-76e2-11e9-8261-1dd465e2361d.png)
[terraform1.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3180571/terraform1.txt)

**Comment by bhaskardegala** [comment]
Don't give spaces for Ami i.e inside double quotes don't give any space 
Or just open your JSON file in vscode then right click -> format document it will simply manage your file

**Comment by sandhyadev** [comment]
Don't give the spaces in between the doublequotes ,remove the space in "ami" field.
follow this
ami = "ami-0de53d8956e8dcf80"

**Comment by Nara-Sagar** [comment]
![image](https://user-images.githubusercontent.com/48256252/57751727-4bfda780-7704-11e9-8ce1-574fe88e9c3b.png)
i am  getting this error repetedly?

**Comment by shaikkhajaibrahim** [comment]
This seems to be problem with key value pair.
________________________________

**Comment by bhaskardegala** [comment]
make sure you have your key in the region that you have specified or 
remove key_name and try it at once
it will create its own key pair

**Comment by Nara-Sagar** [comment]
yes removed the key, now it is working 
![image](https://user-images.githubusercontent.com/48256252/57755833-7ef96880-770f-11e9-8a9f-e718256e3244.png)
