### ISSUE TITLE
Issue with Packer , Not able to launch aws machine

### ISSUE THREAD

**Issue by AnoopPogaru** [QT-DevOps/DevOpsIssues#452]
$ packer validate todays.json
Failed to initialize build 'amazon-ebs': error initializing builder 'amazon-ebs': timeout while waiting for plugin to start

ANUP@ANUP-PC MINGW64 ~/Desktop/Jenkins
$ packer build todays.json

$ packer build todays.json
Failed to initialize build 'amazon-ebs': error initializing builder 'amazon-ebs': timeout while waiting for plugin to start
amazon-ebs output will be in this color.

==> Builds finished but no artifacts were created.

**Comment by AnoopPogaru** [comment]
Could be able to build the aws machine usinjg Terraform . But pacjer is getting failed.

Kindly suggest on this. Any port issues or wat

**Comment by AnoopPogaru** [comment]
{
    "_comment": "This is a comment",

"builders" : [
    {
        "type": "amazon-ebs",
        "access_key": "",
        "secret_key": "",
        "region": "us-east-1",
          "source_ami": "ami-0a313d6098716f372",
        "instance_type": "t2.micro",
        "ssh_username": "ubuntu",
        "ami_name": "packer-new"
      }
  
    ]

}

**Comment by bhaskardegala** [comment]
This [link](https://github.com/hashicorp/packer/issues/6536) may help you out

**Comment by bhaskardegala** [comment]
Have you performed terraform init first

**Comment by ghost** [comment]
please send packer file

**Comment by ghost** [comment]
{
"variables":{
        "access_key": "xxxxxxxxxxxxxxxxxx",
        "secret_key": "Z06XhG7WSL6IZic3iwkTRgu66fxxxxxxxxxxxxxxxxxxxxx"

    },

"builders" : [
{
"type": "amazon-ebs",
"access_key": "{{user `access_key`}}",
"secret_key": "{{ user `secret_key`}}",
"region": "us-west-2",
"source_ami": "ami-005bdb005fb00e791",
"instance_type": "t2.micro",
"ssh_username": "ubuntu",
"ami_name": "packer-new"
}

]
}

**Comment by ghost** [comment]
please use above script may you get solution

**Comment by sdhulipudi** [comment]
Hi Naresh,

I too received same message as mentioned by Anoop.

Could you let us know the reason why did we failed to launch aws machine using basic programming steps? I think Variables are no where related to this issue.

Thanks,
Sukanya

**Comment by sdhulipudi** [comment]
Hi Naresh and Anoop,

I tried again and launched machine successfully.

-> I have changed my "ami_name" and corrected "instance_type" which was wrongly typed as "t2.macro" instead "t2.micro"

Thanks,
Sukanya

**Comment by ghost** [comment]
please close issue
