### ISSUE TITLE
provider.ami: no suitable version installed

### ISSUE THREAD

**Issue by Nara-Sagar** [QT-DevOps/DevOpsIssues#453]
![image](https://user-images.githubusercontent.com/48256252/57761195-a144b380-771a-11e9-87c4-39ca5156e08b.png)

please check this error.

**Comment by bhaskardegala** [comment]
Please share your tf file
If you haven't created a file first create and write a provider as tf download plugins based on provider

**Comment by ghost** [comment]
please upload tf file

**Comment by Nara-Sagar** [comment]
[terra.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3181852/terra.txt)
please find the tf file.

**Comment by dharmatejadevops** [comment]
helloworld is your directory na, execute with the bellow command 
 terraform init .

**Comment by Nara-Sagar** [comment]
![image](https://user-images.githubusercontent.com/48256252/57766129-6f384f00-7724-11e9-9a98-5ba4636f22ec.png)
did the same still not working

**Comment by dharmatejadevops** [comment]
please  execute this command " terrafrom init ." [.] means current directory

**Comment by bhaskardegala** [comment]
Yes you should definitely give path in your case "." Is fine

**Comment by dharmatejadevops** [comment]
there current directory is not the issue i think once check your ami with that region or not.
please change that resorce type "ami_instance" to "aws_instance"

**Comment by srinivas-reddy-mula** [comment]
1)change your resource type to <<aws_instance>>
2)there is no security_group in terraform as a resource
change that <<security_group>> to <<security_groups>> and check once your <<openall>>
any how, security group is not mandatory

**Comment by ghost** [comment]
please verify provider part once 
and remove tfstate , and redo things

**Comment by Nara-Sagar** [comment]
my security groups are blocked
