### ISSUE TITLE
NGNIX Reverse Proxy  to HTTP2

### ISSUE THREAD

**Issue by sunil3456** [QT-DevOps/DevOpsIssues#454]
Can anyone suggest me the best approach to upgrade Ngnix Reverse Proxy to HTTP2.

I can go with application load balancer but client wants to keep same env.

would that help with springboot (How) or Is there any best approach.

Much appreciated thanks

**Comment by CHARANJAI** [comment]
Hi Mr.Sunil,
I think below link will help you out.  Go through that link follow the Documentation.
[https://www.nginx.com/blog/nginx-1-13-9-http2-server-push/](url)
Thanks,
Charan Jayee

**Comment by sunil3456** [comment]
thanks
