### ISSUE TITLE
terraform instance creation

### ISSUE THREAD

**Issue by praveenkumar9154** [QT-DevOps/DevOpsIssues#456]
while i creating instace with connection and provisioner  i got below error 
please look into this sir
![Capture](https://user-images.githubusercontent.com/49840014/57794493-6023c200-7761-11e9-9bda-f12f8d3fe5bf.JPG)

**Comment by dharmatejadevops** [comment]
> while i creating instace with connection and provisioner i got below error
> please look into this sir
> ![Capture](https://user-images.githubusercontent.com/49840014/57794493-6023c200-7761-11e9-9bda-f12f8d3fe5bf.JPG)

send your terraform file

**Comment by praveenkumar9154** [comment]
resource "aws_instance" "hello" {
    ami = "ami-5b673c34" 
    key_name =  "terraform"
    instance_type = "t2.micro"

    }

   resource "aws_security_group" "allow_tls" {
  name        = "allow_tls"
  description = "Allow TLS inbound traffic"
  vpc_id      = "vpc-008bf63dff0dcef20"

  ingress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port       = 0
    to_port         = 0
    protocol        = "-1"
    cidr_blocks     = ["0.0.0.0/0"]
  }
}
connection {
    type = "ssh"
    user = "ec2-user"
    private_key = "${file(./test/terraform.pem)}"   
}

provisioner "remote-exec" {
    inline = ["sudo yum install httpd -y" , "sudo service httpd start"]
}

**Comment by praveenkumar9154** [comment]
if any syntax error please let me know

**Comment by dharmatejadevops** [comment]
> if any syntax error please let me know
put the connection and provisioner on aws_instance resorce and try it

**Comment by bhaskardegala** [comment]
resource "aws_instance" "hello" {
  ami           = "ami-5b673c34"
  key_name      = "terraform"
  instance_type = "t2.micro"

  connection {
    type        = "ssh"
    user        = "ec2-user"
    private_key = "${file("./test/terraform.pem")}"
  }

  provisioner "remote-exec" {
    inline = ["sudo yum install httpd -y", "sudo service httpd start"]
  }
}

resource "aws_security_group" "allow_tls" {
  name        = "allow_tls"
  description = "Allow TLS inbound traffic"
  vpc_id      = "vpc-008bf63dff0dcef20"

  ingress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
## corrections
connection and provision need to be in resource "aws_instance" and you missed double quotes in .pem file path . 
Try out this tf file its working good now

**Comment by praveenkumar9154** [comment]
yes its working fine ..
tq u bhaker and dharmateja for helping out to resolve issue
