### ISSUE TITLE
i cant login into aws ec2 machine and command from instance is not paste into the gitbash

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/DevOpsIssues#457]
ssh -i "manualcreate.pem" ubuntu@ec2-52-32-156-36.us-west-2.compute.amazonaws.com 
this command I can't paste into the gitbash here.when I type the code it shows the error.

**Comment by bhaskardegala** [comment]
Shift+insert to paste anything in git bash 
When ever you are trying to login to your instance using pem key open git bash where ever you have your pem file 
Please show us that error that it was stating while you are trying the code
