### ISSUE TITLE
error came when i executing the packer build -debug command at creating the ami image

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/DevOpsIssues#458]
![build error](https://user-images.githubusercontent.com/50665358/57917505-70978200-78b2-11e9-9e5e-6f05d07d1b46.PNG)

**Comment by allinonedashboard** [comment]
https://github.com/QT-DevOps/AWSIssues/issues/8

**Comment by chowdamramana** [comment]
I got again error when I giving the privileged access to the operation

![error build 2](https://user-images.githubusercontent.com/50665358/57918516-8e65e680-78b4-11e9-90f2-3377af37e31e.PNG)

**Comment by bhaskardegala** [comment]
> I got again error when I giving the privileged access to the operation
> 
> ![error build 2](https://user-images.githubusercontent.com/50665358/57918516-8e65e680-78b4-11e9-90f2-3377af37e31e.PNG)

Please change your Ami name for ever image creation
for best practice start using timestamp to get rid off this sort of errors

**Comment by bhaskardegala** [comment]
In your first issue I think you did not give authentication permission for your iam user while creating access and secret keys
And please never ever share your access key and secret keys

**Comment by chowdamramana** [comment]
I got another issue when I
![errorbuild f](https://user-images.githubusercontent.com/50665358/57926874-19051080-78ca-11e9-8932-db696f4dac11.PNG)
 run the command of packer build -debug

**Comment by ghost** [comment]
please send packer file now

**Comment by chowdamramana** [comment]
> please send packer file now

![Capture](https://user-images.githubusercontent.com/50665358/57926961-5d90ac00-78ca-11e9-881f-c7c6706c41ce.PNG)

**Comment by ghost** [comment]
please change AMI name 
definitely, you get solution

**Comment by ghost** [comment]
please check source_ami

**Comment by ghost** [comment]
{
"variables":{
        "access_key": "",
        "secrete_key": ""

    },

"builders" : [
{
"type": "amazon-ebs",
"access_key": "{{user `access_key`}}",
"secret_key": "{{ user `secrete_key`}}",
"region": "us-west-2",
"source_ami": "ami-005bdb005fb00e791",
"instance_type": "t2.micro",
"ssh_username": "ubuntu",
"ami_name": "packer445"
}

],
"provisioners":[{
    "type": "shell",
    "inline": ["sudo apt-get update ", "sudo apt-get install tree -y"]
  }
]
}

please give proper input to this json file its works

**Comment by chowdamramana** [comment]
> please change AMI name
> definitely, you get a solution

I have tried it already, but no result

**Comment by ghost** [comment]
> {
> "variables":{
> "access_key": "",
> "secrete_key": ""
> 
> ```
> },
> ```
> 
> "builders" : [
> {
> "type": "amazon-ebs",
> "access_key": "{{user `access_key`}}",
> "secret_key": "{{ user `secrete_key`}}",
> "region": "us-west-2",
> "source_ami": "ami-005bdb005fb00e791",
> "instance_type": "t2.micro",
> "ssh_username": "ubuntu",
> "ami_name": "packer445"
> }
> 
> ],
> "provisioners":[{
> "type": "shell",
> "inline": ["sudo apt-get update ", "sudo apt-get install tree -y"]
> }
> ]
> }

try this
it works for me

**Comment by chowdamramana** [comment]
> > {
> > "variables":{
> > "access_key": "",
> > "secrete_key": ""
> > ```
> > },
> > ```
> > 
> > 
> > "builders" : [
> > {
> > "type": "amazon-ebs",
> > "access_key": "{{user `access_key`}}",
> > "secret_key": "{{ user `secrete_key`}}",
> > "region": "us-west-2",
> > "source_ami": "ami-005bdb005fb00e791",
> > "instance_type": "t2.micro",
> > "ssh_username": "ubuntu",
> > "ami_name": "packer445"
> > }
> > ],
> > "provisioners":[{
> > "type": "shell",
> > "inline": ["sudo apt-get update ", "sudo apt-get install tree -y"]
> > }
> > ]
> > }
> 
> try this
> it works for me

again I got the same error

**Comment by ghost** [comment]
please send error

**Comment by chowdamramana** [comment]
> please send error

same error
![Capture](https://user-images.githubusercontent.com/50665358/57931626-85860c80-78d6-11e9-9af4-5995048285e4.PNG)

**Comment by chowdamramana** [comment]
> > please send error
> 
> same error
> ![Capture](https://user-images.githubusercontent.com/50665358/57931626-85860c80-78d6-11e9-9af4-5995048285e4.PNG)

tell me what is the meaning of the error

**Comment by bhaskardegala** [comment]
If you are using visual studio code open your file in it and then right click then you will see a pop up window and click on format document there your issue will be resolved , this happen as you were not using list type approach while writing scripts

**Comment by bhaskardegala** [comment]
You can also review this below mentioned link which appears to be similar issue
[click](https://github.com/QT-DevOps/DevOpsIssues/issues/446#issuecomment-491797718)

**Comment by chowdamramana** [comment]
> If you are using visual studio code open your file in it and then right click then you will see a pop up window and click on format document there your issue will be resolved , this happen as you were not using list type approach while writing scripts

I didn't find any pop-up window can you send me the screenshot

**Comment by bhaskardegala** [comment]
> > If you are using visual studio code open your file in it and then right click then you will see a pop up window and click on format document there your issue will be resolved , this happen as you were not using list type approach while writing scripts
> 
> I didn't find any pop-up window can you send me the screenshot

Just right click on your screen you can find format document option

**Comment by ghost** [comment]
give proper input to this json file it works

{
"variables":{
"access_key": "",
"secrete_key": ""

},
"builders" : [
{
"type": "amazon-ebs",
"access_key": "{{user access_key}}",
"secret_key": "{{ user secrete_key}}",
"region": "us-west-2",
"source_ami": "ami-005bdb005fb00e791",
"instance_type": "t2.micro",
"ssh_username": "ubuntu",
"ami_name": "packer445"
}

],
"provisioners":[{
"type": "shell",
"inline": ["sudo apt-get update ", "sudo apt-get install tree -y"]
}
]
}

**Comment by chowdamramana** [comment]
> give proper input to this json file it works
> 
> {
> "variables":{
> "access_key": "",
> "secrete_key": ""
> 
> },
> "builders" : [
> {
> "type": "amazon-ebs",
> "access_key": "{{user access_key}}",
> "secret_key": "{{ user secrete_key}}",
> "region": "us-west-2",
> "source_ami": "ami-005bdb005fb00e791",
> "instance_type": "t2.micro",
> "ssh_username": "ubuntu",
> "ami_name": "packer445"
> }
> 
> ],
> "provisioners":[{
> "type": "shell",
> "inline": ["sudo apt-get update ", "sudo apt-get install tree -y"]
> }
> ]
> }

I am trying this code but still, I
![Capture err](https://user-images.githubusercontent.com/50665358/57939751-9dff2280-78e8-11e9-8cd3-3b8ab79c1494.PNG)
![pack m](https://user-images.githubusercontent.com/50665358/57939753-9dff2280-78e8-11e9-8642-5cf786e14fe6.PNG)

 got an error

**Comment by ghost** [comment]
please enter credentials

**Comment by bhaskardegala** [comment]
> > give proper input to this json file it works
> > {
> > "variables":{
> > "access_key": "",
> > "secrete_key": ""
> > },
> > "builders" : [
> > {
> > "type": "amazon-ebs",
> > "access_key": "{{user access_key}}",
> > "secret_key": "{{ user secrete_key}}",
> > "region": "us-west-2",
> > "source_ami": "ami-005bdb005fb00e791",
> > "instance_type": "t2.micro",
> > "ssh_username": "ubuntu",
> > "ami_name": "packer445"
> > }
> > ],
> > "provisioners":[{
> > "type": "shell",
> > "inline": ["sudo apt-get update ", "sudo apt-get install tree -y"]
> > }
> > ]
> > }
> 
> I am trying this code but still, I
> ![Capture err](https://user-images.githubusercontent.com/50665358/57939751-9dff2280-78e8-11e9-8cd3-3b8ab79c1494.PNG)
> ![pack m](https://user-images.githubusercontent.com/50665358/57939753-9dff2280-78e8-11e9-8642-5cf786e14fe6.PNG)
> 
> got an error

Did you give administrator privilege to your iam user while creating access and secret keys

**Comment by chowdamramana** [comment]
Yes ,I am giving administrator privilege to Iam user

**Comment by bhaskardegala** [comment]
Create new access and secret keys and try again
And even make sure that your Ami id is present in the same region that you have mentioned

**Comment by chowdamramana** [comment]
> Create new access and secret keys and try again
> And even make sure that your Ami id is present in the same region that you have mentioned

I have tried it, but still, an error comes

**Comment by bhaskardegala** [comment]
> > Create new access and secret keys and try again
> > And even make sure that your Ami id is present in the same region that you have mentioned
> 
> I have tried it, but still, an error comes

it was working fine for us . OK ,try even changing  region 
and share the error screen shots again

**Comment by ghost** [comment]
if issue resolve close issue

**Comment by ghost** [comment]
use this file give proper inputs
[issue1.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3193884/issue1.txt)

**Comment by chowdamramana** [comment]
> use this file give proper inputs
> [issue1.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3193884/issue1.txt)

I have tried it but I got an issue
![Capture](https://user-images.githubusercontent.com/50665358/57971090-17f5e100-79a7-11e9-9de1-bb9a0b2cde1a.PNG)
