### ISSUE TITLE
terrafor m validating issue 

### ISSUE THREAD

**Issue by saipranay54** [QT-DevOps/DevOpsIssues#459]
terraform issue
hi guys,
I am getting the issue while validate the below code
Error: aws_vpc.ntiernetwork: resource repeated multiple times
aws_vpc.ntiernetwork: resource repeated multiple times
please help me out
i have created the three files and written a code as below and i executed the code
code 1:resource "aws_vpc" "ntiernetwork" {
cidr_block="10.10.0.0/16"

type{
    Name="ntier"
}
}

resource "aws_subnet" "web" {
vpc_id="${aws_vpc.ntiernetwork.id}"
cidr_block="10.10.0.0/24"

tags{
Name="web"
}

}

resource "aws_subnet" "business" {
vpc_id="${aws_vpc.ntiernetwork.id}"
cidr_block="10.10.1.0/24"

tags{
Name="business"
}
}
resource "aws_subnet" "db" {
vpc_id="${aws_vpc.ntiernetwork.id}"
cidr_block="10.10.0.2/24"

tags{
Name="db"
}
}
code2:resource "aws_vpc" "ntiernetwork" {
cidr_block="10.10.0.0/16"

type{
    Name="ntier"
}
}

resource "aws_subnet" "web" {
vpc_id="${aws_vpc.ntiernetwork.id}"
cidr_block="10.10.0.0/24"

tags{
Name="web"
}

}

resource "aws_subnet" "business" {
vpc_id="${aws_vpc.ntiernetwork.id}"
cidr_block="10.10.1.0/24"

tags{
Name="business"
}
}
resource "aws_subnet" "db" {
vpc_id="${aws_vpc.ntiernetwork.id}"
cidr_block="10.10.2.0/24"

tags{
Name="db"
}
}
code3:resource "aws_instance" "web_instance" {
ami= "ami-0a313d6098716f372"
instance_type="t2.micro"
key_name="vpclearn"
subnet_id="${aws_subnet.web.id}"

 tags{
     Name="web"
 }
}

resource "aws_instance" "db_instance" {
ami=" ami-0a313d6098716f372"
instance_type="t2.micro"
key_name="vpclearn"
subnet_id="${aws_subnet.web.id}"

 tags{
     Name="db"
 }
}

resource "aws_instance" "business_instance" {
ami=" ami-0a313d6098716f372"
instance_type="t2.micro"
key_name="vpclearn"
subnet_id="${aws_subnet.web.id}"

 tags{
     Name="business"
 }
}
please help me to resolve the same
![terraform issue](https://user-images.githubusercontent.com/50736120/57920809-8f4d4700-78b9-11e9-9e62-12b44413b05b.png)

**Comment by bhaskardegala** [comment]
You are repeating vpc and subnet resources twice with same names
In order to resolve this you need to change resources names 
For ex :-
If you use resource "aws_vpc" "ntirenetwork" once later if you want to use this resource again change it to
Resource "aws_vpc" "ntirenetwork2"

**Comment by saipranay54** [comment]
i have replaced still it is not solved

**Comment by bhaskardegala** [comment]
Can you please share file in PDF or text format

**Comment by ghost** [comment]
send tf file

**Comment by saipranay54** [comment]
[instances.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3191099/instances.txt)
[ntierarchicterture.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3191100/ntierarchicterture.txt)
[vpc.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3191101/vpc.txt)
hi
please find below text files or.tf files data which i have copied in text format
i am validating three .tf files so i am getting the error

**Comment by bhaskardegala** [comment]
Sai Pranay 
If your intension was to create 3 instances in 3 subnets please change subnet name in respective instances

**Comment by bhaskardegala** [comment]
hey pranay
there are few errors in your tf file and i tried to modify them and you can find those files attached in comment and make sure that your key is available in the same region in which you are creating your instance 

[instance.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3191170/instance.txt)
[ntier.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3191171/ntier.txt)
[vpc.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3191172/vpc.txt)

**Comment by ghost** [comment]
[instances.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3191187/instances.txt)
[ntierarchicterture.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3191188/ntierarchicterture.txt)
[vpc.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3191189/vpc.txt)
now its validate

**Comment by ghost** [comment]
please close issue after resolving

**Comment by saipranay54** [comment]
Thanks naresh issue resolved,
followed steps provided by you
