### ISSUE TITLE
Docker Jenkins

### ISSUE THREAD

**Issue by samjoel777** [QT-DevOps/DevOpsIssues#46]
How to link Jenkins and Maven Containers in Docker ?
command that is working

**Comment by shaikkhajaibrahim** [comment]
Link is for services. I dont recommend jenkins & maven to be linked. Maven container with jenkins agent would be my slave

**Comment by samjoel777** [comment]
So can we write Dockerfile with maven installation steps in docker image of jenkins

**Comment by shaikkhajaibrahim** [comment]
yes that should be the way to go ahead
