### ISSUE TITLE
terraform vpc_instace 

### ISSUE THREAD

**Issue by praveenkumar9154** [QT-DevOps/DevOpsIssues#460]
hello all 

while creating instance through vpc i got below error msg
please look into this 
![vpc](https://user-images.githubusercontent.com/49840014/57931963-58862980-78d7-11e9-8789-44e703f4f4fb.JPG)

blow is my terraform syntax
resource "aws_instance" "web_instance" {
     ami = "ami-007d5db58754fa284"
     instance_type = "t2.micro"
     key_name = "terraform"
     subnet_id ="${aws_subnet.db}"
     tags { 
         Name = "web"
     }
 }

**Comment by bhaskardegala** [comment]
Can you please share your whole tf file

**Comment by praveenkumar9154** [comment]
provider "aws" {
    region = "ap-south-1"
    access_key = " "
    secret_key = " "
    }
        
     resource "aws_vpc" "ntiernetwork" {
  cidr_block = "10.10.0.0/16"

  tags {
      Name = "ntier"
  }
     }
     resource "aws_subnet" "db" {
  vpc_id = "${aws_vpc.ntiernetwork.id}"
     cidr_block = "10.10.0.1/24"

     tags {
         Name = "db"
     }
     }
resource "aws_subnet" "web" {
  vpc_id = "${aws_vpc.ntiernetwork.id}"
     cidr_block = "10.10.1.1/24"

     tags {
         Name = "web"
     }
     }
resource "aws_instance" "web_instance" {
     ami = "ami-007d5db58754fa284"
     instance_type = "t2.micro"
     key_name = "terraform"
     subnet_id ="${aws_instance.web_instance.subnet-0120869d30d72b47d}"
     tags { 
         Name = "web"
     }
 }

**Comment by bhagavan2010** [comment]
Please try this subnet_id ="${aws_subnet.web.id}".

**Comment by praveenkumar9154** [comment]
> Please try this subnet_id ="${aws_subnet.web.id}".

same error showing

**Comment by bhaskardegala** [comment]
Please change your subnet id under aws_instance resource to
subnet_id = "${aws_subnet.web.id}" save the document and validate again
Even try to change your region it is not at all mandatory

**Comment by ghost** [comment]
if you share tf file easy to address the problem

**Comment by praveenkumar9154** [comment]
> if you share tf file easy to address the problem

already i shared my tf file

**Comment by bhaskardegala** [comment]
If you have changed your code as mentioned above it will not throw the same error as the one you got earlier please update the error that you are getting now

**Comment by ghost** [comment]
[vpc-ntier.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3192159/vpc-ntier.txt)
use this script 
enter  inputs

**Comment by praveenkumar9154** [comment]
> If you have changed your code as mentioned above it will not throw the same error as the one you got earlier please update the error that you are getting now

showing same error  bhasker

**Comment by praveenkumar9154** [comment]
> [vpc-ntier.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3192159/vpc-ntier.txt)
> use this script

wow ....its working fine

tq u so much naresh 

from afternoon onwards am getting this error

finally sloved

**Comment by ghost** [comment]
ok praveen please close issue

**Comment by praveenkumar9154** [comment]
ok tq u guys
