### ISSUE TITLE
how to enable password authentication on windows ami using  aws

### ISSUE THREAD

**Issue by singaravellu** [QT-DevOps/DevOpsIssues#462]

**Comment by bhaskardegala** [comment]
these two links will help you in finding solution 

Setting Passwords for Windows Instances [link](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-windows-passwords.html)
reset the administrator password on a Windows [link](https://aws.amazon.com/premiumsupport/knowledge-center/reset-admin-password/)

**Comment by ghost** [comment]
in windows, we get the password by using .pem file and if you want to change password we can

**Comment by sandhyadev** [comment]
This link might be help you [https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ResettingAdminPassword_EC2Config.html](url)

**Comment by bhaskardegala** [comment]
Please close your isuue if you are resolved with these resolutions
