### ISSUE TITLE
error:httpd has no installation candidate.

### ISSUE THREAD

**Issue by Nara-Sagar** [QT-DevOps/DevOpsIssues#463]
![image](https://user-images.githubusercontent.com/48256252/57966519-908d7b00-7970-11e9-968f-00cdc6dd6d77.png)

**Comment by bhaskardegala** [comment]
if you are using ubuntu it was apache2 not httpd
httpd is for redhat and centos
so change httpd to apache2 in your script it will work fine

**Comment by Nara-Sagar** [comment]
yes, replaced  apache2 instead of httpd now it's working.
![image](https://user-images.githubusercontent.com/48256252/57966605-05ad8000-7972-11e9-9f36-bfcdf77d5bb3.png)
