### ISSUE TITLE
getting error while vpc peering  with terraform

### ISSUE THREAD

**Issue by dharmatejadevops** [QT-DevOps/DevOpsIssues#464]
attached my terraform files
![pearringerror](https://user-images.githubusercontent.com/43385451/57973496-1a683300-79c7-11e9-99ce-1b415e49008b.png)
[peering.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3194352/peering.zip)

**Comment by sandhyadev** [comment]
peering ip's are miss matched.
please check ur peering ip's and set correctly in peering connection resource.

**Comment by dharmatejadevops** [comment]
> peering ip's are miss matched.
> please check ur peering ip's and set correctly in peering connection resource.

thanks for replaying , ya its correct ip's are mismatched and i will changed the destination cidr blocs and tried its working now.
