### ISSUE TITLE
terraform with ansible deployment error

### ISSUE THREAD

**Issue by kalyanraj236** [QT-DevOps/DevOpsIssues#465]
[terraform.log](https://github.com/QT-DevOps/DevOpsIssues/files/3196351/terraform.log)
[ansible.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3196359/ansible.txt)

**Comment by sandhyadev** [comment]
In your ansible.tf file, the path u give is incorrect while excuting the playbook in provisioner section .
excute this coomand 
"ansible-playbook -i /home/ubuntu/ansible_playbooks/inventory /home/ubuntu/ansible_playbooks/lamp_ubuntu.yml". 
Instead of
ansible-playbook /home/ubuntu/ansible-playbook/lamp_ubuntu.yml
and also some error in ur ansible playbook

**Comment by bhaskardegala** [comment]
hello kalyan,
try this provision it was working good, please change your paths accordingly 
![Capture](https://user-images.githubusercontent.com/48744320/58039462-8033f680-7b50-11e9-9a0a-4c906fb535aa.PNG)

**Comment by nareshabbanapuri** [comment]
if you want to use local-exec (use this script)
resource "aws_instance" "web" {
  ami           = "ami-00331b0e364563ba3"
  instance_type = "t2.micro"
  key_name = "vpc"
  security_groups =["${aws_security_group.allow_tls.id}"]
  subnet_id = "${aws_subnet.subnet-web.id}"
  associate_public_ip_address = true

  tags = {
    Name = "web-vm"
  }
  connection {
    type     = "ssh"
    user     = "ubuntu"
    private_key = "${file("./vpc.pem")}"
  }
  provisioner "remote-exec" {
    inline = [ "sudo apt-get update" , "sudo apt-get install python -y"]}

**Comment by nareshabbanapuri** [comment]
try this one also (create a image with ansible by using packer) 
-------------------------------------------------------------------
resource "aws_instance" "web" {
  ami           = "ami-0da53519542cc375e" 
  instance_type = "t2.micro"
  key_name = "vpc"
  security_groups =["${aws_security_group.allow_tls.id}"]
  subnet_id = "${aws_subnet.subnet-web.id}"
  associate_public_ip_address = true

  tags = {
    Name = "web-vm"
  }
  connection {
    type     = "ssh"
    user     = "ansible"
    password = "ansible"
  }
  provisioner "remote-exec" {
    inline = [        "cd ~","git clone https://github.com/omkaramkalyan/ansible_playbooks.git",
            "ansible-playbook ansible_playbooks/lamp_ubuntu.yml"
    ]
  }
}

**Comment by nareshabbanapuri** [comment]
both are working try any one (or both)

**Comment by kalyanraj236** [comment]
issue resolved..
