### ISSUE TITLE
which vsphere ,vcentre machine is created??

### ISSUE THREAD

**Issue by AnoopPogaru** [QT-DevOps/DevOpsIssues#467]
{
  "type": "vmware-iso",
  "iso_url": "http://old-releases.ubuntu.com/releases/precise/ubuntu-12.04.2-server-amd64.iso",
  "iso_checksum": "af5f788aee1b32c4b2634734309cc9e9",
  "iso_checksum_type": "md5",
  "ssh_username": "packer",
  "ssh_password": "packer",
  "shutdown_command": "shutdown -P now"
}

**Comment by AnoopPogaru** [comment]
We have downloaded the iso image from website, found the iso checksum....using md5sum file.iso

**Comment by AnoopPogaru** [comment]
I dont understand wer is the ubuntu vm created on which silo or which datacentre.,,Can you help me these details using the code. need to built an image using packer on vsphere.

**Comment by nareshabbanapuri** [comment]
use this script
{
    "variables": {
        "myaccess": "xxxxxxxxxxxxxxxxxxxxx",
        "mysecrete": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    "builders": [
        {
            "type": "amazon-ebs",
            "region": "us-west-2",
            "instance_type": "t2.micro",
            "ami_name": "packer-rehl",
            "source_ami": "ami-079596bf7a949ddf8",
            "access_key": "{{user `myaccess`}}",
            "secret_key": "{{user `mysecrete`}}",
            "ssh_username": "ec2-user"
        },
        {
            "type": "hyperv-iso",
            "iso_url": "http://releases.ubuntu.com/12.04/ubuntu-12.04.5-server-amd64.iso",
            "iso_checksum": "769474248a3897f4865817446f9a4a53",
            "iso_checksum_type": "md5",
            "ssh_username": "packer",
            "ssh_password": "packer",
            "shutdown_command": "echo 'packer' | sudo -S shutdown -P now"
          }
    ],
    "provisioners": [
        {
            "type": "shell",
            "inline": [
                "sudo yum update -y",
                "sudo yum install git -y",
                "sudo yum install tree -y"
            ]
        }
    ]
}

**Comment by bhaskardegala** [comment]
> I dont understand wer is the ubuntu vm created on which silo or which datacentre.,,Can you help me these details using the code. need to built an image using packer on vsphere.

The builder builds a virtual machine by creating a new virtual machine from scratch, booting it, installing an OS, provisioning software within the OS, then shutting it down. The result of the VMware builder is a directory containing all the files necessary to run the virtual machine

**Comment by AnoopPogaru** [comment]
But here why did u include amazon ami and zones of ami , which is not related to vmware

**Comment by AnoopPogaru** [comment]
"type": "vmware-iso",
"iso_url": "http://old-releases.ubuntu.com/releases/precise/ubuntu-12.04.2-server-amd64.iso",
"iso_checksum": "af5f788aee1b32c4b2634734309cc9e9",
"iso_checksum_type": "md5",
"ssh_username": "packer",
"ssh_password": "packer",
"shutdown_command": "shutdown -P now"

for this script , i need to know wer is the vm getting deployed on which silo, which datacentre.

**Comment by AnoopPogaru** [comment]
Can you add more attributes to my code, so that can demonstrate as bright idea in office..I want to explain about packer that it s trying to create an image into some x datacentre , y silo, z host,,Thats my moto.

**Comment by bhaskardegala** [comment]
> "type": "vmware-iso",
> "iso_url": "http://old-releases.ubuntu.com/releases/precise/ubuntu-12.04.2-server-amd64.iso",
> "iso_checksum": "af5f788aee1b32c4b2634734309cc9e9",
> "iso_checksum_type": "md5",
> "ssh_username": "packer",
> "ssh_password": "packer",
> "shutdown_command": "shutdown -P now"
> 
> for this script , i need to know wer is the vm getting deployed on which silo, which datacentre.

you can find it in vm datasource

**Comment by bhaskardegala** [comment]
Hey Anoop if you are using vm ware workstation,hyper-v, virtual box the image is created locally and if it VMware exi it will store it in your exi server where you can log in
