### ISSUE TITLE
public ip

### ISSUE THREAD

**Issue by praveenkumar9154** [QT-DevOps/DevOpsIssues#469]
while i creating instance its create without public ip...
what is the issue please tell me

![image](https://user-images.githubusercontent.com/49840014/58174992-c4440a00-7cbc-11e9-8d06-34ad564f60e2.png)

**Comment by bhaskardegala** [comment]
Please replan and apply terraform again then you can see public ip address
As have selected public ip address as dynamic and this will be attached to your instance once it was created so inorder to see public ip address re-perform terraform apply --auto-approve

**Comment by praveenkumar9154** [comment]
re-performed terraform apply , but still same issue

**Comment by Naga-vineela** [comment]
Hi .. did u add argument  "associate_public_ip_address = true" on ur compute section ?
under resource "aws_instance" ?
if not , please add and re-run and see if it works .

**Comment by praveenkumar9154** [comment]
> "associate_public_ip_address = true"

Hi vineela 
 its working fine..... tq u so much

**Comment by praveenkumar9154** [comment]
tq u
