### ISSUE TITLE
Docker: Nodejs container getting killed. 

### ISSUE THREAD

**Issue by sanjaysureshmv** [QT-DevOps/DevOpsIssues#47]
[docker.zip](https://github.com/QT-DevOps/DevOpsIssues/files/2137256/docker.zip)
Hi All

First of all it is a lengthy one since i tried to give my whole process. Please have patience in going through them. :)

I was trying to dockerize a nodejs app from a base image of nodejs:10. The issue is that, after running the app the container gets killed. I was using my own network and allocating ip of my desired. It was working and not getting killed when i manually run the whole statements in my Dockerfile. 

Please see what i done manually and building docker image

`ubuntu@ip-172-31-23-111:~/my-images$ docker run -it -v /home/ubuntu/node_vol/:/opt --name node_test4321 --network new_bridge --ip 192.168.0.10 node:10`
> ubuntu@ip-172-31-23-111:~/my-images$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                   NAMES
**22c3fcea0b77**        node:10             "node"              8 seconds ago       Up 8 seconds                                node_test4321
0b3090108e0f        node:10             "node"              11 minutes ago      Up 11 minutes       0.0.0.0:804->8080/tcp   node_vsdfdf
ec0be281e25c        node:10             "node"              13 minutes ago      Up 13 minutes       0.0.0.0:88->8080/tcp    friendly_rosalind
970ef4c77e85        node:10             "/bin/bash"         14 minutes ago      Up 14 minutes       0.0.0.0:808->8080/tcp   xenodochial_davinci
bc7690c38225        node:10             "/bin/bash"         15 minutes ago      Up 15 minutes       0.0.0.0:80->8080/tcp    elated_cray

`ubuntu@ip-172-31-23-111:~/my-images$ docker exec -it 22c3fcea0b77 /bin/bash`
`root@22c3fcea0b77:/# cat opt/src/app/hello.js `
var http = require('http');
http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('Hello World\n');
}).listen(8080, '192.168.0.10');
console.log('Server running at http://192.168.0.10:8080/');

root@22c3fcea0b77:/# cd opt/src/app/
`root@22c3fcea0b77:/opt/src/app# node hello.js `
Server running at http://192.168.0.10:8080/
^C
`root@22c3fcea0b77:/opt/src/app# npm install pm2 -g`
/usr/local/bin/pm2 -> /usr/local/lib/node_modules/pm2/bin/pm2
/usr/local/bin/pm2-dev -> /usr/local/lib/node_modules/pm2/bin/pm2-dev
/usr/local/bin/pm2-runtime -> /usr/local/lib/node_modules/pm2/bin/pm2-runtime
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 
+ pm2@2.10.4
added 223 packages from 206 contributors in 18.73s
`root@22c3fcea0b77:/opt/src/app# pm2 start hello.js`

[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /opt/src/app/hello.js in fork_mode (1 instance)
[PM2] Done.
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────┼────┼──────┼─────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ hello    │ 0  │ fork │ 63  │ online │ 0       │ 0s     │ 0%  │ 23.0 MB   │ root │ disabled │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

`root@22c3fcea0b77:/opt/src/app# curl 192.168.0.10:8080`
**Hello World**

root@22c3fcea0b77:/opt/src/app# read escape sequence
`ubuntu@ip-172-31-23-111:~/my-images$ docker ps`
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                   NAMES
**22c3fcea0b77**        node:10             "node"              11 minutes ago      Up 11 minutes                               node_test4321

`ubuntu@ip-172-31-23-111:~/my-images$ docker build -t my_nodejs_app:10.0 .`
Sending build context to Docker daemon  3.072kB
Step 1/9 : FROM node:10
 ---> 8753edeb1aa3
Step 2/9 : MAINTAINER sanjaymv
 ---> Using cache
 ---> 30db4cc14612
Step 3/9 : RUN mkdir -p /src/app
 ---> Using cache
 ---> 336d605f54d8
Step 4/9 : WORKDIR /src/app
 ---> Using cache
 ---> f969f113c8d4
Step 5/9 : ADD hello.js /src/app/hello.js
 ---> 989b384cafce
Step 6/9 : EXPOSE 8080
 ---> Running in ade2d6715a37
Removing intermediate container ade2d6715a37
 ---> 2e0622d8baaf
Step 7/9 : RUN apt-get update && npm install pm2 -g
 ---> Running in a4ca19ba60f0
Get:1 http://security.debian.org jessie/updates InRelease [94.4 kB]
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [624 kB]
Ign http://deb.debian.org jessie InRelease
Get:3 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:4 http://deb.debian.org jessie Release.gpg [2420 B]
Get:5 http://deb.debian.org jessie-updates/main amd64 Packages [23.0 kB]
Get:6 http://deb.debian.org jessie Release [148 kB]
Get:7 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 10.1 MB in 6s (1498 kB/s)
Reading package lists...
/usr/local/bin/pm2 -> /usr/local/lib/node_modules/pm2/bin/pm2
/usr/local/bin/pm2-dev -> /usr/local/lib/node_modules/pm2/bin/pm2-dev
/usr/local/bin/pm2-docker -> /usr/local/lib/node_modules/pm2/bin/pm2-docker
/usr/local/bin/pm2-runtime -> /usr/local/lib/node_modules/pm2/bin/pm2-runtime
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/pm2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ pm2@2.10.4
added 223 packages from 206 contributors in 9.483s
Removing intermediate container a4ca19ba60f0
 ---> 00fe2e99be73
Step 8/9 : ENTRYPOINT ["pm2"]
 ---> Running in 0f8306cd2097
Removing intermediate container 0f8306cd2097
 ---> d45aabceb60c
Step 9/9 : CMD ["start", "hello.js"]
 ---> Running in c32303875553
Removing intermediate container c32303875553
 ---> adeacef979d1
Successfully built adeacef979d1
Successfully tagged my_nodejs_app:10.0

`ubuntu@ip-172-31-23-111:~/my-images$ docker images | grep adeacef979d1`
my_nodejs_app       10.0                adeacef979d1        3 minutes ago       707MB

`ubuntu@ip-172-31-23-111:~/my-images$ docker run -it -p 8086:8080 --name node_build10.1 --network new_bridge --ip 192.168.0.15 my_nodejs_app:10.0`

                        -------------

__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 

[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /src/app/hello.js in fork_mode (1 instance)
[PM2] Done.
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────┼────┼──────┼─────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ hello    │ 0  │ fork │ 20  │ online │ 0       │ 0s     │ 1%  │ 21.4 MB   │ root │ disabled │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app

`ubuntu@ip-172-31-23-111:~/my-images$` docker ps |grep my_nodejs_app`
`ubuntu@ip-172-31-23-111:~/my-images$ `

Please let me know how I can run the container continuously without getting it killed. My Dockerfile and hello.js code is attachhed with this.

**Comment by shaikkhajaibrahim** [comment]
Follow the image building as  shown in  
https://pm2.io/doc/en/runtime/integration/docker/?utm_source=pm2&utm_medium=website&utm_campaign=rebranding

container is killed as pm2 returns immedietly

**Comment by shaikkhajaibrahim** [comment]
Other route is use node like mentioned in the attachment 
[docker.zip](https://github.com/QT-DevOps/DevOpsIssues/files/2145521/docker.zip)

i had made slight changes to your docker file 
![image](https://user-images.githubusercontent.com/2438317/42038182-f0d8bd5c-7b07-11e8-98af-de62e8db8423.png)

and hello.js
![image](https://user-images.githubusercontent.com/2438317/42038164-e435ee3a-7b07-11e8-86ef-96e02d04f05c.png)

**Comment by sanjaysureshmv** [comment]
Thank you sir. It was a good trick to listen on all ip address. Learned something about pm2 also :)
