### ISSUE TITLE
Not able to add new node , getting failed in Jenkins

### ISSUE THREAD

**Issue by AnoopPogaru** [QT-DevOps/DevOpsIssues#470]
![image](https://user-images.githubusercontent.com/50481515/58235279-23a62680-7d5e-11e9-8856-ed448116f1dc.png)

**Comment by ghost** [comment]
please generate key from master follow this steps
ssh-keygen
ssh-copy-id jenkins@nodeip

**Comment by ghost** [comment]
follow this document
https://blog.knoldus.com/setting-up-master-slave-machines-using-jenkins/

**Comment by ghost** [comment]
1.give sudo permission for user:  visudo
2.enable password-based authentication:  vi /etc/ssh/sshd_config
3.restart ssh : systemctl restart sshd
4.key generate from master login into Jenkins user : ssh-keygen
5.copy key into slave : ssh-copy-id username@slaveip
step 1 2 3  do it in both master and slave

**Comment by bhaskardegala** [comment]
Anoop this error stats that key exchange was not finished it means you did not copy your public key to the node and this should be done manually and you just follow the steps stated by naresh

**Comment by AnoopPogaru** [comment]
issue with ssh keys, created new keys 

1.give sudo permission for user: visudo
2.enable password-based authentication: vi /etc/ssh/sshd_config
3.restart ssh : systemctl restart sshd
4.key generate from master login into Jenkins user : ssh-keygen
5.copy key into slave : ssh-copy-id username@slaveip
step 1 2 3 do it in both master and slave

after doing this steps.it works for me..thanks!!
