### ISSUE TITLE
webhook issue

### ISSUE THREAD

**Issue by Ankireddykatha** [QT-DevOps/DevOpsIssues#471]
hi guys ,i have to trigger automatic Build when a change is pushed to BitBucket....

====i have installed git bucket plugin and enabled build when a change is pushed to bitbucket

===i have created webhook like url : 
http://xxxxx:8080
and 
http://xxxxxxx:8080/bitbucket-hooks/ still webhook automatic builds are not triggered..

i m getting this(((( Last BitBucket Push
Polling has not run yet.)))

when i put poll scm like * * * * * then builds are triggered.... can you give me anyhelp...

**Comment by bhaskardegala** [comment]
Make sure that ip address provided was public and try using https 
And make sure that you have added this url to you bitbucket hooks in my case I used git-hub
And attached url something like https://<public_ip>:8080/web-hooks/ to my git hub web-hooks (which can be seen in settings section of your repo)

**Comment by bhaskardegala** [comment]
Make sure that you have checked the box which stats "GitHub hook trigger for GITScm polling" while creating the pipeline if you are using git-hub and in your case you can find something related to bit bucket SCM trigger if you have already installed bit bucket plugin

**Comment by ghost** [comment]
hi ankireddy 
that steps are work for github,
you have to do extra settings for bitbucket 
try this
https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/381419546/Configuring+Webhook+To+Jenkins+for+Bitbucket+Bitbucket+Branch+Source+Plugin

**Comment by sandhyadev** [comment]
This link may help u ,while to trigger automatic Build when a change is pushed to BitBucket
![preview](https://stackoverflow.com/questions/11231064/how-do-i-get-jenkins-to-build-on-push-to-a-bitbucket-git-repository)

**Comment by sandhyadev** [comment]
This link may help u while trigger automatically Build when a change is pushed to BitBucket
https://stackoverflow.com/questions/11231064/how-do-i-get-jenkins-to-build-on-push-to-a-bitbucket-git-repository

**Comment by Ankireddykatha** [comment]
thanks........
