### ISSUE TITLE
terraform launch instance in existing VPC

### ISSUE THREAD

**Issue by saikiran243** [QT-DevOps/DevOpsIssues#474]
How to launch an Instance from an existing VPC.. iam unable to find the solution for it

**Comment by bhaskardegala** [comment]
Attach the instance to the specified security group

**Comment by bhaskardegala** [comment]
U can use this argument in your instance
security_groups

**Comment by sandhyadev** [comment]
In the instance resource attach security_groups.
This is one process with already created security group with default vpc
    
![Capture1](https://user-images.githubusercontent.com/42669522/58452240-4ce6fe00-8134-11e9-8af5-76ec6392598c.PNG)

The next process is to create custom vpc along with subnet, routetable (route, subnet association)internet gateway and security group. 
when u creating an instance u specify security_groups name and subnet.

**Comment by bhaskardegala** [comment]
Kiran 
Please close the issue if it was resolved
