### ISSUE TITLE
Package not installting

### ISSUE THREAD

**Issue by khatrigopal** [QT-DevOps/DevOpsIssues#475]
Hi
Please check my terraform file and my pem file also in same directory but package not installing on connection not able to connect, but no error on apply time

provider "aws" {
  region     = "us-west-2"
  access_key = "XXXXXXXX
  secret_key = "XXXXXXXX
}

resource "aws_instance" "webserver" {
    tags {
    "Name" = "Kibana-Testing"
  }
    ami = "ami-005bdb005fb00e791"
    instance_type = "t2.micro"
    vpc_security_group_ids = ["sg-05289978ac69c1a9c"] //subnet group id
    subnet_id = "subnet-0264de1ddd6382637"
    key_name = "testing"

   
}
 
 resource "aws_eip" "ip-test-env" {
  instance = "${aws_instance.webserver.id}"
  vpc      = true

   connection {
        type = "ssh"
        user = "ubuntu"
        private_key = "${file("./testing.pem")}"
    }

    provisioner  "remote-exec" {
        inline = [
       "sudo apt-get update",
      "sudo apt-get install apache2 -y",
      "sudo systemctl enable apache2",
      "sudo systemctl start apache2",
      "sudo chmod 777 /var/www/html/index.html"
        ]
    }   
  }

**Comment by ghost** [comment]
[te.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3232202/te.txt)

I made some changes in your script,  use this

**Comment by khatrigopal** [comment]
Hi
I check with your file but it is not working.
please resolve it.

**Comment by bhaskardegala** [comment]
Hey Gopal 
Your connection and provisioner should become to aws_instance resource but not aws_eip resource please make this change and it will work

**Comment by bhaskardegala** [comment]
Hey Gopal,
Please close the issue if it was resolved

**Comment by khatrigopal** [comment]
resolve
