### ISSUE TITLE
terraform installation failed in choco

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/DevOpsIssues#476]
![terraform ins fail](https://user-images.githubusercontent.com/50665358/58564654-f8827200-824a-11e9-8382-a39154294eb4.PNG)
 when I want to install terraform with choco its failed due to some error

**Comment by bhaskardegala** [comment]
Hey chowdamramana 
Run your powershell as administrator and let us know the status

**Comment by sandhyadev** [comment]
hi chowdamramana,
ur issue belong to permission deny problem.open ur powershell in admin mode and run the terraform command

**Comment by bhaskardegala** [comment]
Hey chowdamramana
Please close the issue if it was resolved
