### ISSUE TITLE
error in the power shell when i copy the path of terraform file

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/DevOpsIssues#479]
![power error](https://user-images.githubusercontent.com/50665358/58745453-da955700-846e-11e9-8d54-d82ab7d24236.PNG)

**Comment by bhaskardegala** [comment]
Hey chowdamramana
Try not giving spaces to your devops folder

**Comment by chowdamramana** [comment]
> Hey chowdamramana
> Try not giving spaces to your devops folder

![Capture](https://user-images.githubusercontent.com/50665358/58746482-3f0ae300-847c-11e9-9692-037147fe89ed.PNG)
again i got the same error
