### ISSUE TITLE
Kubernetes: Pods Ip connection refused

### ISSUE THREAD

**Issue by sanjaysureshmv** [QT-DevOps/DevOpsIssues#48]
I created a nodeport service and exposed the port 30036 using nodePort statement.  I was able to get the nginx welcome page using the private ip of ec2 instance from both Master and Node but when I curl the pod's Ip, I got connection refused. Can any one tell me the reason behind it? cant we expose the pods IP?

`ubuntu@ip-172-31-17-243:~$` kubectl get pods -o wide`

NAME                              READY     STATUS    RESTARTS   AGE       IP          NODE
my-replication-controller-7mj65   1/1       Running   0          1h        10.44.0.1   ip-172-31-29-38
my-replication-controller-gc96t   1/1       Running   0          1h        10.44.0.2   ip-172-31-29-38
my-replication-controller-sg64p   1/1       Running   0          1h        10.44.0.3   ip-172-31-29-38
**my-test-node-port                 1/1       Running   0          36m       10.44.0.4   ip-172-31-29-38**

`ubuntu@ip-172-31-17-243:~$ curl 172.31.29.38:30036`
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>

`ubuntu@ip-172-31-17-243:~$ curl 10.44.0.4:30036`
curl: (7) Failed to connect to 10.44.0.4 port 30036: Connection refused

**Comment by shaikkhajaibrahim** [comment]
As mentioned accessing the pod is possible via node ip address it self.
