### ISSUE TITLE
error when executing the command apply

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/DevOpsIssues#480]
![config terra](https://user-images.githubusercontent.com/50665358/58746574-50a0ba80-847d-11e9-8414-6c622ad457a1.PNG)
![apply err](https://user-images.githubusercontent.com/50665358/58746576-54ccd800-847d-11e9-9ca6-bdcb7bfbff1f.PNG)

**Comment by Naga-vineela** [comment]
issue with your key file as per error message . Please check if u have that Keyfile with given name  in US-west region .

**Comment by ghost** [comment]
please give administrator access permission to iam user 
and give access and secret keys

**Comment by Naga-vineela** [comment]
Yea if its not yet added to admin .. give req permission s n retry
