### ISSUE TITLE
Need Spring Pet Clinic jar

### ISSUE THREAD

**Issue by shaikkhajaibrahim** [QT-DevOps/DevOpsIssues#481]

**Comment by ghost** [comment]
for spring pet-clinic github location
[click here](https://github.com/spring-projects/spring-petclinic)

for spring pet-clinic.jar file
[click here](https://naresh-springpetclinicjarfile.s3-us-west-2.amazonaws.com/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar)
