### ISSUE TITLE
spring pet clinic

### ISSUE THREAD

**Issue by khatrigopal** [QT-DevOps/DevOpsIssues#482]
When i am taking spring pet clinic repo and integrated with jenkins and build mvn package its sowing below error

Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-all/1.7.4/groovy-all-1.7.4.jar (5.4 MB at 1.2 MB/s)
[INFO] /var/lib/jenkins/workspace/sprint-petclinic/src/main/less
[INFO] Executing the mojo: 
[INFO] Wro4j Model path: /var/lib/jenkins/workspace/sprint-petclinic/src/main/wro/wro.xml
[INFO] targetGroups: null
[INFO] minimize: true
[INFO] ignoreMissingResources: null
[INFO] parallelProcessing: false
[INFO] buildDirectory: /var/lib/jenkins/workspace/sprint-petclinic/target
[INFO] destinationFolder: /var/lib/jenkins/workspace/sprint-petclinic/target
[INFO] cssDestinationFolder: /var/lib/jenkins/workspace/sprint-petclinic/target/classes/static/resources/css
[INFO] The following groups will be processed: [petclinic]
[INFO] folder: /var/lib/jenkins/workspace/sprint-petclinic/target/classes/static/resources/css
[INFO] processing group: petclinic.css
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000fd836000, 41721856, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 41721856 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /var/lib/jenkins/workspace/sprint-petclinic/hs_err_pid13963.log
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE

**Comment by khatrigopal** [comment]
I am using t2.micro instance

**Comment by bhaskardegala** [comment]
Hey gopal 
You cant build spring petclinic on t2.micro machine try using at least medium machine

**Comment by ghost** [comment]
first, try it manually and then  do from Jenkins
 Decrease number of Java threads in your machine
stop other jobs in Jenkins

**Comment by khatrigopal** [comment]
Ok. Thanks
