### ISSUE TITLE
Regarding Terraform integrated with jenkins (need docs)

### ISSUE THREAD

**Issue by khatrigopal** [QT-DevOps/DevOpsIssues#483]
Please provide docs or step for how can i integrated my tarraform (.tf) file with Jenkins.

**Comment by ghost** [comment]
https://dzone.com/articles/immutable-infrastructure-cicd-using-hashicorp-terr

**Comment by sandhyadev** [comment]
Terraform Pipelines in Jenkins:
https://medium.com/@timhberry/terraform-pipelines-in-jenkins-47267129ff06

Integrate Terraform with Jenkins using plugin
:https://medium.com/@khandelwal12nidhi/integrate-terraform-with-jenkins-d283dd5d819c

**Comment by khatrigopal** [comment]
Hi

Thanks for your docs, i followed he docs and create a jenkins pipeline

pipeline {
 agent any
 
 stages {
    stage(‘checkout’) {
        steps {
            git branch: 'master', credentialsId: 'XXXXXXXXXXXXX', url: 'https://github.com/khatrigopal/terraform-jenkins.git'
 
        }
    }
    
   // stage('Set Terraform path') {
       // steps {
           // script {
              //  def tfHome = tool name: ‘Terraform’
               // env.PATH = "${tfHome}:${env.PATH}"
            //}
                // sh 'terraform — version'
 
 
     //}
// }
 
    stage('Provision infrastructure') {
 
        steps {
             dir('myfirstec2')
             {
             sh 'terraform init'
             sh 'terraform plan -var "accesskey="${accesskey}" -var "secretkey="${secretkey}" -out=plan'
             // sh 'terraform destroy -auto-approve'
             sh 'terraform apply plan'
             }
 
 
        }
 }
 
 
 
 }
}

and create 2 parameter for access key and secret key.
![terraform-jenkins](https://user-images.githubusercontent.com/35285671/58861124-4f64cd00-86cb-11e9-87e7-16b3c480d1dc.png)

Its working fine.

but my question is i m providing hard core value for access key and secret key in parameter but i dont want it.

Please resolve this issue.

**Comment by bhaskardegala** [comment]
you can use credentials to know more about it refer [here](https://support.cloudbees.com/hc/en-us/articles/203802500-Injecting-Secrets-into-Jenkins-Build-Jobs)

**Comment by khatrigopal** [comment]
Hi
How can we use these credentials plugin for ACCESSKEY and SECRETKEY.
