### ISSUE TITLE
error in executing validate in terraform

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/DevOpsIssues#484]
![apche config](https://user-images.githubusercontent.com/50665358/58878533-1e978e80-86f1-11e9-8e3b-16c4de61e307.PNG)
![apche error](https://user-images.githubusercontent.com/50665358/58878536-1f302500-86f1-11e9-9682-c685ef7ec9f5.PNG)

**Comment by bhaskardegala** [comment]
Hey chowdamramana
Your connection and provisioner are at root level try giving spaces at starting 
And change your private key 
Private_key = "${file("./terraformpract.pem")}" 
You need to give double quotes even for your pem file  make these changes and it will definitely work

**Comment by chowdamramana** [comment]
when i give the double quotations it giving the error
![Capture](https://user-images.githubusercontent.com/50665358/58879971-75529780-86f4-11e9-8fea-bc21a7d33875.PNG)
![Capture1](https://user-images.githubusercontent.com/50665358/58879972-75eb2e00-86f4-11e9-87a7-482013f83fe4.PNG)

**Comment by sandhyadev** [comment]
In connection session ,give the user of ur ec2 machine,but not "terraformpratice"
![Capture12](https://user-images.githubusercontent.com/42669522/58882010-ff046400-86f8-11e9-8157-8654e4f5ddd4.PNG)

**Comment by chowdamramana** [comment]
> In connection session ,give the user of ur ec2 machine,but not "terraformpratice"
> ![Capture12](https://user-images.githubusercontent.com/42669522/58882010-ff046400-86f8-11e9-8157-8654e4f5ddd4.PNG)

it is instance name or user name in aws

**Comment by chowdamramana** [comment]
![err](https://user-images.githubusercontent.com/50665358/58882482-fb251180-86f9-11e9-83e7-d718fa3100db.PNG)

**Comment by chowdamramana** [comment]
![err con](https://user-images.githubusercontent.com/50665358/58882509-0710d380-86fa-11e9-9694-fbaff4eb68b6.PNG)

**Comment by ghost** [comment]
provider "aws" {
  region     = "us-west-2"
  access_key = ""
  secret_key = ""
}

resource "aws_instance" "web" {
  ami                    = "ami-0cb72367e98845d43"
  instance_type          = "t2.micro"
  vpc_security_group_ids = ["sg-0354745117b830051"]
  key_name               = "vpc"

  tags = {
    Name = "HelloWorld"
  }

  connection {
    type        = "ssh"
    user        = "ec2-user"
    private_key = "${file("./vpc.pem")}"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo yum install httpd -y"
    ]
  }
}
use default security group
 use this script , changes as per your requirement

**Comment by bhaskardegala** [comment]
Please upload your file in txt format we can make changes and send you back then you can compare them

**Comment by chowdamramana** [comment]
> Please upload your file in txt format we can make changes and send you back then you can compare them

[web.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3253326/web.txt)

**Comment by chowdamramana** [comment]
> Please upload your file in txt format we can make changes and send you back then you can compare them

[apache.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3253343/apache.txt)

**Comment by chowdamramana** [comment]
I am unable to open apache on the web, what i want to do. after the instance is created

**Comment by chowdamramana** [comment]
the error came when i executing the cmd for the configuration file of your giving
![Capture22](https://user-images.githubusercontent.com/50665358/58895443-86f66800-8711-11e9-83b4-34064ff2b7bc.PNG)

**Comment by bhaskardegala** [comment]
[apache.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3253432/apache.txt)
try this script and make sure you have your pem file in the same folder

**Comment by ghost** [comment]
> the error came when i executing the cmd for the configuration file of your giving
> ![Capture22](https://user-images.githubusercontent.com/50665358/58895443-86f66800-8711-11e9-83b4-34064ff2b7bc.PNG)

please give location of pem file in private_key

**Comment by chowdamramana** [comment]
> > the error came when i executing the cmd for the configuration file of your giving
> > ![Capture22](https://user-images.githubusercontent.com/50665358/58895443-86f66800-8711-11e9-83b4-34064ff2b7bc.PNG)
> 
> please give location of pem file in private_key

when i giving the location of prem file it shows an error
![Capture](https://user-images.githubusercontent.com/50665358/58938353-468afe80-8792-11e9-92ba-9d6aa2cd6569.PNG)

**Comment by bhaskardegala** [comment]
> > > the error came when i executing the cmd for the configuration file of your giving
> > > ![Capture22](https://user-images.githubusercontent.com/50665358/58895443-86f66800-8711-11e9-83b4-34064ff2b7bc.PNG)
> > 
> > 
> > please give location of pem file in private_key
> 
> when i giving the location of prem file it shows an error
> ![Capture](https://user-images.githubusercontent.com/50665358/58938353-468afe80-8792-11e9-92ba-9d6aa2cd6569.PNG)

After closing bracket you need to even close  double quotes

**Comment by chowdamramana** [comment]
> > > > the error came when i executing the cmd for the configuration file of your giving
> > > > ![Capture22](https://user-images.githubusercontent.com/50665358/58895443-86f66800-8711-11e9-83b4-34064ff2b7bc.PNG)
> > > 
> > > 
> > > please give location of pem file in private_key
> > 
> > 
> > when i giving the location of prem file it shows an error
> > ![Capture](https://user-images.githubusercontent.com/50665358/58938353-468afe80-8792-11e9-92ba-9d6aa2cd6569.PNG)
> 
> After closing bracket you need to even close double quotes

I am
![Capture](https://user-images.githubusercontent.com/50665358/59025809-a062f580-8872-11e9-9952-585fb4f104a3.PNG)
 closing the double quotes

**Comment by chowdamramana** [comment]
in validate it asking the host, 
![Capture2](https://user-images.githubusercontent.com/50665358/59026130-5595ad80-8873-11e9-9b58-e7ed497a25bb.PNG)
![Capture5](https://user-images.githubusercontent.com/50665358/59026132-562e4400-8873-11e9-9b77-22a03af7b822.PNG)

so what i want i want to do

**Comment by bhaskardegala** [comment]
After tags try removing = symbol
