### ISSUE TITLE
unable to pull 8-jdk

### ISSUE THREAD

**Issue by ghost** [QT-DevOps/DevOpsIssues#485]
unable to pull '8-jdk' from dockerhub , getting below error

docker: Error response from daemon: pull access denied for 8-jdk, repository does not exist or may require 'docker login'.

**Comment by ghost** [comment]
use this openjdk:8-jdk

**Comment by bhaskardegala** [comment]
openjdk:8

**Comment by ghost** [comment]
hello chittini 
if its works please close issue

**Comment by shaikkhajaibrahim** [comment]
wrong image name
