### ISSUE TITLE
i cant get a apache server manually

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/DevOpsIssues#488]
![3](https://user-images.githubusercontent.com/50665358/58939405-c9ad5400-8794-11e9-8c64-3e8dbc72492a.PNG)
I am doing this process
but i can't get it 
![2](https://user-images.githubusercontent.com/50665358/58939439-daf66080-8794-11e9-8099-e131996a450d.PNG)

**Comment by chowdamramana** [comment]
this is my ip 54.218.120.211

**Comment by sandhyadev** [comment]
In the security group, open 80 port and then browse
http:// 54.218.120.211:80

**Comment by chowdamramana** [comment]
> In the security group, open 80 port and then browse
> http:// 54.218.120.211:80

yeah its worked.but why we open port 80

**Comment by sandhyadev** [comment]
httpd runs on default port 80

**Comment by ghost** [comment]
I think you got the essence 
please close issue
