### ISSUE TITLE
Sir, May I know why I am getting that Yellow highlighted error in editor?! Thanks,

### ISSUE THREAD

**Issue by hanocc** [QT-DevOps/DevOpsIssues#489]
![Error](https://user-images.githubusercontent.com/51271895/58975139-de640900-87e1-11e9-932e-49f3643f4c4a.PNG)

Sir, May I know Why I am getting that Yellow Highlighted error in Editor. Thanks,

**Comment by ghost** [comment]
try this
sudo apt-get install vim -y
use vim instead of vi
and nano also

**Comment by bhaskardegala** [comment]
Try using nano editor and somehow it looks like a Linux bash environment issue try to restart or reboot your machine at once

**Comment by sandhyadev** [comment]
You could simply use your package manager and see if vim is installed. If not, install it.
The vi command will probably be installed as a symbolic link /bin/vi -> /bin/vim.
Install "sudo yum install vim".
