### ISSUE TITLE
Hi, I am getting error(see the attached screen shot). Did any command I missed?

### ISSUE THREAD

**Issue by hanocc** [QT-DevOps/DevOpsIssues#491]
Hi, I am getting error(see the attached screen shot). Did any command I missed?
![Error2](https://user-images.githubusercontent.com/51271895/59013387-76e8a080-8857-11e9-81bd-3e8f6a15881e.PNG)

**Comment by shaikkhajaibrahim** [comment]
No containers are running
try docker container ls -a -q
________________________________

**Comment by bhaskardegala** [comment]
You are not specifing path correctly in your image build step try this 
docker image build -t petclinic:1.1 . (Here last dot specific your current working directory)
In your case you have combined your path with tag

**Comment by sandhyadev** [comment]
Removings the all docker containers, try this : 
docker container rm -f ($docker container ls -a -q)
To build the image ,try this:
docker image build -t petclinic:1.1  .
