### ISSUE TITLE
Regarding Dockerfile

### ISSUE THREAD

**Issue by khatrigopal** [QT-DevOps/DevOpsIssues#492]
Hi

I have 3 working environments  DEV/QA/STG and and i am using nodejs application. Now i want to create a Dockerfile for all the environment, but challenges are:

1. Create a generic Dockerfile for all the env, but all the env. are using diff-differ values
2. Env Values are:
COOKIE_PASSWORD
HEAD_UNIT_USERNAME
HEAD_UNIT_PASSWORD
PG_DB
PG_HOST
PG_PORT
PG_USERNAME
PG_PASSWORD
PORT
WS_ACCESS_KEY
AWS_SECRET_ACCESS_KEY
AWS_REGION
AWS_S3_BUCKET
AWS_SQS_CAMPAIGNS_QUEUE_URL
AWS_SQS_VEHICLES_QUEUE_URL
PQSS_ENABLED=true
AWS_SQS_NOTIFICATION_QUEUE_URL
API_KEY_ENABLED
API_KEY_ID

These values are differ for all DEV/QA/STG.
so How can i create a generic Dockerfile and use these env for particular env.

Please resolve it.

**Comment by ghost** [comment]
create  three different env-files for DEV QA UAT 
using docker-compose call env-files

**Comment by bhaskardegala** [comment]
You can pass those variables in your command line while running your container with help --env and you change variables which are under ENV instruction but not ARG

**Comment by sandhyadev** [comment]
Try this link, you get an clear idea:
https://github.com/docker/compose/issues/6170

**Comment by khatrigopal** [comment]
i dont want to use docker container and when i am providing env variable at run time, application is not starting

**Comment by bhaskardegala** [comment]
Hey Gopal
May I know what was the application that your trying to run and what was your cmd instruction , if possible please share your dockerfile
