### ISSUE TITLE
In some conditions my CMD not executing and killing my container while using variables 

### ISSUE THREAD

**Issue by bhaskardegala** [QT-DevOps/DevOpsIssues#493]
Hello Team please me in explaining why i am not able use ENV variable in CMD instruction 
and here i have three conditions where two are failing and one was successful and i have provided the dockerfile below and i am intentionally placing all three files in one file as it can give you some keen view on those files and please find attached text file with this issue
---
(Container dieing as cmd not executed)
FROM tomcat:8
LABEL author="some-one"
ENV package_name="spring-petclinic.jar"
ADD https://naresh-springpetclinicjarfile.s3-us-west-2.amazonaws.com/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar ${package_name}
CMD [ "java", "-jar", ${package_name} ]

---
(Container dieing as cmd not executed)
FROM tomcat:8
LABEL author="some-one"
ENV package_name="spring-petclinic.jar"
ADD https://naresh-springpetclinicjarfile.s3-us-west-2.amazonaws.com/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar ${package_name}
CMD [ "java", "-jar", "${package_name}" ]

---
(Container runing)
FROM tomcat:8
LABEL author="some-one"
ENV package_name="spring-petclinic.jar"
ADD https://naresh-springpetclinicjarfile.s3-us-west-2.amazonaws.com/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar ${package_name}
CMD java -jar ${package_name} 

[dockerfile.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3265837/dockerfile.txt)

**Comment by Karthick-Gopalakrishnan** [comment]
Hello Baskar,

Attached Dockerfile works , Google says If you want your CMD to expand variables, you need to arrange it for shell,  CMD [ "sh", "-c", "java -jar ${package_name}" ] 

[Dockerfile.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3268414/Dockerfile.txt)

**Comment by bhaskardegala** [comment]
Thanks Karthik for writing to me 
But my question was  why it was working on shell only while ever other command was working normally

**Comment by Karthick-Gopalakrishnan** [comment]
Its clear that CMD is unable to process the variable declared when it passed in a list form 

CMD [ "java", "-jar", "${package_name}" ]

CMD [ "java", "-jar", "${package_name}" ]

here CMD is not using the shell to execute the objects declared , So, it is creating an exception while running the container and it fails..

CMD java -jar ${package_name} : Here CMD is considering java -jar ${package_name} as single object and it is executing it

We will try to figure out the technical explanation behind it

**Comment by bhaskardegala** [comment]
Thanks Karthik for your valuable information I will close the issue for now and update this issue with resolution once I get complete grip over it
