### ISSUE TITLE
Regarding Docker

### ISSUE THREAD

**Issue by khatrigopal** [QT-DevOps/DevOpsIssues#494]
How can we launch a docker container with non root user.

**Comment by ghost** [comment]
use this command
sudo usermod -aG docker username
your user become part of docker group
after exit and re-login to machine

**Comment by khatrigopal** [comment]
my question is when i creating docker image and run the container and when go inside container, its by default root user.
so i want when i go inside go the container it will show non root user.

**Comment by bhaskardegala** [comment]
please refer this link [click here](https://medium.com/@lucjuggery/running-a-container-with-a-non-root-user-e35830d1f42a) it might definitely help you

**Comment by khatrigopal** [comment]
Thanks
i went go through this link but didnt get any information.
can you share some steps for that

**Comment by NareshAbbanapuri** [comment]
why you need? 

> when i go inside go the container it will show non root 
why you need?

**Comment by ghost** [comment]
USER ubuntu
WORKDIR /home/ubuntu
USER someone
you can use this instruction 
it creates user and you will switch as a that user

**Comment by bhaskardegala** [comment]
Hey Gopal 
I think your issue was resolved from today's class if not let us know at once

**Comment by khatrigopal** [comment]
Hi

when i creating any os image (like centos) add user in dockerfile but how can i do it for nginx or another container.

Please give proper command.

**Comment by bhaskardegala** [comment]
Hey Gopal
I couldn't get your question exactly but I think you are asking that how can you add a user to nginx and login with that user for this follow the steps
In your dockerfile take nginx as your base image and file looks like 
FROM nginx
RUN useradd Gopal
USER Gopal
CMD [""]
and while you are trying to login to a container which was running from this image you will get logged in as Gopal user 
If you want to login as a root user instead Gopal user then use this
docker container exec -it -u root container_name /bin/bash
