### ISSUE TITLE
Hi I am facing issue while connecting machine Please find the error screen shot . Could you please tell me the root cause.

### ISSUE THREAD

**Issue by hanocc** [QT-DevOps/DevOpsIssues#495]
![Issue1](https://user-images.githubusercontent.com/51271895/59143063-14bda600-89e5-11e9-8867-5b619f0b8464.PNG)

**Comment by bhaskardegala** [comment]
Please terminate some instances first and try again

**Comment by ghost** [comment]
please read logs clearly
for free tier allow 10 instances only at a time
terminate some of them

**Comment by sandhyadev** [comment]
it looks, your ec2 service  per region limit exceeded in free tier.
First terminate some instances and try again or send an request to amazon for more instances
