### ISSUE TITLE
My Dockerfile

### ISSUE THREAD

**Issue by srinivle** [QT-DevOps/DevOpsIssues#496]
Dockerfile :::::::::: 

FROM ubuntu:18.04
FROM tomcat:9
LABEL author=Srinivas
RUN apt-get update && apt-get install tree unzip -y
RUN wget https://github.com/QT-DevOps/DevOpsIssues/files/2130588/gameoflife.zip && \
        unzip gameoflife.zip && \
        mv gameoflife.war /usr/local/tomcat/webapps/
EXPOSE 8080
CMD ["catalina.sh", "run"]
~

Kindly check and investigate and suggest and validate if everything is working fine at your end as well.

**Comment by ghost** [comment]
FROM tomcat:9 is enough

**Comment by srinivle** [comment]
https://github.com/BRAHMAREDDYV/springpetclinic.git

**Comment by ghost** [comment]
FROM tomcat:9
LABEL author=Srinivas
RUN apt-get update && apt-get install tree unzip -y
RUN wget https://github.com/QT-DevOps/DevOpsIssues/files/2130588/gameoflife.zip && unzip gameoflife.zip && mv gameoflife.war /usr/local/tomcat/webapps/
EXPOSE 8080
CMD ["catalina.sh", "run"]

**Comment by srinivle** [comment]
cool... thank you very much sir 👍

**Comment by ghost** [comment]
please close issue.

**Comment by srinivle** [comment]
FROM openjdk:13
ADD https://naresh-springpetclinicjarfile.s3-us-west-2.amazonaws.com/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar /usr/local/tomcat/springpetclinic.jar
EXPOSE 8080
CMD ["java" , "-jar" , "/usr/local/tomcat/springpetclinic.jar"]

Kindly check and investigate and suggest and validate if everything is working fine at your end as well.
