### ISSUE TITLE
Unable to execute the Dockerfile using ENV variables

### ISSUE THREAD

**Issue by srinivle** [QT-DevOps/DevOpsIssues#497]
Here is the Dockerfile using ENV variable and the image build is going fine but when I execute/run the container it is failing 

root@ip-192-168-1-81:~/springpetclinic# cat Dockerfile
FROM openjdk:13
ENV LOCATION="/usr/local/tomcat/springpetclinic.jar"
ADD https://naresh-springpetclinicjarfile.s3-us-west-2.amazonaws.com/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar $LOCATION
EXPOSE 8080
CMD ["java","-jar",$LOCATION]
root@ip-192-168-1-81:~/springpetclinic#

root@ip-192-168-1-81:~/springpetclinic# docker container run -d -P spring
35d6d900814ce8e46781e06d3c3473c1a33d8cc7a29c978a326459a5adcf46ab
root@ip-192-168-1-81:~/springpetclinic# docker ps -a
CONTAINER ID        IMAGE               COMMAND                   CREATED             STATUS                     PORTS               NAMES
35d6d900814c        spring              "/bin/sh -c '[ \"java…"   10 seconds ago      Exited (2) 9 seconds ago                       serene_gagarin
root@ip-192-168-1-81:~/springpetclinic# docker logs -t 35d6d900814c
2019-06-08T17:15:35.545613478Z /bin/sh: line 0: [: too many arguments

root@ip-192-168-1-81:~/springpetclinic# docker inspect 35d6d900814c
[
    {
        "Id": "35d6d900814ce8e46781e06d3c3473c1a33d8cc7a29c978a326459a5adcf46ab",
        "Created": "2019-06-08T17:15:35.169471475Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "[ \"java\" , \"-jar\" , $LOCATION ]"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 2,
            "Error": "",
            "StartedAt": "2019-06-08T17:15:35.555774863Z",
            "FinishedAt": "2019-06-08T17:15:35.554678751Z"
        },
        "Image": "sha256:db235e63745c7a3fe5243deb2c458ad6c4a8e2454391b7ed9f94916f122171e7",
        "ResolvConfPath": "/var/lib/docker/containers/35d6d900814ce8e46781e06d3c3473c1a33d8cc7a29c978a326459a5adcf46ab/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/35d6d900814ce8e46781e06d3c3473c1a33d8cc7a29c978a326459a5adcf46ab/hostname",
        "HostsPath": "/var/lib/docker/containers/35d6d900814ce8e46781e06d3c3473c1a33d8cc7a29c978a326459a5adcf46ab/hosts",
        "LogPath": "/var/lib/docker/containers/35d6d900814ce8e46781e06d3c3473c1a33d8cc7a29c978a326459a5adcf46ab/35d6d900814ce8e46781e06d3c3473c1a33d8cc7a29c978a326459a5adcf46ab-json.log",
        "Name": "/serene_gagarin",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": true,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/389fb1e3f917970f5c1b95960281558d5cdadd15b7e51167618c17ee43624d82-init/diff:/var/lib/docker/overlay2/6842d2b2b5baa7acfc6d75a7b0cc9c13b26029c9000df972470a6b61616e9569/diff:/var/lib/docker/overlay2/4876e8dd7d5f6679a6aa76a375a4a464e1ecebc5f10e6f22e680fa9753fa1ace/diff:/var/lib/docker/overlay2/307f19280d591f792e5f349e0f2667968d31006d365ba93204fef39c73e25c73/diff:/var/lib/docker/overlay2/e1280baed9dafa5f154f356aa40912619ee623915fd0bcc14eb2dfac3ec42a21/diff",
                "MergedDir": "/var/lib/docker/overlay2/389fb1e3f917970f5c1b95960281558d5cdadd15b7e51167618c17ee43624d82/merged",
                "UpperDir": "/var/lib/docker/overlay2/389fb1e3f917970f5c1b95960281558d5cdadd15b7e51167618c17ee43624d82/diff",
                "WorkDir": "/var/lib/docker/overlay2/389fb1e3f917970f5c1b95960281558d5cdadd15b7e51167618c17ee43624d82/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "35d6d900814c",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/java/openjdk-13/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "JAVA_HOME=/usr/java/openjdk-13",
                "JAVA_VERSION=13-ea+24",
                "JAVA_URL=https://download.java.net/java/early_access/jdk13/24/GPL/openjdk-13-ea+24_linux-x64_bin.tar.gz",
                "JAVA_SHA256=33ce4214fbc42c9e093f1c9fb90a643e591ced5974bac603a6f8795f43801afd",
                "LOCATION=/usr/local/tomcat/springpetclinic.jar"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "[ \"java\" , \"-jar\" , $LOCATION ]"
            ],
            "ArgsEscaped": true,
            "Image": "spring",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "47ce18616f8c942b71be9278f5dc0d7501c054da9b055ea7026766b91fbf2f9f",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/47ce18616f8c",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "92c058e35aca420c44111ffd03e55926c22ee9f8c6e16c4da4d5db3a734c29f8",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
root@ip-192-168-1-81:~/springpetclinic# 

Kindly check the above information and suggest me in this regard.

**Comment by srinivle** [comment]
It looks like the above commands or outputs got truncated/striked off. Kindly check the below file and inspect and suggest and correct me if anything is wrong in this regard.

[Test.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3269733/Test.txt)

**Comment by bhaskardegala** [comment]
Hey srinivle
Refer this issue you will find your solution if not please let us know
#493

**Comment by srinivle** [comment]
Hi Bhaskar garu , 

Thank you very much sir.... I have checked your post.... Only difference is i m using docker image as openjdk instead of using tomcat and square brackets for CMD ..... when I changed it to tomcat image and removed square brackets ... It worked... fantastic.... thank you very much again.
