### ISSUE TITLE
Jenkins Integration failing

### ISSUE THREAD

**Issue by Aamukta** [QT-DevOps/DevOpsIssues#499]
Hi Team,
I build a job with Build step'Invoke top-level Maven targets'  - clean install package .
But this is failing with error. "Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE."
![Capture](https://user-images.githubusercontent.com/42566531/59264792-843fc980-8c61-11e9-8462-0233c39b4ddf.PNG)

**Comment by bhaskardegala** [comment]
Hey aamukta 
Try even adding git clone in invoke shell before mvn clean 
As the above error stats that it could not find directory as it was not been  cloned

**Comment by Aamukta** [comment]
Hi Bhaskar, still the same.
<img width="715" alt="Capture" src="https://user-images.githubusercontent.com/42566531/59343801-4a86c580-8d2a-11e9-920b-a42e616a1e48.PNG">

**Comment by bhaskardegala** [comment]
Your steps in invoke shell should some thing look like
git clone (git clone url)
mvn clean install

**Comment by sivasankardevops** [comment]
i think the problem is with java. plz check it once whether u installed  properly or not

**Comment by bhaskardegala** [comment]
Please try to do that even manually first

**Comment by RamBoddapati** [comment]
hi @Aamukta ,  here solution for your problem.
according to first screen print, you should change to  directory "hello-world" (which  is under "/opt/bitnami/apps/jenkins/jenkins_home/workspace/ )  before initiating mvn command. Usually git itself create this folder and  keep all code here while git cloning.

according to first screen print, you should change to  directory "game-of-life" (which  is under "/var/lib/jenkins/workspace/ )  before initiating mvn command. Usually git itself create this folder and  keep all code here while git cloning.

**Comment by Aamukta** [comment]
> hi @Aamukta , here solution for your problem.
> according to first screen print, you should change to directory "hello-world" (which is under "/opt/bitnami/apps/jenkins/jenkins_home/workspace/ ) before initiating mvn command. Usually git itself create this folder and keep all code here while git cloning.
> 
> according to first screen print, you should change to directory "game-of-life" (which is under "/var/lib/jenkins/workspace/ ) before initiating mvn command. Usually git itself create this folder and keep all code here while git cloning.

Hi Ram.. I dint understand your reply. The first screen shot shows /opt/binami.. because it is a jenkins deployment I used in GCP.  As it dint work with ready made deployment, I tried to built on a vm from the scratch and it shows different path. However, both the ways gave the error. 
Could you please elaborate your solution please

**Comment by q-uest** [comment]
Looks like either Maven (mvn) is not installed or its path is NOT set (in PATH variable) on your build server ?

-- Ram J

**Comment by RamBoddapati** [comment]
@Aamukta , If you dont mind, you can  call me @9515073203, I can explain you.

**Comment by q-uest** [comment]
Were you able to resolve this? If so, please update with the resolution. 

Thanks
