### ISSUE TITLE
Delivery pipeline using Jenkins and Docker

### ISSUE THREAD

**Issue by sanjaysureshmv** [QT-DevOps/DevOpsIssues#50]
I was trying to create a jenkins delivery pipeline where one job will build gameoflife war file, second job will copy the war file to another jenkins slave where docker is installed and third job will build the docker image and push to docker hub. 3 jobs are parametrized and pass output to downstream job. First and second job was successful however third job is  failing with the following error in the screenshot.

+ docker build -t sanjaymv/gameoflife:1.0 .
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.37/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=8cb81a3f287d4a1faa4a3f90ca0cbeefa37e2dc7d7ec27974f3311b0b3e22c98&shmsize=0&t=sanjaymv%2Fgameoflife%3A1.0&target=&ulimits=null: dial unix /var/run/docker.sock: connect: permission denied
Build step 'Execute shell' marked build as failure
Finished: FAILURE

 I have already added jenkins user to docker group and was able to manually execute the docker commands as jenkins user. Please see the details,

jenkins@ip-172-31-23-111:~/workspace/build-container-gol$ `docker build -t sanjaymv/gameoflife:1.0 .`
Sending build context to Docker daemon   83.7MB
Step 1/5 : FROM tomcat:8.0
 ---> b4b762737ed4
Step 2/5 : LABEL author="sanjaymv" organization="my-org"
 ---> Using cache
 ---> 9ca59ffb9541
Step 3/5 : COPY gameoflife.war /usr/local/tomcat/webapps/gameoflife.war
 ---> bbcce8ec02ab
Step 4/5 : EXPOSE 8080
 ---> Running in fc2cf2c7604f
Removing intermediate container fc2cf2c7604f
 ---> 7a5fa6e67386
Step 5/5 : CMD ["catalina.sh", "run"]
 ---> Running in ad1f6e0e4a84
Removing intermediate container ad1f6e0e4a84
 ---> 86ce877708e1
Successfully built 86ce877708e1
Successfully tagged sanjaymv/gameoflife:1.0
![jenkinsfail_3rdjob](https://user-images.githubusercontent.com/39335150/42180925-a8289f94-7e56-11e8-9cbd-36fa6b77251d.png)

Please help me to solve the issue or suggest me an alternate way to accomplish the task

**Comment by shaikkhajaibrahim** [comment]
did you tried relogin after you added user
________________________________

**Comment by sanjaysureshmv** [comment]
Yes sir. I did try that.

**Comment by shaikkhajaibrahim** [comment]
ok do this test
login into machine with jenkins installed using ssh

su jenkins
and then execute
docker version 

share this output

**Comment by sanjaysureshmv** [comment]
Please see the output,

--
jenkins@ip-172-31-23-111:/home/ubuntu$ docker version
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:16:25 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:14:32 2018
  OS/Arch:      linux/amd64
  Experimental: false
--

**Comment by sanjaysureshmv** [comment]
Issue solved after restarting the docker machine :)
