### ISSUE TITLE
error when apply the validate cmd in terraform

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/DevOpsIssues#502]
![Capture](https://user-images.githubusercontent.com/50665358/59418552-d52cfa80-8de6-11e9-9a6a-862fab3ddb35.PNG)
![error](https://user-images.githubusercontent.com/50665358/59418558-d827eb00-8de6-11e9-80f0-9abd41115e6e.PNG)
why the host is required for it and please send me the argument host.

**Comment by bhaskardegala** [comment]
Without validating try to apply it at once

**Comment by chowdamramana** [comment]
Ok

**Comment by chowdamramana** [comment]
> Without validating try to apply it at once

![err](https://user-images.githubusercontent.com/50665358/59449945-c9145d80-8e25-11e9-96a6-d55e5faba187.PNG)
iam applying the apply but it shows still error

**Comment by ghost** [comment]
please send tf file as text format

**Comment by khatrigopal** [comment]
Hi

Once remove "=" sign where you are using "tag" option
use like as
tags {
        "Name" = "apacheserver"
    }

**Comment by khatrigopal** [comment]
also check spaces before using "{" sign

**Comment by chowdamramana** [comment]
> please send tf file as text format

[apachewebser.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3290778/apachewebser.txt)

**Comment by chowdamramana** [comment]
> Hi
> 
> Once remove "=" sign where you are using "tag" option
> use like as
> tags {
> "Name" = "apacheserver"
> }

![tag 2](https://user-images.githubusercontent.com/50665358/59512309-16e89e80-8ed6-11e9-98a7-d8dab1ae2f55.PNG)
![tag 1](https://user-images.githubusercontent.com/50665358/59512311-16e89e80-8ed6-11e9-8e20-22ef84f2ae2f.PNG)

**Comment by RamBoddapati** [comment]
Hi @chowdamramana, you  should use below argument in connection string.Though it is optional one Terraform is expecting host address to connect to machine.

host = "${aws_instace.apacheserver.private_ip}"

the above one would resolve your issue.

**Comment by chowdamramana** [comment]
> Hi @chowdamramana, you should use the below argument in the connection string. Though it is optional one Terraform is expecting host address to connect to the machine.
> 
> host = "${aws_instace.apacheserver.private_ip}"
> 
> the above one would resolve your issue.

I am
![Capture](https://user-images.githubusercontent.com/50665358/59612057-14867e80-913a-11e9-9e7f-de504c62a177.PNG)
![con file](https://user-images.githubusercontent.com/50665358/59612059-14867e80-913a-11e9-80d3-e156d7779604.PNG)

 used that above argument but it shows an error

**Comment by bhaskardegala** [comment]
Once send your file

**Comment by chowdamramana** [comment]
> Once send your file

[apachewebser.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3300250/apachewebser.txt)

**Comment by RamBoddapati** [comment]
Hi @chowdamramana ,  there was a spelling mistake in my previous content. 

host = "${aws_instace.apacheserver.private_ip}"  => spelling mistake @aws_instace

host = "${aws_instance.apacheserver.private_ip}"  => use this. here corrected spelling mistake.

**Comment by chowdamramana** [comment]
> Hi @chowdamramana , there was a spelling mistake in my previous content.
> 
> host = "${aws_instace.apacheserver.private_ip}" => spelling mistake @aws_instace
> 
> host = "${aws_instance.apacheserver.private_ip}" => use this. here corrected spelling mistake.

when I
![df](https://user-images.githubusercontent.com/50665358/59671824-fa04e180-91db-11e9-8bb3-259893864465.PNG)
![new](https://user-images.githubusercontent.com/50665358/59671825-fb360e80-91db-11e9-9461-8907a9510d52.PNG)

 using this command the error came in apply cmd execution

**Comment by bhaskardegala** [comment]
> > Hi @chowdamramana , there was a spelling mistake in my previous content.
> > host = "${aws_instace.apacheserver.private_ip}" => spelling mistake @aws_instace
> > host = "${aws_instance.apacheserver.private_ip}" => use this. here corrected spelling mistake.
> 
> when I
> ![df](https://user-images.githubusercontent.com/50665358/59671824-fa04e180-91db-11e9-8bb3-259893864465.PNG)
> ![new](https://user-images.githubusercontent.com/50665358/59671825-fb360e80-91db-11e9-9461-8907a9510d52.PNG)
> 
> using this command the error came in apply cmd execution

You need to connect using public ip but not private ip

**Comment by RamBoddapati** [comment]
Hi @chowdamramana , If it is not yet resolved, you can call me @9515073203. I can explain you. it looks ports also not opened in your example.

**Comment by chowdamramana** [comment]
![error1](https://user-images.githubusercontent.com/50665358/59964776-db2b8580-9522-11e9-81d3-f60b074cee6f.PNG)
![Capture](https://user-images.githubusercontent.com/50665358/59964777-dc5cb280-9522-11e9-939f-50a00ec6954f.PNG)

**Comment by RamBoddapati** [comment]
Hi @chowdamramana ,
Here is a solution for this issue. 
Referenced from : https://stackoverflow.com/questions/31569910/terraform-throws-groupname-cannot-be-used-with-the-parameter-subnet-or-vpc-se/34586893#34586893

1. we should have subnet created
2. Then We should associate subnet with VPC creation
3. Then we should have Security group created by  associating the VPC id from  step#2.

I will be trying it tomorrow and let you  know.
