### ISSUE TITLE
Hi May I am getting while installing node in node machine. Could you please suggest on this.

### ISSUE THREAD

**Issue by hanocc** [QT-DevOps/DevOpsIssues#504]
![Capture122](https://user-images.githubusercontent.com/51271895/59778996-189ad380-92d5-11e9-997d-202afd284c03.PNG)

**Comment by bhaskardegala** [comment]
I think this node was already added to master ,go to master and check for nodes 
Kubectl get node

**Comment by ghost** [comment]
yes node was added already
reset command on your node and execute then join command again. This will reset your cluster environment and then when you try joining the node again to the cluster, it will create all the files again.
kubeadm​ reset
