### ISSUE TITLE
AWS Systems Manager Run Command Shell script is forloop script not working 

### ISSUE THREAD

**Issue by AudiNayana** [QT-DevOps/DevOpsIssues#509]
HI Team,

I am trying to execute forsloop script in Run command in Aws system manager i got error 
Can you let me know this option only we can execute only command or for loop and while loop scripts also 
Please find attached screen shot or error messge 
![shell script](https://user-images.githubusercontent.com/39982781/60159593-30141800-9811-11e9-95c1-703fac5e464c.JPG)

**Comment by ghost** [comment]
please share script
