### ISSUE TITLE
<URGENT> Team, need help !!! can any one name some list of the applications (something like SpringPetClinic) ??? 

### ISSUE THREAD

**Issue by srinivle** [QT-DevOps/DevOpsIssues#510]
Team, need help !!! can any one name some list of the applications (something like SpringPetClinic) ??? 

Please provide me some list of 5 applications like that such that I can do some deployments using those ..... 

Kindly consider my request and provide me soon... !

**Comment by sandhyadev** [comment]
gameoflife, openmrs, biojava, springpetclinic, shopizer

**Comment by srinivle** [comment]
> gameoflife, openmrs, biojava, springpetclinic, shopizer

Sir, you are awesome... Perfect.... Jowharrrr !!! ..... 

Apart from the above mentioned, do you know/still remember any more???
