### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by sainath2929** [QT-DevOps/DevOpsIssues#511]
i got an 403 forbidden error while get a file from s3 bucket how can i resolve it.
root@d8af99b7e35e:/usr/local/tomcat# wget https://dockerlearn.s3.amazonaws.com/gameoflife.war
--2019-06-27 10:53:56--  https://dockerlearn.s3.amazonaws.com/gameoflife.war
Resolving dockerlearn.s3.amazonaws.com (dockerlearn.s3.amazonaws.com)... 52.216.65.40
Connecting to dockerlearn.s3.amazonaws.com (dockerlearn.s3.amazonaws.com)|52.216.65.40|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-06-27 10:53:56 ERROR 403: Forbidden.

**Comment by sandhyadev** [comment]
it looks like s3 bucket permission issue, make that s3 bucket as public
