### ISSUE TITLE
jenkins build issue

### ISSUE THREAD

**Issue by Sriraj143** [QT-DevOps/DevOpsIssues#513]
Hi guys,

   When I am building entire project using jenkins,build was successful but when I am trying to compile single .java using jenkins build was failure and getting below error but all souce files was placed in workspace of jenkins

+ javac Addition.java
javac: file not found: Addition.java
Usage: javac <options> <source files>
use -help for a list of possible options
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by bhaskardegala** [comment]
Try to add required files to your git hub and and then clone it while you are building instead of adding those files to the workspace manually , after performing this try to update the status of this issue

**Comment by Sriraj143** [comment]
Thanks for your reply,it's been resolved

**Comment by bhaskardegala** [comment]
Please update the issue with resolution and close the issue

**Comment by Sriraj143** [comment]
Hi,

   Do we have calls on devops now
