### ISSUE TITLE
SSH KEY gen in AWS

### ISSUE THREAD

**Issue by AudiNayana** [QT-DevOps/DevOpsIssues#514]
HI Team,
Any body know how to configure SSH key gen and ssh copy in both ec2 machines

**Comment by sandhyadev** [comment]
Create users in both the ec2 machines and follow this step:
1.enable password-based authentication: vi /etc/ssh/sshd_config
(PasswordAuthentication yes)
2.restart ssh : systemctl restart sshd
3.give sudo permission for user: visudo
(username ALL=(ALL:ALL) NOPASSWD: ALL)
4 generate  key inthe 1st ec2 : ssh-keygen
5.copy key into 2nd ec2 : ssh-copy-id username@ip address of other ec2 machine .
Repeat step 1 ,2,3 in 2nd ec2 machine also.

**Comment by AudiNayana** [comment]
HI,
I follow all the steps and after 
while i am try to execute ssh-copy-id username@ip i got below error 
/bin/ssh-copy-id: ERROR: failed to open ID file '/root/.pub': No such file or directory
        (to install the contents of '/root/.pub' anyway, look at the -f option)

I am not able to short it out this problem

**Comment by ghost** [comment]
please login into user and do

**Comment by bhaskardegala** [comment]
Log in to the user in which you have created ssh key and then your issue will be resolved

**Comment by satyamuralidhar** [comment]
###https://github.com/immurali5/Terraform.git


ssh-keygen
ssh-copy-id username@ipaddress
vim /etc/ssh/sshd_config
enable password less authentication
service sshd restart
