### ISSUE TITLE
Git pull - after pull below we will get fast-forward

### ISSUE THREAD

**Issue by ghost** [QT-DevOps/DevOpsIssues#516]
what is fast-forward in git pull
![image10](https://user-images.githubusercontent.com/49831402/60611036-f6c84300-9de2-11e9-96bd-f5f722e7a4f0.png)

**Comment by bhaskardegala** [comment]
It was merging master to new branch , generally in normal merge branch will get merged with master but in fast forward merge master will be looking towards branch you can find this difference in git graph
