### ISSUE TITLE
K8s woker Nodes hang issue

### ISSUE THREAD

**Issue by gnrqt** [QT-DevOps/DevOpsIssues#517]
Hello Team,
Facing an issue while joining the node into the master and Node is hang state please help me below is the error 
root@Node:~# kubeadm join x.x.x.x:6443 --token gxzenm.sr0zuvcrnz79tjw1     --discovery-token-ca-cert-hash sha256:18f90251788a1e156299cb7196a1e439188028109d610b64a0e855ffee55dc98
[preflight] Running pre-flight checks

**Comment by bhaskardegala** [comment]
Is your token still active you can check that by kubeadm token list
