### ISSUE TITLE
How to build multiple .c files to create a Docker image?

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#519]
Hi,

I have been asked to solve the following as part of a job interview selection process:-

.........................................................................................................................................................................
Build a Docker container that uses ttyd ( https://github.com/tsl0922/ttyd ) to expose NetHack via a web interface. While NetHack is available via a variety of system packages, we would like you to compile NetHack 3.6.2 from source, which you can find at
https://www.nethack.org/v362/download-src.html 
The container should preconfigure our preferred game options:
OPTIONS=windowtype:curses,splash_screen,color,guicolor

You should optimize to reduce container size.
Expected outputs:
● A Dockerfile to build the container
................................................................................................................................................................................

The first challenge here is that the source folder, which is zipped twice using tar and gzip has 108 .c files. 
The download ink of the compressed file is:-
https://www.nethack.org/download/3.6.2/nethack-362-src.tgz
How can one build all this into a single binary? 

If someone could help with how multiple c files can be compiled, it would be very useful.

I feel that a Jenkins job may have to be created to first download the file, then un tar it and later un zip it, in order to get the .c files.

How to expose this via a web interface so that the game can be played on a web browser needs to be further understood.

Thanks

**Comment by bhaskardegala** [comment]
make all and make install will help you to compile all your files and i will try to see into this scenario and update you once i am done

**Comment by bhaskardegala** [comment]
u need to change config.h file under include folder according to above preferred options
OPTIONS=windowtype:curses,splash_screen,color,guicolor

**Comment by bhaskardegala** [comment]
[click here](http://mo.morsi.org/blog/2017/04/09/compiling_playing_nethack_360_on_fedora/) this link will help you how to manually install nethack if you succeed this then steps are simple
you will write a docker file where you take Ubuntu as base image and first you install ttyd using RUN instruction and then compile nethack as you followed manually using RUN and expose it some port generally 80 if you are done with all of this then you need to optimize your file i.e size of your image should be reduced and you can do it by docker multi-stage build

**Comment by rameshm78** [comment]
Thanks Bhaskar.
The link asks to Edit [src/Makefile] and update some lines. There is no file called Makefile in the src directory.
I then installed "make" and tried make all, but it failed as follows:-

$ sudo make all
( cd src ; make )
make[1]: Entering directory '/home/ubuntu/tiny/nethack-3.6.2/src'
cc -O -I../include -c monst.c
make[1]: cc: Command not found
Makefile:636: recipe for target 'monst.o' failed
make[1]: *** [monst.o] Error 127
make[1]: Leaving directory '/home/ubuntu/tiny/nethack-3.6.2/src'
Makefile:140: recipe for target 'nethack' failed
make: *** [nethack] Error 2
ubuntu@ip-172-31-20-18:~/tiny/nethack-3.6.2$

Let me know if something is wrong in the way I did

**Comment by bhaskardegala** [comment]
You can find Makefile in src folder and I think everything was set in makefile nothing to modify and try to take care of other things but some how compilation failed for me yesterday I will try to look into that today

**Comment by rameshm78** [comment]
Hi Bhaskar,
I think it's because of missing dependencies. I managed to install it and also play the game. However, unable to build the dockerfile.
Manual steps for installation are as follows:-
sudo su -
apt-get update 
apt-get install -y gcc libncurses5-dev make bison flex
wget "https://www.nethack.org/download/3.6.2/nethack-362-src.tgz"
tar xzvf nethack-362-src.tgz 
cd nethack-3.6.2/sys/unix
./setup.sh hints/linux
cd ../../
make
make install
cd
ls
echo 'OPTIONS=windowtype:curses,splash_screen,color,guicolor' >> /root/nh/install/games/lib/nethackdir/sysconf 

To run the game, use the following command:-
nh/install/games/nethack

Since this needs to be run using ttyd, I made the Dockerfile as follows, but it fails saying unable to cd nethack-3.6.2/sys/unix
......................................................................................................
FROM ubuntu

RUN \
  apt-get update && apt-get -y install gcc libncurses5-dev make bison flex cmake g++ pkg-config git vim-common \
  libwebsockets-dev libjson-c-dev libssl-dev wget && \
  git clone https://github.com/tsl0922/ttyd.git && \
  cd ttyd && mkdir build && cd build && \
  cmake .. && \
  make && make install && \
  wget "https://www.nethack.org/download/3.6.2/nethack-362-src.tgz" && \
  tar xzvf nethack-362-src.tgz && rm nethack-362-src.tgz && \
  cd sys/unix && ./setup.sh hints/linux && cd ../../ && make && make install && \
  rm -rf nethack-3.6.2 && \
  echo 'OPTIONS=windowtype:curses,splash_screen,color,guicolor' >> /root/nh/install/games/lib/nethackdir/sysconf  

EXPOSE 80
CMD ["ttyd", "-p", "80", "nh/install/games/nethack"]
....................................................................................................

Somehow I'm not getting the absolute path correct

**Comment by bhaskardegala** [comment]
even in CMD try to give absolute path or use WORKDIR instruction this might definitely help and please send log file of your image build

**Comment by bhaskardegala** [comment]
if possible i  can update with docker file by tomorrow evening

**Comment by rameshm78** [comment]
The complete logs are too huge to copy paste, but this is where it is failing now:-

Cannot find hints file nethack-3.6.2/sys/unix/hints/linux
The command '/bin/sh -c apt-get update && apt-get -y install gcc libncurses5-dev make bison flex cmake g++ pkg-config git vim-common   libwebsockets-dev libjson-c-dev libssl-dev wget &&   git clone https://github.com/tsl0922/ttyd.git &&   cd ttyd && mkdir build && cd build &&   cmake .. &&   make && make install &&   wget "https://www.nethack.org/download/3.6.2/nethack-362-src.tgz" &&   tar xzvf nethack-362-src.tgz && rm nethack-362-src.tgz &&   cd nethack-3.6.2/sys/unix && ./setup.sh nethack-3.6.2/sys/unix/hints/linux && cd ../../ && make && make install &&   rm -rf nethack-3.6.2 &&   echo 'OPTIONS=windowtype:curses,splash_screen,color,guicolor' >> /root/nh/install/games/lib/nethackdir/sysconf' returned a non-zero code: 1
ubuntu@ip-172-31-26-73:~/challenge$

Not sure what to give as WORKDIR, since there are two installations in this - ttyd followed by Nethack.

My Dockerfile is as follows now after adding absolute paths everywhere. CMD already had absolute path:-
.....................................................................................................................................
FROM ubuntu

RUN \
  apt-get update && apt-get -y install gcc libncurses5-dev make bison flex cmake g++ pkg-config git vim-common \
  libwebsockets-dev libjson-c-dev libssl-dev wget && \
  git clone https://github.com/tsl0922/ttyd.git && \
  cd ttyd && mkdir build && cd build && \
  cmake .. && \
  make && make install && \
  wget "https://www.nethack.org/download/3.6.2/nethack-362-src.tgz" && \
  tar xzvf nethack-362-src.tgz && rm nethack-362-src.tgz && \
  cd nethack-3.6.2/sys/unix && ./setup.sh nethack-3.6.2/sys/unix/hints/linux && cd ../../ && make && make install && \
  rm -rf nethack-3.6.2 && \
  echo 'OPTIONS=windowtype:curses,splash_screen,color,guicolor' >> /root/nh/install/games/lib/nethackdir/sysconf  

EXPOSE 80
CMD ["ttyd", "-p", "80", "/nh/install/games/nethack"]
........................................................................................................................................

I'm currently in Australia so I'm 4.5 hrs ahead of you. Already night here.
Really appreciate your help.

**Comment by rameshm78** [comment]
Some person has written a Dockerfile for the Nethack game and it actually works. But I have no idea what the SED command is doing and can't explain to interviewer when they ask. I tried integrating it with ttyd instructions but that is giving error at build time. 

This is the Github link of the Dokerfile I found on the net:
https://github.com/matsuu/docker-nethack

The Dockerfile is:
.....................................................................................................
FROM alpine

ARG NH_VER=3.6.1

RUN \
  apk --no-cache add byacc curl flex gcc groff linux-headers make musl-dev ncurses-dev util-linux && \
  curl -sL https://nethack.org/download/${NH_VER}/nethack-${NH_VER//.}-src.tgz | tar zxf - && \
  ( \
    cd nethack-${NH_VER} && \
    sed -i -e 's/cp -n/cp/g' -e '/^PREFIX/s:=.*:=/usr:' sys/unix/hints/linux && \
    sh sys/unix/setup.sh sys/unix/hints/linux && \
    make all && \
    make install \
  ) && \
  rm -rf nethack-${NH_VER}

# for backup
VOLUME /usr/games/lib/nethackdir

ENTRYPOINT ["/usr/games/nethack"]
................................................................................................

However, Alpine image doesn't support apt-get update and apt-get install

**Comment by rameshm78** [comment]
The Docker image for ttyd is available at:
https://hub.docker.com/r/tsl0922/ttyd/

I copied installations steps from here for my Dockerfile.

**Comment by rameshm78** [comment]
The question I put is just part 1 of the entire challenge.
The remaining parts are as follows:

Part 2 - Deploy to Kubernetes using KubeSail
KubeSail is a free Kubernetes hosting platform for small projects. Sign up with your GitHub
account, and create a deployment which runs your Docker container on KubeSail.
You will need to host your built container image somewhere in order to do this. We recommend a
public repository on Docker Hub, Quay.io or BinTray. Please name the repository for this container
image “ tdoc-<your initials>-nethack ”.
Expected outputs:
● A Kubernetes YAML file to deploy your service
● The URL of your built image repository

Part 3 - Expose the service with authentication
We don’t want everybody able to access our game server. Put HTTP Basic authentication in place
to protect the service, with the following valid credentials (which you should ensure stay secret).
Username: ephox
Password: N0wI5Tiny
Username: tiny
Password: i5gr0w1ng
Both sets of credentials must be usable for the same game server. If you get stuck, we will accept
a submission that only handles one set of credentials, provided you explicitly state this as part of
the submission. Submissions that handle both will be graded higher.
Expose the service on KubeSail via HTTPS.
Expected outputs:
● A URL where we can play some NetHack with your container
● Any additional Dockerfiles or Kubernetes config required

**Comment by rameshm78** [comment]
I actually got the game to work in a container. Now need to get it working on ttyd so that it can be played on a browser. Not sure if this has to be hosted on an apache server.
Here's the Dockerfile:
..........................................................................................................................................
FROM ubuntu

RUN \
  apt-get update && apt-get -y install gcc libncurses5-dev make bison flex cmake g++ pkg-config git vim-common \
  libwebsockets-dev libjson-c-dev libssl-dev wget && \
  git clone https://github.com/tsl0922/ttyd.git && \
  cd ttyd && mkdir build && cd build && \
  cmake .. && \
  make && make install && \
  cd &&\
  wget "https://www.nethack.org/download/3.6.2/nethack-362-src.tgz" && \
  tar xzvf nethack-362-src.tgz && rm nethack-362-src.tgz && \
  cd /root/nethack-3.6.2/sys/unix && ./setup.sh hints/linux && cd ../../ && make && make install && \
  rm -rf /root/nethack-3.6.2 && \
  echo 'OPTIONS=windowtype:curses,splash_screen,color,guicolor' >> /root/nh/install/games/lib/nethackdir/sysconf  

EXPOSE 80
CMD ["./root/nh/install/games/nethack"]
.........................................................................................................................................................................

**Comment by rameshm78** [comment]
I actually got the game to work in a container. Now need to get it working on ttyd so that it can be played on a browser. Not sure if this has to be hosted on an apache server.
Here's the Dockerfile:
..........................................................................................................................................
FROM ubuntu

RUN \
  apt-get update && apt-get -y install gcc libncurses5-dev make bison flex cmake g++ pkg-config git vim-common \
  libwebsockets-dev libjson-c-dev libssl-dev wget && \
  git clone https://github.com/tsl0922/ttyd.git && \
  cd ttyd && mkdir build && cd build && \
  cmake .. && \
  make && make install && \
  cd &&\
  wget "https://www.nethack.org/download/3.6.2/nethack-362-src.tgz" && \
  tar xzvf nethack-362-src.tgz && rm nethack-362-src.tgz && \
  cd /root/nethack-3.6.2/sys/unix && ./setup.sh hints/linux && cd ../../ && make && make install && \
  rm -rf /root/nethack-3.6.2 && \
  echo 'OPTIONS=windowtype:curses,splash_screen,color,guicolor' >> /root/nh/install/games/lib/nethackdir/sysconf  

EXPOSE 80
CMD ["./root/nh/install/games/nethack"]
.........................................................................................................................................................................

**Comment by rameshm78** [comment]
Hi Bhasker,

I managed to run the container and play the game on browser.  Can you help me in reducing the size? Khaja sir didn't teach multi stage builds, so I'm not sure how that is done.

Biggest challenge is the Linux commands. One needs to be very thorough in Linux to be able to write decent dockerfiles.
Part 2 remains to be solved using Kube Sail account.
Here is the Dockerfile:
................................................................................................................................................................................
FROM tsl0922/ttyd

RUN \
  apt-get update && apt-get install -y wget cmake libncurses5-dev flex bison && cd &&\
  wget "https://www.nethack.org/download/3.6.2/nethack-362-src.tgz" && \
  tar xzvf nethack-362-src.tgz && rm nethack-362-src.tgz && \
  cd /root/nethack-3.6.2/sys/unix && ./setup.sh hints/linux && cd ../../ && make && make install && \
  rm -rf /root/nethack-3.6.2 && \
  echo 'OPTIONS=windowtype:curses,splash_screen,color,guicolor' >> /root/nh/install/games/lib/nethackdir/sysconf && \
  echo "/usr/local/bin/ttyd -c ramesh:123 -p 80 '/root/nh/install/games/nethack'" > /root/start.sh

EXPOSE 80
ENTRYPOINT ["/bin/bash"]
CMD ["/root/start.sh"]
.......................................................................................................................................................................
this has to be built and then run using:
docker run -d -p 80:80 <imageName:tag>

Then open public ip of the vm on a browser and enter the username ramesh and password 123
Apart from reducing size, also need to find a way to hide the login credentials, maybe by using ARG

**Comment by Karthick-Gopalakrishnan** [comment]
Ramesh,

Your image is based on ubuntu ?! , why dont you try using alpine it will bring down the size of image.

**Comment by rameshm78** [comment]
Hi Karthick,

My Image is not based on Ubuntu. I had tried alpine but it was not even supporting apt-get update. Anyway, it is mandatory to use ttyd . So instead of Ubuntu, I based it on the ttyd image. Else I'll have to use base image and then install ttyd.

Regards
Ramesh

**Comment by bhaskardegala** [comment]
Sorry Ramesh I was bit busy from few days and I could not update docker file I will definitely try to create and share it with you mean while you can optimise your dockerfile by adding one more FROM instruction and you can definitely find some reference template in Google and for your second part create a deployment file and tricky task is to create 2 set of credentials and I will definitely try to look in to that and let you know
With regards
Bhaskar

**Comment by rameshm78** [comment]
Hi Bhaskar,

I tried making Kubernetes service and deployment yamls for KubeSail, but the deployment script kept showing errors. Could you please take a look? 

All scripts are at: 
https://github.com/rameshm78/fortiny
Image is uploaded on github at:
https://cloud.docker.com/u/rameshm78/repository/docker/rameshm78/tdoc-rm-nethack

Regards
Ramesh

**Comment by bhaskardegala** [comment]
just saw your files you need to even add secret.yml file for credentials and in tiny-svc.yml file generally the node port values lies between 31000 - 32767 as per my knowledge and try to change that and i did not try out scripts and will set up my environment and check that at once

**Comment by rameshm78** [comment]
Could you please share what this secret.yml looks like? This topic was not covered by Khaja sir when I attended his k8s session last year.

**Comment by bhaskardegala** [comment]
You can refer this [link](https://kubernetes.io/docs/concepts/configuration/secret/)

**Comment by rameshm78** [comment]
My response was rejected by the company. They gave the complete solution and at least 75% of the concepts was not covered in the QT course.
