### ISSUE TITLE
Volumes in Kubernetes

### ISSUE THREAD

**Issue by SrinivReddy** [QT-DevOps/DevOpsIssues#52]
Hello, 
My requirement is provide volume mount point to a container  in K8 cluster

my doubt is if we mention auto volume mount point in docker file while building image how it will work in k8s cluster as container will create in any node we cant assure that container will create always in one particular node...

and how can we preserve  container's important data/directories at one place ?
please give me solution...

**Comment by shaikkhajaibrahim** [comment]
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

Use this link

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
