### ISSUE TITLE
Docker build error for Mongodb --  /bin/sh: 1: sudo: not found

### ISSUE THREAD

**Issue by karthik4u619** [QT-DevOps/DevOpsIssues#520]
wrote a docker file for mongodb, but while building it is throwing a error. executed same steps manually and able to connect. 
**DOCKER FILE**
FROM ubuntu:bionic
LABEL Author="Karthik Kalva" 
RUN sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4 
RUN echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" \
| sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list 
RUN sudo apt-get update 
RUN sudo apt-get install -y mongodb-org
RUN sudo service mongod start
RUN sudo service mongod restart
EXPOSE 27017
CMD ["mongod"]
![error](https://user-images.githubusercontent.com/46345969/60864863-6191d800-a242-11e9-9f6b-1990c7c8c5f8.png)

**DOCKER ERROR**

ubuntu@ip-192-168-0-118:~/images/mongo$ vi dockerfile                                                                                                                                                              ubuntu@ip-192-168-0-118:~/images/mongo$ docker image build -t mongo .                                                                                                                                              Sending build context to Docker daemon  2.048kB                                                                                                                                                                    Step 1/10 : FROM ubuntu:bionic                                                                                                                                                                                      ---> 4c108a37151f                                                                                                                                                                                                 Step 2/10 : LABEL Author="Karthik Kalva"                                                                                                                                                                            ---> Using cache                                                                                                                                                                                                   ---> 8a1add72718a                                                                                                                                                                                                 Step 3/10 : RUN sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4                                                                                          ---> Running in 54df062e4952                                                                                                                                                                                      /bin/sh: 1: sudo: not found                                                                                                                                                                                        
The command '/bin/sh -c sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4' returned a non-zero code: 127                                                  ubuntu@ip-192-168-0-118:~/images/mongo$
--
![error](https://user-images.githubusercontent.com/46345969/60864725-0829a900-a242-11e9-9037-6c010af94623.png)

**Comment by bhaskardegala** [comment]
Hey karthik 
Don't use sudo in your RUN instruction and you issue gets resolved

**Comment by karthik4u619** [comment]
hi bhaskar, that solved the sudo issue but. am not able to install mongodb as root user using docker image of ubuntu or centos  as base and getting inside to execute to write in docker file. which got executed manually as ubuntu user from aws machine.
``**URL OF Installation followed** ``
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
  ``**NEW ERROR**``

E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation

![gnup](https://user-images.githubusercontent.com/46345969/60920907-eae2f200-a2b6-11e9-802b-7a930bad30f2.png)

**Comment by bhaskardegala** [comment]
Can you please update your dockerfile with logs here so that it can help us

**Comment by karthik4u619** [comment]
``**DOCKERFILE**``
FROM ubuntu:bionic
LABEL Author="Karthik Kalva" 
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4 
RUN echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" \
| tee /etc/apt/sources.list.d/mongodb-org-4.0.list 
RUN apt-get update 
RUN apt-get install -y mongodb-org
RUN service mongod start
RUN service mongod restart
EXPOSE 27017
CMD ["mongod"]

``**Error screenshot**``

![gnup](https://user-images.githubusercontent.com/46345969/60942899-eabc1400-a301-11e9-80c8-d47971089211.png)

**Comment by srmanikanta** [comment]
install packages such as gnung or gnup1 or gnupg2 for docker instruction in docker fille
