### ISSUE TITLE
AWS EKS Networking Issue

### ISSUE THREAD

**Issue by saikiran243** [QT-DevOps/DevOpsIssues#521]
Hi I have a managed EKS cluster (AWS-EKS) running in a VPC which have a restricted count on the IP. now it have around 150 IP's 
my pods will be increased to 1000 in future.
as Amazon EKS supports native VPC networking via the Amazon VPC CNI plugin for Kubernetes. which allows Kubernetes pods to have the same IP address inside the pod as they do on the VPC network. 
i will be running out of IP's soon. can any one help me on this note for an enterprised grade K8s
does EKS have any Docker kind of networking which gets the ip with 172.17.0.1/16 kind of range which doesnt exhaust. 
i dont want to go with Kops solution but anything on awseks is much appreciated.

Thanks
regards
saikiran (past student)

**Comment by bhaskardegala** [comment]
Hey saikiran
I think This vpc restrictions are over nodes and but not pods for pods we use service

**Comment by saikiran243** [comment]
Thanks Bhasker, i raised a request with AWS team They said that amazon vpc cni has an overlay network which takes IPs from the vpc and assign to the pods it cant be changed in any manner when used EKS service hence we are changing the VPC range. adding extra subnets to the cluster,

closing the issue
