### ISSUE TITLE
``CRASHLOOPBACKOFF`` kubernetes pod error

### ISSUE THREAD

**Issue by karthik4u619** [QT-DevOps/DevOpsIssues#522]
``**Yaml file**``
apiVersion: v1
kind: Pod
metadata:
  name: application-server
  labels:
    env: test
    server: tomcat
spec:
  containers:
  - name: gameoflife
    image: karthik4u619/karthik4u619:gameoflife
    ports:
      - containerPort: 8080

``**DOCKERFILE**`` working in container as docker file not in pod as yaml.
FROM tomcat:8.0
LABEL Author="Karthik Kalva"
ADD https://auditbucket1.s3-us-west-2.amazonaws.com/gameoflife/gameoflife.war /usr/local/tomcat/webapps
EXPOSE 8080
CMD [ "catalina.sh","run" ]

``**--ERROR MSG --**``
![crashloopbaackoff](https://user-images.githubusercontent.com/46345969/60946550-1fcd6400-a30c-11e9-82ac-668084cf2512.png)

**Comment by bhaskardegala** [comment]
It might be due to network setup issue in your machine try to run this file in aks or eks or try to reinstall kubeadm again , your file seems to look good and the issue might be in setup
