### ISSUE TITLE
Template creation using Terraform

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [QT-DevOps/DevOpsIssues#523]
Hi EveryOne..
Can some one please let me know how to create a template using terraform script..?
Is it same like writing terraform script for aws instance creation ? 
Is writing terraform script for aws instance is called a terraform template ?
I am confused, please clarify..

Thanks
SajidKhan

**Comment by bhaskardegala** [comment]
I think this [link](https://www.terraform.io/docs/providers/template/d/file.html) might help you

**Comment by SajidAliKhanMohammed** [comment]
yes, i have already gone through that link, but could not get idea..
thanks for your help Bhaskar..

**Comment by bhaskardegala** [comment]
Ok then I can update you with proper information by tomorrow

**Comment by bhaskardegala** [comment]
we generally write scripts for infra-provisioning in terraform and in those scripts we write templates and generally we use templates in terraform to in one resource for using attributes of other resources for this we use interpolation i.e ${...} , if we want to use some conditional statements like for then we can use     %{for ...}
%{end ...}

**Comment by SajidAliKhanMohammed** [comment]
ok thanks for the information Bhaskar...
