### ISSUE TITLE
hi,im getting error when java_home variable stting in jenkins

### ISSUE THREAD

**Issue by azeemqtdevops** [QT-DevOps/DevOpsIssues#525]
i cannot found java path, 
also it do not set in environment ...there im getting error
i'll give u screen shots ,plz tell me how to fix it

![path](https://user-images.githubusercontent.com/49971074/61178522-1f82e080-a60c-11e9-8020-267a75855f31.png)
![path1](https://user-images.githubusercontent.com/49971074/61178523-1f82e080-a60c-11e9-83ee-8fbb38f4d630.png)
![path2](https://user-images.githubusercontent.com/49971074/61178524-1f82e080-a60c-11e9-88e4-193b5e18c0df.png)
![path3](https://user-images.githubusercontent.com/49971074/61178525-201b7700-a60c-11e9-89c4-18dfcc5c5ace.png)

thank u.

**Comment by ghost** [comment]
please save file with Esc  : wq

**Comment by ghost** [comment]
azeem please close  issue
