### ISSUE TITLE
SSH key permission denied

### ISSUE THREAD

**Issue by praveenkumar9154** [QT-DevOps/DevOpsIssues#527]
Hi Naresh/All
 while am copying ssh key from my Ansible server to Node its showing below error 
i given sudo permission to user and edited sshd_config file also

plese do give me solution

sudo ssh-copy-id ansible@172.31.30.102
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/ansible/.ssh/id_rsa.pub"
The authenticity of host '172.31.30.102 (172.31.30.102)' can't be established.
ECDSA key fingerprint is SHA256:f/lfn/C3WBmX/N4uKdfl+yhhhO/+pUeIz3jVf9v+Vu8.
Are you sure you want to continue connecting (yes/no)? yes
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are alread
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install
ansible@172.31.30.102: Permission denied (publickey).
ansible@ip-172-31-31-103:~$ ssh 172.31.30.102
ansible@172.31.30.102: Permission denied (publickey).

**Comment by sandhyadev** [comment]
This issue seems to ssh service restart.
follow this step:
sudo -i
vi /etc/ssh/sshd_config--> in this passwordauthentication shoud be 'yes'
service ssh restart
and remaining step are same

**Comment by praveenkumar9154** [comment]
thanq u Sandhya

**Comment by harikumar430** [comment]
> Hi Naresh/All
> while am copying ssh key from my Ansible server to Node its showing below error
> i given sudo permission to user and edited sshd_config file also
> 
> plese do give me solution
> 
> sudo ssh-copy-id ansible@172.31.30.102
> /usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/ansible/.ssh/id_rsa.pub"
> The authenticity of host '172.31.30.102 (172.31.30.102)' can't be established.
> ECDSA key fingerprint is SHA256:f/lfn/C3WBmX/N4uKdfl+yhhhO/+pUeIz3jVf9v+Vu8.
> Are you sure you want to continue connecting (yes/no)? yes
> /usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are alread
> /usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install
> ansible@172.31.30.102: Permission denied (publickey).
> ansible@ip-172-31-31-103:~$ ssh 172.31.30.102
> ansible@172.31.30.102: Permission denied (publickey).

Hello praveen, im also getting same like this. did you resolve this ?

**Comment by praveenkumar9154** [comment]
Yes I resolved.....

**Comment by harikumar430** [comment]
i did same thing without error but iam getting this problem repeatedly.

can u please tell me what u did after that problem occured?

**Comment by hitesh7269** [comment]
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/ansible/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
ansible@172.31.6.183: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
i have this error 
i gave the password authentication also
can you give me the solution
