### ISSUE TITLE
"msg": "Cannot write to ControlPath /home/ansible/.ansi

### ISSUE THREAD

**Issue by Nara-Sagar** [QT-DevOps/DevOpsIssues#528]
![image](https://user-images.githubusercontent.com/48256252/61284165-0fb9f680-a7dc-11e9-929d-c41c18ec71de.png)

please tell how to fix this error!!

**Comment by ghost** [comment]
create user __adduser username__
enable passwordbaseauth  __/etc/ssh/sshd_config__
make as sudo user __visudo__
restart ssh   __systemctl restart sshd__
login to user __su username__
generate keys __ssh-keygen__
copy keys into node __ssh-copy-id username@nodeip__
install python in node __apt-get install python -y__ if node is __ubuntu__  and  __yum install python -y__ if node is __RedHat/Centos__

**Comment by ghost** [comment]
if you done close this issue with solutions
