### ISSUE TITLE
SSH Permission issue with copy id to node

### ISSUE THREAD

**Issue by amit49409** [QT-DevOps/DevOpsIssues#529]
Hello, I am getting permission issue with the copy id from the ACS to node server.

getting below ERROR

ssh-copy-id ansible@10.1.0.21
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/ansible/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
ansible@10.1.0.21: Permission denied (publickey).
![Screenshot 2019-07-16 23 14 14](https://user-images.githubusercontent.com/22767281/61316896-7f050a00-a81f-11e9-94ef-36aff243e0e2.png)

**Comment by sandhyadev** [comment]
Follow the steps clearly:
Become root user "sudo -i"
enable passwordbaseauth in "/etc/ssh/sshd_config" file
restart ssh "service sshd restart"
create user "adduser username"
make as sudo user "visudo"
login to user "su username"
install ansible in added user
generate keys "ssh-keygen"
copy keys into node "ssh-copy-id username@nodeip"
install python in node apt-get install python -y if node is ubuntu and yum install python -y if node is RedHat/Centos

**Comment by amit49409** [comment]
Thanks, Issue Resolved
