### ISSUE TITLE
Jenkins: SonarQube configuration error

### ISSUE THREAD

**Issue by SaiSrikanth10** [QT-DevOps/DevOpsIssues#53]
I've installed Jenkins from Vagrant Ubuntu 14.04. I've also practiced different type of projects in Jenkins and it worked well. Now I've installed Sonarqube in my windows machine and tried to configured that one in Jenkins. While building a project the following error coming.

![image](https://user-images.githubusercontent.com/39853597/42552660-09916c52-84fb-11e8-8edc-bcd0c619aab1.png)

Please help in resolving this. Thank you

**Comment by shaikkhajaibrahim** [comment]
Please add your sonarqube configuration steps

**Comment by SaiSrikanth10** [comment]
Sir,

I've downloaded sonarqube7.2 and started StartSonar.bat. I'm also able to access that from http://192.168.33.1:9000. In my Jenkins, Manage Jenkins -> Configure system and added sonarqube configuration as below.

![image](https://user-images.githubusercontent.com/39853597/42554668-52f00fa4-8503-11e8-9f80-016a43117b86.png)

In the pipeline project, I've written a pipeline script, which I've taken from our github.

**Comment by shaikkhajaibrahim** [comment]
Ping from jenkins to windows machine and share results

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SaiSrikanth10** [comment]
![image](https://user-images.githubusercontent.com/39853597/42555087-bc24542a-8504-11e8-9e26-af92631348c0.png)

I've tried to configure my windows private IP, public IP, and also localhost:9000. But It is not happening.

**Comment by shaikkhajaibrahim** [comment]
Jenkins job configuration screen shot please

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SaiSrikanth10** [comment]
![image](https://user-images.githubusercontent.com/39853597/42555321-79720c2a-8505-11e8-9b7e-0df68f2ee45d.png)


![image](https://user-images.githubusercontent.com/39853597/42555362-a439f404-8505-11e8-8267-ff9d9716c1c0.png)

**Comment by shaikkhajaibrahim** [comment]
Try Sonar rather than sonar

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SaiSrikanth10** [comment]
Please see this.
![image](https://user-images.githubusercontent.com/39853597/42555703-ca08ccea-8506-11e8-81f9-455feef26260.png)



![image](https://user-images.githubusercontent.com/39853597/42555654-a24a0278-8506-11e8-8803-a987a0b25ef7.png)

**Comment by shaikkhajaibrahim** [comment]
Try this pipeline 

withSonarQubeEnv('**Sonar**')  {
 sh 'mvn clean package sonar:sonar
}

**Comment by SaiSrikanth10** [comment]
Sir,

The build got successful. Thank you.

May I know the reason why it has failed earlier times. ?

**Comment by shaikkhajaibrahim** [comment]
Sonarqube environment created was Sonar. You are trying access with name sonar. But environment check is case sensitive.
Please close the issue

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
