### ISSUE TITLE
vagrant centos not running because of ssh permission issue 

### ISSUE THREAD

**Issue by amit49409** [QT-DevOps/DevOpsIssues#530]
Hello All,

I am using windows 7 (64bit), and i have installed vagrant into the my system.

execute the following command for the creating virtual machine of centos 7

- vagrant init centos/7
- vagrant up
{here machine start installing the centos file}
- ssh vagrant
{here shows the error}
ssh: Could not resolve hostname vagrant: Name or service not known

![Screenshot 2019-07-16 23 21 53](https://user-images.githubusercontent.com/22767281/61317948-96dd8d80-a821-11e9-9a2a-8fcb2403c7b8.png)
[vagrant issue.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3398457/vagrant.issue.txt)

**Comment by sandhyadev** [comment]
Use "vagrant ssh"

**Comment by amit49409** [comment]
Thanks, issue Resolved
