### ISSUE TITLE
Devops Connecting between 2 instances

### ISSUE THREAD

**Issue by eswar0424** [QT-DevOps/DevOpsIssues#532]
I created 2 ubuntu instances in AWS in same security group with all tcp allow but when i am connecting one machine to another machine with private ip 
**public key perimission denied** is coming..

please resolve ASAP.. so that i can practice Ansible.

Regards,
QT-eswar

**Comment by shaikkhajaibrahim** [comment]
vi /etc/ssh/sshd_config
 
passwordauthentication => yes

**Comment by shaikkhajaibrahim** [comment]
Restart sshd

**Comment by eswar0424** [comment]
it is already yes but still i cant ssh or cant do ssh-copy-id

**Comment by eswar0424** [comment]
thanks it got resolved.....
