### ISSUE TITLE
ansible issue

### ISSUE THREAD

**Issue by sainath2929** [QT-DevOps/DevOpsIssues#533]
ansible@ip-172-31-91-175:~/playbooks$ ansible-playbook lamp_beginer.yml
ERROR! Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/home/ansible/playbooks/lamp_beginer.yml': line 6, column 10, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

   - name: update ubuntu packages and install apache2
      apt:
         ^ here

**Comment by sainath2929** [comment]
code:
---
- hosts: all
  become: yes
  tasks: 
   - name: update ubuntu packages and install apache2
      apt: 
        name: apache2
        update_cache: yes
        state: present
   - name: restart apche2
      service: 
        name: apache2
        state: restarted

**Comment by sandhyadev** [comment]
Please share your file zip format

**Comment by Karthick-Gopalakrishnan** [comment]
[ansible.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3415767/ansible.txt)
try this

**Comment by sainath2929** [comment]
It's yaml file

**Comment by sainath2929** [comment]
I use same code bro. I pasted my code in comment

**Comment by nagireddy-9** [comment]
i think your facing space issues...
fallow bellow script...
![gitinstall](https://user-images.githubusercontent.com/50133860/61613477-0ec31200-ac7f-11e9-9567-e9fd6422f8be.PNG)

**Comment by sainath2929** [comment]
Yeah it's space issue. Thankyou nagireddy bro

**Comment by ghost** [comment]
close issue if you done
