### ISSUE TITLE
Elastic stac installing issue

### ISSUE THREAD

**Issue by AudiNayana** [QT-DevOps/DevOpsIssues#534]
Hi,
I am trying to install Elastic search on Aws instance,
When i try to tracert ip 9200 i got connection refused error
I open all traffic in inbound rules 

Please give me any suggestions

**Comment by ghost** [comment]
please read logs /var/log/elasticSearch
else
share logs

**Comment by dharmatejadevops** [comment]
Did you enable port 9200 and check the log file.

**Comment by ghost** [comment]
have you done some configuration in /etc/elasticsearch/elasticsearch.yml
do change as a fallow document of elastic search 
what is the version you tried? better to try less than 7.0
