### ISSUE TITLE
i got an error in ansible when install httpd

### ISSUE THREAD

**Issue by sainath2929** [QT-DevOps/DevOpsIssues#535]
ansible@ip-172-31-91-175:~/playbooks$ ansible-playbook  lamp-novice2.yml

PLAY [all] *************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************
ok: [172.31.80.162]

TASK [install httpd] ***************************************************************************************************************************************************************************
 [WARNING]: Could not find aptitude. Using apt-get instead

fatal: [172.31.80.162]: FAILED! => {"cache_update_time": 1563867190, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'httpd'' failed: E: Package 'httpd' has no installation candidate\n", "rc": 100, "stderr": "E: Package 'httpd' has no installation candidate\n", "stderr_lines": ["E: Package 'httpd' has no installation candidate"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nPackage httpd is a virtual package provided by:\n  nginx-light 1.14.0-0ubuntu1.3\n  nginx-full 1.14.0-0ubuntu1.3\n  nginx-extras 1.14.0-0ubuntu1.3\n  lighttpd 1.4.45-1ubuntu3.18.04\n  nginx-core 1.14.0-0ubuntu1.3\n  apache2 2.4.29-1ubuntu4.8\n  yaws 2.0.4+dfsg-2\n  webfs 1.21+ds1-12\n  tntnet 2.2.1-3build1\n  mini-httpd 1.23-1.2build1\n  micro-httpd 20051212-15.1\n  ebhttpd 1:1.0.dfsg.1-4.3build1\n  aolserver4-daemon 4.5.1-18.1\n  aolserver4-core 4.5.1-18.1\n\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Package httpd is a virtual package provided by:", "  nginx-light 1.14.0-0ubuntu1.3", "  nginx-full 1.14.0-0ubuntu1.3", "  nginx-extras 1.14.0-0ubuntu1.3", "  lighttpd 1.4.45-1ubuntu3.18.04", "  nginx-core 1.14.0-0ubuntu1.3", "  apache2 2.4.29-1ubuntu4.8", "  yaws 2.0.4+dfsg-2", "  webfs 1.21+ds1-12", "  tntnet 2.2.1-3build1", "  mini-httpd 1.23-1.2build1", "  micro-httpd 20051212-15.1", "  ebhttpd 1:1.0.dfsg.1-4.3build1", "  aolserver4-daemon 4.5.1-18.1", "  aolserver4-core 4.5.1-18.1", ""]}

PLAY RECAP *************************************************************************************************************************************************************************************
172.31.80.162              : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by dharmatejadevops** [comment]
Send me your play book and send details of your Noed.
If your node os family is debian package  httpd is not work , if it is ubuntu  replace httpd to apache2 
and if os family is REHL apt is not working.

**Comment by sainath2929** [comment]
it is centos and the code i had written.
---
- hosts: all
  become: yes
  tasks:
    - name: install apache server
      package: 
        name: httpd
        state: present
      notify: 
      - restart apache   
    - name: install php
      package:
        name: "{{ item }}"
        state: present
      loop:
      - php
      - php-mysql 
      notify:
      - restart apache
  handlers: 
  - name: restart apache
    service:
       name: httpd
       state: restarted

**Comment by VENKATAREDDYVENNA** [comment]
Try the below one once.

---
- hosts: all
  become: yes
  tasks:
  - name: install apache server
    package:
      name: httpd
      state: present
    notify:
      - restart apache
  - name: install php
    package:
      name: "{{ item }}"
      state: present
    loop:
      - php
      - php-mysql
    notify:
     - restart apache
  handlers:
    - name: restart apache
      service:
      name: httpd
      state: restarted

**Comment by VENKATAREDDYVENNA** [comment]
@sainath2929  

I can't see the exact syntax what you wrote in the .yml file because it is changing the format when you paste the content directly. Can you please  upload the .txt file format once

**Comment by sainath2929** [comment]
[ansible.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3425499/ansible.txt)

**Comment by dharmatejadevops** [comment]
hi sainath, did you add any node as REHL family then that script works. otherwise change the package name as apache2 instead of httpd

**Comment by sainath2929** [comment]
apache2 working in ubuntu.but i want to run it on centos mechine

**Comment by dharmatejadevops** [comment]
> apache2 working in ubuntu.but i want to run it on centos mechine

do you have centos node configure with ansible control server 

Sainath just now i check the playbook and play 's on server with centos node its working fine.

**Comment by sainath2929** [comment]
but it does not show centos page in browser when we enter public ip in address bar
