### ISSUE TITLE
Doubt in Interview question

### ISSUE THREAD

**Issue by venki090790** [QT-DevOps/DevOpsIssues#536]
Hi Sir,

I have attended couple of interviews where they have asked below question.

1.  How do you protect your environment? Can you please let us know how  security will be provided to servers in companies.

2. How can you build the project in specific environment(Dev, QA,prod)
   i have told we use parameterised jobs ..could you please clarify on this sir.
 Lets consider i have entered Dev,qa,prod ..while build i have selected Dev..How does the jenkins match the key word of Dev and deploy to that particular server only?  This question is haunting me sir.

**Comment by vkatukam** [comment]
Hi,

1. Protecting servers in the environment is done by different methods like firewall, they will not open all ports to the external world and they will use only private IPs to all servers.

2. When you select the environment for parameterized jobs that value will be passed as an argument to the shell script, with that value it will pull the latest code from a respective branch from git hub and will be deployed into the respective server(all these processes will be written in a shell script)

**Comment by RamBoddapati** [comment]
@venki090790 ,
2. In jenkins,  the value which you are passing from parameters should be used/called in build step as below
Windows Node : "-variable  var_name=%var_from_parameter%
Linux node: "-variable var_name=$var_from_parameter
