### ISSUE TITLE
unable to unarchive in ansible

### ISSUE THREAD

**Issue by akashsan** [QT-DevOps/DevOpsIssues#537]
Receiving error as: fatal: [172.31.47.0]: FAILED! => {"changed": false, "msg": "Could not find or access 'apache-tomcat-*.tar.gz'\nSearched in:\n\t/home/ansible/files/apache-tomcat-*.tar.gz\n\t/home/ansible/apache-tomcat-*.tar.gz\n\t/home/ansible/files/apache-tomcat-*.tar.gz\n\t/home/ansible/apache-tomcat-*.tar.gz on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

Playbook Snippet: 

- name: Extract tomcat to /opt/tomcat/
    unarchive:
      src: apache-tomcat-*.tar.gz
      dest: /opt/tomcat/

![image](https://user-images.githubusercontent.com/50402277/61793083-dfa5cf80-ae3b-11e9-97bf-d7d3907d8d7d.png)

**Comment by akashsan** [comment]
I was able to make work but is not an optimal solution
1. Added the whole filename ie "apache-tomcat-8.5.38.tar.gz" would liked to user wild card like "apache-tomcat-*.tar.gz" - Can someone guide me to use like these wild cards
2. Added remote_src to yes

unarchive:
      src: /opt/tomcat/apache-tomcat-8.5.38.tar.gz
      dest: /opt/tomcat/
      remote_src: yes

**Comment by dharmatejadevops** [comment]
> I was able to make work but is not an optimal solution
> 
> 1. Added the whole filename ie "apache-tomcat-8.5.38.tar.gz" would liked to user wild card like "apache-tomcat-*.tar.gz" - Can someone guide me to use like these wild cards
> 2. Added remote_src to yes
> 
> unarchive:
> src: /opt/tomcat/apache-tomcat-8.5.38.tar.gz
> dest: /opt/tomcat/
> remote_src: yes

Check once source path you given correctly or not. or in the source path the *.gz file exist or not

**Comment by bhaskardegala** [comment]
please update this issue was this resolved

**Comment by akashsan** [comment]
@bhaskardegala : as stated above how use wild cards like  "apache-tomcat-*.tar.gz" in ansible

**Comment by RamBoddapati** [comment]
@akashsan ,  you are using wildcards in right way , but you missed to  provide path where the files exists. This you have corrected in your second post.

**Comment by RamBoddapati** [comment]
Just remind among us. Please close the issues if it  reached solution
