### ISSUE TITLE
Unable to install java in centos using ansible

### ISSUE THREAD

**Issue by akashsan** [QT-DevOps/DevOpsIssues#538]
Manually tried the following command executed successfully: "yum install -y java-1.8.0 wget"
Where as when entered in ansible playbook as following it gives error as
"fatal: [172.31.47.0]: FAILED! => {"changed": false, "msg": "No package matching 'java=\"1.8.0\"' found available, installed or updated", "rc": 126, "results": ["No package matching 'java=\"1.8.0\"' found available, installed or updated"]}
"

Playbook Snippet:

vars:
    tomcat_url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.38/bin/apache-tomcat-8.5.38.tar.gz
    java_version: 1.8.0 
  tasks:
  - name: install java 1.8.0
    yum:
      name: java="{{java_version}}"
      state: present

![image](https://user-images.githubusercontent.com/50402277/61793457-cf422480-ae3c-11e9-98bf-fab48e6cd113.png)

**Comment by sandhyadev** [comment]
tasks:
 - name: install java 1.8.0
   yum:
      name: java-"{{java_version}}"
      state: present

try java-"{{ java_version}}"

**Comment by bhaskardegala** [comment]
please close this issue if this was been resolved
