### ISSUE TITLE
unable to execute the below yml 

### ISSUE THREAD

**Issue by ravindra619** [QT-DevOps/DevOpsIssues#539]
while i am installing the apache and php packages  i am getting the  below error
and by executing also i am getting error screenshot is attached
![1](https://user-images.githubusercontent.com/53264236/61795785-d15ab200-ae41-11e9-812d-8b82a1bb9cb2.PNG)

**Comment by sandhyadev** [comment]
Replace the "{{items}}" with "{{ item }}" in php packages section

**Comment by bhaskardegala** [comment]
i think your issue was been resolved then close the issue if not update this issue

**Comment by ravindra619** [comment]
still i am unable to execute after changing the items to item please find the attachment
![2](https://user-images.githubusercontent.com/53264236/61858435-ae80da00-aee3-11e9-986d-07c34151f924.PNG)

**Comment by bhaskardegala** [comment]
What is the version of ansible that you are using if it is older version
try using with_items rather than loop

**Comment by ravindra619** [comment]
hi bhaskar,
i am using ansible 2.0 version

**Comment by bhaskardegala** [comment]
Loop will not help you if you are using 2.0 so use with_items

**Comment by ravindra619** [comment]
i am new to this,how can i use with_items
can you please send the commands and where to replace it.

**Comment by RamBoddapati** [comment]
@ravindra619 , this url could help you. "Loop" is been introduced Ansible 2.5 version onwards.

**Comment by RamBoddapati** [comment]
Sorry, here is url.

https://docs.ansible.com/ansible/2.4/playbooks_loops.html
