### ISSUE TITLE
Unable to start Tomcat using ansible on Centos7

### ISSUE THREAD

**Issue by akashsan** [QT-DevOps/DevOpsIssues#540]
Firstly I successfully installed tomcat8 on centos7 manually.
But using ansible I am getting below error
![image](https://user-images.githubusercontent.com/50402277/61800427-9e68ec00-ae4a-11e9-9856-21a62d9918be.png)

Playbook Snippet:
 - name: Start tomcat
    systemd:
      name: tomcat
      enabled: yes
      state: restarted 

My Complete playbook
![image](https://user-images.githubusercontent.com/50402277/61801553-9dd15500-ae4c-11e9-9209-b2235824976f.png)

**Comment by akashsan** [comment]
error details:


TASK [Start tomcat] **************************************************************************************************************************************************************************** fatal: [172.31.47.0]: FAILED! => {"changed": false, "msg": "Unable to start service tomcat: Job for tomcat.service failed because the control process exited with error code. See \"systemctl st atus tomcat.service\" and \"journalctl -xe\" for details.\n"}
--

**Comment by dharmatejadevops** [comment]
> error details:
> 
> ## TASK [Start tomcat] **************************************************************************************************************************************************************************** fatal: [172.31.47.0]: FAILED! => {"changed": false, "msg": "Unable to start service tomcat: Job for tomcat.service failed because the control process exited with error code. See "systemctl st atus tomcat.service" and "journalctl -xe" for details.\n"}

send your playbook

**Comment by akashsan** [comment]
[tomcatcentos.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3428400/tomcatcentos.txt)

**Comment by dharmatejadevops** [comment]
hi akashasan , add java home on /etc/default/tomcat8 then its work
refer this[ link ](https://gist.github.com/alexislucena/89a046dc747123faf4496fb946c1fe79)

**Comment by akashsan** [comment]
Hi dharmatejadevops,

For Centos tomcat, the java home is already set in tomcat.service file.
That did not help either.
[tomcat.service.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3429623/tomcat.service.txt)

The tricky part is I  have already installed this manually

**Comment by bhaskardegala** [comment]
akashsan please share full logs by using ansible-playbook -vvv it gives you full logs 
and even try to adding JAVA_HOME path to environment as it seems to be missing in file

**Comment by akashsan** [comment]
The java path is already added on tomcat.service file (attached above: File name: tomcat.service.txt) and it did not work.

Additionally Now I added set java home path on playbook itself but still it did not work.
 - name: Set JAVA_HOME
    lineinfile:
      dest: /etc/environment
      state: present
      regexp: '^JAVA_HOME'
      line: 'JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre'    


Error Details 3rd level verbose: 
TASK [Reload daemon & restart the tomcat server] ***************************************************************************************************************************
task path: /home/ansible/tomcatcentos.yml:30
<172.31.47.0> ESTABLISH SSH CONNECTION FOR USER: None
<172.31.47.0> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/dd458d38e6 172.31.47.0 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<172.31.47.0> (0, '/home/ansible\n', '')
<172.31.47.0> ESTABLISH SSH CONNECTION FOR USER: None
<172.31.47.0> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/dd458d38e6 172.31.47.0 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-tmp-1564034954.5-116788293873061 `" && echo ansible-tmp-1564034954.5-116788293873061="` echo /home/ansible/.ansible/tmp/ansible-tmp-1564034954.5-116788293873061 `" ) && sleep 0'"'"''
<172.31.47.0> (0, 'ansible-tmp-1564034954.5-116788293873061=/home/ansible/.ansible/tmp/ansible-tmp-1564034954.5-116788293873061\n', '')
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/systemd.py
<172.31.47.0> PUT /home/ansible/.ansible/tmp/ansible-local-1325ObmZPC/tmpgWBFTE TO /home/ansible/.ansible/tmp/ansible-tmp-1564034954.5-116788293873061/AnsiballZ_systemd.py
<172.31.47.0> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/dd458d38e6 '[172.31.47.0]'
<172.31.47.0> (0, 'sftp> put /home/ansible/.ansible/tmp/ansible-local-1325ObmZPC/tmpgWBFTE /home/ansible/.ansible/tmp/ansible-tmp-1564034954.5-116788293873061/AnsiballZ_systemd.py\n', '')
<172.31.47.0> ESTABLISH SSH CONNECTION FOR USER: None
<172.31.47.0> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/dd458d38e6 172.31.47.0 '/bin/sh -c '"'"'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1564034954.5-116788293873061/ /home/ansible/.ansible/tmp/ansible-tmp-1564034954.5-116788293873061/AnsiballZ_systemd.py && sleep 0'"'"''
<172.31.47.0> (0, '', '')
<172.31.47.0> ESTABLISH SSH CONNECTION FOR USER: None
<172.31.47.0> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/dd458d38e6 -tt 172.31.47.0 '/bin/sh -c '"'"'sudo -H -S -n  -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-mitcqndcrttpvckcxnoiotvrkvsjmbry ; /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1564034954.5-116788293873061/AnsiballZ_systemd.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<172.31.47.0> (1, '\r\n{"msg": "Unable to start service tomcat: Job for tomcat.service failed because the control process exited with error code. See \\"systemctl status tomcat.service\\" and \\"journalctl -xe\\" for details.\\n", "failed": true, "invocation": {"module_args": {"no_block": false, "force": null, "name": "tomcat", "daemon_reexec": false, "enabled": null, "daemon_reload": true, "state": "restarted", "user": null, "scope": null, "masked": null}}}\r\n', 'Shared connection to 172.31.47.0 closed.\r\n')
<172.31.47.0> Failed to connect to the host via ssh: Shared connection to 172.31.47.0 closed.
<172.31.47.0> ESTABLISH SSH CONNECTION FOR USER: None
<172.31.47.0> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/dd458d38e6 172.31.47.0 '/bin/sh -c '"'"'rm -f -r /home/ansible/.ansible/tmp/ansible-tmp-1564034954.5-116788293873061/ > /dev/null 2>&1 && sleep 0'"'"''
<172.31.47.0> (0, '', '')
fatal: [172.31.47.0]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "daemon_reexec": false,
            "daemon_reload": true,
            "enabled": null,
            "force": null,
            "masked": null,
            "name": "tomcat",
            "no_block": false,
            "scope": null,
            "state": "restarted",
            "user": null
        }
    },
    "msg": "Unable to start service tomcat: Job for tomcat.service failed because the control process exited with error code. See \"systemctl status tomcat.service\" and \"journalctl -xe\" for details.\n"
}

PLAY RECAP *****************************************************************************************************************************************************************
172.31.47.0                : ok=6    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

![image](https://user-images.githubusercontent.com/50402277/61850161-314c6980-aed1-11e9-8bc4-427c945aef7e.png)

**Comment by akashsan** [comment]
journalctl -xe (ACS server)

![image](https://user-images.githubusercontent.com/50402277/61851207-f26be300-aed3-11e9-89e9-ecf2fd8f13a5.png)

Centos Node:
![image](https://user-images.githubusercontent.com/50402277/61851287-247d4500-aed4-11e9-9a7e-87231de73684.png)

**Comment by bhaskardegala** [comment]
this [link](https://askubuntu.com/questions/802597/unable-to-start-apache-tomcat-8-5-4-on-ubuntu-16-04) will help you

**Comment by akashsan** [comment]
The following steps I followed to install and configure tomcat 8 on centos 7 manually and the below steps work manually
1. yum install -y java-1.8.0 wget
2. wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.38/bin/apache-tomcat-8.5.38.tar.gz
3. tar -zxvf apache-tomcat-*.tar.gz
4. mv apache-tomcat-*/* /opt/tomcat/
5. Create a tomcat systemd service file - vi /etc/systemd/system/tomcat.service 
6. systemctl daemon-reload
7. systemctl start tomcat
8. systemctl status tomcat
9. systemctl enable tomcat

Question is why it is not working with ansible, @bhaskardegala : I have followed every step mentioned in the link except -chmod tomcat step as I do not have specific tomcat user and I am using ansible as my user.

**Comment by RamBoddapati** [comment]
Hi @akashsan ,
if my  guess is correct, you  should provide right  permissions to tomcat.service as your are copying from template. You can use "mode" parameter from template module to change the permissions of "tomcat.service" file after its get copied/created.

**Comment by akashsan** [comment]
@shaikkhajaibrahim Sir please help me

**Comment by akashsan** [comment]
> Hi @akashsan ,
> if my guess is correct, you should provide right permissions to tomcat.service as your are copying from template. You can use "mode" parameter from template module to change the permissions of "tomcat.service" file after its get copied/created.

Added mode: '0777' still same error

**Comment by ramjagadeeshkumar** [comment]
Try this out set selinux

**Comment by shaikkhajaibrahim** [comment]
resize your t2.micro to bigger size and increase heap
