### ISSUE TITLE
ansible -m ping localhost is not working from ansible server

### ISSUE THREAD

**Issue by tandrarajesh** [QT-DevOps/DevOpsIssues#541]
127.0.0.1 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '127.0.0.1' (ECDSA) to the list of known hosts.\r\nansible@127.0.0.1: Permission denied (publickey,password).",
    "unreachable": true
}

I have added the IP 127.0.0.1 in /etc/ansible/hosts  file.

**Comment by akashsan** [comment]
In host file just add "localhost" (without quotes).

Also have you copied ssh-key, if not then execute the following command on Ansible configuration machine:

ssh-copy-id localhost

**Comment by dharmatejadevops** [comment]
> In host file just add "localhost" (without quotes).
> 
> Also have you copied ssh-key, if not then execute the following command on Ansible configuration machine:
> 
> ssh-copy-id localhost

ssh-copy-id <'username'>@localhost

**Comment by bhaskardegala** [comment]
hey rajesh 
are you able to connect to node manually i.e from command line 
---
ssh username@ip_address (change values accordingly)

---
please update this issue after doing this 
don't forget to change and restart sshd before doing this

**Comment by tandrarajesh** [comment]
> ## hey rajesh
> are you able to connect to node manually i.e from command line
> ssh username@ip_address (change values accordingly)
> 
> please update this issue after doing this
> don't forget to change and restart sshd before doing this

**Comment by tandrarajesh** [comment]
![Ansible -m ping all worked](https://user-images.githubusercontent.com/39631097/61864799-b9416c00-aeef-11e9-80b2-823fa78d1612.PNG)


it worked for me. Thanks and closing the issue.
