### ISSUE TITLE
i got error in browser when i enter public ip it does not show any page

### ISSUE THREAD

**Issue by sainath2929** [QT-DevOps/DevOpsIssues#542]

**Comment by sainath2929** [comment]
actually i am using two machines in ansible. one is ubuntu and anothes is centos when i run playbook all process done correctly but when i enter ip address in address bar there is no response to centos public ip and the palybook code is:
---
- hosts: all
  become: yes
  tasks:
    - name: display os information to the user
      debug:
         msg: os family is {{ ansible_os_family}}  
    - name: update ubuntu packages
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: install apache server
      package: 
        name: "{{ webserver_package }}"
        state: present
      notify: 
      - restart apache   
    - debug:
        msg: ubuntu updated using packages {{webserver_package}}
    - name: install php packages
      package:
        name: "{{ item }}"
        state: present
      loop:
      - php
      - php-mysql 
      notify:
      - restart apache
    - name: copy info.php page
      get_url: 
          url: https://ansibleexp.s3.amazonaws.com/info.php
          dest: /var/www/html/info.php
      notify:
      - reatart apache
  handlers: 
    - name: restart apache
      service:
       name: "{{ webserver_package }}"
       state: restarted

**Comment by RamBoddapati** [comment]
Hi @sainath2929 , 
Open port 8080 (http) in your nodes.

**Comment by bhaskardegala** [comment]
Well said ram
Yes Sainath you need to open inbound port for your CentOS node in aws

**Comment by saee241** [comment]
you are running on centos machine and you are using apt instead of yum
