### ISSUE TITLE
what is the solution for this error

### ISSUE THREAD

**Issue by sainath2929** [QT-DevOps/DevOpsIssues#543]
ansible@ip-172-31-91-175:~$ ansible-playbook -i -vv ~/inventries/webservehosts ~/playbooks/lamp-towards-better.yml
 [WARNING]: Unable to parse /home/ansible/-vv as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

ERROR! A playbook must be a list of plays, got a <class 'ansible.parsing.yaml.objects.AnsibleUnicode'> instead

The error appears to be in '/home/ansible/inventries/webservehosts': line 1, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

172.31.95.18 webserver_package=httpd
^ here

**Comment by RamBoddapati** [comment]
Hi @sainath2929 , you  must use inventory file path immediate to "-i" option.  Please remove "-vv" option "-i" and keep "-vv" as lat parameter.  This will  solve your problem.

**Comment by bhaskardegala** [comment]
Hi Sainath 
You can reframe your command as follows
ansible-playbook -i <path_of_your_inventory> -vv <path_of_your_playbook> 
In your case you are trying to place -vv ie verbosity beside path so it was trying to search for -vv file so please change your command accordingly

**Comment by ghost** [comment]
ram has tried that what sends Bhaskar 
if done close the issue with the solution
