### ISSUE TITLE
Hi Team, I am unable to login into Centos machine. Pls find the error screen shot.

### ISSUE THREAD

**Issue by hanocc** [QT-DevOps/DevOpsIssues#544]
![Centoserror](https://user-images.githubusercontent.com/51271895/61987939-adad8c80-b038-11e9-8260-751352bf1876.PNG)

**Comment by hanocc** [comment]
Hi, could you any one please respond if you know this issue..

**Comment by tandrarajesh** [comment]
Please make sure your pem file is in same downloads location.

**Comment by hanocc** [comment]
thanks rajesh.
