### ISSUE TITLE
how can i get docker image from docker volume

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/DevOpsIssues#545]
I want to create a docker image from docker volume, so please give me a process

**Comment by bhaskardegala** [comment]
Chowdamramana I think you can create docker volume from docker image and it can be done by both instruction and command line

**Comment by chowdamramana** [comment]
I know how to create docker volume from image , I want to know how to
create image from volume

**Comment by bhaskardegala** [comment]
You can create docker image from container by exporting container

**Comment by ghost** [comment]
volume is for storage 
I don't think it possible
