### ISSUE TITLE
Unable to connect AWS EC2 instance ( Customer ODC )

### ISSUE THREAD

**Issue by vinodh2020** [QT-DevOps/DevOpsIssues#546]
Hello Team,
               I am facing some issue to connect from EC2 instance from Git on windows 7 . I am assuming that , no file wall blocked to connect from restricted network as EC2 is enabled for all TCP/IP protocols .

Issue :
occurring in restricted network ( Ex : Customer ODC )
Same i am able to connect in my home network.

Please help me with solution if can do any thing .

Thanks,
Vinodh

**Comment by tandrarajesh** [comment]
Hi vinodh,
Yes you are right. Because from your own laptop you are having local admin access but from the office system you are a user with no admin access. 
This might be reason.

**Comment by vinodh2020** [comment]
Hello Rajesh,
                 Thanks for quick response. can you please help me if any other alternative to work from office laptop .
is Admin access require to connect EC2 instances ?

Thanks,
Vinodh

**Comment by tandrarajesh** [comment]
Try connecting with other than office network.

**Comment by vinodh2020** [comment]
Other than office N/W its working fine. But i would like to know how to connect from ODC network and what all things should be done If  have .

Thanks in Advance .

Thanks,
Vinodh

**Comment by shaikkhajaibrahim** [comment]
it depends on your network proxy settings configured.
________________________________
