### ISSUE TITLE
tell me solution for this error

### ISSUE THREAD

**Issue by sainath2929** [QT-DevOps/DevOpsIssues#547]
ERROR:
ansible@ip-172-31-91-175:~/playbooks$ ansible-playbook -i ~/inventries/webservehosts ~/playbooks/tomcat8.yml

PLAY [all] *************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************
ok: [172.31.80.162]

TASK [update ubuntu and install tomcat] ********************************************************************************************************************************************************
 [WARNING]: Could not find aptitude. Using apt-get instead

ok: [172.31.80.162]

TASK [copy tomcat8 file] ***********************************************************************************************************************************************************************
fatal: [172.31.80.162]: FAILED! => {"changed": false, "msg": "Could not find or access '/templates/tomcat8.j2' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

PLAY RECAP *************************************************************************************************************************************************************************************
172.31.80.162              : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

CODE:
---
 - hosts: all
   become: yes
   vars:
    xmx_size: 512m
    max_perm_size: 256m
    tomcat_additional_packages:
      - tomcat7-docs 
      - tomcat7-admin
      - tomcat7-examples
    tomcat_username: admin
    tomcat_password: password
   tasks:
     - name: update ubuntu and install tomcat
       apt:
         name: tomcat8
         update_cache: yes
         state: present
     - name: copy tomcat8 file
       template:
           src: /templates/tomcat8.j2
           dest: /etc/default/tomcat8
       notify:
        - restart tomcat8
     - name: install tomcat additional packages
       apt:
         name: "{{ item }}"
         state: present
       loop: "{{ tomcat_additional_packages }}"
     - name: copy tomcat users file
       template:
           src: templates/tomcat-users.xml.j2
           dest: /etc/tomcat8/tomcat-users.xml
       notify:
        - restart tomcat8  
   handlers:
    - name: restart tomcat8
      service:
        name: tomcat8
        state: restarted

**Comment by shaikkhajaibrahim** [comment]
problem with template source you have give from root
________________________________

**Comment by sainath2929** [comment]
sorry sir.i did't get that. tell me in detailed way.
and i found one error. i am unable to get templates folder from my pc

**Comment by ghost** [comment]
please send as text file

**Comment by ghost** [comment]
don't give  like this templates/tomcat-users.xml.j2
give entire path
