### ISSUE TITLE
Modify the lengthy code to run docker containers using docker multiple images

### ISSUE THREAD

**Issue by AnoopPogaru** [QT-DevOps/DevOpsIssues#548]
Sir,

I had installed Ansible on master, slave on python. Written some ansible playbook so that it should take multiple docker images, run docker containers using the same the image. 

---
- hosts: all
  become: yes
  tasks:
    - name: Install pip
      apt: name=python-pip state=present

    - name: install docker-py
      pip: name=docker-py

    - name: Build Docker image from Dockerfile
      docker_image:
        name: tomcat
        path: docker
        state: present
      docker_image:
        name: nginx
        path: docker
        state: present
      docker_image:
        name: tomcat
        path: postgres
        state: present

    - name: Running the container
      docker_container:
        name: tomcat
        image: tomcat
        ports: 7500:8080
        state: started
       docker_container:
        name: nginx
        image: nginx
        ports: 7501:8080
        state: started
        docker_container:
        name: pos

Thatgres
        image: postgres
        ports: 7502:5432
        state: started

Output is fine
All images and containers are running but code is too long.
ansible@ip-172-31-82-17:/tmp$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
807ab5fa3d4d        postgres            "docker-entrypoint.s…"   37 seconds ago      Up 36 seconds       0.0.0.0:7502->5432/tcp    postgres
061fcb3bdee6        postgres            "docker-entrypoint.s…"   5 hours ago         Up 5 hours          0.0.0.0:32769->5432/tcp   magical_hamilton
84e6b624d11b        nginx               "nginx -g 'daemon of…"   5 hours ago         Up 5 hours          0.0.0.0:7000->80/tcp      nginx
cea85930aede        tomcat              "catalina.sh run"        5 hours ago         Up 5 hours          0.0.0.0:32768->8080/tcp   xenodochial_grothendieck
8188708415dc        tomcat              "catalina.sh run"        5 hours ago         Up 5 hours          0.0.0.0:7500->8080/tcp    tomcat
ansible@ip-172-31-82-17:/tmp$

Please modify the code with ansible modules like items or lists, images_lists: 

Need to submit some bright idea in my offc on this. 
Please help me.

Thanks
Anup

**Comment by ghost** [comment]
please describe clearly
