### ISSUE TITLE
terraform ec2 connection 

### ISSUE THREAD

**Issue by pvmr25** [QT-DevOps/DevOpsIssues#549]
Hi Team,

Please fyi below aws.tf code

resource "aws_instance" "vm" {
  ami           = "ami-08fd8ae3806f09a08"
  instance_type = "t2.micro"
  key_name      = "mad-aws-NC-keys"
  security_groups = ["SG-ALL"]
  
  connection {
      type     = "ssh"
      user     = "ubuntu"
      private_key = "${file("./mad-aws-NC-keys.pem")}"
      
  }
  provisioner "remote-exec" {
    inline = ["sudo apt-get update", "sudo apt-get install nginx -y"] 
  }

}

after validate the code am getting below error

[mad@ip-100-0-1-100 scripts]$ terraform validate

Error: Missing required argument

  on aws.tf line 14, in resource "aws_instance" "vm":
  14:   connection {

The argument "host" is required, but no definition was found.

------------------------------------------------------------------

again rewrite the code as below

resource "aws_instance" "vm" {
  ami           = "ami-08fd8ae3806f09a08"
  instance_type = "t2.micro"
  key_name      = "mad-aws-NC-keys"
  security_groups = ["SG-ALL"]
  
  connection {
      type     = "ssh"
      user     = "ubuntu"
      private_key = "${file("./mad-aws-NC-keys.pem")}"
      host = "self.public_ip"
  }
  provisioner "remote-exec" {
    inline = ["sudo apt-get update", "sudo apt-get install nginx -y"] 
  }

now code is validate  and terraform plan also working 

now issue is below 

aws_instance.vm: Still creating... [5m20s elapsed]
aws_instance.vm: Still creating... [5m30s elapsed]
aws_instance.vm (remote-exec): Connecting to remote host via SSH...
aws_instance.vm (remote-exec):   Host: self.public_ip
aws_instance.vm (remote-exec):   User: ubuntu
aws_instance.vm (remote-exec):   Password: false
aws_instance.vm (remote-exec):   Private key: true
aws_instance.vm (remote-exec):   Certificate: false
aws_instance.vm (remote-exec):   SSH Agent: false
aws_instance.vm (remote-exec):   Checking Host Key: false
aws_instance.vm: Still creating... [5m40s elapsed]

Error: timeout - last error: dial tcp: lookup self.public_ip on 100.0.0.2:53: no such                        host

Please help me on that form any one

Thanks & regards 
Madhava

**Comment by dharmatejadevops** [comment]
> Hi Team,
> 
> Please fyi below aws.tf code
> 
> resource "aws_instance" "vm" {
> ami = "ami-08fd8ae3806f09a08"
> instance_type = "t2.micro"
> key_name = "mad-aws-NC-keys"
> security_groups = ["SG-ALL"]
> 
> connection {
> type = "ssh"
> user = "ubuntu"
> private_key = "${file("./mad-aws-NC-keys.pem")}"
> 
> }
> provisioner "remote-exec" {
> inline = ["sudo apt-get update", "sudo apt-get install nginx -y"]
> }
> 
> }
> 
> after validate the code am getting below error
> 
> [mad@ip-100-0-1-100 scripts]$ terraform validate
> 
> Error: Missing required argument
> 
> on aws.tf line 14, in resource "aws_instance" "vm":
> 14: connection {
> 
> The argument "host" is required, but no definition was found.
> 
> again rewrite the code as below
> 
> resource "aws_instance" "vm" {
> ami = "ami-08fd8ae3806f09a08"
> instance_type = "t2.micro"
> key_name = "mad-aws-NC-keys"
> security_groups = ["SG-ALL"]
> 
> connection {
> type = "ssh"
> user = "ubuntu"
> private_key = "${file("./mad-aws-NC-keys.pem")}"
> host = "self.public_ip"
> }
> provisioner "remote-exec" {
> inline = ["sudo apt-get update", "sudo apt-get install nginx -y"]
> }
> 
> now code is validate and terraform plan also working
> 
> now issue is below
> 
> aws_instance.vm: Still creating... [5m20s elapsed]
> aws_instance.vm: Still creating... [5m30s elapsed]
> aws_instance.vm (remote-exec): Connecting to remote host via SSH...
> aws_instance.vm (remote-exec): Host: self.public_ip
> aws_instance.vm (remote-exec): User: ubuntu
> aws_instance.vm (remote-exec): Password: false
> aws_instance.vm (remote-exec): Private key: true
> aws_instance.vm (remote-exec): Certificate: false
> aws_instance.vm (remote-exec): SSH Agent: false
> aws_instance.vm (remote-exec): Checking Host Key: false
> aws_instance.vm: Still creating... [5m40s elapsed]
> 
> Error: timeout - last error: dial tcp: lookup self.public_ip on 100.0.0.2:53: no such host
> 
> Please help me on that form any one
> 
> Thanks & regards
> Madhava

Hi Madava, can you send me your terraform files

**Comment by ghost** [comment]
this pem file issue
please give right path
or
share tf file

**Comment by bhaskardegala** [comment]
If you are on different network other than aws then you should consider allocation of public ip as well

**Comment by pvmr25** [comment]
problem sloved

**Comment by pvmr25** [comment]
issue was host = "self.public_ip" to be give ip address
