### ISSUE TITLE
Unable to enable PSRemoting on Win 7 and Win 10

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#55]
I have a Win 7 desktop . As instructed, I upgraded the PowerShell to 5.1 and ran the commands:
Set-ExecutionPolicy Unrestricted
Enable-PSRemoting -SkipNetworkProfileCheck -Force

However, when I run: 
PS C:\Users\Administrator> Enter-PSSession -ComputerName localhost
I get the following output:-
Enter-PSSession : Connecting to remote server localhost failed with the following error message : Access is denied. For more 
information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ Enter-PSSession -ComputerName localhost
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (localhost:String) [Enter-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : CreateRemoteRunspaceFailed

This was done after pausing Kaspersky protection and snoozing my Zonealarm Firewall

In the same machine I also have a Win 10 installed using VMWare Workstation 14 Player. When I run the same commands through Powershell 5.1 on it, I get the following response:

PS C:\Windows\system32> PS C:\Windows\system32> Enter-PSSession -ComputerName localhost
Enter-PSSession : Connecting to remote server localhost failed with the following error message : WinRM cannot process
the request. The following error with errorcode 0x8009030e occurred while using Negotiate authentication: A specified
logon session does not exist. It may already have been terminated.
 Possible causes are:
  -The user name or password specified are invalid.
  -Kerberos is used when no authentication method and no user name are specified.
  -Kerberos accepts domain user names, but not local user names.
  -The Service Principal Name (SPN) for the remote computer name and port does not exist.
  -The client and remote computers are in different domains and there is no trust between the two domains.
 After checking for the above issues, try the following:
  -Check the Event Viewer for events related to authentication.
  -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or
use HTTPS transport.
 Note that computers in the TrustedHosts list might not be authenticated.
   -For more information about WinRM configuration, run the following command: winrm help config. For more
information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ Enter-PSSession -ComputerName localhost
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (localhost:String) [Enter-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : CreateRemoteRunspaceFailed

**Comment by shaikkhajaibrahim** [comment]
Can your execute "winrm qc" in powershell as Administrator & Share your response
________________________________

**Comment by shaikkhajaibrahim** [comment]
And one more basic check. Are you running your powershell as Admininstrator ?
________________________________

**Comment by rameshm78** [comment]
Yes, I'm always running PowerShell as administrator.

PS C:\Users\Administrator> winrm qc
WinRM service is already running on this machine.
WinRM is already set up for remote management on this computer.

**Comment by rameshm78** [comment]
I found the issue.
Issue is that this command [ Enter-PSSession -ComputerName localhost ] no
longer works in this form with latest Win 10 installation.
It has to include the username:

PS C:\Windows\system32> Enter-PSSession -ComputerName localhost -Credential
rameshm78@gmail.com

A GUI for Windows Powershell credential request pops up asking for
Username: and Password.
Username is already present. When Correct password is entered and Ok is
clicked, the prompt changes to:
[localhost]: PS C:\Users\rames\Documents>

Regards
Ramesh

On Thu, Jul 12, 2018 at 5:45 PM, shaikkhajaibrahim <notifications@github.com

**Comment by shaikkhajaibrahim** [comment]
Great.
