### ISSUE TITLE
jenkins plugin installation

### ISSUE THREAD

**Issue by Jsuresh47** [QT-DevOps/DevOpsIssues#551]
i faced this question in interview

i want to install one plugin . the plug required after installation the server must be restart but in server some important jobs are running but i dont want to restart the server but i must install that plugin how you can achieve this task.

**Comment by tandrarajesh** [comment]
We can install the plugin in two ways.
1. By Jenkins UI install plugin functionality, for this there should be no blocking from connectivity I.e.from office network we cannot do it easily.
2. By downloading the plugin manually and attaching the same through the UI of Jenkins for this no need of worry of network side. 
This is as my knowledge, not 100% sure.

**Comment by tandrarajesh** [comment]
https://www.cloudbees.com/blog/install-plugins-without-restarting-jenkins
