### ISSUE TITLE
unable to install choclatey by using cmd prompt

### ISSUE THREAD

**Issue by UpputuriEswaraPrasad** [QT-DevOps/DevOpsIssues#553]
throwing an error  Error :7-Zip  signalled an unknown error .

I have tried by googling different ways but could able to resolve the issue .
i tried to set the environment  variable chocolaty as true  and rerun again .. it is showing same issue again . please find the screen shot attached .
![image](https://user-images.githubusercontent.com/52620871/62294420-7d2a8000-b488-11e9-991b-694ca0624a29.png)

**Comment by ghost** [comment]
go to this page
[https://chocolatey.org/](url)
install chocolatey 
open PowerShell run as administrator 
Install with PowerShell.exe

**Comment by UpputuriEswaraPrasad** [comment]
I have tried that as well , even then same am facing same issue  .

![image](https://user-images.githubusercontent.com/52620871/62339469-bfd87080-b4f9-11e9-8c77-3088fb402953.png)

**Comment by ghost** [comment]
what is your OS?

**Comment by UpputuriEswaraPrasad** [comment]
Windows 8.1 pro

**Comment by ghost** [comment]
Windows 8.1  not stable
better to go windows 10 Pro

**Comment by UpputuriEswaraPrasad** [comment]
Ok .. thank you  i will update the same in and close the issue
