### ISSUE TITLE
in chef while bootstraping getting this error SSH session could not be established

### ISSUE THREAD

**Issue by Nara-Sagar** [QT-DevOps/DevOpsIssues#554]
![image](https://user-images.githubusercontent.com/48256252/62410742-10d68a80-b608-11e9-8b11-e007f56b52c1.png)

**Comment by ramjagadeeshkumar** [comment]
ssh enable is required

**Comment by ghost** [comment]
please give pem file path with .pem

**Comment by SUDHAKARREDDYPONUGOTI** [comment]
![image](https://user-images.githubusercontent.com/33710217/62434620-99634100-b756-11e9-830f-8be0dd056c83.png)
Me to facing same issue please help out on this.

**Comment by SUDHAKARREDDYPONUGOTI** [comment]
bootstrap with public IP address, then connected successfully

**Comment by ghost** [comment]
yes ,  give Public IP

**Comment by Nara-Sagar** [comment]
yeah its working after giving the pem file path with .pem extension thanks.
