### ISSUE TITLE
Response:  Failed to authenticate as ****. Synchronize the clock on your host.

### ISSUE THREAD

**Issue by SrinivasCloud** [QT-DevOps/DevOpsIssues#555]
Hello Team,
when i am using **(knife node list)** using powershell under the folder chef-repo am getting the issue as ERROR: Failed to authenticate to https://api.chef.io/organizations/kjnchef**(organization name)** as **(user name)**kjnbabu with key C:/ChefSer/Aug2019/chef-starter/chef-repo/.chef/kjnbabu.pem**(.Pem File where i have download from manage.console.io )**
Response:  Failed to authenticate as kjnbabu. Synchronize the clock on your host.

am uploading the image also, can any one help to find out the issue.If you solve the issue thanks in advance
![cheferror1](https://user-images.githubusercontent.com/53685360/62422430-4cd52280-b6d0-11e9-831b-1671d414d023.png)
 

**I have changed the timezone also, Restarted the powereshell.But its not working,**

**Comment by venkatmamillapalli** [comment]
Hi Srinivas,

Your .pem key must be present in chef-repo folder

**Comment by ghost** [comment]
I think its time synchronization error

**Comment by SrinivasCloud** [comment]
Sorry I have deleted my admin role for organization in groups on manage.chef.io,i sign up new account and generate new chef-repo. one more thing time zone of my system is wrong. I have changed it It's working..thanks Naresh...
