### ISSUE TITLE
bridge issue

### ISSUE THREAD

**Issue by kmraok** [QT-DevOps/DevOpsIssues#557]
Onin one of my project, I am trying to deploy an application,I am getting this below error in docker continers.COuld u plz help me in this ..

Creating network "platform6_app_net" with driver "bridge"
could not find plugin bridge in v1 plugin registry: plugin not found
![docker error](https://user-images.githubusercontent.com/43443111/62466388-d3f8c800-b7ae-11e9-8586-1b65c94dfbaa.jpg)

![image](https://user-images.githubusercontent.com/43443111/62466345-b88dbd00-b7ae-11e9-92fa-1092053163ab.png)

**Comment by shaikkhajaibrahim** [comment]
Share your docker-compose.yml file
