### ISSUE TITLE
berks upload error

### ISSUE THREAD

**Issue by spandanareddyt** [QT-DevOps/DevOpsIssues#558]
![IMG_1462](https://user-images.githubusercontent.com/53507073/62481215-71fc8a80-b7cf-11e9-9a2a-d4e7aae2e2e0.jpg)
i am getting dis error while doing berks upload not able to solve it can any one help me out

**Comment by ghost** [comment]
please change metadata version
in metadata.rb

**Comment by spandanareddyt** [comment]
thank u


Thanks & Regards
------------------------------------


*Spandana Thirupari*

**Comment by spandanareddyt** [comment]
thank u for the help the error got rectified by changeing the version in metadata to 0.1.1 from 0.1.0
