### ISSUE TITLE
Ph

### ISSUE THREAD

**Issue by spandanareddyt** [QT-DevOps/DevOpsIssues#559]
![55221434-BD1D-4299-B686-B2CE25F36D27](https://user-images.githubusercontent.com/53507073/62485816-6c0ca680-b7db-11e9-89d1-620510c0e034.jpeg)

Got stuck and not able to go forward

**Comment by ghost** [comment]
please do this
Esc : wq

**Comment by spandanareddyt** [comment]
yup problem solved i typed wrong type
