### ISSUE TITLE
Unable to create VM Scale set in azure

### ISSUE THREAD

**Issue by vardhanK1** [QT-DevOps/DevOpsIssues#56]
Hi , 

While creating VM Scale set in Azure in UI and CLI i am getting error , 

Please find the below screenshot for your reference.
![vmscaleset err](https://user-images.githubusercontent.com/40157996/42638386-21ae9e8e-860b-11e8-8e3b-f85d5728b343.PNG)

Thanks 
Vardhan K

**Comment by vardhanK1** [comment]
For that error i have tried to fix , but it showing that template is not valid according to the validation procedure,

**Comment by raviops100** [comment]
Hi Vardhan,

i cant give exact fix but if you follow the below link once it may resolve your issue.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-invalid-template-errors

**Comment by raviops100** [comment]
is this issue resolved ??

**Comment by vardhanK1** [comment]
HI Ravi, 

For the given link is for syntactical error explanation , but in my case i have tried it in UI, and cli , in the both cases i got the same error. i hope this will workout with Pay-As-you-Go , because i am on free trail.

Let me try with this and come back to you.

Thanks for the response.

**Comment by shaikkhajaibrahim** [comment]
Closing this issue as microsoft has to resolve this
