### ISSUE TITLE
Kitchen converge

### ISSUE THREAD

**Issue by spandanareddyt** [QT-DevOps/DevOpsIssues#561]
![FE71EE45-4A95-488E-84FB-21992A3EA042](https://user-images.githubusercontent.com/53507073/62572199-c9bef280-b8b0-11e9-8d3a-713d2a155578.jpeg)
Haveing Problem in kitchen converge

**Comment by ghost** [comment]
share kitchen file

**Comment by spandanareddyt** [comment]
---
driver:
name: vagrant
provider: hyperv
network:
-["public_network", bridge: "vagrant"]
## The forwarded_port port feature lets you connect to ports on the VM
guest via
## localhost on the host.
## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

# network:
# - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
name: chef_zero
# You may wish to disable always updating cookbooks in CI or other testing
environments.
# For example:
# always_update_cookbooks: <%= !ENV['CI'] %>
always_update_cookbooks: true

## product_name and product_version specifies a specific Chef product and
version to install.
## see the Chef documentation for more details:
https://docs.chef.io/config_yml_kitchen.html
# product_name: chef
# product_version: 15

verifier:
name: inspec

platforms:
#- name: ubuntu-18.04
- name: centos-7

suites:
- name: default
run_list:
- recipe[effectivelamp::default]
verifier:
inspec_tests:
- test/integration/default
attributes:


Thanks & Regards
------------------------------------


*Spandana Thirupari*

**Comment by spandanareddyt** [comment]
@NareshAbbanapuri  please let me know if dis is wrong

**Comment by spandanareddyt** [comment]
I am not able to resolve dis problem

**Comment by ghost** [comment]
[kitchen.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3475642/kitchen.zip)
try this

**Comment by spandanareddyt** [comment]
not getting sir same error

**Comment by ghost** [comment]
please share logs

**Comment by spandanareddyt** [comment]
@NareshAbbanapuri Sir the error is solved as their was a mis-type of image id in visual studio code
