### ISSUE TITLE
power shell cmdlet error

### ISSUE THREAD

**Issue by vinayi345119** [QT-DevOps/DevOpsIssues#562]
AM getting this error. Kindly do the needfull.

C:\Users\I345119\Desktop\Terraform\2019\hello-world> terraform init
terraform : The term 'terraform' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ terraform init
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (terraform:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
<img width="590" alt="powershellerror" src="https://user-images.githubusercontent.com/34369680/62588180-72d21100-b8e2-11e9-95ac-382e0c6f30d9.PNG">

**Comment by ghost** [comment]
please run this command where you have tf file

**Comment by vinayi345119** [comment]
@NareshAbbanapuri  : am doing the same path is correct. No idea what is wrong

**Comment by vinayi345119** [comment]
tf file is inside hello-world

**Comment by vinayi345119** [comment]
terraform was not installed, After installing the terraform it worked 

Thanks,
Vinay
