### ISSUE TITLE
Kitchen converge of ec2 issue on ubuntu 16.04 base machine

### ISSUE THREAD

**Issue by htornala** [QT-DevOps/DevOpsIssues#564]
Hi,
I am using ubuntu 16.04 base machine as work station, I am facing issue while doing kitchen converge for AWS, It is asking for yes/no, eventhough I have given yes I'm facing issue.
![Screenshot from 2019-08-07 14-30-20](https://user-images.githubusercontent.com/51317614/62610080-8bf9b280-b920-11e9-9c08-e06fb3cf84d5.png)
[log.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3476203/log.txt)
[issue.tar.gz](https://github.com/QT-DevOps/DevOpsIssues/files/3476215/issue.tar.gz)
[issue.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3476219/issue.zip)

 I have attached logs, screenshot,kitchen.yml file for reference, can any one please help me

**Comment by SESHUNAIDU** [comment]
Add chef_license: accept  in kitchen.yml in provisioner section

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  client_rb:
    chef_licence: accept

Try in this way it will be resolve

**Comment by SESHUNAIDU** [comment]
[.kitchen.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3562328/default.kitchen.zip)

**Comment by SESHUNAIDU** [comment]
add chef_license: accept  in kitchen.yml file in provisioner section

once check out the above kitchen.zip file. your issue will be resolve

**Comment by htornala** [comment]
Thank you sesh, it has worked when added to attributes section, attached file for reference
[kitchen_aws_bkp.yml.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3562566/kitchen_aws_bkp.yml.zip)
