### ISSUE TITLE
Kitchen converge: SSH Connection failed

### ISSUE THREAD

**Issue by akashsan** [QT-DevOps/DevOpsIssues#565]
On running kitchen converge, receiving following error
![image](https://user-images.githubusercontent.com/50402277/62649152-f129c400-b971-11e9-9933-4067dd3ebde3.png)

My Kitchen.yml
[kitchen.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3478475/kitchen.zip)

My folder structure:
![image](https://user-images.githubusercontent.com/50402277/62649289-3e0d9a80-b972-11e9-88b9-380212cae0b0.png)

Logs:
[default-ubuntu-1804.log](https://github.com/QT-DevOps/DevOpsIssues/files/3478479/default-ubuntu-1804.log)

**Comment by ghost** [comment]
please verify everything same region or not
need to give pem  file path

**Comment by akashsan** [comment]
Yes @NareshAbbanapuri  sir, the pem file path is present inside the cookbook and i am running the command inside the cookbook aswell.
I saw where my machines are created. 
Let me know how to confirm the region

**Comment by akashsan** [comment]
Confirmed my zone availability using
aws ec2 describe-availability-zones --region us-east-2 command.

Still same issue

**Comment by bhaskardegala** [comment]
Is your issue solved

**Comment by akashsan** [comment]
No
