### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by kmraok** [QT-DevOps/DevOpsIssues#568]
Hi..any budy have a document of Docker installation on Windows server 2019/windows10 VM's. I tried the installation, but getting an error while switching from windows containers to Linux containers. Is it possible to install Docker on Windows VM's without enabling virtualization on VM?
Because we can't enter into BIOS on VM.The Same error it throwing on Win10Professional & Winserver2019 EE

![Switching 2](https://user-images.githubusercontent.com/43443111/62697237-e9acfe00-b9f7-11e9-94f0-bf6778616941.png)
![Switching error](https://user-images.githubusercontent.com/43443111/62697239-e9acfe00-b9f7-11e9-9960-9f3d2fc394c3.png)
![Switching to Linux](https://user-images.githubusercontent.com/43443111/62697241-ea459480-b9f7-11e9-8e54-c94a9d631aab.png)
![Win-10 VM](https://user-images.githubusercontent.com/43443111/62697243-ea459480-b9f7-11e9-95c3-e554add5c72f.png)

**Comment by bhaskardegala** [comment]
I think you should definitely have a virtualistion (VM ware ) for installing docker

**Comment by kmraok** [comment]
But in VM's we can't enable virtualization ..how to resolve this issue?

**Comment by raviops99** [comment]
Hi Rao,
Can you please go through below link hope it may help you 
https://4sysops.com/archives/install-docker-on-windows-server-2019/

**Comment by ghost** [comment]
try to take linux vm

**Comment by kmraok** [comment]
Thanks for ur support
