### ISSUE TITLE
  In cli  vm creation storage account error

### ISSUE THREAD

**Issue by BALU6** [QT-DevOps/DevOpsIssues#57]
![s](https://user-images.githubusercontent.com/34449707/42700078-4bb121cc-86e0-11e8-8ae6-0038fbfadd70.PNG)

**Comment by Imalli5253** [comment]
![capture1](https://user-images.githubusercontent.com/20962752/42754368-dd8b3866-8911-11e8-89a3-e7cfd00e133c.JPG)
It will work by adding "--use-unmanaged-disk" and "--admin-username"
