### ISSUE TITLE
Sonar job failure

### ISSUE THREAD

**Issue by chirala** [QT-DevOps/DevOpsIssues#570]
Hi sir,
          while i am executing the job using sonarqube i am getting this error can you please guide me how to resolve that issue 

+ mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar
[[1;34mINFO[m] Scanning for projects...
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m------------< [0;36morg.springframework.samples:spring-petclinic[0;1m >------------[m
[[1;34mINFO[m] [1mBuilding petclinic 2.1.0.BUILD-SNAPSHOT[m
[[1;34mINFO[m] [1m--------------------------------[ jar ]---------------------------------[m
[[1;34mINFO[m] 
[[1;34mINFO[m] [1m--- [0;32msonar-maven-plugin:3.2:sonar[m [1m(default-cli)[m @ [36mspring-petclinic[0;1m ---[m
[[1;34mINFO[m] User cache: /home/jenkins/.sonar/cache
[[1;34mINFO[m] Publish mode
[[1;34mINFO[m] Load global settings
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;31mBUILD FAILURE[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time:  4.290 s
[[1;34mINFO[m] Finished at: 2019-08-08T11:11:05Z
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;31mERROR[m] Failed to execute goal [32morg.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar[m [1m(default-cli)[m on project [36mspring-petclinic[m: [1;31mNot authorized. Please check the properties sonar.login and sonar.password.[m -> [1m[Help 1][m
[[1;31mERROR[m] 
[[1;31mERROR[m] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
[[1;31mERROR[m] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[[1;31mERROR[m] 
[[1;31mERROR[m] For more information about the errors and possible solutions, please read the following articles:
[[1;31mERROR[m] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[Pipeline] }
WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succeeded?
[Pipeline] // withSonarQubeEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by ghost** [comment]
please check properties of sonarqube

**Comment by bhaskardegala** [comment]
Authentication problem it could not verify your credentials

**Comment by chirala** [comment]
Thanks for your support
