### ISSUE TITLE
while running chef kitchen with ec2 driver ......

### ISSUE THREAD

**Issue by raju245** [QT-DevOps/DevOpsIssues#572]
![Untitled](https://user-images.githubusercontent.com/35062809/62786240-d1181300-badf-11e9-9aae-5888bcee4640.png)
![Untitled1](https://user-images.githubusercontent.com/35062809/62786243-d1181300-badf-11e9-98c9-e1eb67a67d68.png)

**Comment by ghost** [comment]
problem in the transport section
please give some space after transport (ssh_key , username)

**Comment by bhaskardegala** [comment]
As Naresh said earlier try using proper indentation and check your fire wall and turn off your anti virus software

**Comment by raju245** [comment]
yes, I tried but it didn't work out  turned off firewall and gave proper indentation and no antivirus in my laptop
