### ISSUE TITLE
failed to kitchen converge 

### ISSUE THREAD

**Issue by mounika0104** [QT-DevOps/DevOpsIssues#573]
![mounika](https://user-images.githubusercontent.com/53105296/62817721-91543880-bb7e-11e9-8ec9-e810e2eef72c.jpg)

**Comment by ghost** [comment]
use this bento/centos7  not bento/centos-7

**Comment by mounika0104** [comment]
i tried both but the result is same

**Comment by mounika0104** [comment]
the problem is solved.my antivirus doesn't support some sites to download bento/centos7box. so i added the site to add exclusion and it worked
