### ISSUE TITLE
There was an error while executing `VBoxManage`, a CLI used by Vagrant  for controlling VirtualBox. The command and stderr is shown below.

### ISSUE THREAD

**Issue by Nara-Sagar** [QT-DevOps/DevOpsIssues#574]
![image](https://user-images.githubusercontent.com/48256252/62820795-2a874d00-bb87-11e9-9bb1-9ee212bc4de1.png)

Every time I do kitchen converge I am getting this error.

**Comment by bhaskardegala** [comment]
I was not good at vagrant, I think you can use hyper-v instead

**Comment by Nara-Sagar** [comment]
I think this is happening because I have enabled both HyperV and virtual box I have uninstalled the VirtualBox now it's working without showing any error.
