### ISSUE TITLE
ssh connection failed while test kitchen EC2

### ISSUE THREAD

**Issue by Nara-Sagar** [QT-DevOps/DevOpsIssues#575]
![image](https://user-images.githubusercontent.com/48256252/62831523-8660dd00-bc3e-11e9-9ee0-720da0d8b03a.png)
![image](https://user-images.githubusercontent.com/48256252/62831527-8fea4500-bc3e-11e9-8e62-97c21186802a.png)
every time i am getting the fallowing error.
[SSH] connection failed, retrying in 1 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)

**Comment by ghost** [comment]
please send kitchen.yml file

**Comment by bhaskardegala** [comment]
Please try using git bash instead of powershell

**Comment by venkatmamillapalli** [comment]
please remove doublecodes for subnet-id

**Comment by Nara-Sagar** [comment]
this issue got resolved.
