### ISSUE TITLE
Hi, I am having issue while doing kitchen converge.

### ISSUE THREAD

**Issue by hanocc** [QT-DevOps/DevOpsIssues#576]
![error-1](https://user-images.githubusercontent.com/51271895/62835043-63035580-bc71-11e9-8b40-3d705e729d03.PNG)

**Comment by ghost** [comment]
share kitchen.yml file

**Comment by bhaskardegala** [comment]
It might be due to your firewall try using git bash instead of powershell

**Comment by dharmatejadevops** [comment]
share your log file once
