### ISSUE TITLE
Kitchen::UserError

### ISSUE THREAD

**Issue by rajeshande430** [QT-DevOps/DevOpsIssues#578]
I am unable to perform kitchen converge with aws, somehow the moment in punch kitchen converge, immediately the error pops up, tried so long but no luck, guys could someone help on this.

![1 KitchenUserError](https://user-images.githubusercontent.com/53960487/62919508-ed53d280-bdb3-11e9-8c73-1781507a40e8.JPG)
![1 yamlfile](https://user-images.githubusercontent.com/53960487/62919509-ed53d280-bdb3-11e9-987b-0ac0dc224f17.JPG)

Kitchen error log is as attached.

I, [2019-08-13T09:56:41.174276 #9976]  INFO -- Kitchen: -----> Starting Kitchen (v2.2.5)
E, [2019-08-13T09:56:41.194132 #9976] ERROR -- Kitchen: ------Exception-------
E, [2019-08-13T09:56:41.196514 #9976] ERROR -- Kitchen: Class: Kitchen::UserError
E, [2019-08-13T09:56:41.196623 #9976] ERROR -- Kitchen: Message: Error parsing C:/Users/user/Desktop/chef kits/chef-repo/cookbooks/awstomcatcookbook/kitchen.yml as YAML.
Please run `kitchen diagnose --no-instances --loader' to help debug your issue.
E, [2019-08-13T09:56:41.196715 #9976] ERROR -- Kitchen: ----------------------
E, [2019-08-13T09:56:41.196795 #9976] ERROR -- Kitchen: ------Backtrace-------
E, [2019-08-13T09:56:41.196872 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:364:in `rescue in parse_yaml_string'
E, [2019-08-13T09:56:41.197459 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:352:in `parse_yaml_string'
E, [2019-08-13T09:56:41.197541 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:129:in `yaml'
E, [2019-08-13T09:56:41.197607 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:117:in `combined_hash'
E, [2019-08-13T09:56:41.197669 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:68:in `read'
E, [2019-08-13T09:56:41.197730 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:152:in `data'
E, [2019-08-13T09:56:41.197790 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:131:in `suites'
E, [2019-08-13T09:56:41.197850 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:182:in `filter_instances'
E, [2019-08-13T09:56:41.197910 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:141:in `build_instances'
E, [2019-08-13T09:56:41.197970 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:117:in `instances'
E, [2019-08-13T09:56:41.198029 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:112:in `filtered_instances'
E, [2019-08-13T09:56:41.198088 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:142:in `parse_subcommand'
E, [2019-08-13T09:56:41.198147 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command/action.rb:35:in `block in call'
E, [2019-08-13T09:56:41.198206 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
E, [2019-08-13T09:56:41.198266 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command/action.rb:34:in `call'
E, [2019-08-13T09:56:41.198325 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/cli.rb:52:in `perform'
E, [2019-08-13T09:56:41.198386 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
E, [2019-08-13T09:56:41.198446 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
E, [2019-08-13T09:56:41.198508 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
E, [2019-08-13T09:56:41.198568 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
E, [2019-08-13T09:56:41.198648 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
E, [2019-08-13T09:56:41.198744 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/bin/kitchen:13:in `block in <top (required)>'
E, [2019-08-13T09:56:41.198812 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2019-08-13T09:56:41.198873 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/bin/kitchen:13:in `<top (required)>'
E, [2019-08-13T09:56:41.198933 #9976] ERROR -- Kitchen: C:/opscode/chefdk/bin/kitchen:359:in `load'
E, [2019-08-13T09:56:41.199002 #9976] ERROR -- Kitchen: C:/opscode/chefdk/bin/kitchen:359:in `<main>'
E, [2019-08-13T09:56:41.199049 #9976] ERROR -- Kitchen: ----End Backtrace-----
E, [2019-08-13T09:56:41.199094 #9976] ERROR -- Kitchen: ---Nested Exception---
E, [2019-08-13T09:56:41.199140 #9976] ERROR -- Kitchen: Class: Psych::SyntaxError
E, [2019-08-13T09:56:41.199185 #9976] ERROR -- Kitchen: Message: (<unknown>): could not find expected ':' while scanning a simple key at line 18 column 1
E, [2019-08-13T09:56:41.199232 #9976] ERROR -- Kitchen: ----------------------
E, [2019-08-13T09:56:41.199277 #9976] ERROR -- Kitchen: ------Backtrace-------
E, [2019-08-13T09:56:41.199323 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:364:in `rescue in parse_yaml_string'
E, [2019-08-13T09:56:41.199370 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:352:in `parse_yaml_string'
E, [2019-08-13T09:56:41.199416 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:129:in `yaml'
E, [2019-08-13T09:56:41.199462 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:117:in `combined_hash'
E, [2019-08-13T09:56:41.199509 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:68:in `read'
E, [2019-08-13T09:56:41.199555 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:152:in `data'
E, [2019-08-13T09:56:41.199600 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:131:in `suites'
E, [2019-08-13T09:56:41.199646 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:182:in `filter_instances'
E, [2019-08-13T09:56:41.199693 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:141:in `build_instances'
E, [2019-08-13T09:56:41.199739 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:117:in `instances'
E, [2019-08-13T09:56:41.199785 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:112:in `filtered_instances'
E, [2019-08-13T09:56:41.199831 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:142:in `parse_subcommand'
E, [2019-08-13T09:56:41.199876 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command/action.rb:35:in `block in call'
E, [2019-08-13T09:56:41.199922 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
E, [2019-08-13T09:56:41.199968 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command/action.rb:34:in `call'
E, [2019-08-13T09:56:41.200014 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/cli.rb:52:in `perform'
E, [2019-08-13T09:56:41.200060 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
E, [2019-08-13T09:56:41.200131 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
E, [2019-08-13T09:56:41.200183 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
E, [2019-08-13T09:56:41.200229 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
E, [2019-08-13T09:56:41.200274 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
E, [2019-08-13T09:56:41.200320 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/bin/kitchen:13:in `block in <top (required)>'
E, [2019-08-13T09:56:41.200381 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2019-08-13T09:56:41.200428 #9976] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/bin/kitchen:13:in `<top (required)>'
E, [2019-08-13T09:56:41.200475 #9976] ERROR -- Kitchen: C:/opscode/chefdk/bin/kitchen:359:in `load'
E, [2019-08-13T09:56:41.200520 #9976] ERROR -- Kitchen: C:/opscode/chefdk/bin/kitchen:359:in `<main>'
E, [2019-08-13T09:56:41.200565 #9976] ERROR -- Kitchen: ----End Backtrace-----

**Comment by ghost** [comment]
remove the availability zone , subnet id , security group 
try it once

**Comment by rajeshande430** [comment]
Hi naresh,

tried but the same error

**Comment by rajeshande430** [comment]
I, [2019-08-13T11:16:04.098397 #3176]  INFO -- Kitchen: -----> Starting Kitchen (v2.2.5)
E, [2019-08-13T11:16:04.118061 #3176] ERROR -- Kitchen: ------Exception-------
E, [2019-08-13T11:16:04.119728 #3176] ERROR -- Kitchen: Class: Kitchen::UserError
E, [2019-08-13T11:16:04.119801 #3176] ERROR -- Kitchen: Message: Error parsing C:/Users/user/Desktop/chef kits/chef-repo/cookbooks/awscb/kitchen.yml as YAML.
Please run `kitchen diagnose --no-instances --loader' to help debug your issue.
E, [2019-08-13T11:16:04.119862 #3176] ERROR -- Kitchen: ----------------------
E, [2019-08-13T11:16:04.119916 #3176] ERROR -- Kitchen: ------Backtrace-------
E, [2019-08-13T11:16:04.119969 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:364:in `rescue in parse_yaml_string'
E, [2019-08-13T11:16:04.120022 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:352:in `parse_yaml_string'
E, [2019-08-13T11:16:04.120108 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:129:in `yaml'
E, [2019-08-13T11:16:04.120170 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:117:in `combined_hash'
E, [2019-08-13T11:16:04.120249 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:68:in `read'
E, [2019-08-13T11:16:04.120307 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:152:in `data'
E, [2019-08-13T11:16:04.120360 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:131:in `suites'
E, [2019-08-13T11:16:04.120417 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:182:in `filter_instances'
E, [2019-08-13T11:16:04.120469 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:141:in `build_instances'
E, [2019-08-13T11:16:04.120521 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:117:in `instances'
E, [2019-08-13T11:16:04.120572 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:112:in `filtered_instances'
E, [2019-08-13T11:16:04.120672 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:142:in `parse_subcommand'
E, [2019-08-13T11:16:04.120798 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command/action.rb:35:in `block in call'
E, [2019-08-13T11:16:04.120872 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
E, [2019-08-13T11:16:04.120942 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command/action.rb:34:in `call'
E, [2019-08-13T11:16:04.121007 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/cli.rb:52:in `perform'
E, [2019-08-13T11:16:04.121070 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
E, [2019-08-13T11:16:04.121133 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
E, [2019-08-13T11:16:04.121196 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
E, [2019-08-13T11:16:04.121260 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
E, [2019-08-13T11:16:04.121323 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
E, [2019-08-13T11:16:04.121442 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/bin/kitchen:13:in `block in <top (required)>'
E, [2019-08-13T11:16:04.121522 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2019-08-13T11:16:04.121582 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/bin/kitchen:13:in `<top (required)>'
E, [2019-08-13T11:16:04.121642 #3176] ERROR -- Kitchen: C:/opscode/chefdk/bin/kitchen:359:in `load'
E, [2019-08-13T11:16:04.121700 #3176] ERROR -- Kitchen: C:/opscode/chefdk/bin/kitchen:359:in `<main>'
E, [2019-08-13T11:16:04.121758 #3176] ERROR -- Kitchen: ----End Backtrace-----
E, [2019-08-13T11:16:04.121815 #3176] ERROR -- Kitchen: ---Nested Exception---
E, [2019-08-13T11:16:04.121872 #3176] ERROR -- Kitchen: Class: Psych::SyntaxError
E, [2019-08-13T11:16:04.121929 #3176] ERROR -- Kitchen: Message: (<unknown>): could not find expected ':' while scanning a simple key at line 19 column 1
E, [2019-08-13T11:16:04.121986 #3176] ERROR -- Kitchen: ----------------------
E, [2019-08-13T11:16:04.122043 #3176] ERROR -- Kitchen: ------Backtrace-------
E, [2019-08-13T11:16:04.122100 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:364:in `rescue in parse_yaml_string'
E, [2019-08-13T11:16:04.122158 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:352:in `parse_yaml_string'
E, [2019-08-13T11:16:04.122216 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:129:in `yaml'
E, [2019-08-13T11:16:04.122273 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:117:in `combined_hash'
E, [2019-08-13T11:16:04.122331 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/loader/yaml.rb:68:in `read'
E, [2019-08-13T11:16:04.122389 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:152:in `data'
E, [2019-08-13T11:16:04.122446 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:131:in `suites'
E, [2019-08-13T11:16:04.122504 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:182:in `filter_instances'
E, [2019-08-13T11:16:04.122558 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:141:in `build_instances'
E, [2019-08-13T11:16:04.122606 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/config.rb:117:in `instances'
E, [2019-08-13T11:16:04.122654 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:112:in `filtered_instances'
E, [2019-08-13T11:16:04.122703 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command.rb:142:in `parse_subcommand'
E, [2019-08-13T11:16:04.122751 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command/action.rb:35:in `block in call'
E, [2019-08-13T11:16:04.122800 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
E, [2019-08-13T11:16:04.122849 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/command/action.rb:34:in `call'
E, [2019-08-13T11:16:04.122899 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/cli.rb:52:in `perform'
E, [2019-08-13T11:16:04.122947 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
E, [2019-08-13T11:16:04.123000 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
E, [2019-08-13T11:16:04.123049 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
E, [2019-08-13T11:16:04.123098 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
E, [2019-08-13T11:16:04.123146 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
E, [2019-08-13T11:16:04.123194 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/bin/kitchen:13:in `block in <top (required)>'
E, [2019-08-13T11:16:04.123242 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/lib/kitchen/errors.rb:171:in `with_friendly_errors'
E, [2019-08-13T11:16:04.123291 #3176] ERROR -- Kitchen: C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.2.5/bin/kitchen:13:in `<top (required)>'
E, [2019-08-13T11:16:04.123339 #3176] ERROR -- Kitchen: C:/opscode/chefdk/bin/kitchen:359:in `load'
E, [2019-08-13T11:16:04.123386 #3176] ERROR -- Kitchen: C:/opscode/chefdk/bin/kitchen:359:in `<main>'
E, [2019-08-13T11:16:04.123434 #3176] ERROR -- Kitchen: ----End Backtrace-----

[kitchen.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3495713/kitchen.zip)


FYI.
[awscb::awsrp]

**Comment by ghost** [comment]
[kitchen.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3496398/kitchen.zip)
please try this

**Comment by rajeshande430** [comment]
This worked well, what is the issue earlier, why was i not able to start kitchen converge ?
