### ISSUE TITLE
Waiting for ssh connection 

### ISSUE THREAD

**Issue by Nara-Sagar** [QT-DevOps/DevOpsIssues#579]
![image](https://user-images.githubusercontent.com/48256252/62996116-1e4e0900-be81-11e9-96cf-60364050ba51.png)

every time I do kitchen converge with AWS ec2 I get this only why it's not getting a login.

**Comment by rajeshande430** [comment]
I also had a same problem earlier, i believe its a problem with the security group, use the attached kitchen file and replace it within your cookbook then edit as necessary and try converging again and see if it works.
NOTE : ensure to change the ssh key id & ssh key as per your 
let me know if it works
[kitchen.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3500726/kitchen.zip)

**Comment by Nara-Sagar** [comment]
hi Rajesh Thanks for helping. yeah, it is working after changing the kitchen.yml file.
