### ISSUE TITLE
Getting error while running powershellDSC script

### ISSUE THREAD

**Issue by Josephreddykandi** [QT-DevOps/DevOpsIssues#58]
Hi all, 

I am using windows 10 machine and 5.1v Powershell. I have written sample PowerShell DSC script to create a new file in the existing directory. 

below are the steps I have followed. 
1. written a script with a file name as helloconfig.ps1 
2. open PowerShell as an administrator and go to the folder where I have written script and execute the script it will create a MOF file.
3. then I have run the command **Start-DscConfiguration .\helloconfig\ -Wait -Verbose** it shows below error. 
![image](https://user-images.githubusercontent.com/37059570/42727463-c1ca83d2-87c4-11e8-8484-f534664dece0.png)

can you please advide me how can i slove this one?

**Comment by manikantagaddam** [comment]
can u  Please check Get-ExecutionPolicy.please make sure that it is unrestricted or remoteassgined

**Comment by Josephreddykandi** [comment]
Hi @manikantagaddam, 

Thanks for looking into this one. when i run the Get-ExecutionPolicy command it shows "unrestricted" message. 

PS G:\powershell>
PS G:\powershell> Get-ExecutionPolicy
Unrestricted
PS G:\powershell>
PS G:\powershell>

**Comment by Josephreddykandi** [comment]
I have tried on the cloud windows server 2016 machine but still, I am getting the same error. can you please suggest me on this one?

**Comment by manikantagaddam** [comment]
post the script wt u r trying to executing and also check by enabling psremoting and and check whether it is connecting to guest or localhost

**Comment by Josephreddykandi** [comment]
here is the script:

Configuration helloconfig {

    Import-DscResource -ModuleName psdesiredstateconfiguration

    node loaclhost {

        File hellofile {

            DestinationPath = 'F:\temp\josh.txt'
            Type = 'File'
	    Ensure = 'Present'
        
        }
    }
}
helloconfig

**Comment by shaikkhajaibrahim** [comment]
Spelling of localhost

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by manikantagaddam** [comment]
And also  check dis Import-DscResource -ModuleName PsDesiredStateConfiguration

**Comment by Josephreddykandi** [comment]
sorry for that, spelling correction and adding contents resource is working. 

Configuration helloconfig {

    Import-DscResource -ModuleName psdesiredstateconfiguration

    node localhost {

        File hellofile {

            DestinationPath = 'F:\temp\josh.txt'
            Type = 'File'
	    Ensure = 'Present'
	    Contents= 'hello'
        
        }
    }
}
helloconfig 

thank you sir

**Comment by manikantagaddam** [comment]
Closed
