### ISSUE TITLE
Windows slave not able to connect to Linux Master Jenkins

### ISSUE THREAD

**Issue by thisiskrish1984** [QT-DevOps/DevOpsIssues#581]
HI.Iam trying to connect my Windows slave to Linux master.
But unable to connect it and facing following issues
.Even had a look on same kinda issues posted here and changed the required needs such as ports on security groups, 
changed Turn-off Defender firewall off in both public and private on Control Panel\System and Security\Windows Defender Firewall\Customize Settings\Private networkseetings\ etc.
Added port number 36927 which mentioned is not reachable.
And still not able to resolve it.
Plz have a look and help me out to resolve it.TIA.
![1](https://user-images.githubusercontent.com/47324599/63063281-a384fc80-bf19-11e9-95ee-cb3c2b812d9a.PNG)
![2](https://user-images.githubusercontent.com/47324599/63063294-aed82800-bf19-11e9-8da7-c2344ec9a668.PNG)

**Comment by ravipanthangi** [comment]
Hi

**Comment by raviops99** [comment]
Hi Krishna,

 before excuting above step you need to turn off firewall in your laptop or machine
For some time then windows slave connect  to Linux master please try this

**Comment by thisiskrish1984** [comment]
Hi Ravi
It's was off before executing the steps.Later as per the requirement I
changed the settings but still not able to establish the connection between
windows and Linux and not able to find the exact issue too.

**Comment by raviops99** [comment]
Can you please go through closed issue
Issue number 338 still if you get same issue 
Will see further

**Comment by thisiskrish1984** [comment]
Sure.will check it out.

**Comment by thisiskrish1984** [comment]
> Can you please go through closed issue
> Issue number 338 still if you get same issue
> Will see further

HI Ravi executed the same recommended steps and also gone through similar issues but still not able to resolve it.

**Comment by thisiskrish1984** [comment]
Tried again with the same steps as follows.
1.Created new node on Jenkins
![13](https://user-images.githubusercontent.com/47324599/63643312-62e06c80-c6eb-11e9-88d5-2438b3b18d41.PNG)
2.Downloaded the agent.jar file and changed the private ip into public ip and executed it on Windows 
![14](https://user-images.githubusercontent.com/47324599/63643346-03cf2780-c6ec-11e9-944e-1bc46095f765.PNG)
powershell
3.After execution
![11](https://user-images.githubusercontent.com/47324599/63643347-1e090580-c6ec-11e9-8ab6-0142eda3ee8b.PNG)
4.changed the Defender firewall setting as off on my windows machine
![15](https://user-images.githubusercontent.com/47324599/63643352-35e08980-c6ec-11e9-8f77-6ca4d294ecb3.PNG)
5.Added port 45575 on security/firewall on my linux machine which is mentioned as not reachable.
And still getting the same issues.

NOTE:While changing the Configure global security->Agent-> Random .
Iam getting Reverse proxy setup is broken.
![12](https://user-images.githubusercontent.com/47324599/63643420-552be680-c6ed-11e9-8fa5-256794d0aef7.PNG)

**Comment by mani5a3** [comment]
hi once check  below thing
1) go jenkins server --> manage jenkins --> configuration system --> jenkins location(check the ip if it  is not match to the  public of ec2 instance replace it with public ip)

**Comment by thisiskrish1984** [comment]
HI mani5a3.
Thanks man.Changed the ip on the mentioned path and established connection between windows node to Linux master and at the end getting issues on jar file.
Herewith attached the screenshot.Plz have a look and let me know.
Thanks.
![Capture1](https://user-images.githubusercontent.com/47324599/64359850-d0af6100-d026-11e9-8c53-e406aa3b991f.PNG)
