### ISSUE TITLE
Problem while using wget, not able to download  (Chef kitchen EC2) 

### ISSUE THREAD

**Issue by jayshah7** [QT-DevOps/DevOpsIssues#582]
Hello all, 

I configured EC2 in my kitchen.yml file and while performing kitchen create, it stuck at wget command in ec2 instance although port 443 is open and have internet access. 

EC2 instance <i-067ae59c6ed5bd44d> ready (hostname: ec2-18-236-145-191.us-west-2.compute.amazonaws.com).
       Waiting for SSH service on ec2-18-236-145-191.us-west-2.compute.amazonaws.com:22, retrying in 3 seconds
       [SSH] Established
       Finished creating <default-ubuntu-1604> (1m11.06s).
-----> Converging <default-ubuntu-1604>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.0.8...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef 15 package
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying wget...

When I login to EC2 instance and try same command it also hungs and I can see it is trying to connect through port 443 : 

 sudo wget https://omnitruck.chef.io/install.sh
--2019-08-15 08:56:03--  https://omnitruck.chef.io/install.sh
Resolving omnitruck.chef.io (omnitruck.chef.io)... 151.101.42.110
Connecting to omnitruck.chef.io (omnitruck.chef.io)|151.101.42.110|:443...

 netstat -aln | grep 443
tcp        0      1 192.168.1.57:33966      151.101.42.110:443      SYN_SENT
tcp        0      1 192.168.1.57:39726      151.101.190.110:443     SYN_SENT

Attaching my kitchen.yml file. Additionally, after doing lot of research in google some point towards setting http_proxy parameter. I am connecting from China using an inbuilt VPN proxy router, so if this is issue how can I know url for proxy ? 

Please help me. 

[kitchen.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3504996/kitchen.zip)

**Comment by rajeshande430** [comment]
[kitchen.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3507835/kitchen.zip)
try the attached kitchen file, be sure to update only the ssh id and key and recipe name and rest all keep as it is and checkout if u are able to succeed.

**Comment by jayshah7** [comment]
Hello Rajesh, 

Thanks it worked finally !!! 

When I compared kitchen.yml file you skipped subnetid & security group which means it will go to default VPC. In my case I was referring to new VPC created which had some issues.
