### ISSUE TITLE
FC033: Missing template file: default.rb:26

### ISSUE THREAD

**Issue by rajeshande430** [QT-DevOps/DevOpsIssues#583]
I could understand why foodcritic says "FC033: Missing template file: default.rb:26", yes there was a template written in my cookbook to update the username and password during tomcat8 installation process, i couldnt figureout what was the error in it, although if i run "kitchen converge" i endup landing fatal error which points to the same issue template issue.

guys need someone help, is there any fix for this.

attached is my kitchen file

[kitchen.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3507803/kitchen.zip)

**Comment by bhaskardegala** [comment]
Please share even your cookbook

**Comment by rajeshande430** [comment]
Uploaded the cookbook, could you check and reply

[tcat8.zip](https://github.com/QT-DevOps/DevOpsIssues/files/3523252/tcat8.zip)

**Comment by rajeshande430** [comment]
any update on the above
