### ISSUE TITLE
error in pipeline job for sonar analysis java.lang.NoSuchMethodError: No such DSL method 'withSonarqubeEnv' 

### ISSUE THREAD

**Issue by Rameshdutt80** [QT-DevOps/DevOpsIssues#584]
Hi i tried to excute a example for sonarqube analysis by running docker image for sonarqube

step1
![1](https://user-images.githubusercontent.com/37854691/63409852-9d0ded80-c40f-11e9-9cb0-4f0fd94eda93.png)

step2
![2](https://user-images.githubusercontent.com/37854691/63409872-a434fb80-c40f-11e9-84a5-c7ab797f4535.png)

step3
![3](https://user-images.githubusercontent.com/37854691/63409884-a8f9af80-c40f-11e9-9cd7-7f006e0c1abf.png)

step4 i found below error 

![4](https://user-images.githubusercontent.com/37854691/63409906-b0b95400-c40f-11e9-99b3-30f53c05b1f2.png)
![5](https://user-images.githubusercontent.com/37854691/63409917-b6169e80-c40f-11e9-9e97-0a988811c162.png)

could you please suggest me on this

**Comment by RahulAnita** [comment]
Below link might help you:

https://stackoverflow.com/questions/42763384/unknown-stage-section-withsonarqubeenv

**Comment by ghost** [comment]
please check script once

**Comment by sandhyadev** [comment]
Please change your groovy script 

withSonarQubeEnv('sonarqube') 
not this withSonarQubeEnv('sonarQube')

Here the issue is name mismatch
