### ISSUE TITLE
"I got an error while i am trying to run playbooks(install lamp-stack on ubuntu)"

### ISSUE THREAD

**Issue by sanjeevaduri** [QT-DevOps/DevOpsIssues#585]
![ansible error](https://user-images.githubusercontent.com/52369863/63414550-bc117d00-c419-11e9-87f2-d64e72a068e7.PNG)

**Comment by sanjeevaduri** [comment]
"when i am trying to run the play book . Automatically  (.retry) file also created
![ansible1](https://user-images.githubusercontent.com/52369863/63415161-ea438c80-c41a-11e9-9623-1cfb92227dc1.PNG)

**Comment by srmanikanta** [comment]
if you run the playbook again after failed execute the following command
ansible-playbook lamp-beginar.yml --limit @lamp-beginar.retry
or else if you stop the .retry file 
open ansible.cfg file
retry_files_enabled = False

**Comment by raviops99** [comment]
Can you  please  share  playbook what  you have written

**Comment by ghost** [comment]
please share playbook

**Comment by sanjeevaduri** [comment]
Sure , here i attatched it plz check for a while.
![new yml file](https://user-images.githubusercontent.com/52369863/63495779-25f35a80-c4de-11e9-992d-277d81b74628.PNG)

**Comment by sanjeevaduri** [comment]
Hi, guys thank you for your response I resolved the issue. The problem is I  did a mistake in Sudo permissions of node1.
