### ISSUE TITLE
Ansible error : Failed to connect to the host via ssh: Authentication failed.

### ISSUE THREAD

**Issue by praveensatti** [QT-DevOps/DevOpsIssues#586]
i'm an using a local ansible.cfg file  for connecting to hosts as below. im receiving  the above error. im able to ssh the machine manually (ssh -i /home/ec2-user/id.pem ec2-user@ip )
cat ansible.cfg 
[defaults]
inventory = /home/ec2-user/ansible/servers
private_key_file = /home/ec2-user/id.pem
remote_user = ec2-user
host_key_checking = False

cat servers
[test]
10.0.5.232

full stack error below:

[ec2-user@ip-10-0-1-181 ansible]$ ansible -vvv  -m ping all
ansible 2.8.2
  config file = /home/ec2-user/ansible/ansible.cfg
  configured module search path = ['/home/ec2-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Apr 30 2019, 22:50:54) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
Using /home/ec2-user/ansible/ansible.cfg as config file
host_list declined parsing /home/ec2-user/ansible/servers as it did not pass it's verify_file() method
script declined parsing /home/ec2-user/ansible/servers as it did not pass it's verify_file() method
auto declined parsing /home/ec2-user/ansible/servers as it did not pass it's verify_file() method
Parsed /home/ec2-user/ansible/servers inventory source with ini plugin
META: ran handlers
<10.0.5.232> ESTABLISH SSH CONNECTION FOR USER: ec2-user
<10.0.5.232> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/home/ec2-user/id.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ec2-user"' -o ConnectTimeout=10 -o ControlPath=/home/ec2-user/.ansible/cp/07f65e7d42 10.0.5.232 '/bin/sh -c '"'"'echo ~ec2-user && sleep 0'"'"''
<10.0.5.232> (255, b'', b'Authentication failed.\r\n')
10.0.5.232 | UNREACHABLE! => {
    **"changed": false,
    "msg": "Failed to connect to the host via ssh: Authentication failed.",
    "unreachable": true**
}

**Comment by praveensatti** [comment]
i'm connecting from baston/jumphost server to my private subnet servers, ssh port is opened in security groups.

**Comment by raviops99** [comment]
Hi Praveen 
This error  related you while doing ssh-key generation and ssh-copy-id  can you please verify these steps again

**Comment by chowdamramana** [comment]
copy the ssh key to ansible server and nodes as ansible user
