### ISSUE TITLE
Jfrog integration with Maven

### ISSUE THREAD

**Issue by sunnydevops** [QT-DevOps/DevOpsIssues#587]
I am trying to integrate Jfrog with Maven, but I am getting some error. when I am trying to deploy using  $ mvn deploy

<img width="947" alt="error" src="https://user-images.githubusercontent.com/31772526/63496483-a2d30400-c4df-11e9-9baa-14a5eeda7e51.PNG">
setting.xml file

<img width="533" alt="setting" src="https://user-images.githubusercontent.com/31772526/63496675-f5acbb80-c4df-11e9-88f2-60011ba6f92b.PNG">

**Comment by ghost** [comment]
give right ip address and credentilas

**Comment by bhaskardegala** [comment]
Make sure jfrog is running

**Comment by Jsuresh47** [comment]
jfrog running in aws instance or local system please check. if it is running in aws server instead of local host mention public ip of jfrog server.

**Comment by Pradipta1995** [comment]
integrate jfrog with Jenkins not with maven
