### ISSUE TITLE
Java:No such file or directory issues after setting varaible

### ISSUE THREAD

**Issue by thisiskrish1984** [QT-DevOps/DevOpsIssues#589]
HI.Installed jdk 8 on ubuntu 16 and set the java path environment variable and after exceuting source /etc/environment iam getting the below issues.
jenkins@ip-172-31-39-52:/home/ubuntu$ sudo update-alternatives --config java
There is only one alternative in link group java (providing /usr/bin/java): /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
Nothing to configure.
jenkins@ip-172-31-39-52:/home/ubuntu$ sudo vi /etc/environment
jenkins@ip-172-31-39-52:/home/ubuntu$ source /etc/environment
bash: JAVA_HOME:/usr/lib/jvm/java-8-openjdk-amd64: No such file or directory
bash: MAVEN_HOME:/usr/share/maven: No such file or directory
jenkins@ip-172-31-39-52:/home/ubuntu$

The previous ubuntu machine had no issues setting up environment variable.

**Comment by raviops99** [comment]
Hi Krish, 
While setting environment variables in /etc/profile have you set below path variable please  check once 
export PATH=$PATH:$HOME/bin:$JAVA_HOME/bin

**Comment by thisiskrish1984** [comment]
HI Raviops99.
Thanks.Usually I install jdk 8 and set the variable path alone.Now its working after export.Thanks again.
