### ISSUE TITLE
Ansible: jenkins not downloading at desired tomcat path "var/lib....."

### ISSUE THREAD

**Issue by itzpraveen18** [QT-DevOps/DevOpsIssues#59]

**Comment by itzpraveen18** [comment]
this is the issue which i  have i tried to fix the bug by upgarding python to > 3version by viewing the bug im the following but still am unable to get it 
and in below its installed tomcat succesfuully but jenkins.war is not downloading 
[ansible@ip-172-31-84-21 ~]$ ansible-playbook -K  -i invent/newinvent appserver.                                                                                                                yaml
SUDO password:

PLAY [webserver] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [172.31.92.221]

TASK [updating packages] *******************************************************
changed: [172.31.92.221]

TASK [installing tomcat 7 into ubunut 14.04] ***********************************
ok: [172.31.92.221]

TASK [downloading the jar jenkins file from webserver] *************************
fatal: [172.31.92.221]: FAILED! => {"changed": false, "msg": "Failed to validate                                                                                                                 the SSL certificate for tomcat.apache.org:443. Make sure your managed systems h                                                                                                                ave a valid CA certificate installed. If the website serving the url uses SNI yo                                                                                                                u need python >= 2.7.9 on your managed machine  (the python executable used (/us                                                                                                                r/bin/python) is version: 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]) or                                                                                                                 you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` pyt                                                                                                                hon modules to perform SNI verification in python >= 2.6. You can use validate_c                                                                                                                erts=False if you do not need to confirm the servers identity but this is unsafe                                                                                                                 and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/                                                                                                                ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.or                                                                                                                g, /etc/ansible. The exception msg was: hostname 'tomcat.apache.org' doesn't mat                                                                                                                ch either of '*.openoffice.org', 'openoffice.org'."}
        to retry, use: --limit @/home/ansible/appserver.retry

my playbook how i wrote :exaclty like this 

weberver playbook

---
  - hosts: webserver
    become: yes
    tasks:
    - name: "updating packages" 
      apt:
        update_cache: yes
      
    - name: "installing tomcat 7 into ubunut 14.04"
      apt:
        name: tomcat7
        state: present
          #for downloadin a file 

    - name: "downloading the jar jenkins file from webserver "
      get_url:
        dest: /var/lib/tomcat7/webapps/jenkins.war
        url: https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war
        
      

    - name: "restarting the machine " 
       service:
          name: tomcat7
          state: restarted  
    

inventory file:


[centos]
localhost
172.31.94.216

[ubuntu]
172.31.92.221

[webserver]
172.31.92.221

**Comment by shaikkhajaibrahim** [comment]
This is issue with ansible refer https://github.com/ansible/ansible/issues/33417

**Comment by itzpraveen18** [comment]
Thank you sir for your Response , I will fix it today
