### ISSUE TITLE
 EC2 with jenkins 

### ISSUE THREAD

**Issue by VenkateshYembuluru** [QT-DevOps/DevOpsIssues#590]
Hi good afternoon,

i installed JAVA and jenkins at EC2 instance  . 
but i am not able to open jenkins  at browser.
if anyone knows kindly guide..

**Comment by RahulAnita** [comment]
Please use "http://private ip:port number" to open jenkins

**Comment by anon-42** [comment]
More details needed man.
Make sure your security group have an inbound rule allowing port 8080.

**Comment by ghost** [comment]
please give detailed info

**Comment by bhaskardegala** [comment]
As anon said make sure 8080 was open in security group , java home is set , environment variables are reloaded and finally try to see and share the logs of Jenkins
