### ISSUE TITLE
Shopizer build success but Failed to Archive Artifacts from Jenkins

### ISSUE THREAD

**Issue by kishorejaan1** [QT-DevOps/DevOpsIssues#591]
[[1;34mINFO[m] 
[[1;34mINFO[m] shopizer ........................................... [1;32mSUCCESS[m [01:37 min]
[[1;34mINFO[m] sm-core-model ...................................... [1;32mSUCCESS[m [01:58 min]
[[1;34mINFO[m] sm-core-modules .................................... [1;32mSUCCESS[m [ 26.018 s]
[[1;34mINFO[m] sm-core ............................................ [1;32mSUCCESS[m [05:10 min]
[[1;34mINFO[m] sm-shop-model ...................................... [1;32mSUCCESS[m [  0.392 s]
[[1;34mINFO[m] sm-shop ............................................ [1;32mSUCCESS[m [02:58 min]
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] [1;32mBUILD SUCCESS[m
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
[[1;34mINFO[m] Total time:  13:22 min
[[1;34mINFO[m] Finished at: 2019-09-01T07:42:32Z
[[1;34mINFO[m] [1m------------------------------------------------------------------------[m
Archiving artifacts
‘target/shopizer*.jar’ doesn’t match anything: even ‘target’ doesn’t exist
ERROR: Step ‘Archive the artifacts’ failed: No artifacts found that match the file pattern "target/shopizer*.jar". Configuration error?
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Finished: FAILURE

+++++ >> How to open the application becz it didn't given any .jar file with the name of artifact..

And Deployed from Node using ]$ mvn deploy  [See the attached screenshot]

![image](https://user-images.githubusercontent.com/43911102/64073564-914ae280-ccbd-11e9-9c5f-a27eba371626.png)

**Comment by raviops99** [comment]
Hi Kishore, 
Can you  please share your pom.xml file
You have written

**Comment by kishorejaan1** [comment]
[pom.xml.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3564806/pom.xml.txt)

**Comment by raviops99** [comment]
Hi Kishore,
In your pom. xml staring from top around 7 to or 8 th line we have XML element call packaging inside that element  you mentioned pom just replace with jar
2. To store artificats in pom file you have mentioned nexus repo details did integrate Jenkins with nexus. 
3. pin file extension only pom.xml not pom.xml.txt
Please try step 1 and 3 and try to build once
Let us see will work or not

**Comment by kishorejaan1** [comment]
Yeah.. Thanks Ravi its working now.. But  I have attached original pom file only to you .. Its not allowing me to attach pom.xml here.. so that I just renamed it for ur reference..

**Comment by ghost** [comment]
please close issue
