### ISSUE TITLE
Hi, having issue while running openmrs and shopizer application in powershell. Would you please look into this once.. please find the error screen shot.

### ISSUE THREAD

**Issue by hanocc** [QT-DevOps/DevOpsIssues#592]
![openmrs](https://user-images.githubusercontent.com/51271895/64118576-8a070000-cdb5-11e9-9061-c5458dff86ef.PNG)

**Comment by ghost** [comment]
shophizer require db

**Comment by bhaskardegala** [comment]
Are you facing similar issues for other jar files ex:- spring petclinic

**Comment by hanocc** [comment]
Hi Bhaskar, I have issue with only OPENMRS and SHOPIZER....any suggestion from your side.? Thanks for your great support always. Appreciate you!

**Comment by raviops99** [comment]
Hi 
1.please run the same command 
Without ./ before .jarfile 
If you get same error 
2. Please share your pom.xml file

**Comment by shaikkhajaibrahim** [comment]
Use the right jar files
