### ISSUE TITLE
Unable to create New Node on Jenkins

### ISSUE THREAD

**Issue by kishorejaan1** [QT-DevOps/DevOpsIssues#593]
![image](https://user-images.githubusercontent.com/43911102/64188308-cad34780-ce8f-11e9-9de2-b26363fe6e4f.png)

![image](https://user-images.githubusercontent.com/43911102/64187850-f30e7680-ce8e-11e9-860c-db7e864295cf.png)

![image](https://user-images.githubusercontent.com/43911102/64188005-31a43100-ce8f-11e9-8812-5c37fb60c343.png)

![image](https://user-images.githubusercontent.com/43911102/64205150-f0bf1300-ceb4-11e9-9e53-53a550537086.png)

--> I have made my user as adiminstrator from " visudo " and passwordauthentication = Yes.
--> Even I tried to send Keys also from Jenkins to Node.. Even though am getting same error.. 
--> Installed mvn, jdk8, git also.

Could you please let me know did I miss anything...

**Comment by rajeshande430** [comment]
hi, try changing the HOST KEY VERIFICATION STRATEGEY : select none and try again, hopefully it would work

**Comment by Nara-Sagar7** [comment]
I am also facing the same issue, have you found any solution for this??

**Comment by rajeshande430** [comment]
guy, try changing the host key verification stratagey to non verifying verification strategy and use aws machine public ip, i am sure you will be able to get through the connection from master to node.

this worked for me

![err](https://user-images.githubusercontent.com/53960487/64241763-60fd8100-cf15-11e9-8fcd-e89fdacea07e.JPG)

**Comment by Nara-Sagar7** [comment]
Bro try manually trusted key verification strategy it's working for me.

![image](https://user-images.githubusercontent.com/54387478/64241965-51d10000-cf22-11e9-80c4-59035a5b2bab.png)

![image](https://user-images.githubusercontent.com/54387478/64242016-690fed80-cf22-11e9-8151-126626fca347.png)

![image](https://user-images.githubusercontent.com/54387478/64242041-74631900-cf22-11e9-84ad-d1dcbc36cb5d.png)

**Comment by rajeshande430** [comment]
Please post manual trusted key verification process here so that other can chekout including me

**Comment by kishorejaan1** [comment]
> Bro try manually trusted key verification strategy it's working for me.
> 
> ![image](https://user-images.githubusercontent.com/54387478/64241965-51d10000-cf22-11e9-80c4-59035a5b2bab.png)
> 
> ![image](https://user-images.githubusercontent.com/54387478/64242016-690fed80-cf22-11e9-8151-126626fca347.png)
> 
> ![image](https://user-images.githubusercontent.com/54387478/64242041-74631900-cf22-11e9-84ad-d1dcbc36cb5d.png)



Thanks a lot Bro... its working now If I choose manually trusted...

**Comment by kishorejaan1** [comment]
Thanks Guys... !!  its working now If I choose manually trusted... 

But the question is If I choose know host file verification Strategy , why its not working.. Did we miss anything.. it was working in classroom seems..

What was the logic behind there..

**Comment by kishorejaan1** [comment]
root@ip-172-31-39-24:~#
root@ip-172-31-39-24:~# cd /var/lib/jenkins/
root@ip-172-31-39-24:/var/lib/jenkins# cp -rp ~/.ssh/ /var/lib/jenkins/
root@ip-172-31-39-24:/var/lib/jenkins# sudo chown -Rh jenkins:jenkins /var/lib/jenkins/.ssh
root@ip-172-31-39-24:/var/lib/jenkins#
root@ip-172-31-39-24:/var/lib/jenkins# sudo chmod 600 /var/lib/jenkins/.ssh/{authorized_keys,id_rsa,known_hosts}
root@ip-172-31-39-24:/var/lib/jenkins#
root@ip-172-31-39-24:/var/lib/jenkins#


![image](https://user-images.githubusercontent.com/43911102/64247012-93b27400-cf2b-11e9-905d-5d482883abf0.png)

![image](https://user-images.githubusercontent.com/43911102/64247059-aaf16180-cf2b-11e9-9c9f-f51828ecb4b7.png)

**Comment by kishorejaan1** [comment]
The Perfect solution for this is for the option " known hosts file verification strategy " is below:

in My case JENKINS_HOME = /home/jenkins/

copy the know_hosts file in Master ~/.ssh/known_hosts to <JENKINS_HOME>/.ssh

]# cd ~
]# cd  .ssh
]# cp known_host  <JENKINS_HOME>/.ssh
]# cd /home/jenkins/.ssh/
jenkins@ip-172-31-42-138:~$ cd .ssh/
jenkins@ip-172-31-42-138:~/.ssh$ ls -ltrc
total 12
-rw-r--r-- 1 root root  403 Sep  6 13:30 id_rsa.pub
-rw------- 1 root root 1679 Sep  6 13:30 id_rsa
-rw-r--r-- 1 root root  444 Sep  6 13:33 known_hosts
jenkins@ip-172-31-42-138:~/.ssh$
jenkins@ip-172-31-42-138:~/.ssh$
jenkins@ip-172-31-42-138:~/.ssh$
jenkins@ip-172-31-42-138:~/.ssh$ pwd
/home/jenkins/.ssh
jenkins@ip-172-31-42-138:~/.ssh$
