### ISSUE TITLE
Error While adding node to the jenkins master

### ISSUE THREAD

**Issue by Nara-Sagar7** [QT-DevOps/DevOpsIssues#595]
![image](https://user-images.githubusercontent.com/54387478/64238490-23502680-cf1c-11e9-8dbc-6f9e100b96e8.png)

**Comment by Nara-Sagar7** [comment]
if the known host verification strategy is not working try with the other verification trategy options for this kind of errors.

![image](https://user-images.githubusercontent.com/54387478/64242271-e0458180-cf22-11e9-9cf5-3e2f048b0744.png)

**Comment by kishorejaan1** [comment]
![image](https://user-images.githubusercontent.com/43911102/64246687-e5a6ca00-cf2a-11e9-9110-8a31364805d3.png)
![image](https://user-images.githubusercontent.com/43911102/64246790-1981ef80-cf2b-11e9-907b-d151317926ef.png)


Followed the below steps on Master Node:

root@ip-172-31-39-24:~#
root@ip-172-31-39-24:~# cd /var/lib/jenkins/
root@ip-172-31-39-24:/var/lib/jenkins# cp -rp ~/.ssh/ /var/lib/jenkins/
root@ip-172-31-39-24:/var/lib/jenkins# sudo chown -Rh jenkins:jenkins /var/lib/jenkins/.ssh
root@ip-172-31-39-24:/var/lib/jenkins#
root@ip-172-31-39-24:/var/lib/jenkins# sudo chmod 600 /var/lib/jenkins/.ssh/{authorized_keys,id_rsa,known_hosts}
root@ip-172-31-39-24:/var/lib/jenkins#
root@ip-172-31-39-24:/var/lib/jenkins#
