### ISSUE TITLE
SonarQube Service not starting

### ISSUE THREAD

**Issue by srinivaspm** [QT-DevOps/DevOpsIssues#597]
sudo systemctl status sonar
● sonar.service - SonarQube service
   Loaded: loaded (/etc/systemd/system/sonar.service; enabled; vendor preset: enabled)
   **Active: failed (Result: start-limit-hit)** since Sat 2019-09-07 15:51:46 IST; 1h 2min ago

Sep 07 15:51:45 mint-VirtualBox systemd[1]: Started SonarQube service.
Sep 07 15:51:46 mint-VirtualBox systemd[1]: sonar.service: Service hold-off time over, scheduling 
Sep 07 15:51:46 mint-VirtualBox systemd[1]: sonar.service: Scheduled restart job, restart counter 
Sep 07 15:51:46 mint-VirtualBox systemd[1]: Stopped SonarQube service.
Sep 07 15:51:46 mint-VirtualBox systemd[1]: **sonar.service: Start request repeated too quickly.**
Sep 07 15:51:46 mint-VirtualBox systemd[1]: sonar.service: Failed with result 'start-limit-hit'.
Sep 07 15:51:46 mint-VirtualBox systemd[1]: Failed to start SonarQube service.

**Comment by srinivaspm** [comment]
I have installed sonarqube in Virtualbox, Trying to start the service. But it did not.

**Comment by srmanikanta** [comment]
#sonarqube requires the below prerequisites if  you done already please close the issue
The SonarQube server requires at least 2GB of RAM to run efficiently and 1GB of free RAM for the OS.

**Comment by ijazm123** [comment]
root@jenkins:~# free -mh
              total        used        free      shared  buff/cache   available
Mem:           3.6G        772M        2.5G        5.3M        380M        2.6G
Swap:            0B          0B          0B

**Comment by swapnilpotnis** [comment]
@srmanikanta : i am facing the same issue. I have a free RAM of 2GB as well yet the issue persists. Can you please help??

**Comment by sailokesh-heeddata** [comment]
@srinivaspm you service file need to be with the **Execstart=path/sonar.sh console** and you need to give your ip with http://<ipaddress>:9000.
