### ISSUE TITLE
Hi, Can anyone help, as I am Unable to Build Shopizer Application with Jenkins

### ISSUE THREAD

**Issue by sandeepmeshram** [QT-DevOps/DevOpsIssues#598]
Below are the Steps that I have Configured in Jenkins,but still I am getting timeout issue
So Can anyone please help how Do I resolve this issue, In Advance Thanks for help.
And Attached is the screenshot
1) I have Created New Job of Free Style Project.
2) I have Configured Source Code Management as Git with below URL 
https://github.com/shopizer-ecommerce/shopizer.git   , So this URL is copied from Shopizer Git Hub.
3) Branch is Master
4) Build is   clean Package
Note:- My Jenkins Server is on Windows

![JenkinError](https://user-images.githubusercontent.com/53405425/64478660-fa07f280-d1c8-11e9-8d36-2d258aceca0f.PNG)

**Comment by vkatukam** [comment]
please provide credentials to get access.

**Comment by ghost** [comment]
Shopizer  not cloning  into your localrepo
can  you try in invoke shell
git clone url

**Comment by raviops99** [comment]
Hi Sandeep,
1.go to job and configure page
2. Under source code management git - additional behaviour add behaviour " wipe out repository & force clone"
3. Save then build

**Comment by sandeepmeshram** [comment]
> Shopizer not cloning into your localrepo
> can you try in invoke shell
> git clone url

Hi Naresh, thanks for help, I have tried with invoke shell and it worked out and build the shopizer application.
So Closing this issue.
