### ISSUE TITLE
sonarqube error in jenkins

### ISSUE THREAD

**Issue by satyamuralidhar** [QT-DevOps/DevOpsIssues#6]
sir once i click in sonarqube logo its not showing sonarcube page 
mouse button can be appeared but not showing clicking option

its refreshing the page

![error on sonarqube](https://user-images.githubusercontent.com/38804803/40513502-964723ec-5fc3-11e8-9c9a-c4017c9fe26e.jpg)

**Comment by shaikkhajaibrahim** [comment]
Can you also add the sonar qube configuration steps which you have done & also jenkins job configuration

**Comment by satyamuralidhar** [comment]
sir iam also configured sonarcube another server and it also adding on manage jenkins configuration

ipaddress: 9000  working

but its not working  sonarcube

**Comment by vijaybhaskarreddyy** [comment]
while job configuration you have given sonarqube details. add those configuration details or add screen short.

**Comment by gvharikrishna** [comment]
My game of life build in Jenkins keep failing, throwing the below error when i run the jenkins job everytime.
![image](https://user-images.githubusercontent.com/28618322/40593769-48215e6c-6248-11e8-867c-0ff6e2cd06ac.png)
My environment consist of a single jenkin server installed sonarqube on port 9000

**followed the below steps to integrate sonarqube jenkins**
Log into Jenkins as an administrator and go to Manage Jenkins > Configure System: 
Scroll down to the SonarQube configuration section, click on Add SonarQube
Manage Jenkins > Global Tool Configuration
SonarQube Scanner configuration section and click on Added SonarQube Scanner.
**Job configuration**
![image](https://user-images.githubusercontent.com/28618322/40593844-d2c27f38-6248-11e8-8107-a8b785844782.png)

could you please help me to integrate the sonarqube and fix the above error

**Comment by vijaybhaskarreddyy** [comment]
In build steps you have to write analysis properties please cross  check once

**Comment by satyamuralidhar** [comment]
problem has been solved


On Tue, May 29, 2018 at 6:48 AM, vijaybhaskarreddy <notifications@github.com
