### ISSUE TITLE
Add multiple subnets to the existing virtual net

### ISSUE THREAD

**Issue by satyakuppala** [QT-DevOps/DevOpsIssues#60]
Hi Sir,
i am trying to add the subnet to the existing vnet but the new subnet is replaced with old subnet 

the command i used is 
az network vnet create -g refcli -n jiovnet --address-prefix 10.0.0.0/16 --subnet-name webtier --subnet-prefix 10.0.0.0/24 --subnet-name activedirectorytier --subnet-prefix 10.0.1.0/24

it is creating only activedirectorytier

**Comment by rameshm78** [comment]
Syntax of your command appears to be incorrect. I could be wrong,
While creating the vnet, you can add only one subnet. As is the case while using the UI.

Sample code is:
az network vnet create -g MyResourceGroup -n MyVnet --address-prefix 10.0.0.0/16 --subnet-name MySubnet --subnet-prefix 10.0.0.0/24

All additional Subnets need to be added using the "az network vnet subnet create" command

**Comment by satyakuppala** [comment]
Hi
Thank you for the reply 
can you please give me some examples for adding the additional subnet for the existing vnet

**Comment by rameshm78** [comment]
Hi Satya,
Just like our instructor keeps telling us, Google for "az network vnet subnet create", take a result from Microsoft docs, click on the command in the list. It will take you to the section where usage and examples are given.
I don't have any examples written down at the moment. I just build by loking at the examples from that page.

Reards
Ramesh

**Comment by shaikkhajaibrahim** [comment]
az network vnet create takes only one subnet, you are trying to give two subnets in same command.

**Comment by manikantagaddam** [comment]
Closed ?
