### ISSUE TITLE
jenkins Nexus integration failing on timeout

### ISSUE THREAD

**Issue by Rameshdutt80** [QT-DevOps/DevOpsIssues#600]
installed nexus on windows7 

![image](https://user-images.githubusercontent.com/37854691/64768078-781c1e80-d566-11e9-957a-689f4b70063c.png)

in AWS ec2 jenkins is running, while integrating with nexus getting below error
![image](https://user-images.githubusercontent.com/37854691/64768579-566f6700-d567-11e9-9232-a30deaa93a15.png)

I thought it might be private and public ip conflict
but i did set up public ip address in windows
any Suggestion on this

**Comment by shaikkhajaibrahim** [comment]
Can you elaborate on where is jenkins & nginx and is it possible to ping from jenkins to nginx

**Comment by Rameshdutt80** [comment]
issue got resolved
