### ISSUE TITLE
packer Failed during calling the playbook

### ISSUE THREAD

**Issue by kishorejaan1** [QT-DevOps/DevOpsIssues#601]
amazon-ebs: Setting up python-cryptography (2.1.4-1ubuntu1.3) ...
    amazon-ebs: Setting up python-paramiko (2.0.0-1ubuntu1.2) ...
    amazon-ebs: Setting up ansible (2.8.4-1ppa~bionic) ...
==> amazon-ebs: --2019-09-12 15:16:32--  https://kishorepack.s3.ap-south-1.amazonaws.com/i_playbook.yml
==> amazon-ebs: Resolving kishorepack.s3.ap-south-1.amazonaws.com (kishorepack.s3.ap-south-1.amazonaws.com)... 52.219.66.95
==> amazon-ebs: Connecting to kishorepack.s3.ap-south-1.amazonaws.com (kishorepack.s3.ap-south-1.amazonaws.com)|52.219.66.95|:443... connected.
==> amazon-ebs: HTTP request sent, awaiting response... 200 OK
==> amazon-ebs: Length: 341 [binary/octet-stream]
==> amazon-ebs: Saving to: ‘i_playbook.yml’
    amazon-ebs: Running build......
==> amazon-ebs:
==> amazon-ebs:      0K                                                       100% 15.2M=0s
==> amazon-ebs:
==> amazon-ebs: 2019-09-12 15:16:32 (15.2 MB/s) - ‘i_playbook.yml’ saved [341/341]
==> amazon-ebs:
==> amazon-ebs:  [WARNING]: provided hosts list is empty, only localhost is available. Note
==> amazon-ebs: that the implicit localhost does not match 'all'
==> amazon-ebs: ERROR! Syntax Error while loading YAML.
==> amazon-ebs:   did not find expected key
==> amazon-ebs:
==> amazon-ebs: The error appears to be in '/home/ubuntu/i_playbook.yml': line 6, column 3, but may
==> amazon-ebs: be elsewhere in the file depending on the exact syntax problem.
==> amazon-ebs:
==> amazon-ebs: The offending line appears to be:
==> amazon-ebs:
==> amazon-ebs:
==> amazon-ebs:   - tasks:
==> amazon-ebs:   ^ here
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Script exited with non-zero exit status: 4.Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Script exited with non-zero exit status: 4.Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
root@ip-172-31-11-173:~/packers_lab#
root@ip-172-31-11-173:~/packers_lab#

**Comment by kishorejaan1** [comment]
1)---packerbuild.sh
{

  "builders": [
  {
	  "type": "amazon-ebs",
	  "ami_name": "packer_image",
	  "access_key": "<hide by kishore>",
	  "secret_key": "<hide by kishore>",
	  "source_ami": "ami-0a74bfeb190bd404f",
	  "instance_type": "t2.micro",
	  "region": "ap-south-1",
	  "ami_name": "packer_image"
  }]
  "provisioners": [
  {
	  	  "type": "shell",
  		  "script": "provision.sh"
  } ]
  
}



2)--- provision.sh


#!/bin/bash
set -e
#provision.sh
 sudo apt-get update
 echo "apt-get update done."
 sudo apt install software-properties-common
 sudo apt-add-repository ppa:ansible/ansible
 sudo apt-get update
 sudo apt-get install ansible -y
 sudo wget "https://sampleforansible.s3.ap-south-1.amazonaws.com/i_playbook.yml"
 echo "Running build......"
 sudo ansible-playbook i_playbook.yml


3) --- i_playbook.yml


![image](https://user-images.githubusercontent.com/43911102/64902326-f7bf0000-d6c2-11e9-9ba2-6b1e90a8b10b.png)

**Comment by ghost** [comment]
do manually first
