### ISSUE TITLE
no berksfile or berksfile.lock found

### ISSUE THREAD

**Issue by khksairaj** [QT-DevOps/DevOpsIssues#602]
I am trying to execute berks install & berks upload in chef.

But i am getting an error "no berksfile or berksfile.lock found"

give me the better solution please.

Thank you.

**Comment by bhaskardegala** [comment]
Hi khksairaj while creating cookbook have you given the argument -b if you have not done that you will not be having Berk file

**Comment by khksairaj** [comment]
> Hi khksairaj while creating cookbook have you given the argument -b if you have not done that you will not be having Berk file

Hey thanks, its working now.

But first time while running chef, i have not passed any such argument....before few months. Is there any changes happen recently ?
