### ISSUE TITLE
Hi, While uploading the cookbook in chef server,  i am getting the below error

### ISSUE THREAD

**Issue by dtutika** [QT-DevOps/DevOpsIssues#603]
PS H:\Chef\chef-repo\cookbooks\my-second-cookbook> berks upload
E, [2019-09-17T07:55:14.190066 #11840] ERROR -- : Net::HTTPServerException: 401 "Unauthorized"
E, [2019-09-17T07:55:14.191258 #11840] ERROR -- : C:/opscode/chefdk/embedded/lib/ruby/2.6.0/net/http/response.rb:122:in `error!'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20-universal-mingw32/lib/chef/http.rb:152:in `request'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20-universal-mingw32/lib/chef/http.rb:131:in `post'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20-universal-mingw32/lib/chef/cookbook_uploader.rb:59:in `upload_cookbooks'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.0.8/lib/berkshelf/uploader.rb:79:in `block (2 levels) in upload'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.0.8/lib/berkshelf/uploader.rb:61:in `map'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.0.8/lib/berkshelf/uploader.rb:61:in `block in upload'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.0.8/lib/berkshelf/ridley_compat.rb:56:in `new_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.0.8/lib/berkshelf.rb:172:in `ridley_connection'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.0.8/lib/berkshelf/uploader.rb:55:in `upload'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.0.8/lib/berkshelf/uploader.rb:42:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.0.8/lib/berkshelf/berksfile.rb:580:in `upload'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.0.8/lib/berkshelf/cli.rb:195:in `upload'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.0.8/lib/berkshelf/cli.rb:47:in `dispatch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.0.8/lib/berkshelf/cli.rb:23:in `execute!'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/berkshelf-7.0.8/bin/berks:5:in `<top (required)>'
C:/opscode/chefdk/bin/berks:363:in `load'
C:/opscode/chefdk/bin/berks:363:in `<main>'
There was an error connecting to the Chef Server

**Comment by bhaskardegala** [comment]
I think you missed your server pem file
