### ISSUE TITLE
Terraform Issue

### ISSUE THREAD

**Issue by kirthip1983** [QT-DevOps/DevOpsIssues#604]
provider "aws" {
  region "ap-south-1"
  access_key ""
  secret_key ""
}
resource "aws_instance" MyWebServer {
  ami "ami-0cb0e70f44e1a4bb5"
  instance_type "t2.micro"
}

C:\ProgramData\chocolatey\lib\terraform
C:\Users\Kirthi\Desktop\Devops/sample1.tf 

[Error.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3624504/Error.txt)

**Comment by shaikkhajaibrahim** [comment]
provider aws {
   region = ""
}

you have written wrong syntax use =
________________________________

**Comment by bhaskardegala** [comment]
Hi kirthip

Hope your issue was resolved please update with solution and close the issue

**Comment by kirthip1983** [comment]
Hi, yes the issue is resolved...thankyou
