### ISSUE TITLE
terraform connection issue

### ISSUE THREAD

**Issue by saipranay54** [QT-DevOps/DevOpsIssues#605]
while i am validating the code i am facing the below issue, i think this is because of host what should i enter in host and how to find address of the resource
code:provider "aws" {
     region = "us-east-1"
     access_key = "
     secret_key = "" 
}
resource "aws_instance" "web" {
    instance_type = "t2.micro"
    ami = "ami-0cfee17793b08a293"
    key_name = "vpclearn"
    security_groups = ["launch-wizard-1"]

    connection {
        type = "ssh"
        user = "ec2-user"
        private_key = "${file("./vpclearn.pem")}"
        host = ""
    }

provisioner "remote-exec" {
    inline = ["sudo yum install tomcat -y","sudo service tomcat start"]
}
}
![terraform issue](https://user-images.githubusercontent.com/50736120/65143224-0cd4bf80-da32-11e9-9d14-73d20a4e838b.png)

**Comment by kp1310** [comment]
Hello,

You should have this line in your code to work correctly under connection

host        = "${aws_instance.web1.public_ip}"

aws_instance is the resource you have define.

so in here you have define resource as web so your host should be:

host        = "${aws_instance.web.public_ip}"

it should solve the same.

please to let me know if this resolves your issue.

Thanks
Kp
