### ISSUE TITLE
Conectivity issue on Jenkins node

### ISSUE THREAD

**Issue by Vineet-Maloo** [QT-DevOps/DevOpsIssues#607]
Hello

I am facing the connectivity issue while configuring the jenkins node.

Kindly see the screenshot 
![jenkins](https://user-images.githubusercontent.com/55178549/65259109-c2cb0700-db21-11e9-9b96-bcc6573e6921.PNG)
![error_log](https://user-images.githubusercontent.com/55178549/65259123-cc546f00-db21-11e9-9cda-a86735a12880.PNG)

**Comment by bhaskardegala** [comment]
Once try using public ip at once and make sure you have established password less SSH connection between master and node

**Comment by vkatukam** [comment]
I also faced same issue, but I used "Manually provided key verification strategy" and provided SSH Key then am able to create agent successfully. 

Please let me know if anyone succeded with "Known hosts file verification strategy" option and share your solution.

**Comment by Vineet-Maloo** [comment]
It worked on selecting 'Non verifying Verification strategy' for Host key verification.

Thank you
