### ISSUE TITLE
Ansible playbook error 

### ISSUE THREAD

**Issue by Nara-Sagar7** [QT-DevOps/DevOpsIssues#608]
please find the details iam getting this error but unable to identify why happening.
ansible@ansible-master:~/tomcat-deploy$ ansible-playbook -vvv newtomcat8.yml 
ansible-playbook 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.15+ (default, Jul  9 2019, 16:51:35) [GCC 7.4.0]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass it's verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
ERROR! A malformed block was encountered while loading handlers
The error appears to be in '/home/ansible/tomcat-deploy/newtomcat8.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
---
- hosts: all
  ^ here
My playbook.

[tomcat.txt.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3635041/tomcat.txt.txt)

**Comment by mani5a3** [comment]
please post the yaml file

**Comment by Nara-Sagar7** [comment]
i have fixed this issue it was the typo error in the yaml file.
