### ISSUE TITLE
tomcat login error

### ISSUE THREAD

**Issue by saipranay54** [QT-DevOps/DevOpsIssues#609]
hi,
after installing the tomcat i tried to login the manager app after entering the login details,it is not taking my user name and password after setting up the in the usersname.xml file
please find the below screen shots
thank you,
![login error](https://user-images.githubusercontent.com/50736120/65372129-903c1e00-dc89-11e9-9f15-da30ed8e24ea.png)
![userxml file](https://user-images.githubusercontent.com/50736120/65372132-992cef80-dc89-11e9-8e7c-422cf4f9dd60.png)

**Comment by ghost** [comment]
check user.xml once

**Comment by bhaskardegala** [comment]
Hi saipranay 
Have you copied everything from the previous file if you miss a space or syntax this will definitely screw your file and you will not be able to login and even once check context file in manager and host manager file

**Comment by raviops99** [comment]
Hi Sai,

in your user.xml file remove all the last four lines

add these below lines and save the file

-->
<role rolename="manager-gui"/>
<user username="tomcat" password="tomcat" roles="manager-gui,manager-script"/>

after that restart tomcat.

try with username and password with tomcat.

hope it will work

**Comment by raviops99** [comment]
in your user.xml file remove all the last four lines

add these below lines and save the file

-->
<role rolename="manager-gui"/>
<user username="tomcat" password="tomcat" roles="manager-gui,manager-script"/>

after that restart tomcat.

try with username and password with tomcat.

hope it will work

**Comment by raviops99** [comment]
-->
<role rolename="manager-gui"/>
<user username="tomcat" password="tomcat" roles="manager-gui,manager-script"/>

**Comment by raviops99** [comment]
![Screenshot_2019-09-23-23-30-00-90](https://user-images.githubusercontent.com/54374332/65486479-2c506a00-dec2-11e9-945b-78a51f94e0fc.png)

**Comment by raviops99** [comment]
your user.xml look like above add password tomcat and follow above steps

**Comment by saipranay54** [comment]
I will try bro thanks

**Comment by saipranay54** [comment]
after i followed your steps i got the below error
![error](https://user-images.githubusercontent.com/50736120/65585200-b6bacb80-df9f-11e9-9e41-171ba130605c.png)
![userxml file](https://user-images.githubusercontent.com/50736120/65585296-dce06b80-df9f-11e9-8808-c66e2565333e.png)

**Comment by raviops99** [comment]
Hi Sai, 
No need to add Tomcat user line in the user.xml file only last three lines you need to add username place give tomcat and password place give tomcat and save the file and restart tomact after logging from hi you need to try username password as tomcat ok please try this

**Comment by raviops99** [comment]
Last 3 lines of I have sent screen shot of above

**Comment by ghost** [comment]
please follow this link
https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-8-on-ubuntu-16-04

**Comment by saipranay54** [comment]
hi naresh/mani,
issue got fixed yesterdat by mani thanks
