### ISSUE TITLE
PowerShell DSC script fails to create MOF file

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#61]
Hi,

I tried running the helloworldconfig.ps1 file on both my Win 7 system and Win 10 virtual system using PowerShell 5.1 as Administrator, but it waits a long time and fails with the following error:
The script failed due to call depth overflow.
    + CategoryInfo          : InvalidOperation: (0:Int32) [], ParentContainsErrorRe 
   cordException
    + FullyQualifiedErrorId : CallDepthOverflow

![image](https://user-images.githubusercontent.com/40449948/42750118-a6a95c50-8903-11e8-9128-1ab843e44461.png)

Can anyone please help me out?

Regards
Ramesh

**Comment by Imalli5253** [comment]
Please share the Powershell code..

**Comment by rameshm78** [comment]
Configuration helloworldconfig {

    Import-DscResource -ModuleName PsDesiredStateConfiguration

    Node localhost {
        File hellofile {
            DestinationPath = "D:\temp\test.txt"
            Ensure = 'Present'
            Contents = "Test"
        }
    }
}
.\helloworldconfig

**Comment by rameshm78** [comment]
And I can see the problem.
I removed the .\ and it worked.
