### ISSUE TITLE
Unable to pass the parameters in Jenkins

### ISSUE THREAD

**Issue by Vineet-Maloo** [QT-DevOps/DevOpsIssues#610]
Hi

I am facing the below issue while passing the parameters.

![image](https://user-images.githubusercontent.com/55178549/65412014-f3ee5480-de0b-11e9-96c9-a060a0d4fcdc.png)

![image](https://user-images.githubusercontent.com/55178549/65412040-0d8f9c00-de0c-11e9-8881-13e50dfe114c.png)

![image](https://user-images.githubusercontent.com/55178549/65412122-331ca580-de0c-11e9-94d8-07f1847861a9.png)

**Comment by raviops99** [comment]
Hi binder, 
Can you please post have you installed  Jenkins on windows or Linux. 
Can you please try git URL another application like game of life once

**Comment by raviops99** [comment]
Sorry for typo vineet

**Comment by Vineet-Maloo** [comment]
Hi Ravi

I am using Jenkins on Linux. I tried using game of life repository, same error.

**Comment by raviops99** [comment]
Hi Vineet,
In your mentioned screen shot
Branch specifer  give $branch_neme (or) ${branch_name}
Remove */
Please try now hope it will work.
