### ISSUE TITLE
Facing problem installing Java and Tomcat Terraform

### ISSUE THREAD

**Issue by karthikreddy28** [QT-DevOps/DevOpsIssues#611]
Hi,
I am Not able to install Java and Tomcat using terraform code which was explained on 20th september. I was able to create ec2 instance using code but facing the below issue when trying this command Terraform apply. Please help me with this issue.

![terraform](https://user-images.githubusercontent.com/55773317/65563570-a22ef280-df0f-11e9-8372-1cd5c934b1cb.PNG)

**Comment by ghost** [comment]
what is your os?
are you done manual steps before writing terraform file?
share terraform file

**Comment by karthikreddy28** [comment]
Yes i was manually able to install on ec2 instance.

My OS is windows 10.

Please find my terraform files attached

Thank you

**Comment by karthikreddy28** [comment]
Please find my terraform folder attached
 openmrs-multiteanant.zip
<https://drive.google.com/file/d/1awrFy7oQNhNetoFFoTOHRwWr7JVWWOUE/view?usp=drive_web>

**Comment by karthikreddy28** [comment]
I was able to sort out the issue.
