### ISSUE TITLE
Unable to Open Ngnix with port 8045

### ISSUE THREAD

**Issue by vinodh2020** [QT-DevOps/DevOpsIssues#613]
Hello All,
            I have created container on Ngnix latest image and able to see container runs well. But when i try to open ngnix with 8045 not able to open .

please help me on this issue.

Commands used : 
[appsoa@alpdcutildev01 ~]$ docker run -d -i -t -p 8045:8080 nginx:latest /bin/bash

c75947b6ed40e94cb0ed0aa692a15f58a09970d7eb29fb669e1add54efed9312

 

 

[appsoa@alpdcutildev01 ~]$ docker ps -a

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                   PORTS                                              NAMES

c75947b6ed40        nginx:latest        "/bin/bash"              9 seconds ago       Up 8 seconds             80/tcp, 443/tcp, 0.0.0.0:8045->8080/tcp            drunk_ptolemy

 

 

 

 

[appsoa@alpdcutildev01 ~]$  ip addr show

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN

    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00

    inet 127.0.0.1/8 scope host lo

    inet6 ::1/128 scope host

       valid_lft forever preferred_lft forever

2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000

    link/ether 00:21:f6:00:00:3f brd ff:ff:ff:ff:ff:ff

    inet 10.93.202.92/23 brd 10.93.203.255 scope global eth0

    inet6 fe80::221:f6ff:fe00:3f/64 scope link

       valid_lft forever preferred_lft forever

3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000

    link/ether 00:21:f6:00:00:9c brd ff:ff:ff:ff:ff:ff

    inet 10.93.70.93/23 brd 10.93.71.255 scope global eth1

    inet6 fe80::221:f6ff:fe00:9c/64 scope link

       valid_lft forever preferred_lft forever

4: br-6444a35681ec: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP

    link/ether 02:42:f2:29:8c:e5 brd ff:ff:ff:ff:ff:ff

    inet 172.18.0.1/16 scope global br-6444a35681ec

    inet6 fe80::42:f2ff:fe29:8ce5/64 scope link

       valid_lft forever preferred_lft forever

5: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP

    link/ether 02:42:0c:8f:5a:46 brd ff:ff:ff:ff:ff:ff

    inet 172.17.0.1/16 scope global docker0

    inet6 fe80::42:cff:fe8f:5a46/64 scope link

       valid_lft forever preferred_lft forever

427: vethec18d1d: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6444a35681ec state UP

    link/ether 62:4d:07:39:bd:68 brd ff:ff:ff:ff:ff:ff

    inet6 fe80::604d:7ff:fe39:bd68/64 scope link

       valid_lft forever preferred_lft forever

429: vethecf6614: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6444a35681ec state UP

    link/ether 42:74:e1:94:67:80 brd ff:ff:ff:ff:ff:ff

    inet6 fe80::4074:e1ff:fe94:6780/64 scope link

       valid_lft forever preferred_lft forever

431: veth0a008fc: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6444a35681ec state UP

    link/ether 0e:61:9c:88:64:76 brd ff:ff:ff:ff:ff:ff

    inet6 fe80::c61:9cff:fe88:6476/64 scope link

       valid_lft forever preferred_lft forever

433: vethe9094f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-6444a35681ec state UP

    link/ether aa:ad:3e:07:d4:46 brd ff:ff:ff:ff:ff:ff

    inet6 fe80::a8ad:3eff:fe07:d446/64 scope link

       valid_lft forever preferred_lft forever

441: vethb16baf0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP

    link/ether 0e:04:86:a8:10:a3 brd ff:ff:ff:ff:ff:ff

    inet6 fe80::c04:86ff:fea8:10a3/64 scope link

       valid_lft forever preferred_lft forever

[appsoa@alpdcutildev01 ~]$ ps -ef | grep 443

appsoa   19403 10186  0 12:05 pts/4    00:00:00 grep 443

root     19914 20345  0 Sep13 ?        00:03:58 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 443 -container-ip 172.18.0.6 -container-port 443

![image](https://user-images.githubusercontent.com/47656950/65713467-e14b7800-e0b6-11e9-9528-0580cf632fe2.png)

Thanks,
Vinodh

Thanks,
Vinodh

**Comment by vinodh2020** [comment]
When i see container status , looks like command column shows 

nginx -g 'deamon of ..'

May i know if any one have idea

**Comment by srmanikanta** [comment]
nginx is a webserver it is running on port  80 so try this command
 docker run -d -it -p 80:80 nginx:latest
again run nginx try this
 docker run -d -it -p 81:80 nginx:latest

**Comment by srmanikanta** [comment]
if you got the answer pleae close the issue
