### ISSUE TITLE
Docker: Game of Life issue

### ISSUE THREAD

**Issue by kp1310** [QT-DevOps/DevOpsIssues#615]
Hello,

I've created a Docker file with below information:

FROM ubuntu:18.04
LABEL Author="KP"
LABEL Org="QT"
RUN apt-get update && apt-get install openjdk-8-jdk -y && apt-get install tomcat8 -y
ADD https://qt-s3-new-testing.s3-us-west-2.amazonaws.com/gameoflife.war //root/dockerfile

Now after that i build the docker image with 
below command:
docker image build -t gol:ubuntu .

after that i ran the docker container:
docker container run -p 8088:8080 -d gol:ubuntu
it created below:
742e2a16cc99f9b2b3b7e359cc228b12d7780c66c5b8138866e63ed3cb5b176e

after that just checked if container is created

bash-5.0# docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

NO OUTPUT SHOWN...

then i checked if container service running, but the status is EXITED

bash-5.0# docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                        PORTS               NAMES
f93483029768        gol:ubuntu          "/bin/bash"              18 minutes ago      Exited (0) 18 minutes ago                         trusting_hofstadter
7fa8d1e79cb7        49fe9dd5115c        "/bin/sh -c 'apt-get…"   32 minutes ago      Exited (100) 32 minutes ago                       strange_hodgkin
605ead320cef        49fe9dd5115c        "/bin/sh -c 'apt-get…"   38 minutes ago      Exited (1) 33 minutes ago                         inspiring_galois

So not sure how to run this specific application or what's next, Although i am checking also from my side about the same.

**Comment by tandrarajesh** [comment]
I think you missed CMD command.

**Comment by rajeshande430** [comment]
guys can someone review whats wrong in this docker file, i am getting tomcat page but gameoflife file is not copying to the webapps folder

FROM tomcat
ADD https://qt-s3-new-testing.s3-us-west-2.amazonaws.com/gameoflife.war /gameoflife.war
EXPOSE 8080
CMD ["cp", "/gameoflife.war", "/usr/local/tomcat/webapps"]

**Comment by kp1310** [comment]
I did but now i am getting below issue while executing docker container run command:

root@ip-172-31-32-123:/home/ubuntu/docker# docker container run -p 8081:8082 -d sp:clinic .
5c8ebeff8751845f674b6c85cd82e6d59c216e620b24adce61b5857495bafc07
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \".\": executable file not found in $PATH": unknown.

**Comment by rajeshande430** [comment]
FROM tomcat
ADD https://qt-s3-new-testing.s3-us-west-2.amazonaws.com/gameoflife.war /usr/local/tomcat/webapps/gameoflife.war
EXPOSE 8080
CMD ["catalina.sh", "run"]

this worked for me, try out if useful

**Comment by chowdamramana** [comment]
you used FROM as ubuntu
FROM is base image, so use tomcat as base image for war files

**Comment by kp1310** [comment]
Thanks, @rajeshande430 @chowdamramana i tried the same and now i can see that the docker is running.
now how to access the application Game of Life from local host?
also if any info about the error:

813924127f372b2c31f521e1834b33ed32f924ab940b043b91b8159c5839a431
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \".\":
 executable file not found in $PATH": unknown.


Earlier i had this issue fixed by adding the same by adding my home directory in the PATH environment variable.
it worked once but now again when i try to do the same it doesn't.

Thanks

**Comment by kp1310** [comment]
@rajeshande430 @chowdamramana issue resolved and now i am able to access the website.
proceeding with the closure of the issue.

thanks
Kuldeep
