### ISSUE TITLE
docker nginx issue

### ISSUE THREAD

**Issue by tabrez78** [QT-DevOps/DevOpsIssues#616]
trying to deploy a website on nginx on docker with the following code
FROM nginx
MAINTAINER tabrez
ADD index.html /var/www/html/index.html
CMD ["nginx", "-g", "daemon off;"]

but index.html is not copied

**Comment by rajeshande430** [comment]
please use COPY instead of ADD

**Comment by tabrez78** [comment]
index.html is copied in the /var/www/html/index.html
but using browser cannot see the application 
192.168.0.181:32777
application is running on port 32777
i can only see nginx welcome page

**Comment by tabrez78** [comment]
FROM nginx
MAINTAINER tabrez
COPY Metronic/* /usr/share/nginx/html/*
CMD ["nginx", "-g", "daemon off;"]


Step 1/4 : FROM nginx
 ---> f949e7d76d63
Step 2/4 : MAINTAINER tabrez
 ---> Using cache
 ---> 12be5c6bd079
Step 3/4 : COPY Metronic/* /usr/share/nginx/html/*
When using COPY with more than one source file, the destination must be a directory and end with a /

can see the page not completely
i think i was copying index.html into wrong location i.e /var/www/html/index.html
Now atleast i am getting some thing on the page but its not the actual page of the website

Step 3/4 : COPY Metronic/* /usr/share/nginx/html/*
When using COPY with more than one source file, the destination must be a directory and end with a /

what do you mean by this ,please assist me where i am going wrong.

thanks

**Comment by rajeshande430** [comment]
COPY Metronic/* /usr/share/nginx/html/
When using COPY with more than one source file, the destination must be a directory and end with a /

Step 3/4 : COPY Metronic/* /usr/share/nginx/html/
When using COPY with more than one source file, the destination must be a directory and end with a /

try the above it will work, i have removed the *s ..

**Comment by tabrez78** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/47026101/65838715-6bab0a80-e349-11e9-81e4-ab71702b3b8f.png)
this is my screen shot

**Comment by tabrez78** [comment]
can we run a website on docker container

**Comment by RahulAnita** [comment]
yes

**Comment by tabrez78** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/47026101/66012472-bb84ff80-e50a-11e9-9300-2707f1848bc6.png)
![Screenshot (6)](https://user-images.githubusercontent.com/47026101/66012517-e2dbcc80-e50a-11e9-92c9-2e96a1e5a73b.png)
![Screenshot (7)](https://user-images.githubusercontent.com/47026101/66012520-e7a08080-e50a-11e9-9a45-b5961da7c266.png)
![Screenshot (8)](https://user-images.githubusercontent.com/47026101/66012522-ea9b7100-e50a-11e9-924c-244309004b40.png)
![Screenshot (9)](https://user-images.githubusercontent.com/47026101/66012537-fb4be700-e50a-11e9-8d1a-d615e840b7a2.png)

this is the output of deploying the website on nginx

**Comment by shaikkhajaibrahim** [comment]
Share your code

**Comment by tabrez78** [comment]
FROM nginx
MAINTAINER tabrez
COPY Metronic/* /usr/share/nginx/html/*
CMD ["nginx", "-g", "daemon off;"]



this is  the docker file i was using.i think i have shared everything in the screen shots uploaded in the issue and one more thing how do i know the public default location of www loction . is it/var/www/htm or /usr/share/nginx/html

**Comment by tabrez78** [comment]
http://192.168.0.33/tabrez78/metronic.git

**Comment by Pradipta1995** [comment]
FROM ubuntu
RUN apt-get update
RUN apt-get install nginx -y
COPY index.html /var/www/html/
EXPOSE 80
CMD ["nginx","-g","daemon off;"]


 
You need to use the nginx for Loadbalancing and proxy server , not use for Deploy the static website
