### ISSUE TITLE
error when creating a ansible role 

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/DevOpsIssues#617]
![3](https://user-images.githubusercontent.com/50665358/65868803-a9825000-e396-11e9-8be9-423db9c666d8.PNG)

**Comment by RahulAnita** [comment]
Hello,

just try with - ansible-galaxy init role-name

Also make sure your user ansible have sudo access.

**Comment by chowdamramana** [comment]
> Hello,
> 
> just try with - ansible-galaxy init role-name
> 
> Also make sure your user ansible have sudo access.

I am using -vvv for getting more details about the failure

**Comment by bhaskardegala** [comment]
Hi chowdamramana
I think your user don't have proper permissions to create a files in this folder , so first look into folder permissions if possible
