### ISSUE TITLE
Terraform Issue Apacheserver

### ISSUE THREAD

**Issue by wasimkhan33** [QT-DevOps/DevOpsIssues#618]
In creating simple terraform for apache server showing below error in main.tf

PS C:\Practice\Terraform> terraform validate .

Error: Missing required argument

  on main.tf line 13, in resource "aws_instance" "hello":
  13:    connection {

The argument "host" is required, but no definition was found.

connection {
     type = "ssh"
     user = "ec2-user"
     private_key = "${file("./terraform.pem")}"
   }

Always showing error for HOST in connection so I put their host = "self.public_ip"

But then machine creating in loop please suggest
![image](https://user-images.githubusercontent.com/55997315/65903002-3f3ecf00-e3d9-11e9-88ab-4b089101c072.png)

also tried      host = "${aws_instance.hello.public_ip}" then its showing

![image](https://user-images.githubusercontent.com/55997315/65904327-e02e8980-e3db-11e9-946c-e4d3338b8e85.png)

**Comment by ghost** [comment]
please mention host

**Comment by wasimkhan33** [comment]
connection {
     type = "ssh"
     user = "ec2-user"
     private_key = "${file("./terrafo.pem")}"
     host = "${aws_instance.hello.public_ip}"
   }

This one works for me thanks
