### ISSUE TITLE
i have pulled an jenkins image in ec2 instance  and trying to excess it but  i am unable to it

### ISSUE THREAD

**Issue by singaravellu** [QT-DevOps/DevOpsIssues#619]
![image](https://user-images.githubusercontent.com/32475854/66024317-2cc7b100-e511-11e9-8c5f-a84e84dca979.png)

**Comment by ghost** [comment]
open port 8080
and publicip:8080

**Comment by singaravellu** [comment]
i have opened all traffic but still unable to acesses

**Comment by raviops99** [comment]
Hi, 
After pulling Jenkins Image in docker container if you want access the should be in running. 
After container create don't execute control +c  you need to execute contorol+pq container will not stop you can access Jenkins if you already know this point we will check another option

**Comment by singaravellu** [comment]
container is running you can see above screenshot

**Comment by raviops99** [comment]
while using docker run command
docker run -p 8080:8080 -p 50000:50000 jenkins

command : please use another port 8084:8080 remaing same above
and open port 8084 in EC2 machine security group.

if you trying in personal laptop you can open alltcp port in EC2 machine.

then try to acces public ip ec2:8084

**Comment by singaravellu** [comment]
sure
