### ISSUE TITLE
Unable to connect AWS Ubuntu machine

### ISSUE THREAD

**Issue by MuraliTL25** [QT-DevOps/DevOpsIssues#62]
I am unable to connect ubuntu machine. Please find below screen shot. 
![connect ubuntu with git](https://user-images.githubusercontent.com/39365053/42793262-ee0c35ac-8996-11e8-9ed5-de2567f01e99.PNG)
![not connect ubantu machine](https://user-images.githubusercontent.com/39365053/42793290-05918524-8997-11e8-8996-0b81b12f1b0a.PNG)
![amazon jenkins ec2](https://user-images.githubusercontent.com/39365053/42793293-08202c5a-8997-11e8-88d0-5ee559788c7b.PNG)

**Comment by manikantagaddam** [comment]
What you trying to see on web page it is already connected to machine right? or Did u installed any package

**Comment by Imalli5253** [comment]
Please try after installation of any package(nginx, apache2 , tomcat,). 
Please check "PORTS" if you have installed those already.

**Comment by shaikkhajaibrahim** [comment]
Can you show your security group rules?

**Comment by shaikkhajaibrahim** [comment]
Where are rules ??

**Comment by MuraliTL25** [comment]
It's issue with security group rules. I have corrected security group details.Now it's working fine. Thanks!
