### ISSUE TITLE
k8s cluster error

### ISSUE THREAD

**Issue by NarendarBabu** [QT-DevOps/DevOpsIssues#624]
ubuntu@ip-172-31-25-191:~$ kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
The connection to the server localhost:8080 was refused - did you specify the right host or port?
error: unable to recognize "https://cloud.weave.works/k8s/net?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiIxNiIsIEdpdFZlcnNpb246InYxLjE2LjEiLCBHaXRDb21taXQ6ImQ2NDdkZGJkNzU1ZmFmMDcxNjk1OTlhNjI1ZmFmMzAyZmZjMzQ0NTgiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE5LTEwLTAyVDE3OjAxOjE1WiIsIEdvVmVyc2lvbjoiZ28xLjEyLjEwIiwgQ29tcGlsZXI6ImdjIiwgUGxhdGZvcm06ImxpbnV4L2FtZDY0In0K": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused
ubuntu@ip-172-31-25-191:~$

**Comment by bhaskardegala** [comment]
Can you please elaborate the issue and check your ports at once

**Comment by NarendarBabu** [comment]
Port connection is refused 8080, while applying kubectl apply

**Comment by raviops99** [comment]
Hi Narendra,
first can you please cross check all below ports open SSH       22
ALL UDP    0-65535
ALL TRAFFIC
ALL TCP 
CUSTOME TCP 8080
After this execute below commands:
sudo -i
swapoff -a
exit
strace -eopenat kubectl version
after this try to do
kubectl get nodes
kubectl apply
