### ISSUE TITLE
jenkins master slave

### ISSUE THREAD

**Issue by saireddy224** [QT-DevOps/DevOpsIssues#625]
what happen to slaves if we restart jenkins master

**Comment by raviops99** [comment]
Hi Sai,
when a Jenkins master is  restarted the current running jobs are lost and the jobs queue is cleared.This is a Jenkins common behavior,
By using <jenkins_url>/safeRestart to restart your instance, Jenkins will:
- wait for current running jobs to complete
- restart
- keep queued jobs so they are launched after the restart

**Comment by saireddy224** [comment]
> Hi Sai,
> when a Jenkins master is restarted the current running jobs are lost and the jobs queue is cleared.This is a Jenkins common behavior,
> By using <jenkins_url>/safeRestart to restart your instance, Jenkins will:
> 
> * wait for current running jobs to complete
> * restart
> * keep queued jobs so they are launched after the restart

what will happens to slaves.will they lost connection and do theey lost jobs

**Comment by raviops99** [comment]
yes ,
The slave then cannot reconnect until the master Jenkins is restarted 
and any jobs running on slaves will stopped in between.

**Comment by mani5a3** [comment]
see when you are running jenkins in ec2 instance every time it will get new public address it will not update in jenkins configuration system (search for jenkins location and update ip with newly generated ip)and again connect to slave

**Comment by raviops99** [comment]
Hi Sai,
if you got answer please close the issue

**Comment by Abbanapuri** [comment]
why dont you try once
