### ISSUE TITLE
Issue while deleting POD in kubernetes

### ISSUE THREAD

**Issue by kishorejaan1** [QT-DevOps/DevOpsIssues#626]
I Ran a nginx image on the cluster and used replicas=2. 
I deleted the same image, but its not deleting becz of used replicas option...
How can I delete that pod permanently.

kubectl run nginx --image=nginx --replicas=2
kubectl delete pod nginx-6db489d4b7-slxb7 --now
output: pod "nginx-6db489d4b7-slxb7" deleted

Eventhoug I used kubectl delete pods --all

ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$ kubectl get pods
NAME                     READY   STATUS    RESTARTS   AGE
nginx-6db489d4b7-2fgkn   1/1     Running   0          8s
nginx-6db489d4b7-w8x2q   1/1     Running   0          34s
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$ kubectl delete pod nginx-6db489d4b7-2fgkn
pod "nginx-6db489d4b7-2fgkn" deleted

ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$ kubectl get pods
NAME                     READY   STATUS    RESTARTS   AGE
nginx-6db489d4b7-fq9c7   1/1     CreatingContainer   0          15s
nginx-6db489d4b7-w8x2q   1/1     Running   0          56s
ubuntu@ip-172-31-44-142:~$

ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$ kubectl get pods
NAME                     READY   STATUS    RESTARTS   AGE
nginx-6db489d4b7-ld4hp   1/1     Running   0          9s
nginx-6db489d4b7-w8x2q   1/1     Running   0          76s
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$

**Comment by Jsuresh47** [comment]
you need to edit in deployment file pod numbers to one only.

**Comment by kishorejaan1** [comment]
> you need to edit in deployment file pod numbers to one only.

FYI --

I didn't use any Manifest Yaml File... I used to create pod from command line (imperative).

**Comment by kishorejaan1** [comment]
Got Solution from Internet...  Deleted deployment... 

ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$ kubectl run nginx --image=nginx --replicas=2
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
deployment.apps/nginx created
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$ kubectl get pods
NAME                     READY   STATUS    RESTARTS   AGE
nginx-6db489d4b7-sfx55   1/1     Running   0          9s
nginx-6db489d4b7-vkgdg   1/1     Running   0          9s
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$ kubectl get deployments
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   2/2     2            2           19s
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$ kubectl delete deployment nginx
deployment.apps "nginx" deleted
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$ kubectl get pods
No resources found in default namespace.
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$
ubuntu@ip-172-31-44-142:~$

**Comment by kishorejaan1** [comment]
Workaround::
++++++++++
kubectl run nginx --image=nginx --replicas=2
kubectl get pods
kubectl get deployments
kubectl delete deployment nginx
kubectl get pods

**Comment by srmanikanta** [comment]
if you got the answer please close the issue
