### ISSUE TITLE
Jenkins Slave Issue

### ISSUE THREAD

**Issue by Jsuresh47** [QT-DevOps/DevOpsIssues#627]
Am trying to configure Master and Slave in Jenkins but it is shows connection closed what is the solution to this issue.
Thanks in advance.

**Comment by btpk** [comment]
are you trying to connect through master to slave or slave to master? please attach the error screenshot..

**Comment by srmanikanta** [comment]
please post the screenshot of your error 
if you already done this please close the issue

**Comment by shaikkhajaibrahim** [comment]
Since no response from 23 days closing issues
