### ISSUE TITLE
Unable to connect jenkin machine in  aws ubuntu 14.04

### ISSUE THREAD

**Issue by MuraliTL25** [QT-DevOps/DevOpsIssues#63]
Hi,

Please find below screen shots. I have checked proxy and internet connections everything looking good, I am not sure why I am getting this page cann't be reached. 
Please find below below my AWS security groups details.
Security groups
launch-wizard-7. view inbound rules. view outbound rules

![jenkins cann t reach error](https://user-images.githubusercontent.com/39365053/42899749-a2552e58-8ae4-11e8-9a6d-940e22b64e3e.PNG)
![aws ubuntu 14 0 machine](https://user-images.githubusercontent.com/39365053/42899764-af06efd8-8ae4-11e8-9930-c097b771dead.PNG)

**Comment by MuraliTL25** [comment]
Before I use https://.......:8080 it's throwing this site cannot reached and check proxy and firewall and network diagnostics, now  I  have changed to http:://.......:8080 , I am getting "This site cannot be reached err_timed_out chrome". For this i tried to restart machine and run some commands in command prompt.. still facing same issue...

**Comment by MuraliTL25** [comment]
Before I use https://.......:8080 it's throwing this site cannot reached and check proxy and firewall and network diagnostics, now  I  have changed to http:://.......:8080 , I am getting "This site cannot be reached err_timed_out chrome". For this i tried to restart machine and run some commands in command prompt.. still facing same issue...

**Comment by shaikkhajaibrahim** [comment]
Share your public url

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MuraliTL25** [comment]
Public url is keep on changing Today it is "13.59.207.18", yesterday it was "18.191.209.108" and I tried now also it is giving below error.

"This site can’t be reached
13.59.207.18 took too long to respond.
Search Google for 207 8080
ERR_CONNECTION_TIMED_OUT"

**Comment by Ram-peram** [comment]
Please install apache http server on this machine and try the http server URL first to confirm where will be the issue.

**Comment by MuraliTL25** [comment]
I tried with apache, still facing same issue. Please find below screen shots.
![apche started on ubuntu aws](https://user-images.githubusercontent.com/39365053/43015997-f0ddea84-8c6e-11e8-8aa3-17be5274700e.PNG)
![site cannot reached](https://user-images.githubusercontent.com/39365053/43016075-449933cc-8c6f-11e8-9c7a-7754e18f114f.PNG)

**Comment by shaikkhajaibrahim** [comment]
Screenshot of security group

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MuraliTL25** [comment]
Hi,
Now I am able to connect Apache server, Need to check Jenkins. "The issue with Security group only, before **Security Type** was SSH now I have changed to "All Trafic". Thanks!

**Comment by MuraliTL25** [comment]
I am able to connect Jenkins also. Thanks!.
