### ISSUE TITLE
616 is issue is not resolved yet

### ISSUE THREAD

**Issue by tabrez78** [QT-DevOps/DevOpsIssues#630]

**Comment by tabrez78** [comment]
while building docker file git clone is asking for the password even after copying ssh keys
host key verification failed

**Comment by raviops99** [comment]
Hi Can you please execute below command on linux machine where docker is running

ssh-keygen -R hostname

-R hostname
Removes all keys belonging to hostname from a known_hosts file. This option is useful to delete hashed hosts .

**Comment by srmanikanta** [comment]
if you got the answer please close the issue

**Comment by tabrez78** [comment]
thanks
