### ISSUE TITLE
issue in running docker container

### ISSUE THREAD

**Issue by sohanmadhana** [QT-DevOps/DevOpsIssues#631]
ubuntu@ip-172-31-22-208:~/gol$ docker container run -d -p 8081:8080 gol:task
c4ccf79afd2ecc803953ae801ce8472f169de9eaaacf36981ea91cee64f17238
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"exec\": executable file not found in $PATH": unknown.

**Comment by mani5a3** [comment]
once restart the docker and then check

**Comment by raviops99** [comment]
Hi Sohan,

Can you please post what is operating system you are using and docker version

**Comment by Abbanapuri** [comment]
please check CMD in dockerfile
