### ISSUE TITLE
Jenkins : Build Pipeline View Plugin

### ISSUE THREAD

**Issue by rajendrapopuri** [QT-DevOps/DevOpsIssues#632]
I created three users (with limited access ex: user1, user2, user3) and three jobs in Jenkins and granted job specific access to each user using pattern matching. Security mechanism configured is Role Based Authorization. Also, I grouped these jobs in Build Pipeline View using upstream/downstream relationship. Jobs are appearing for each user id based on pattern matching, but the build pipeline view is appearing only for user1 but not for other two user id's (user2 and user3). Any thoughts? 
Note: user1, user2 and user3 have same permissions.
Thanks, Raj.

**Comment by raviops99** [comment]
Hi Rajendra,
Below link may help for you are query

https://issues.jenkins-ci.org/browse/JENKINS-41274

**Comment by rajendrapopuri** [comment]
Hi Ravi, thanks for your reply. 

The above URL relate to jenkins pipeline using groovy script.
but I am looking for Build Pipeline View plugin.. Here is the reference youtube video. https://www.youtube.com/watch?v=mf5MsQtEa5o

**Comment by shaikkhajaibrahim** [comment]
Refer to Blue Ocean, Here we don't focus on UI Elements
