### ISSUE TITLE
Docker permission issue

### ISSUE THREAD

**Issue by Nara-Sagar7** [QT-DevOps/DevOpsIssues#634]
![image](https://user-images.githubusercontent.com/54387478/67760438-58ce4780-fa67-11e9-9eb2-e7d081477c1b.png)
16:14:15  [[1;34mINFO[m] Webapp assembled in [60 msecs]
16:14:15  [[1;34mINFO[m] Building war: /home/jenkins/workspace/docker/target/myweb-0.0.7-SNAPSHOT.war
16:14:15  [[1;34mINFO[m] WEB-INF/web.xml already added, skipping
16:14:15  [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
16:14:15  [[1;34mINFO[m] [1;32mBUILD SUCCESS[m
16:14:15  [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
16:14:15  [[1;34mINFO[m] Total time:  5.595 s
16:14:15  [[1;34mINFO[m] Finished at: 2019-10-29T10:44:15Z
16:14:15  [[1;34mINFO[m] [1m------------------------------------------------------------------------[m
16:14:15  [Pipeline] }
16:14:15  [Pipeline] // stage
16:14:15  [Pipeline] stage
16:14:15  [Pipeline] { (Build Docker Image)
16:14:15  [Pipeline] sh
16:14:15  + docker build -t sagardevops/my-app:1.0.0 .
16:14:15  Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=frb4bxjgzws0vc7m64riax8bm&shmsize=0&t=sagardevops%2Fmy-app%3A1.0.0&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
16:14:15  [Pipeline] }
16:14:15  [Pipeline] // stage
16:14:15  [Pipeline] }
16:14:15  [Pipeline] // node
16:14:15  [Pipeline] End of Pipeline
16:14:15  ERROR: script returned exit code 1
16:14:15  Finished: FAILURE

Can any one please tell what i have done wrong!!

**Comment by raviops99** [comment]
Hi sagar,
Please execute below commands where docker is installed
To create docker group
Sudo groupadd docker
Add user to the docker group
Sudo usermod -aG docker $USER
Log out and religion in to terrminal

**Comment by Nara-Sagar7** [comment]
hey, Ravi thank you now it's working.
