### ISSUE TITLE
Kibana installation error.

### ISSUE THREAD

**Issue by Nara-Sagar7** [QT-DevOps/DevOpsIssues#636]
Hello.
any buddy have any idea why I am getting this error, I have installed the elasticsearch and kibana and when I am opening kibana in my browser I am getting like below please find the screenshot.

![image](https://user-images.githubusercontent.com/54387478/67950594-e6e53200-fc0f-11e9-800c-45e7fdadbac9.png)

**Comment by raviops99** [comment]
Can you please provide lubana logs while starting

**Comment by raviops99** [comment]
Please provide  kibaba logs while starting

**Comment by raviops99** [comment]
Can you please share kibaba.yml file

**Comment by Pradipta1995** [comment]
increase the java heap space for all elk machine to min 4 gb

**Comment by srmanikanta** [comment]
#please add the below configuration to the /etc/elasticsearch/elasticsearch.yml
initial_master_nodes: -
#restart the elasticsearch service
sudo systemctl restart elasticsearch
i hope your issue is solved right now
if your issue is solved then close your issue
thanks
srmanikanta

**Comment by shaikkhajaibrahim** [comment]
Duplicate Refer #637
