### ISSUE TITLE
Kibana server is not ready yet

### ISSUE THREAD

**Issue by kishorejaan1** [QT-DevOps/DevOpsIssues#637]
![image](https://user-images.githubusercontent.com/43911102/68034628-08195180-fce8-11e9-9cbb-1f826dd26816.png)

++++

root@ip-172-31-8-194:~# sudo systemctl start kibana.service
root@ip-172-31-8-194:~#
root@ip-172-31-8-194:~# sudo systemctl status kibana.service
● kibana.service - Kibana
   Loaded: loaded (/etc/systemd/system/kibana.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-11-01 15:10:09 UTC; 35s ago
 Main PID: 3306 (node)
    Tasks: 21 (limit: 1152)
   CGroup: /system.slice/kibana.service
           └─3306 /usr/share/kibana/bin/../node/bin/node /usr/share/kibana/bin/../src/cli -c /etc/kibana/kibana.yml

Nov 01 15:10:29 ip-172-31-8-194 kibana[3306]: {"type":"log","@timestamp":"2019-11-01T15:10:29Z","tags":["status","plugin:cross_cluster_replication@7.4.2","error"],"pid":330
Nov 01 15:10:29 ip-172-31-8-194 kibana[3306]: {"type":"log","@timestamp":"2019-11-01T15:10:29Z","tags":["status","plugin:file_upload@7.4.2","error"],"pid":3306,"state":"red
Nov 01 15:10:29 ip-172-31-8-194 kibana[3306]: {"type":"log","@timestamp":"2019-11-01T15:10:29Z","tags":["status","plugin:snapshot_restore@7.4.2","error"],"pid":3306,"state"
Nov 01 15:10:31 ip-172-31-8-194 kibana[3306]: {"type":"log","@timestamp":"2019-11-01T15:10:31Z","tags":["reporting","warning"],"pid":3306,"message":"Generating a random key
Nov 01 15:10:31 ip-172-31-8-194 kibana[3306]: {"type":"log","@timestamp":"2019-11-01T15:10:31Z","tags":["status","plugin:reporting@7.4.2","error"],"pid":3306,"state":"red",
Nov 01 15:10:31 ip-172-31-8-194 kibana[3306]: {"type":"log","@timestamp":"2019-11-01T15:10:31Z","tags":["status","plugin:security@7.4.2","error"],"pid":3306,"state":"red","
Nov 01 15:10:31 ip-172-31-8-194 kibana[3306]: {"type":"log","@timestamp":"2019-11-01T15:10:31Z","tags":["reporting","warning"],"pid":3306,"message":"The Reporting plugin en
Nov 01 15:10:31 ip-172-31-8-194 kibana[3306]: {"type":"log","@timestamp":"2019-11-01T15:10:31Z","tags":["reporting","warning"],"pid":3306,"message":"See Chromium's log outp
Nov 01 15:10:31 ip-172-31-8-194 kibana[3306]: {"type":"log","@timestamp":"2019-11-01T15:10:31Z","tags":["reporting","warning"],"pid":3306,"message":"Reporting plugin self-c
Nov 01 15:10:34 ip-172-31-8-194 kibana[3306]: {"type":"log","@timestamp":"2019-11-01T15:10:34Z","tags":["reporting","esqueue","queue-worker","error"],"pid":3306,"message":"
lines 1-18/18 (END)

+++++
![image](https://user-images.githubusercontent.com/43911102/68034739-47e03900-fce8-11e9-9cfa-759a971c2d0d.png)

root@ip-172-31-8-194:~#
root@ip-172-31-8-194:~# curl http://172.31.8.194:5601
Kibana server is not ready yet
root@ip-172-31-8-194:~#
root@ip-172-31-8-194:~#
root@ip-172-31-8-194:~#

+++++

FYI --
Elasticsearch status:

![image](https://user-images.githubusercontent.com/43911102/68034880-8d046b00-fce8-11e9-8c80-f83f48c19b88.png)

**Comment by raviops99** [comment]
Hi Kishore,
In kibana.yml file where server.host parameter give aws machine private IP where kibana you have installed.open all tcp ports on the machine.

from browser try http://publiciip:8601.

Pleasetry this

**Comment by kishorejaan1** [comment]
![image](https://user-images.githubusercontent.com/43911102/68085950-856dcf00-fe6c-11e9-9eab-cbf709944710.png)
![image](https://user-images.githubusercontent.com/43911102/68085954-9a4a6280-fe6c-11e9-9bbf-1d6e2cceca89.png)

![image](https://user-images.githubusercontent.com/43911102/68085958-a6362480-fe6c-11e9-800d-32b0851e5bad.png)

**Comment by kishorejaan1** [comment]
> Hi Kishore,
> In kibana.yml file where server.host parameter give aws machine private IP where kibana you have installed.open all tcp ports on the machine.
> 
> from browser try http://publiciip:8601.
> 
> Pleasetry this

Hello Ravi,

    Can you please look the issue.. Still am facing same issue... I tried in google also couldn't find any solution for this...

**Comment by srmanikanta** [comment]
#please add the below configuration to the /etc/elasticsearch/elasticsearch.yml
initial_master_nodes: - <private ip of elastic search>
#restart the elasticsearch service
sudo systemctl restart elasticsearch 
i hope your issue is solved right now
if your issue is solved then close your issue
thanks
srmanikanta

**Comment by shaikkhajaibrahim** [comment]
Is it done?
