### ISSUE TITLE
Ansible Playbook

### ISSUE THREAD

**Issue by anupsahoo11** [QT-DevOps/DevOpsIssues#638]
Hi ,

I want to create an Ansible Playbook, which will
1. create database
2. create VM instance and deploy service(Can be any application) on it
3. configure CDN with VM instance 

I am stuck at step 3. Can anyone suggest any solution.
Thanks in advance.

Regards,
Anup

**Comment by shaikkhajaibrahim** [comment]
First elaborate on all the manual linux/unix commands

**Comment by anupsahoo11** [comment]
[Ansible.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3819486/Ansible.txt)
This my Playbook
[user_data.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3819490/user_data.txt)
The user data file to install Redmine during Bootstrap
I am mostly stuck on getting the CDN DNS name as ouput and linking the load balancer to CDN

**Comment by shaikkhajaibrahim** [comment]
I dont want ansible playbook, please write the manual commands
