### ISSUE TITLE
How to edit the file inside container from outside Host

### ISSUE THREAD

**Issue by ramana152** [QT-DevOps/DevOpsIssues#639]
Hello All,

     I have one docker container, that container is running in weblogic11, so that weblogic is running by default in Production-mode, so i want to change that production-mode to Development-mode, for that i need to edit file  config.xml inside container, how we can edit that file from outside the container?

 Thanks in Advance!!!

**Comment by Pradipta1995** [comment]
$ docker container exec it "id of the container" /bin/bash

you are inside the container and change any file..

**Comment by srmanikanta** [comment]
if you edit any file in container firtst you should be in that container to do that
docker container run -it <yourcontainerid> <command>
example:
docker container -it 039c3265e074 /bin/bash
once you are inside that container goto your file and change
after complete the process then ctrl+P+Q -->to exit from container without killing the container.
i hope this is useful to you
thanks 
srmanikanta

**Comment by shaikkhajaibrahim** [comment]
If you want to edit the file in the running container, use docker exec -it, if it is before starting container use Docker environment variables
