### ISSUE TITLE
Unable to use param

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#64]
Hi,

I'm trying to install basic stuff on a new Win 10 system. Created the below PowerShell DSC script. It creates a .mof file if used without param. Upon using param, the following error is thrown:

![image](https://user-images.githubusercontent.com/40449948/42954529-9d762f0c-8b9a-11e8-99e1-94bd7892fe96.png)

This is the script:
Configuration BasicSetup {
    
    Import-DSCResource -ModuleName cChoco
    param ($computer = 'localhost')

	Node $computer {
        
		cChocoInstaller InstallChoco {
                       InstallDir = "c:\Chocolatey"
            }
            
		cChocoPackageInstaller git {
			name = 'git'
			ensure = 'present'
            }
            
		cChocoPackageInstaller visualstudiocode {
			name = 'visualstudiocode'
			ensure = 'present'
            }

        cChocoPackageInstaller notepadplusplus {
			name = 'notepadplusplus'
			ensure = 'present'
            }
        
        cChocoPackageInstaller 7zip {
			name = '7zip'
			ensure = 'present'
            }
		}
	}
BasicSetup -computer localhost

Please let me know what the mistake is.

**Comment by shaikkhajaibrahim** [comment]
Try something like this.

Configuration ParamTestConfig {
    Import-DscResource -ModuleName PSDesiredStateConfiguration
    Node $computer {
        File TempDirectory
        {
            DestinationPath = "C:\Temp\HelloWorld"
            Ensure = "Present"
            Type = "Directory"
        }
    }
}

$computer = 'localhost'

ParamTestConfig

**Comment by rameshm78** [comment]
This script is working. However, if I remove $computer = 'localhost' and instead call the config as ParamTestConfig -computer 'localhost', I'm still getting the error:
ParamTestConfig : A parameter cannot be found that matches parameter name 'computer'.
At E:\PowerShellDSC\ParamTestConfig.ps1:14 char:21
+     ParamTestConfig -computer localhost
+                     ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ParamTestConfig], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,ParamTestConfig

1. The param function cannot be used
2. This method cannot be used to pass parameters at runtime. 
So what is the solution for making a parameterized script? Examples found by Googling is very complicated for me to understand as I don't have any scripting background/ experience.
So how can we have parameterize our script?

**Comment by shaikkhajaibrahim** [comment]
As covered in class param has to be passed b4 creating MOF file
