### ISSUE TITLE
is it mandatory to "service sshd restart" after changing authentication in config

### ISSUE THREAD

**Issue by akashvarma43** [QT-DevOps/DevOpsIssues#643]

**Comment by VENKATAREDDYVENNA** [comment]
Hi @akashvarma43 
In order to update the sshd configuration file changes to the service, we need to restart (or) reload the service. Otherwise, the changes that you made in the /etc/ssh/sshd_config won't affect the service. 


service sshd restart (or) service sshd reload anything can help you.
