### ISSUE TITLE
Do we need same user names on both ACS and nodes 

### ISSUE THREAD

**Issue by akashvarma43** [QT-DevOps/DevOpsIssues#645]
-Do we need same user names on both ACS and nodes to establish PASSWD less audentication
Update
-Not able to establish password less audencation with different usernames on ACS and NODE
- but can establish connection with same user names on both
 WHY is this!

**Comment by raviops99** [comment]
Hi Akash,
Yes we have to create same user in acs and  nodes
Basically we do this to achive password less authentication based on SSH concept
And also you need  to mention same user all the nodes sudeors file
