### ISSUE TITLE
ansible node connecting failure

### ISSUE THREAD

**Issue by sohanmadhana** [QT-DevOps/DevOpsIssues#646]
I have created 2 ubuntu machines, 1 control node and 1 node. I followed all the instructions of ansible installation on control node and python installation for node.
I added ansible as user in control node and sohan as user in the node.
I created a ssh key in ansible and copied it to sohan through ssh-copy-id sohan@<private-ip>
It is throwing a error.
![error](https://user-images.githubusercontent.com/54635473/68562731-eef36c00-0470-11ea-9509-77556a64576b.PNG)

**Comment by raviops99** [comment]
Hi Sohan,
1.Create a user in ansible control server and also same user in node ex:
adduser ansible
2. This is user add in vi sudo file i guess u have done this step
3. now login acs and from ansible user
Execute ssh-keygen
4. now ssh-copy-id  ansible@priviate dns of 
Of ansible nodeserver
5. I guess u have already added control server /etc/ansible/hosts file
Mention private dns ip ansible noder sever.
If not do 5 step first then 4 step

**Comment by shaikkhajaibrahim** [comment]
And you are running as a root user, execute ansible command from the ansible user

**Comment by sohanmadhana** [comment]
Thank you for your response. I had done that using identical usernames then I tried using different usernames, it didn't work.
Is it necessary to have same username for both control node and node?

**Comment by Abbanapuri** [comment]
> Thank you for your response. I had done that using identical usernames then I tried using different usernames, it didn't work.
> Is it necessary to have same username for both control node and node?
No

**Comment by bhaskardegala** [comment]
Hi

Have you changed sshd_config file on both the nodes

**Comment by srmanikanta** [comment]
It is possible to configure ansible node with a different user.
#ansible -m ping -u <nodeusername> all
#ansible-playbook palybook.yml -u <nodeusername>

**Comment by suriuma554** [comment]
devops@ip-172-31-2-5:/home/ubuntu$ ssh-copy-id devops@172.31.2.98
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/devops/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
devops@172.31.2.98: Permission denied (publickey).
"i am facing this error what exactly it means"

**Comment by shaikkhajaibrahim** [comment]
Please follow all of the steps
