### ISSUE TITLE
Ansible playbook execution:   [WARNING]: Could not find aptitude. Using apt-get instead

### ISSUE THREAD

**Issue by sudhaaws9** [QT-DevOps/DevOpsIssues#648]
![Screenshot (6)](https://user-images.githubusercontent.com/57389496/68657412-a9f73480-0559-11ea-91c9-1f7ef942e1bf.png)
![Screenshot (5)](https://user-images.githubusercontent.com/57389496/68656515-fa6d9280-0557-11ea-9acd-5b401223be20.png)

my yml file:

---
- hosts: all
  become: yes
  tasks:
    - name: install tree
      apt:
        name: tree
        update_cache: yes
        state: present

plz, any one help me in my issue.

**Comment by Abbanapuri** [comment]
that is not error 
just warning

**Comment by bhaskardegala** [comment]
Hi sudha

As naresh said it is just a warning nothing to worry about it, if your
issue was resolved please close it

**Comment by sudhaaws9** [comment]
ok. i got it. tq u for ur response on my doudth.
