### ISSUE TITLE
bash shell script solution

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/DevOpsIssues#649]
![1](https://user-images.githubusercontent.com/50665358/68740238-a377c400-0610-11ea-9b36-4d253d3b47cf.jpg)
![2](https://user-images.githubusercontent.com/50665358/68740239-a377c400-0610-11ea-9e4c-8c8133d7cd2b.jpg)
![3](https://user-images.githubusercontent.com/50665358/68740240-a4105a80-0610-11ea-9c4f-21a55d451f70.jpg)

**Comment by shaikkhajaibrahim** [comment]
This is not for shell scripts
