### ISSUE TITLE
Ansible Playbook not executing

### ISSUE THREAD

**Issue by vjulakanti** [QT-DevOps/DevOpsIssues#650]
I have created 2 ubuntu machines, 1 ACS(172.31.22.188)  and  node1(172.31.26.162). I followed all the instructions of ansible installation on control node and python installation for node.
I connect ACS to as ansible user, in that user i created one directory, in that directory created **testinventory** and **tree-playbook.yml** files 
In **testinventory** i added ACS and node1 private ipaddresses
then i try to execute that **tree-playbook.yml**  but am following below error. ACS is not connecting
![playbook](https://user-images.githubusercontent.com/10668742/68930174-d73f1f00-07b3-11ea-90a6-763857bb97ad.PNG)

**Comment by srmanikanta** [comment]
Before execute the playbook
please check the ansible -m ping all

**Comment by harishvangapandu** [comment]
add localhost also in inventory then check ansible -m ping all and then execute the playbook

**Comment by raviops99** [comment]
Hi please follow below link 
https://www.australtech.net/ansible-failed-to-connect-to-the-host-via-ssh/

**Comment by Abbanapuri** [comment]
please do all steps as mention in docs(directdevops.blog)

**Comment by bhaskardegala** [comment]
In your case local host was not able to ping it self try exchanging shh key
for local host as well

**Comment by vjulakanti** [comment]
Thanks all now working fine.
