### ISSUE TITLE
Unable to find GIT in Jenkins "Configuration System"

### ISSUE THREAD

**Issue by baisachinna** [QT-DevOps/DevOpsIssues#651]
I am trying to add GIT details as per shown in below. But i couldn't find GIT option to add. I have installed jenkins with GIT plugin. I am trying to install GIT plugin (Page: 109/Jenkin.pdf).

![GIT_As_per_Jenkins_Doc](https://user-images.githubusercontent.com/3677634/69007631-3bb5c780-08f5-11ea-80ff-e6ec6ae0194d.jpg)

Below is the Installed plugins in my Jenkin Server.
![Installed_Git_in_Jenkins](https://user-images.githubusercontent.com/3677634/69007683-c8608580-08f5-11ea-9d68-20c6df7e7fe7.JPG)

**Comment by raviops99** [comment]
Hi Chinna,
Have you install ed Jenkins windows ???

**Comment by baisachinna** [comment]
Hi Ravi

Yes, Its on windows.

**Comment by raviops99** [comment]
Don't set any path in global tool configaration go  manage Jenkins install git plug create new freestyle job in SCM u will git option
Suggestion : please practice Jenkins on Linux environment

**Comment by CHARANJAI** [comment]
Hi chinna,
Ravi shared good content.If you got solution please close the case.

**Comment by baisachinna** [comment]
Thanks Ravi for helping in.
