### ISSUE TITLE
Clarify the below issue while going to the folder path in win powershell.?

### ISSUE THREAD

**Issue by gopichandu98** [QT-DevOps/DevOpsIssues#653]
while going to the folder path in powershell it is showing the Error like not recoganized the name of cmdlet.i did run as a administrator and checking the folder path also.path is also correct but y it is showing the error.can u look in to the issue.
![sniping](https://user-images.githubusercontent.com/55825566/69316782-920d6800-0c5f-11ea-844c-9af3d1cb7a20.PNG)

**Comment by bhaskardegala** [comment]
If you would like to go into that folder use 'cd' before the path

**Comment by gopichandu98** [comment]
Here the problem is not noly the path if iam execute any command in powershell iam facing same kind of problem.

**Comment by bhaskardegala** [comment]
Hi gopi,
Can you please elaborate your issue ,
What are the commands that you are trying out and what are the failures

**Comment by srmanikanta** [comment]
please follow the below things:
* first extract the starter-kit zip file
* go to that chef stater-kit path just like the below
#cd C:\Users\GOPI\Downloads\chef-starter\chef-repo
* copy your node .pem file to this location
* execute the knife bootstrap command

**Comment by Abbanapuri** [comment]
please follow manikanta steps you get
