### ISSUE TITLE
Powershell not working in VSCode

### ISSUE THREAD

**Issue by vjulakanti** [QT-DevOps/DevOpsIssues#655]
I am trying to open power shell in VSCode, but whenever am using **knife node list** command it is opening new cmd. why it is opening new cmd here..  
![image](https://user-images.githubusercontent.com/10668742/69423657-b3984d80-0d4c-11ea-8b7f-b786118e37e1.png)

**Comment by bhaskardegala** [comment]
Hi,
You are using ruby in vs instead powershell , try using powershell terminal

**Comment by vjulakanti** [comment]
@bhaskardegala i executed in powershell command only whenever i run **knife node list** command, terminal is changing powershell to ruby . then new cmd window is opening

**Comment by bhaskardegala** [comment]
I think that it might be an issue with administration permissions

**Comment by srmanikanta** [comment]
I thinks you not installed powershell extension in visual studio code
please first install powershell extension and then ctrl + shift + p
it will open powershell in you current page.
if already did this please close the issue.
