### ISSUE TITLE
SSH Session could not be Establish .....how to establish the ssh session 

### ISSUE THREAD

**Issue by SRIDHAR666** [QT-DevOps/DevOpsIssues#656]
![image (2)](https://user-images.githubusercontent.com/58039386/69434270-49d76e00-0d63-11ea-977f-0f777131a719.png)
![image (3)](https://user-images.githubusercontent.com/58039386/69434271-49d76e00-0d63-11ea-90f3-118eda8a3170.png)
![ssh](https://user-images.githubusercontent.com/58039386/69434273-49d76e00-0d63-11ea-9818-4a6432d7c22b.png)

**Comment by bhaskardegala** [comment]
Please check whether your pem file is placed in .chef folder or not

**Comment by srmanikanta** [comment]
Now you are in .chef folder please get back to chef-repo folder 
To do that execute the below command
#cd ..  
Now execute the knife bootstrap command
#knife bootstrap -U <username> -i <pemfile> --sudo -N <givenameofyournode>

**Comment by srmanikanta** [comment]
Now you are in .chef folder please get back to chef-repo folder
To do that execute the below command
#cd ..
Now execute the knife bootstrap command
#knife bootstrap publicip -U username -i pemfile  --sudo -N nodename
I think this information is useful to you if not please ignore.
if already done this please close the issue.

**Comment by Abbanapuri** [comment]
please give pem file location

**Comment by chnadoo123** [comment]
> Now you are in .chef folder please get back to chef-repo folder To do that execute the below command #cd .. Now execute the knife bootstrap command #knife bootstrap publicip -U username -i pemfile --sudo -N nodename I think this information is useful to you if not please ignore. if already done this please close the issue.

this is not working
