### ISSUE TITLE
recipes are not installing in node1(ubuntu)

### ISSUE THREAD

**Issue by vjulakanti** [QT-DevOps/DevOpsIssues#657]
i created a recipe file using below resources 
![image](https://user-images.githubusercontent.com/10668742/69440971-cbcd9400-0d6f-11ea-89fe-5f615fc47c18.png)
and i added that cookbook to **runlist**, then i login to node1. then i run **sudo hef-client** this command to execute those resources, but those resources are not installing once check below

![image](https://user-images.githubusercontent.com/10668742/69441277-6ded7c00-0d70-11ea-994f-6751203cc467.png)

**Comment by srmanikanta** [comment]
check the below things:
* Go to your berks file(located in your cookbook folder) and execute the below commands
# berks install
#berks upload
* go to your chef server and edit the run_list 
* finally go to chef node and execute this command
#sudo chef-sudo
I think it is useful to you, if not please ignore
if already find the solution to this please close the issue.

**Comment by bhaskardegala** [comment]
I was expecting that you uploaded your cookbook first then modified your cookbook on workstation and if you want to update it on the server change your metadata version and do Berks upload again, Please update the issue accordingly,
Thanks

**Comment by srmanikanta** [comment]
check the below things:

Go to your berks file(located in your cookbook folder) and execute the below commands
#berks install
#berks upload
go to your chef server and edit the run_list
finally go to chef node and execute this command
#sudo chef-sudo
I think it is useful to you, if not please ignore
if already find the solution to this please close the issue.
Note: if you modify the recipes please change the version in metadata file
and again do the berks install , berks upload ,change the run_list and execute the sudo chef-client 
I think it is useful to you, if not please ignore 
if you already find the solution to this please close the issue.

**Comment by Abbanapuri** [comment]
please change cookbook version in metadata.rb and berks upload again and add to run_list

**Comment by bhaskardegala** [comment]
There might be another possibility make sure auto save is enabled in vs code
