### ISSUE TITLE
spring-petclinic.jar file

### ISSUE THREAD

**Issue by srmanikanta** [QT-DevOps/DevOpsIssues#659]
https://learningspcfromqt.s3.us-east-2.amazonaws.com/spring-petclinic.jar

**Comment by kp1310** [comment]
Hey,

Unable to download spring petclinic from this location, getting below error:

 wget https://learningspcfromqt.s3.us-east-2.amazonaws.com/spring-petclinic.jar
--2019-12-19 12:08:46--  https://learningspcfromqt.s3.us-east-2.amazonaws.com/spring-petclinic.jar
Resolving learningspcfromqt.s3.us-east-2.amazonaws.com (learningspcfromqt.s3.us-east-2.amazonaws.com)... 52.219.84.56
Connecting to learningspcfromqt.s3.us-east-2.amazonaws.com (learningspcfromqt.s3.us-east-2.amazonaws.com)|52.219.84.56|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-12-19 12:08:46 ERROR 404: Not Found.
