### ISSUE TITLE
Error while configuring AWS CLI

### ISSUE THREAD

**Issue by DasaradhBetha9** [QT-DevOps/DevOpsIssues#661]
![image](https://user-images.githubusercontent.com/58160150/69816892-59512e00-121f-11ea-9075-6842ae231bbd.png)

Hi, While configuring AWS CLI, I'm getting an error of  ''unknown output type'' 

Please do needful.

**Comment by DasaradhBetha** [comment]
![image](https://user-images.githubusercontent.com/58160150/69817143-f318db00-121f-11ea-857e-82f611c9f4e8.png)
