### ISSUE TITLE
Error while configuring AWS CLI

### ISSUE THREAD

**Issue by DasaradhBetha9** [QT-DevOps/DevOpsIssues#662]
![image](https://user-images.githubusercontent.com/58160150/69817605-f9f41d80-1220-11ea-9c37-d3f50916b4ab.png)

While configuring AWS through CLI, I'm getting an error of ''unknown output type''

I tried changing the regions. but can't resolve.

Pls do needful.

**Comment by ramdaspally** [comment]
region is:  ap-south-1   
format is : json

**Comment by Abbanapuri** [comment]
region: ap-south-1
format: json
