### ISSUE TITLE
--Exception------- >>>>>> Class: Kitchen::ActionFailed >>>>>> Message: 1 actions failed. >>>>>>     Failed to complete #create action: [The image id '[ami-0123b531fc646552f]' does not exist] on default-ubuntu-1604 >>>>>> ---------------------- >>>>>> Please see .kitchen/logs/kitchen.log for more details >>>>>> Also try running `kitchen diagnose --all` for configuration

### ISSUE THREAD

**Issue by naidusrk** [QT-DevOps/DevOpsIssues#663]
<img width="1137" alt="Screenshot 2019-11-28 at 9 24 20 PM" src="https://user-images.githubusercontent.com/35523036/69819726-830d5380-1225-11ea-8f88-bfd81f99c2bf.png">
**kitchen.yml:**

---
<img width="211" alt="Screenshot 2019-11-28 at 9 17 02 PM" src="https://user-images.githubusercontent.com/35523036/69819376-d92dc700-1224-11ea-8115-c9fdbfaa8b07.png">

driver:
  name: ec2
  aws_ssh_key_id: AnsibleKeypairs # key pair name
  region: us-west-2 # region code of aws
  availability_zone: us-west-2b # availability_zone of us-west
  subnet_id: subnet-1171735a # subnet-id noted from above steps
  instance_type: t2.micro # as it is free instance type
  image_id: ami-0654973af14fd607c  # image id of ubuntu
  security_group_ids: ["sg-0d6d4a49db8f94d27"]

## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15

verifier:
  name: inspec

transport:
  ssh_key: ./AnsibleKeypairs.pem
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu # username from ami-id

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[apacheCookBook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

**Comment by ramdaspally** [comment]
please check once
select  ec2 ubuntu machine ,  not sql server

**Comment by naidusrk** [comment]
> please check once
> select ec2 ubuntu machine , not sql server

Selected Only ubuntu machine as well, getting the same error

**Comment by naidusrk** [comment]
<img width="1152" alt="Screenshot 2019-11-29 at 8 16 53 AM" src="https://user-images.githubusercontent.com/35523036/69840213-b3361000-1280-11ea-9572-dd6649f1f6de.png">

**Comment by naidusrk** [comment]
<img width="829" alt="Screenshot 2019-11-29 at 8 46 10 AM" src="https://user-images.githubusercontent.com/35523036/69841330-bb904a00-1284-11ea-9c79-0bd49c6017e5.png">

**Comment by naidusrk** [comment]
It is working now, as i have given region name as wrong and one more thing AMI ID will change from  region to another region.Thank you

**Comment by srmanikanta** [comment]
please close the issue.
