### ISSUE TITLE
kubernetes deployment error

### ISSUE THREAD

**Issue by ajs777** [QT-DevOps/DevOpsIssues#664]
![Screenshot (134)](https://user-images.githubusercontent.com/37798362/69852952-9ebb3d00-12ab-11ea-8e2d-61bdbcfd5c1f.png)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata: 
      labels:
        app: nginx
    spec:
      containers:
        - name: my-Deployment
          image: nginx
          ports:
          - containerPort: 80

**Comment by RahulAnita** [comment]
Hi,

Please use the below code and let me know in case of any issues:

apiversion: apps/v1
kind: Deployment
metadata:
name: my-deployment
namespace: default
spec:
replicas: 3
strategy:
type: RollingUpdate
rollingUpdate:
maxSurge: 1
maxUnavailable: 25%
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
minReadySeconds: 20
spec:
containers:
- name: my-Deployment
image: nginx
imagePullPolicy: Always
ports:
- containerPort: 80

**Comment by vkatukam** [comment]
names in metadata must be in lower case letters only and along with few other special characters.
