### ISSUE TITLE
Jenkins :SonarQube Issue

### ISSUE THREAD

**Issue by itzpraveen18** [QT-DevOps/DevOpsIssues#67]
Sir ,sonar qube reports are not generating, 
i configured sonar credentials with jenkins  but still it showing following 
error

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:28 min
[INFO] Finished at: 2018-07-22T20:38:18Z
[INFO] ------------------------------------------------------------------------
[spring] $ /var/lib/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/sonar/bin/sonar-scanner -Dsonar.host.url=http://192.168.40.10:9000 ******** -Dsonar.projectName=spring-petclinic -Dsonar.projectVersion=1.3 -Dsonar.projectKey=sonar -Dsonar.sources=. -Dsonar.projectBaseDir=/var/lib/jenkins/workspace/spring
INFO: Scanner configuration file: /var/lib/jenkins/tools/hudson.plugins.sonar.SonarRunnerInstallation/sonar/conf/sonar-scanner.properties
INFO: Project root configuration file: /var/lib/jenkins/workspace/spring/sonar-project.properties
INFO: SonarQube Scanner 3.2.0.1227
INFO: Java 1.8.0_181 Oracle Corporation (64-bit)
INFO: Linux 3.13.0-153-generic amd64
INFO: User cache: /var/lib/jenkins/.sonar/cache
ERROR: SonarQube server [http://192.168.40.10:9000] can not be reached
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 5.816s
INFO: Final Memory: 3M/15M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarQube Scanner execution
ERROR: Unable to execute SonarQube
ERROR: Caused by: Fail to get bootstrap index from server
ERROR: Caused by: connect timed out
ERROR: 
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
WARN: Unable to locate 'report-task.txt' in the workspace. Did the SonarScanner succedeed?
ERROR: SonarQube scanner exited with non-zero code: 1
Recording test results
Finished: FAILURE

**Comment by raviops100** [comment]
Please follow below steps
Go to Jenkins :
==================
1.go to new project :: free style project 

2.go to source code management

3. git hub url of  your project

https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-simple

4.go to build environmrnt
go to maven pacakge ===> goals package
5.add buid step
	in anaslisis prporties
projeckey=sonar
projectname=projectname
sonarprojecr version=1.0
soanar sources= .

6.now build the code 
7.it will show the test results in sonar qube UI
====> Hope this works <=========

**Comment by manikantagaddam** [comment]
Is dis closed ?
