### ISSUE TITLE
not able to login into machine, getting as permission denied when typed ssh ansible@ip

### ISSUE THREAD

**Issue by Rupini93** [QT-DevOps/DevOpsIssues#671]
not able to login into machine, getting as permission denied when typed ssh ansible@ip.
my ping command was successful on both the machines.
![Screenshot (15)](https://user-images.githubusercontent.com/57709400/70042625-34750600-15e5-11ea-973a-30c51bfa93aa.png)

**Comment by srmanikanta** [comment]
please check the following steps:
* create a user in both ansible control server and node using "adduser"  command this command will create a home directory and password for the user.
* once you create the user add the user to "visudo file with nopasswd 
* do the password authentication yes in /etc/ssh/sshd_config  file of your node
* restart the service sshd
above 3 steps are common for both acs and node
* now goto acs  Install ansible 
* now goto node Install python
* once you install ansible in your acs goto ansible user and generate ssh-keygen
* copy the public key using ssh-copy-id  into your node
* check the node is connected or not, from your acs ssh user@ip
* check ansible -m ping all
if it is working fine all your configuration is successful
please check all the steps I think you missed in some step
if you got the solution for this please ignore this and please close the issue.
