### ISSUE TITLE
chef recipes error

### ISSUE THREAD

**Issue by gatkaraju** [QT-DevOps/DevOpsIssues#673]
after created multiple recipes, iam trying to upload recipes to chef server, showing this error what can i do ???
![Screenshot (9)](https://user-images.githubusercontent.com/57340047/70051213-a43fbc80-15f6-11ea-992e-d356adc8350f.png)

**Comment by RahulAnita** [comment]
I recommend trying to do berks upload with a new directory and clean Berksfile generated by berks cookbook. If that works then slowly add lines you want to your Berksfile to discover if perhaps something is wrong in the file.

**Comment by gatkaraju** [comment]
> 
> 
> I recommend trying to do berks upload with a new directory and clean Berksfile generated by berks cookbook. If that works then slowly add lines you want to your Berksfile to discover if perhaps something is wrong in the file.

i changed version its working now....

and how to remove cookbooks in manage.chef.io server??

**Comment by srmanikanta** [comment]
if you got the solution from the above issue please close the issue
