### ISSUE TITLE
JENKINS SETUP ERROR

### ISSUE THREAD

**Issue by bhargavsindu** [QT-DevOps/DevOpsIssues#674]
after installing jenkins im unable to install suggested plugins or selected plugins. getting below error while clicking install suggested plugins
![image](https://user-images.githubusercontent.com/49969967/70069460-ce55a680-1617-11ea-99d2-5e3e80cafba0.png)

**Comment by raviops99** [comment]
Hi Bhargavi,
Are you installing Jenkins on ubuntu or redhat can you post versions of Linux

**Comment by srmanikanta** [comment]
Try again to installing the plugins. some times it is happening because network or the jenkins server issue.
if you already done this please close the issue.
