### ISSUE TITLE
getting error while bootstraping the node or in knife node list

### ISSUE THREAD

**Issue by harikumars169** [QT-DevOps/DevOpsIssues#676]
![Capturedd](https://user-images.githubusercontent.com/57283736/70118527-31822000-168e-11ea-977a-e967eaa8a69c.PNG)

**Comment by srmanikanta** [comment]
bootstraping process:
* copy the ec2(node) pem file  to your chef-repo folder
* knife bootstrap `nodeipaddress` -U `username` -i `pemfilepath` -N `nodename/nodeprivatedns` --sudo
* goto chef server and check your node is added or not, if the node is added successfully 
* knife node list command display  the nodes added by chef server
