### ISSUE TITLE
terraform apply error for grafana 

### ISSUE THREAD

**Issue by saniic** [QT-DevOps/DevOpsIssues#677]
I have done some changes in Prometheus.tf file for installing kube-state-metrics did terraform plan/apply. I am getting below error with Grafana. i didn't made any changes in grafana or anywhere other than promethues file. Could someone can help with below error?

=======================
Plan: 9 to add, 1 to change, 2 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

null_resource.grafana: Destroying... (ID: 7857656263094496211)
null_resource.grafana: Destruction complete after 0s
module.resource_tagging.null_resource.check_tags_against_tagging_standards: Destroying... (ID: 292482023257138172)
module.resource_tagging.null_resource.check_tags_against_tagging_standards: Destruction complete after 0s
local_file.journalbeat_value_yaml: Creating...
==
1 error(s) occurred:

* null_resource.grafana: Error running command '        # Need to have a secret created for chart to get deployed. Secret contents can later be updated and pod recreated.
        kubectl create namespace grafana|| echo "^ Error expected if resource is being updated ^";
        kubectl apply -f "/home/saneesh/cluster-common/common/templates/grafana/dashboards/resource-limit-dashboards.yaml";
        kubectl -n grafana create secret generic grafana-smtp --from-literal="user=placholder" --from-literal="password=placeholder"||echo "^ Error expected if resource is being updated ^";
        helm upgrade --install --tiller-namespace tiller-full --force --namespace grafana \
        --kube-context=dev-ind.vet-dev.digitalecp.mcd.com \
        --values "/home/saneesh/cluster-common/common/.cache/grafana_values.yaml" \
        grafana stable/grafana --version=2.3.3
    ': exit status 1. Output: Error from server (AlreadyExists): namespaces "grafana" already exists
^ Error expected if resource is being updated ^
configmap/resource-limit-dashboards unchanged
Error from server (AlreadyExists): secrets "grafana-smtp" already exists
^ Error expected if resource is being updated ^
Error: failed to download "stable/grafana" (hint: running `helm repo update` may help)

**Comment by saniic** [comment]
This issue resolved by using helm init command . thanks

**Comment by srmanikanta** [comment]
please close the issue
