### ISSUE TITLE
error while Bootstrapping centos machine of azure account

### ISSUE THREAD

**Issue by srinath426** [QT-DevOps/DevOpsIssues#678]
Tried many times bootstrapping my Centos machine of Azure account,
FYI I tried using username, password and also generating SSH public/Private keys
Please help me to resolve this. here below is the screenshot of error
![Screenshot (2)](https://user-images.githubusercontent.com/58582226/70296978-42f43500-1812-11ea-9488-2ea8ffedc201.png)

**Comment by Abbanapuri** [comment]
knife bootstrap ip --sudo -U username -P password   -N nodename

**Comment by srinath426** [comment]
its not working
![Screenshot (3)](https://user-images.githubusercontent.com/58582226/70686831-75e76e80-1cd3-11ea-9064-41e89714a8bc.png)

**Comment by srinath426** [comment]
> knife bootstrap ip --sudo -U username -P password -N nodename

Its not working
![Screenshot (3)](https://user-images.githubusercontent.com/58582226/70686862-8861a800-1cd3-11ea-99a8-901b2ba11cbf.png)
