### ISSUE TITLE
ansible node is taking too long to ping and the playbook is failing

### ISSUE THREAD

**Issue by tabrez78** [QT-DevOps/DevOpsIssues#679]
ansible-playbook -i hosts lamp.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [192.168.0.146]
ok: [192.168.0.86]
fatal: [192.168.0.237]: FAILED! => {"failed": true, "msg": "ERROR! Timeout (12s) waiting for privilege escalation prompt: "}

TASK [install apache and restart] **********************************************
fatal: [192.168.0.86]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"' failed. The error was: ERROR! error while evaluating conditional (ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"): ERROR! 'ansible_facts' is undefined\n\nThe error appears to have been in '/home/ansadmin/playbook/lamp.yml': line 5, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    tasks:\n      - name: install apache and restart\n        ^ here\n"}
fatal: [192.168.0.146]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"' failed. The error was: ERROR! error while evaluating conditional (ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"): ERROR! 'ansible_facts' is undefined\n\nThe error appears to have been in '/home/ansadmin/playbook/lamp.yml': line 5, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    tasks:\n      - name: install apache and restart\n        ^ here\n"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
192.168.0.146              : ok=1    changed=0    unreachable=0    failed=1
192.168.0.237              : ok=0    changed=0    unreachable=0    failed=1
192.168.0.86               : ok=1    changed=0    unreachable=0    failed=1

**Comment by Abbanapuri** [comment]
share playbook

**Comment by tabrez78** [comment]
---
  - hosts: all
    become: yes
    tasks:
      - name: install apache and restart
        package:
          name: "{{package_name}}"
          state: present
        notify:
          - restart and enable apache
        when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"
      - name: install php modules
        package:
          name: "{{item}}" 
          state: present
        notify:
          - restart and enable apache  
        when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"
        loop: "{{php_module}}"
    handlers:    
      - name: restart and enable apache
        service:
          name: "{{package_name}}"
          enabled: yes
          state: restarted
          when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"

**Comment by tabrez78** [comment]
---
- hosts: webservers
  become: yes
  tasks:
    - name: install apache and restart
      package:
        name: "{{ package_name }}"
        state: present
      notify:
        - restart and enable apache
      when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"
    - name: install php modules
      package:
        name: "{{ item }}"
        state: present
      loop: "{{ php_module }}"
      notify:
        - restart and enable apache
     when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"
  handlers
    - name: restart and enable apache
      service:
        name: "{{ package_name }}"
        enabled: yes
        state: restarted
      when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"






This is the output

login as: ansadmin
     ┌────────────────────────────────────────────────────────────────────┐
     │                        • MobaXterm 11.1 •                          │
     │            (SSH client, X-server and networking tools)             │
     │                                                                    │
     │ ➤ SSH session to ansadmin@192.168.0.180                            │
     │   • SSH compression : ✔                                            │
     │   • SSH-browser     : ✔                                            │
     │   • X11-forwarding  : ✘  (disabled or not supported by server)     │
     │   • DISPLAY         : 192.168.0.198:0.0                            │
     │                                                                    │
     │ ➤ For more info, ctrl+click on help or visit our website           │
     └────────────────────────────────────────────────────────────────────┘

Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-142-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

157 packages can be updated.
102 updates are security updates.

New release '18.04.3 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


Last login: Thu Dec 19 18:51:57 2019
ansadmin@ansible-server:~$ cd playbook/
ansadmin@ansible-server:~/playbook$ ll
total 36
drwxrwxr-x 4 ansadmin ansadmin 4096 Dec 19 21:33 ./
drwxr-xr-x 7 ansadmin ansadmin 4096 Dec 19 21:33 ../
drwxrwxr-x 2 ansadmin ansadmin 4096 Dec  8 21:57 group_vars/
-rw-rw-r-- 1 ansadmin ansadmin  117 Dec 19 19:21 hosts
drwxrwxr-x 2 ansadmin ansadmin 4096 Dec  6 20:25 host_vars/
-rw-rw-r-- 1 ansadmin ansadmin  844 Dec 19 21:33 lamp.yml
-rw-rw-r-- 1 ansadmin ansadmin  300 Nov 26 22:31 myfirst.yml
-rw-rw-r-- 1 ansadmin ansadmin  977 Dec 19 20:14 newlamp.yml
-rw-rw-r-- 1 ansadmin ansadmin  129 Dec 19 20:15 tree.yml
ansadmin@ansible-server:~/playbook$ cat lamp.yml
---
-  hosts: webservers
   become: yes
   tasks:
     - name: install apache and restart
       package:
         name: "{{ package_name }}"
         state: present
       notify:
         - restart and enable apache
       when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"
     - name: install php modules
       package:
         name: "{{ item }}"
         state: present
       loop: "{{ php_module }}"
       notify:
         - restart and enable apache
       when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"
   handlers:
     - name: restart and enable apache
       service:
         name: "{{ package_name }}"
         enabled: yes
         state: restarted
       when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"
ansadmin@ansible-server:~/playbook$ vi lamp.yml
ansadmin@ansible-server:~/playbook$ ansible-playbook -i hosts lamp.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [192.168.0.237]
ok: [192.168.0.86]
ok: [192.168.0.146]

TASK [install apache and restart] **********************************************
fatal: [192.168.0.86]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"' failed. The error was: ERROR! error while evaluating conditional (ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"): ERROR! 'ansible_facts' is undefined\n\nThe error appears to have been in '/home/ansadmin/playbook/lamp.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: install apache and restart\n      ^ here\n"}
fatal: [192.168.0.146]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"' failed. The error was: ERROR! error while evaluating conditional (ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"): ERROR! 'ansible_facts' is undefined\n\nThe error appears to have been in '/home/ansadmin/playbook/lamp.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: install apache and restart\n      ^ here\n"}
fatal: [192.168.0.237]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"' failed. The error was: ERROR! error while evaluating conditional (ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"): ERROR! 'ansible_facts' is undefined\n\nThe error appears to have been in '/home/ansadmin/playbook/lamp.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: install apache and restart\n      ^ here\n"}

PLAY RECAP *********************************************************************
192.168.0.146              : ok=1    changed=0    unreachable=0    failed=1
192.168.0.237              : ok=1    changed=0    unreachable=0    failed=1
192.168.0.86               : ok=1    changed=0    unreachable=0    failed=1

ansadmin@ansible-server:~/playbook$ vi lamp.yml
ansadmin@ansible-server:~/playbook$

**Comment by tabrez78** [comment]
---
-  hosts: webservers
   become: yes
   tasks:
     - name: install apache and restart
       package:
         name: "{{ package_name }}"
         state: present
       notify:
         - restart and enable apache
       when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"
     - name: install php modules
       package:
         name: "{{ item }}"
         state: present
       loop: "{{ php_module }}"
       notify:
         - restart and enable apache
       when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"
   handlers:
     - name: restart and enable apache
       service:
         name: "{{ package_name }}"
         enabled: yes
         state: restarted
       when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"

**Comment by tabrez78** [comment]
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [192.168.0.237]
ok: [192.168.0.86]
ok: [192.168.0.146]

TASK [install apache and restart] **********************************************
fatal: [192.168.0.86]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"' failed. The error was: ERROR! error while evaluating conditional (ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"): ERROR! 'ansible_facts' is undefined\n\nThe error appears to have been in '/home/ansadmin/playbook/lamp.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: install apache and restart\n      ^ here\n"}
fatal: [192.168.0.146]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"' failed. The error was: ERROR! error while evaluating conditional (ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"): ERROR! 'ansible_facts' is undefined\n\nThe error appears to have been in '/home/ansadmin/playbook/lamp.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: install apache and restart\n      ^ here\n"}
fatal: [192.168.0.237]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"' failed. The error was: ERROR! error while evaluating conditional (ansible_facts['os_family'] == \"Debian\" or ansible_facts['os_family'] == \"RedHat\"): ERROR! 'ansible_facts' is undefined\n\nThe error appears to have been in '/home/ansadmin/playbook/lamp.yml': line 5, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: install apache and restart\n      ^ here\n"}

PLAY RECAP *********************************************************************
192.168.0.146              : ok=1    changed=0    unreachable=0    failed=1
192.168.0.237              : ok=1    changed=0    unreachable=0    failed=1
192.168.0.86               : ok=1    changed=0    unreachable=0    failed=1
