### ISSUE TITLE
Unable to start service apache2: Job for apache2.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by Rameshdutt80** [QT-DevOps/DevOpsIssues#68]
Written Yaml code as given the below
---
- hosts: all
  become: yes
  tasks:
  - name: installing apach2 and update packages
    apt:
      name: apache2
      update_cache: yes
  - name: apache2 restarted
    service:
      name: apache2
      enabled: yes
      state: restarted
  - name: Php installing and adding additions packages to it
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - php
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql
  - name: apache2 restarting again
    service:
      name: apache2
      enabled: yes
      state: restarted

After executing the ansible-playbook 
getting error as givne in the below screen shot

![image](https://user-images.githubusercontent.com/37854691/43182153-e24c7d72-8ffd-11e8-9ac7-a4e7bac6b3ea.png)

**Comment by devopsawsazure** [comment]
![image](https://user-images.githubusercontent.com/39402697/43307037-ba0ef116-919a-11e8-89ce-940a85777274.png)
Not yet installed apache2(state: present) not given ,but trying to restart.

**Comment by shaikkhajaibrahim** [comment]
state: present is default.
No need for present.

My doubt is regarding configuration.

Can you share results of ansible -m ping all
________________________________

**Comment by Rameshdutt80** [comment]
![image](https://user-images.githubusercontent.com/37854691/43352825-7d877e54-9247-11e8-89b5-e23fd96a10c0.png)


And now the above error not came when i used handlers in the playbook yml file

**Comment by shaikkhajaibrahim** [comment]
Ok Great. But that has no dependency on handlers
