### ISSUE TITLE
SonarQube not working in Pipeline

### ISSUE THREAD

**Issue by humblemetsuke** [QT-DevOps/DevOpsIssues#680]
pipeline {
         agent any
         stages {
                 stage('Checkout') {
                 steps {
                     echo 'Retrieving Jenkinsfile from the github repository.'
                   checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'LocalBranch', localBranch: 'dummy']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/humblemetsuke/coursework_2']]])
                 }
                 }
                  
        stage('SonarQube') {
    environment {
        scannerHome = tool 'SonarQube'
    }
    steps {
        withSonarQubeEnv('SonarQube') {
            sh "${scannerHome}/bin/sonar-scanner"
        }
        timeout(time: 10, unit: 'MINUTES') {
            waitForQualityGate abortPipeline: true
        }
    }
}

Returns error message:

SonarQube installation defined in this job (sonarqube) does not match any configured installation. Number of installations that can be configured: 1.

If you want to reassign jobs to a different SonarQube installation, check the documentation under https://redirect.sonarsource.com/plugins/jenkins.html

1) have enabled QualityGate webhook in Jenkins.
2)Manage Jenkins > Configure System > SonarQube servers value is SonarQube.
3)Manage Jenkins > Global Tool Configuration > SonarQube Scanner value is SonarQube.

Not sure what is causing issue.

**Comment by Abbanapuri** [comment]
please check configure system 
         what is the name you given to  sonarqube
