### ISSUE TITLE
how to make machine work by getting "changed=1". As i got changed=0, means no work has done by that machine.

### ISSUE THREAD

**Issue by Rupini93** [QT-DevOps/DevOpsIssues#681]
How to make machine work by getting "changed=1". As  I  got "changed=0",  that means no work has done by that machine. Can I Know where i have been messed.
![Screenshot (16)](https://user-images.githubusercontent.com/57709400/70423214-13a02b00-1a93-11ea-981b-b46dff3e1bcd.png)

**Comment by Abbanapuri** [comment]
please share playbook
