### ISSUE TITLE
How to expand environement variables in string parameters of Jenkins?

### ISSUE THREAD

**Issue by uday1kiran** [QT-DevOps/DevOpsIssues#682]
For a Jenkins Free-style job, there is a string parameter as
Path1 = C:\users\uday\OneDrive\Share1\Sharepath\mydata\data1\syncfolder

The above value will be provided.
Is there any way, I can specify the username dynamically to this variable?

Path1=%userprofile%\OneDrive\Share1\Sharepath\mydata\data1\syncfolder

If I directly provide this, it is not expanding the value at runtime.

**Comment by srmanikanta** [comment]
hi udaykiran
In the string parameter you have specify the default value and whenever you are executing this it will take the default value if you did not pass anything, overhere you have to change the default value to user defined value.
if you are resolve this please close the issue.

**Comment by uday1kiran** [comment]
Hi srmanikanta,

that's not my question

Let's say,  I have a parameter.
Path1
Default value is : C:\users\uday\OneDrive\Share1\Sharepath\mydata\data1\syncfolder

Instead, If I set default value as:
C:\users\%username%\OneDrive\Share1\Sharepath\mydata\data1\syncfolder

username -- represents environment variable for current user on windows.

Will, hot to tell my job to expand that value.Present it is taking the string as is.

**Comment by srmanikanta** [comment]
hi uday kiran,
use this `C:\Users\%USERNAME%\OneDrive\Share1\Sharepath\mydata\data1\syncfolder`

**Comment by uday1kiran** [comment]
Hi manikanta,

Thank you, but it is not expanding through jenkins.

**Comment by debasis-gif** [comment]
Hi Uday,

Can you use the following in the pipeline script :

// Define variable
def user_name = "uday"
def Path1=C:\Users\${user_name}\OneDrive\Share1\Sharepath\mydata\data1\syncfolder

pipeline {
  ….
   steps {
      echo "Path is: ${Path1}"
     }
    }
  }
}

Please let me know if this is what you were asking for

**Comment by srmanikanta** [comment]
hi uday kiran, please close the issue.

**Comment by uday1kiran** [comment]
It is not working to close
