### ISSUE TITLE
Choco is not recognizing in Windows Powershell, but when i try with CMD it is working fine

### ISSUE THREAD

**Issue by vjulakanti** [QT-DevOps/DevOpsIssues#683]
I opened **WindowsPowerShell** terminal Run as administrator mode,then i used **below command**. it is executed and it is showing like **Chocolaty is now Ready**.
![Powershell1](https://user-images.githubusercontent.com/10668742/70610141-0b79f400-1c29-11ea-836a-1883aa3f8b8f.PNG)
then i closed this terminal and opened new terminal, then used below commands but i getting error. once check and tell me how to solve.
![Powershell2](https://user-images.githubusercontent.com/10668742/70610607-e33ec500-1c29-11ea-856d-7309841f0f68.PNG)

**Comment by anupam-fl** [comment]
Hi vjulakanti,
Did you reboot your system? Once you reboot, please check if the choco --version command works.

Secondly, chocolatey may not have been updated in the environment path variable. To check the path, open Windows Powershell.
![image](https://user-images.githubusercontent.com/58856475/70819196-97179000-1da3-11ea-9285-bdc31d232272.png)

 Please type **$env:path**
Are there entries for chocolatey? 

Thanks.

**Comment by srmanikanta** [comment]
To install chocolatey in windows two methods 
1. command prompt
copy the below command and open command prompt as an administrator and paste the command
once the choco installation is successful then close the command prompt and reopen again.   

```@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin" ```

2. power shell
copy the below command and open powershell as an administrator and paste the command
once the choco installation is successful then close the power shell  and reopen again. 
```
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))```

No need to set a path for chocolatey, in windows  path will be taken automatically using choco commad.   
you should follow any of the above method. if you did already please close the issue.

**Comment by anupam-fl** [comment]
> To install chocolatey in windows two methods
> 
> 1. command prompt
>    copy the below command and open command prompt as an administrator and paste the command
>    once the choco installation is successful then close the command prompt and reopen again.
> 
> `@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin" `
> 
> 1. power shell
>    copy the below command and open powershell as an administrator and paste the command
>    once the choco installation is successful then close the power shell  and reopen again.
> 
> ```
> Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))```
> 
> you should follow any of the above method. if you did already please close the issue.
> ```
 Hello srmanikanta,
vjulakanti tried power shell method  but is unable to invoke "choco" command from powershell. She's ,however, able to do it from the command prompt. I am guessing that the path variables are not set properly. Let's wait for her response to check on the path.

Thanks.

**Comment by srmanikanta** [comment]
No need to set a path for chocolatey, in windows  path will be taken automatically using choco commad
If you got the answer for above problem please close the issue
