### ISSUE TITLE
How to pass values when debugging python code in Visual Studio Code?

### ISSUE THREAD

**Issue by anupam-fl** [QT-DevOps/DevOpsIssues#685]
Hi,
When we debug a python code in Visual Studio Code (VSC), is there a way to pass values to the program as an input? For example, let us take the add.py program below, where we pass 10,20, 30. How can we pass 10,20,30 in debug mode? 

![image](https://user-images.githubusercontent.com/58856475/70820884-b3b5c700-1da7-11ea-9dfd-384605a95024.png)

Thanks.

**Comment by shaikkhajaibrahim** [comment]
Use import pdb and pdb.set_trace to set values
