### ISSUE TITLE
No X11 DISPLAY variable was set, but this program performed an operation which requires it.

### ISSUE THREAD

**Issue by ramana152** [QT-DevOps/DevOpsIssues#686]
Hello All,
 
          Am trying creating docker container for JMETER, but am getting error while creating docker container.
Error,
No X11 DISPLAY variable was set, but this program performed an operation which requires it.

Below the screenshot.
![XDISPLAY11 error](https://user-images.githubusercontent.com/39365142/70997565-687b1b80-20fb-11ea-9c8a-3e5b14453a29.PNG)

**Comment by srmanikanta** [comment]
hi ramana,
follow this link [Click Here](https://stackoverflow.com/questions/662421/no-x11-display-variable-what-does-it-mean) 
if you are resolve the issue please close the issue.
