### ISSUE TITLE
connection reset

### ISSUE THREAD

**Issue by rajagdevops** [QT-DevOps/DevOpsIssues#687]
client_loop: send disconnect: Connection reset by peer

i am getting this message  when i connected to server in cloud. To maintain proper connection without interruption is there any way?
![Screenshot (6)_LI](https://user-images.githubusercontent.com/59006742/71060520-b7709180-218b-11ea-993e-bdb8d77b35f4.jpg)

**Comment by anupam-fl** [comment]
Hello rajagdevops ,
Please check that you have a steady connection to the Internet. 

If your session is idle and you get the "connection reset" message, then the following post may help you: https://forums.aws.amazon.com/message.jspa?messageID=486213

Thanks.
