### ISSUE TITLE
Need Docker video which is happened on Feb 16th 2019

### ISSUE THREAD

**Issue by solarisadminster** [QT-DevOps/DevOpsIssues#688]
Hello Sir, 

I am a old student, who studied DEVOPS course on Jan & Feb 2019 batch. Now I am again going through the videos which you have shared. In that the session the docker session which is happened on Feb 16th 2019 is missing. Could you please send this one day video ( Feb 16th 2019 ) to my email ID - solarisadminster@gmail.com

Thanks for the help 

Thanks and Regards,
Pratap Chandran

**Comment by srmanikanta** [comment]
sir if you have any videos related issue please contact this number 9963799240
please close the issue.
