### ISSUE TITLE
Kubernetes metrics server pod keep on crashing

### ISSUE THREAD

**Issue by vkatukam** [QT-DevOps/DevOpsIssues#689]
I have cloned Kubernetes-sigs/metrics-server repo and ran all manifests in 1.8+. 
metrics server pod keeps on crashing with the below error.

panic: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication: dial tcp 10.96.0.1:443: connect: connection refused

Even I have disabled the TLS certificate verification.

**Comment by srinivasareddyasha** [comment]
How u installed metrics server in kubernetes?
Use Helm to install metrics-server

**Comment by vkatukam** [comment]
I was tried with helm and using manifest as well.

**Comment by srmanikanta** [comment]
hi vkatukam,
 if resolve the issue, please close the issue or update the issue if you are not resolve.
