### ISSUE TITLE
about jenkins installation

### ISSUE THREAD

**Issue by BALABHASKARARAO** [QT-DevOps/DevOpsIssues#69]
I am using jenksns versin 2.1.X  But i want to install jenksns. 2.7.3 as jenkins as a service in ubuntu 16.04. I tried to found out links this" wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -
sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
sudo apt-get install jenkins,,,"

the above command are giving 2.10.X,, 
give suggestion link to install jenkins 2.7.3 as jenkins as a service..

**Comment by devopsawsazure** [comment]
Replace the stable link with http://pkg.jenkins.io/debian-stable/binary/jenkins_2.7.3_all.deb

**Comment by BALABHASKARARAO** [comment]
E: Malformed entry 1 in list file /etc/apt/sources.list.d/jenkins.list (Suite)
E: The list of sources could not be read.

IT give the the above  error. I Think replacing the above command does not work

**Comment by raviops100** [comment]
Jenkins Debian packages for ubuntu 16.04  

1. wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -

2. Then add the following entry in your   /etc/apt/sources.list   file

go to end of this file add the below entry

deb https://pkg.jenkins.io/debian binary/

3. apt-get update
4. apt-get install jenkins

**Comment by BALABHASKARARAO** [comment]
it works but i gave Jenkins 2.135 version but i Want 2.7.X version jenkins as a service installation commands.

**Comment by shaikkhajaibrahim** [comment]
Post the question to jenkins community as this is very much jenkins documentation
________________________________
