### ISSUE TITLE
how to apply rolling update strategy for one container in a Pod

### ISSUE THREAD

**Issue by vkatukam** [QT-DevOps/DevOpsIssues#691]
I have created two containers in a Pod, i want to apply rolling update strategy to one container only.
below is the manifest file.

apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-rolling-update
 namespace: practice
spec:
 selector:
  matchLabels:
   type: nginx-rolling
 replicas: 4
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxSurge: 1
   maxUnavailable: 1
   container:
    name: nginx
 minReadySeconds: 5
 revisionHistoryLimit: 10
 template:
  metadata:
   labels:
    type: nginx-rolling
  spec:
   containers:
   - name: niginx-test
     image: nginx
   - name: busybox-test
     image: busybox

error: a container name must be specified for pod nginx-rolling-update-6f5f5c8c7b-mmdsk, choose one of: [niginx-test busybox-test]

how do i fix this. any sugesstions,. Thank you.

**Comment by ABBANAPURI0445** [comment]
please pass container name
