### ISSUE TITLE
ansibletower servicenow integration

### ISSUE THREAD

**Issue by satishnbtech** [QT-DevOps/DevOpsIssues#692]
Hi All,
I was trying to ansible tower service now integration by using below URL
I have configured ansible tower and created service now dev instance and followed the documentation steps as per below link, but at step no. 12
I was getting error( auth ivalid of redirect url)
https://www.ansible.com/blog/ansible-servicenow-howto-part-3-making-outbound-restful-api-calls-to-ansible-tower
if anyone aware of this Please help me out.

**Comment by shaikkhajaibrahim** [comment]
Service now support cannot be expected over here.
