### ISSUE TITLE
Error while Installing SonarQube

### ISSUE THREAD

**Issue by manireddyk** [QT-DevOps/DevOpsIssues#693]
Hi,

I tried to install SonarQube on a separate ubuntu machine then the below error occurred while running the command 'sudo apt-get update'.
I have followed the documentation - https://directdevops.blog/2019/01/05/sonarqube/  and I can't find the key there in the official documentation as well.

![SonarQube issue](https://user-images.githubusercontent.com/46611593/71637965-921a6380-2c20-11ea-91d1-3eb260c9642d.JPG)

I have updated the source list as well(please find the below screenshot).

![SonarQube Sourcelist](https://user-images.githubusercontent.com/46611593/71637981-f6d5be00-2c20-11ea-9c98-c62441739641.JPG)

Please let me know how to proceed further.
Thanks,
Mani

**Comment by ABBANAPURI0445** [comment]
please copy this line
deb [trusted=yes] http://downloads.sourceforge.net/project/sonar-pkg/deb  binary/

**Comment by manireddyk** [comment]
Thanks @ABBANAPURI0445
