### ISSUE TITLE
Jenkins node issue

### ISSUE THREAD

**Issue by Harini2196** [QT-DevOps/DevOpsIssues#694]
I have been trying to add centos node to master and i'm facing "known host" issue. Couldn't resolve the issue with the solutions found from google. Please find the screenshot attached and help me resolve the same.
![Centos_node_issue](https://user-images.githubusercontent.com/48150308/71640784-bcb6fb80-2cb6-11ea-84b5-c84fd8e36241.PNG)

**Comment by raviops99** [comment]
Hi harini,
Can you please follow below link
https://support.cloudbees.com/hc/en-us/articles/115000073552-Host-Key-Verification-for-SSH-Agents?mobile_site=true

**Comment by ABBANAPURI0445** [comment]
please copy ssh keys
or please select method called no host verify keys

**Comment by srmanikanta** [comment]
Follow This Below Approach:
Node configuration:
* Install java on node
* create a user named as jenkins (or any name)  in node
* ser the password for jenkins user.
* add the user to the /etc/sudoers file as root user using  `visudo` commad  
* enable password_authentication in /etc/ssh/sshd_config
* restart the `service sshd restart`
Server configuration:
* add the user to the /etc/sudoers file as root user using  `visudo` commad  
* enable password_authentication in /etc/ssh/sshd_config
* restart the `service sshd restart`
*  switch as jenkins user
* try to connect to node manually 
* `ssh <username>@<privateip>` it will ask a password then enter jenkins  user password.
Note: I Think you already knew above things but please cross-check.Above process is for password authentication only. 
If you find the solution for above issue please close the issue.

**Comment by ABBANAPURI0445** [comment]
please close issue
