### ISSUE TITLE
error with artifactory setup

### ISSUE THREAD

**Issue by manireddyk** [QT-DevOps/DevOpsIssues#695]
Hello People,
When I was setting up this artifactory in an ubuntu machine, artifactory service is not getting started.

![Artifactory setup error](https://user-images.githubusercontent.com/46611593/71644441-6afe7900-2c96-11ea-8be5-fa3fb60852a4.JPG)

Executed ''systemctl status artifactory.service" then showing below messages.

![image](https://user-images.githubusercontent.com/46611593/71644471-e2340d00-2c96-11ea-885c-ffd9c8aeed81.png)

 Followed documentation - https://www.jfrog.com/confluence/display/RTF/Installing+on+Linux+Solaris+or+Mac+OS#InstallingonLinuxSolarisorMacOS-ServiceInstallation

Thank you.
Mani

**Comment by ABBANAPURI0445** [comment]
https://computingforgeeks.com/how-to-install-jfrog-artifactory-on-ubuntu/
please follow this doc
take t2.large or medium

**Comment by srmanikanta** [comment]
Minimum requirement for artifactory 64 bit os, 4 cores processor, 4GB RAM 
I think you took t2.micro  this machine is for 1 CPU and 1GB RAM this configuration is not enough for artifactory. Try above configuration.
If you already done this please close the issue.
