### ISSUE TITLE
Docker Build credentials Issue

### ISSUE THREAD

**Issue by Nara-Sagar7** [QT-DevOps/DevOpsIssues#696]
Successfully built af74c129c413
Successfully tagged container:1.0
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Docker Push)
[Pipeline] withCredentials
Masking supported pattern matches of $dockerpassword
[Pipeline] {
[Pipeline] sh
+ docker login -u devops -p {dockepassword}
**WARNING! Using --password via the CLI is insecure. Use --password-stdin.**
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by raviops99** [comment]
Hi Naga sagar,
While giving username and password
Dont give email address as username
Give username of account.

it may work please try.

**Comment by Nara-Sagar** [comment]
I have given username only not email.

**Comment by raviops99** [comment]
Hi ok i will Check is their any oher thing you are missing can you please share pipeline script you have written

**Comment by Nara-Sagar7** [comment]
hi Ravi.
please find the below Jenkins pipeline script which I have written to deploy a docker container.

node('slave') {
    stage('SCM Checkout') {
        git 'https://github.com/Nara-Sagar7/Game-of-life.git'
    }
    stage('Build') {
        sh 'mvn clean package'
    }
    stage('Quality Check') {
        withSonarQubeEnv('SONAR') {
            sh 'mvn sonar:sonar'
        }
    }
    stage('Docker Build') {
        sh 'docker build -t container:1.0 .'
    }
    stage('Docker Push') {
        withCredentials([string(credentialsId: 'docker-password', variable: 'dockerpassword')]) {
            sh "docker login -u sagardevops -p ${dockepassword}"
        }
        sh 'docker push sagardevops/container:1.0 .'
    }

}

**Comment by Nara-Sagar7** [comment]
hi Ravi.
I think I have fixed the issue it the problem with the credentials as well as the docker image tagging now its resolved thanks for your help.
![image](https://user-images.githubusercontent.com/54387478/71763796-19f4bc00-2f06-11ea-92eb-869ed49e6b94.png)
