### ISSUE TITLE
image not creating

### ISSUE THREAD

**Issue by sasireddy24** [QT-DevOps/DevOpsIssues#698]
when i try to build it is showing "error launching source instance : the request launching is not supported
![issue](https://user-images.githubusercontent.com/58424850/71778747-bf2b9500-2fd7-11ea-8aaa-520b7e274104.png)

**Comment by raviops99** [comment]
Hi Sasi,
Can you please share packer file

**Comment by sasireddy24** [comment]
![sas](https://user-images.githubusercontent.com/58424850/71800726-dbced800-307e-11ea-946c-fc33bc636bf7.png)
![sas](https://user-images.githubusercontent.com/58424850/71800770-f99c3d00-307e-11ea-8e8c-f9685991f16e.png)
