### ISSUE TITLE
Docker run issue

### ISSUE THREAD

**Issue by Lokeswararao** [QT-DevOps/DevOpsIssues#699]
Hi 

I've created a Docker file with below information:

FROM tomcat:8.0-jre8
MAINTAINER Lokesh
ADD gameoflife.war /usr/local/tomcat/webapps/gameoflife.war
EXPOSE 8080      
CMD ["cataline.sh","run"]   

now i have build the docker image with below command:
 docker build -t gol:1.0 . -->Successed

after that i ran the docker container:
getting the below error:

ubuntu@ip-172-31-18-75:~$ docker run -p 8080:8080 --name gol1 gol:1.0
docker: Error response from daemon: driver failed programming external connectivity on endpoint gol1 
(ec4ef13e864ded3a7042e395f4a9c286225dc541cb8f707e4e897fb4ffdf1e39): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use.

then i checked if container service running, but the status is CREATED.
ubuntu@ip-172-31-18-75:~$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
cf85096f73fb        gol:1.0             "cataline.sh run"   3 minutes ago       Created                                 gol

![image](https://user-images.githubusercontent.com/26164550/71783025-14cb6600-3007-11ea-8600-88bb9ea85dfd.png)

**Comment by raviops99** [comment]
Hi lokeswararao
Can you please execute below commands
Where you are installed docker
Sudo systemctl stop systemd-resolved
Sudo systemctl disable systemd-resolved
Please try this if it didn't work will try another option

**Comment by Lokeswararao** [comment]
Hi Ravi,
Thanks for your response. But still im facing same issue.Find in the image.
![image](https://user-images.githubusercontent.com/26164550/71796305-0bc2af00-3070-11ea-95dd-53aa617eedc5.png)

**Comment by Lokeswararao** [comment]
Even i have tried with the below commands also:

ubuntu linux kernal version issue with docker
-------------------------------------------- 
sudo apt-get install linux-generic-lts-xenial
sudo reboot

but still same issue.

**Comment by Lokeswararao** [comment]
![image](https://user-images.githubusercontent.com/26164550/71836368-d783d880-30d9-11ea-8668-845f9d53c647.png)

**Comment by raviops99** [comment]
Hi lokeswararao,
Please try below options
1. I feel it is related to port forwarding concept meaning if you want to expose your application to outside world
Syntax
EC2 machine portno: container port number
Can you please try 8085:8080
Try this combination in docker run
2. In other way around if any other container is running with 8080 port 
If you working in practice machine kill all the container what are running
Docker rm -f $(docker ps -aq) which removes all containers now u can start
Docker run with port forwarding 8085:8080
Make sure AWS EC2 instance 8085 port should open in security group
Thanks

**Comment by Lokeswararao** [comment]
![image](https://user-images.githubusercontent.com/26164550/71870063-7b9d6c00-313a-11ea-9081-881d7dcf884b.png)

**Comment by srmanikanta** [comment]
The above issue is for port mapping 
change the port number of your host and container and then try 
`docker run -p <host_port>:<container_port> -name <containername> <imagename>`
if you got the answer for above error please close the issue

**Comment by Lokeswararao** [comment]
Thanks for your suggestions Kalyan, Ravi, Mani..
Now issue got resolved. i have used the below command.
docker run -d -P imagename
