### ISSUE TITLE
Unable to  rm docker containers. Below is the error messages i'm seeing when i run docker rm -f $(docker ps -a -q)

### ISSUE THREAD

**Issue by nadipallibhargavdevops** [QT-DevOps/DevOpsIssues#70]
Error response from daemon: driver "devicemapper" failed to remove root filesystem for b9731c7d8ebesabsr01ec95446hasbeksebnae72304df3ebab72b83a31011cdc20: failed to remove device bne7bc1sbensb5064e61d630530f081b000000ssbdske1d316e6ba7a: devicemapper: Error running DeleteDevice dm_task_run failed

Can any one help me out here ??

**Comment by raviops100** [comment]
Hi Can you please post which docker version have you installed in your machine
and which flavour of Linux and it is version

**Comment by shaikkhajaibrahim** [comment]
Closing the issue as no response
