### ISSUE TITLE
Terraform Aws_provider download error

### ISSUE THREAD

**Issue by praveenkumar9154** [QT-DevOps/DevOpsIssues#700]
when i run terraform init command below error is generated 
please look into this issue 

![image](https://user-images.githubusercontent.com/49840014/71805688-d8424d80-308c-11ea-919d-54f526b2918f.png)

**Comment by raviops99** [comment]
Can you please share teraaform file

**Comment by praveenkumar9154** [comment]
this is my terraform file, please look into this 

provider "Aws" {
  access_key= ""
  secret_key=""
  region="ap-south-1"
}

resource "aws_seurity_group" "allow_all" {
  name = "allow_all"
  description= "Allow all inbound traffic"

igress {
    from_port = 0
    to_port = 65535
    portocol = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
}
tags {
    name = "allow_all"
}
}

**Comment by srmanikanta** [comment]
praveen kumar, I thinks you forgot the command sysntax:
`terraform init .` 
. (dot) is your current directory where terraform files are stored 
follow above systax it is working if you any doubts on terraform commands systax go through 
terraform --help
terraform  init --help --> see the command usage
if you got the answer for above error please close the issue

**Comment by praveenkumar9154** [comment]
already am in the current directory, that's y I was given dot,
but I get this error repeatedly.

**Comment by Vinothkuppuswamy** [comment]
go back to JAN-19 directory. you have copied the path till hello.tf file and trying to execute INIT command. From below path execute the INIT command.
E:\devops\terraform\JAN-19 > terraform init .

**Comment by praveenkumar9154** [comment]
hello.tf is my directory , under hello.tf i have my terraform file...

**Comment by MakrandakaMax** [comment]
error in the first line "Aws" should be "aws". The "a" should be small letter.

**Comment by praveenkumar9154** [comment]
Tq u for giving solution....its working wowwww

**Comment by MakrandakaMax** [comment]
I hope the error didn’t annoy you too much 😝😝😝 speaking from experience haha. Do close this issue as its resolved. 👍👍

**Comment by praveenkumar9154** [comment]
i received lot of experience form this issue  😝...
