### ISSUE TITLE
Connection Timed out Issue

### ISSUE THREAD

**Issue by SuneelKallur** [QT-DevOps/DevOpsIssues#702]
![Connection Timed out](https://user-images.githubusercontent.com/59555105/71820989-e1e0ab00-30b6-11ea-8b44-6ce8f2052d7e.png)
When i am trying to connect Ubuntu from git bash using the following command

$ ssh -i ~/Downloads/suneel_keypair.pem ubuntu@13.232.133.128
ssh: connect to host 13.232.133.128 port 22: Connection timed out

Following are the few , while i notice this will repeat so many times

1. Mostly when try to start new Ubuntu VM 
2. After sometime while i was working on other things and keep git bash on idle
3. when trying to connect from jenkins master to nodes

**Comment by raviops99** [comment]
Hi suneel,

Check out firewall status with below code
Sudo ufw status
It it showing  some fire wall deactivate
Sudo ufw disable
Then try ssh user@ipaddress
2. While working on other things 
In git bash click on top command or ping google.com i will not go in to idle state please try

**Comment by SuneelKallur** [comment]
If i can't able to connect to ubuntu machine 
how can i check Sudo ufw status and Sudo ufw disable

ping google.com
is working fine

It showing as Connected

Still Not working for me , do i need to create a new ubuntu vm or do i need to delete old pem file
and create new one 

Pls help me on this

**Comment by srinivasareddyasha** [comment]
ping me that ip from your local machine
and also check the connectivity using telnet or nc

**Comment by Vinothkuppuswamy** [comment]
Please check Configure Security Group type that you gave SSH or all services while creating an EC2 Instance. I also once got the same error then I have deleted instance and created one with type All services and source as anywhere then it worked for me

**Comment by SuneelKallur** [comment]
Hi Vinoth ,

Thanks for the response 
I had done deleting the entire instance ,keys and re-created the process 

it will work fine for an hour or above 
in continuation process while working , i getting this issue

**Comment by SuneelKallur** [comment]
Hi Ravi ,

Thanks for the response

when i execute Sudo ufw status
it is already showing as inactive

after this , i am not getting this issue frequently 

it is normal , git base connection lost when we keep idle , that i am getting

**Comment by ABBANAPURI0445** [comment]
please verify vpc
internetgateway
routetable
