### ISSUE TITLE
Failed to get existing workspaces: NoSuchBucket: The specified bucket does not exist

### ISSUE THREAD

**Issue by saniic** [QT-DevOps/DevOpsIssues#703]
Terraform init throwing error 
Failed to get existing workspaces: NoSuchBucket: The specified bucket does not exist
        status code: 404, request id: BDCF876CA393B347, host id: 986wbciCWo1988e+kIjxbqHjahhZKK5ioShy1fu9KRyboO+6inlT5hXQZYnlhF5NOI0XjgDUgHk=
		
		
Below is my configuration (Terraform v0.11.14)
=============================================
main.tf
-------

resource "aws_subnet" "mysubnet" {
    vpc_id = "${aws_vpc.myvpc.id}"
    cidr_block = "10.10.0.0/24"

    tags  {
        Name = "mysubnet"
    }
}

# Use the below module to create s3 bucket and DynamoDB 

module s3_backend {
  source                      = "youngfeldt/backend-s3/aws"
  version                     = ">= 1.0.0"
  backend_s3_bucket           = "qtterraformstoragekooi"
  backend_dynamodb_lock_table = "qtterraformlockfilekooi"
  create_dynamodb_lock_table  = "true"
  create_s3_bucket            = "true"
  s3_key                      = "backenddemo"
}

variable.tf
----------
variable "accesskey" {
    type = "string"
}

variable "secretkey" {
    type = "string"
}

variable "region" {
    type = "string" 
}

backend.tf
---------
terraform {
  backend "s3" {
    bucket = "qtterraformstoragekooi"
    key    = "backenddemo"
  }
}

terraform.tfvars
---------------
accesskey = "123456"
secretkey = "12345678904a3J+HDZwALO5Zc"

=====================================

PS C:\Sani\Study> terraform init --backend-config='access_key=123456' --backend-config='secret_key=12345678904a3J+HDZwALO5Zc' --backend-config='dynamodb_table=qtterraformlockfilekooi'
Initializing modules...
- module.s3_backend
  Found version 1.3.3 of youngfeldt/backend-s3/aws on registry.terraform.io
  Getting source "youngfeldt/backend-s3/aws"

Initializing the backend...
region
  The region of the S3 bucket.

  Enter a value: us-east-1

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Failed to get existing workspaces: NoSuchBucket: The specified bucket does not exist
        status code: 404, request id: BDCF876CA393B347, host id: 986wbciCWo1988e+kIjxbqHjahhZKK5ioShy1fu9KRyboO+6inlT5hXQZYnlhF5NOI0XjgDUgHk=
		
		
===============

**Comment by ABBANAPURI0445** [comment]
no bucket is available
