### ISSUE TITLE
==> amazon-ebs: Warning: apt-key output should not be parsed (stdout is not a terminal)

### ISSUE THREAD

**Issue by tunkpavan** [QT-DevOps/DevOpsIssues#704]
I am trying to install Jenkins using Shell Script but getting error please tell me what is a issue in the script file :

### 
![jenkins-install-issue](https://user-images.githubusercontent.com/59603032/71886534-61778400-3162-11ea-8b6d-c454d5b8a726.PNG)
My script : 
#!/bin/bash
sudo apt-get update
sudo apt-get install openjdk-8-jdk -y
sudo apt-get install software-properties-common -y
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
echo 'deb https://pkg.jenkins.io/debian-stable binary/' | sudo tee -a /etc/apt/sources.list\"
sudo apt-get update
sudo apt-get install jenkins -y

#######################################

My Packer File :+1: 

{
    "builders": [
        {
            "type": "amazon-ebs",
            "ami_name": "tomcatforpacker",
            "ami_description": "tomcat from packer",
            "access_key": "1234454",
            "secret_key": "34354245354646464",
            "region": "us-west-2",
            "instance_type": "t2.micro",
            "source_ami": "ami-06d51e91cea0dac8d",
            "ssh_username": "ubuntu"

    }],
    "provisioners": [
        {
            "type": "shell",
            "script": "./installjenkins.sh"
        }
    ]
}

Please any one help me out with this issue ?

**Comment by ABBANAPURI0445** [comment]
please check /etc/apt/sorces.list
add or not

**Comment by srmanikanta** [comment]
please manually execute the below command 
 ```
echo 'deb https://pkg.jenkins.io/debian-stable binary/' | sudo tee -a /etc/apt/sources.list"
 ```
and check this is command is executed successfully or not
please close the issue if  solved
