### ISSUE TITLE
how to use map datatype with provision

### ISSUE THREAD

**Issue by saniic** [QT-DevOps/DevOpsIssues#705]
// tfvars file hhaving below values

tags {
#Mandatory tags
Environment = "US-EAST-DEV-US-VET-AECP-DEVCLUSTERINFRASTRUCTURE"
GBL = "195500855387"
ApplicationID = "APP0012189"
Owner = "US-VET-INFRASUPPORT@us.mcd.com"
"Patch Group" = "Not-Patched-By-2W"
"cpm backup" = "mcds_us_none_1_non_prod_607546651489"

#Additional tags
Name = "US-EAST-DEV-US-VET-AECP-DEVCLUSTERINFRASTRUCTURE"
ManagedBy = "Terraform"
Cluster = "DEV"
}

// variable.tf file having below

# Variables for common tagging module
variable "tags" {
type = "map"
description = "Tags to be passed into the common tagging Terraform module"

// When ai am changing any of the value in tfvars file, it should update kops cluster and i m using below null_resource and jq commands for the same. 

resource "null_resource" "tagging_update" {
triggers {
patchGroup = "${var.tags}"
}
provisioner "local-exec" {
command = "kops get ig nodes -o json | jq '.spec.cloudLabels["Patch Group"]="Not-Patched-By-2W"|.spec.cloudLabels["Cluster"]="DEV-IND"'
}
}

>> Instead of hardcoding the command, how can i use variable with jq command here
>> I am little confused with how to use map data type here. 
 
Could you please help in this

**Comment by srmanikanta** [comment]
A map value is a lookup table from string keys to string values. This is useful for selecting a value based on some other provided value.

A common use of maps is to create a table of machine images per region, as follows:

variable "images" {
  type    = "map"
  default = {
    "us-east-1" = "image-1234"
    "us-west-2" = "image-4567"
  }
}
please ensure this variable in your command ["Patch Group"] --> p is small.
if you are resolve the issue please close the issue.

**Comment by srmanikanta** [comment]
click here for [reference](https://medium.com/@jmarhee/using-maps-with-terraform-8b5054e7bcb8)
please close the issue.
