### ISSUE TITLE
Need help in Jenkins

### ISSUE THREAD

**Issue by phanim4u** [QT-DevOps/DevOpsIssues#706]
I'm triggering Jenkins job via Rest API and passing some variable with value in the url which is used in Rest API. my requirement is, the variable which is passed with rest api need to be accessed in jenkins job which is triggered and use that variable value to trigger another RestAPI .

So can any one help me on this.

**Comment by shaikkhajaibrahim** [comment]
Refer this example https://support.cloudbees.com/hc/en-us/articles/218889337-How-to-build-a-job-using-the-REST-API-and-cURL-
