### ISSUE TITLE
terraform init not working

### ISSUE THREAD

**Issue by ghost** [QT-DevOps/DevOpsIssues#707]
The terraform init command doesn't create a state file
![terrafom](https://user-images.githubusercontent.com/58951038/72064483-fb296780-3301-11ea-80eb-fc47422f8996.PNG)
![terrafom1](https://user-images.githubusercontent.com/58951038/72064485-fbc1fe00-3301-11ea-9273-043994dc2350.PNG)

**Comment by MakrandakaMax** [comment]
I think the main.tf file must contain some info like the provider details. I had the same problem with the main.tf file being empty. Try adding the provider details and run the "terraform init ." command.

**Comment by ghost** [comment]
thans buddy
