### ISSUE TITLE
Terraform validate error when using Argument Reference for vpc_id

### ISSUE THREAD

**Issue by MakrandakaMax** [QT-DevOps/DevOpsIssues#708]
![tf1](https://user-images.githubusercontent.com/58435658/72068816-e81b9500-330b-11ea-9d00-d74c405a7cc9.png)

[main.txt](https://github.com/QT-DevOps/DevOpsIssues/files/4040404/main.txt)

Found a solution online, here is the link https://stackoverflow.com/questions/59038537/fix-interpolation-only-expressions-are-deprecated-warning-in-terraform

But when I used the  "terraform 0.12upgrade" command, it validated and apply worked and the vpc and subnets were created. But the curly brackets {} and $ were removed around the reference like below in the main.tf file. 

![tf2](https://user-images.githubusercontent.com/58435658/72152746-e916fa00-33d1-11ea-8986-c888bd14b7a7.png)

But I don't think this can be accepted. Any one has any other solution?

**Comment by MakrandakaMax** [comment]
I think this is the solution https://discuss.hashicorp.com/t/terraform-0-12-14-released/3898

**Comment by Vinothkuppuswamy** [comment]
I have the same issue but was able to go ahead do the tasks as it was only warnings

**Comment by MakrandakaMax** [comment]
I'm guessing maybe there are some changes coming through. If you click the link on my comment just before yours that might give you some info. Maybe Visual Studio Code possibly have not made those changes in their software. Not 100% sure but just my assumption.

**Comment by srmanikanta** [comment]
In terraform version 0.11 interpolation is like this
${var.foo}
but terraform version 0.12 interpolation is like this
var.foo
Note: warning is not a problem it is executed
please close the issue.
