### ISSUE TITLE
Terraform: Variable reference var.accesskey keyword throwing an error

### ISSUE THREAD

**Issue by Vinothkuppuswamy** [QT-DevOps/DevOpsIssues#709]
Hi,

It's not allowing below syntax and showing syntax error.

provider "aws" {
    access_key = var.accesskey
    secret_key = var.secretkey
    region = var.region
}

Instead, **I had to give below, so it worked:**
provider "aws"{
    access_key = "${var.accesskey}"
    secret_key = "${var.secretkey}"
    region = "us-west-2"
}

Input.tf file is below for reference:

variable "accesskey" {
    type = "string"
}
variable "secretkey" {
   type = "string"
}

**Is this an issue with version compatibility?**

 I checked the version as well and it shows the recent one
Terraform v0.12.18
+ provider.aws v2.43.0

**Comment by MakrandakaMax** [comment]
Whats the exact error that your getting?

**Comment by Vinothkuppuswamy** [comment]
Error in VS code shows as "Unknown token: 2:18 IDENT var.access_key". Sorry can't take a snapshot of a screen due to security issue in office laptop

**Comment by amaresh7** [comment]
In input.tf file, you r not mention region as a variable.
eg.
variable "region" {
  default = "ap-south-1"  or type = "string"
}

**Comment by Vinothkuppuswamy** [comment]
Guess, I might be using an older version of VS code. Might need to upgrade VS code and check. CLosing an issue as it's not show stopper
