### ISSUE TITLE
ansible control server is not connecting to ubuntu node after firing ""ansible -m ping all""

### ISSUE THREAD

**Issue by SAURAUT** [QT-DevOps/DevOpsIssues#71]
localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
ansible@ip-172-31-44-83:~$ ansible -m ping all -vvv
Using /etc/ansible/ansible.cfg as config file
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<ip-172-31-31-193.us-east-2.compute.internal> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r -tt localhost '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1532763077.58-206785142359519 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1532763077.58-206785142359519 )" )'
<ip-172-31-31-193.us-east-2.compute.internal> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r -tt ip-172-31-31-193.us-east-2.compute.internal '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1532763077.58-61050749222370 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1532763077.58-61050749222370 )" )'
<localhost> PUT /tmp/tmpdn2rSG TO /home/ansible/.ansible/tmp/ansible-tmp-1532763077.58-206785142359519/ping
<localhost> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r '[localhost]'
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r -tt localhost 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1532763077.58-206785142359519/ping; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1532763077.58-206785142359519/" > /dev/null 2>&1'

****ip-172-31-31-193.us-east-2.compute.internal | UNREACHABLE! => {
    "changed": false,
    "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue",
    "unreachable": true****
}
localhost | SUCCESS => {
    "changed": false,
    "invocation": {
        "module_args": {

**Comment by pravin-07** [comment]
check your cloud instance in security group ssh port from anywhere on both ACS-NODE

**Comment by SAURAUT** [comment]
Yes both acs and node are in security group already still facing issue.

**Comment by sanjaysureshmv** [comment]
The user trying to login to the nodes are showing as None. 

ESTABLISH SSH CONNECTION FOR USER: None

Please share how you manually login to the node from ansible control server

You can also define the user with which you can login to the nodes in the hosts file as follows,

[Redhat]
172.31.26.236 ansible_user=ec2-user ansible_private_key_file=/home/ansible/devops.pem

**Comment by satyatvs** [comment]
Hope you have copied ACS public key to your ubuntu node. also make sure that you have enabled passwordauthentication enabled in sshd_config file. restart sshd services and logout and connect again try the same.

**Comment by pravin-07** [comment]
Just login into root and swith to ansible in your node try it once.

Praveen Kumar Bhunjiya
Mobile No  9826733967/9617879146
Mail-pravinkahar98@gmail.com

**Comment by pravin-07** [comment]
And check sshd_config file whether it is password authentication no or yes.

Praveen Kumar Bhunjiya
Mobile No  9826733967/9617879146
Mail-pravinkahar98@gmail.com
