### ISSUE TITLE
Query about command "Terraform Destroy"

### ISSUE THREAD

**Issue by Vinothkuppuswamy** [QT-DevOps/DevOpsIssues#710]
I tried to execute the command "terraform destroy "aws.plan" and got the feedback saying destroy cant be executed on a plan.

then I have tried "terraform destroy -var "acceskey=access-key" -var "secretkey=secret-key"  ." then it worked and asked for confirmation where I had to mention "Yes" to continue for destroying the resources created.

Curiosity question: If we have to automate Destroy comment in Jenkins, is it possible to do?? and any other ways are there to skip the confirmation where manually "YES" need to be entered.

**Comment by amaresh7** [comment]
I thing destroy cmd only work over apply cmd.!!!!

**Comment by Vinothkuppuswamy** [comment]
Got the answer from today's class session. --auto-approve option will help skip in asking confirmation.

terraform destroy -var "accesskey=your-access-key" -var "secretkey=your-secret-key" --auto-approve .
