### ISSUE TITLE
Failed to connect repository : Failed to create http proxy uri

### ISSUE THREAD

**Issue by Ranganath-Github** [QT-DevOps/DevOpsIssues#711]
While i was trying to connect to github repository from Jenkins, i was encountered an error like, "Failed to connect repository: Failed to create http proxy uri". 

Attached screenshot for your reference.

Could you please let me know the resolution for this issue.

Thanks,
<img width="720" alt="Error_Github_Repo" src="https://user-images.githubusercontent.com/58923523/72217111-1d182980-3550-11ea-8355-d03c53ce7bf7.PNG">

**Comment by ABBANAPURI0445** [comment]
please check github url

**Comment by srmanikanta** [comment]
please refer this link [click here](https://stackoverflow.com/questions/52702032/failed-to-connect-to-repository-failed-to-create-http-proxy-uri)
if solved please close the issue

**Comment by PuskurArunkumar** [comment]
Failed to connect to repository : Failed to create http proxy uri

iama also facing the same erro.
