### ISSUE TITLE
creating lmage from packer using aws

### ISSUE THREAD

**Issue by anilkumar0999** [QT-DevOps/DevOpsIssues#712]
while creating the image using packer getting the following issue.

{
    "builders": [
        {
            "type": "amazon-ebs",
            "ami_name": "awspacker",
            "ami_description": "creating tomcat using

 packer",
            "access_key": "",
            "secret_key": "",
            "region": "ap-south-1",
            "instance_type": "t2.micro",
            "source_ami": "ami-08ddb3f251a88cf33",
            "ssh_username": "ubuntu"

    }]
}

![Capture](https://user-images.githubusercontent.com/47030451/72235465-4b514400-35f8-11ea-86e8-83fb2aad5afe.PNG)

**Comment by ABBANAPURI0445** [comment]
please try this ami-0123b531fc646552f

**Comment by srmanikanta** [comment]
please use the ami in the ap-south-1 region 
if already solved this error please close the issue
