### ISSUE TITLE
Jenkins+Windows node+maven project

### ISSUE THREAD

**Issue by amaresh7** [QT-DevOps/DevOpsIssues#713]
![Annotation 1](https://user-images.githubusercontent.com/58915129/72247189-5d43de80-361a-11ea-8fef-4de05c31e9e0.jpg)
windows node connect to jenkins
![Annotation 2](https://user-images.githubusercontent.com/58915129/72247229-7056ae80-361a-11ea-9093-fd03ad07ab02.png)
pep-2 showing error
![Annotation 3](https://user-images.githubusercontent.com/58915129/72247276-8c5a5000-361a-11ea-902b-d59a909f4cd9.png)
output...

**Comment by amaresh7** [comment]
am using  my laptop as a agent...

**Comment by ABBANAPURI0445** [comment]
you clone public repository so credentials not require

**Comment by srmanikanta** [comment]
Problem is not for credentials please check the below things:
* your job is executed on your node
* if job is executed on your node and you will get  an error please check your build configuration.
if you got a solution to this error please close the issue.
