### ISSUE TITLE
why we get validation warnings in vpc_id, when we do terraform validate

### ISSUE THREAD

**Issue by Rupini93** [QT-DevOps/DevOpsIssues#715]
why we get validation warnings, when we do terraform validate
![Screenshot (64)](https://user-images.githubusercontent.com/57709400/72353496-2cdb6d80-370a-11ea-8355-6959c10cca9b.png)

**Comment by raviops99** [comment]
Hi rupini,
Can you please post what is teraaform version you are installed

**Comment by amaresh7** [comment]
its terraform current  version issue,
 try it =   aws_vpc.myvpc.id  instead of "${aws_vpc.myvpc.id}"
=>remove "${}" every where....

**Comment by MakrandakaMax** [comment]
[https://discuss.hashicorp.com/t/terraform-0-12-14-released/3898](url) this seems to me the possible solution. But it doesn't effect the creation. Everything will be created without any problems.

**Comment by srmanikanta** [comment]
In terraform version 0.11  interpolation is like this 
${var.foo}
but terraform version 0.12 interpolation is like this 
var.foo
Note: warning is not a problem it is executed 
please close the issue.
