### ISSUE TITLE
issue in terraform 

### ISSUE THREAD

**Issue by kslvvaraprasad** [QT-DevOps/DevOpsIssues#717]
hi there is an issue in terraform .version i am using Terraform v0.12.19.Error locking state: Error acquiring the state lock:
![terraform unable to read state file](https://user-images.githubusercontent.com/58965423/72622969-44189600-396a-11ea-9797-14ed50f84f87.png)

**Comment by ABBANAPURI0445** [comment]
terraform force-unlock LOCK_ID [DIR]

**Comment by srmanikanta** [comment]
please [Refer Here](https://www.terraform.io/docs/state/locking.html) 
If you got the answer for your error please close the issue.
