### ISSUE TITLE
Artifactory

### ISSUE THREAD

**Issue by amaresh7** [QT-DevOps/DevOpsIssues#719]
![artifactory](https://user-images.githubusercontent.com/58915129/72750036-bd6dee00-3be1-11ea-8084-1e978592122c.png)
integrate with jenkins pipeline, but it is not update automatically and showing this?

**Comment by raviops99** [comment]
Hi amaresh,
After installing artifactroy plugin
U will get artifactroy server's
After giving the artifactroy server details
Username and password click on test connect u should get test connection successful if you are already done this attachment screen shot click on refresh repo tab it fetaches few details from artifactroy

**Comment by amaresh7** [comment]
ya already done it...but still..

**Comment by raviops99** [comment]
Where u have installed artifactroy meaning whather physical server or AWS cloud 
If AWS cloud it should be publicised dress of AWS machine:8081 it should not 127.0.0.1
And artifactroy machine should java installed

**Comment by amaresh7** [comment]
t2.micro ram 1gb so its not work on it,then i install to my ubuntu (oracle vartual box) .
it install & work properly but to integrate the jenkins its not working.
and ya 127 is not a private ip port,i thing because of 127 port i am may be face issue...
