### ISSUE TITLE
getting error as "failed to read ssh private key" while doing terraform apply

### ISSUE THREAD

**Issue by Rupini93** [QT-DevOps/DevOpsIssues#721]
getting error as "failed to read ssh private key" while doing terraform apply
![Screenshot (69)](https://user-images.githubusercontent.com/57709400/72977900-6d6a7380-3dfb-11ea-95f6-6c5f24d5004a.png)

**Comment by ABBANAPURI0445** [comment]
share tf file

**Comment by Rupini93** [comment]
![Screenshot (70)](https://user-images.githubusercontent.com/57709400/72980101-d94edb00-3dff-11ea-93a8-974fc40e09bb.png)
tf file

**Comment by amaresh7** [comment]
complete path u put on this private_key.
eg.   private_key = file("/C:/<key name>")

**Comment by MakrandakaMax** [comment]
In connection you need to provide connection type which would be ssh, so type = "ssh". Specify which tomcat as well, I don't think just tomcat would work. 
If it still doesn't work try this, this is how I have done the layout which is inside the resource:
  provisioner "remote-exec" {
    connection {
      type = "ssh"
      user = "ubuntu"
      host = self.public_ip
      private_key = "${file("./<yourkeypairname>.pem")}"
    }
    inline = [
        "sudo apt-get update",
        "sudo apt-get install tomcat8 -y",
    ]  
  }

**Comment by srmanikanta** [comment]
plese check the below things:

Are you copy the linuxlearning1.pem key into your terraform files directory(path)
change the user name terrfrom to ubuntu(terraform user is not present by default in ubuntu machine)
connection {
        type        = "ssh"
        user        = "ubuntu"
        private_key = "${file(./linuxlearning1.pem)}"
        host        = "${aws_instance.tomcat.public_ip}"
}
if you already find the solution to this error please close the issue
