### ISSUE TITLE
getting error as ssh error

### ISSUE THREAD

**Issue by Rupini93** [QT-DevOps/DevOpsIssues#722]
![Screenshot (70)](https://user-images.githubusercontent.com/57709400/72980399-87f31b80-3e00-11ea-86ec-8418cd946556.png)

**Comment by amaresh7** [comment]
java is prerequisite , try it.
-----------------------------
provisioner "remote-exec" {
    inline = [
      "sudo apt-get update", "sudo apt-get install openjdk-8-jdk -y", "sudo apt-get install tomcat9 -y"
    ]
  }

**Comment by ABBANAPURI0445** [comment]
please logs

**Comment by ABBANAPURI0445** [comment]
please share logs

**Comment by MakrandakaMax** [comment]
What is the error that you are getting?

**Comment by srmanikanta** [comment]
please check the below things:
* Are you copy the  linuxlearning1.pem key into your terraform files directory(path) 
* change the user name terrfrom to ubuntu(terraform user is not present by default in ubuntu machine)
``` 
connection {
        type        = "ssh"
        user        = "ubuntu"
        private_key = "${file(./linuxlearning1.pem)}"
        host        = "${aws_instance.tomcat.public_ip}"
}
```
if you already find the solution to this error please close the issue.
