### ISSUE TITLE
GETTING CONNECTION ERROR WHILE USING GIT BASH

### ISSUE THREAD

**Issue by harikumars169** [QT-DevOps/DevOpsIssues#723]
while git bash is in idle state it giving a msg called connection lost plzz any one give the solution for this
![Capture](https://user-images.githubusercontent.com/57283736/73052284-cfce7d00-3eaa-11ea-8d8f-9eeb4fa1e172.PNG)

**Comment by amaresh7** [comment]
can you explain briefy out of this,bcz there is  lots of thing to be face this kind of situaction..

**Comment by dhana9000** [comment]
if it is idle use,
ping google.com

**Comment by harikumars169** [comment]
> if it is idle use,
> ping google.com

can u plz explain me what is ping google.com

**Comment by dhana9000** [comment]
ping is used to verify that a particular IP address exist and accepts request. Here google.com is IP address

**Comment by harikumars169** [comment]
Thnk u

**Comment by srmanikanta** [comment]
hello, harikumar if you solve the above error please close the issue.
