### ISSUE TITLE
Kubernetes: nodeNotReady issue

### ISSUE THREAD

**Issue by anwar095** [QT-DevOps/DevOpsIssues#725]
Hi,
Issue: worker node in the kubernetes cluster is in not ready state.

Checking kubelet logs, below error is displayed,
Error displayed: Failed to connect to api-server. the server has asked to provide the credentials.

Can anyone please help on this? Thank you

**Comment by ABBANAPURI0445** [comment]
apply pod network
flanel or weavenet

**Comment by ABBANAPURI0445** [comment]
if you have a solution please close issue with sol
