### ISSUE TITLE
Docker image bulid issue 

### ISSUE THREAD

**Issue by prasadsai528** [QT-DevOps/DevOpsIssues#726]
$ docker image build -t myapache .
Sending build context to Docker daemon  38.15MB
Step 1/3 : FROM ubuntu
 ---> ccc6e87d482b
Step 2/3 : RUN "apt-get update"
 ---> Running in 863a34bf7091
**/bin/sh: 1: apt-get update: not found
The command '/bin/sh -c "apt-get update"' returned a non-zero code: 127**

**Comment by dhana9000** [comment]
hi prasadsai,
In the Dockerfile remove double quotes for apt-get update, and build the image

**Comment by prasadsai528** [comment]
> hi prasadsai,
> In the Dockerfile remove double quotes for apt-get update, and build the image

Tn'Q' Bro, It's working.

**Comment by srmanikanta** [comment]
prasad sai please close the issue.
