### ISSUE TITLE
while i am building apache2 image on ubuntu vm , it shown a error as " /bin/sh: 1: apt-get update: not found The command '/bin/sh -c "apt-get update"' returned a non-zero code: 127" kindly go through provided snapshot and give resolution how to resolve it .

### ISSUE THREAD

**Issue by neelaraokala** [QT-DevOps/DevOpsIssues#727]

**Comment by neelaraokala** [comment]
![image](https://user-images.githubusercontent.com/60516092/73591687-cd59cc00-4517-11ea-9c9d-8915c5120f9b.png)

**Comment by ABBANAPURI0445** [comment]
share Dockerfile

**Comment by neelaraokala** [comment]
![image](https://user-images.githubusercontent.com/60516092/73596186-31938480-4546-11ea-8b88-ae1a4c50d1f6.png)

**Comment by neelaraokala** [comment]
thankyou@dhana9000. i just gone through ur suggestion is remove double quotes to apt-get update ,
its working now.
