### ISSUE TITLE
Ansible for LAMP not working properly

### ISSUE THREAD

**Issue by VenkateshYembuluru** [QT-DevOps/DevOpsIssues#728]
lampfactsandwhen.yml file

---
- hosts: webservers
  become: yes
  tasks:
    -  name:  install apache
       package:
         -  name:  "{{ pacakage_name }}"
            status: present
       notify:
         -  retstart and enable apache2
       when:  ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Debian"
  handlers:
    -  name:  retstart and enable apache2
       service:
         -  name: "{{ package_name}}"
            enabled: yes
            state: restart
       when:  ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Debian"

**************************************

ansible_playbook$ ansible-playbook -i hosts.yml -vv lampfactsandwhen.yml when you getting message as:

**ansible-playbook 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/devops/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
Using /etc/ansible/ansible.cfg as config file
ERROR! unexpected parameter type in action: <class 'ansible.parsing.yaml.objects.AnsibleSequence'>

The error appears to be in '/home/devops/ansible_playbook/lampfactsandwhen.yml': line 5, column 8, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    -  name:  install apache
       ^ here**

*****************************************************

**Comment by ABBANAPURI0445** [comment]
please send playbook and logs

**Comment by VenkateshYembuluru** [comment]
[error.docx](https://github.com/QT-DevOps/DevOpsIssues/files/4142851/error.docx)
kindly verify attached document contains ansible-play book and error screen shot
