### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by debasis-gif** [QT-DevOps/DevOpsIssues#729]
Hi,
I am getting the "Segmentation fault" error once I have logged with ubuntu user for an AWS EC2 instance connected through Putty. Any docker commands from the terminal would receive this error.
Please help to resolve...
![image](https://user-images.githubusercontent.com/60258623/73669621-c379c980-46cd-11ea-8b06-93002164da42.png)

Thanks 
Debasis

**Comment by raviops99** [comment]
Can you please post what is the docker version you are installed

**Comment by debasis-gif** [comment]
Hi, I am using the server Docker version 19.03.5 and other details which might help :
![image](https://user-images.githubusercontent.com/60258623/73745673-91be3c80-4779-11ea-93d7-4b659ef7c66a.png)

**Comment by shaikkhajaibrahim** [comment]
Can you help with the script you used to install docker

**Comment by debasis-gif** [comment]
It was through docker.sh script available in docker hub / git hub url, I do not exactly remember now but in an attempt to set up putty and Aws instance creation (instead of everytime going through docker playground ssh terminal)
Please suggest if I need to uninstall docker and re-install with a proper and latest script for the correct version of docker

**Comment by debasis-gif** [comment]
Hello, any resolution to this? 
Anyway for last few days I did not encounter similar issues. I am able to work on the Putty sessions with the AWS EC2 instances for long time, without the segmentation fault. It could be on the particular day when I could not proceed further with the issue, I had some network issues, I am not sure if that had to do something with the docker segmentation fault.
