### ISSUE TITLE
Command needed to run ansible playbook with 4 vars files

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#73]
Hi,

I created the betterlamp.yml file as instructed. In place of the earlier single myinventory file, it now has 4 files containing its variables - redhat.yml, ubuntu.yml, webserver.yml, and localhost.yml.

Earlier the command was simple:
 $ ansible-playbook -i myinventory betterlamp.yml

Now what is the command to run the main ansible playbook with the additional 4 yml files?

**Comment by shaikkhajaibrahim** [comment]
Ansible-Playbook is used to run only one playbook (yml) file at a time.

If you want to run multiple wait for roles to be finished.
________________________________

**Comment by rameshm78** [comment]
So the exercise you asked us to do on Saturday, cannot be done now?

**Comment by sanjaysureshmv** [comment]
Assuming you have placed the 4 additional files under group_vars, you can directly run the command,
 ansible-playbook -i myinventory betterlamp.yml. The variables inside the betterlamp.yml will get values from the 4 additional files. Ansible does this automatically.

**Comment by shaikkhajaibrahim** [comment]
Hi Sanjay,

Variable files & Playbook files please refer them separetly.

If you ask about yml files in ansible general understanding is that you are speaking about playbooks.


You can multiple var files but only one playbook file.
So my exercise is still valid

You can have
________________________________

**Comment by shaikkhajaibrahim** [comment]
There is no specific command for variables, only convention based folders
![image](https://user-images.githubusercontent.com/2438317/43450074-8c988df4-94cf-11e8-8b20-548bb4af0c3e.png)

The above example is ran with 

ansible-playbook -i hosts betterlamp.yaml

php_packages variable value is loaded from group vars

there is no need to change any command. Things are loaded dynamically
