### ISSUE TITLE
appliance configuration is showing error i.e network connectivity error 

### ISSUE THREAD

**Issue by git-pavanireddy** [QT-DevOps/DevOpsIssues#730]
![migration issue](https://user-images.githubusercontent.com/60656237/73749129-c1247780-4780-11ea-9f20-1e909ecdb1cf.PNG)

**Comment by shaikkhajaibrahim** [comment]
You have not configured the ip correctly, please raise this on Azure Issues https://github.com/QT-DevOps/AzureIssues
