### ISSUE TITLE
unable to download zip file from artifactory

### ISSUE THREAD

**Issue by praveen1461996** [QT-DevOps/DevOpsIssues#732]
getting below error while downloading in SOME INSTANCES 
[devops@ebs1227 ~]$ curl -u user:password "http://192.168.4.252:8081/artifactory/Internal/Release/4.3/Build8/spring.zip"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1  887M    1 15.5M    0     0   928k      0  0:16:19  0:00:17  0:16:02  587k
curl: (56) Failure when receiving data from the peer

**Comment by raviops99** [comment]
Sometimes proxy blocking the request to the server
If possible instead of curl use wget and url
And try i am not sure please try it once

**Comment by srmanikanta** [comment]
In some cases, server do not support particular request, like some servers support PUT/POST any one of them.
it was proxy blocking the request to the server.

But in your case
```
curl -X POST -u username:password "http://192.168.4.252:8081/artifactory/Internal/Release/4.3/Build8/spring.zip"
```
if you already find the solution to this please close the issue.
