### ISSUE TITLE
Extracting the file in proper location using remote ssh is not working 

### ISSUE THREAD

**Issue by NaveenALO** [QT-DevOps/DevOpsIssues#734]
sudo cd /home/qa-user/Newfolder
sudo chmod -R 777 /home/qa-user/Newfolder
sudo tar -xvf /home/qa-user/Newfolder/ai-app-docker-20.0.0.443.tar.gz 

Job getting success but iam unable to see the extracted file in the location 

![image](https://user-images.githubusercontent.com/59245093/73921962-52652c80-48ee-11ea-8691-e64063a47275.png)

**Comment by srmanikanta** [comment]
Hi, Naveen 
To extract tar files to a particular location first you should check the target directory is present or not  then target directory is not present create your target directory 
for example you are trying to extract tar file into some /tmp/target
1. create target directory in /tmp
```
mkdir -p /tmp/target
```
2. To extract a tar file into different or a particular directory  
```
sudo tar -xvf <yourtar file> -C /tmp/target
or 
sudo tar -xvf <yourtar file> --directory  /tmp/target
```

In your script no need to change the target directory, directly you can mention on tar command

you already find the solution to this please close the issue.

**Comment by NaveenALO** [comment]
Thanks srmanikanta. it is working fine.
