### ISSUE TITLE
Wordpress Pod CrashLoopBackoff

### ISSUE THREAD

**Issue by Nara-Sagar7** [QT-DevOps/DevOpsIssues#735]
Hello I am Trying to Deploy a Wordpress Application With MySql and when i deploying the WordPress Deployment the wordpress pod  is getting crashLoopBackoff i am trying to fix it using logs but i am not getting whats wrong with this stack, Mysql working file but getting error in wordpress.

below are the Yaml Files.
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: DB_HOST
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: DB_PASSWORD
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
data:
  DB_PASSWORD: bXlzcWxwYXNzd29yZA==
  DB_HOST: bXlzcWw=

And also attaching the logs screen shot.
![image](https://user-images.githubusercontent.com/54387478/73932313-120eaa00-4900-11ea-9c59-460aa89d76c4.png)

**Comment by ABBANAPURI0445** [comment]
crashLoopBackoff:  this means starting pod and crashes repeatedly 
https://sysdig.com/blog/debug-kubernetes-crashloopbackoff/

**Comment by shaikkhajaibrahim** [comment]
for wordpress to work you need to mysql svc to be up first
