### ISSUE TITLE
docker installation is failed in windows could anyone help me please 

### ISSUE THREAD

**Issue by singaravelugit** [QT-DevOps/DevOpsIssues#736]
I have installed docker in my office machine getting below could anyone help in this.. 
C:\Users\singvenk>docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:17:08 2019
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by raviops99** [comment]
Hi can you please follow below link
https://stackoverflow.com/questions/40459280/docker-cannot-start-on-windows

**Comment by srmanikanta** [comment]
To install docker in windows please follow the official documentaion [click here](https://docs.docker.com/docker-for-windows/install/) and read pre-requisites for this installation and follow the steps.
