### ISSUE TITLE
while creating ec2 in terraform Vm is created but the provisioning is not done it is showing a error line SSH connection is failed

### ISSUE THREAD

**Issue by gopichandu98** [QT-DevOps/DevOpsIssues#737]
![terraform fail](https://user-images.githubusercontent.com/55825566/74129523-c9a80280-4c05-11ea-96ba-d00f6f39c7e5.PNG)
Error: timeout - last error: SSH authentication failed (ec2-user@3.134.101.236:22): ssh: handshake failed: ssh: unable to  authenticate, attempted methods [none publickey], no supported methods remain.
![terraform fail](https://user-images.githubusercontent.com/55825566/74129539-d9bfe200-4c05-11ea-8dda-bac6df4b058a.PNG)

**Comment by gopichandu98** [comment]
provider "aws" {
    region = "us-east-2"
    access_key = "accesskey"
    secret_key = "secret key"
  
}

resource "aws_instance" "ec2" {
  ami = "ami-0fc20dd1da406780b"
  instance_type = "t2.micro"
  key_name = "ubuntu"
  security_groups = ["OpenAll"]

  connection {
      type = "ssh"
      user = "ec2-user"
      host =  "${aws_instance.ec2.public_ip}"
      private_key = "${file("./ubuntu.pem")}"
  }
  provisioner "remote-exec" {
      inline = ["sudo apt-get install tomcat -y"]

  }
}

**Comment by dhana9000** [comment]
If you are creating a ubuntu machine your user should be  "ubuntu". Maybe this will help you, Try this
connection {
type = "ssh"
user = "ubuntu"
host = "${aws_instance.ec2.public_ip}"
private_key = "${file("./ubuntu.pem")}"
}

**Comment by dhana9000** [comment]
provisioner "remote-exec" {
inline = ["sudo apt-get update",
              "sudo apt-get install openjdk-8-jdk -y",
              "sudo apt-get install tomcat8 -y"]

}

**Comment by gopichandu98** [comment]
hii dhana ,

Now its working and if we are using a connection type is SSH default user is root but that is also not working.

**Comment by gopichandu98** [comment]
iam facing a connection isuue while iam using the data source for security group 
![Capture](https://user-images.githubusercontent.com/55825566/74216957-ffafba00-4ccb-11ea-88ac-dba796f4826c.JPG)

**Comment by gopichandu98** [comment]
provider "aws" {
    region     = "us-east-2"
    access_key = "accesskey"
    secret_key = "secretkey"
  
}


data "aws_security_group" "mygroup" {
    name = "default"


}

resource "aws_instance" "ec2" {
  ami = "ami-0fc20dd1da406780b"
  instance_type = "t2.micro"
  key_name = "ubuntu"
  security_groups = ["${data.aws_security_group.mygroup.name}"]

  connection {
      type = "ssh"
      user = "ubuntu"
      host =  "${aws_instance.ec2.public_ip}"
      private_key = "${file("./ubuntu.pem")}"
  }
  provisioner "remote-exec" {
        inline = ["sudo apt-get update", "sudo apt-get install mongodb -y"]
    }

  
}

**Comment by dhana9000** [comment]
hi gopichandu, If you use default security group we cannot connect to instance and we will get connection timed out error as the AMI requires port(s) 22 to be open in order to have access.
default security group doesn't have port(s) 22 open.
![sg](https://user-images.githubusercontent.com/58977739/74230635-d05c7580-4cea-11ea-8efd-bb3165f33dd8.PNG)

![image](https://user-images.githubusercontent.com/58977739/74230953-6f816d00-4ceb-11ea-9a0a-19dbac1fa478.png)

**Comment by dhana9000** [comment]
This link may help you in writing data source for security group:
https://stackoverflow.com/questions/57467251/map-all-existing-aws-security-groups-in-terraform
