### ISSUE TITLE
Terraform UI 

### ISSUE THREAD

**Issue by srinivle** [QT-DevOps/DevOpsIssues#738]
Hi Team, could anyone please tell me if there is any way we can download the .tf terraform scripts from the Terraform UI??? is there any such Terraform UI site??? Any suggestions please???

**Comment by dhana9000** [comment]
I don't known exactly, but this link may help you. once refer this 
https://registry.terraform.io/

**Comment by srinivle** [comment]
sure sure..I will give it a try.... thank you very much .... Thanks a lot again.

**Comment by dhana9000** [comment]
http://www.glitterlabs.com/terraform_ui/index.html

**Comment by srinivle** [comment]
cool stuff sir

**Comment by ABBANAPURI0445** [comment]
please close the issue if resolved
