### ISSUE TITLE
Ansible not able to deploy asking sudo password 

### ISSUE THREAD

**Issue by saikiran243** [QT-DevOps/DevOpsIssues#74]
1)I have installed ansible (ubuntu) a node as (ubuntu)
2)copied ansible user id_rsa.pub to node ansible user authorisation keys
3) allowed password authentication in both machines and added ansible user to sudo group
4) done with ssh user@ip no password is asking
5) able to apply adhoc commands
![a3](https://user-images.githubusercontent.com/26058420/43396848-8fdd062a-9420-11e8-8f4b-028b31568fc9.PNG)
6) not able to apply playbooks
![a1](https://user-images.githubusercontent.com/26058420/43396869-a4fedf06-9420-11e8-88c0-650bb5009ff2.PNG)
7) -vvv resoponse is 
![a2](https://user-images.githubusercontent.com/26058420/43396884-b75dbb0e-9420-11e8-8a89-3775eed3818c.PNG)
here is the sample playbook iam executing 

---
- hosts: all
  become: yes
  tasks:
  - name: Execute ansible ping on hosts
    ping:
  - name: Update packages on ubuntu
    apt:
      name: git
      update_cache: yes
      state: present
  - name: install tree
    apt:
      name: tree
      state: present

**Comment by siva0139** [comment]
ansible-playbook hello.yml -K

**Comment by saikiran243** [comment]
thanks, it solved. but how can i overcome this as I mentioned in the yaml file as 
become: yes 
and added keys to authenticate .. even i can ssh to node_ansibleuser@ip without a password.

**Comment by siva0139** [comment]
%admin ALL=(ALL) ALL
ansible ALL=(ALL) NOPASSWD: ALL     --- make nopasswd : all in visudo in  all machines
