### ISSUE TITLE
while build a ami image in aws using packer i got a error like (failed to parse the template:invalid character):error parsing json 

### ISSUE THREAD

**Issue by gopichandu98** [QT-DevOps/DevOpsIssues#740]
can u look into once .find the below json
{
    "builders" : [{
        
        "type": "amazon-ebs",
        "access_key": "accesskey",
        "secret_key": "secretkey",
        "region": "us-east-2",
        "owners": "amazon",
        "instance_type": "t2.micro",
        "source_ami": "ami-0fc20dd1da406780b",
        "ami_name": "myimage",
         "ssh_username" : "ubuntu"

     }]

}

![packer error](https://user-images.githubusercontent.com/55825566/74407526-30245f00-4e58-11ea-89b1-ccc50a9a2f01.JPG)

**Comment by dhana9000** [comment]
hi gopichandu,
Remove owners from builders section. 
owners is used in source_ami_filter.
![image](https://user-images.githubusercontent.com/58977739/74414093-b9db2900-4e66-11ea-9f00-19f3b1358751.png)

Error (Error parsing json: invalid character) occurs, when we miss comma after key=value pair.
you missed comma after "type": "amazon-ebs".
After removing owners key=value pair, code which you have provided is working fine.
Check weather you have saved changes in  your file or not and validate  the file.

**Comment by gopichandu98** [comment]
Hii dhana,
Please check already I kept a cama at type: amazon-ebs.please once check
above  my packer template.iam facing same issue.

Regards,
Gopi.t

**Comment by dhana9000** [comment]
plz share the latest file.

**Comment by gopichandu98** [comment]
now its working fine thanks for quick responce

**Comment by dhana9000** [comment]
You are welcome, pls close this issue.
