### ISSUE TITLE
Terraform remote-exec fail

### ISSUE THREAD

**Issue by Ramparitala** [QT-DevOps/DevOpsIssues#741]
Hello Everybody, 

I am getting timeout error on remote-exec. Can someone please help me to get this resolve. 
==========Here is my code===========
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "private_key_path" {
    default = "Terraform.pem"
}
variable "key_name" {
  default = "Terraform"
}

provider "aws" {
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
  region     = "us-east-1"
}

resource "aws_security_group" "nginx_sg" {
  name          = "nginx_sg"
  description   = "security group for nginx from terraform"

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }
  ingress {
    from_port   = 8080
    to_port     = 8080
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port       = 0
    to_port         = 0
    protocol        = "-1"
    cidr_blocks     = ["0.0.0.0/0"]
  }
}

resource "aws_instance" "nginx" {
  ami           = "ami-07ebfd5b3428b6f4d"
  instance_type = "t2.micro"
  key_name        = "${var.key_name}"
  vpc_security_group_ids = ["${aws_security_group.nginx_sg.id}"]
  associate_public_ip_address = "true"

  connection {
    user        = "ubuntu"
    private_key = "${file(var.private_key_path)}"
    host = "${aws_instance.nginx.id}"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo apt-get update",
      "sudo apt-get install nginx -y",
      "sudo service nginx start"
     ]
  }
}

output "aws_instance_public_dns" {
    value = "http://${aws_instance.nginx.public_dns}:80"
}

===========Error============

aws_instance.nginx (remote-exec): Connecting to remote host via SSH...
aws_instance.nginx (remote-exec):   Host: i-0ad0667xxxxxxx
aws_instance.nginx (remote-exec):   User: ubuntu
aws_instance.nginx (remote-exec):   Password: false
aws_instance.nginx (remote-exec):   Private key: true
aws_instance.nginx (remote-exec):   Certificate: false
aws_instance.nginx (remote-exec):   SSH Agent: true
aws_instance.nginx (remote-exec):   Checking Host Key: false
aws_instance.nginx: Still creating... [5m50s elapsed]
aws_instance.nginx: Still creating... [6m0s elapsed]

Error: timeout - last error: dial tcp 92.242.132.24:22: i/o timeout

Thank you in advance !

**Comment by dhana9000** [comment]
Hi Ramparitala,
In connection section the value of host should be public_ip.
host = "${aws_instance.nginx.public_ip}"

**Comment by Ramparitala** [comment]
Thank you for your prompt response @dhana9000 . Issue resolved by changing host to
 host = "${aws_instance.nginx.public_ip}"
