### ISSUE TITLE
Docker image creation

### ISSUE THREAD

**Issue by pavankumarr3ddy** [QT-DevOps/DevOpsIssues#742]
hi, 
i'm trying to build an image. 

evrything is going fine but me and my friend also facing the same issue that in vi dockerfile i'm unable to run the command apt -get or sudo apt-get. 
/ 
could u please check where i have gone wrong.
![image](https://user-images.githubusercontent.com/58127643/74588278-108c6280-5021-11ea-9e7d-80f5157ba034.png)

**Comment by dhana9000** [comment]
hi pavankumar,
please remove double quotes for apt-get update in Dockerfile and in dockerfile sudo command does not work.

**Comment by ABBANAPURI0445** [comment]
remove sudo
