### ISSUE TITLE
kubernetes

### ISSUE THREAD

**Issue by pradeeprepati** [QT-DevOps/DevOpsIssues#743]
while joining worker into master iam getting error message like this
![Capture](https://user-images.githubusercontent.com/58842251/74600428-9ce96480-50b7-11ea-824c-cd262bd0b995.PNG)
how to solve this error

**Comment by dhana9000** [comment]
Hi pradeep,
Once try this, run "kubeadm​ reset" command on you worker node and then use join command.

**Comment by ABBANAPURI0445** [comment]
please follow this link
https://github.com/kubernetes/kubeadm/issues/974

**Comment by ABBANAPURI0445** [comment]
if the issue is solved, please close
