### ISSUE TITLE
GIT-Not able to view .git folder

### ISSUE THREAD

**Issue by thisiskrish1984** [QT-DevOps/DevOpsIssues#744]
HI
Installed Git on local machine and after executuing git init to start working.I dont find .git folder normally but could able to view from hidden folders with the command ls -laf.
What changes should i do to view .git folder normally?
Thanks.

**Comment by dhana9000** [comment]
Hi krish,
By default .git folder is hidden in windows, the only reason to hide the .git folder is  to keep a person  from accidentally deleting it or changing it's contents.
To configure dot files we have core.hideDotFiles setting.

![image](https://user-images.githubusercontent.com/58977739/74743014-aaece000-5285-11ea-81e6-e2b15430910e.png)

i hope this will help you.

**Comment by thisiskrish1984** [comment]
Thanks for ur kind reply.
