### ISSUE TITLE
kubernetes 

### ISSUE THREAD

**Issue by 105636046** [QT-DevOps/DevOpsIssues#745]
![Screenshot (1)](https://user-images.githubusercontent.com/60434784/74757168-a6cbbd00-529b-11ea-8d0c-1b6690b4d336.png)
 While configuring kubectl  it is showing following error 
please do the needful help

**Comment by dhana9000** [comment]
once run these commands as a normal user.
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
