### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by Neelimapayasamgit** [QT-DevOps/DevOpsIssues#746]
Hi Team

I tried kubeadm setup on azure cluster yesterday , it worked well got output of kubectl get pods and all.
After restarting the master and node , I am unable to execute commands

Error:

root@kubemaster:~#  kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?
root@kubemaster:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

kindly help.

Note: I added 8080 port to inbound rule in azure and tried but no luck.

Thanks
Neelima

**Comment by dhana9000** [comment]
Hey neelima 
Try this out "systemctl start kubelet "
Let me know the output

**Comment by Neelimapayasamgit** [comment]
Hi Dhana
Thanks for addressing this issue . 

Here is the output

root@kubemaster:~# systemctl start kubelet
root@kubemaster:~# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Fri 2020-02-21 02:11:39 UTC; 1min 48s ago
     Docs: https://kubernetes.io/docs/home/
 Main PID: 1201 (kubelet)
    Tasks: 19 (limit: 4675)
   CGroup: /system.slice/kubelet.service
           └─1201 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-dri

Feb 21 02:13:16 kubemaster kubelet[1201]: E0221 02:13:16.859688    1201 cni.go:385] Error deleting kube-system_coredns-6955765f44-h5b49/d0bc6b10cea8aab4d0ede4194e569355d11b550118c79da28efac
Feb 21 02:13:16 kubemaster kubelet[1201]: E0221 02:13:16.860591    1201 remote_runtime.go:128] StopPodSandbox "d0bc6b10cea8aab4d0ede4194e569355d11b550118c79da28efac8982c42fc98" from runtime
Feb 21 02:13:16 kubemaster kubelet[1201]: E0221 02:13:16.860665    1201 kuberuntime_manager.go:898] Failed to stop sandbox {"docker" "d0bc6b10cea8aab4d0ede4194e569355d11b550118c79da28efac89
Feb 21 02:13:16 kubemaster kubelet[1201]: W0221 02:13:16.862515    1201 cni.go:331] CNI failed to retrieve network namespace path: cannot find network namespace for the terminated container
Feb 21 02:13:16 kubemaster kubelet[1201]: weave-cni: unable to release IP address: Delete http://127.0.0.1:6784/ip/78902acf293bcb50d949be6a5126b52c6cd14d10263768c27f29b3793ef61794: dial tcp
Feb 21 02:13:16 kubemaster kubelet[1201]: E0221 02:13:16.908094    1201 cni.go:385] Error deleting kube-system_coredns-6955765f44-h5b49/78902acf293bcb50d949be6a5126b52c6cd14d10263768c27f29b
Feb 21 02:13:16 kubemaster kubelet[1201]: E0221 02:13:16.908621    1201 remote_runtime.go:128] StopPodSandbox "78902acf293bcb50d949be6a5126b52c6cd14d10263768c27f29b3793ef61794" from runtime
Feb 21 02:13:16 kubemaster kubelet[1201]: E0221 02:13:16.908658    1201 kuberuntime_manager.go:898] Failed to stop sandbox {"docker" "78902acf293bcb50d949be6a5126b52c6cd14d10263768c27f29b37
Feb 21 02:13:16 kubemaster kubelet[1201]: E0221 02:13:16.908726    1201 kuberuntime_manager.go:676] killPodWithSyncResult failed: failed to "KillPodSandbox" for "7f2e5d0a-39e2-4aa2-bd95-8c2
Feb 21 02:13:16 kubemaster kubelet[1201]: E0221 02:13:16.908755    1201 pod_workers.go:191] Error syncing pod 7f2e5d0a-39e2-4aa2-bd95-8c224fa52dae ("coredns-6955765f44-h5b49_kube-system(7f2

root@kubemaster:~# kubectl get nodes
The connection to the server localhost:8080 was refused - did you specify the right host or port?
root@kubemaster:~# kubectl get pods
The connection to the server localhost:8080 was refused - did you specify the right host or port?
root@kubemaster:~#

**Comment by ABBANAPURI0445** [comment]
configure kubectl as normal user
run as a normal user

**Comment by Neelimapayasamgit** [comment]
@ABBANAPURI0445  I have done it already and worked on it , after restarting servers got this issue

**Comment by ABBANAPURI0445** [comment]
run this commands  as regular user
----------------------
sudo cp /etc/kubernetes/admin.conf $HOME/
sudo chown $(id -u):$(id -g) $HOME/admin.conf
export KUBECONFIG=$HOME/admin.conf

**Comment by kslvvaraprasad** [comment]
hi
go to normal user and then try ..me too got same problem then exited from root user and tried ..

**Comment by Neelimapayasamgit** [comment]
thanks everyone
