### ISSUE TITLE
Jenkins Email sending error

### ISSUE THREAD

**Issue by vaddeadiseshu** [QT-DevOps/DevOpsIssues#747]
while configuring and checking a  email notification i am getting the following error.the username and password i given was correct.
![jenkins email error](https://user-images.githubusercontent.com/53860731/75138814-2977d080-5711-11ea-98d5-3282e83fb895.jpg)

javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials u76sm5573354qka.21 - gsmtp

	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:809)
	at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:752)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:669)
	at javax.mail.Service.connect(Service.java:317)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)

**Comment by dhana9000** [comment]
Hi vaddeadiseshu,
your username should be in the format of "user_email_id@gmail.com"  
once follow this document 
https://www.360logica.com/blog/email-notification-in-jenkins/

**Comment by srmanikanta** [comment]
If you configure jenkins e-mail please you should follow the below steps:
* first enable two step verification for reference [click here](https://support.google.com/accounts/answer/185833?hl=en) 
* generate an app password
* add the app password instead of your password
Above process working fine.
If this is useful to you please close the issue.

**Comment by mostatechnologies** [comment]
enable "Less secure app access" from Gmail settings.

**Comment by qpostest99** [comment]
"Less secure app access" this feature is no longer available. Any idea how to resolve the issue without this gmail setting

**Comment by samirvarude** [comment]
Gmail Account -> Security - > 2 - Step Verification - > App passwords (Bottom of Page) - Create App Password account (Provide any name) - Save - Password will generated.

Take password and save it on Password field under "Use SMTP Authentication" section.

This is latest one and worked for me.

**Comment by namdev-rathod** [comment]
If you are not able to find App Password..

First turn on two step authentication.
Go to Link https://myaccount.google.com/apppasswords and set up the app password.
