### ISSUE TITLE
Legacy application containerization 

### ISSUE THREAD

**Issue by sunnydevops** [QT-DevOps/DevOpsIssues#748]
Hello Team,

I have already containerized java microservices application for my practice purpose.   But now I am thinking to containerize legacy applications like (.net framework).  

Please help me with this.

**Comment by srmanikanta** [comment]
please follw this link [click here](https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-create-console-app) for simple .net application.
* first do it manually 
* then write a docker file for whatever you did manually 
* finally build the image and then run as a container.
