### ISSUE TITLE
Create docker container with python virtual environment as 3.6 and that virtual environment should be for only user Add one user if needed

### ISSUE THREAD

**Issue by raghuvadde251** [QT-DevOps/DevOpsIssues#749]
Create docker container with python virtual environment as 3.6 and that virtual environment should be for only user Add one user if needed

**Comment by srmanikanta** [comment]
you can add the user if you want by using interactive terminal. 
please close the issue.

**Comment by shaikkhajaibrahim** [comment]
Why dont you try and send the error you got
