### ISSUE TITLE
Failed to download module-Cloudwatch module in Terraform

### ISSUE THREAD

**Issue by adamalli01** [QT-DevOps/DevOpsIssues#750]
[cloudwatch.txt](https://github.com/QT-DevOps/DevOpsIssues/files/4271427/cloudwatch.txt)
![error](https://user-images.githubusercontent.com/43026073/75620759-ca073e00-5bb2-11ea-9ead-dfd5bc3c117c.JPG)

**Comment by srmanikanta** [comment]
please post your terraform script here.
