### ISSUE TITLE
Error occuring while Log files sending to elastic search

### ISSUE THREAD

**Issue by hareesh309** [QT-DevOps/DevOpsIssues#751]
![Capture](https://user-images.githubusercontent.com/61037317/75854427-2ddd7100-5e16-11ea-916e-331342b3fcca.JPG)

**Comment by srmanikanta** [comment]
please check logstash configuration once and check the installed java version.It shouldbe  8 or 11.
[refer here](https://www.elastic.co/guide/en/logstash/current/config-examples.html) for reference
