### ISSUE TITLE
Alert configuration on kibana.

### ISSUE THREAD

**Issue by surendramannem** [QT-DevOps/DevOpsIssues#753]
Hello Sir, 
This is Surendra Mannem. 

Your Devops class student. 
Working as a "cloud operation engineer" on Azure platform . 

I 've done my lab in the below way. 

Step 1: Installed Elastic search on Centos
Step 2: Installed logstash on centos
step 3: Create connetions by creating the .conf files.
Step 4: Installed Kibana in Elastic Search.
Step 5: Installed "Metric beats" on centos machine, Installed winlog on my local laptop. 
Step 6: Made changes in .Yml fine to establish communication. 

Issues i faced. I deployed machines in "Azure enviroment". 

For got the open the ports like 80, 445,5601,9200 & 5044 on the machines. 

Kibana access link: http://52.167.170.171:5601/

Can you please help me with the, alert confinguration on kibana..

**Comment by ramjagadeeshkumar6666** [comment]
![aaa](https://user-images.githubusercontent.com/60171094/76178738-68605880-61de-11ea-9ce2-2145eaa9097b.jpg)

**Comment by surendramannem** [comment]
Hello Ram,

I've already open the ports, i just mentioned the issue i faced.  

Thank you for the reply.

**Comment by ramjagadeeshkumar6666** [comment]
https://www.elastic.co/guide/en/kibana/current/settings.html

**Comment by surendramannem** [comment]
thank you, will go through the link
