### ISSUE TITLE
How can i fix the issue in Jenkins server while  add a jenkins user and its priviliges in visudo file?

### ISSUE THREAD

**Issue by prasadsai528** [QT-DevOps/DevOpsIssues#754]
![jenkins Issue](https://user-images.githubusercontent.com/55782151/75964604-83d11800-5eed-11ea-8131-cf0217fec5b5.PNG)

**Comment by dhana9000** [comment]
hi prasadsai,
first type "fg" and then run visudo
otherwise to add jenkins user to the sudo group run this command
usermod -aG sudo jenkins

**Comment by prasadsai528** [comment]
> hi prasadsai,
> first type "fg" and then run visudo
> otherwise to add jenkins user to the sudo group run this command
> usermod -aG sudo jenkins

Tnk you
