### ISSUE TITLE
While node is adding to Jenkins master , Its not adding to master error coming how can i fix it ?

### ISSUE THREAD

**Issue by prasadsai528** [QT-DevOps/DevOpsIssues#756]
![Jenkins node Fails](https://user-images.githubusercontent.com/55782151/76065543-e1c73380-5fb1-11ea-8408-5b7016725877.PNG)

**Comment by RahulAnita** [comment]
SO, the solution is to set this option to "Manually trusted key verification strategy". It's an option under "Launch Method" in the node configuration:

Dashboard -> Manage Jenkins -> Manage Nodes -> Gear Symbol in the row of your Slave node

**Comment by srmanikanta** [comment]
prasad sai follow the instructions:
* first login into jenkins master as jenkins user.
```
sudo -i
su  jenkins
cd ~
```
* once the switched to jenkins user please try to login with node credentainls
```
ssh <nodeusername>@<nodeuserprivateip>
```
* goto manage jenkins-> manage node-> configure the node 
* once the node configuration is done launch the agent.
Note: Before doing the above configuration

* check the user is add in visudo and enable password authentication is yes for both jenkins master and jenkins node
* restart the sshd service

please close the issue.

**Comment by prasadsai528** [comment]
Tnk u
