### ISSUE TITLE
Spring Petclinic application do not run....

### ISSUE THREAD

**Issue by debasis-gif** [QT-DevOps/DevOpsIssues#758]
Hi,
In an attempt to run the "Spring Petclinic" application on Web, the url simply does not work. I have tried all the options - here is the gist :

1. Have build the image and container for Spring Petclinic application build through a Dockerfile using Maven installed in the VM 
2. Have pushed the image onto Docker Hub for public accessibility in my Dockerhub account
3. Apache2 and Tomcat 8.5.x is up and running with firewall allowed for Apache Full (80) and Tomcat (8080)
4. to run on browser -> http://<public-ip>/spring-petclinic 
5. **Above url does not work.**
6. Please find the attached snapshots - if you can find where I am going wrong.. 

**_Here are the snapshots for ease of reference :_**
**Dockerfile-Spring-Petclinic**
![**Dockerfile-Spring-Petclinic**](https://user-images.githubusercontent.com/60258623/76156386-c8dc9080-611f-11ea-8d2c-af9072c5d755.png)
**apache-tomcat running**
![**apache-tomcat running**](https://user-images.githubusercontent.com/60258623/76156398-fa555c00-611f-11ea-8d4f-5594a572b05f.png)
**spring-petclinic container running**
![**spring-petclinic container running**](https://user-images.githubusercontent.com/60258623/76156411-2670dd00-6120-11ea-9369-08b6dcf2f2b2.png)
**spring-petclinic image pushed to Dockerhub**
![**spring-petclinic image pushed to Dockerhub**](https://user-images.githubusercontent.com/60258623/76156427-6c2da580-6120-11ea-9394-36ce4d7dc3b8.png)
**apache tomcat url running**
![**apache tomcat url running**](https://user-images.githubusercontent.com/60258623/76156433-794a9480-6120-11ea-8e58-9c8447daa5de.png)
**Network Security group config in Azure for VM**
![**Network Security group config in Azure for VM**](https://user-images.githubusercontent.com/60258623/76156440-85ceed00-6120-11ea-99ed-9ffefba9a30b.png)
**spring-petclinic url not working**
![**spring-petclinic url not working**](https://user-images.githubusercontent.com/60258623/76156446-97b09000-6120-11ea-810d-a861b38b3d79.png)

**Comment by srmanikanta** [comment]
In tomcat webapp folder we can deploy only .war files but right now you are deploying a jar this is not work for spring-petclinic take game-of-life it built the war file.

.jar files are run like this 
`java -jar <pathofyourjarfile /spring-petclinic.jar>`
or else
write a linux service for jar file.

**Comment by debasis-gif** [comment]
I have taken your hint and deployed the .jar file in the correct Docker layer (this was the point of confusion, but now understand the layer structure) 
and post that have used ENTRYPOINT to execute the .jar file

Here's the modified **Dockerfile:**
FROM maven:3-jdk-8 as mvn
LABEL author='Debasis'
RUN git clone https://github.com/spring-projects/spring-petclinic.git 
RUN cd spring-petclinic  &&  mvn install -DskipTests

FROM tomcat:8
LABEL author='Debasis'
COPY --from=mvn  /spring-petclinic/target/spring-petclinic*.jar /usr/local/tomcat/webapps/spring-petclinic.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/usr/local/tomcat/webapps/spring-petclinic.jar"]

**Comment by debasis-gif** [comment]
The above build is working **fine** now - have checked the image and the container with docker inspect.
I could get to invoke the petclinic application by 
**http://public ip-addr:8080/**

Thanks for your response

Debasis

**Comment by debasis-gif** [comment]
Hi,
I have commented in the GitHub.
The problem is resolved 
Thanks & Regards,
Debasis Pal7972930164 / 9836965177 

    On Sunday, 8 March 2020, 12:23:36 GMT+5:30, srmanikanta <notifications@github.com> wrote:  
 
 
run like this
http://<ip:8080>
ensure your 8080 port is open or not.
