### ISSUE TITLE
sudo apt-get udpate commnad error with respect of ansible

### ISSUE THREAD

**Issue by pravin-07** [QT-DevOps/DevOpsIssues#76]
root@ip-172-31-43-138:~# apt-get update
Err:1 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease
  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
0% [Connecting to us-east-1.ec2.archive.ubuntu.com (54.152.129.43)] [Connecting^                                          C

**Comment by shaikkhajaibrahim** [comment]
seems to be packet failed . 

Did you followed https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#latest-releases-via-apt-ubuntu ?

**Comment by pravin-07** [comment]
yes .problem solved their is some problem firewall issues in aws (inbound/outbound ICMP/TCP rule.)
thanks these document is also helpful for further installation.
