### ISSUE TITLE
In Jenkins on build error

### ISSUE THREAD

**Issue by karthik2111** [QT-DevOps/DevOpsIssues#760]
Hi All,

I have encountered the error while compiling the build step in jenkins. Could you please help on this.

Please find the attachment of details.

![1](https://user-images.githubusercontent.com/54673408/76325649-91cbd200-630d-11ea-8779-51625125a762.PNG)
![2](https://user-images.githubusercontent.com/54673408/76325656-92fcff00-630d-11ea-96bd-2ea0239ec382.PNG)

**Comment by dhana9000** [comment]
Hi karthik,
There is Insufficient memory issue, this might be issue with the size of instance you have selected.
once build the project with  t2.medium instance.

**Comment by karthik2111** [comment]
Hi Dhana,

Thanks for the help. Now the issue got resolved.

Thanks,
karthik J

**Comment by raviops99** [comment]
Please close the issue
