### ISSUE TITLE
Kubernetes - not being able to run 2 pods in the same node

### ISSUE THREAD

**Issue by debasis-gif** [QT-DevOps/DevOpsIssues#761]
Hi,
I have been trying to do Kubernetes deployment of 2 application images in the same node over two loadbalancer services.
I could invoke one application (**game of life**) through the created service external ip address, whereas the other one (**spring petclinic**) simply does not run, whereas the service and deployment has been created similar to the other application.
Manually I have tested both the applications to be invoked/working through docker containers.

Here are the 2 YAML files for your reference:
**spc-deployment**
[spc-deployment-txt.txt](https://github.com/QT-DevOps/DevOpsIssues/files/4315998/spc-deployment-txt.txt)
**gol-deployment**
[gol-deployment-txt.txt](https://github.com/QT-DevOps/DevOpsIssues/files/4315999/gol-deployment-txt.txt)

Please help me find out where did I go wrong...

Thanks
Debasis

**Comment by shaikkhajaibrahim** [comment]
Doesnt run is fine, where are logs?
