### ISSUE TITLE
I am unable to expose docker container to external using ec2 instance public ip address

### ISSUE THREAD

**Issue by Saikrishna57429** [QT-DevOps/DevOpsIssues#763]
I had run the below docker command in linux machine after installing docker in that ubuntu machine

docker run -d -p 8080:8080 tomcat:8
![DockerContainer](https://user-images.githubusercontent.com/62132061/76599215-87d2ea80-652a-11ea-8ad9-e7b75ac7e1da.PNG)

I had got the below error

![Error](https://user-images.githubusercontent.com/62132061/76599266-a89b4000-652a-11ea-8769-edd139835dbe.PNG)

**Comment by dhana9000** [comment]
hi saikrishna,
Error 404 doesn't mean that your tomcat is not working it only shows that it is unable to find index files.

**Comment by raviops99** [comment]
Hi saikrishna,
The error is related to port mapping
Reason: if  u don't open 8080 Port in AWS cloud machine
Reason 2 : did u write expose 8080 in docker file
Please check these 2 possibilities
Please share your docker file
