### ISSUE TITLE
unable to login with  node's ip into acs 

### ISSUE THREAD

**Issue by pradeeprepati** [QT-DevOps/DevOpsIssues#764]
while login with nodes ip in acs, it is getting error "permission denied(publickey)" how to solve it

**Comment by dhana9000** [comment]
Hi pradeep,
If you use username & ip to login into machine, it might be the issue with configuring sshd_config file.
once ensure that you have configured sshd_config file and restarted sshd service.

**Comment by pradeeprepati** [comment]
[](url)
this is the error

**Comment by pradeeprepati** [comment]
root@ip-172-31-32-71:/# ssh 172.31.36.59
root@172.31.36.59's password:
Permission denied, please try again.
root@172.31.36.59's password:
Permission denied, please try again.



this is the error

**Comment by pradeeprepati** [comment]
eventhough i entered correct password it is coming like that only

**Comment by dhana9000** [comment]
hi, 
switch to user and  execute ssh.
![Capture1](https://user-images.githubusercontent.com/58977739/76679628-11a4b580-6608-11ea-9dbb-c261c5b93cdf.PNG)

**Comment by pradeeprepati** [comment]
thankyou
