### ISSUE TITLE
NAGIOS IS NOT RUNNING

### ISSUE THREAD

**Issue by sailakshmi1** [QT-DevOps/DevOpsIssues#766]
i am trying to install nagios on ubuntu 18.04 by following this documentation. https://support.nagios.com/kb/article/nagios-core-installing-nagios-core-from-source-96.html#Ubuntu

it is asking to open inbound 80 port on local firewall, i have done it. but unable to run nagios.
I have tested using http://ipaddress/nagios
iam getting the below error
**The requested URL was not found on this server.

Apache/2.4.29 (Ubuntu) Server at 34.219.168.205 Port 80**

**Comment by shaikkhajaibrahim** [comment]
please send the whole list of commands which you executed and the changes made by you

**Comment by sailakshmi1** [comment]
Ubuntu 18.x 

sudo apt-get update
sudo apt-get install -y autoconf gcc libc6 make wget unzip apache2 php libapache2-mod-php7.2 libgd-dev

cd /tmp
wget -O nagioscore.tar.gz https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.5.tar.gz
tar xzf nagioscore.tar.gz

cd /tmp/nagioscore-nagios-4.4.5/
sudo ./configure --with-httpd-conf=/etc/apache2/sites-enabled
sudo make all

sudo make install-groups-users
sudo usermod -a -G nagios www-data

sudo make install
sudo make install-daemoninit
sudo make install-commandmode
sudo make install-config

sudo make install-webconf
sudo a2enmod rewrite
sudo a2enmod cgi
-----------------------------------------------
[ upto here no problem ]

Configure Firewall
You need to allow port 80 inbound traffic on the local firewall so you can reach the Nagios Core web interface.

sudo ufw allow Apache
sudo ufw reload
 
![test](https://user-images.githubusercontent.com/58159448/76735599-748a6f80-6722-11ea-93de-2de7a1496076.png)

**Comment by srmanikanta** [comment]
In ubuntu by default the ufw is disabled. 
* so if want to enable execute the below command
`sudo ufw enable`
* You need to allow port 80 inbound traffic on the local firewal.
` sudo ufw allow Apache`
` sudo ufw reload`
* the the firewall status
`sudo ufw status`

* set the password of nagiosadmin user to follow the below command
* it asks password then provide the new password of nagiosadmin user
`sudo htpasswd -c /usr/local/nagios/etc/htpasswd.users nagiosadmin`
* restart the nagios server 
` sudo systemctl restart apache2.service`
* check the nagios server is up and running
* finally enable 80 port in your aws security group 
* test the nagios server
`http://<publicip/nagios/`
* it asks  username and password in ourcase the username is nagiosadmin and the password is whatever you recently set for nagiosadmin provide those credentials.

 please follow the above steps it is  successfully running nagios server.
please close the issue.

**Comment by srmanikanta** [comment]
please close the issue.
