### ISSUE TITLE
ansible node is not connecting to node

### ISSUE THREAD

**Issue by pradeeprepati** [QT-DevOps/DevOpsIssues#767]
![Capture3](https://user-images.githubusercontent.com/58842251/76696645-d069df80-66b3-11ea-988b-0e97a263911c.PNG)
![Capture4](https://user-images.githubusercontent.com/58842251/76696654-d364d000-66b3-11ea-9efb-cf8d16d7260f.PNG)

i have tried connecting node with root user as well as ansible user. error is coming like this in both ways

**Comment by shaikkhajaibrahim** [comment]
which user have you configured ansible with  i mean you should have created a user right

**Comment by pradeeprepati** [comment]
i have configured ansible with devops user

**Comment by srmanikanta** [comment]
please check the below things:
* Create a devops user(or any name) in both the acs master and node
* Add the user in visudo
* enable the password and publickey authentication in /etc/ssh/sshd_config
* restart the sshd service `service sshd restart` 
* once the above configuration is done then goto ansible control server(acs)
* switch as devops user
* generate ssh key `ssh-keygen`
* copy the public key from acs to nodes`ssh-copy-id  devops@<nodeprivateip>`
* once copy the public key check the connection `ssh devops@nodeprivateip`

connection is success your configuration is done.

finally create an inventory, check the connection 
`ansible -m ping -i inventory all`

I think above process is helpful to you please close the issue.
If not useful this process please ignore.
