### ISSUE TITLE
ansible -i <path to inventory> -m ping all not working

### ISSUE THREAD

**Issue by sailakshmi1** [QT-DevOps/DevOpsIssues#769]
getting this error
![test2](https://user-images.githubusercontent.com/58159448/76735742-cfbc6200-6722-11ea-9f23-0e95fc41787d.png)

**Comment by dhana9000** [comment]
Hi sailakshmi,
execute "ssh  ipadress" on ACS node and check whether ssh is working  or not, if it is working, once try to execute "ssh-copy-id private-ipaddress(of node you want to connect) " and execute "ansible -i inventory -m ping all"

**Comment by Ranganath-Github** [comment]
In your case, inventory has which IP address? is it Public IP or Private IP ?

**Comment by sailakshmi1** [comment]
Inventory has private ip addresses.

**Comment by sailakshmi1** [comment]
I did ssh ipaddress and it is working..I am able to login nodes but unable to ping

**Comment by dhana9000** [comment]
did it ask for password when you executed ssh ipaddress???

**Comment by srmanikanta** [comment]
please check the below things:

* Create a devops user(or any name) in both the acs master and node
* Add the user in visudo
* enable the password and publickey authentication and password authentication in /etc/ssh/sshd_config
* restart the sshd service service sshd restart
* once the above configuration is done then goto ansible control server(acs)
* switch as devops user
* generate ssh key ssh-keygen
* copy the public key from acs to nodesssh-copy-id devops@<nodeprivateip>
* once copy the public key check the connection ssh devops@nodeprivateip
* connection is success your configuration is done.

* finally create an inventory, check the connection
ansible -m ping -i inventory all

I think above process is helpful to you please close the issue.
If not useful this process please ignore.

**Comment by srmanikanta** [comment]
please close the issue
