### ISSUE TITLE
Jenkins pipeline script for deploy war files to tomcat

### ISSUE THREAD

**Issue by durganaidu191604** [QT-DevOps/DevOpsIssues#77]
Hi All,
If any one please suggest me while deploying war file using Jenkins pipeline script i'm getting below error
ERROR: Failed to run ssh-add

Thanks

**Comment by MuraliTL25** [comment]
Please attach your console output details

**Comment by durganaidu191604** [comment]
Hi Murali,
FYI.,

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.290 s
[INFO] Finished at: 2018-08-01T14:31:51Z
[INFO] ------------------------------------------------------------------------
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Deploy to Tomcat)
[Pipeline] sshagent
[ssh-agent] Using credentials ec2-user (tomcat-dev)
[ssh-agent] Looking for ssh-agent implementation...
[ssh-agent]   Exec ssh-agent (binary ssh-agent on a remote machine)
$ ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-dcvw7r0vYC6F/agent.4109
SSH_AGENT_PID=4111
Running ssh-add (command line suppressed)
Identity added: /var/lib/jenkins/workspace/deploy-to-tomcat@tmp/private_key_8687831602340364059.key (/var/lib/jenkins/workspace/deploy-to-tomcat@tmp/private_key_8687831602340364059.key)
[ssh-agent] Started.
[Pipeline] {
[Pipeline] sh
$ ssh-agent -k
unset SSH_AUTH_SOCK;
unset SSH_AGENT_PID;
echo Agent pid 4111 killed;
[ssh-agent] Stopped.
[deploy-to-tomcat] Running shell script
+ scp -o StrictHostKeyChecking=no target/myweb-0.0.1.war ec2-user@10.0.2.208:/opt/tomcat/webapps/
scp: /opt/tomcat/webapps/: No such file or directory
[Pipeline] }
[Pipeline] // sshagent
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by shaikkhajaibrahim** [comment]
Why SCP?
why not ansible copy?
________________________________

**Comment by durganaidu191604** [comment]
Hi Sir,

problem solved now its working fine
