### ISSUE TITLE
Jenkins server is showing error ..How can i fix it?

### ISSUE THREAD

**Issue by prasadsai528** [QT-DevOps/DevOpsIssues#770]
While plugins are downloading i will disturb that then its showing like attach below..

![jenkins server Error](https://user-images.githubusercontent.com/55782151/76826068-89a9f000-6841-11ea-9553-3f1590c81f70.PNG)

**Comment by dhana9000** [comment]
Hi prasadsai,
1.Delete JENKINS_HOME/plugins/pluginname.jpi.disabled for the respective plugins
2.Restart jenkins service

**Comment by prasadsai528** [comment]
> Hi prasadsai,
> 1.Delete JENKINS_HOME/plugins/pluginname.jpi.disabled for the respective plugins
> 2.Restart jenkins service
Bro..
Its not resolved, i forgot the plugins names .Even i check the logs of jenkins i not able to reslove issue

**Comment by dhana9000** [comment]
hi,
once try this out: 
cd /var/lib/jenkins/plugins
ls -la | grep disable
remove plugins which are disabled

**Comment by srmanikanta** [comment]
hi, prasadsai 
restart the jenkins server.
if resolved this issue please close the issue
