### ISSUE TITLE
while executing playbook

### ISSUE THREAD

**Issue by Rajulolabhattu** [QT-DevOps/DevOpsIssues#771]
ERROR! 'handler' is not a valid attribute for a Play

The error appears to have been in '/home/devops/raju.yml': line 2, column 4, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
 - hosts: all
   ^ here

**Comment by dhana9000** [comment]
Hi Raju,
use "handlers" instead of handler

**Comment by Rajulolabhattu** [comment]
hi dhana9000
i'm using "handlers" only

**Comment by dhana9000** [comment]
Hi,
once check the position of handlers 
- hosts: all
  become: yes
  tasks: 
    ....
    ...
  handlers:
    ...

if not solved plz share your play-book

**Comment by Rajulolabhattu** [comment]
---
 - hosts: all
   become: yes
   vars:
     package:
       - httpd
       - httpd httpd-tools
     pack:
       - php
       - php-fpm
       - php-mysqlnd
       - php-gd
       - php-xml
       - php-mbstring
 - tasks:
     - name: fail the playbook on unsupported platform
       fail:
         mgs: 'this playbook only runs on centOS'
       when: ansible_distribution != 'centOS'
     - name: install httpd
       yum:
         name: "{{ item }}"
         state: present
         update_cache: yes
       loop: "{{ package }}"
       notify:
         - httpd installed
         - httpd service
     - name: install mariadb-service
       yum:
        name: mariadb
        state: present
       notify:
         - installed mariadb
         - mariadb service
     - name: install php_modules
       yum:
         name: "{{ item }}"
         state: present
       loop: "{{ pack }}"
       notify:
         - installed pack
         - httpd service
   handlers:
     - name: httpd installed
       debug:
         mgs: "{{package}} are installed httpd"
     - name: installed mariadb
       debug:
         mgs: istalled mariadb
     - name: installed pack
       debug:
         mgs: " {{ pack }} is installed "
     - name: httpd service
       service:
         name: httpd
         enabled: yes
         state: restarted

**Comment by Rajulolabhattu** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/62057171/77016837-d48d4a00-699e-11ea-932c-c075c34ee435.png)
![Screenshot (11)](https://user-images.githubusercontent.com/62057171/77016841-d5be7700-699e-11ea-815b-8f453d066ff2.png)

**Comment by Rajulolabhattu** [comment]
in vars: package: i found that httpd httpd tools are not required ,Even though i remove that it can't run the program

**Comment by dhana9000** [comment]
tasks will not have "-"

**Comment by srmanikanta** [comment]
Please verify your playbook once
this is syntax error, first remove the `-`  infront of tasks then try 
please give a feedback . if you resolved already please close the issue.

**Comment by Rajulolabhattu** [comment]
i removed the '-' infront of the tasks but i got new issue please go through below
![Screenshot (13)](https://user-images.githubusercontent.com/62057171/77062910-c96c0580-6a02-11ea-8a8b-c7b54234bee8.png)

**Comment by dhana9000** [comment]
In ansible condition "when: ansible_distribution != centOS "
in centOs  "C"  should be capital "CentOS"

**Comment by Rajulolabhattu** [comment]
even though its not working

**Comment by srmanikanta** [comment]
please check your mentioned  nodeip is centos or ubuntu
if you face the same issue then share your playbook here

**Comment by dhana9000** [comment]
In fail module you wrote mgs: it's msg:

**Comment by Rajulolabhattu** [comment]
till im not getting dhana while im doing syntax check it shows every thing good

i mentioned centos ip only srmanikanta

**Comment by srmanikanta** [comment]
please share your playbook

**Comment by Rajulolabhattu** [comment]
@srmanikanta 
![Screenshot (17)](https://user-images.githubusercontent.com/62057171/77148826-53c17180-6ab6-11ea-91bc-800cab81ac17.png)
![Screenshot (18)](https://user-images.githubusercontent.com/62057171/77148830-5754f880-6ab6-11ea-8610-fc3b9f7c01c2.png)

**Comment by dhana9000** [comment]
once try "ansible_distribution != CentOS"
and msg: instead od mgs:

**Comment by Rajulolabhattu** [comment]
thankq @dhana9000  its working

**Comment by Rajulolabhattu** [comment]
thanks @srmanikanta for your support
