### ISSUE TITLE
error while using view push commands

### ISSUE THREAD

**Issue by abhisheknayak101** [QT-DevOps/DevOpsIssues#773]
i am getting error "cannot perform on non tty device " while using "aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin <account id>.dkr.ecr.us-west-2.amazonaws.com/studentcoursesevice"

p.s - i removed my account id above for security purpose

[
![error](https://user-images.githubusercontent.com/59557076/77035745-7fb7f680-69d3-11ea-9e6b-a58b41bc1458.png)
](url)

**Comment by srmanikanta** [comment]
* goto your aws ecr then select your repository
* click on view push commands
* then copy the login commad of your ecr and paste it in your terminal.
* this command is helpful for login into your ecr
