### ISSUE TITLE
Facing an issue while installling bahmni manually on Centos machine

### ISSUE THREAD

**Issue by Ranganath-Github** [QT-DevOps/DevOpsIssues#774]
Hi,

While manually installing bahmni on Centos machine, facing issue as below;

<img width="926" alt="Bahmni_Installation_issue" src="https://user-images.githubusercontent.com/58923523/77154925-b28ce800-6ac2-11ea-85f1-349f06d929e2.PNG">

Please let me know how to troubleshoot the above issue.

Thanks,

**Comment by srmanikanta** [comment]
Try to install bahmni manually on centos for reference [click here](https://www.youtube.com/results?search_query=install+bahmni+on+centos+7)

once the manuall execution is success then write playbook step by step it might help to correct errors.

if you face any error related to ansible playbook use -vvv for troubleshoot.

**Comment by shaikkhajaibrahim** [comment]
Please resolve challenges on your own
