### ISSUE TITLE
getting error while running touch cmd after creating user ansibleadmin user and giving sudo privilage 

### ISSUE THREAD

**Issue by singaravellu** [QT-DevOps/DevOpsIssues#776]
![image](https://user-images.githubusercontent.com/32475854/77245717-a9c51f00-6c46-11ea-9917-0f1ba7ec769e.png)
suggest me if i am worng 

![image](https://user-images.githubusercontent.com/32475854/77245731-c8c3b100-6c46-11ea-877f-c8c81d75ffd3.png)

**Comment by dhana9000** [comment]
Hi, 
Username ALL=(ALL:ALL) NOPASSWD: ALL  line 
Should be under %sudo

**Comment by singaravellu** [comment]
ok let me try

**Comment by singaravellu** [comment]
![image](https://user-images.githubusercontent.com/32475854/77248526-08e35d80-6c60-11ea-9fbb-c8a00951853b.png)
i am getting this error while executing playbook.yml could you help

**Comment by singaravellu** [comment]
i got the issue ansible node should also have sudo privilages  as above now it's working fiine.

**Comment by dhana9000** [comment]
ok, plz close the issue
