### ISSUE TITLE
 Failed to start SonarQube service. Mar 22 15:45:39 jenkins systemd[1]: sonarqube.service: Unit entered failed state. Mar 22 15:45:39 jenkins systemd[1]: sonarqube.service: Failed with result 'start-limit-hit'.

### ISSUE THREAD

**Issue by ijazm123** [QT-DevOps/DevOpsIssues#777]
Failed to start SonarQube service.
Mar 22 15:45:39 jenkins systemd[1]: sonarqube.service: Unit entered failed state.
Mar 22 15:45:39 jenkins systemd[1]: sonarqube.service: Failed with result 'start-limit-hit'.

**Comment by dhana9000** [comment]
hi, 
ensure that u are using t2.medium

**Comment by srmanikanta** [comment]
sonarqube requires the below prerequisites if you done already please close the issue
The SonarQube server requires at least 2GB of RAM to run efficiently and 1GB of free RAM for the OS.

please launch minimum 4GB of RAM machine and try
