### ISSUE TITLE
getting error as-  {"msg": "template error while templating string: unexpected '/'. String: {{ /home/centos }}"}

### ISSUE THREAD

**Issue by Rupini93** [QT-DevOps/DevOpsIssues#781]
Installed nagios, on centos. manually getting home page, but getting error as -  FAILED! => {"msg": "template error while templating string: unexpected '/'. String: {{ /home/centos }}"}

![Screenshot (132)](https://user-images.githubusercontent.com/57709400/77704695-e3fe2b80-6f7a-11ea-8aa0-4a9c184f8939.png)

**Comment by dhana9000** [comment]
Please share your playbook

**Comment by srmanikanta** [comment]
above error comes when you are provide a variable value instead of its name.
please check your playbook and correct for reference [click here](https://stackoverflow.com/questions/43628823/ansible-template-error-while-templating-string-unexpected)
if you solved the above error pleae close the issue.
