### ISSUE TITLE
Ansible playbook error

### ISSUE THREAD

**Issue by ashok655** [QT-DevOps/DevOpsIssues#782]
Getting an error when build an docker image using ansible playbook

play book
--------------

---
- hosts: all
  become: yes
  tasks:
  - name: installing python packages
    apt:
      name: python-pip
      update_cache: yes
      state: present
  - name: installing pip packages
    pip:
      name: docker
  - name: building image
    docker_image:
      name: firstimage
      path: docker
      state: build

Error:
---------
[WARNING]: Please specify build.pull instead of pull. The pull option has been renamed and will be removed in
Ansible 2.12.
[DEPRECATION WARNING]: Param 'pull' is deprecated. See the module docs for more information. This feature will
be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
fatal: [172.31.87.72]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "archive_path": null,
            "build": {
                "args": null,
                "cache_from": null,
                "container_limits": null,
                "dockerfile": null,
                "etc_hosts": null,
                "http_timeout": null,
                "network": null,
                "nocache": false,
                "path": "docker",
                "pull": false,
                "rm": true,
                "target": null,
                "use_config_proxy": null
            },
            "buildargs": null,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "container_limits": null,
            "debug": false,
            "docker_host": "unix://var/run/docker.sock",
            "dockerfile": null,
            "force": null,
            "force_absent": false,
            "force_source": false,
            "force_tag": false,
            "http_timeout": null,
            "load_path": null,
            "name": "firstimage",
            "nocache": false,
            "path": null,
            "pull": false,
            "push": false,
            "repository": null,
            "rm": true,
            "source": "build",
            "ssl_version": null,
            "state": "present",
            "tag": "latest",
            "timeout": 60,
            "tls": false,
            "tls_hostname": "localhost",
            "use_tls": null,
            "validate_certs": false
        }
    },
    "msg": "Requested build path docker could not be found or you do not have access."

**Comment by RahulAnita** [comment]
You have to provide full path in path: docker.

**Comment by ashok655** [comment]
> You have to provide full path in path: docker.

I tried with full path still same error

**Comment by srmanikanta** [comment]
follw this link [click here](http://opensolitude.com/2015/05/26/building-docker-images-with-ansible.html)
