### ISSUE TITLE
I have tried to install Jenkins on Redhat, Amazon Linux, Centos but always getting errors

### ISSUE THREAD

**Issue by ranjith1428** [QT-DevOps/DevOpsIssues#783]
**I have executed below commands:**

yum update
yum install java-1.8*

vim ~/.bash_profile

JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-1.el8_0.x86_64
export JAVA_HOME
PATH=$PATH:$JAVA_HOME

yum -y install wget
wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
yum -y install jenkins

service jenkins start

chkconfig jenkins on
After this Step:
![image](https://user-images.githubusercontent.com/62072459/78113145-ea7a2080-741c-11ea-95df-617a652f74c1.png)

Iam Getting Error like that:

![image](https://user-images.githubusercontent.com/62072459/78113047-c3bbea00-741c-11ea-8f31-fb5f2981eb30.png)

**Comment by dhana9000** [comment]
Hi, I don't know exactly, but it might be due to internet issues, even I faced the same problem, when I run Jenkins on Ubuntu.

**Comment by srmanikanta** [comment]
it is network issue please update the issue or close this if solved

**Comment by ranjith1428** [comment]
At this I Have Skipped Plugins installation Step, Than Its worked for me
![image](https://user-images.githubusercontent.com/62072459/78333008-ae72c700-75a6-11ea-91bb-3536d27a96ff.png)
