### ISSUE TITLE
docker image is failing with the following error

### ISSUE THREAD

**Issue by tabrez78** [QT-DevOps/DevOpsIssues#784]
Step 13/14 : RUN pip install -r requirements.txt
 ---> Running in cc5c8c73a6ba
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1

**Comment by srmanikanta** [comment]
tabrez it is path issue. you are trying to install requirements.txt  but requirements.txt is not in your ralative path. try workdir or absolute path.
