### ISSUE TITLE
“Could not load file or assembly ‘System.Web,Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a’

### ISSUE THREAD

**Issue by radhakrishna108** [QT-DevOps/DevOpsIssues#788]
when i am running any commands in cmd or powershell i am getting “Could not load file or assembly ‘System.Web,Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a’ this error how to resolve this...?

![error](https://user-images.githubusercontent.com/30693808/78827520-dd52c800-7a00-11ea-8225-b3fe5a9c200e.PNG)

![image](https://user-images.githubusercontent.com/30693808/78827718-328ed980-7a01-11ea-9eea-0444514b103b.png)

**Comment by srmanikanta** [comment]
This issue can be caused by missing or damaged Microsoft .NET Framework 4 files
To resolve the issue
Repair Microsoft .NET 4 Framework
or Uninstall and reinstall Microsoft .NET 4 Framework
