### ISSUE TITLE
Regarding to create a chefclient in centos instance

### ISSUE THREAD

**Issue by MadalaSwetha** [QT-DevOps/DevOpsIssues#789]
Please find attachment of error while creating chefclient in centos instance. Please find resolution.
![Chefclient1](https://user-images.githubusercontent.com/39823207/79041626-d699a000-7c0e-11ea-923a-6ab0e906b617.PNG)

**Comment by dhana9000** [comment]
Hi,
Give path to pem file

**Comment by MadalaSwetha** [comment]
Please find path of pem file.
C:\Users\Dell\Downloads\chef-repo\Chef.pem

Regards,
Swetha.

**Comment by dhana9000** [comment]
Once try this
knife bootstrap <ipaddress> -U <username> -i ./chef.pem --sudo -N '<name of node>

**Comment by dhana9000** [comment]
Once try this
knife bootstrap ipaddress -U username -i ./chef --sudo -N 'name of node'

**Comment by srmanikanta** [comment]
This error is related to your pem file which is not currently identified in your chef-repo 
so please mention the path like this  -i .\chef.pem in  your command

**Comment by MadalaSwetha** [comment]
Hi Team,

I fixed my issue. Thank you for your support.

Regards,
Swetha.

**Comment by MadalaSwetha** [comment]
I fixed this issue with the help of QT Team. Thank You team
