### ISSUE TITLE
Unable to deploy war file into tomcat webapps on using role concept  

### ISSUE THREAD

**Issue by sanjivak** [QT-DevOps/DevOpsIssues#79]
=> Executed      ansible-galaxy install geerlingguy.java
=> Executed      ansible-galaxy install idealista.tomcat-role

written my yaml code given below.

---
- hosts: all
  become: yes
  roles:
  - geerlingguy.java
  - idealista.tomcat-role
  tasks:
  - name: copy war
    copy:
      src: gameoflife.war
      dest: /opt/tomcat/webapps/gameoflife.war
    notify:
    - restart tomcat
  handlers:
  - name: restart tomcat
    service: 
      name: tomcat
      state: restarted
      enabled: yes
      

=> while Executing yml file , i am getting error as given in the screen shot.
=> here the role folder where exits in the path /etc/ansible/roles/geerlingguy.java/tasks/main.yml

![gol error](https://user-images.githubusercontent.com/38131789/43562682-8c0d63ec-963b-11e8-9e60-efe655a9bdb6.PNG)

**Comment by shaikkhajaibrahim** [comment]
Copying war is not role it is task and restarting tomcat is handler
________________________________

**Comment by sanjivak** [comment]
Hi sir,
  The issue is occuring while running the cmd 
       => ansible-playbook  gameoflife.yml
=> on executing the above command saying there is an syntax error in geerlinguy.java
=> but as per that there is no error in geerlingguy.java and I am still facing this issue.


![gol error](https://user-images.githubusercontent.com/38131789/43565545-aaea3ed6-9648-11e8-9603-650663dea465.PNG)

**Comment by shaikkhajaibrahim** [comment]
Why include_tasks?
can you share complete zip

**Comment by shaikkhajaibrahim** [comment]
Closing issue as zip is not shared
