### ISSUE TITLE
How to connect the Oracle DB in K8S if its on-premise end.

### ISSUE THREAD

**Issue by adamalli01** [QT-DevOps/DevOpsIssues#791]
Suppose if web sever is running in K8S and i want to connect the DB from on-premise end. Please suggest me on this.

**Comment by srmanikanta** [comment]
follow this link [click here](https://directdevops.blog/2019/11/02/deploying-the-docker-application-and-mysql-with-volume-support-into-kubernetes-from-code-to-docker-registries-like-acr-ecr-and-then-to-eks-aks/)
this link is about eks and also aks but you can use this process to add the database to your webserver 
I think it might helpful if not please ignore.

**Comment by NareshAbbanapuri** [comment]
use direct connect

**Comment by NareshAbbanapuri** [comment]
please close issue

**Comment by shaikkhajaibrahim** [comment]
Where is k8s running (On Cloud) ?
Need more information for a specific answer

**Comment by adamalli01** [comment]
yes sir,K8S is running in AWS cloud(Web server only running) and Oracle DB is running in On premises. So its should be communicate to each other. How to setup this and what are the parameter i have to pass.

**Comment by shaikkhajaibrahim** [comment]
Use aks and vpn
