### ISSUE TITLE
want to set the command in a loop

### ISSUE THREAD

**Issue by Rajulolabhattu** [QT-DevOps/DevOpsIssues#792]
![Screenshot (69)](https://user-images.githubusercontent.com/62057171/79075895-3b3e2300-7d13-11ea-9129-bce39135aa4b.png)

i just want to pass the above command single time by using loop condition. can anyone suggest me how to write the loop statement for the above program and my assumption is given below

---
- name: creating a mysql database
  cmd: mysql -u root -p'root'
    name: "{{item}}"
    state: present
  loop:
    - CREATE DATABASE zabbixdb character set utf8 collate utf8_bin;
    - CREATE USER 'zabbix'@'localhost' IDENTIFIED BY 'password';
    - GRANT ALL PRIVILEGES ON zabbixdb.* TO 'zabbix'@'localhost' WITH GRANT OPTION;
    - FLUSH PRIVILEGES;

**Comment by srmanikanta** [comment]
write a shellscript for your commands and then execute that script using shell or cmd module.

**Comment by Rajulolabhattu** [comment]
![Screenshot (74)](https://user-images.githubusercontent.com/62057171/79119353-c66bf700-7dad-11ea-9e48-e7edc08b4e98.png)
i changed the script like this but im not getting how to run the command only once
