### ISSUE TITLE
got error in chef

### ISSUE THREAD

**Issue by chaithanyach** [QT-DevOps/DevOpsIssues#793]
![april11  resource](https://user-images.githubusercontent.com/59727648/79104755-d6bfaa00-7d8c-11ea-87b2-c1298ca45751.png)
![april11 error](https://user-images.githubusercontent.com/59727648/79104759-d7584080-7d8c-11ea-85cd-033c99468f99.png)
while convergence   i got this error when i execute sudo chef-client command please help me out this

**Comment by srmanikanta** [comment]
please post the error indetail.
hi chaithanya 
please follow the below steps I think you are skip some steps please identify and correct it.
1. generate cookbook.command is
 chef generate cookbbok <cookbookname>  -b (don't forget to mention -b)
2. next step is generate a recipe or use the default one
 once your recipe is done 
knife generate recipe cookbookpath recipename 
3. upload the cook book to your chef server
change to your cookbook
cd cookbookname
berks install 
berks upload

then chekc your runlist and add the recipe and execute the cookbook manually or wait for convergence time.

**Comment by shaikkhajaibrahim** [comment]
Closing as no response from 9 days
