### ISSUE TITLE
i'm getting an error while executing the below below ansible play book.

### ISSUE THREAD

**Issue by vijayamadiri** [QT-DevOps/DevOpsIssues#794]
---
- hosts: all
  become: yes
  tasks:
    - name: fail this playbook on Centos falvours
      fail:
        msg: 'this playbook is developed only for ubuntu_flavour'
      when: ansible_distribution != 'ubuntu'
    - name: Install and update apahe2
      apt:  
        name: apache2
        update_cache: yes
        State: present
    - name: install php module
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - libapache2-mod-php
        - php-mysql
        - php-cli
    - name: restart and enable apache2
      service:
        name: apache2
        enabled: yes
        state: restarted

Error message:
PLAY [all] *******************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************
ok: [172.31.46.39]
[DEPRECATION WARNING]: Distribution Ubuntu 18.04 on host 172.31.34.111 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release
 will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information. This feature will be removed
in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [172.31.34.111]

TASK [fail this playbook on Centos falvours] *********************************************************************************************************************************************************************
fatal: [172.31.34.111]: FAILED! => {"changed": false, "msg": "This playbook is developed only for ubuntu_flavour"}
fatal: [172.31.46.39]: FAILED! => {"changed": false, "msg": "This playbook is developed only for ubuntu_flavour"}

PLAY RECAP *******************************************************************************************************************************************************************************************************
172.31.34.111              : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
172.31.46.39               : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by dhana9000** [comment]
Hi, 
Try this   
when: ansible_distribution != 'Ubuntu' , in ubuntu replace 'u' with capital 'U'

**Comment by vijayamadiri** [comment]
Hi dhana. Thanks for providing your comment. But still it is showing the below error message.
![image](https://user-images.githubusercontent.com/62703091/79186999-b0efdf00-7e38-11ea-94fb-5955f46b8a90.png)

**Comment by SandhyaKatigari** [comment]
Please check the syntax check command

**Comment by dhana9000** [comment]
as @SandhyaKatigari said use syntax check and in apt-module replace "State" with "state"

**Comment by NareshAbbanapuri** [comment]
hi
use when condition in each task

**Comment by vijayamadiri** [comment]
> Please check the syntax check command

Thanks for spending your time on this code. But tried with the syntax check as well. don't gave any errors. PFB screen shot.
![image](https://user-images.githubusercontent.com/62703091/79224374-989fb480-7e78-11ea-964c-044514fe8d14.png)

**Comment by vijayamadiri** [comment]
Now i got it. i didn't observe this.  "State" with "state". So Thank you very much for every one for your effort.
![image](https://user-images.githubusercontent.com/62703091/79226702-714ae680-7e7c-11ea-8884-c0c658b5c107.png)

**Comment by vijayamadiri** [comment]
Thank you very much for supporting this.
