### ISSUE TITLE
Save button is missing in Manage.chef.io

### ISSUE THREAD

**Issue by DivyasreeYanala** [QT-DevOps/DevOpsIssues#795]
<img width="513" alt="Capture" src="https://user-images.githubusercontent.com/63571979/79174209-f88a5280-7dc7-11ea-85a3-9b3fb75645d2.PNG">

**Comment by rpkoya** [comment]
It may be issue with your screen size please check once, it should be like below.

![image](https://user-images.githubusercontent.com/63572053/79178660-69128d00-7e23-11ea-8901-e1d4befdfa57.png)

**Comment by DivyasreeYanala** [comment]
Settings are normal. I don't find issue with settings.

**Comment by rpkoya** [comment]
Can you provide me remote access of your system to check.

Regards,
Ravindra.

**Comment by DivyasreeYanala** [comment]
yeah sure but how to give access?

**Comment by rpkoya** [comment]
download Anydesk and provide details.

**Comment by DivyasreeYanala** [comment]
![image](https://user-images.githubusercontent.com/63571979/79181725-11e8ca00-7ddb-11ea-82c6-0a4598d1f0fc.png)
