### ISSUE TITLE
Facing error while generating cookbook

### ISSUE THREAD

**Issue by SandhyaKatigari** [QT-DevOps/DevOpsIssues#797]
I am getting below error while trying to generate cookbook.
Please help me.
![image](https://user-images.githubusercontent.com/63640375/79209021-7a2dbf00-7e60-11ea-8adf-b5de47e2f435.png)

**Comment by srmanikanta** [comment]
download the chef-starter kit to another location or copy this to some where in your windows system 
or else run the powershell as administrator and try to generate the cookbook.
I think this work if not update the issue.

**Comment by SandhyaKatigari** [comment]
Thanks for the inputs.
After changing the chef-starter location i am able to generate cookbook.
