### ISSUE TITLE
aws machine logging error

### ISSUE THREAD

**Issue by saireddy224** [QT-DevOps/DevOpsIssues#80]
i am unable to logging into my aws machine using git bash.i am getting error
![capture1](https://user-images.githubusercontent.com/7966678/43567605-d0baf900-964f-11e8-84b3-3aafbeb3abff.PNG)

**Comment by arunkumar127** [comment]
Hi @saireddy224 

Are you using Ubuntu machine?
If so use **ubuntu** instead of **ec2-user**

Command:
ssh -i "Ansible.pem" ubuntu@ec2-54-89-225-247.compute-1.amazonaws.com

**Comment by shaikkhajaibrahim** [comment]
I dont see you entering yes

**Comment by nempati** [comment]
after pasting the SSH cmd we must type:yes and execute it

**Comment by mani5a3** [comment]
closed
