### ISSUE TITLE
unable to run kitchen converge

### ISSUE THREAD

**Issue by rpkoya** [QT-DevOps/DevOpsIssues#800]
I am getting below error while running kitchen converge, please help..

![image](https://user-images.githubusercontent.com/63572053/79348093-256a7100-7f52-11ea-9c70-e0bca5886293.png)

**Comment by dbalamurugan** [comment]
please check your kitchen.yml file transport: alignment it correct.

**Comment by rpkoya** [comment]
No, its placement issue, earlier i placed transport content above verifier, it didn't worked, now i placed that content below verifier, its worked, my working content is as below.
-------------
verifier:
  name: inspec

transport:
    ssh_key: "./kitchen.pem"
    connection_timeout: 10
    connection_retries: 3
    username: ubuntu 
----------
