### ISSUE TITLE
Error while authenicating Test Kitchen with AWS

### ISSUE THREAD

**Issue by DivyasreeYanala** [QT-DevOps/DevOpsIssues#801]
![image](https://user-images.githubusercontent.com/63571979/79365831-29c66800-7f19-11ea-9843-d932bbb32743.png)

**Comment by Rajulolabhattu** [comment]
Did u install aws CLI

**Comment by DivyasreeYanala** [comment]
Yes , problem with CLI.
Thanks for the help
