### ISSUE TITLE
error when creating a sonarqube container by using the docker-compose

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/DevOpsIssues#802]
the logs od the docker-compose od sonarqube find below
when i creating the container ,the sonarqube container is down immeadiatly
version: "3.3"
services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    restart: always
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
  db:
    image: postgres
    container_name: postgres
    restart: always
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
![Screenshot from 2020-04-15 23-05-27](https://user-images.githubusercontent.com/50665358/79369890-54431000-7f6f-11ea-8ae1-a237a7aea700.png)
![Screenshot from 2020-04-15 23-05-32](https://user-images.githubusercontent.com/50665358/79369898-560cd380-7f6f-11ea-9266-6f808ae2e1be.png)
![Screenshot from 2020-04-15 23-05-57](https://user-images.githubusercontent.com/50665358/79369902-56a56a00-7f6f-11ea-81a2-eaf814f76051.png)

**Comment by srmanikanta** [comment]
follow this steps:
openjdk 11 is required.
sonar 7.x does not start the service as root user so create a normal user and  change the ownership recursively for  sonarqube package.
if your change the ownership still some logs are owned by root user delete those logs.
Note: are you configure this manually if not first try manually then write a compose file.
you face some problem in manual installation so try it first then correct those things in compose file.

**Comment by chowdamramana** [comment]
I am already installed java 11 in instance
Actually sonarqube runs with sonar users

**Comment by srmanikanta** [comment]
please read above and correct it.
are checking the sonarqube ownership can have  sonar user
and verify the ownership of the sonar logs (because logs as owned by root user in some cases remove those logs and try again)

**Comment by chowdamramana** [comment]
when changing the ownership of sonarlogs it works,I know ,without changing the ownership of volume in local how we can do

**Comment by srmanikanta** [comment]
are you resolve the issue chowdamramana? if you resolve the issue please close.
