### ISSUE TITLE
fatal cookbook file recipes/default.rb has a ruby syntax error

### ISSUE THREAD

**Issue by AddulAleem** [QT-DevOps/DevOpsIssues#803]
Hi,
I was trying to install git through cookbook but iam getting fatal ruby error 
i know its couple of days old but was busy just started practising .. please help me out 

Thanks  
![Fatal error ruby](https://user-images.githubusercontent.com/63742242/79369826-37a6d800-7f6f-11ea-8166-0e8b60577660.PNG)

**Comment by AddulAleem** [comment]
Further to my issue i've noticed the difference in text colour with this is ruby syntax error 
![My Recipe](https://user-images.githubusercontent.com/63742242/79408689-9133f480-7fb9-11ea-942f-36b1020f84b3.PNG)
![your Recipe](https://user-images.githubusercontent.com/63742242/79408693-92fdb800-7fb9-11ea-9406-39aa847cc7c4.PNG)

**Comment by AddulAleem** [comment]
[helloworld.zip](https://github.com/QT-DevOps/DevOpsIssues/files/4484630/helloworld.zip)

**Comment by srmanikanta** [comment]
use visual studio code for better syntax correction. 
and the logs for find the syntax error.

**Comment by AddulAleem** [comment]
i have already using VScode but didn't help the above screenshot i shared it was from vscode .. any way I have deleted the cookbook and created the new one which help.

i am closing this issue
