### ISSUE TITLE
I am having issue connecting to my ec2 instance

### ISSUE THREAD

**Issue by sharmatanmaya** [QT-DevOps/DevOpsIssues#804]
I have created the ec2 instance and then i tried conencting to it through powershell as well as git bash. Both the way are failing.
=======================================================
GitBash:
Tanmaya@DESKTOP-VQKB2GH MINGW64 /d/QualityThoughts/Chef/chef-repo/cookbooks/kitchenawsdemo (master)
$ ssh -i "../../chef.pem" ubuntu@ec2-18-188-66-185.us-east-2.compute.amazonaws.com

Tanmaya@DESKTOP-VQKB2GH MINGW64 /d/QualityThoughts/Chef/chef-repo/cookbooks/kitchenawsdemo (master)
$
==================================================
Powershell:
PS D:\QualityThoughts\Chef\chef-repo\cookbooks\kitchenawsdemo> kitchen login
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'D:/QualityThoughts/Chef/chef-repo/chef.pem' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "D:/QualityThoughts/Chef/chef-repo/chef.pem": bad permissions
ubuntu@ec2-18-188-66-185.us-east-2.compute.amazonaws.com: Permission denied (publickey).
PS D:\QualityThoughts\Chef\chef-repo\cookbooks\kitchenawsdemo> ssh -i ../../chef.pem ubuntu@18.188.66.185
The authenticity of host '18.188.66.185 (18.188.66.185)' can't be established.
ECDSA key fingerprint is SHA256:+hoSbD+K8EiEQ/I104PoxODhT70FJCmoVQb/N4FJZlk.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '18.188.66.185' (ECDSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for '../../chef.pem' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "../../chef.pem": bad permissions
ubuntu@18.188.66.185: Permission denied (publickey).

**Comment by rpkoya** [comment]
there is an issue with powershell, please try on Git it should connect, if its not connecting, please check the permissions, run the below command from your Git,
chmod 400 <your .pem file>

**Comment by sharmatanmaya** [comment]
I tried that many times, but no connection. Later after trying for about 20 mins it connected. But this is happening everytime I try to use gitbash to connect to ec2. Not sure what is the exact issue.

**Comment by srmanikanta** [comment]
please check your network connection and instance connectivity also so 
ping <instancepublicip >
check any packets are losed 
and more thing is verity vpc,security group.

**Comment by NareshAbbanapuri** [comment]
please share kitchen.yml

**Comment by sharmatanmaya** [comment]
it was intermittent issue, i am able to connenct now.
