### ISSUE TITLE
Facing ssh connection failed error while executing kitchen converge

### ISSUE THREAD

**Issue by SandhyaKatigari** [QT-DevOps/DevOpsIssues#806]
Hii,

I am getting ssh connection failed error while executing kitchen converge.
Please help me here.

![image](https://user-images.githubusercontent.com/63640375/79411295-2a660980-7fc0-11ea-8e6d-1f3a27a83315.png)

My kitchen.yml file
=====================================================
---
driver:
  name: ec2
  aws_ssh_key_id: chefnode
  region: ap-south-1
  availability_zone: ap-south-1a 
  subnet_id: subnet-027bf3b3bca5ec2a2
  instance_type: t2.micro
  image_id: 'ami-0620d12a9cf777c87'
  security_group_ids: ["sg-0da7fe3ef468e3bd3"]

## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15
transport:
ssh_key: "./chefnode.pem"
connection_timeout: 10
connection_retries: 3
username: ubuntu

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
#  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[awskitchen::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

![image](https://user-images.githubusercontent.com/63640375/79411629-e9bac000-7fc0-11ea-9a4c-0a411bc6e6bf.png)

===================================================

I have placed my .pem file in the below location.

![image](https://user-images.githubusercontent.com/63640375/79411448-7a44d080-7fc0-11ea-989f-aa430fd9dbc9.png)

**Comment by rpkoya** [comment]
Paste transport content below verifier field as below screenshot, it should work.

![image](https://user-images.githubusercontent.com/63572053/79422497-9ce3e300-7fda-11ea-9b5f-277aef6fa13b.png)

**Comment by srmanikanta** [comment]
the reason for failling this is :
* use the same region for, subnet,ami,security group and key pair 
* copy your instance pemfile to cookbook
* you wrote a kitchen.yml file for only ubuntu but try to converge two platform means centos7 so it does not work so comment the centos-7 platform or write thw configuration for ubuntu and centos in your kitchen.yml 
* give the correct  pem file path 
if you did not mention right path it says ssh  connection failed.
check the above things ans try again.

**Comment by SandhyaKatigari** [comment]
> Paste transport content below verifier field as below screenshot, it should work.
> 
> ![image](https://user-images.githubusercontent.com/63572053/79422497-9ce3e300-7fda-11ea-9b5f-277aef6fa13b.png)

**Comment by SandhyaKatigari** [comment]
> > Paste transport content below verifier field as below screenshot, it should work.
> > ![image](https://user-images.githubusercontent.com/63572053/79422497-9ce3e300-7fda-11ea-9b5f-277aef6fa13b.png)

Problem is with yaml syntax.
Thanks everyone for the support.
