### ISSUE TITLE
facing ssh connection failed while i executing kitchen converge  plese help me anyone 

### ISSUE THREAD

**Issue by ram-1912** [QT-DevOps/DevOpsIssues#808]
my kitchen.yml file is given below 
---
---
driver:
  name: ec2
  aws_ssh_key_id: junnu
  region: us-east-2
  availability_zone: us-east-2b
  subnet_id: subnet-a6a5fddc
  instance_type: t2.micro
  image_id: ami-0fc20dd1da406780b
  security_group_ids: ["sg-0c06b8cde59e6b264"]

## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15
  transport:
  ssh_key: "./junnu.pem"
  connection_timeout: 10
  connection_retries: 3
  username: ubuntu

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  # - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[ramkitchenaws::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:  
---
and also my cookbook folder is given below
<img width="958" alt="Annotation 2020-04-16 202220" src="https://user-images.githubusercontent.com/62230764/79471611-747ed780-8020-11ea-935d-7615dab7dd9c.png">
<img width="615" alt="Annotation 2020-04-16 202650" src="https://user-images.githubusercontent.com/62230764/79471817-b27bfb80-8020-11ea-8c05-53661d838929.png">

**Comment by SandhyaKatigari** [comment]
Hii,

Paste transport content below verifier filed. Check the below screenshot.

![image](https://user-images.githubusercontent.com/63640375/79476955-3cc75e00-8027-11ea-9eaf-39805d4471ad.png)

**Comment by ram-1912** [comment]
my kitchen.yml file is given below 
----

driver:
  name: ec2
  aws_ssh_key_id: junnu
  region: us-east-2
  availability_zone: us-east-2b
  subnet_id: subnet-a6a5fddc
  instance_type: t2.micro
  image_id: ami-0fc20dd1da406780b
  security_group_ids: ["sg-0c06b8cde59e6b264"]

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15
verifier:
  name: inspec

transport:
  ssh_key: ./junnu.pem
  connection_timeout: 10
  connection_retries: 3
  username: ubuntu

platforms:
  - name: ubuntu-18.04
  # - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[ramkitchenaws::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
<img width="261" alt="Annotation 2020-04-17 062556" src="https://user-images.githubusercontent.com/62230764/79520395-580c8a80-8074-11ea-97d4-3735878dd538.png">

**Comment by ram-1912** [comment]
i got the same error

**Comment by ram-1912** [comment]
i got the same error mam
