### ISSUE TITLE
getting ssh connection failed error while executing kitchen converge

### ISSUE THREAD

**Issue by manasa373767** [QT-DevOps/DevOpsIssues#809]
I tried all the ways to resolve this issue as u replied before for the same previous issues..
I tried by changing pem file path,yaml file allignment  order and i also tried in powershell as well...but still getting the error
![Screenshot (17)](https://user-images.githubusercontent.com/62063357/79476315-7481d600-8026-11ea-8ea3-1e2636659184.png)
my cookbook and yml file
![Screenshot (15)](https://user-images.githubusercontent.com/62063357/79476445-9da26680-8026-11ea-97a6-0825e0050552.png)
![Screenshot (16)](https://user-images.githubusercontent.com/62063357/79476471-a85cfb80-8026-11ea-8690-0c93fc046256.png)

**Comment by manasa373767** [comment]
my yaml file
---
driver:
  name: ec2
  aws-ssh-key-id: chef
  region: us-east-1
  availability-zone: us-est-1a
  subnet_id: subnet-2417fe05
  instance_type: t2.micro
  image_id: 'ami-07ebfd5b3428b6f4d'
  security_group_ids: ["sg-6cc66141"]

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15

verifier:
  name: inspec

transport:
ssh_key: "./chef.pem" 
connection_timeout: 10
connection_retries: 2
username: "ubuntu"

platforms:
  - name: ubuntu-18.04
 # - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[kitchen2::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

**Comment by SandhyaKatigari** [comment]
Hii,
Paste the chef.pem file inside the  kitchen2 folder not in cookbooks folder.

**Comment by manasa373767** [comment]
hi mam
i tried in that way also but not resolved

**Comment by SandhyaKatigari** [comment]
> hi mam
> i tried in that way also but not resolved

Remove double quotes for ssh_key parameter and try once.

transport:
ssh_key: ./chef.pem
connection_timeout: 10
connection_retries: 2
username: "ubuntu"

**Comment by manasa373767** [comment]
still getting same mam..and i got issue while executing aws ec2 describe-vpcs and for executing subnet command also
![Screenshot (19)](https://user-images.githubusercontent.com/62063357/79480864-4f906180-802c-11ea-9fa4-a38e3415322c.png)
i also tried by reinstall my aws cli

**Comment by srmanikanta** [comment]
That is not the error just you did not specify the output format so 
re-execute the `aws configure` command 
leave the accesskey ,secret key,region as default and mention output format as `json`.

**Comment by SandhyaKatigari** [comment]
Hii

Have you used aws configure.
If not first try aws configure command and use credentials file for
accessory and secret key.

Better to use aws cli commands in cms prompt or git bash.

**Comment by SandhyaKatigari** [comment]
Hii
I thinks the availability zone is us-east-1a.
In the uploaded file a missed,check once.

availability-zone: us-est-1a

**Comment by manasa373767** [comment]
![Screenshot (22)_LI](https://user-images.githubusercontent.com/62063357/79529592-acbb0000-808a-11ea-8e01-e17928f71483.jpg)

**Comment by SandhyaKatigari** [comment]
Give default region name as us-east-1a and try

**Comment by manasa373767** [comment]
thank you
