### ISSUE TITLE
war file is not running on node,apart from everything is fine.(java,tomcat).

### ISSUE THREAD

**Issue by pravin-07** [QT-DevOps/DevOpsIssues#81]
---  
- hosts: all 
  become: yes 
  roles: 
  - geerlingguy.java 
  - idealista.tomcat-role   
  tasks: 
  - name: copy war 
    copy: 
      src: /home/ansible/warzone/jenkins.war
      dest: /opt/tomcat/webapps/jenkins.war 
  notify: 
  - restart tomcat 
  handlers: 
  - name : restart tomcat 
  service:
    name:tomcat 
    state:restarted 
    enabled:yes

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [172.31.88.137]

TASK [geerlingguy.java : Include OS-specific variables.] ***********************
skipping: [172.31.88.137]

TASK [geerlingguy.java : Include OS-specific variables for Fedora.] ************
skipping: [172.31.88.137]

TASK [geerlingguy.java : Include version-specific variables for Debian.] *******
ok: [172.31.88.137]

TASK [geerlingguy.java : Define java_packages.] ********************************
ok: [172.31.88.137]

TASK [geerlingguy.java : include_tasks] ****************************************
skipping: [172.31.88.137]

TASK [geerlingguy.java : include_tasks] ****************************************
included: /home/ansible/.ansible/roles/geerlingguy.java/tasks/setup-Debian.yml f                                          or 172.31.88.137

TASK [geerlingguy.java : Ensure Java is installed.] ****************************
ok: [172.31.88.137] => (item=[u'openjdk-8-jdk'])

TASK [geerlingguy.java : include_tasks] ****************************************
skipping: [172.31.88.137]

TASK [geerlingguy.java : Set JAVA_HOME if configured.] *************************
skipping: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat | Ensure tomcat group] ********************
ok: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat | Ensure tomcat user] *********************
ok: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat | Create logs path] ***********************
skipping: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat | Create install path] ********************
ok: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat | Check Tomcat version] *******************
ok: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat | Download & Extract Tomcat] **************
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using
`result|failed` use `result is failed`. This feature will be removed in version
 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
skipping: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat | Copy Daemon script] *********************
ok: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat | Configuring service] ********************
ok: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat | Delete pre-installed folders in webapps]                                           ***
skipping: [172.31.88.137] => (item={'value': {u'deployed': True}, 'key': u'host-                                          manager'})
skipping: [172.31.88.137] => (item={'value': {u'deployed': True}, 'key': u'docs'                                          })
skipping: [172.31.88.137] => (item={'value': {u'deployed': True}, 'key': u'manag                                          er'})
skipping: [172.31.88.137] => (item={'value': {u'deployed': True}, 'key': u'ROOT'                                          })
skipping: [172.31.88.137] => (item={'value': {u'deployed': True}, 'key': u'examp                                          les'})

TASK [idealista.tomcat-role : Tomcat | Copy tomcat config] *********************
ok: [172.31.88.137] => (item={u'dest': u'/opt/tomcat/conf/tomcat-users.xml', u's                                          rc': u'tomcat-users.xml.j2'})
ok: [172.31.88.137] => (item={u'dest': u'/opt/tomcat/conf/server.xml', u'src': u                                          'server.xml.j2'})
ok: [172.31.88.137] => (item={u'dest': u'/opt/tomcat/bin/setenv.sh', u'src': u's                                          etenv.sh.j2'})
ok: [172.31.88.137] => (item={u'dest': u'/opt/tomcat/conf/logging.properties', u                                          'src': u'logging.properties.j2'})

TASK [idealista.tomcat-role : Tomcat | Ensure extra tomcat config file and templ                                          ate paths exists] ***

TASK [idealista.tomcat-role : Tomcat | Copy extra tomcat config files (provided                                           by playbooks)] ***

TASK [idealista.tomcat-role : Tomcat | Copy extra tomcat config templates (provi                                          ded by playbooks)] ***

TASK [idealista.tomcat-role : Tomcat agent installation | Install required packa                                          ges] ***
skipping: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat agent installation | Ensure install path] *                                          **
skipping: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat agent installation | Check if agent is inst                                          alled] ***
skipping: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat agent installation | Download agent] ******
skipping: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat agent installation | Unarchive package] ***
skipping: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat agent installation | Check configuration fi                                          les] ***
skipping: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat agent installation | Configure the Java age                                          nt] ***
skipping: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat agent installation | Check catalina options                                          ] ***
skipping: [172.31.88.137]

TASK [idealista.tomcat-role : Tomcat agent installation | Configure catalina opt                                          ions] ***
skipping: [172.31.88.137] => (item={u'dest': u'/opt/tomcat/bin/setagentenv.sh',                                           u'src': u'setagentenv.sh.j2'})

TASK [idealista.tomcat-role : Tomcat | Install download war from maven require p                                          ackage] ***
skipping: [172.31.88.137] => (item=[])

TASK [idealista.tomcat-role : Tomcat | Download wars from maven] ***************
skipping: [172.31.88.137] => (item={u'repository_url': u'http://amavenrepository                                          /any', u'group_id': u'sample', u'name': u'ROOT.war', u'extension': u'war', u'art                                          ifact_id': u'any'})

TASK [idealista.tomcat-role : Tomcat | Change maven downloaded war owner] ******
skipping: [172.31.88.137] => (item={u'repository_url': u'http://amavenrepository                                          /any', u'group_id': u'sample', u'name': u'ROOT.war', u'extension': u'war', u'art                                          ifact_id': u'any'})

TASK [idealista.tomcat-role : Tomcat | Download wars on webapps] ***************
ok: [172.31.88.137] => (item={u'url': u'https://tomcat.apache.org/tomcat-8.5-doc                                          /appdev/sample/sample.war', u'name': u'sample.war'})

TASK [idealista.tomcat-role : Tomcat | Copy local wars to webapps] *************
skipping: [172.31.88.137] => (item=/home/ansible/Roletask/AnsibleZone/ClassRoomE                                          xamples/July2018/JavaDeployment/sample.war)

PLAY RECAP *********************************************************************
172.31.88.137              : ok=13   changed=0    unreachable=0    failed=0

**Comment by pganapathirao** [comment]
War file should be copy in same path.

**Comment by pravin-07** [comment]
yes its present on current Dir. &  java and  tomcat successfully running on node.their is some syntax problem?

**Comment by sanjaysureshmv** [comment]
check the permission of jenkins.war file. the owner should be tomcat. You can give the owner as follows in the playbook,

name: copy war
copy:
  src: /home/ansible/warzone/jenkins.war
  dest: /opt/tomcat/webapps/jenkins.war
  owner: tomcat

**Comment by shaikkhajaibrahim** [comment]
Closing this issue
