### ISSUE TITLE
Unable to knowing the mistake where I did in the below ansible code.

### ISSUE THREAD

**Issue by vijayamadiri** [QT-DevOps/DevOpsIssues#810]
![image](https://user-images.githubusercontent.com/62703091/79533099-b8132900-8094-11ea-86df-f975bd01a3a2.png)

I'am getting the below error.
![image](https://user-images.githubusercontent.com/62703091/79533366-48516e00-8095-11ea-993c-a680293a7052.png)

**Comment by SandhyaKatigari** [comment]
Hii,

In the above playbook, ansible_distribution is Ubuntu where U in capital letter.

![image](https://user-images.githubusercontent.com/63640375/79541175-f7e30c00-80a6-11ea-8e71-f2d21710cc69.png)

**Comment by NareshAbbanapuri** [comment]
hi vijay
in ubuntu U should be capital 
Ubuntu
Please close issue

**Comment by vijayamadiri** [comment]
Ohh Sorry. i have checked for first issue which was raised. But i didn't cross check this code with first issue. Any way thanks for your reply.
