### ISSUE TITLE
Kitchen convergence execution in chef

### ISSUE THREAD

**Issue by vamsihub** [QT-DevOps/DevOpsIssues#812]
![chef](https://user-images.githubusercontent.com/44359643/79570210-a81c3900-80d6-11ea-9a4e-45d68e3f8115.PNG)
I am getting following error while executing kitchen convergence,

![image](https://user-images.githubusercontent.com/44359643/79569679-adc54f00-80d5-11ea-9a1f-92d08df0944b.png)

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-1804>.  Please see .kitchen/logs/default-ubuntu-1804.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

I have tried with few steps where you have given in closed issues but no lock, please help me as soon as possible.

My kitchen.yml file

---
driver:
  name: ec2
  aws_ssh_key_id: chef_client2
  region: ap-south-1
  availability_zone: ap-south-1a
  subnet_id: subnet-54d0e13c
  instance_type: t2.micro
  image_id: 'ami-0620d12a9cf777c87'
  security_group_ids: ["sg-01a3ac361a90adb78"]

## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15

verifier:
  name: inspec

transport:
  ssh_key: ./chef_client2.pem
  connection timeout: 10
  connection retries: 5
  username: ubuntu

platforms:
  - name: ubuntu-18.04
  # - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[kitchencooker::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

![convergence](https://user-images.githubusercontent.com/44359643/79570023-54a9eb00-80d6-11ea-8bd7-475d638bc582.PNG)

Please help to resolve this issue

**Comment by SandhyaKatigari** [comment]
Hii,

In the kitchen.yml file you missed _ symbol under transport section.

use connection_timeout and connection_retries

**Comment by vamsihub** [comment]
I changed it but error is same, 
actually error is showing    "Converge failed on instance <default-ubuntu-1804" as shown in pic, unable to get.

**Comment by vamsihub** [comment]
But thank you for responding

**Comment by SandhyaKatigari** [comment]
Share your default.rb file here

**Comment by vamsihub** [comment]
#
# Cookbook:: kitchencooker
# Recipe:: default
#
# Copyright:: 2020, The Authors, All Rights Reserved.


file '/tmp/read.txt' do
    content 'Amazon great sale'
    action : create
end

**Comment by rpkoya** [comment]
Hi,

issue with your kitchen file alignment, the alignment should look like below 
![kitchen-alignment1](https://user-images.githubusercontent.com/63572053/79630792-077b5700-8172-11ea-8428-31ee06358967.png)
![kitchen-alignment2](https://user-images.githubusercontent.com/63572053/79630795-0e09ce80-8172-11ea-94fd-c00f0987695c.png)

Please align your content as above and check.

**Comment by srmanikanta** [comment]
if you resolve the issue please close the issue or update the issue

**Comment by vamsihub** [comment]
No its not working

**Comment by samineni1927** [comment]
![converge error](https://user-images.githubusercontent.com/60940441/79642627-5f3eb000-81bc-11ea-9b44-8289b3f69e0d.PNG)


can you please share the screenshot like above @vamsihub

**Comment by vamsihub** [comment]
i will share tomorrow, thanku for the help
