### ISSUE TITLE
Keypair does not exist.

### ISSUE THREAD

**Issue by surendramannem** [QT-DevOps/DevOpsIssues#813]
<img width="620" alt="Keypair" src="https://user-images.githubusercontent.com/54304137/79607097-4d073800-8110-11ea-8df0-9fe990e148cd.PNG">

.yml

===============
---
driver:
   name: ec2
   aws_ssh_key_id: kitchen # key pair name 
   region: us-west-2 # region code of aws
   availability_zone: us-west-2b # availability_zone of us-west
   subnet_id: subnet-69716922 # subnet-id noted from above steps
   instance_type: t2.micro # as it is free instance type
   image_id: ami-0d1cd67c26f5fca19 # image id of ubuntu
   security_group_ids: ["sg-8e4a56d1"]   
## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15

verifier:
  name: inspec

transport:
  ssh_key: "~/.ssh/kitchen.pem"
  connection_timeout: 10
  connection_retries: 3
  username: ubuntu

platforms:
  - name: ubuntu-18.04
  #- name: centos-7

suites:
  - name: default
    run_list:
      - recipe[testkitchen::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
================

<img width="441" alt="cookbook-testkitchen" src="https://user-images.githubusercontent.com/54304137/79607246-8dff4c80-8110-11ea-83c4-c156e6cebd17.PNG">

**Comment by SandhyaKatigari** [comment]
Hi,

Use ssh key as below and tray once
ssh_key: ./kitchen.pem

**Comment by rpkoya** [comment]
Hi,
Issue with your kitchen.yml file, send your kitchen.yml file to check.

**Comment by srmanikanta** [comment]
check the pemfile path in kitchen.yml. and do not pass the .pem extension in key pair id parameter.

**Comment by surendramannem** [comment]
Kitchen.yml file: I tired both, it didn't work for me.. 

Just to mention:  vpc id showing the aws portal and what i get using the command "aws ec2 describe-vpcs" is different. 

I took the  data what it shows in cmd line, "subnet, vpc & Security group". 
===================
---
driver:
   name: ec2
   aws_ssh_key_id: kitchen # key pair name 
   region: us-west-2 # region code of aws
   availability_zone: us-west-2b # availability_zone of us-west
   subnet_id: subnet-69716922 # subnet-id noted from above steps
   instance_type: t2.micro # as it is free instance type
   image_id: ami-0d1cd67c26f5fca19 # image id of ubuntu
   security_group_ids: ["sg-8e4a56d1"]   
## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15

verifier:
  name: inspec

transport:
  ssh_key: "/kitchen.pem"
  connection_timeout: 10
  connection_retries: 3
  username: ubuntu


platforms:
  - name: ubuntu-18.04
  #- name: centos-7

suites:
  - name: default
    run_list:
      - recipe[testkitchen::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
====================

**Comment by shaikkhajaibrahim** [comment]
Please change the driver to ec2

**Comment by shaikkhajaibrahim** [comment]
Please relook at https://directdevops.blog/2019/04/02/test-kitchen-setup-with-aws/

**Comment by surendramannem** [comment]
Hello Team,

Thank you for the replies, the above mentioned issue got resolved, I'm looking at "east-us" region in AWS portal. later changed to "west us 2", now vpc, subnet $ SG are matched and successfully executed for ubuntu.. installed tomcat also but only for ubuntu.. 

When  i tried to do for centos. got the below error, look like image problem "ami for centos". 

![image](https://user-images.githubusercontent.com/54304137/79713110-6532af00-82ea-11ea-8fa6-e1fe638c10b3.png)

Can anyone help me with this.. Thank you..

**Comment by srmanikanta** [comment]
try to launch manually for centos ami once and copy that ami and use in your kitchen.yml

**Comment by surendramannem** [comment]
Hi Manikanta,

Thank you for the update, 

I tired to do the same, but didn't work out both have same  "ami-0bc06212a56393ee1"

**Comment by shaikkhajaibrahim** [comment]
@srmanikanta Try to take remote connection and look into issue

**Comment by rpkoya** [comment]
HI surendramannem,

Try the below command to get AMI Image of centos for your current region and try to use that ami to install.

aws ec2 describe-images --owners 'aws-marketplace' --filters 'Name=product-code,Values=aw0evgkw8e5c1q413zgy5pjce' --query 'sort_by(Images, &CreationDate)[-1].[ImageId]' --output 'text'

**Comment by surendramannem** [comment]
Sure , will try that. Thank you for the help.

Regards,
Surendra Mannem.
