### ISSUE TITLE
Error While Creating a cookbook

### ISSUE THREAD

**Issue by abhi-devops02** [QT-DevOps/DevOpsIssues#814]
While creating a cookbook, I am getting this following issue.

G:Devops\cookbooks> chef generate cookbook -b testkitchen
Generating cookbook testkitchen
- Ensuring correct cookbook content
- Committing cookbook files to git

================================================================================
Error executing action `run` on resource 'execute[git-commit-new-files]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '128'
---- Begin output of git commit -m "Add generated cookbook content" ----
STDOUT:
STDERR: *** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'kabhi@DESKTOP-UGPIEOD.(none)')
---- End output of git commit -m "Add generated cookbook content" ----
Ran git commit -m "Add generated cookbook content" returned 128

Resource Declaration:
---------------------
# In C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-dk-4.7.113/lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb

160:     execute('git-commit-new-files') do
161:       command('git commit -m "Add generated cookbook content"')
162:       cwd cookbook_dir
163:     end
164:   end

Compiled Resource:
------------------
# Declared in C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-dk-4.7.113/lib/chef-dk/skeletons/code_generator/recipes/cookbook.rb:160:in `from_file'

execute("git-commit-new-files") do
  action [:run]
  default_guard_interpreter :execute
  command "git commit -m \"Add generated cookbook content\""
  backup 5
  declared_type :execute
  cookbook_name :code_generator
  recipe_name "cookbook"
  cwd "F:/Dev/QT/Keypairs/chef-repo/cookbooks/testkitchen"
  domain nil
  user nil
end

Missing Windows Admin Privileges
--------------------------------
chef-client doesn't have administrator privileges. This can be a possible reason for the resource failure.

System Info:
------------
chef_version=15.8.23
ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]
program_name=C:/opscode/chefdk/bin/chef
executable=C:/opscode/chefdk/bin/chef

ERROR: Chef Infra failed to converge: execute[git-commit-new-files] (code_generator::cookbook line 160) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '128'
---- Begin output of git commit -m "Add generated cookbook content" ----
STDOUT:
STDERR: *** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'kabhi@DESKTOP-UGPIEOD.(none)')
---- End output of git commit -m "Add generated cookbook content" ----
Ran git commit -m "Add generated cookbook content" returned 128 from file C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/mixlib-shellout-3.0.9-universal-mingw32/lib/mixlib/shellout.rb:300:in `invalid!'
Caused by: (Mixlib::ShellOut::ShellCommandFailed) execute[git-commit-new-files] (code_generator::cookbook line 160) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '128'
---- Begin output of git commit -m "Add generated cookbook content" ----
STDOUT:
STDERR: *** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'kabhi@DESKTOP-UGPIEOD.(none)')
---- End output of git commit -m "Add generated cookbook content" ----
Ran git commit -m "Add generated cookbook content" returned 128

**Comment by SandhyaKatigari** [comment]
Hii, 
Even it is throwing error sometimes cookbook folder is generating.
Check ls command once.

**Comment by abhi-devops02** [comment]
It was working fine yesterday. But today i was getting this error
command is correct. 

I was trying to create from powershell.

**Comment by rpkoya** [comment]
Hi,

I also got this error when i installed chefdk on another system, to fix this you need to give details in the below command..

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

Please provide your email ID and Name on the above command, those details should match with the account you created in manage.chef.io

**Comment by abhi-devops02** [comment]
> Hi,
> 
> I also got this error when i installed chefdk on another system, to fix this you need to give details in the below command..
> 
> git config --global user.email "[you@example.com](mailto:you@example.com)"
> git config --global user.name "Your Name"
> 
> Please provide your email ID and Name on the above command, those details should match with the account you created in manage.chef.io

problem resolved. 
it works fine after passing the details as u mentioned.
Thanks for suggestion
