### ISSUE TITLE
chef kitchen create issue

### ISSUE THREAD

**Issue by sandhyapalli** [QT-DevOps/DevOpsIssues#815]
I
[kitchen.txt](https://github.com/QT-DevOps/DevOpsIssues/files/4497332/kitchen.txt)

 am getting like below while running command "kitchen create" and not creating any EC2 instance

![image](https://user-images.githubusercontent.com/51368872/79652865-6f13bf80-81cf-11ea-855e-8021c3da1323.png)

please find attachment "kitchen.txt" for   my kitchen.yaml file

![image](https://user-images.githubusercontent.com/51368872/79657845-e0a03d80-81d0-11ea-905c-c50cafa0527e.png)

Please look into the issue ASAP

**Comment by rpkoya** [comment]
please send your kitchen.yml file.

**Comment by NareshAbbanapuri** [comment]
please run kitchen destroy and again run kitchen create
