### ISSUE TITLE
Error while using Kitchen Create

### ISSUE THREAD

**Issue by DivyasreeYanala** [QT-DevOps/DevOpsIssues#816]
<img width="311" alt="kitchen driver" src="https://user-images.githubusercontent.com/63571979/79673803-edaa3600-81aa-11ea-932b-57591d268941.PNG">
<img width="739" alt="kitchen error" src="https://user-images.githubusercontent.com/63571979/79673804-f1d65380-81aa-11ea-8e66-d2e80311877a.PNG">
<img width="275" alt="Kithen transport" src="https://user-images.githubusercontent.com/63571979/79673806-f569da80-81aa-11ea-8c21-d0a1e7325472.PNG">
Getting error with aws, please help me to solve this.

**Comment by ashok655** [comment]
Having the same error.Hope someone will respond with a solution

**Comment by rpkoya** [comment]
Please paste the transporter below verifier and check, for your reference i am pasting my yml file please check below.
![kitchen-alignment2](https://user-images.githubusercontent.com/63572053/79676801-545d3d00-8207-11ea-8efa-15799ea5a3b4.png)

**Comment by DivyasreeYanala** [comment]
After changing the transporter also,still the same error is showing

**Comment by shaikkhajaibrahim** [comment]
you need to install aws cli and configure the user, 
![image](https://user-images.githubusercontent.com/2438317/79680140-fee65780-8229-11ea-9a82-c97dd3df842e.png)


 Please read the complete documentation at https://directdevops.blog/2019/04/02/test-kitchen-setup-with-aws/

**Comment by ashok655** [comment]
@DivyasreeYanala - Resloved this error by edit ENV varilable.Kitchen.yml read access id and access key from ENV varialbles.My ENV details showing previous configuration so i have edited with new details and restarted git bash.it is working for me now and can see instance created in aws account.let me know how you getting on with this.

![image](https://user-images.githubusercontent.com/43445964/79684416-22f56900-8229-11ea-9b7b-254a930edef8.png)

**Comment by DivyasreeYanala** [comment]
Solved the issue, Thank you
