### ISSUE TITLE
Issue running aws commands

### ISSUE THREAD

**Issue by sharmatanmaya** [QT-DevOps/DevOpsIssues#817]
I have aws cli installed in my machine. when i am trying to run aws command i am getting error
aws ec2 describe-vpcs
An error occurred (AuthFailure) when calling the DescribeVpcs operation: AWS was not able to validate the provided access credentials

its happening with other commands as well like 
aws ec2 describe-images

**Comment by shaikkhajaibrahim** [comment]
Please create the IAM User have access key and secret key then execute 
aws configure and enter  the details as mentioned 
![image](https://user-images.githubusercontent.com/2438317/79680067-36a0cf80-8229-11ea-9f86-38df646adbe8.png)

Please read the complete document
