### ISSUE TITLE
curl: (7) Failed to connect to localhost port 8080: Connection refused

### ISSUE THREAD

**Issue by siva0139** [QT-DevOps/DevOpsIssues#82]
ubuntu@ip-172-31-82-241:~$ ./hello.js
Server running at http://localhost:8080/
ubuntu@ip-172-31-82-241:~$ curl http://localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused

**Comment by shaikkhajaibrahim** [comment]
Did you changed the localhost in your hello.js to private ip address of the machine?
________________________________
