### ISSUE TITLE
kitchen issue

### ISSUE THREAD

**Issue by shafiqshaik** [QT-DevOps/DevOpsIssues#821]
![image](https://user-images.githubusercontent.com/63976896/79697966-a345b980-827d-11ea-9624-5584fd9d666e.png)
kitchen issue while i am converging the ubuntu machine I am getting the connection time out I have given a correct image_id as well

this is my yaml fie

---
driver:
  name: ec2
  aws_ssh_key_id: chef
  region: us-east-2 # region code of aws
  availability_zone: us-east-2a # availability_zone of us-west
  subnet_id: ********** # subnet-id noted from above steps
  instance_type: t2.micro # as it is free instance type
  image_id: 'ami-01e36b7901e884a10' # image id of centos
  security_group_ids: ["************"]

## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

transport:
    ssh_key: ./chef.pem # relative path to pem file
    connection_timeout: 10
    connection_retries: 5
    username: centos # username from ami-id
  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver:
      image_id: 'ami-0fc20dd1da406780b'
    transport:
      username: ubuntu    
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[tomcat::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

**Comment by SandhyaKatigari** [comment]
Paste transport content below verifier field and check.

**Comment by srmanikanta** [comment]
please verify the ami is it  ubuntu or centos?
if that is ubuntu ami write the kitchen.yml file only for ubuntu 
or is centos ami write  the kitchen.yml file only for centos 
please comment unrelated stuff.(like platform ,user)
mention pemfile path correctly.
if you resolved this please close the issue or else update the issue. and share your kitchen.yml file completely.

**Comment by NareshAbbanapuri** [comment]
hi
please try to attach  kitchen.yml file

**Comment by shafiqshaik** [comment]
thank you I am able to resolve it
