### ISSUE TITLE
issue with list of all ec2 instances in us-west-2

### ISSUE THREAD

**Issue by Teja1213** [QT-DevOps/DevOpsIssues#822]
![Capture](https://user-images.githubusercontent.com/26798087/79700984-7edee280-8267-11ea-846d-936255673034.PNG)

**Comment by SandhyaKatigari** [comment]
Give the default region name as us-west-2 and don't share your access and secret keys

**Comment by NareshAbbanapuri** [comment]
hi Teja
the output format is json 
please check once
note: don't share your access and secret key

**Comment by srmanikanta** [comment]
please mention a valid output format 
aws outpur format supported the following

1.json – The output is formatted as a JSON string.

2.yaml – The output is formatted as a YAML string. (Available in the AWS CLI version 2 only.)

3.text – The output is formatted as multiple lines of tab-separated string values. This can be useful to pass the output to a text processor, like grep, sed, or awk.

4..table – The output is formatted as a table using the characters +|- to form the cell borders. It typically presents the information in a "human-friendly" format that is much easier to read than the others, but not as programmatically useful.

choose which one you want don't mention other than this.

**Comment by yagnasivasai** [comment]
> please mention a valid output format
> aws outpur format supported the following
> 
> 1.json – The output is formatted as a JSON string.
> 
> 2.yaml – The output is formatted as a YAML string. (Available in the AWS CLI version 2 only.)
> 
> 3.text – The output is formatted as multiple lines of tab-separated string values. This can be useful to pass the output to a text processor, like grep, sed, or awk.
> 
> 4..table – The output is formatted as a table using the characters +|- to form the cell borders. It typically presents the information in a "human-friendly" format that is much easier to read than the others, but not as programmatically useful.
> 
> choose which one you want don't mention other than this.

Hi
Do you know how to submit challenges? Via Github and Via Slack

**Comment by shaikkhajaibrahim** [comment]
@Teja1213  Not a good idea to share your secret keys and access keys, if they are still active I would recommend removing the iam user 
and your output-format is wrong as @srmanikanta  mentioned
