### ISSUE TITLE
Docker image build Issue..Cloud any help to me?

### ISSUE THREAD

**Issue by prasadsai528** [QT-DevOps/DevOpsIssues#823]
![Dcoker image build issue](https://user-images.githubusercontent.com/55782151/79739216-8233a600-831b-11ea-99d5-61b974f2997e.PNG)

**Comment by srmanikanta** [comment]
please post your dockerfile here.

**Comment by NareshAbbanapuri** [comment]
hi sai
please share Dockerfile

**Comment by prasadsai528** [comment]
> please post your dockerfile here.

![Dockefile](https://user-images.githubusercontent.com/55782151/79832423-07c06000-83c7-11ea-867f-3f21b2656dd3.PNG)

**Comment by srmanikanta** [comment]
in above scenario no need to take two images 
if you really take follow this on  second image(from openjdk:8) you have to use workdir instrction 
use a valid path in cmd.
update the issue accordingly.

**Comment by NareshAbbanapuri** [comment]
yes here no need two base images
and you can use RUN or ADD instructions
ADD src dest
eg:
-----
 ADD url .
------

**Comment by shaikkhajaibrahim** [comment]
@prasadsai528  what is that you are trying to do in the Dockerfile as it is not making any sense,
We use multi stage builds to optimize the images.

As naresh suggested for what you have written 

![image](https://user-images.githubusercontent.com/2438317/79944961-74506300-848a-11ea-9bb1-dcf3eb340b73.png)

This is more than enough
