### ISSUE TITLE
unable to execute resources in chef  convergence

### ISSUE THREAD

**Issue by manasa373767** [QT-DevOps/DevOpsIssues#824]
getting  0 resources while doing convergence..
![2](https://user-images.githubusercontent.com/62063357/79761321-e2880f00-833e-11ea-9a94-4a700e03f5af.png)
**My Cookbook**
#
# Cookbook:: .
# Recipe:: install
#
# Copyright:: 2020, The Authors, All Rights Reserved.

package_name = node['apache']['package_name']  

service_resource_name = 'service[apache]'

package node['apache']['package_name'] do
    action :install
    notifies :enable, 'service[apache]'
end
 
service 'apache' do
    service_name node['apache']['package_name']
    action :nothing
end

packages =  node['apache']['php_packages'] 

packages.each do |package_now|
    package package_now do
    action :install
    notifies :restart, 'service[apache]'
end 
end      
**My  attribute**
if node['platform_family'] == 'debian'
    default['apache']['package_name'] = 'apache2'
    default['apache']['php_packages'] = ['php','libapache2-mod-php','php-mysql','php-cli']    

elsif node['platform_family'] == 'rhel'
    default['apache'][ 'package_name'] = 'httpd'
    default['apache'][ 'php_packages'] = ['php','php-mysql','php-fpm']     
end

**Comment by SandhyaKatigari** [comment]
Hii,

remove below line in cookbook and try once.

service_resource_name = 'service[apache]'

**Comment by manasa373767** [comment]
hi
still getting  as same

**Comment by srmanikanta** [comment]
please check your cookbook is uploaded to chef server or not if uploaded edit the run_list of your node(please cross check once).
