### ISSUE TITLE
undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by samineni1927** [QT-DevOps/DevOpsIssues#825]
while convergence following error occurred

undefined method **`each'** for nil:NilClass

![converge error](https://user-images.githubusercontent.com/60940441/79856441-fc326080-83e9-11ea-979a-8b57d3ddf09b.PNG)

**attribute file as below**
if node['platform_family'] == 'debian'
    default['chefapache']['package_name'] = 'apache2'
    default['apache']['php_packages'] = ['php', 'libapache2-mod-php', 'php-mysql', 'php-cli']
    
elsif node['platform_family'] == 'rhel'
    default['chefapache']['package_name'] = 'httpd'
    default['chefapache']['php_packages'] = ['php','php-mysql', 'php-fpm']
end

**recipe file as below**
# Cookbook:: .
# Recipe:: apacheinstall
#
# Copyright:: 2020, The Authors, All Rights Reserved.

# using the attribute defined in the attributes/default.rb file

package_name = node['chefapache']['package_name']

package node['chefapache']['package_name'] do
    action :install
    notifies :enable, 'service[apache]'
end

service 'apache' do
    service_name node['chefapache']['package_name']
    action :nothing
end

packages = node['chefapache']['php_packages']

packages.each do |package_now|
    package package_now do
        action :install
        notifies :restart, 'service[apache]'
    end
end

**Comment by srmanikanta** [comment]
I think this is the error 
`default['apache']['php_packages'] = ['php', 'libapache2-mod-php', 'php-mysql', 'php-cli']`
The above line is there in your attribute file
so change this file to
`default['chefapache']['php_packages'] = ['php', 'libapache2-mod-php', 'php-mysql', 'php-cli']`
change this and try

**Comment by samineni1927** [comment]
Thanks @srmanikanta
