### ISSUE TITLE
 Syntax Error

### ISSUE THREAD

**Issue by DivyasreeYanala** [QT-DevOps/DevOpsIssues#826]
<img width="438" alt="1" src="https://user-images.githubusercontent.com/63571979/79801916-02aed280-832d-11ea-8126-80558d7de757.PNG">

**Comment by srmanikanta** [comment]
please the install.rb file line number 8
that is the mistake.for reference 
```
package_name = node['apache']['package_name']

package node['apache']['package_name'] do
    action :install
    notifies :enable, 'service[apache]'
end
```
please cross check once.
