### ISSUE TITLE
Kitchen creation issue 

### ISSUE THREAD

**Issue by AddulAleem** [QT-DevOps/DevOpsIssues#830]
Hi All,

I have made couple of attempt to create a kitchen with deep scrutiny but plenty of attempt with no luck the final error before about to success i have got below error msg, can anyone please spare few minutes to identify my error ..

I am attaching log file and kitchen.yml here 

![image](https://user-images.githubusercontent.com/63742242/79885294-42041e80-8414-11ea-9305-919e8bc6b4c5.png)

D:\Practicechef\chef-starter\chef-repo\cookbooks\newkitchen\.kitchen

 
[newkitchen.zip](https://github.com/QT-DevOps/DevOpsIssues/files/4511022/newkitchen.zip)

Thanks in advance for your time guys

**Comment by AddulAleem** [comment]
if you expand .kitchen folder you will see the logs ...
please help

**Comment by AddulAleem** [comment]
logs have been copied to note pad although there is zip file in attached i.e. newkitchen.zip /// but herewith i am attaching the log zip file here again in txt format 
[Kitchen logs.zip](https://github.com/QT-DevOps/DevOpsIssues/files/4513414/Kitchen.logs.zip)

**Comment by srmanikanta** [comment]
you are raised two issues related to one error so please close anyone .
I answered 829 issue. if you resolve close both issues if not update the issue number 829.

**Comment by shaikkhajaibrahim** [comment]
duplicate #829
