### ISSUE TITLE
error while trying to execute java command in playbook

### ISSUE THREAD

**Issue by vinodmaddela** [QT-DevOps/DevOpsIssues#831]
I am able to install and download the springpetclinic.jar to my node using playbook but the screen goes idle while trying to run the command "java -jar spc.jar" in the playbook.

---
- hosts: all
  become: yes
  tasks:
    - name: Install OpenJDK Java
      apt:
        name: ['openjdk-8-jdk']
        state: present

    - name: download spring pet clinic jar
      get_url:
        url: https://2020absoftsol.s3.amazonaws.com/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar
        dest: /home/ansible/
<img width="947" alt="Annotation 2020-04-22 001708" src="https://user-images.githubusercontent.com/38660202/79924010-b2b83480-842e-11ea-9dc5-8a70ad42ee0b.png">

    - name: Run command 
      command: java -jar spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar

**Comment by srmanikanta** [comment]
try to run your task like this
```
- name: Run command 
  command: nohup java -jar spring-petclinic-2.2.0.BUILD-SNAPSHOT.ja &
```

**Comment by shaikkhajaibrahim** [comment]
Why dont you create spring petclinic as a service 
https://docs.spring.io/spring-boot/docs/current/reference/html/deployment.html
or as @srmanikanta  mentioned
