### ISSUE TITLE
not able to see the apache info page

### ISSUE THREAD

**Issue by shafiqshaik** [QT-DevOps/DevOpsIssues#832]
when I run publicipdreess/info.php i am   not able to see the apache info page
everything is working fine when I do SUDO CHEF-CLIENT added the screenshot for reference

![image](https://user-images.githubusercontent.com/63976896/79934019-7219e480-8449-11ea-85ab-6d1c841678fb.png)

this is my recipe
apt_update 'updateubuntu' do
    ignore_failure true
    action :update
    only_if{ node['platform'] =='ubuntu' }
end

package_name = node['apache']['package_name']

package node['apache']['package_name'] do
    action :install
    notifies :enable, 'service[apache]'
end

service 'apache' do
    service_name node['apache']['package_name']
    action :nothing
end

packages = node['apache']['php_packages']

packages.each do |package_now|
    package package_now do
        action :install
        notifies :restart, 'service[apache]'
    end
end

cookbook_file '/var/www/html/info.php' do
    source 'info.php'
    action :create
    notifies :restart, 'service[apache]'
end

**Comment by srmanikanta** [comment]
hi shafiqshaik 
please follow this instructions
goto your node and check the httpd package is installed or not
if installed then check the status of the service like service httpd status
if servie httpd status is active(running) then check your security group is opened port 80 or not.
please verify the above things and update the issue.

**Comment by shaikkhajaibrahim** [comment]
Can you share the screen shot of you security group in ec2
@srmanikanta  take the remote session and help him out, he stays in UK to my knowledge so in IST noon post 3:00 PM should be comfortable

**Comment by srmanikanta** [comment]
call to lab assistance number.

**Comment by shafiqshaik** [comment]
![image](https://user-images.githubusercontent.com/63976896/80281503-7bce7100-8703-11ea-8e0e-a5dd73f1668e.png)

**Comment by srmanikanta** [comment]
I am manikanta please call to me whenever you are available on india time.
