### ISSUE TITLE
Unable to install chef server manage

### ISSUE THREAD

**Issue by rpkoya** [QT-DevOps/DevOpsIssues#833]
Hi,
I installed chef standalon server in ubuntu and trying to configure,
during "sudo chef-manage-ctl reconfigure" 
i am unable to Acccept License, its not giving me to type "yes" can anyone help on this.
attaching screenshots for your reference 
![chef-manage-0](https://user-images.githubusercontent.com/63572053/80048734-a3201500-852e-11ea-9bd9-750a9fe6fe78.png)
![chef-manage-1](https://user-images.githubusercontent.com/63572053/80048736-a4514200-852e-11ea-9074-0bc7507eb78a.png)
![chef-manage-2](https://user-images.githubusercontent.com/63572053/80048737-a4e9d880-852e-11ea-8bc5-83b16615a914.png)

**Comment by srmanikanta** [comment]
please [click here](https://github.com/srmanikanta/Chef-Repo/blob/master/chef_installation.md) for reference.

**Comment by rpkoya** [comment]
Thanks for the document Manikanta, 
I have installed Chef Server and also done bootstrap on a vmware machine,
I want to know how to setup kitchen on vcenter,  i tried the setup but when i run kitchen list command it was showing Dummy in the driver field..
If there is any document on this can you please share me.

Regards,
Ravindra

**Comment by srmanikanta** [comment]
please follow this reference file [click here](https://github.com/srmanikanta/kitchen-vcenter).

**Comment by rpkoya** [comment]
hi,

i followed the above document, when i did kitchen list, i am getting driver as Dummy instead of vcenter, if you have any sample kitchen.yml file can you please send me for reference.

**Comment by srmanikanta** [comment]
please post the logs. and error screenshot.
