### ISSUE TITLE
Debasis Pal: Java install using Chef Supermarket - berks install encounters error...

### ISSUE THREAD

**Issue by debasis-gif** [QT-DevOps/DevOpsIssues#837]
Hello, I am trying to install Java OpenJDK 11 via Chef supermarket - using **"java"** cookbook.
**metadata.rb** has the following :
**depends 'java', '~> 8.1.2'**

the following is the error msg:
![image](https://user-images.githubusercontent.com/60258623/80118280-cf2aad00-85a5-11ea-86de-694d23c05b48.png)

I have used other java installer from super market **"java_se"** but with same error output 

I am using the following versions of **Chefdk**:
![image](https://user-images.githubusercontent.com/60258623/80118873-9c34e900-85a6-11ea-9e6b-908672cd5ea6.png)

Please help resolve the issue

Thanks
Debasis

**Comment by debasis-gif** [comment]
Ok, this should be considered as CLOSED, as I had installed the windows installer version as follows and uninstalled the crossed one. Following this the issue has been resolved.

![image](https://user-images.githubusercontent.com/60258623/80125419-431d8300-85af-11ea-88cd-77898f37f039.png)

**Comment by srmanikanta** [comment]
please close the issue.

**Comment by debasis-gif** [comment]
Hi,
Sorry.
Have done it now - CLOSED the issue.
Thanks & Regards,
Debasis Pal7972930164 / 9836965177 

    On Friday, 24 April 2020, 08:19:22 GMT+5:30, srmanikanta <notifications@github.com> wrote:  
 
 


please close the issue.
