### ISSUE TITLE
Not able configure in aws cli while executing test kitchen

### ISSUE THREAD

**Issue by vishwendh105** [QT-DevOps/DevOpsIssues#839]
Not able configure in aws cli while executing test kitchen. After creating a user a entering a region in the aws cli it is asking about the default output format can you please help me in this.
[testkitc.zip](https://github.com/QT-DevOps/DevOpsIssues/files/4537978/testkitc.zip)
My cookbook and error messeage given above.

**Comment by srmanikanta** [comment]
mention default output format is `json`.

**Comment by srmanikanta** [comment]
close the issue if resolved.
