### ISSUE TITLE
chif install windows 10power shellbelow problem

### ISSUE THREAD

**Issue by Anil1205-a** [QT-DevOps/DevOpsIssues#841]
![image](https://user-images.githubusercontent.com/57809881/80557875-f8a86600-89f5-11ea-82e4-9e80caa52e3b.png)
 im install chef server created to chef url and also download kit key folder

**Comment by rpkoya** [comment]
Hi Anil, to work chef commands you should install ChefDK in your Workstation.
Please install chef DK from below URL and check.
https://downloads.chef.io/chefdk/

**Comment by srmanikanta** [comment]
please read the official chef documentation for bootstrap the windows node because you have to install chef client manually on windows node and enable so configuration.

**Comment by srmanikanta** [comment]
first in first open powershell as run as adminitrator and then install chef dk on your windows 10 
once you installed then close the powershell and reopen.
