### ISSUE TITLE
K8s package issue any help?

### ISSUE THREAD

**Issue by prasadsai528** [QT-DevOps/DevOpsIssues#843]
apt-get update && sudo apt-get install -y apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add 
vim /etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial 
![k8s issue installing ](https://user-images.githubusercontent.com/55782151/80570193-01aa2f00-8a18-11ea-9a46-8a5ffc9a8b2f.PNG)

**Comment by srmanikanta** [comment]
please read this document and try [Click Here](https://directdevops.blog/2019/10/12/kubernetes-classroom-series-12-oct-2019/)
