### ISSUE TITLE
changing Jenkins default port from 8080 to 80

### ISSUE THREAD

**Issue by sudhup** [QT-DevOps/DevOpsIssues#844]
Hi,
Can someone help me to change the default port of Jenkins from 8080 to 80.
I tried the following steps but couldn't load Jenkins from http://X.X.X.X:80
[Note: my firewall configuration is inactive and I set inbound rule to allow traffic from all]
$sudo vi /etc/default/jenkins
  changed HTTP_PORT=80
$sudo systemctl restart jenkins

![Untitled](https://user-images.githubusercontent.com/62091122/80577475-94e96180-8a24-11ea-9f2a-7eebbd0d9520.png)

**Comment by srmanikanta** [comment]
I already answer your question on phone call please close the issue.

**Comment by sudhup** [comment]
ok. Thanks
