### ISSUE TITLE
issue with git checkout master

### ISSUE THREAD

**Issue by Teja1213** [QT-DevOps/DevOpsIssues#845]
![image](https://user-images.githubusercontent.com/26798087/80623607-73827880-8a18-11ea-990e-cb69c03a16c3.png)
[](url)

**Comment by srmanikanta** [comment]
are you change or rename or delete  the name of a directory/file in your git repo?
if you done this please close the git bash and re-open again.

**Comment by Teja1213** [comment]
got it
