### ISSUE TITLE
When i am commiting my code to github i am getting an authentication failed fatal error.

### ISSUE THREAD

**Issue by vishwendh105** [QT-DevOps/DevOpsIssues#846]
![Git1](https://user-images.githubusercontent.com/51240081/80789313-474a3180-8ba9-11ea-894b-4e6bfa23d3ea.png)
![Git2](https://user-images.githubusercontent.com/51240081/80789357-5d57f200-8ba9-11ea-9630-4efacd8beb0e.png)
I have uploaded my screen shot of the error message.help me!!

**Comment by srmanikanta** [comment]
try this command
`git pull origin master `
then 
`git push -u origin master`

Note:  if it is not working please check the git url in .git/config file

**Comment by vishwendh105** [comment]
I have tried all the commands and It is not working.

**Comment by singaravellu** [comment]
change username/password in credential manager and try to push to github repository it will work or else you can do again  
git config --global user.name "<name>"
git config --global user.email "<mailid>"
and push

**Comment by NareshAbbanapuri** [comment]
hi
open credential manager and delete old one
