### ISSUE TITLE
while adding git remote add origin <url> and puhsing  getting error could you please help 

### ISSUE THREAD

**Issue by singaravellu** [QT-DevOps/DevOpsIssues#847]
git push -u origin master
remote: Repository not found.
fatal: repository 'https://github.com/singaravellu/learning.git/' not found
![image](https://user-images.githubusercontent.com/32475854/80860586-30c5d800-8c86-11ea-8975-2b6d20b0cba7.png)

**Comment by singaravellu** [comment]
if we create in remote repository with the name learning.git  then able to resolve the issue.

but in general using command git remote add origin <url> it's not working  giving same error as i mentioned above .do we need to go to remote repository and need to create manually?
could you please help on it. is that the process need to be followed?

**Comment by srmanikanta** [comment]
follow this procedure
* goto your repository then
* `ls -a`
* `cd .git`
* `vi config`
* this file is look like this 
```
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
[remote "origin"]
        url = https://github.com/<yourrepository>.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
```
in the above there is a remote section in there, find the key name as 'url' and provide your remote repository url.
then git push -u origin master.

Note: ensure your remote repo url is correct or not in .git/config file.

**Comment by singaravellu** [comment]
done the same thing but still i am facing the  issue.

**Comment by srmanikanta** [comment]
singaravellu call to this number 7893532934
