### ISSUE TITLE
Regarding to unlock Jenkins

### ISSUE THREAD

**Issue by MadalaSwetha** [QT-DevOps/DevOpsIssues#850]
I am getting permission denied while I am trying to unlock Jenkins. I need help in getting administration password. Post installation of Jenkins please help me to get password to unlock Jenkins. 

 
![image](https://user-images.githubusercontent.com/39823207/81142378-2e68c400-8f8d-11ea-966e-adfd93ba5df6.png)
![jenkinserror1](https://user-images.githubusercontent.com/39823207/81142499-7556b980-8f8d-11ea-8b97-5dd6a870a9a5.PNG)

**Comment by puru7791** [comment]
initialAdminPassword file does't have executable permission, just use cat command or change the permission of that file by hitting chmod +x <filename> then u can run.

**Comment by MadalaSwetha** [comment]
I fixed it with your help Purushotham. Thank you.
