### ISSUE TITLE
No hosts found error in Ansible

### ISSUE THREAD

**Issue by DivyasreeYanala** [QT-DevOps/DevOpsIssues#851]
![image](https://user-images.githubusercontent.com/63571979/81237798-778d3800-8fce-11ea-82ea-168cf663cbf2.png)
Ansible-playbook is:
![image](https://user-images.githubusercontent.com/63571979/81237872-a6a3a980-8fce-11ea-9889-3babbee4b355.png)
Host is as follow:
![image](https://user-images.githubusercontent.com/63571979/81237963-de125600-8fce-11ea-92d8-ad4b394861fd.png)
Please help me to solve this.
Thanks in advance.

**Comment by kirandevops12** [comment]
write 'package_name=apache2' and not 'package_name:apache2' in the host file.
As the error message is indicating it should be key=value
