### ISSUE TITLE
Terraform resource creation

### ISSUE THREAD

**Issue by RamanaChowdam** [QT-DevOps/DevOpsIssues#852]
when trying to create a terraform resource by using the data source it is failing 

resource "aws_instance" "platform" {
    ami           = var.ami_id
    instance_type = var.instance_type
    subnet_id     = var.public_subnet_id
    vpc_security_group_ids = aws_security_group.sg-test.id == "" ? data.aws_security_group.platform_security_groups : aws_security_group.sg-test.id
    key_name      = var.pemfile
    associate_public_ip_address = true 
    tags          = {
        name = "platform-Instance"
    }

}

data "aws_security_group" "platform_security_groups" {
    name = "terraform-test"
    vpc_id = var.vpc_id_of_platform
  
}

resource "aws_security_group" "sg-test" {
    name = "terraform-test"
    description = "testing sg creation"
    vpc_id = var.vpc_id_of_platform
    count = length(data.aws_security_group.platform_security_groups)
    ingress {
        description = "TLS from VPC"
        from_port   = 443
        to_port     = 443
        protocol    = "tcp"
        cidr_blocks = [ "0.0.0.0/0" ]
    }

    egress {
        from_port   = 0
        to_port     = 0
        protocol    = "-1"
        cidr_blocks = [ "0.0.0.0/0" ]
    }

  tags = {
    Name = "testing"
  }
  

  
}

i want to create and not create resource based on the data source output and i a want to assign security groups based on that creation
 
![Screenshot from 2020-05-07 15-30-39](https://user-images.githubusercontent.com/60684784/81282092-56812180-9078-11ea-87c2-7139a90f4043.png)

**Comment by srmanikanta** [comment]
please check the line number 5 in main.tf file
if you interpolate the values then follow this syntax
`${<resourcetype>.<resourcenmae>.<attributename>}`

**Comment by RamanaChowdam** [comment]
> please check the line number 5 in main.tf file
> if you interpolate the values then follow this syntax
> `${<resourcetype>.<resourcenmae>.<attributename>}`

for new syntax, we can give directly like this
<resource_type>.<name_of_resource>.<atttribute>

**Comment by srmanikanta** [comment]
yes ramana, if you know the new syntax try it. it clearly says the error in line 5 so please try to resolve.

**Comment by shaikkhajaibrahim** [comment]
Please don't help for challenges
