### ISSUE TITLE
Not able to unlock jenkins 

### ISSUE THREAD

**Issue by vishwendh105** [QT-DevOps/DevOpsIssues#854]
not able to unlock jenkins as the displayed the path to find the password to unlock jenkins and i am uploading the related images. i have checked the path from C:/var/lib/ but found nothing
![Git5](https://user-images.githubusercontent.com/51240081/81396529-323e4700-9143-11ea-961b-38c5b928e33e.png)
![Git6](https://user-images.githubusercontent.com/51240081/81396556-3c604580-9143-11ea-84bb-b495fa322382.png)

**Comment by srmanikanta** [comment]
if you are using linux just use this command in your linux terminal
`cat  /var/lib/jenkins/secrets/initialAdminPassword`. 
it will display the initial password 
if you are using windows open powershell and type the command
`cat C:\Users\<username>\.jenkins\secrets\initialAdminPassword`.

Note: find this location  $JENKINS_HOME/secrets/initialAdminPassword if you are using linux or windows.

**Comment by vishwendh105** [comment]
Okay , but machine is running on windows OS

**Comment by srmanikanta** [comment]
please find the jenkins home and try.
whether you are using windows or linux not that matter.
 `$JENKINS_HOME/secrets/initialAdminPassword` this is the path for both linux and windows. I already mention the path for both os's please read the comment completely.

**Comment by vishwendh105** [comment]
Sorry,my issue was not resolved i am not able to reply because of connectivity issue .
i am getting the same error that the path is not present.
![Git7](https://user-images.githubusercontent.com/51240081/81643938-57350180-9444-11ea-8ccd-059d6c79bb88.png)

**Comment by Lucifer2325** [comment]
i cannot access for initial password
![Screenshot 2023-05-27 033007](https://github.com/QT-DevOps/DevOpsIssues/assets/81623547/38dcb6a7-5254-4436-86a8-b134ba297ccf)

**Comment by aquibjaved1** [comment]
Use 'password' as admin password and try.

**Comment by srv1020** [comment]
use account as root user 

sudo su
cat /var/lib/jenkins/secrets/initialAdminPassword
