### ISSUE TITLE
building failure

### ISSUE THREAD

**Issue by Rajulolabhattu** [QT-DevOps/DevOpsIssues#858]
while executing the mvn package command i got a error as shown below 
![Screenshot (86)](https://user-images.githubusercontent.com/62057171/81509569-2e6c1980-9329-11ea-858e-692c3133ef5d.png)

**Comment by srmanikanta** [comment]
hi raju,
right now you are executing the `mvn package` as ubuntu user, but ubuntu user doesn't have permissions on jenkins home like `/var/lib/jenkins`

you have to do the following steps:
1. first connect to your jenkins server
2. once you connected then switch to root user `sudo -i`
3.  then finnaly switch to jenkins user `su jenkins`
4. get back to jenkins home `cd ~`
5. now execute this command `mvn package`
These are the steps to follow.
please close the issue.
