### ISSUE TITLE
How to verify whether Game Of Life is deployed correctly

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#86]
Hi,
My yml file seems to have run correctly and I can also see the new page at 
http://18.222.221.111:8080/
How do I see or play this game of life now?
---
- hosts: all
  become: yes
  roles:
  - geerlingguy.java
  - idealista.tomcat-role
  tasks:
  - name: copy war
    copy:
      src: gameoflife.war
      dest: /opt/tomcat/webapps/gameoflife.war
      owner: tomcat
    notify:
    - restart tomcat
  handlers:
  - name: restart tomcat
    service:
      name: tomcat
      state: restarted
      enabled: yes

![image](https://user-images.githubusercontent.com/40449948/43654468-ee9146ea-9768-11e8-8ca2-dc291ac3fbb9.png)

The contents in the deployed machine is as follows:
![image](https://user-images.githubusercontent.com/40449948/43654531-2f864d26-9769-11e8-923f-d24f2ccaadc3.png)

**Comment by arunkumar127** [comment]
@rameshm78 
To access website, url format is **http://<PublicIP>:<PortNo>/<projectname>**

In your case, url will be -
**http://18.222.221.111:8080/gameoflife**

**Comment by arunkumar127** [comment]
@rameshm78 
To access website, url format is **http://PublicIP:PortNo/projectname**

In your case, url will be -
**http://18.222.221.111:8080/gameoflife**

**Comment by rameshm78** [comment]
Thanks a lot Arun.
Success at last :-)
