### ISSUE TITLE
Jenkins Build Issue

### ISSUE THREAD

**Issue by rpkoya** [QT-DevOps/DevOpsIssues#860]
Hi,
I have created cloned spc project from github and created few builds, worked fine.
but when i gave "mvn package" in execute shell command line and tries to build it is failing.
i am attaching console outputs for your reference for both success and failure, can you please advice me why this is failing when i gave mvn package?
if i login to jenkins server and run mvn package from jenkins user it is running fine..

Please advice.

Regards,
Ravindra
[consoleoutput-failed.txt](https://github.com/QT-DevOps/DevOpsIssues/files/4610962/consoleoutput-failed.txt)
[consoleoutput-success.txt](https://github.com/QT-DevOps/DevOpsIssues/files/4610963/consoleoutput-success.txt)

**Comment by srmanikanta** [comment]
hi ravindra, call this number once 7893532934.

**Comment by rpkoya** [comment]
HI Manikanta, thanks for the call, issue with the processor in mt vmware, i installed Jenkins in aws on t2.large, in that its working fine.
