### ISSUE TITLE
NOT ABLE TO UNLOCK JENKINS

### ISSUE THREAD

**Issue by vishwendh105** [QT-DevOps/DevOpsIssues#861]
Sorry,my issue was not resolved i am not able to reply because of some connectivity issue .
i am getting the same error that the path is not present.here is screenshot of my error message.
![Git7](https://user-images.githubusercontent.com/51240081/81644101-be52b600-9444-11ea-997a-6f543ff38c85.png)

**Comment by srmanikanta** [comment]
hi vishwendh, call this number once 7893532934.

**Comment by vishwendh105** [comment]
Got it! unlocked jenkins.
