### ISSUE TITLE
Chef::Exceptions::ValidationFailed: Property package_name must be one of: String, Array!  You passed {}.

### ISSUE THREAD

**Issue by leelakumarit** [QT-DevOps/DevOpsIssues#863]
i am getting the validation error when i run the cookbook.

-------Recipe: install.rb
# Cookbook:: apacheaws
# Recipe:: install
# Copyright:: 2020, The Authors, All Rights Reserved.
# execute if only ubuntu
apt_update 'updateubuntu' do
    ignore_failure true
    action :update
    only_if { node['platform'] == 'ubuntu' }
end

package node ['apacheaws']['package_name'] do
    action :install
end

service node ['apacheaws']['package_name'] do
    action :enable
end

-------------attributes/default.rb

if node['platform_family'] == 'rhel'
    default['apacheaws']['package_name'] == 'httpd'

elsif node['platform_family'] == 'debian'
    default['apacheaws']['package_name'] == 'apache2'
end

--------output: 
Recipe Compile Error in /var/chef/cache/cookbooks/apacheaws/recipes/install.rb
================================================================================

Chef::Exceptions::ValidationFailed
----------------------------------
Property package_name must be one of: String, Array!  You passed {}.

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/apacheaws/recipes/install.rb:17:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/apacheaws/recipes/install.rb:

 10:
 11:  apt_update 'updateubuntu' do
 12:      ignore_failure true
 13:      action :update
 14:      only_if { node['platform'] == 'ubuntu' }
 15:  end
 16:
 17>> package node['apacheaws']['package_name'] do
 18:      action :install
 19:  end
 20:
 21:  service node['apacheaws']['package_name'] do
 22:      action :enable
 23:  end 24:

System Info:
------------
chef_version=15.10.12
platform=ubuntu
platform_version=18.04
ruby=ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef/bin/chef-client

Running handlers:
[2020-05-10T19:22:49+00:00] ERROR: Running exception handlers
Running handlers complete
[2020-05-10T19:22:49+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 01 seconds
[2020-05-10T19:22:49+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2020-05-10T19:22:49+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-05-10T19:22:49+00:00] FATAL: Chef::Exceptions::ValidationFailed: Property package_name must be one of: String, Array!  You passed {}.
ubuntu@ip-172-31-46-217:~$ Connection reset by 52.15.58.213 port 22

**Comment by srmanikanta** [comment]
share your cookbook in zip format

**Comment by leelakumarit** [comment]
[apacheaws.zip](https://github.com/QT-DevOps/DevOpsIssues/files/4630147/apacheaws.zip)

**Comment by srmanikanta** [comment]
hi leelakumarit,
you did some mistakes in install.rb, attribute file I correct it and mention where you make mistakes so please download this file and verify once this below cookbook is executed successfully  
[apacheaws.zip](https://github.com/QT-DevOps/DevOpsIssues/files/4632879/apacheaws.zip)

please close the issue.

**Comment by leelakumarit** [comment]
Hi, you have attached the same file again without any changes, can you please check and upload the changes you made.

Thanks,
Lee

**Comment by srmanikanta** [comment]
sorry for the oversight, this is the modified one please check
[apacheaws_modified.zip](https://github.com/QT-DevOps/DevOpsIssues/files/4634151/apacheaws_modified.zip)

**Comment by srmanikanta** [comment]
please close the issue.

**Comment by leelakumarit** [comment]
issue is fixed 
thaks, 
Lee
