### ISSUE TITLE
Cannot login to Jenkins Master server

### ISSUE THREAD

**Issue by debasis-gif** [QT-DevOps/DevOpsIssues#867]
Hello SIr,
I have been trying to setup a WINDOWS agent for Jenkins Server.
In doing so I could not properly connect to Jenkins master and then started to configure the global security settings. I tried to test for authorization through user and after that I am getting this error as I login to my Jenkins master UI **(http://<Jenkins Server>:8080/login?from=%2F)**

Getting the following error every time after the login screen with username and password:

![image](https://user-images.githubusercontent.com/60258623/82224450-7ac6e300-9941-11ea-9717-6006adedd65a.png)

Please help me resolve the issue as I cannot go forward with further work.

Thanks
Debasis Pal

**Comment by srmanikanta** [comment]
This is the network error please refresh the page in browser.

**Comment by singaravellu** [comment]
you can use below step to resolve i had faced the same while morning

![image](https://user-images.githubusercontent.com/32475854/82242977-6e03b880-995c-11ea-936e-cc9e622bedd2.png)

**Comment by debasis-gif** [comment]
I am constrained to try this option of crumb for PCSRF security, as I am not being able to invoke the landing page of Jenkins GUI after I provide my login credentials.

Anyway after trying many options which did not work, I was forced to remove my Jenkins installation on AWS Linux and went for re-installation and configuration, after which I am back to normal operations.

Anyway, I will remember this solution in case in future I encounter such problems related to PCSRF

Thanks
Debasis

**Comment by srmanikanta** [comment]
if you resolve the issue, please close the issue.
