### ISSUE TITLE
unable to build job

### ISSUE THREAD

**Issue by seshi7** [QT-DevOps/DevOpsIssues#868]
Hi Team,
while building jenkins job i am getting build failure.
I created jenkinsfile and also added,commited, when ever i do build getting failure.
In job configure also i mentioned (like git url)correctly.
Project i cloned is springpet-clinic & also gameof-life
could u help me to find where the error is.
![error](https://user-images.githubusercontent.com/38456695/82289538-a5a54b80-99c2-11ea-92b9-9417b8807d0c.PNG)

**Comment by srmanikanta** [comment]
are you create a jenkinsfile in your git repository? please check and share the screenshot here.

**Comment by seshi7** [comment]
yes
![error1](https://user-images.githubusercontent.com/38456695/82330265-3cdcc400-9a00-11ea-8272-0eb48ce293e1.PNG)

**Comment by srmanikanta** [comment]
once you are in this path `root@ip-172-31-80-220:~/spring-petclinic`
execute this command `mv jenkinsfile Jenkinsfile`
and try to build the project and update the issue.

**Comment by seshi7** [comment]
okay now i moved & the issue resolved
