### ISSUE TITLE
executing ansible playbook getting the below error can anyone help on this issue

### ISSUE THREAD

**Issue by srinivaspanjala** [QT-DevOps/DevOpsIssues#87]
ansible@ip-172-31-92-13:~$ ansible-playbook -vv hello.ymal
ansible-playbook 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: hello.ymal ***************************************************************************************************************************************************************************
1 plays in hello.ymal

PLAY [all] *************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************
task path: /home/ansible/hello.ymal:2
The authenticity of host 'ip-172-31-92-13.ec2.internal (172.31.92.13)' can't be established.
ECDSA key fingerprint is SHA256:FLFBxBZtewbJmxcEtPxmOHa6jhioPFqsFslc8TQQOKI.
Are you sure you want to continue connecting (yes/no)? ok: [ip-172-31-88-235.ec2.internal]
yes
fatal: [ip-172-31-92-13.ec2.internal]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'ip-172-31-92-13.ec2.internal,172.31.92.13' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,password).\r\n", "unreachable": true}
META: ran handlers

TASK [install webserver] ***********************************************************************************************************************************************************************
task path: /home/ansible/hello.ymal:7
ok: [ip-172-31-88-235.ec2.internal] => {"cache_update_time": 1533476740, "cache_updated": false, "changed": false}
META: ran handlers
META: ran handlers
        to retry, use: --limit @/home/ansible/hello.retry

PLAY RECAP *************************************************************************************************************************************************************************************
ip-172-31-88-235.ec2.internal : ok=2    changed=0    unreachable=0    failed=0
ip-172-31-92-13.ec2.internal : ok=0    changed=0    unreachable=1    failed=0

**Comment by shaikkhajaibrahim** [comment]
Can you share your playbook

**Comment by mani5a3** [comment]
yaml or yml extension right. spelling is incorrect ymal

**Comment by srinivaspanjala** [comment]
Thank you
