### ISSUE TITLE
terraform instance not creating

### ISSUE THREAD

**Issue by yagnasivasai** [QT-DevOps/DevOpsIssues#870]
![Screenshot (8)](https://user-images.githubusercontent.com/60940642/82443187-b1763800-9abe-11ea-98b5-b2059f0fc5ab.png)

**Comment by srmanikanta** [comment]
please check the ami id and iam user permissions.

**Comment by srmanikanta** [comment]
hi yaznasivasai, if you resolve the issue please close otherwise please update the issue

**Comment by yagnasivasai** [comment]
I tried with IAM user with admin privileges as well as root user but no
use..

**Comment by srmanikanta** [comment]
hi yaznasivasai call to this number 7893532934.

**Comment by ashok655** [comment]
Try with different ami-id

**Comment by NareshAbbanapuri** [comment]
hi
share tf file

**Comment by srmanikanta** [comment]
hi yaznasivasai, are you resolved or not ? 
if you resolve please close the issue otherwise update the issue.
