### ISSUE TITLE
an error occurred ( unable to connect jenkins) while select plugins to install 

### ISSUE THREAD

**Issue by ram-1912** [QT-DevOps/DevOpsIssues#871]
jenkins error 
unable to connect jenkins error is displayed 
<img width="960" alt="Annotation 2020-05-20 204018" src="https://user-images.githubusercontent.com/62230764/82463383-6407c400-9ada-11ea-81cb-e75e532b8c06.png">

**Comment by srmanikanta** [comment]
try to refresh the page it might be network issue, if you alreadu resolve the issue please close the issue.
