### ISSUE TITLE
NOT ABLE TO INSTALL TO CHOCOLATEY

### ISSUE THREAD

**Issue by vishwendh105** [QT-DevOps/DevOpsIssues#872]
Hello, 
I am not able to install chocolatey in my local machine as process shown in the video. I am getting the error as shown in the screen shot below. And also i have tried using the CMD the same error was repeating. Please help!!
![TF2](https://user-images.githubusercontent.com/51240081/82464522-cf9e6100-9adb-11ea-8e74-e16999fdf673.png)

**Comment by srmanikanta** [comment]
hi vishwendh,
please open powershell as an administrator and try to execute the choco command.
if you resolve the issue please close the issue.

**Comment by vishwendh105** [comment]
Issue resolved!!
