### ISSUE TITLE
Error while executing mvn package through artifactory

### ISSUE THREAD

**Issue by samineni1927** [QT-DevOps/DevOpsIssues#873]
Tried to execute the sample java maven project using artifactory and got below error.
![artifactory](https://user-images.githubusercontent.com/60940441/82471081-d630d680-9ae3-11ea-8ab6-17afeec89ae8.PNG)

my settings.xml file in txt format
[settings.xml file.txt](https://github.com/QT-DevOps/DevOpsIssues/files/4658082/settings.xml.file.txt)

**Comment by srmanikanta** [comment]
try to execute the `mvn package` as jenkins user.

**Comment by samineni1927** [comment]
the error was same 
![artifactory2](https://user-images.githubusercontent.com/60940441/82475818-b18c2d00-9aea-11ea-832e-66c5337bb11c.PNG)

**Comment by samineni1927** [comment]
the same connection issue on jenkins server 
![artifactory3](https://user-images.githubusercontent.com/60940441/82482610-b6ee7500-9af4-11ea-9c65-335799b592ea.PNG)

jfrog artifactory is working fine on http://localhost:8081/

**Comment by srmanikanta** [comment]
please check the port 8081 is opened in your security group. if you are not able to resolve the issue
please call this number 7893532934.

**Comment by srmanikanta** [comment]
hi samineni. if you resolve the issue please close the issue otherwise update the issue.

**Comment by samineni1927** [comment]
No sir by changing the Base URL to system http://pcIP-address:8082 also the connection refused.

**Comment by srmanikanta** [comment]
your url must be like this `http://<publicip>:8081`
