### ISSUE TITLE
Terraform (Error while doing apply)

### ISSUE THREAD

**Issue by abhi-devops02** [QT-DevOps/DevOpsIssues#874]
I am getting this error while creating s3bucket. While applying terraform apply, 

error what i was getting
![image](https://user-images.githubusercontent.com/63766247/82642866-39c61b80-9c2c-11ea-8912-416a295b027d.png)

My main.tf file
![image](https://user-images.githubusercontent.com/63766247/82642797-1ac78980-9c2c-11ea-8c47-53f9e4f83d0f.png)

**Comment by srmanikanta** [comment]
try another bucket name because the bucket `abhis3bucket`  already created.

**Comment by sharmatanmaya** [comment]
I think the test-bucket is already created, try using different name.

**Comment by abhi-devops02** [comment]
I tried with different names as well. Getting same error
Tried with 5 different names

**Comment by NareshAbbanapuri** [comment]
hi Abhi
please use a different name

**Comment by abhi-devops02** [comment]
> hi Abhi
> please use a different name

I tried with different names as well. But couldn't resolve

**Comment by shaikkhajaibrahim** [comment]
Is this still open

**Comment by srmanikanta** [comment]
hi abhi, s3 name is contains unique name, so everytime you will execute terrafrom apply with a different s3 bucketname or simple destroy the old one and again apply.
Note: whatever you provide the name of the bucket that name was not exist in the aws. unique means it is globally becomes unique.

**Comment by abhi-devops02** [comment]
> Is this still open

Yes Sir, I am unable to create it

**Comment by abhi-devops02** [comment]
> hi abhi, s3 name is contains unique name, so everytime you will execute terrafrom apply with a different s3 bucketname or simple destroy the old one and again apply.
> Note: whatever you provide the name of the bucket that name was not exist in the aws. unique means it is globally becomes unique.

What I did was, I totally deleted all the folder and tried with different name.

**Comment by srmanikanta** [comment]
abhi please call to 7893532934

**Comment by abhi-devops02** [comment]
> abhi please call to 7893532934

Tried of calling you but getting as your no is outof service

**Comment by srmanikanta** [comment]
> > abhi please call to 7893532934
> 
> Tried of calling you but getting as your no is outof service

now it is working.
