### ISSUE TITLE
Windows Agent for Jenkins Master issue

### ISSUE THREAD

**Issue by debasis-gif** [QT-DevOps/DevOpsIssues#875]
Hello Sir,
I have set up windows node on AWS and installed java (openjdk8) over chocolatey.
I wanted to use this node to connect to Jenkins Master (Ubuntu on AWS).

- New node from Manage Jenkins created 

- Then went to windows node (remote desktop connect) to setup the connection to Jenkins Master

- The **agent.jar** has been downloaded and **secret-file** has also been created on the WIndows node onto the **c:\users\Administrator\jenkins** folder 

- The global security configuration has been setup to use TCP port for inbound agents as **random**

- But the final step on the windows agent **java -jar agent.jar ………** fails like below:
![image](https://user-images.githubusercontent.com/60258623/82666619-e8ca1d80-9c53-11ea-9cf9-8a3c5e086bec.png)

Please finally Windows agent fails to connect to the Jenkins master.

Please help resolve the issue

Thanks
Debasis

**Comment by srmanikanta** [comment]
please copy the ` java -jar agent.jar............` command properly from jenkins master and open all traffic in your security group also.

**Comment by debasis-gif** [comment]
Hi,
I have pasted the command in the screenshot **"java -jar agent.jar...."** - please check and there should not be any issue in it. 

The command is being run in the Windows agent node with the **-jnlpUrl** URL option pointing to global ip-addr of Jenkins Master server.

The security group on the WIndows node is configured with in-bound traffic protocol for **ALL_TCP** with anywhere port.

The error encountered as mentioned in the snapshot is **No argument is allowed...***

**Comment by srmanikanta** [comment]
hi debasis call to this number 7893532934.

**Comment by debasis-gif** [comment]
Hi Manikanta,
Thanks for your response and am sorry to have read the mail late - there is some issue with network and electricity in Kolkata after the Amphan storm devastation.
Will it be fine if I call this number today (Sunday) or shall I call tomorrow?
Thanks & Regards,
Debasis Pal7972930164 / 9836965177 

    On Saturday, 23 May 2020, 19:17:13 GMT+5:30, srmanikanta <notifications@github.com> wrote:  
 
 


hi debasis call to this number 7893532934.

**Comment by srmanikanta** [comment]
no problem, if you call today.

**Comment by shaikkhajaibrahim** [comment]
Try to use the command correctly.
Also share the screen shot of then jenkins node configure

**Comment by debasis-gif** [comment]
**RESOLVED...**
Solution:
======
1. prepared the Windows agent powershell run by Administrator for environmental variables for 
**$env:JAVA_HOME** and **$env:PATH (to use JAVA_HOME/bin)**

2. The command line used the secret without using secret-file
**java -jar agent.jar -jnlpUrl http://3.6.87.196:8080/computer/WindowsAgent/slave-agent.jnlp -_secret 868300de300e32edecd636bba000631b6e67af78f2be74aebf2c36b3baaa28cb_ -workDir "C:\Users\Administrator\jenkins"**

![image](https://user-images.githubusercontent.com/60258623/82757396-d4298900-9dfd-11ea-9e0a-5147b79b2baf.png)

**Comment by debasis-gif** [comment]
![image](https://user-images.githubusercontent.com/60258623/82757555-ce807300-9dfe-11ea-99d3-8f32d8af6b93.png)

**Comment by debasis-gif** [comment]
Hi Manikanta,
The issue #857 is now resolved and closed. 
I have put in the solution steps in the case closure.
Thanks for your and Khaja sir's help. 
Thanks & Regards,
Debasis Pal7972930164 / 9836965177 

    On Sunday, 24 May 2020, 09:48:45 GMT+5:30, shaikkhajaibrahim <notifications@github.com> wrote:  
 
 


Try to use the command correctly.
Also share the screen shot of then jenkins node configure
