### ISSUE TITLE
chef convergence is not updating the node run_list

### ISSUE THREAD

**Issue by vinodmaddela** [QT-DevOps/DevOpsIssues#876]
Hi,
I've read the related threads on the QT-DevOps but couldn't find the answer. So, I am posting it my questions

1. I have manually converged the node after the **initial berks upload** and could verify the items in the cookbook recipe on the node. Later, I made changes to the recipe, updated version in metadata.rb and performed a berks upload. After that I logged into chef server and updated the node with latest version of the cookbook and waited for the convergence to happen. however it did not happen after waiting for couple of hours. I then tried manual convergence and it worked. I am trying to understand why it did not pick the updated run_list?
I tried using **knife status** to see when it last converged, is there a different command?

2. To view the versions of the cookbook I tried few commands but not successful. The closet command is **knife cookbook show COOKBOOK [version] [..] [...] (options)**. can anyone reply if they are able see the versions?

Thanks in advance!

**Comment by srmanikanta** [comment]
try these commands 
`knife search -i 'cookbooks:your-cookbook' -a cookbooks.your-cookbook.version`
or 
`knife node show <node-name> -a base_cookbook.cookbook_versions`
if your resolve the issue. please close the issue otherwise update the issue.

**Comment by vinodmaddela** [comment]
Hi @srmanikanta , thank you for your response.
**knife search -i 'cookbooks:your-cookbook' -a cookbooks.your-cookbook.version**  - when run is displaying the node information and this command is asking us to pass **version info**

I am trying to get the list of all the versions. e,g when we run **knife cookbook list** it displays the list of all cookbooks. Likewise I am trying to find a command which returns list of cookbook versions. 

The other command also displaying the same info..
 Aplogies, if I had not made my question clear. All I want is 
1. to get list of versions associated with the cookbook ?
2. command to see convergence info?

TIA

**Comment by srmanikanta** [comment]
hi vinodmaddela, please try this command 
`knife node show <node-name> -a cookbooks`
just pass your node name in the above `<node-name>`
![image](https://user-images.githubusercontent.com/50364350/82736259-eea02b80-9d45-11ea-8f57-a9d9df73d0fc.png)
I think this is useful to you, if not please ignore.

**Comment by vinodmaddela** [comment]
Thanks @srmanikanta ,  but it isn't really helping. 

can we wait for couple of days for others to respond with their inputs and then close it?

**Comment by sharmatanmaya** [comment]
List of version associated with the cookbook can be viewed 
knife cookbook show <cookbookname>

**Comment by shaikkhajaibrahim** [comment]
Can  you use the chef_client supermarket cookbook and change the convergance to 10 mins and see whether its executed or not on chef server. Use hosted chef-server reports section

**Comment by vinodmaddela** [comment]
> List of version associated with the cookbook can be viewed
> knife cookbook show

Hi @sharmatanmaya , @srmanikanta  thank you for the input. 

I am able to see the list of cookbook versions in UI; please refer to the screen
![image](https://user-images.githubusercontent.com/38660202/83056779-e00b8a00-a04d-11ea-8375-87632a40445f.png)

But I was actually looking for a command to view the version in cmd and the command is 

**knife cookbook show cookbook_name --list** Please refer to the screen

![image](https://user-images.githubusercontent.com/38660202/83056583-9753d100-a04d-11ea-96e7-b3434c778f1a.png)

Thank you!

**Comment by vinodmaddela** [comment]
> Can you use the chef_client supermarket cookbook and change the convergance to 10 mins and see whether its executed or not on chef server. Use hosted chef-server reports section

Sir @shaikkhajaibrahim , the convergence is happening now.. Thank you !
