### ISSUE TITLE
i am getting below error while installing jfrog artifactory could anyone help on this

### ISSUE THREAD

**Issue by singaravellu** [QT-DevOps/DevOpsIssues#877]
![image](https://user-images.githubusercontent.com/32475854/82727443-44ee7980-9d08-11ea-8139-acfcdd93cd1f.png)

**Comment by srmanikanta** [comment]
hi singaravellu. please download the `jfrog-artifactory-pro-6.19.1.deb` before you installed.

**Comment by srmanikanta** [comment]
please close the issue.

**Comment by singaravellu** [comment]
still not yet done it was asking password to start service for root user system was not responding

**Comment by singaravellu** [comment]
will try to work in high configuration machine
