### ISSUE TITLE
sonarqube complete installation steps

### ISSUE THREAD

**Issue by venkatvegesna** [QT-DevOps/DevOpsIssues#878]
could you please provide the latest installation steps you followed to install sonarqube with mysql.
as temporarly i hosted on docker due to issue with manual installation steps provided.

sudo apt-get update
sudo apt-get install openjdk-8-jdk
sudo apt-get install sonar=6.7.4
sudo service sonar start

installing sonarqube didnt work using apt-get on ubuntu.

**Comment by srmanikanta** [comment]
hi venkat, call to this number 7893532934.

**Comment by shaikkhajaibrahim** [comment]
https://directdevops.blog/2019/01/05/sonarqube/
