### ISSUE TITLE
unable to configure email notification via google smtp server to test

### ISSUE THREAD

**Issue by venkatvegesna** [QT-DevOps/DevOpsIssues#879]
i am unable to configure smtp server for testing the email notifications on jenkins using email extension plugin.Is there any other way we can test this via smtp as dont have smtp mail server with me.i am using google gmail as below and encountering error on testing configuration.

SMTP : smtp.gmail.com
User Name:<PROVIDED gmail> 
 Password: <PROVIDED gmail password>
  Use SSL:YES
SMTP Port:465
 Test e-mail recipienT:<provided gmail>

when tested configuration getting below error my credentials are correct cross checked.

javax.mail.AuthenticationFailedException: 534-5.7.9 Application-specific password required. Learn more at
534 5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor q4sm11896087qtf.35 - gsmtp

**Comment by srmanikanta** [comment]
hi venkat, call to this number 7893532934.

**Comment by shaikkhajaibrahim** [comment]
smtp2go.com
