### ISSUE TITLE
Shell Script 

### ISSUE THREAD

**Issue by itzpraveen18** [QT-DevOps/DevOpsIssues#88]
Dear Friends , I have wrote the shell scripts  for Jenkins installation  
i have  provided the   "sudo apt-get install oracle-java8-installer -y " in install script but still it showing prompt like "Yes" or "Not" during the run time of script for java 
what to do for this i there any alternate to this??

mine shell script i have provided like this 

sudo apt-get update
sudo apt-add-repository ppa:webupd8team/java -y
sudo apt-get update
echo "installing java"
sleep  10
sudo apt-get install oracle-java8-installer -y
echo "showing java version "
sleep 3
java -version
echo "export JAVA_HOME=/usr/lib/jvm/java-8-oracle/   export PATH=$PATH:$HOME/bin:$JAVA_HOME/bin  "  >> /etc/profile

java -version 
sleep 10 
echo "installing Maven "
cd /opt
 sudo wget wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
 sudo tar xzf apache-maven-3.5.4-bin.tar.gz
sudo ln -s /opt/apache-maven-3.5.4/bin/mvn /usr/bin/mvn
echo "M2_HOME=/opt/apache-maven-3.5.4   PATH=$PATH:$M2_HOME/bin    export M2_HOME    export PATH  " >> /etc/profile

sleep 3
mvn --version

echo "starting jenkins installations "

sleep 10
wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add - 
sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list' 

sudo apt-get update
sudo apt-get install jenkins -y 
sudo cat /var/lib/jenkins/secrets/initialAdminPassword
sudo service jenkins status
sleep 10
sudo service jenkins restart

**Comment by raviops100** [comment]
after 6 th line of your script add below line

read -p "Press enter to continue"

**Comment by itzpraveen18** [comment]
Dear Ravi Thank you For your Response 
 read -p "Press enter to continue"
 for me also it shown a prompt press to continue while executing but i  dont want any prompt like  " press yes or no " like that ??  to enter manually,
  it should be automated

**Comment by satyatvs** [comment]
you are trying to install licenced version java, so you have to agree the licence
if not you can use open jdk8 default so that manual intervention is not required.

**Comment by itzpraveen18** [comment]
Thank you Ravi
