### ISSUE TITLE
BUILD ISSUE 

### ISSUE THREAD

**Issue by vishwendh105** [QT-DevOps/DevOpsIssues#881]
Hello, QT
when ever i am going to building the project i am getting the build error  attaching the screen shot of it.
![Jenkins1](https://user-images.githubusercontent.com/51240081/82791842-14374d00-9e8c-11ea-90b6-840f13130ef7.png)

**Comment by singaravellu** [comment]
post the configuration where you are trying to execute the shell command

**Comment by ashok655** [comment]
command entered in invoke shell is incorrect.share the details of configuration to resolve error.

**Comment by srmanikanta** [comment]
hi vishwendh, 
write the command in execute shell as follows
`echo "building the code"`
please close the issue.

**Comment by srmanikanta** [comment]
hi vishwendh, are you resolve the issue. if yes please close the issue otherwise update the issue.
