### ISSUE TITLE
Terraform[getting error while doing apply] 

### ISSUE THREAD

**Issue by seshi7** [QT-DevOps/DevOpsIssues#883]
Hi Team,
I created a resource for s3 bucket then i seen the s3 bucket in s3.
when i try to create another bucket getting error.
i created my instance in northvirginia.

![terraform-issue2](https://user-images.githubusercontent.com/38456695/82801846-94b17a00-9e9b-11ea-8ed3-abdfdeeee99f.PNG)

![terraform-issue1](https://user-images.githubusercontent.com/38456695/82801527-12c15100-9e9b-11ea-8efd-e9ad1bd37fe7.PNG)

**Comment by ashok655** [comment]
Did you create the initial S3 bucket in same region?I think,the role policy is restricted to us-east-2.

Try with us-east-2.

**Comment by srmanikanta** [comment]
hi seshi,
s3 bucket is global and it contain's unique name
so you have to provide unique name that no one can used that name before.
and please ensure your current region and check in that region.
Note: if you execute terraform apply multiple please change the name of s3 bucket.

**Comment by NareshAbbanapuri** [comment]
hi 
shesi first delete user name in IAM
don't share access key and secrete key
bucket name unique
use different region

**Comment by seshi7** [comment]
Hi,
I changed user name of IAM earlier.
I deleted the terraform folder and i recreated then it works in same region.
I dont know why i get error if i use the script what i mention here.
When i change the bucket name it is working.

**Comment by srmanikanta** [comment]
hi seshi, are you resolve the issue, if not update the issue.

**Comment by seshi7** [comment]
Yeah i resolved
