### ISSUE TITLE
Error while using chef supermarket cookbooks 

### ISSUE THREAD

**Issue by vinodmaddela** [QT-DevOps/DevOpsIssues#884]
I tried executing the cookbook exercise by @shaikkhajaibrahim  sir from git location 
[https://github.com/asquarezone/ChefZone/tree/master/Exercise/Supermarket](url) getting an error.
 Can anyone correct where I went wrong? 
Please refer tot the screen 
![image](https://user-images.githubusercontent.com/38660202/82807370-87869200-9e7f-11ea-8d20-b78b20b53ed3.png)

**Comment by srmanikanta** [comment]
share your cookbook logs.

**Comment by vinodmaddela** [comment]
Hi @srmanikanta , I think I am making a mistake by not defining the custom resouces from chef supermarket properly in the cookbook. pls refer screen for log

![image](https://user-images.githubusercontent.com/38660202/83081196-ffb7a800-a077-11ea-9dee-171c191c54fa.png)

**Comment by srmanikanta** [comment]
please check `from_file` in your default.rb
