### ISSUE TITLE
Jenkins+Windows node configuration issue

### ISSUE THREAD

**Issue by sharmatanmaya** [QT-DevOps/DevOpsIssues#885]
While configuring a windows node to my Jenkins master which is hosted in an AWS machine i found that, there is no option "Let Jenkins control this windows agent as a windows service" available under launch method field. Is there a way to enable this option?

**Comment by srmanikanta** [comment]
actually this is the process
* launch a windows node and 
* then goto your jenkins server and then configure the node, once you configured the node then you will get some commad copy that command 
* next move on to windows node and execute that command or write a windows service for using that command.

I think this is useful to you if not please ignore.
