### ISSUE TITLE
Not getting private_ip and public_ip any help

### ISSUE THREAD

**Issue by singaravellu** [QT-DevOps/DevOpsIssues#887]
input
![image](https://user-images.githubusercontent.com/32475854/83170288-effc9a00-a131-11ea-8039-16d108424478.png)

output 

<img width="457" alt="output" src="https://user-images.githubusercontent.com/32475854/83170361-09054b00-a132-11ea-90e2-def0c3daafd4.PNG">

**Comment by srmanikanta** [comment]
remove double quotes in outputs just write like this
`aws_instance.newec2.public_ip and aws_instance.newec2.private_ip`

**Comment by abhi-devops02** [comment]
Hello
![image](https://user-images.githubusercontent.com/63766247/83213890-e8181680-a180-11ea-84c0-78af6e9b9052.png)

Here you made one small mistake. In the above image you have mentioned value in (""). Please remove it and try once again.

**Comment by singaravellu** [comment]
yeah thanks small mistake
