### ISSUE TITLE
getting below error please help on this 

### ISSUE THREAD

**Issue by singaravellu** [QT-DevOps/DevOpsIssues#888]
input 
<img width="540" alt="inputj" src="https://user-images.githubusercontent.com/32475854/83248461-b758d100-a1c2-11ea-8936-88739f6cc2fd.PNG">
  output 

![image](https://user-images.githubusercontent.com/32475854/83248498-c6d81a00-a1c2-11ea-8cdb-922598e8c7ac.png)

**Comment by neelaraokala** [comment]
![resolution](https://user-images.githubusercontent.com/60516092/83334433-1baf8980-a2c4-11ea-8730-5b8820ccfcd9.png)
we will go it by trail and error methode:
1.Remove the SLASH with in the CIRCLE and give command as **sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'**  then try it works ok other than 
2. mention "n" immediate next to SLASH as like and try
![resolution2](https://user-images.githubusercontent.com/60516092/83334566-13a41980-a2c5-11ea-8dc7-4d143770ece7.png)
  NOTE: i'm just try to resolve the issue , don't mine if it is not resolved.

**Comment by ramjagadeeshkumar** [comment]
sudo apt-get update
sudo apt-get install openjdk-8-jdk -y
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > \
    /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
sudo apt-get install jenkins
sudo service jenkins status


https://www.digitalocean.com/community/tutorials/how-to-install-jenkins-on-ubuntu-18-04

Above link also help to install Jenkins in Ubuntu 18

**Comment by singaravellu** [comment]
@ramjagadeeshkumar  my concern is not how to install jenkins manually need to automate using terraform

**Comment by singaravellu** [comment]
@neelaraokala Remove the SLASH with in the CIRCLE and give command as sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list' it's working but it's not ending still keep on creating
![image](https://user-images.githubusercontent.com/32475854/83346837-a1235000-a33d-11ea-851b-728c2fcea7fd.png)

**Comment by neelaraokala** [comment]
if it is still creating , just stop it by using "ctrl+c" then login into your jenkins by using 8080 port. it works fine other wise , go with 2nd option  "/n " as i mentioned above . it may works.

**Comment by singaravellu** [comment]
if you provide /n getting bellow error 
![image](https://user-images.githubusercontent.com/32475854/83351711-0722ce00-a364-11ea-94bb-9138ee7a65d9.png)

**Comment by srmanikanta** [comment]
hi singaravellu, actually this is done by two ways,
1. use `\n` for newline.
2. use heredocs

for reference [Click Here](https://www.terraform.io/docs/configuration/expressions.html#string-literals)

**Comment by singaravellu** [comment]
same error @ srmanikanta
