### ISSUE TITLE
As i was commiting my code to github i was not able view my code.

### ISSUE THREAD

**Issue by vishwendh105** [QT-DevOps/DevOpsIssues#890]
Hello, QT
 As i was Once again commiting my code to github i was not able view my code. Iam attaching my output screen shot.
![Git10](https://user-images.githubusercontent.com/51240081/83347265-a71b3000-a341-11ea-87bd-69ce689e2472.png)

**Comment by neelaraokala** [comment]
Hi vishwendh105,
what ever you commit's it will moved to local repository .if you want to see your commits  go with "git log "  it will shown your commit's details as like below mentioned snap  
![resolution3](https://user-images.githubusercontent.com/60516092/83348474-94f1bf80-a34a-11ea-8abd-58eabe1db619.png). if you want to see the code which your commited , enter pwd , it will show the path . you can find it there.

**Comment by srmanikanta** [comment]
hi vishwendh, please elaborate your question.

**Comment by vishwendh105** [comment]
When I was committing my code to GitHub through powershell. I am not able
to see my code which is committed  in my repo.

**Comment by srmanikanta** [comment]
use git push command and then check.

**Comment by vishwendh105** [comment]
Tried using the Git Push but same result

**Comment by srmanikanta** [comment]
post a screenshot of git push command

**Comment by vishwendh105** [comment]
I have tried git push it was showing fatal showing fatal error have tried all the possibilities it showed and also attached the screen shot.
![Git11](https://user-images.githubusercontent.com/51240081/83395997-dea8db80-a418-11ea-90ea-7d0e229d1b8d.png)

**Comment by srmanikanta** [comment]
use this command `git push vishwendh105 master`

**Comment by srikantheee** [comment]
this works out _$git push origin master_

**Comment by vishwendh105** [comment]
Hello, manikanta. I have used the command mentioned by you but it gives an error. Here is the screen shot of it.
![Git12](https://user-images.githubusercontent.com/51240081/83663676-9fc88080-a5e6-11ea-9bf2-2f59050ae809.png)

**Comment by srmanikanta** [comment]
do git pull operation before git push.
