### ISSUE TITLE
running ansible-playbook from terraform in local-exec

### ISSUE THREAD

**Issue by tejamvs** [QT-DevOps/DevOpsIssues#891]
Hi Guys,
By using terraform i created a ec2 and using local-exec to run a ansiblle-playbook.
My machine with terraform also had ansible installed. 
I dont want to install ansible on the ec2 creating by terraform, So im running below command .
Im able to connect to the ec2 created by terraform through connect and it is executing the commands. But the remote-exec is not working .

**provisioner "local-exec" {
    command = "sleep 120;ansible-playbook -u ubuntu -i ${aws_instance.bastionhost.public_ip},  --private-key ./sample.pem create_users.yml"    
}**

where ${aws_instance.bastionhost.public_ip}--- publicip to the instance creating
sample.pem------ pem file of aws

Im getting below :
The authenticity of host '<publivip>' can't be established.

Can anyone help with the other command of running or the issue. It will be grateful.Thanks in advance.

**Comment by Teja-MVS** [comment]
Thanks guys , i found the solution in one of the forum , it is in different method, i made my solution from it. For reference below is the solution to it . 

**resource "aws_eip" "bastionhost-eip" {
  instance                 = aws_instance.bastionhost.id
  vpc                      = true
  tags                     = {
      Name                 = var.eip-names[1]
  }
  depends_on               = [ aws_instance.bastionhost ]

  provisioner "local-exec" {
    command = "echo [terra_ansible_host:vars] > hosts"
  }
  provisioner "local-exec" {
    command = "echo ansible_ssh_user=ubuntu >> hosts"
  }
  provisioner "local-exec" {
    command = "echo ansible_ssh_private_key_file=/home/ubuntu/vpc-ec2-dynamic/sample.pem >> hosts"
  }
  provisioner "local-exec" {
    command = "echo [terra_ansible_host] >> hosts"
  }
  provisioner "local-exec" {
    command = "echo ${aws_eip.bastionhost-eip.public_ip} >> hosts"
  }
  provisioner "local-exec" {
    command = "sudo ansible-playbook -i hosts create_users.yml"
  }

connection {
        type                = "ssh"
        user                = "ubuntu"
        private_key         = file("/home/ubuntu/vpc-ec2-dynamic/sample.pem")
        host                = aws_eip.bastionhost-eip.public_ip
    }
}**

Reference link : **https://www.bogotobogo.com/DevOps/Ansible/Ansible-Terraform-null_resource-local-exec-remote-exec-triggers.php**
