### ISSUE TITLE
getting sendEmail() error when calling  

### ISSUE THREAD

**Issue by singaravellu** [QT-DevOps/DevOpsIssues#892]
jenkins file
![image](https://user-images.githubusercontent.com/32475854/83754055-f4bcd300-a688-11ea-8207-66a684868f91.png)

output of jenkins

![image](https://user-images.githubusercontent.com/32475854/83754093-07370c80-a689-11ea-9f09-fc999f9bef05.png)

**Comment by srmanikanta** [comment]
try manually first then write a script because manually I think you are not configure correctly. once manually is success then write a groovy script.

**Comment by singaravellu** [comment]
i have configure and ran it's working fine.
