### ISSUE TITLE
JFrog Artifactory login screen after installation not coming up

### ISSUE THREAD

**Issue by debasis-gif** [QT-DevOps/DevOpsIssues#893]
Hi Sir,
After all the installation and correct start of artifactory service from ubuntu server (t2.large) the UI cannot be invoked 

**http://13.233.76.73:8081/artifactory** 

The JFrog logo keeps on blinking...

Please suggest what could be the issue:

![image](https://user-images.githubusercontent.com/60258623/83786327-2d23d780-a6b0-11ea-99be-0d8ff24dc008.png)

Here's the artifactory service up and running
![image](https://user-images.githubusercontent.com/60258623/83787065-d539a080-a6b0-11ea-8c41-6344f5eecb6d.png)

**Comment by srmanikanta** [comment]
try like this `http://<publicip>:8081`

**Comment by debasis-gif** [comment]
Hello,

The solution is found:
After a lot of experiments in installation finally it was found that **the issue was related to the browser** - I was using the url over Internet-Explorer, whereas when I tried to run it on another browser (Chrome/Google) just for the sake of checking it is working immediately. I have wasted a lot of time in not doubting the browser issue - **_this is a lesson learnt_**

I need to get the latest version of IE browser and will check if it works - **till then I will keep the issue open**
