### ISSUE TITLE
Define attributes in notifies in CHEF

### ISSUE THREAD

**Issue by abasimdev** [QT-DevOps/DevOpsIssues#894]
My recipe is as follows :
![recipe](https://user-images.githubusercontent.com/64391011/83964845-35a52980-a8cd-11ea-9e04-90b2e91b319d.PNG)

My attribute file :
![attribute](https://user-images.githubusercontent.com/64391011/83964869-51a8cb00-a8cd-11ea-8d22-518ccf2b4ceb.PNG)
Error:
![Error](https://user-images.githubusercontent.com/64391011/83964882-5ec5ba00-a8cd-11ea-848b-385844cf4123.PNG)

Please tell me how can I define attributes in notifies resource.

**Comment by shaikkhajaibrahim** [comment]
First your syntax is wrong  https://docs.chef.io/resource_common/#notifications
see interpolation as discussed in the class 

![image](https://user-images.githubusercontent.com/2438317/84262938-2d065a80-ab3c-11ea-8a60-ce6198fec80d.png)
