### ISSUE TITLE
Chef Error while installing multiple packages using custom attributes

### ISSUE THREAD

**Issue by abasimdev** [QT-DevOps/DevOpsIssues#895]
Recipe:
![py_recipe](https://user-images.githubusercontent.com/64391011/84008151-12db4980-a98f-11ea-99af-565a666d59d8.PNG)
Attribute file:
![upload](https://user-images.githubusercontent.com/64391011/84008672-c6dcd480-a98f-11ea-9342-6b115d00db70.PNG)

Error log:
![Error_log](https://user-images.githubusercontent.com/64391011/84008230-28507380-a98f-11ea-8365-70c4e8c11162.PNG)

When I write my resource as below it executes properly:
package %w(python3 python3-pip) do
    action :install
end

But same giving an error while trying with custom attributes.

**Comment by shaikkhajaibrahim** [comment]
you should be defining it as array/list
default['python']['pkg_name'] = ['python3', 'python3-pip']
