### ISSUE TITLE
very silly doubt

### ISSUE THREAD

**Issue by vishwendh105** [QT-DevOps/DevOpsIssues#896]
How a code is integrated when we create CI pipeline??

**Comment by tandrarajesh** [comment]
We will get the code from git by pulling or cloning 
Git pull 
Git clone

**Comment by vishwendh105** [comment]
Can I get an example Jenkins file??

**Comment by shaikkhajaibrahim** [comment]
![image](https://user-images.githubusercontent.com/2438317/84262327-0eec2a80-ab3b-11ea-9f25-6f1c0be4ff93.png)
