### ISSUE TITLE
How do we define Terraform yes/no confirmation in Jenkins pipeline.

### ISSUE THREAD

**Issue by Jagannath92** [QT-DevOps/DevOpsIssues#897]

**Comment by Jagannath92** [comment]
May I know where the state file is created or provider is download when terraform scripts build from jenkins, source in git.
![image](https://user-images.githubusercontent.com/58015684/84218577-5ac3b300-aaec-11ea-928f-488dddc24e5c.png)
![image](https://user-images.githubusercontent.com/58015684/84218619-6f07b000-aaec-11ea-9938-5c58000bd518.png)

**Comment by Jagannath92** [comment]
![image](https://user-images.githubusercontent.com/58015684/84218723-9b233100-aaec-11ea-8041-53e70fabddfc.png)

**Comment by Jagannath92** [comment]
![image](https://user-images.githubusercontent.com/58015684/84218782-c279fe00-aaec-11ea-84d2-b3a67ace3780.png)

**Comment by shaikkhajaibrahim** [comment]
Please have a look at -auto-approve argument in terraform apply --help
