### ISSUE TITLE
In packer I am able to give ami-name but can you say how to give Name

### ISSUE THREAD

**Issue by Jagannath92** [QT-DevOps/DevOpsIssues#898]
![Capture](https://user-images.githubusercontent.com/58015684/84159770-0e945680-aa8b-11ea-9b00-b2fd2d4e5305.PNG)

**Comment by shaikkhajaibrahim** [comment]
That is tag not name 
if you want to add tags

![image](https://user-images.githubusercontent.com/2438317/84262072-94230f80-ab3a-11ea-9f70-fa1fb0623eeb.png)

**Comment by Jagannath92** [comment]
![image](https://user-images.githubusercontent.com/58015684/84338677-536adb00-abba-11ea-9aa2-cf612b9c274a.png)

**Comment by Jagannath92** [comment]
Sir,I have tried with tags. can you please help.
![image](https://user-images.githubusercontent.com/58015684/84338970-0e937400-abbb-11ea-96c3-f511b313269e.png)
