### ISSUE TITLE
Unable to query ami using datasource in terraform

### ISSUE THREAD

**Issue by Jagannath92** [QT-DevOps/DevOpsIssues#899]
data "aws_ami" "example" {
  executable_users = [5666197xxxx]
  owners           = [5666197xxxx]
  filter {
    name   = "name"
    values = ["example/images/packer*"]
  }
  filter {
    name   = "root-device-type"
    values = ["ebs"]
  }
  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

resource "aws_instance" "abc" {
    count = 1
    ami = "data.aws_ami.example.id"
    instance_type = "t2.micro"
    tags            = {
        Name        = "My Ec2 ${count.index}"
    }

}

**Comment by Jagannath92** [comment]
![image](https://user-images.githubusercontent.com/58015684/84209677-5be8e600-aad4-11ea-8348-cb8fcc62d3a5.png)

**Comment by Jagannath92** [comment]
![image](https://user-images.githubusercontent.com/58015684/84209741-889cfd80-aad4-11ea-9d4c-147a62160c3e.png)

**Comment by shaikkhajaibrahim** [comment]
Can you use build query aws ec2 describe-images using filter section and use the same arguments in data source. 

Read full docs sir  refer https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-images.html
