### ISSUE TITLE
Jenkins(Deploy game-of-life on tomcat)

### ISSUE THREAD

**Issue by samjoel777** [QT-DevOps/DevOpsIssues#9]
![tomcat testcase](https://user-images.githubusercontent.com/37773567/40552409-305c1bf6-605d-11e8-9120-cff630c6f21c.PNG)

**Comment by samjoel777** [comment]
Sir,we can use scp jenkins:gameoflife-web/target/gameoflife.war jenkins:/var/lib/tomcat8/webapps/.
Can i have the output log of your tomcat build.

**Comment by sanjaysureshmv** [comment]
scp syntax: scp <source_path> user@<ip_of_tomcatserver>:<destination_path>
my config: scp $ArtifactLocation jenkins@$tomcat_server:/var/lib/tomcat8/webapps/'
where $ArtifactLocation= /var/lib/jenkins/workspace/gameoflife\ project/gameoflife- 
                                         web/target/gameoflife.war 
$tomcat_server=13.127.53.100
make sure you pass these parameters from the upstream project

**Comment by vijaybhaskarreddyy** [comment]
check your syntax scp
like @sanjaysureshmv  as said.

**Comment by samjoel777** [comment]
thanks guys worked
i refer not giving names in jenkins items(New item) with spaces(i.e game of life),suggested game-of-life
