### ISSUE TITLE
While installing chef using chefdk in CLI facing the below issue

### ISSUE THREAD

**Issue by Neerajvarma** [QT-DevOps/DevOpsIssues#90]
C:\WINDOWS\system32>choco install chefdk
Chocolatey v0.10.11
Installing the following packages:
chefdk
By installing you accept licenses for the packages.
[NuGet] An error occurred while loading packages from 'https://chocolatey.org/api/v2/': Unable to connect to the remote server
chefdk not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - chefdk - chefdk not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.
![issue](https://user-images.githubusercontent.com/42227450/43875683-0579faf6-9baf-11e8-95e8-6be66dee0961.PNG)

**Comment by shaikkhajaibrahim** [comment]
It seems to me as internet connectivity issue.

Can you retry on powershell in Administrator mode
________________________________

**Comment by shaikkhajaibrahim** [comment]
Any updates?

**Comment by Neerajvarma** [comment]
Hello,

sir... Thanks for response...issue resolved while i tried to reinstall
using the chocolaty
