### ISSUE TITLE
May I know where the state file is created or provider downloaded when terraform scripts build from jenkins, source in git.

### ISSUE THREAD

**Issue by Jagannath92** [QT-DevOps/DevOpsIssues#901]
![image](https://user-images.githubusercontent.com/58015684/84340351-26202c00-abbe-11ea-9d1b-ca8d566247d4.png)

**Comment by srmanikanta** [comment]
terraform show is used to inspect a state file or plan 
syntax is `terraform show options plan path or state file path`
you have to provide path of state file or plan.
example 
`terraform show -json ./plan_path`

if it was  useful please close the issue.

**Comment by Jagannath92** [comment]
Can you say whenever terraform script run from jenkins where the state file is stored. on apply or plan where the state file is created. Thankyou

**Comment by srmanikanta** [comment]
this is the reference for terraform in ci/cd [click here](https://directdevops.blog/2020/01/07/devops-classroom-series-06-jan-2020-terraform/)
terraform state default location is local and in team it is stored in remote such as s3 and plan  will also stored in local or remote.

**Comment by Jagannath92** [comment]
if source present in git, In jenkins script - terraform plan -out planfile.plan  .  
where the plan file is stored or created. I haven't seen any plan files are state files created when I executed the terraform scripts from jenkins

**Comment by Jagannath92** [comment]
if backends are setup than it will be stored in s3 incase backends are not setup than where state files and plan files stored.

**Comment by srmanikanta** [comment]
plan is created by with your own then only it stored in some name on your current directory where terraform directory is initialized.
 if you are not set backend,state is stored default in your local terraform directory.

**Comment by Jagannath92** [comment]
sorry, my question is if we call terraform scripts from jenkins where state files are stored. I can explain issue pls call me. 

Thanks
