### ISSUE TITLE
please correct if any thing wrong in script: Unable to query ami using datasource in terraform, tried query from aws ec2 describe-images worked but from datasource not able to query

### ISSUE THREAD

**Issue by Jagannath92** [QT-DevOps/DevOpsIssues#902]
got some output from aws ec2 describe-images 
![image](https://user-images.githubusercontent.com/58015684/84377143-c9ddfc00-abff-11ea-90b1-6885faffa577.png)

but from below script not

data "aws_ami" "example" {
executable_users = [5666197xxxx]
owners = [5666197xxxx]
filter {
name = "name"
values = ["example/images/packer*"]
}
filter {
name = "root-device-type"
values = ["ebs"]
}
filter {
name = "virtualization-type"
values = ["hvm"]
}
}

resource "aws_instance" "abc" {
count = 1
ami = "data.aws_ami.example.id"
instance_type = "t2.micro"
tags = {
Name = "My Ec2 ${count.index}"

**Comment by Jagannath92** [comment]
tried with below syntax too - not worked.
ami = "data.aws_ami.example.selected.id"
ami = "data.aws_ami.example.name"
ami = "data.aws_ami.example.selected.name"

**Comment by srmanikanta** [comment]
try to use 
ami = data.aws_ami.example.image_id

**Comment by Jagannath92** [comment]
I have tried with give input but same result. Thankyou

**Comment by srmanikanta** [comment]
try this
```
data "aws_ami" "example" {
owners = [ self ]
filter {
name = "tag:<tagkeyname>"
values = [" <tagvalues>"]
}
}

resource "aws_instance" "abc" {
count = 1
ami = "data.aws_ami.example.id"
instance_type = "t2.micro"
tags = {
Name = "My Ec2 ${count.index}"
}
```
Note : please mention tag keyname and tagvalue.

**Comment by Jagannath92** [comment]
tried now error at run time. 
![image](https://user-images.githubusercontent.com/58015684/84556143-6f978500-ad3e-11ea-89ff-5c0ba9df3991.png)

![image](https://user-images.githubusercontent.com/58015684/84556124-58f12e00-ad3e-11ea-8f3e-e6c7185185d9.png)

resource "aws_instance" "abc" {
    count = 1
//    ami = "ami-0ee6ba45ed0572e6e"
    ami = "data.aws_ami.example.image_id"
    instance_type = "t2.micro"
    tags            = {
        Name        = "My Ec2 ${count.index}"
   }}

data "aws_ami" "example" {
owners = [56661974xxxx]
filter {
name = "tag:Name"
values = ["packer"]
}}

Image available with tag:Name value= packer

**Comment by srmanikanta** [comment]
remove double quotes in ami = data.aws_ami.example.image_id or write like this ami = "${data.aws_ami.example.image_id}"

**Comment by Jagannath92** [comment]
I am facing same error. could you please try remotely once. Thanks
