### ISSUE TITLE
Issue while Bootstrapping in latest version of chef

### ISSUE THREAD

**Issue by sujith140** [QT-DevOps/DevOpsIssues#903]
![Annotation 2020-06-13 163959](https://user-images.githubusercontent.com/61341872/84567188-9680a600-ad94-11ea-9774-d8b50d1bb8d1.png)
![2](https://user-images.githubusercontent.com/61341872/84567215-d6e02400-ad94-11ea-8af4-d103aa73e954.png)
Can anyone help me on this?

**Comment by srmanikanta** [comment]
This can happen if you have already boot strapped a node then you download your starter kit again. The previous client.pem is not removed from the node. You need to manually remove this so that authentication can occur.
