### ISSUE TITLE
How to configure application health endpoint on Kubernetes

### ISSUE THREAD

**Issue by sharmatanmaya** [QT-DevOps/DevOpsIssues#905]
I have a springboot application deployed into docker. that container is being manged by kubernetes. sometime the application is runnig out of memory and is down but k8s doesnot have any idea about it. How can i configure k8s to restart my application when the application goes down?

**Comment by singaravellu** [comment]
use liveliness and readiness probe and configure in manifest file

**Comment by sharmatanmaya** [comment]
I have configured liveness and readiness for a /healthcheck custom endpoint in a spring boot application controller, which return 200/500 http error depending upon the api status. WIll it capture for any Out of memory error as well?

**Comment by singaravellu** [comment]
you can also configure the resource limits if it exceeds the specified limits it should restart.
