### ISSUE TITLE
Anyone completed Challenges

### ISSUE THREAD

**Issue by rpkoya** [QT-DevOps/DevOpsIssues#906]
Hi,
If any one completed challenges, please let me know i have some queries

Regards,
Ravindra

**Comment by singaravellu** [comment]
yeah i am facing getting issue while building openmrs-core as and openmrs-standalone 
![image](https://user-images.githubusercontent.com/32475854/90238793-1e8e3500-de44-11ea-86f5-1d88557561af.png)
