### ISSUE TITLE
Getting this error while doing terraform remote state s3 

### ISSUE THREAD

**Issue by seshi7** [QT-DevOps/DevOpsIssues#909]
![t1](https://user-images.githubusercontent.com/38456695/85433791-96f21b80-b5a2-11ea-966e-cc218500c05b.PNG)

And the terraform script is 
![t2](https://user-images.githubusercontent.com/38456695/85434016-00722a00-b5a3-11ea-9571-bb4399832d90.PNG)

and also created dynamodb_table 
![t3](https://user-images.githubusercontent.com/38456695/85434057-1384fa00-b5a3-11ea-966b-387c65201636.PNG)

**Comment by srmanikanta** [comment]
give admin access to IAM user and then try.
