### ISSUE TITLE
Chef Bootstrap. Authenticationfaild. asking password

### ISSUE THREAD

**Issue by achyuthreddy69** [QT-DevOps/DevOpsIssues#91]
![untitled](https://user-images.githubusercontent.com/41581775/43889743-9cee1cf4-9be2-11e8-9c82-c2dd265e10b3.jpg)

**Comment by shaikkhajaibrahim** [comment]
do you have chef.pem in C:\users\manoj\downloads\chef-repo ?
________________________________

**Comment by kuncham405** [comment]
Hi,

Am getting the same issue.

 i have the file chef.pem in C:\users\Ckuncham\downloads\chef-repo file, but still it is showing same error

**Comment by Jagadeeshw** [comment]
knife bootstrap 18.222.254.158(Pubip) -i chef.pem -x ubuntu -N mychef --sudo
# try this or copy .pem file to that particular path (like --\--- \Downloads\che-repo\chef.pem)

**Comment by kuncham405** [comment]
Now am getting another 
ERROR: Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout

**Comment by shaikkhajaibrahim** [comment]
Is the 22 port opened on that machine for every one

**Comment by chagamreddy** [comment]
Authentication failed for user ubuntu@ec2-52-70-135-40.compute-1.amazonaws.com@ec2-52-70-135-40.compute-1.amazonaws.com (Net::SSH::AuthenticationFailed)
ERROR: Net::SSH::AuthenticationFailed: Authentication failed for user ubuntu@ec2-52-70-135-40.compute-1.amazonaws.com@ec2-52-70-135-40.compute-1.amazonaws.com

sir it was asking password i am simply press the ENTER then it will showing like this ERROR.
yes sir my port number is 22 for this machine

**Comment by shaikkhajaibrahim** [comment]
Is direct SSH working

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chagamreddy** [comment]
tanq sir it will working

**Comment by kuncham405** [comment]
Hi Sir,

Is it working, i restart the virtual machine ( Azure )

Thank your information

**Comment by achyuthreddy69** [comment]
I got it, sir.
