### ISSUE TITLE
docker container status

### ISSUE THREAD

**Issue by neelaraokala** [QT-DevOps/DevOpsIssues#910]
**FROM openjdk:8
LABEL author="neelarao"
RUN wget https://referenceappkhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar
EXPOSE 8080
CMD ["java", "-jar", "spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar"]**

when running a container by using above dockerfile, 
contianer status showing as "up" 

![container up 2020-06-25 161513](https://user-images.githubusercontent.com/60516092/85706831-3842b400-b700-11ea-8472-6f4099be400c.png)

but while running container from below dockerfile, 

**FROM openjdk:8
LABEL author="neelarao"
RUN wget https://github.com/spring-projects/spring-petclinic.git
EXPOSE 8080
CMD ["java", "-jar", "spring-petclinic.git"]**
![container_exited 2020-06-25 161337](https://user-images.githubusercontent.com/60516092/85706916-51e3fb80-b700-11ea-92e5-89659cd88089.png)

container status showing as "exited" 

is there anything wrong in CMD instruction?

**Comment by neelaraokala** [comment]
my self, i'm resolved.

**Comment by yagnasivasai** [comment]
> my self, i'm resolved.

How did you resolve?

**Comment by neelaraokala** [comment]
in the second dockerfile, the cloned link was  **https://github.com/spring-projects/spring-petclinic.git**,  it is just developed app, in further we need to build it then send it to S3 bucket or Artifactory, and then we have to clone it from their (S3 or artifactory).

**Comment by yagnasivasai** [comment]
> in the second dockerfile, the cloned link was  **https://github.com/spring-projects/spring-petclinic.git**,  it is just developed app, in further we need to build it then send it to S3 bucket or Artifactory, and then we have to clone it from their (S3 or artifactory).

Thank you
