### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by YeshwanthReddyChalla** [QT-DevOps/DevOpsIssues#915]
While creating free style project to clone the code (springpetclinic) from git (https://github.com/spring-projects/spring-petclinic.git)
I am facing the below issue
![Jenkins1](https://user-images.githubusercontent.com/53093655/86500926-4eacd780-bdb2-11ea-9cf0-74db54901a0c.png)

Console Output
Started by user Yeshwanth
Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/springpetclinic
No credentials specified
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/spring-projects/spring-petclinic.git # timeout=10
Fetching upstream changes from https://github.com/spring-projects/spring-petclinic.git
 > git --version # timeout=10
 > git fetch --tags --progress -- https://github.com/spring-projects/spring-petclinic.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
 > git rev-parse origin/master^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Finished: FAILURE

**Comment by singaravellu** [comment]
fork the repo to your github account and try

**Comment by YeshwanthReddyChalla** [comment]
Thank you

**Comment by singaravellu** [comment]
please close the issue if resolved

**Comment by YeshwanthReddyChalla** [comment]
closed
