### ISSUE TITLE
K8s: Unable to install  Docker CE 

### ISSUE THREAD

**Issue by nrao0221** [QT-DevOps/DevOpsIssues#916]
Steps to reproduce:

1. Created master and worker on AWS Ubuntu(t2 large)
2. I have connected to master and ran the below commands
1. Install packages to allow apt to use a repository over HTTPS
  apt-get update && apt-get install -y \
   apt-transport-https ca-certificates curl software-properties-common gnupg2 

2. Add Docker’s official GPG key:
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

3. When I ran Docker CE , I am getting bellow error

apt-get update && apt-get install -y \
  containerd.io=1.2.13-2 \
  docker-ce=5:19.03.11~3-0~ubuntu-$(lsb_release -cs) \
  docker-ce-cli=5:19.03.11~3-0~ubuntu-$(lsb_release -cs)

E: Unable to locate package containerd.io
E: Couldn't find any package by glob 'containerd.io'
E: Couldn't find any package by regex 'containerd.io'
E: Version '5:19.03.11~3-0~ubuntu-xenial' for 'docker-ce' was not found
E: Unable to locate package docker-ce-cli

Could you please suggest me to proceed

Please find the attached screen shot for reference
![DockerCEerror](https://user-images.githubusercontent.com/66910796/86514731-565f9100-be31-11ea-9a44-ff7418b9bad1.jpg)

**Comment by ramjagadeeshkumar** [comment]
This is 5 
# Add the Docker apt repository:
add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) \
  stable"



References link https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker

**Comment by singaravellu** [comment]
hi nrao please reply if possible otr if issue is resolved close this

**Comment by srmanikanta** [comment]
right now your switched as root user but you have ubuntu user's home directory so change first user home directory by executing the this command `cd ~` and then execute your installation commands.
