### ISSUE TITLE
I we have 100 developers so can we have 100 feature branches under the development branch. pls. explain this senario

### ISSUE THREAD

**Issue by hairavi10** [QT-DevOps/DevOpsIssues#919]

**Comment by srmanikanta** [comment]
if you have 100 developers  no need to create 100 feature branches it depends on application features, in one feature branch can be used  different developers.

**Comment by shaikkhajaibrahim** [comment]
Yes but feature branches will not be per developer, it will per feature. 
Some organizations prefer having feature branches in the local repos of dev not in remote
