### ISSUE TITLE
Unable to install Apache Tomcat

### ISSUE THREAD

**Issue by vishwendh105** [QT-DevOps/DevOpsIssues#920]
Hello,QT,
I am trying to install the Apache Tomcat server using the documentation of Digital Ocean Documentation {https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-8-on-ubuntu-16-04} and i am losing at the point of updatig my service file and exiting my service file.
Please help me!!

**Comment by badaltechiepi** [comment]
@vishwendh105 Can you tell what is the issue which you are getting.

**Comment by srmanikanta** [comment]
please post related error screenshot.

**Comment by vishwendh105** [comment]
Hello, Sorry QT for the delay 
Here is the screen shot of the error message and trying different commands to save and exit the file in terminal commands like :wq,^x,^b,
![Tomcat1](https://user-images.githubusercontent.com/51240081/87849423-2969ae80-c906-11ea-9f9a-e2f83fae6360.png)
^X,^B etc. Please let me know the correct command.

**Comment by srmanikanta** [comment]
check your installed version of tomcat and then try like this `sudo systemctl start tomcatx` where x is your tomcat version number.

**Comment by vishwendh105** [comment]
I Had tried that command but it shows tomcat is NOT FOUND

**Comment by srmanikanta** [comment]
you are executed some commands for tomcat installation so please post tomcat installation commands here i will tell you which version of tomcat your are installed.
