### ISSUE TITLE
Kubernetes ImagePullBackoff

### ISSUE THREAD

**Issue by tarunkumar110695** [QT-DevOps/DevOpsIssues#921]
![yaml file](https://user-images.githubusercontent.com/51618597/87441008-3a69a580-c610-11ea-9486-e8272b09096a.PNG)
![docker image](https://user-images.githubusercontent.com/51618597/87441234-83b9f500-c610-11ea-9f74-d4e31b2b2ab1.PNG)
![error](https://user-images.githubusercontent.com/51618597/87441243-84eb2200-c610-11ea-95ed-284535b45086.PNG)

**Comment by tarunkumar110695** [comment]
Hi All,

I'm trying to run my own image on the k8s cluster i'm getting the following error please help. the image is in my local machine, do i need add any addons ?

**Comment by srmanikanta** [comment]
follow this link [click here](https://stackoverflow.com/questions/37302776/what-is-the-meaning-of-imagepullbackoff-status-on-a-kubernetes-pod) for reference

**Comment by singaravellu** [comment]
is the image is in k8's cluster or in your local machine

**Comment by tarunkumar110695** [comment]
the image is in my master node of K8s cluster

**Comment by shaikkhajaibrahim** [comment]
https://managedkube.com/kubernetes/k8sbot/troubleshooting/imagepullbackoff/2019/02/23/imagepullbackoff.html
