### ISSUE TITLE
jenkins issue

### ISSUE THREAD

**Issue by Surendra-410** [QT-DevOps/DevOpsIssues#922]
while giving the sour
![jenkins error](https://user-images.githubusercontent.com/54952626/87781416-43e05100-c84e-11ea-95ed-edf22a0ae240.PNG)
cecode repo we are getting the following issue..

**Comment by srmanikanta** [comment]
please post your error screenshot properly

**Comment by singaravellu** [comment]
please fork the project to your github account and try

**Comment by singaravellu** [comment]
hi surendra please reply or else close this issue if resolved
