### ISSUE TITLE
 when i run sudo apt-get update this error was happened (101: Network is unreachable)

### ISSUE THREAD

**Issue by praveenkumar57** [QT-DevOps/DevOpsIssues#925]
![Screenshot (105)](https://user-images.githubusercontent.com/56515888/88315765-61248c00-cd34-11ea-855a-ba29cad7880b.png)

**Comment by venugopalkatukam** [comment]
try this https://ubuntuforums.org/showthread.php?t=2387453&p=13749884#post13749884

**Comment by praveenkumar57** [comment]
Hi...
I tried those commands you mentioned in the link but it won't work

**Comment by srmanikanta** [comment]
first check the network connection, your instance is connected to internet or not and open all traffic in security group.

**Comment by praveenkumar57** [comment]
Hi ...
I run ping google.com its working and I opened all traffic in the security group but I run Sudo apt-get update same error has happened
![Screenshot (121)](https://user-images.githubusercontent.com/56515888/90368826-52599c80-e088-11ea-8565-73956b427f43.png)
![Screenshot (122)](https://user-images.githubusercontent.com/56515888/90368832-54bbf680-e088-11ea-8fd1-7ab89569fd46.png)

. I do not know what could have happened. I have googled applied some fixes but nothing seems to work

**Comment by srmanikanta** [comment]
hi praveenkumar, are you change anything in /etc/apt/sources.list or add any repository into that file 
If it is yes the error is related to your repository, please check if anything is wrong in your repository file.

**Comment by praveenkumar57** [comment]
I am trying to install artifactory that's why I added some configuration. Then I tried to  Sudo apt-get update that error has happened

**Comment by shaikkhajaibrahim** [comment]
This is bcoz apt sources is having some link which is not reachable
