### ISSUE TITLE
DOCKER BUILD IMAGES -QUERY

### ISSUE THREAD

**Issue by SVMK1009** [QT-DevOps/DevOpsIssues#926]
this is my sample dockerfile content:

FROM tomcat:10.0.0-M7-jdk8-openjdk
MAINTAINER vMC
ADD jenkins.war /usr/local/tomcat/webapps/jenkins.war
WORKDIR /opt/vmc/
EXPOSE 8080
CMD ["catalina.sh", "run"]

this is the content im getting while trying to build the image:
ubuntu@ip-172-31-3-193:/opt/vmc/images$ docker image build .
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM tomcat:10.0.0-M7-jdk8-openjdk
 ---> aaf96e87b224
Step 2/5 : MAINTAINER vMC
 ---> Using cache
 ---> e4ff1a829d8f
Step 3/5 : ADD jenkins.war /usr/local/tomcat/webapps/jenkins.war
**ADD failed: stat /var/lib/docker/tmp/docker-builder860780445/jenkins.war: no such file or directory**

**Comment by ramjagadeeshkumar** [comment]
Add failed due path error or wrong path 
Please check your machine  
Jenkins war available are not
Enter pwd to check path of the file location

**Comment by SVMK1009** [comment]
> Add failed due path error or wrong path
> Please check your machine
> Jenkins war available are not
> Enter pwd to check path of the file location

in manual , i tried pulling the  tomcat image , runnig the image ans inspected the image with he process id
even there it shows the working drectory as /usr/local/tomcat 
but while trying to access the folder, it shows , no such directory is available::
looks like some fishy
PLEASE SOMEONE HELP ME IN THIS

**Comment by singaravellu** [comment]
which version of tomcat image you have pulled try using tomcat:9 you can get path

**Comment by puru7791** [comment]
ADD instruction contains _src_ or URL and _dest_, if u don't specify absolute path at src, it looks at Current directory. check once
WORKDIR means Default working directory of Container eg: when u hit _docker container exec -it <cont. Id>_. it goes to default directory whatever u specified path in WORKDIR.
