### ISSUE TITLE
unable to see the apache server page after sucessfully installing it on ansible server

### ISSUE THREAD

**Issue by sonu720** [QT-DevOps/DevOpsIssues#928]
![issue3](https://user-images.githubusercontent.com/59817914/89126689-4ce74880-d505-11ea-80c0-17eb7740f13f.png)

**Comment by srmanikanta** [comment]
hi sonu,
once you install the apache2  and take node public ip then open your browser  `http://<publicip:80>`
Note: in security group ensure port 80 is open or not.

**Comment by 13185198** [comment]
hi,
once you done with apache2 installation follow these steps:
1.Check status to see whether Apache2 is active with the command: $ sudo service apache2 status.
2.Apache2 runs on port 80( check security group --> inbound rule -->add rule with port 80)
3.copy public ip address of machine(where you have installed Apache2) n paste it on browser.

**Comment by sonu720** [comment]
hi,
After installing i am opening with port 80 but it showing the same
1.Check status to see whether Apache2 is active with the command: $ sudo service apache2 status. when i execute this command it shows as following
![issue3_](https://user-images.githubusercontent.com/59817914/89276289-1aeaf900-d661-11ea-824d-4cf6fd7df7c4.png)

**Comment by srmanikanta** [comment]
Please Share your playbook

**Comment by sonu720** [comment]
Hi, 
Issue got resolved as I changed security group. 
Thank u
