### ISSUE TITLE
Can we direct ansible to use dnf repository instead yum in CentOs18

### ISSUE THREAD

**Issue by cmanduva** [QT-DevOps/DevOpsIssues#929]
While installing multiple packages we have used the **package** module to install packages through yum and apt in centos and Ubuntu. However, while installing in CentOs 18 we need to use the dnf package repository instead the yum, so while using the package module can we direct playbook to use dnf module.

Please suggest.

**Comment by srmanikanta** [comment]
you will write direct playbook for centos machine but you have to use when condition.
