### ISSUE TITLE
creating subnet with perticular az

### ISSUE THREAD

**Issue by vdileepdevops** [QT-DevOps/DevOpsIssues#93]
can i create subnet wtth perticular az with in the vpc,using cli

**Comment by shaikkhajaibrahim** [comment]
aws ec2 create-subnet --availability-zone <zonecode> --vpc-id <vpc-id>

zonecode = us-west-2a

Refer https://docs.aws.amazon.com/cli/latest/reference/ec2/create-subnet.html
create-subnet — AWS CLI 1.15.71 Command Reference<https://docs.aws.amazon.com/cli/latest/reference/ec2/create-subnet.html>
Description¶. Creates a subnet in an existing VPC. When you create each subnet, you provide the VPC ID and the IPv4 CIDR block you want for the subnet.
docs.aws.amazon.com


________________________________
