### ISSUE TITLE
Java Version Change in Windows Node

### ISSUE THREAD

**Issue by adamalli01** [QT-DevOps/DevOpsIssues#930]
Hi All, 

I have done setup from Jenkins Master to Windows node via SSH and I have set the java path in jenkins node too. And it working properly. But when my java version is upgrading in Windows node. Then jenkins slave is disconnecting automatically and its affected my job too. 

How to handle this type of situation. 

Khaja Sir@Could you please help me on this issue.

**Comment by srmanikanta** [comment]
as you said you are set the path in jenkins node and you are upgrading the java, for my suggestion is upgrade the java path is jenkins node because you are set the path, paths are not updated automatically.

**Comment by adamalli01** [comment]
Al are the windows Azure machine . In our company couple of moth java  upgrading is going one  due to that its deleting the old java and in place of old java its putting new java. just like jdk_251 or jdk_261 due to that Jenkins node got disconnected. And its affecting the night build job.

**Comment by shaikkhajaibrahim** [comment]
Sir please set the explicit export statement (set JAVA_HOME) in your jenkins job if thats the case
