### ISSUE TITLE
Is retry option is available for downloading any package from git repo

### ISSUE THREAD

**Issue by adamalli01** [QT-DevOps/DevOpsIssues#931]
Hi All, 

Due to some latency issue my package is not downloading from Azure Git repo in my Jenkins job. I am facing this issue as intermittent. 

Is there any option . So that i can put retry option in Jenkins job.

**Comment by srmanikanta** [comment]
use poll scm in jenkins job

**Comment by adamalli01** [comment]
i can't use poll scm. it will run who job once again

**Comment by srmanikanta** [comment]
hi adamalli, please refer this link [Click Here](https://stackoverflow.com/questions/44569686/how-to-re-build-task-on-jenkins-until-build-succeed#:~:text=To%20retry%20a%20Jenkins%20job%2C%20you%20can%20use%20the%20Naginator%20plugin.&text=Simply%20install%20the%20plugin%2C%20and,after%20the%20time%20you%20specified.)

I think it is helpful to you.

**Comment by shaikkhajaibrahim** [comment]
Why dont you verify the check sum, if not re download/pull using script
