### ISSUE TITLE
while executing Ansible-playbook  facing the below issue could anyonehelp

### ISSUE THREAD

**Issue by singaravellu** [QT-DevOps/DevOpsIssues#932]
![image](https://user-images.githubusercontent.com/32475854/90095968-ba8a4480-dd4f-11ea-9826-b6ab7fbc55e4.png)
here is the inventory 
![image](https://user-images.githubusercontent.com/32475854/90096005-d5f54f80-dd4f-11ea-90b7-dc234c9481c7.png)
here is the playbookfile
![image](https://user-images.githubusercontent.com/32475854/90096043-eb6a7980-dd4f-11ea-99b8-6db5ecc2c376.png)

**Comment by ghost** [comment]
Make sure ansible user have sudo permisions on remote host
edit /etc/sudoers file add entry for anisble user

**Comment by singaravellu** [comment]
i have added user to sudo group  by executing the sudo usermod -aG sudo ansible

**Comment by ghost** [comment]
By adding user to sudo group using usermod user will ask for password when we try to become sudo. so we need user which has sudo permissions and password should not be asked. 
add `<user> ALL:ALL NOPASSWD:ALL` entry in /etc/sudoers file

**Comment by singaravellu** [comment]
ok thank you  it's working  <user> ALL=(ALL:ALL) NOPASSWD:ALL
