### ISSUE TITLE
while building openmrs-standalone application getting below eror

### ISSUE THREAD

**Issue by singaravellu** [QT-DevOps/DevOpsIssues#933]
![image](https://user-images.githubusercontent.com/32475854/90238023-e63a2700-de42-11ea-820d-c8c979e50976.png)

**Comment by srmanikanta** [comment]
try to run mvn command as jenkins user

**Comment by singaravellu** [comment]
tired with jenkins user as well

**Comment by srmanikanta** [comment]
hi, singaravellu please call mynumber once

**Comment by singaravellu** [comment]
unable to reach you

**Comment by shaikkhajaibrahim** [comment]
If the machine is of size t2.micro then you might have issue
