### ISSUE TITLE
Error: multiple VPCs matched; use additional constraints to reduce matches to a single VPC

### ISSUE THREAD

**Issue by tabrez78** [QT-DevOps/DevOpsIssues#936]
trying to use aws_security_group data source in creation a ec2 instance with the following code

data "aws_security_group" "mysecuritygroup"{
     filter {
    name   = "vpc-id"
    values = ["vpc-0b3d99a0ec731b0cb"]
  }
  filter {
    name   = "group-name"
    values = ["sg-0fef2d07133290d9f"]
  }

}
resource "aws_instance" "myec2"{
    ami = "ami-0bbe28eb2173f6167"
    instance_type = "t2.micro"
    key_name = "terraform"
    vpc_security_group_ids = [data.aws_security_group.mysecuritygroup.id]
    associate_public_ip_address = "true"
    
    

}

**Comment by tabrez78** [comment]
sir how do i use data source for aws_vpc because its taking the default vpc

**Comment by shaikkhajaibrahim** [comment]
If you get multiple vpcs matched, then use index
