### ISSUE TITLE
sharing the data with the EFS, NFS?

### ISSUE THREAD

**Issue by seshi7** [QT-DevOps/DevOpsIssues#937]
Hi Team,

If we define the Docker volume in the docker compose file is it possible to share the data with the EFS, NFS?

If it is possible how can we achieve this can some one help on this.

Thanks

**Comment by srmanikanta** [comment]
hi seshi, it is possible to share the volumes through efs or nfs please refer this link [Click Here](https://dzone.com/articles/mount-aws-efs-nfs-or-cifssamba-volumes-in-docker)

**Comment by seshi7** [comment]
Okay 
Thank you
