### ISSUE TITLE
spc

### ISSUE THREAD

**Issue by maheshunicorn** [QT-DevOps/DevOpsIssues#939]
Hey,

Unable to download spring petclinic from this location, getting below error:

wget https://learningspcfromqt.s3.us-east-2.amazonaws.com/spring-petclinic.jar
--2019-12-19 12:08:46-- https://learningspcfromqt.s3.us-east-2.amazonaws.com/spring-petclinic.jar
Resolving learningspcfromqt.s3.us-east-2.amazonaws.com (learningspcfromqt.s3.us-east-2.amazonaws.com)... 52.219.84.56
Connecting to learningspcfromqt.s3.us-east-2.amazonaws.com (learningspcfromqt.s3.us-east-2.amazonaws.com)|52.219.84.56|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-12-19 12:08:46 ERROR 404: Not Found.

**Comment by srmanikanta** [comment]
check the bucket is exist or not

**Comment by maheshunicorn** [comment]
this is my bucket url https://spc9.s3-us-west-2.amazonaws.com/spring-petclinic.jar

**Comment by srmanikanta** [comment]
hi mahesh, please change the bucket permission as public access
