### ISSUE TITLE
I tried this chef code, but 'welcome to chef' is not showing in browser

### ISSUE THREAD

**Issue by Mu6alik6ishnan** [QT-DevOps/DevOpsIssues#94]
apt_update 'update packages' do
  action :update
end

file '/home/ubuntu/message.txt' do
  content 'welcome to chef.'
  action :create
end

apt_package 'apache2 installation' do
  package_name 'apache2'
  action :install
end

file '/var/www/html/index.php' do
  content 'welcome to chef.'
  action :create
end

**Comment by shaikkhajaibrahim** [comment]
index.html not PHP

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by prakkug** [comment]
same issue ...not able to see the message in the browser 
apt_update 'update packages' do
  action :update
end
file '/home/ubuntu/message.txt' do
  content 'Welcome to Chef !!'
  action :create
end

apt_package 'install apache' do
  package_name 'apache2'
  action :install
end
file '/var/www/html/index.html' do
  content 'Welcome to Chef !!'
  action :create
end
service 'restart apache' do
  service_name 'apache2'
  action :restart
end

**Comment by shaikkhajaibrahim** [comment]
Is port 80 opened in security group

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Mu6alik6ishnan** [comment]
Yes in security group port 80 is opened but same issue...'welcome to chef' is not showing

**Comment by prakkug** [comment]
After port 80, it worked for me

**Comment by mani5a3** [comment]
please post with screen shorts and someone is creating cookbooks outside of cookbooks folder  so please 
 that's why post with  screen shots
