### ISSUE TITLE
Getting Error while uploading the cookbook through berks

### ISSUE THREAD

**Issue by cmanduva** [QT-DevOps/DevOpsIssues#941]
I have created the cookbook using the -b option (chef generate cookbook -b lamp), when I am running the berks install I am getting the below message, anyone faced the same if yes please do suggest me to mitigate.

PS C:\Users\cmanduva\Downloads\chef-starter\chef-repo> berks install
No Berksfile or Berksfile.lock found at 'C:/Users/cmanduva/Downloads/chef-starter/chef-repo'!

Cookbook Generation:
PS C:\Users\cmanduva\Downloads\chef-starter\chef-repo> berks install
No Berksfile or Berksfile.lock found at 'C:/Users/cmanduva/Downloads/chef-starter/chef-repo'!

**Comment by srmanikanta** [comment]
hi cmanduva, rightnow you are in chef-repo folder, just change the path to your cookbook and then try.
hope this is useful to you, if not update the issue.
