### ISSUE TITLE
getting below error while installing chocolatey

### ISSUE THREAD

**Issue by swathiraos** [QT-DevOps/DevOpsIssues#942]
pls resolve my issue.

![error](https://user-images.githubusercontent.com/39555063/91876892-e471bf80-ec9a-11ea-9804-3c3e53e81227.PNG)

**Comment by srmanikanta** [comment]
are you run this command in windows 7 if yes first in first update the .net frame version and then update the powershell version then try with this command. or download chefdk by using this link [click here](https://packages.chef.io/files/stable/chefdk/2.0.28/windows/2008r2/chefdk-2.0.28-1-x86.msi)

**Comment by swathiraos** [comment]
Thank you. resolved the issue.
