### ISSUE TITLE
kitchen converge issue

### ISSUE THREAD

**Issue by puneeth29** [QT-DevOps/DevOpsIssues#944]
![kitchen converge](https://user-images.githubusercontent.com/62132819/92080484-450a1500-eddf-11ea-9bde-315ab1438a29.png)

**Comment by srmanikanta** [comment]
hi puneeth, please change the driver name in kitchen.yml file

**Comment by puneeth29** [comment]
i did put the driver as ec2 
![examp](https://user-images.githubusercontent.com/62132819/92210282-0f7f2d80-eeac-11ea-885f-6608b7fa5228.png)


> hi puneeth, please change the driver name in kitchen.yml file

**Comment by puneeth29** [comment]
but still facing the same error
