### ISSUE TITLE
Kitchen Converge Issue

### ISSUE THREAD

**Issue by dhananjay-gajakosh** [QT-DevOps/DevOpsIssues#945]
I did Kitchen converge but it giving error to me "No package is available for tree "

if platform?('ubuntu')
    apt_update 'update packages' do
        ignore_failure true
        action :update
    end
end

utilities = %w(git tree nano)
package utilities do
    action :install
end

When I removed tree from utilities then Test Kitchen is finished.

But When you try this in class on 1st september tree package is install successfully but when I tried for ubuntu it not works for me why ?

**Comment by shaikkhajaibrahim** [comment]
Try manually and see the issue with tree

**Comment by shaikkhajaibrahim** [comment]
Closing as no response
