### ISSUE TITLE
ssh.key

### ISSUE THREAD

**Issue by puneeth29** [QT-DevOps/DevOpsIssues#947]
![ssh key error](https://user-images.githubusercontent.com/62132819/92253214-dadf9600-eeec-11ea-987b-eb84c020ea75.png)
i did mention my ssh_key

**Comment by puru7791** [comment]
Look at this [kitchen.yml](https://docs.chef.io/workstation/config_yml_kitchen/#syntax), u will understand. And follow the exact syntax.
