### ISSUE TITLE
terraform1

### ISSUE THREAD

**Issue by puneeth29** [QT-DevOps/DevOpsIssues#949]
![terraform](https://user-images.githubusercontent.com/62132819/92390468-87fa1e80-f138-11ea-845f-ee9ebc382654.png)
I have my .pem file in my cookbook and still mentioned in kitchen.yaml too

**Comment by srmanikanta** [comment]
you ssh key is not identified by kitchen, so mention path like this `ssh_key: ./terraform1.pem`
