### ISSUE TITLE
softwares are not installing and i dont know what to do next.

### ISSUE THREAD

**Issue by achyuthreddy69** [QT-DevOps/DevOpsIssues#95]
![untitled](https://user-images.githubusercontent.com/41581775/43953149-bff6b3fe-9cb5-11e8-8697-73b82d39b0a4.png)

**Comment by sanjaysureshmv** [comment]
Seems like you have not added the cookbook into the run list. The run list array is not showing any cookbook (Its showing only empty array [ ]). 
Please add the uploaded cookbook to the desired nodes runlist  by editing the runlist, if not already added to the run list. After it when you run sudo chef-client, you can see something like this,
ubuntu@ip-172-31-24-20:/var/www/html$ sudo chef-client 
Starting Chef Client, version 13.10.4
resolving cookbooks for run list: ["first_cook_book"]
Synchronizing Cookbooks:
  - first_cook_book (0.1.4)

**Comment by achyuthreddy69** [comment]
how should I add a cookbook to run list

**Comment by prakkug** [comment]
https://manage.chef.io/
after selecting the node ...Select "Edit Run List" on the left panel and then on the right panel drag your recipes from "Available Recipes" to "Current Run List"

**Comment by achyuthreddy69** [comment]
thank u..
