### ISSUE TITLE
how to download keypair on to your download folder if creating using terraform 

### ISSUE THREAD

**Issue by tabrez78** [QT-DevOps/DevOpsIssues#952]
sir how to i download the keypair on my local download folder while creating it from terraform as it does'nt give any option to download like it does through cli

**Comment by srmanikanta** [comment]
first download the key manually and then use  that key in terraform.
or if you have create your own key follow this [link](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/key_pair)
