### ISSUE TITLE
S3 bucket & War file issue

### ISSUE THREAD

**Issue by Rushikesh9989** [QT-DevOps/DevOpsIssues#953]
Hi sir,
       how can i create a new bucket in S3,how can i get gameoflife.war file and how can i upload that war file into S3 bucket ?

**Comment by srmanikanta** [comment]
hi rushikesh,
have you attend the jenkins classes? and have your attend the aws s3 classes? if not please wait. 
anyway i will tell the procedure please follow and do the steps.
1. take the code of game of life from git
2. install java, maven on your linux and goto your game of life project folder and the execute maven goal `mvn package`
3. once you execute the mvn package then target folder is created in your project folder and goto gameoflife-web folder and then you see a file gameoflife.war
4. install aws cli in your linux machine and configure
5. create a bucket in aws
5. by using aws cli `s3` command you will upload the file to your s3 bucket.
6. once you upload the file to bucket then make it public.
This is the complete procedure for upload the war file to a bucket.

**Comment by Rushikesh9989** [comment]
Tq sir
