### ISSUE TITLE
Class room videos issue 

### ISSUE THREAD

**Issue by BathinaRaman** [QT-DevOps/DevOpsIssues#954]
This is Raman, i am devops student, from fast four days, i am unable to download class videos to my local(laptop), there is no space issue, i have a space in my system, maybe you required my mail-id to verify permissions, this is my mail-id: vramanbabu@gmail.com

**Comment by BathinaRaman** [comment]
i am trying to download from this location https://drive.google.com/drive/folders/1Ch97BoitfVUfJsz0XR0xeGikaXZEbwmR

**Comment by shaikkhajaibrahim** [comment]
Sir this is no the place for administrative issues. Write to quality thought.in@gmail.com
