### ISSUE TITLE
Login error to AWS EC2 instance (Ubuntu)

### ISSUE THREAD

**Issue by prrohith** [QT-DevOps/DevOpsIssues#956]
Hi,

I am trying to do ssh from powershell to my UBUNTU ece2 isntance. I get permission denied for my .pem file.

When i checked online i found that i need to give read permission (0400) to the .pem file.

But chmod 0400 doesn't work, do you the windows powershell commant to give acess?

**Comment by srmanikanta** [comment]
open gitbash and execute the chmod 400 `<yourpemfie>` it is a linux command but it works on gitbash.
once you execute that command you will execute the ssh command from powershell or gitbash.
