### ISSUE TITLE
Not able to connect jenkins port 8080 after installing on ubuntu vm.

### ISSUE THREAD

**Issue by Anju93rajput** [QT-DevOps/DevOpsIssues#957]
Hi Sir,

I'm not able to connect jenkins port 8080 after installing on ubuntu vm. I have checked the ubuntu running with it's public ip addresses. after that only I installed jenkins on ubuntu machine. I have checked Jenkins is successfully installed by command service jenkins status on running vm. 
Could you please let me know why it's not coming up.
http://18.222.209.21:8080 -- trying with this getting sit can't be reached.

thanks,
Anju

**Comment by naresh86** [comment]
Hi Anju,

I also faced the same issue, for this I added new security group rule to the existing rules
https://user-images.githubusercontent.com/8927418/94262212-beb1a080-ff50-11ea-92b0-74d8d3a9a9a1.png

now I am able to access that url.

Thanks
Naresh

**Comment by Anju93rajput** [comment]
Issue got fix with suggested way of Naresh. added custom port of 8080. :)
Thanks Naresh
