### ISSUE TITLE
jenkins passwd

### ISSUE THREAD

**Issue by puneeth29** [QT-DevOps/DevOpsIssues#959]
![jenkins passwd](https://user-images.githubusercontent.com/62132819/94415299-06c40380-019b-11eb-978a-8346bd6c70d7.png)

no matter what I type it's saying wrong and I used the psswd which I gave on UI and didn't work as well

**Comment by puru7791** [comment]
u didn't know jenkins passwd right, try to become a root user and run it.

**Comment by puneeth29** [comment]
I did SU -I 
and SU jenkins and later tried sudo visudo and I got this issue

**Comment by puru7791** [comment]
I got it, but u r trying to switch normal user to root. it might ask password for the normal user. For Jenkins user itself created whenever it is being installed. so u didn't know `Jenkins` passwd right. type `exit` it goes to the root and run `visudo`.

**Comment by shaikkhajaibrahim** [comment]
Hi puneeth, Jenkins is created as part of installation & by default it will not have password, so 
1. Become root user (sudo -i)
2. su jenkins

Best is to try watch linux tutorials for linux user management
