### ISSUE TITLE
Chef: Node not converging after default time

### ISSUE THREAD

**Issue by sanjaysureshmv** [QT-DevOps/DevOpsIssues#96]
Hi,
After uploading the cookbook to the chef server, the node does not converge to the latest version of cookbook which was 0.1.2. In the chef server, the version is showing 0.1.2. Please see the screenshot
![cookbook_version_0 1 2](https://user-images.githubusercontent.com/39335150/43950276-7e8f5bee-9cad-11e8-857a-e395ac60dffc.png)
After the convergence time(default 30 minutes), when I checked the node, apache was not installed. The latest cookbook was not uploaded to the direcotry /var/chef/cache/cookbooks/first_cook_book/recipes. When I did sudo chef-client from the node, I was able to see the index page with specified content
![op](https://user-images.githubusercontent.com/39335150/43950557-36458970-9cae-11e8-87b8-6c1980d52c03.png)
Please clear my following doubts
1. How to know the default convergence period? Is it specified on any config file in client or server?
2 . How can we know if convergence happend ?Is there any way we can find it from either workstation chef server or client? 
3. Why the node was not converged to the latest version of cookbook

**Comment by venkatmamillapalli** [comment]
same doubt for me.Plz give me clarification on this

**Comment by shaikkhajaibrahim** [comment]
Please have patience, I will cover this topic in class.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by shaikkhajaibrahim** [comment]
Use chef-supermarket cookbook chef-client
