### ISSUE TITLE
While creating jenkins node for hrmsqa agent is failing to get connect

### ISSUE THREAD

**Issue by Sumanth-lsvs** [QT-DevOps/DevOpsIssues#960]
While creating jenkins node for hrmsqa agent is failing to get connect and getting issue as

error message:-
[09/29/20 04:15:24] [SSH] SSH host key matches key in Known Hosts file. Connection will be allowed.
ERROR: Failed to authenticate as jenkins. Wrong password. (credentialId:try1/method:password)
[09/29/20 04:15:27] [SSH] Authentication failed.
Authentication failed.
[09/29/20 04:15:27] Launch failed - cleaning up connection
[09/29/20 04:15:27] [SSH] Connection closed.

![Screenshot (133)](https://user-images.githubusercontent.com/68912089/94512442-0737bb00-01ea-11eb-81c7-ab4a51f80998.png)

**Comment by puru7791** [comment]
try it manually i.e `ssh user-name@<node-ip>` if it works I'll establish a connection automatically when you relaunch the node

**Comment by Sumanth-lsvs** [comment]
still having the same issue
anyone please help me with this issue

**Comment by puru7791** [comment]
Did u configure SSH on Node ie `etc/ssh/sshd_config` before connecting node in jenkins

**Comment by Sumanth-lsvs** [comment]
yes i did
I searched the error in google
https://superuser.com/questions/1226069/configuring-jenkins-build-node-wrong-password
in the link he gave solution but what system preferences he is talking about, i didn't get it.

**Comment by puru7791** [comment]
Okay, do one thing, try this if it works then later relaunch the node 
1. Try to switch jenkins user on master node  and Type `ssh  <node-user name> <nodeip>` 
Ex: ssh node@192.0.0.0.

**Comment by shaikkhajaibrahim** [comment]
Hi Sumanth,
As i have said in the class if you are using known hosts verification strategy, you should try connecting from jenkins master to jenkins node.  This can be done after configuring /etc/ssh/sshd_config file after setting PasswordAuthentication to Yes (if you are using key based authentication)
So do the following 

1. ssh in to jenkins master, become a root user switch to jenkins
2. Now execute ssh jenkins@<jenkinsnodeip>
3. Now from jenkins ui configure the node.

Please watch & listen video carefully.

Once this works please close the issue

**Comment by Sumanth-lsvs** [comment]
Hi Sir,
 I tried 4 times by following the video but still, I am facing the same issue
![Screenshot (134)](https://user-images.githubusercontent.com/68912089/94606460-810e8980-0268-11eb-8b86-d195848dbebc.png)
I connected from jenkins master to node as shown above sir
I didn't even understand the error

**Comment by Sumanth-lsvs** [comment]
Hi sir
I resolvd the issue, thanks for your time
Purushotham B (puru7791) thanks for the suggestions
