### ISSUE TITLE
can't access sonarqube 

### ISSUE THREAD

**Issue by Sumanth-lsvs** [QT-DevOps/DevOpsIssues#967]
unable to load sonar webpage
![Screenshot (140)](https://user-images.githubusercontent.com/68912089/95144181-05b84680-0746-11eb-9900-6ae6869768d0.png)
![Screenshot (141)](https://user-images.githubusercontent.com/68912089/95144182-05b84680-0746-11eb-8511-ccf0f41736a5.png)

**Comment by shaikkhajaibrahim** [comment]
Is the port 8082,8081 opened?

**Comment by shaikkhajaibrahim** [comment]
Are the ports opened can you share the security group inbound rules

**Comment by Sumanth-lsvs** [comment]
![Screenshot (142)](https://user-images.githubusercontent.com/68912089/95407819-19051680-08ec-11eb-8be6-78343330daac.png)

**Comment by Sumanth-lsvs** [comment]
![Screenshot (140)_LI](https://user-images.githubusercontent.com/68912089/95408347-40a8ae80-08ed-11eb-8a0f-2534c4f3e728.jpg)
the underlined part from the above pic is the one line that I got different from the youtube video sir
I didn't understand what went wrong and I tried multiple times, I got that line differently all the times sir.
,

**Comment by shaikkhajaibrahim** [comment]
Sir is it a t2.micro?

**Comment by Sumanth-lsvs** [comment]
yes sir it is t2.micro
should i do it in t2.medium

**Comment by shaikkhajaibrahim** [comment]
Yes sir

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Sumanth-lsvs** [comment]
Thank you sir
