### ISSUE TITLE
terraform apply . 

### ISSUE THREAD

**Issue by thotagopi** [QT-DevOps/DevOpsIssues#970]
Hi sir when ever I run the terraform command life using this command terraform apply . getting this error
PS C:\Users\DELL> cd D:\terraform\TerraformZone\Oct20\helo.tf
PS D:\terraform\TerraformZone\Oct20\helo.tf> terraform apply .

Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
status code: 403, request id: 712adbeb-87c6-482d-80cf-c0edb4a267c1

please let me know where I am lacking

provider "aws" {
    region      = "us-west-2"
   }
resource "aws_s3_bucket" "mybucket" {
    bucket      = "terraformgopi"
    tags = {
    Name        = "My bucket"
    Environment = "Dev"
    CreatedBy   = "Terraform"
  }
}

**Comment by santhoshd402** [comment]
Please check syntax of secret key, please remove <,> before and after of secret key value  . and you will get this

**Comment by thotagopi** [comment]
> Please check syntax of secret key, please remove <,> before and after of secret key value . and you will get this

Thank you santhosh
