### ISSUE TITLE
Unable to create state file in backend using terraform apply command

### ISSUE THREAD

**Issue by prrohith** [QT-DevOps/DevOpsIssues#974]
Hi,

I wrote the below code for backend and created the required s3 bucket and dynamodb table for the terraform statefile. But I get the following error.

terraform {
    backend "s3" {
        bucket= "rohithterraformstate"
        key="global/ntier/terraform.tfstate"
        region="us-west-2"

        dynamodb_table="terraformlocktable"
          
    }
}

PS E:\Devops Job\Terraform_Packer\ntier_code> terraform apply .
Acquiring state lock. This may take a few moments...

Error: Error locking state: Error acquiring the state lock: 2 errors occurred:
        * ValidationException: One or more parameter values were invalid: Missing the key lockid in the item
        status code: 400, request id: 38RDO1M6UBOAQP3156S37IKP8RVV4KQNSO5AEMVJF66Q9ASUAAJG
        * ValidationException: The provided key element does not match the schema
        status code: 400, request id: BLLEF6MKPJ6L7DVNLKDKVFC3NBVV4KQNSO5AEMVJF66Q9ASUAAJG

Terraform acquires a state lock to protect the state from being written
by multiple users at the same time. Please resolve the issue above and try
again. For most commands, you can disable locking with the "-lock=false"
flag, but this is not recommended.

**Comment by santhoshd402** [comment]
make sure that your request mapping template structure matches the Amazon DynamoDB key structure...

and also run terraform init before apply.

Meanwhile i will check  and update you ... Reach me @7893532934

check LockID in dynamoDB table

**Comment by prrohith** [comment]
Hi,

I checked the template. It is correct as explained in the class. Also I ran
the init command before I ran the apply command.

Kind regards,
Rohith

**Comment by santhoshd402** [comment]
Hi rohith,

The script what you shared is perfectly working. i tried that with my credentials its absolutely working fine.
Crosscheck your work . if you got same issue . plz cal me @7893532934 we will discuss more about this.

**Comment by prrohith** [comment]
Earlier I created LockID as "lockid", which cause the issue. After checking with Santhosh, I changed the name to "LockID" again. It fixed the issue.
