### ISSUE TITLE
Facing issue while building my docker image

### ISSUE THREAD

**Issue by Pravin-Kumar-GitHub** [QT-DevOps/DevOpsIssues#979]
While building my docker image, don't know why I am seeing these lines (mentioned in Italic). I would like to know what causing to print these lines. To avoid those lines, I created new ec2 machine and then docker installation and again I build the below image. Then it works fine ! 
Any other way to resolve this issue and why it is occurring ?. Please assist.

Thanks in advance !

=> vi Dockerfile
FROM tomcat:8.5-jdk8-corretto
LABEL Pravin
ADD gameoflife.war /usr/local/tomcat/webapps/gameoflife.war
EXPOSE 8080
RUN ["catalina.sh", "run"]

=> docker build -t gol:1.0 .
O/P :-
Sending build context to Docker daemon  3.226MB
Step 1/5 : FROM tomcat:8.5-jdk8-corretto
8.5-jdk8-corretto: Pulling from library/tomcat
37373184fe69: Pull complete
de2752f6f919: Pull complete
5c4a711c48ae: Pull complete
89a451ce5bbd: Pull complete
2615fa0bb54c: Pull complete
Digest: sha256:2350f0795707561863321de54c3d956462766a93b864c8414989afe01630afd1
Status: Downloaded newer image for tomcat:8.5-jdk8-corretto
 ---> 4e54765f8ff8
Step 2/5 : LABEL Pravin
 ---> Running in 3f1a7674ecec
Removing intermediate container 3f1a7674ecec
 ---> 1d84c746a754
Step 3/5 : ADD gameoflife.war /usr/local/tomcat/webapps/gameoflife.war
 ---> 62e1c3bf842e
Step 4/5 : EXPOSE 8080
 ---> Running in c9623fa90ca1
Removing intermediate container c9623fa90ca1
 ---> 584ec3a26aad
Step 5/5 : RUN ["catalina.sh", "run"]
 ---> Running in 6365c56ff6c2
_18-Dec-2020 07:21:48.943 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/8.5.61
18-Dec-2020 07:21:48.950 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Dec 3 2020 14:03:28 UTC
18-Dec-2020 07:21:48.951 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 8.5.61.0
18-Dec-2020 07:21:48.952 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
18-Dec-2020 07:21:48.952 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.0-1029-aws
18-Dec-2020 07:21:48.953 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
18-Dec-2020 07:21:48.953 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-1.8.0-amazon-corretto/jre
18-Dec-2020 07:21:48.954 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_275-b01
18-Dec-2020 07:21:48.955 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Amazon.com Inc.
18-Dec-2020 07:21:48.955 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
18-Dec-2020 07:21:48.956 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
18-Dec-2020 07:21:48.956 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
18-Dec-2020 07:21:48.957 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
18-Dec-2020 07:21:48.959 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
18-Dec-2020 07:21:48.959 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
18-Dec-2020 07:21:48.960 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
18-Dec-2020 07:21:48.960 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
18-Dec-2020 07:21:48.965 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
18-Dec-2020 07:21:48.969 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
18-Dec-2020 07:21:48.970 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
18-Dec-2020 07:21:48.970 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.25] using APR version [1.6.3].
18-Dec-2020 07:21:48.971 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
18-Dec-2020 07:21:48.973 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
18-Dec-2020 07:21:48.978 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.0.2k-fips  26 Jan 2017]
18-Dec-2020 07:21:49.154 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
18-Dec-2020 07:21:49.189 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
18-Dec-2020 07:21:49.228 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1349 ms
18-Dec-2020 07:21:49.281 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
18-Dec-2020 07:21:49.285 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.61
18-Dec-2020 07:21:49.332 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/gameoflife.war]
18-Dec-2020 07:21:50.776 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
18-Dec-2020 07:21:50.906 INFO [localhost-startStop-1] org.springframework.web.servlet.FrameworkServlet.initServletBean FrameworkServlet 'gameoflife': initialization started
18-Dec-2020 07:21:50.951 INFO [localhost-startStop-1] org.springframework.context.support.AbstractApplicationContext.prepareRefresh Refreshing WebApplicationContext for namespace 'gameoflife-servlet': startup date [Fri Dec 18 07:21:50 UTC 2020]; root of context hierarchy
18-Dec-2020 07:21:51.019 INFO [localhost-startStop-1] org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions Loading XML bean definitions from ServletContext resource [/WEB-INF/gameoflife-servlet.xml]
18-Dec-2020 07:21:51.252 INFO [localhost-startStop-1] org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.registerDefaultFilters JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
18-Dec-2020 07:21:51.433 INFO [localhost-startStop-1] org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@5446f6cf: defining beans [homePageController,gameController,org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,view-Resolver]; root of factory hierarchy
18-Dec-2020 07:21:51.611 INFO [localhost-startStop-1] org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler Mapped URL path [/home] onto handler [com.wakaleo.gameoflife.webtests.controllers.HomePageController@70d75747]
18-Dec-2020 07:21:51.612 INFO [localhost-startStop-1] org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler Mapped URL path [/home.*] onto handler [com.wakaleo.gameoflife.webtests.controllers.HomePageController@70d75747]
18-Dec-2020 07:21:51.619 INFO [localhost-startStop-1] org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler Mapped URL path [/home/] onto handler [com.wakaleo.gameoflife.webtests.controllers.HomePageController@70d75747]
18-Dec-2020 07:21:51.620 INFO [localhost-startStop-1] org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler Root mapping to handler [com.wakaleo.gameoflife.webtests.controllers.HomePageController@70d75747]
18-Dec-2020 07:21:51.621 INFO [localhost-startStop-1] org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler Mapped URL path [/game/new] onto handler [com.wakaleo.gameoflife.webtests.controllers.GameController@def3e62]
18-Dec-2020 07:21:51.622 INFO [localhost-startStop-1] org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler Mapped URL path [/game/new.*] onto handler [com.wakaleo.gameoflife.webtests.controllers.GameController@def3e62]
18-Dec-2020 07:21:51.623 INFO [localhost-startStop-1] org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler Mapped URL path [/game/new/] onto handler [com.wakaleo.gameoflife.webtests.controllers.GameController@def3e62]
18-Dec-2020 07:21:51.623 INFO [localhost-startStop-1] org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler Mapped URL path [/game/start] onto handler [com.wakaleo.gameoflife.webtests.controllers.GameController@def3e62]
18-Dec-2020 07:21:51.624 INFO [localhost-startStop-1] org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler Mapped URL path [/game/start.*] onto handler [com.wakaleo.gameoflife.webtests.controllers.GameController@def3e62]
18-Dec-2020 07:21:51.625 INFO [localhost-startStop-1] org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler Mapped URL path [/game/start/] onto handler [com.wakaleo.gameoflife.webtests.controllers.GameController@def3e62]
18-Dec-2020 07:21:51.625 INFO [localhost-startStop-1] org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler Mapped URL path [/game/next] onto handler [com.wakaleo.gameoflife.webtests.controllers.GameController@def3e62]
18-Dec-2020 07:21:51.626 INFO [localhost-startStop-1] org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler Mapped URL path [/game/next.*] onto handler [com.wakaleo.gameoflife.webtests.controllers.GameController@def3e62]
18-Dec-2020 07:21:51.627 INFO [localhost-startStop-1] org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler Mapped URL path [/game/next/] onto handler [com.wakaleo.gameoflife.webtests.controllers.GameController@def3e62]
18-Dec-2020 07:21:51.904 INFO [localhost-startStop-1] org.springframework.web.servlet.FrameworkServlet.initServletBean FrameworkServlet 'gameoflife': initialization completed in 998 ms
18-Dec-2020 07:21:51.932 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/gameoflife.war] has finished in [2,599] ms
18-Dec-2020 07:21:51.935 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
18-Dec-2020 07:21:51.970 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 2738 ms_

**Comment by Pravin-Kumar-GitHub** [comment]
Sorry.. It's my typo mistake.. In my Dockerfile, instead of CMD, I gave as RUN.. I believe that's why I am seeing these lines (mentioned in Italic). Please share your inputs.

Thanks again !!

Revised Dockerfile
=> vi Dockerfile
FROM tomcat:8.5-jdk8-corretto
LABEL Pravin
ADD gameoflife.war /usr/local/tomcat/webapps/gameoflife.war
EXPOSE 8080
CMD ["catalina.sh", "run"]

**Comment by santhoshd402** [comment]
Is the issue cleared or still facing issue...

**Comment by Pravin-Kumar-GitHub** [comment]
It's cleared..
Closing this issue..
