### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by kuncham405** [QT-DevOps/DevOpsIssues#98]
Hi Sir,

Am not able to create the file at chef server, but able to install the application's ( Git,Java,)

While doing "Berks install" it is fine, but while doing "berks upload" for the same cookbook to upload the file, "it is showing frozen (0.1.0), need your help on this.

**Comment by shaikkhajaibrahim** [comment]
Change version of cookbook in metadata.rb file & then do Berks upload

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kuncham405** [comment]
i got it sir, thank you
