### ISSUE TITLE
error in validating providing crendentials

### ISSUE THREAD

**Issue by prashanth-1212** [QT-DevOps/DevOpsIssues#989]
error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: SignatureDoesNotMatch: Signature not yet current: 20210112T194419Z is still later than 20210112T072625Z (20210112T071125Z + 15 min.)
        status code: 403, request id: 374a9d87-2bb7-4cbe-bb01-3b1a9cc7b20b

**Comment by santhoshd402** [comment]
please elaborate issue
provide script screenshot 
or else reach me whatsapp we can solve each other in the remote
