### ISSUE TITLE
TFS Upgrade

### ISSUE THREAD

**Issue by jyothsnagali** [QT-DevOps/DevOpsIssues#99]
Hello Sir, 
First of all, Thanks a lot for being an awesome teacher. 
I am looking for help in Upgrading TFS. 

In our Organization, we are using TFS 2017.1 in Windows Server 2008 with SQL 2014. 
We are planning to upgrade to TFS 2018, where minimum requirement of OS is Windows Server 2012.
So, We have got our servers ready with Windows Server 2016 and SQL 2016 installed. 

Can you please help me with steps on how to move our TFS Instance to this new server and then Upgrade to TFS 2018. Thanks

- Jyothsna

**Comment by raviops100** [comment]
Hi Jyothsna,

Please go for below link hope this helps to achive requirement.
https://www.edrockwell.com/blog/upgrade-tfs-2017-to-tfs-2018-walkthrough/

**Comment by jyothsnagali** [comment]
Yes. I Have referred it. 
As we are changing our infrastructure first, then upgrade. Do you have any steps for moving our TFS instances to other Servers?

**Comment by shaikkhajaibrahim** [comment]
Hi jyoshna,
TFS is not our expertise, but TFS will have replication options, refer them in msdn

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
