### ISSUE TITLE
docker container are running but not accessible in browser it showing error 404 docker installed on aws ubuntu

### ISSUE THREAD

**Issue by prashanth-1212** [QT-DevOps/DevOpsIssues#993]
docker run tomcat is worked only after doing
docker pull tomcat:latest
docker run -d --name mytomcat -p 8080:8080 tomcat:latest
docker exec -it mytomcat /bin/bash
mv webapps webapps2
mv webapps.dist/ webapps
exit
but docker run nginx is not working
docker run hello-world-python is not working
all containers are running in cli but not accessiable in browse how to fix this

**Comment by santhoshd402** [comment]
Bro cal me on whatsapp we will solve Issue on remote...
I seen you have lot issues we will solve all...
Cal me on whatsapp

**Comment by prashanth-1212** [comment]
plz send your number

**Comment by santhoshd402** [comment]
If you read entire mail... You can see lab assistant number... 
Please reach me on whatsapp same number

**Comment by prashanth-1212** [comment]
okay
