### ISSUE TITLE
error during excuting kitchen create

### ISSUE THREAD

**Issue by Reddy-hub-sudo** [QT-DevOps/DevOpsIssues#994]
![error kitchen create](https://user-images.githubusercontent.com/77826063/105457127-4cf22500-5cac-11eb-899d-59bb8a43ae47.jpg)
Dear sir
can anyone explain the reason behind this error (waiting for SSH service.................retrying in 3 sec)

**Comment by santhoshd402** [comment]
Solved right...
Please close issue
