### ISSUE TITLE
centos-7 kitchen create error

### ISSUE THREAD

**Issue by Reddy-hub-sudo** [QT-DevOps/DevOpsIssues#995]
![centos-7 error](https://user-images.githubusercontent.com/77826063/105727089-babe7b00-5f50-11eb-8c00-e9934c6d325d.png)

can anyone tell me why this error is occurring.

**Comment by bhaskardegala** [comment]
Hi Reddy, 
Nothing wrong with chef , just follow the instructions given by aws (from logs), you need to accept terms and subscribe

**Comment by Reddy-hub-sudo** [comment]
If you time. Can we try to through screen sharing..iam unable to do
