### ISSUE TITLE
tomcat kitchen converge error in chef

### ISSUE THREAD

**Issue by Reddy-hub-sudo** [QT-DevOps/DevOpsIssues#997]
![tomcat error](https://user-images.githubusercontent.com/77826063/105969414-3e41ae80-60ae-11eb-8b24-7e45acc14628.png)

can anyone help me. why this error is coming

**Comment by bhaskardegala** [comment]
Hi Reddy, 
From logs it stats that Tomcat group already exists, and my guess was you are using shell/command instead of chef resource. So try using "group" resource so that it will not fail if group exists due to idempotency

**Comment by Reddy-hub-sudo** [comment]
when we are creating centos-7 for the First time we have to create manually. then it won't ask again for a subscription while using CLI commands.
