### ISSUE TITLE
ansible playbook error

### ISSUE THREAD

**Issue by venugopalkatukam** [QT-DevOps/DevOpsIssues#998]
unable to install tomcat with ansible playbook
![ansible](https://user-images.githubusercontent.com/49026727/106047415-9954bf00-6109-11eb-94a8-a30fff51ddbd.PNG)

**Comment by santhoshd402** [comment]
Please check the file url

**Comment by bhaskardegala** [comment]
Hi venu,

I guess you are using unarchive module for unzipping the file, and by default ansible tries to find the file on control server but in our case you have file in remote server (node). So try adding "remote_src=yes" parameter to the module so it will search for the file on remote server
